- clippy_lints/src/transmute/transmute_null_to_fn.rs
- tests/ui/transmute_null_to_fn.rs
- tests/ui/transmute_null_to_fn.stderr
fixes: #11485 
changelog: trigger [`transmute_null_to_fn`] on chain of casts
> trigger [`transmute_null_to_fn`] on chain of casts

- clippy_lints/src/unit_types/let_unit_value.rs
- tests/ui/let_unit.fixed
- tests/ui/let_unit.rs
changelog: [`let_unit_value`]: fix the FalsePostive on async fn arguments
fix #11502
> fix FP of let_unit_value on async fn args

- clippy_lints/src/matches/redundant_guards.rs
- tests/ui/redundant_guards.fixed
- tests/ui/redundant_guards.rs
- tests/ui/redundant_guards.stderr
changelog: [`redundant_guards`]: Now checks if the variable is bound using `ref` before linting.
The lint should not be emitted, when the local variable is bind by-ref in the pattern.
fixes #11465
> add extra `byref` checking for the guard's local

- clippy_lints/src/misc.rs
- clippy_utils/src/lib.rs
- tests/ui/used_underscore_binding.rs
- tests/ui/used_underscore_binding.stderr
Fixes #11520
Fixes #947
Also ignores usages of `PhantomData`
> used_underscore_bindings: respect lint levels on the binding definition

- clippy_lints/src/casts/cast_possible_truncation.rs
- tests/ui/cast.rs
changelog: Fix the ICE in [`cast_possible_truncation`], when the `Shr` bits is larger than `u64::MAX`
fix #11426
> fix ICE by `u64::try_from(<u128>)`

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/methods/mod.rs
- clippy_lints/src/methods/redundant_as_str.rs
- tests/ui/redundant_as_str.fixed
- tests/ui/redundant_as_str.rs
- tests/ui/redundant_as_str.stderr
This lint checks for `as_str` on a `String` immediately followed by `as_bytes` or `is_empty` as those methods are available on `String` too. This could possibly also be extended to `&[u8]` in the future.
changelog: New lint [`redundant_as_str`] #11526
> Add redundant_as_str lint

- clippy_lints/src/casts/cast_lossless.rs
- tests/ui/cast_lossless_integer.fixed
- tests/ui/cast_lossless_integer.rs
- tests/ui/cast_lossless_integer.stderr
changelog: fix [`cast_lossless`] in the case when the cast operand is a macro call
fix #11458
> fix cast_lossless with macro call

- clippy_lints/src/needless_pass_by_ref_mut.rs
- tests/ui/needless_pass_by_ref_mut.rs
- tests/ui/needless_pass_by_ref_mut.stderr
Fixes https://github.com/rust-lang/rust-clippy/issues/11380.
The problem was that it needed to go through closures as well in async functions to correctly find the mutable usage of async function arguments.
changelog: Correctly handle mutable usage of async function arguments in closures.
r? @Centri3
> Fix mutaby used async function argument in closure for `needless_pass_by_ref_mut`

- clippy_lints/src/matches/redundant_guards.rs
- tests/ui/redundant_guards.fixed
- tests/ui/redundant_guards.rs
- tests/ui/redundant_guards.stderr
A tiny improvement to the `redundant_guards` lint. There's no associated issue for this, just noticed it while going through the code.
Right now it warns on `Some(x) if x == 2` and suggests `Some(2)`, but it didn't do that for `Some(x) if 2 == x` (i.e. when the local is on the right side and the pattern on the left side).
changelog: [`redundant_guards`]: also lint if the pattern is on the left side
> [`redundant_guards`]: lint if the pattern is on the left side

- clippy_lints/src/needless_pass_by_ref_mut.rs
- tests/ui/needless_pass_by_ref_mut.rs
- tests/ui/needless_pass_by_ref_mut.stderr
changelog: [`needless_pass_by_ref mut`]: fixes false positive caused by not covering mutable references passed to a closure inside of a fuction
fixes #11545
> fixed fp caused by moving &mut reference inside of a closure

- clippy_lints/src/large_futures.rs
The value used in the large_futures example was not large enough to trigger the lint given the default threshold. The example also contained more code than necessary. This PR changes the value size from 1kB to 16kB and reduces the example in size.
changelog: [`large_futures`]: Fix and simplify example
> Fix large_futures example

- clippy_lints/src/enum_variants.rs
- tests/ui-toml/enum_variants_threshold0/clippy.toml
- tests/ui-toml/enum_variants_threshold0/enum_variants_name_threshold.rs
changelog: [`enum_variant_names`]: prevent ice when threshold is 0 and enum has no variants
r? @y21 
Fixes the same ice issue raised during review of https://github.com/rust-lang/rust-clippy/pull/11496
> prevent ice when threshold is 0 and enum has no variants

- Cargo.toml
- src/driver.rs
- src/main.rs
On rust-lang/cargo#12578, a new colored help message format was introduced. This PR introduces the same styling from that `cargo help` message to our `cargo clippy --help` message.
More information is provided in the original PR, fixes #11482. The perfect reviewing process would be that the reviewer installs this branch and checks for themselves, but here are some screenshots, there are some more screenshots in the original issue.
(Note that the actual text may change in the actual commit, that screenshot is just to test the colors).
Also note that the `color-print` version **should always** be synced with Cargo's `color-print` version to avoid increasing build times in the rust-lang/rust repo.
changelog:Add colors to the `cargo clippy --help` output :tada:.
> Add colored help to be consistent with Cargo

- clippy_lints/Cargo.toml
- clippy_lints/src/utils/conf.rs
Inspired by #11560, adds a test that each config option exists in some form in a `clippy.toml` in `tests/` (currently some are in `ui-toml`, some in `ui-cargo`)
> Test that each config value exists in a test clippy.toml

- clippy_lints/src/wildcard_imports.rs
- tests/ui/wildcard_imports.fixed
- tests/ui/wildcard_imports.rs
- tests/ui/wildcard_imports.stderr
- tests/ui/wildcard_imports_2021.edition2018.fixed
- tests/ui/wildcard_imports_2021.edition2018.stderr
- tests/ui/wildcard_imports_2021.edition2021.fixed
- tests/ui/wildcard_imports_2021.edition2021.stderr
- tests/ui/wildcard_imports_2021.rs
fix https://github.com/rust-lang/rust-clippy/issues/9942
changelog: [`wildcard_imports`]: No longer lints when imported items contain an item with the name `_`
> Do not lint when imported item contains underscore

- clippy_lints/src/missing_assert_message.rs
Updates `missing_assert_message`'s docs to reflect that it ignores test functions as pointed out by @mickvangelderen in https://github.com/rust-lang/rust-clippy/pull/10362#issuecomment-1732288652
---
changelog: [`missing_assert_message`]: Update docs to reflect this lint ignores test functions
> Mention that `missing_assert_message` lint ignores test functions

- clippy_lints/src/raw_strings.rs
IMO it doesn't improve code enough to be warn by default. [It seems to be unclear to some also](https://github.com/rust-lang/rust-clippy/issues/11402), but that can probably be remedied separately
changelog: Moved [`needless_raw_string_hashes`] to `pedantic` (Now allow-by-default)
[#11415](https://github.com/rust-lang/rust-clippy/pull/11415)
r? @flip1995
> Move `needless_raw_string_hashes` to `pedantic`

- clippy_lints/src/write.rs
- tests/ui/print_literal.fixed
- tests/ui/print_literal.rs
- tests/ui/print_literal.stderr
- tests/ui/write_literal.fixed
- tests/ui/write_literal.rs
- tests/ui/write_literal.stderr
- tests/ui/write_literal_2.rs
- tests/ui/write_literal_2.stderr
- fixes https://github.com/rust-lang/rust-clippy/issues/10128
- `clippy --fix` replaces multiple warnings at once
e.g.) 
```rust
writeln!(v, "{0} {1}", "hello", "world");
// before: `writeln!(v, "hello {1}", "world");`
// now: `writeln!(v, "hello world");`
```
changelog: [`print_literal`], [`write_literal`]: Now handles positional argument properly
> write_literal: Fix index of the remaining positional arguments

- clippy_lints/src/enum_clike.rs
- clippy_lints/src/matches/overlapping_arms.rs
- clippy_utils/src/consts.rs
- clippy_utils/src/lib.rs
This simplifies some code and also fixes the float array handling to properly take into account the `offset`, and to work with little-endian targets.
Fixes https://github.com/rust-lang/rust-clippy/issues/11488
> mir_to_const improvements

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/iter_without_into_iter.rs
- clippy_lints/src/lib.rs
- tests/ui/iter_without_into_iter.rs
- tests/ui/iter_without_into_iter.stderr
Closes #9736
A new lint that looks for `iter` (and `iter_mut`) method implementations without the type implementing `IntoIterator` for `&Type`.
Imo this seems rather pedantic, so I went with that, but I can be convinced to change it to `style` like the linked issue asked for.
Writing a machine applicable suggestion seems a bit tricky and tedious, so for now this relies on the user adding remaining lifetimes.
changelog: new lint: `iter_without_into_iter`
> new lint: `iter_without_into_iter`

- clippy_lints/src/allow_attributes.rs
- clippy_lints/src/methods/mod.rs
Discovered in https://github.com/rust-lang/rust-analyzer/pull/15680/files#diff-7cb229b5139c72b6c230e3c195be375724c92226421fd57d5cf08872503e8c27L214-R226
> Add missing lint description headers

- clippy_lints/src/manual_let_else.rs
- tests/ui/manual_let_else_match.fixed
- tests/ui/manual_let_else_match.rs
- tests/ui/manual_let_else_match.stderr
Fixes #11579.
The lint already had logic for omitting a block in `else` if a block is already present, however this didn't handle the case where the block is from a different expansion/syntax context. E.g.
```rs
macro_rules! panic_in_block {
() => { { panic!() } }
}
let _ = match Some(1) {
Some(v) => v,
_ => panic_in_block!()
};
```
It would see this in its expanded form as `_ => { panic!() }` and think it doesn't have to include a block in its suggestion because it is already there, however that's not true if it's from a different expansion like in this case.
changelog: [`manual_let_else`]: only omit block in suggestion if the block is from the same expansion
> [`manual_let_else`]: only omit block if span is from same ctxt

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/iter_without_into_iter.rs
- tests/ui/into_iter_without_iter.rs
- tests/ui/into_iter_without_iter.stderr
Closes #9736 (part 2)
This implements the other lint that my earlier PR missed: given an `IntoIterator for &Type` impl, check that there exists an inherent `fn iter(&self)` method.
changelog: new lint: `into_iter_without_iter`
r? @Jarcho since you reviewed #11527 I figured it makes sense for you to review this as well?
> new lint: `into_iter_without_iter`

- clippy_lints/src/manual_non_exhaustive.rs
- tests/ui/manual_non_exhaustive_enum.rs
- tests/ui/manual_non_exhaustive_enum.stderr
Fixes #11583
changelog: Fix [`manual_non_exhaustive`] false positive for unit enum variants when enum is explicitly `non_exhaustive`.
> Don't lint `manual_non_exhaustive` when enum is `#[non_exhaustive]`

- book/src/development/adding_lints.md
The file pointed to by the old link
https://github.com/rust-lang/rust-clippy/blob/557f6848bd5b7183f55c1e1522a326e9e1df6030/clippy_lints/src/lib.rs#L110
did not talk about categories and levels.
The new link (hopefully) points here
https://doc.rust-lang.org/stable/clippy/
which has a nice table explaining the mappings.
> Fix documentation link

- clippy_lints/src/implicit_hasher.rs
- fixes #10511 
I checked [the reported repository](https://github.com/rust-lang/rust-clippy/issues/10511#issuecomment-1474271205) and found that clippy hangs at [py_sync.rs#L85](https://github.com/rigetti/qcs-sdk-rust/blob/842094068ed6174ba08b52a2fbae39dda77cbd00/crates/python/src/py_sync.rs#L85), where a macro(`py_function_sync_async`) defines type parameters. this macro is used in the same crate, so `in_external_macro` wouldn't catch them.
This PR fixes the problem by using `Span#from_expansion`.
---
changelog: ICE: [`implicit_hasher`]: No longer lints inside macros, which could cause ICEs
[#11593](https://github.com/rust-lang/rust-clippy/pull/11593)
> Use Span#from_expansion instead of in_external_macro

- clippy_lints/src/write.rs
- tests/ui/print_literal.fixed
- tests/ui/print_literal.rs
- tests/ui/print_literal.stderr
> Don't escape unicode escape braces in `print_literal`

- clippy_lints/src/needless_pass_by_ref_mut.rs
- tests/ui/infinite_loop.rs
- tests/ui/infinite_loop.stderr
- tests/ui/let_underscore_future.rs
- tests/ui/let_underscore_future.stderr
- tests/ui/mut_key.rs
- tests/ui/mut_key.stderr
- tests/ui/mut_reference.rs
- tests/ui/mut_reference.stderr
- tests/ui/needless_pass_by_ref_mut.rs
- tests/ui/needless_pass_by_ref_mut.stderr
- tests/ui/should_impl_trait/method_list_2.rs
- tests/ui/should_impl_trait/method_list_2.stderr
- tests/ui/slow_vector_initialization.rs
- tests/ui/slow_vector_initialization.stderr
[Related to [this Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/needless_pass_by_ref_mut.20isn't.20ready.20for.20stable)]
`needless_pass_by_ref_mut` has been released with some important bugs (notably having a lot of reported false positives and an ICE). So it may not be really ready for being in stable until these problems are solved. This PR changes the lint's category from `suspicious` to `nursery`, just that.
> Move `needless_pass_by_ref_mut`: `suspicious` -> `nursery`

- clippy_lints/src/std_instead_of_core.rs
- tests/ui/auxiliary/proc_macro_derive.rs
- tests/ui/std_instead_of_core.fixed
- tests/ui/std_instead_of_core.rs
- tests/ui/std_instead_of_core.stderr
- fixes https://github.com/rust-lang/rust-clippy/issues/10198
note: The lint for the reported `thiserror::Error` has been suppressed by [Don't lint unstable moves in std_instead_of_core](https://github.com/rust-lang/rust-clippy/pull/9545/files#diff-2cb8a24429cf9d9898de901450d640115503a10454d692dddc6a073a299fbb7eR29) because `thiserror::Error`  internally implements `std::error::Error for (derived struct)`.
changelog: [`std_intead_of_core`]: avoid linting inside proc-macro
I confirmed this change fixes the problem:
<details>
<summary>test result without the change</summary>
```console
error: used import from `std` instead of `core`
--> tests/ui/std_instead_of_core.rs:65:14
|
LL |     #[derive(ImplStructWithStdDisplay)]
|              ^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: this error originates …
```
> std_instead_of_core: avoid lint inside of proc-macro

- clippy_lints/src/ignored_unit_patterns.rs
- tests/ui/auxiliary/proc_macro_derive.rs
- tests/ui/ignored_unit_patterns.fixed
- tests/ui/ignored_unit_patterns.rs
- tests/ui/ignored_unit_patterns.stderr
Fixes https://github.com/rust-lang/rust-clippy/issues/11601
The reported problem occured in [a derive macro](https://github.com/mpalmer/ct-structs/actions/runs/6386980382/job/17334587328#step:6:239). This PR avoid linting in macros.
changelog: [`ignored_unit_patterns`] No longer lints inside macro definitions
> Avoid invoking `ignored_unit_patterns` in macro definition

- clippy_lints/src/redundant_locals.rs
- tests/ui/redundant_locals.rs
- tests/ui/redundant_locals.stderr
Fixes https://github.com/rust-lang/rust-clippy/issues/11599
changelog: [`redundant_locals`] No longer lints which implements Drop trait to avoid reordering
> Fix: avoid changing drop order

- clippy_lints/src/items_after_test_module.rs
- clippy_utils/src/lib.rs
- tests/ui/items_after_test_module/after_proc_macros.rs
- tests/ui/items_after_test_module/auxiliary/submodule.rs
- tests/ui/items_after_test_module/block_module.stderr
- tests/ui/items_after_test_module/in_submodule.rs
- tests/ui/items_after_test_module/in_submodule.stderr
- tests/ui/items_after_test_module/multiple_modules.rs
- tests/ui/items_after_test_module/root_module.fixed
- tests/ui/items_after_test_module/root_module.rs
- tests/ui/items_after_test_module/root_module.stderr
Fixes #11050
Fixes #11153
changelog: [`items_after_test_module`]: Now suggests a machine-applicable suggestion.
changelog: [`items:after_test_module`]: Also lints for non root modules
> Fix `items_after_test_module` for non root modules, add applicable suggestion

- clippy_lints/src/redundant_locals.rs
- tests/ui/redundant_locals.stderr
Fixes #11625
AFAIK, `span_lint_and_help` points the beginning of spans when we pass multiple spans to the second argument, so This PR I also modified its help span and its message.
lint result of the given example in the issue will be:
```console
error: redundant redefinition of a binding `apple`
--> src/main.rs:5:5
|
5 |     let apple = apple;
|     ^^^^^^^^^^^^^^^^^^
|
help: `apple` is initially defined here
--> src/main.rs:4:9
|
4 |     let apple = 42;
|         ^^^^^
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_locals
```
I hope that this change might help reduce user confusion, but I'd appreciate alternative suggestions:)
changelog: [`redundant_locals`]: Now points at the rebinding of the variable
> Improve `redundant_locals` help message

- clippy_lints/src/redundant_locals.rs
- tests/ui/redundant_locals.rs
- tests/ui/redundant_locals.stderr
Fixes #11619 
Rebinding over macro like the code below, idents will be different (`x#4` and `x#0` in that case).
```rust
fn reassign_in_macro() {
let x = 10;
macro_rules! mac {
($i:ident) => {
let mut x = x;
}
}
mac!(y);
}
```
It causes unwrapping `None`. 
https://github.com/rust-lang/rust-clippy/blob/9554e477c29e6ddca9e5cdce71524341ef9d48e8/clippy_lints/src/redundant_locals.rs#L88-L98
changelog: ICE: [`redundant_locals`]: No longer lints rebinding over macro
> Fix ice in `redundant_locals`

- clippy_lints/src/iter_without_into_iter.rs
- tests/ui/into_iter_without_iter.rs
Fixes #11635
changelog: [`into_iter_without_iter`]: walk up deref impl chain to find `iter` methods
> [`into_iter_without_iter`]: walk up deref impl chain to find `iter` methods

- Cargo.toml
- tests/compile-test.rs
Hopefully fixes #11489
r? @flip1995
> Update ui_test to 0.21.2

- clippy_lints/src/manual_is_ascii_check.rs
- tests/ui/manual_is_ascii_check.fixed
- tests/ui/manual_is_ascii_check.rs
- tests/ui/manual_is_ascii_check.stderr
changelog: [`manual_is_ascii_check`]: Also check for `is_ascii_hexdigt`
> [`manual_is_ascii_check`]: Also check for `is_ascii_hexdigt`

- clippy_lints/src/loops/same_item_push.rs
- clippy_lints/src/manual_bits.rs
- clippy_lints/src/methods/get_first.rs
- clippy_lints/src/methods/search_is_some.rs
- clippy_lints/src/missing_doc.rs
- clippy_lints/src/needless_continue.rs
- clippy_lints/src/slow_vector_initialization.rs
- clippy_lints/src/uninit_vec.rs
- clippy_lints/src/unnecessary_map_on_constructor.rs
- clippy_utils/src/consts.rs
- clippy_utils/src/higher.rs
- tests/ui/get_first.fixed
- tests/ui/get_first.rs
- tests/ui/get_first.stderr
Fixes #11594
I left the issue open for a couple days before making the PR to see if anyone has something to say, but it looks like there aren't any objections to removing this check that prevented linting on non-primitive slices, so here's the PR now.
There's a couple of instances in clippy itself where we now emit the lint. The actual relevant change is in the first commit and fixing the `.get(0)` instances in clippy itself is in the 2nd commit.
changelog: [`get_first`]: lint on non-primitive slices
> [`get_first`]: lint on non-primitive slices

- triagebot.toml
https://github.com/rust-lang/triagebot/pull/1720
> triagebot no-merges: exclude "Rustup"s, add labels

- book/src/development/adding_lints.md
Documents the outcome described in https://github.com/rust-lang/rust-clippy/issues/11662 so that the situation can be avoided in the future by other individuals.
> Document conflicting lints

- clippy_lints/src/methods/unnecessary_lazy_eval.rs
- tests/ui/unnecessary_lazy_eval.fixed
- tests/ui/unnecessary_lazy_eval.rs
- tests/ui/unnecessary_lazy_eval.stderr
- tests/ui/unnecessary_lazy_eval_unfixable.rs
- tests/ui/unnecessary_lazy_eval_unfixable.stderr
Fixes #11672 
We already check if closure parameters don't have type annotations and reduce the applicability to `MaybeIncorrect` if they do, since those help type inference and removing them breaks code. We didn't do this for return type annotations however. This PR adds it. This doesn't change it to produce a fix that will compile, but it will prevent rustfix from auto-applying it.
(In general I'm not sure if we can suggest a fix that will compile. In this specific example, it might be possible to suggest `&[] as &[u8]`, but as-casts won't always work, e.g. `Default::default() as &[u8]` is a compile error, so just reducing applicability should be a safe fix in any case for now)
changelog: [`unnecessary_lazy_eval`]: reduce applicability to `MaybeIncorrect` if closure has return type …
> [`unnecessary_lazy_eval`]: reduce applicability if closure has return type annotation

- clippy_lints/src/multiple_unsafe_ops_per_block.rs
- tests/ui/multiple_unsafe_ops_per_block.rs
The await desugaring contains two calls (`Poll::new_unchecked` and `get_context`) inside a single unsafe block. That violates the lint.
fixes #11312
changelog: [`multiple_unsafe_ops_per_block`]: fix false positives in `.await`
> Make `multiple_unsafe_ops_per_block` ignore await desugaring

- tests/ui/needless_pass_by_ref_mut.rs
Fixes https://github.com/rust-lang/rust-clippy/issues/11610.
This was already fixed. I simply added a regression test.
changelog: Add regression test for #11610 about mutable usage of argument in async function for the `needless_pass_by_ref_mut` lint
> Add regression test for #11610 about mutable usage of argument in async function for the `needless_pass_by_ref_mut` lint

- clippy_lints/src/needless_pass_by_ref_mut.rs
- tests/ui/needless_pass_by_ref_mut.rs
Fixes https://github.com/rust-lang/rust-clippy/issues/11586.
Fixes https://github.com/rust-lang/rust-clippy/issues/11180.
As suggested in the two issues above, this lint should not be emitted if this an unsafe function or if the argument is used in an unsafe block.
changelog: [`needless_pass_by_ref_mut`]: Don't emit if the variable is used in an unsafe block or function
> Don't emit `needless_pass_by_ref_mut` if the variable is used in an unsafe block or function

- book/src/lint_configuration.md
- clippy_lints/src/lib.rs
- clippy_lints/src/matches/mod.rs
- clippy_lints/src/use_self.rs
- clippy_lints/src/utils/conf.rs
- clippy_utils/Cargo.toml
- clippy_utils/src/msrvs.rs
- src/driver.rs
- tests/ui-toml/invalid_min_rust_version/invalid_min_rust_version.rs
- tests/ui-toml/invalid_min_rust_version/invalid_min_rust_version.stderr
Gives the error a span pointing to the invalid config value
Also puts `Conf` itself in the `OnceLock` rather than just the `Msrv` for [the `register_late_mod_pass` work](https://github.com/rust-lang/rust/pull/116731) since it will be used from two different callbacks
> Deserialize `Msrv` directly in `Conf`

- clippy_lints/src/methods/filter_map_identity.rs
- clippy_lints/src/methods/flat_map_identity.rs
- clippy_lints/src/methods/map_identity.rs
- clippy_utils/src/lib.rs
- tests/ui/map_identity.fixed
- tests/ui/map_identity.rs
Fixes #9122
`.map(|a: u32| a)` can help type inference, so we should probably allow this and not warn about "unnecessary map of the identity function"
changelog: [`map_identity`]: allow closure with type annotations
> [`map_identity`]: allow closure with type annotations

- clippy_lints/src/lib.rs
- clippy_lints/src/non_copy_const.rs
- tests/ui-toml/borrow_interior_mutable_const/clippy.toml
- tests/ui-toml/borrow_interior_mutable_const/ignore.rs
- tests/ui-toml/declare_interior_mutable_const/clippy.toml
- tests/ui-toml/declare_interior_mutable_const/ignore.rs
Fix #10537
changelog: Now `declare_interior_mutable_const` and `borrow_interior_mutable_const` respect the `ignore-interior-mutability` configuration entry
> Now `declare_interior_mutable_const` and `borrow_interior_mutable_const` respect the `ignore-interior-mutability` configuration entry

- clippy_lints/src/missing_enforced_import_rename.rs
Similar to https://github.com/rust-lang/rust-clippy/pull/8261 that did the same thing to disallowed_methods & disallowed_types.
This lint is also only triggered if import renames are defined in the `clippy.toml` file.
changelog: Moved [`missing_enforced_import_renames`] to `style` (Now warn-by-default)
[#11539](https://github.com/rust-lang/rust-clippy/pull/11539)
> Warn missing_enforced_import_renames by default

- clippy_utils/src/lib.rs
- lintcheck/src/main.rs
- tests/ui/map_identity.fixed
- tests/ui/map_identity.rs
- tests/ui/map_identity.stderr
Fixes #7189
This lint now recognizes `.map(|(a, b)| (a, b))` as a useless `map` call.
changelog: [`map_identity`]: recognize tuple identity function
> [`map_identity`]: recognize tuple identity function

- clippy_lints/src/if_not_else.rs
- tests/ui/if_not_else_bittest.rs
Currently, clippy makes unhelpful suggestions such as this:
```
warning: unnecessary `!=` operation
--> src/vm.rs:598:36
|
598 |                     *destination = if source & 0x8000 != 0 { 0xFFFF } else { 0 };
|                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: change to `==` and swap the blocks of the `if`/`else`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#if_not_else
= note: `-W clippy::if-not-else` implied by `-W clippy::pedantic`
```
Bit tests often take on the form `if foo & 0x1234 != 0 { … } else { … }`, and the `!= 0` part reads as "has any bits set". Therefore, this code already has the "correct" order, and shouldn't be changed.
This PR disables the lint for these cases, and in fact all …
> Skip if_not_else lint for '!= 0'-style checks

- clippy_lints/src/option_if_let_else.rs
- tests/ui/option_if_let_else.fixed
- tests/ui/option_if_let_else.rs
- tests/ui/option_if_let_else.stderr
fixes: #11429 
changelog: suggest passing function instead of calling it in closure for [`option_if_let_else`]
> suggest passing function instead of calling it in closure for [`option_if_let_else`]

- clippy_lints/src/returns.rs
- tests/ui/let_and_return.fixed
- tests/ui/let_and_return.rs
- tests/ui/let_and_return.stderr
- fixes https://github.com/rust-lang/rust-clippy/issues/11335
changelog: [`let_and_return`]: Wrap suggestion with parenthesis if necessary
r? @Centri3
> let_and_return: Wrap with parenthesis if necessary

- clippy_dev/src/main.rs
- clippy_dev/src/update_lints.rs
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/utils/author.rs
- clippy_lints/src/utils/dump_hir.rs
- clippy_lints/src/utils/internal_lints.rs
- clippy_lints/src/utils/internal_lints/metadata_collector.rs
- clippy_lints/src/utils/internal_lints/unsorted_clippy_utils_paths.rs
- declare_clippy_lint/src/lib.rs
`LINT_AUTHOR` and `DUMP_HIR` can be removed since their corresponding lint passes are only used for side effects
The metadata collector lint can be made an `internal` lint since `clippy::internal` is set to deny when running the collector
Also renames some internal lints/passes
> Remove the `internal_warn` lint category

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/methods/mod.rs
- clippy_lints/src/methods/waker_clone_wake.rs
- clippy_utils/src/paths.rs
- tests/ui/waker_clone_wake.fixed
- tests/ui/waker_clone_wake.rs
- tests/ui/waker_clone_wake.stderr
Check for patterns of `waker.clone().wake()` and replace them with `waker.wake_by_ref()`.
An alternative name could be `waker_clone_then_wake`
changelog: [ `waker_clone_wake`]: new lint
> Add `waker_clone_and_wake` lint to check needless `Waker` clones

- clippy_lints/src/iter_without_into_iter.rs
- tests/ui/into_iter_without_iter.rs
- tests/ui/into_iter_without_iter.stderr
- tests/ui/iter_without_into_iter.rs
- tests/ui/iter_without_into_iter.stderr
See #11692 for more context.
tldr: the lint `iter_without_into_iter` has suggestions that don't compile, which imo isn't that problematic because it does have the appropriate `Applicability` that tells external tools that it shouldn't be auto-applied.
However there were some obvious "errors" in the suggestion that really should've been included in my initial PR adding the lint, which is fixed by this PR:
- `IntoIterator::into_iter` needs a `self` argument.
- `IntoIterator::Iter` associated type doesn't exist. This should've just been `Item`.
This still doesn't make it machine applicable, and the remaining things are imho quite non-trivial to implement, as I've explained in https://github.com/rust-lang/rust-clippy/issues/11692#issuecomment-1773886111.
I personally think it's fine to leave …
> [`iter_without_into_iter`]: fix papercuts in suggestion and restrict linting to exported types

- clippy_lints/src/floating_point_arithmetic.rs
- clippy_utils/src/sugg.rs
- tests/ui/floating_point_mul_add.fixed
- tests/ui/floating_point_mul_add.rs
- tests/ui/floating_point_mul_add.stderr
This fixes #11559 by adding a branch in the `Neg` implementation for `Sugg` that adds parentheses to keep precedence in order, then using that in the suggestion. I also removed some needless `.to_string()`s while I was at it.
---
> Fix missing parenthesis in suboptimal floating point help

- clippy_lints/src/panic_unimplemented.rs
https://doc.rust-lang.org/nightly/core/macro.todo.html describes that `todo!()` is intended for explicitly unfinished code. Explain this, and mention `unimplemented!()` as an alternative.
Whilst we're here, improve the punctuation on the other lints.
changelog: [`todo`]: expand docs
> Expand docs on clippy::todo

- clippy_lints/src/read_zero_byte_vec.rs
I think the concerns in #9274 are valid, and we should move this to nursery while we're reworking this.
changelog: [`read_zero_byte_vec`] moved to nursery
> move `read_zero_byte_vec` to nursery

- clippy_lints/src/doc.rs
- tests/ui/doc/doc-fixable.fixed
- tests/ui/doc/doc-fixable.rs
This fixes #11568 by ignoring camelCase words starting with a lower case letter.
r? @blyxyas 
---
> ignore lower-camel-case words in `doc_markdown`

- .github/workflows/clippy.yml
- .github/workflows/clippy_bors.yml
- clippy_lints/Cargo.toml
- clippy_utils/Cargo.toml
- clippy_utils/src/diagnostics.rs
- clippy_utils/src/paths.rs
It's only used to gate a few `const`s, removing the feature gate means it doesn't have to be recompiled when moving between a normal and `-F internal` build/test/etc
> Remove internal feature from clippy_utils

- clippy_lints/src/vec_init_then_push.rs
Makes the perf argument clearer, since a single push doesn't have unnecessary allocations compared to `vec![x]`
> Use multiple pushes in `vec_init_then_push` example

- clippy_lints/src/item_name_repetitions.rs
- tests/ui/enum_variants.rs
- tests/ui/enum_variants.stderr
changelog: [`enum_variant_names`]: fix single word variants preventing lint of later variant pre/postfixed with the enum name 
fixes #11494 
Single word variants prevented checking the `check_enum_start` and `check_enum_end` for being run on later variants
> fix enum_variant_names depending lint depending on order

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/implicit_saturating_add.rs
- clippy_lints/src/methods/mod.rs
- clippy_lints/src/methods/unnecessary_fallible_conversions.rs
- tests/ui/manual_string_new.fixed
- tests/ui/manual_string_new.rs
- tests/ui/manual_string_new.stderr
- tests/ui/unnecessary_fallible_conversions.fixed
- tests/ui/unnecessary_fallible_conversions.rs
- tests/ui/unnecessary_fallible_conversions.stderr
- tests/ui/unnecessary_fallible_conversions_unfixable.rs
- tests/ui/unnecessary_fallible_conversions_unfixable.stderr
- tests/ui/useless_conversion_try.rs
Closes #11577
A new lint that looks for calls such as `i64::try_from(1i32)` and suggests `i64::from(1i32)`. See lint description (and linked issue) for more details for why.
There's a tiny bit of overlap with the `useless_conversion` lint, in that the other one warns `T::try_from(T)` (i.e., fallibly converting to the same type), so this lint ignores cases like `i32::try_from(1i32)` to avoid emitting two warnings for the same expression.
Also, funnily enough, with this one exception, this lint would warn on exactly every case in the `useless_conversion_try` ui test that `useless_conversion` didn't cover (but never two warnings at the same time), which is neat. I did add an `#![allow]` though since we don't want interleaved warnings from multiple lints in the same uitest.
changelog: new …
> new lint: `unnecessary_fallible_conversions`

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/loops/for_kv_map.rs
- clippy_lints/src/loops/mod.rs
- clippy_lints/src/loops/unused_enumerate_index.rs
- clippy_lints/src/methods/iter_kv_map.rs
- clippy_utils/src/lib.rs
- tests/ui/unused_enumerate_index.fixed
- tests/ui/unused_enumerate_index.rs
- tests/ui/unused_enumerate_index.stderr
A lint for unused `.enumerate()` indexes (`for (_, x) in iter.enumerate()`).
I wasn't able to find a `rustc_span::sym::Enumerate`, so the code for checking that it's the correct `Enumerate` iterator is a bit weird.
---
changelog: New lint: [`unused_enumerate_index`]: A new lint for checking that the indexes from `.enumerate()` calls are used.
[#10404](https://github.com/rust-lang/rust-clippy/pull/10404)
> Add `unused_enumerate_index` lint

- clippy_lints/src/methods/get_first.rs
- tests/ui/get_first.fixed
- tests/ui/get_first.rs
- tests/ui/get_first.stderr
fixes #11695 
Also run the lint on `VecDeque` and suggest using `.front()` instead of `.get(0)` when trying to access the first element.
PS: At first I implemented the VecDeque Lint in a separate `if_chain` (see the previous commit).
Let me know if thats the preferred way, then I will remove the refactoring into one block.
changelog: [`get_first`]: fix false negative: Also lint `VecDeque` and suggest using `front()`
> Fix get_first false negative for VecDeque

- clippy_lints/src/loops/unused_enumerate_index.rs
- tests/ui/crashes/ice-11755.rs
Fixes #11755
changelog: [`unused_enumerate_index`]: don't ICE on empty tuples
I'm going to nominate for beta backport because the code that is needed to trigger this seems likely to occur in real code
@rustbot label +beta-nominated
> [`unused_enumerate_index`]: don't ICE on empty tuples

- book/src/development/adding_lints.md
- clippy_dev/src/new_lint.rs
- clippy_lints/src/types/mod.rs
In #11685, `clippy_lints::utils::conf` and `clippy_utils::msrvs` were moved to a separate `clippy_config` crate.
I noticed that not all references to those paths were updated, so this small PR intends to fix those.
> update references of old `msrvs` and `conf` paths

- clippy_utils/src/hir_utils.rs
1) Remove wildcard as requested in https://github.com/rust-lang/rust-clippy/issues/10267.
2) Implement `hir_utils::eq_expr` for `ExprKind::Closure`, `ExprKind::ConstBlock`, `ExprKind::InlineAsm` and `ExprKind::Yield`.
3) Reorder branches of `hir_utils::eq_expr` to be in alphabetical order.
---
> Make SpanlessEq more consistent

- clippy_lints/src/arc_with_non_send_sync.rs
- tests/ui/arc_with_non_send_sync.rs
- tests/ui/arc_with_non_send_sync.stderr
Fixes: #11714 
Improved the lint message for [`arc_with_non_send_sync`] to suggest using `RC` unless user needs an Arc, then suggests wrapping in a mutex, and then suggests implementing `Sync` and `Send`.
---
changelog: [`arc_with_non_send_sync`]: Suggest RC over unsafe impl of Send and Sync
> [arc_with_non_send_sync] Improve suggested resolution

- clippy_lints/src/module_style.rs
fixes: #11775
current state: indiscriminately emits the lint for mod files in tests.
The following
```
tests/
common/
mod.rs
test.rs
```
is a common pattern for code shared across the tests and is suggested in the rust book. The change adds an additional check to verify that the mod file is not in tests.
changelog: Fix [`mod_module_files`]: false positive for mod files in tests folder
> [`mod_module_files`] Don't emit lint for mod.rs in tests

- CONTRIBUTING.md
- book/src/development/adding_lints.md
- book/src/development/defining_lints.md
- clippy_config/src/types.rs
- clippy_lints/src/disallowed_names.rs
- clippy_lints/src/doc.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/methods/mod.rs
- clippy_lints/src/nonstandard_macro_braces.rs
- clippy_lints/src/pass_by_ref_or_value.rs
- clippy_lints/src/raw_strings.rs
- src/driver.rs
And some other miscellaneous clean-up in the area
> Destructure `Conf` in `register_lints`

- clippy_utils/src/lib.rs
- tests/ui/map_identity.fixed
- tests/ui/map_identity.rs
- tests/ui/map_identity.stderr
Fixes #11764
Note: the original tests before this were slightly wrong themselves already and had to be changed. They were calling `map` on an iterator of `&(i32, i32)`s, so this PR would stop linting there, but they were meant to test something else unrelated to binding modes, so I just changed them to remove the references so that it iterates over owned values and they all bind by value. This way they continue to test what they checked for before: the identity function for tuple patterns.
changelog: [`map_identity`]: respect match ergonomics
> [`map_identity`]: respect match ergonomics

- clippy_lints/src/methods/unnecessary_fallible_conversions.rs
- tests/ui/unnecessary_fallible_conversions.stderr
- tests/ui/unnecessary_fallible_conversions_unfixable.stderr
fixes: #11753 
changelog: [`unnecessary_fallible_conversions`]: add type details to lint note
> Add type details to unnecessary_fallible_conversions note

- clippy_lints/src/dereference.rs
- clippy_utils/src/ty.rs
- tests/ui/explicit_auto_deref.fixed
- tests/ui/explicit_auto_deref.rs
- tests/ui/explicit_auto_deref.stderr
- tests/ui/needless_borrow.fixed
- tests/ui/needless_borrow.rs
- tests/ui/needless_borrow.stderr
Changes both lints to follow rustc's rules around auto-deref through `ManuallyDrop` union fields rather than just bailing on union fields.
changelog: [`needless_borrow`] & [`explicit_auto_deref`]: Lint on most union field accesses
> Lint `needless_borrow` and `explicit_auto_deref` on most union field accesses

- clippy_lints/src/manual_let_else.rs
- clippy_utils/src/lib.rs
- tests/ui/manual_let_else.rs
- tests/ui/manual_let_else.stderr
A few changes to the divergence check in `manual_let_else` and moves it the implementation to `clippy_utils` since it's generally useful:
* Handle internal `break` and `continue` expressions.
e.g. The first loop is divergent, but the second is not.
```rust
{
loop {
break 'outer;
};
}
{
loop {
break;
};
}
```
* Match rust's definition of divergence which is defined via the type system.
e.g. The following is not considered divergent by rustc as the inner block has a result type of `()`:
```rust
{
'a: {
panic!();
break 'a;
};
}
```
* Handle when adding a single semicolon would make the expression divergent.
e.g. The following would be a divergent if a semicolon were added after the `if` expression:
```rust
{ if panic!() { 0 } else { 1 } }
```
> Fixes to `manual_let_else`'s divergence check

- triagebot.toml
Catherine decided that the best course of action would be to (maybe temporarily) remove her from the reviewer's rotation (but not unassign her from her current reviews). This PR does that. She'll always be welcomed back if she wants to review some more :heart:
> Alejandra González: [youremyfrennow.mp4](https://rust-lang.zulipchat.com/user_uploads/4715/7nE2W6cb8Q02gcK-vubvmsPM/youremyfrennow.mp4)
>
>Catherine, Fred (@xFrednet ) noticed that you aren't as active as in the summer, and proposed that maybe you preferred to be removed from the reviewer rotation. Don't worry, you aren't being taken out of the team, just wanted to know if you maybe preferred to not have those reviews pilling up (they can be pretty stressful to see).
>
>If you decide to step out of the reviewers rotation, you …
> Removing @Centri3 from reviewer rotation

- clippy_lints/src/loops/manual_memcpy.rs
- tests/ui/manual_memcpy/without_loop_counters.rs
- tests/ui/manual_memcpy/without_loop_counters.stderr
fixes: #11689 
This PR improves `manual_memcpy` suggestions by reducing unnecessary indexing.
For example, 
```rust
let src = [0, 1, 2, 3, 4];
let mut dest = [0; 4];
for i in 0..4 {
dest[i] = src[i];
{
```
Clippy suggests `dest[..4].copy_from_slice(&src[..4]);`.
I reduced this suggestion as `dest.copy_from_slice(&src[..4]);`. (Removed needless indexing.)
changelog: [`manual_memcpy`]: Reduce indexing suggestions when array length is equal to loop range
> fix: [manual_memcpy] reduce indexing suggestions when array length is equal to loop range

- clippy_lints/src/casts/cast_possible_wrap.rs
- clippy_lints/src/module_style.rs
Fixes https://github.com/rust-lang/rust-clippy/issues/11805
Essentially just changes the section of code that applies the lint from using `cx.struct_span_lint` and instead opts for `span_lint_and_then`, which automatically appends the help text.
changelog: add missing help text for `cast_possible_wrap`, `mod_module_files`, and `self_named_module_files` lints
> add help text where missing to lints

- clippy_lints/src/functions/impl_trait_in_params.rs
- tests/ui/crashes/ice-11803.rs
- tests/ui/crashes/ice-11803.stderr
Fixes #11803
If I'm reading the old code correctly, it was taking the span of the first parameter (without checking that it exists, which caused the ICE) and uses that to figure out where the generic parameter to insert should go (cc @blyxyas you wrote the lint, is that correct?).
This seemed equivalent to just `generics.span`, which doesn't require calculating the spans like that and simplifies it a fair bit
changelog: don't ICE when function has no parameters but generics have an `impl Trait` type
> [`impl_trait_in_params`]: avoid ICE when function with `impl Trait` type has no parameters

- clippy.toml
- clippy_utils/src/diagnostics.rs
- tests/ui-internal/disallow_struct_span_lint.rs
- tests/ui-internal/disallow_struct_span_lint.stderr
`LintContext::struct_span_lint` and `TyCtxt::struct_span_lint_hir` don't show the link to the clippy documentation, see: #11805
In #11810, the last few calls to those methods were replaced with `span_lint_*`. It seems like we should just disallow them altogether so that no new code tries to use them.
The existing `disallowed_methods` lint makes this easy.
> disallow calls to `LintContext::struct_span_lint` and `TyCtxt::struct_span_lint_hir`

- .github/workflows/deploy.yml
This action was way outdated, produced a lot of warnings and didn't seem to work anymore.
> Update rust-cache GHA in deploy workflow

- clippy_lints/src/attrs.rs
- tests/ui/cfg_features.fixed
- tests/ui/cfg_features.rs
- tests/ui/cfg_features.stderr
Fixes #11240.
One thought I had is that we could use the levenshtein distance (of 1) to ensure this is indeed `test` that was targeted. But maybe it's overkill, not sure.
changelog: [`maybe_misused_cfg`]: Extend lint over `cfg(test)`
r? @blyxyas
> Extend `maybe_misused_cfg` lint over `cfg(test)`

- clippy_lints/src/matches/match_same_arms.rs
- clippy_utils/src/consts.rs
- clippy_utils/src/eager_or_lazy.rs
- tests/ui/unnecessary_lazy_eval.fixed
- tests/ui/unnecessary_lazy_eval.rs
- tests/ui/unnecessary_lazy_eval.stderr
Fixes #9422
Fixes #9814
Fixes #11793
It's a bit sad that we have to do this because arithmetic operations seemed to me like the prime example where a closure would not be necessary, but this has "side effects" (changes behavior when going from lazy to eager) as some of these panic on overflow/underflow if compiled with `-Coverflow-checks` (which is the default in debug mode).
Given the number of backlinks in the mentioned issues, this seems to be a FP that is worth fixing, probably.
changelog: [`unnecessary_lazy_evaluations`]: don't lint if closure has panicky arithmetic operations
> teach `eager_or_lazy` about panicky arithmetic operations

- clippy_lints/src/methods/mod.rs
- clippy_lints/src/unnecessary_map_on_constructor.rs
Fixes typos and markup errors, and also makes the examples more realistic by hiding the `;`s so as not to visibly be discarding the computed value. Affected lints:
* `redundant_as_str`
* `unnecessary_map_on_constructor`
> Fix typos in recent lint documentation.

- clippy_lints/src/macro_use.rs
- tests/ui/macro_use_imports.stderr
Fixes [the `macro_use_imports` ordering dependence](https://github.com/rust-lang/rust/pull/117649#issuecomment-1797716088) on the hash of `Span`s
> Make `macro_use_imports` lint ordering more stable

- clippy_lints/src/lines_filter_map_ok.rs
- tests/ui/lines_filter_map_ok.fixed
- tests/ui/lines_filter_map_ok.rs
- tests/ui/lines_filter_map_ok.stderr
Fixes #11686 
changelog: [`lines_filter_map_ok`]: Also lint calls to `flatten()`
> Lint `flatten()` under `lines_filter_map_ok`

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/impl_hash_with_borrow_str_and_bytes.rs
- clippy_lints/src/lib.rs
- tests/ui/impl_hash_with_borrow_str_and_bytes.rs
- tests/ui/impl_hash_with_borrow_str_and_bytes.stderr
Fixes #11710 
The essence of the issue is that types that implement Borrow<T> provide a facet or a representation of the underlying type. Under these semantics `hash(a) == hash(a.borrow())`.
This is a problem when a type implements `Borrow<str>`, `Borrow<[u8]>` and Hash, it is expected that the hash of all three types is identical. The problem is that the hash of [u8] is not the same as that of a String, even when the byte reference ([u8]) is derived from `.as_bytes()`
---
---
changelog: New lint: [`impl_hash_borrow_with_str_and_bytes`]
[#11781](https://github.com/rust-lang/rust-clippy/pull/11781)
> Verify Borrow<T> semantics for types that implement Hash, Borrow<str> and Borrow<[u8]>.

- clippy_lints/src/attrs.rs
- tests/ui/cfg_features.fixed
- tests/ui/cfg_features.rs
- tests/ui/cfg_features.stderr
Follow-up of the improvements that were suggested to me in https://github.com/rust-lang/rust-clippy/pull/11821:
* I unified the output to use the same terms.
* I updated the code to prevent creating a new symbol.
r? @blyxyas
changelog: [`maybe_misued_cfg`]: Output and code improvements
> Improve maybe misused cfg

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/methods/join_absolute_paths.rs
- clippy_lints/src/methods/mod.rs
- tests/ui/join_absolute_paths.rs
- tests/ui/join_absolute_paths.stderr
Hey @ofeeg, this PR is a copy of all the changes you did in https://github.com/rust-lang/rust-clippy/commit/47171d3c6366dd08476b2ab1e1661950d13a4218 from PR https://github.com/rust-lang/rust-clippy/pull/11208. I wasn't sure how to fix the git history. Hope you're okay with me figuring this out in this separate PR
---
changelog: New lint [`join_absolute_paths`]
[#11453](https://github.com/rust-lang/rust-clippy/pull/11453)
Closes: https://github.com/rust-lang/rust-clippy/issues/10655
r? @Centri3 Since you also gave feedback on the other PR. I hope that I copied everything correctly, but a third pair of eyes would be appreciated :D
> New lint `clippy::join_absolute_paths`

- clippy_lints/src/doc/link_with_quotes.rs
- clippy_lints/src/doc/markdown.rs
- clippy_lints/src/doc/missing_headers.rs
- clippy_lints/src/doc/mod.rs
- clippy_lints/src/doc/needless_doctest_main.rs
- clippy_lints/src/doc/suspicious_doc_comments.rs
- tests/ui/doc_link_with_quotes.rs
- tests/ui/doc_link_with_quotes.stderr
So, first, sorry for the bad diff. 😅 
In #11798, @flip1995  suggested splitting `doc.rs` up, much like how we have the `methods/`, `matches/`, `types/` subdirectories.
I agree with this, the file is getting bigger as we add more and more doc lints that it makes sense to do this refactoring.
This is purely an internal change that moves things around a bit. 
(**EDIT:** depending on the outcome of https://github.com/rust-lang/rust-clippy/pull/11801#issuecomment-1816715615 , this may change the lint group name from `doc_markdoc` to `doc`).
I tried to not change any of the actual logic of the lints and as such some things weren't as easy to move to a separate file. So we still have some `span_lint*` calls in the `doc/mod.rs` file, which I think is fine. This is also the case in …
> Split `doc.rs` up into a subdirectory

- clippy_lints/src/returns.rs
- tests/ui/needless_return_with_question_mark.fixed
- tests/ui/needless_return_with_question_mark.rs
- tests/ui/needless_return_with_question_mark.stderr
Fixes #11616
When we have something like
```rs
let _x: String = {
return Err(())?;
};
```
we shouldn't suggest removing the `return` because the `!`-ness of `return` is used to coerce the enclosing block to some other type. That will lead to a typeck error without a diverging expression like `return`.
changelog: [`needless_return_with_question_mark`]: don't lint if `return`s never typed-ness is used for coercion
> [`needless_return_with_question_mark`]: don't lint if never type is used for coercion

- tests/ui/transmute_ptr_to_ptr.fixed
- tests/ui/transmute_ptr_to_ptr.rs
- tests/ui/transmute_ptr_to_ptr.stderr
- tests/ui/transmute_ref_to_ref.rs
- tests/ui/transmute_ref_to_ref.stderr
Fixes #10285.
Fixes #10286.
Fixes #10289.
Fixes #10287.
This PR simply adds tests for the listed issues as they're already implemented so we can close them.
r? @blyxyas 
changelog:none
> Add tests for issues #10285, #10286, #10289, #10287

- clippy_lints/src/manual_non_exhaustive.rs
- tests/ui/manual_non_exhaustive_enum.rs
- tests/ui/manual_non_exhaustive_enum.stderr
- tests/ui/manual_non_exhaustive_struct.stderr
Fixes https://github.com/rust-lang/rust-clippy/issues/10550.
As indicated in https://github.com/rust-lang/rust-clippy/pull/10559, the underscore check should be removed.
changelog: remove underscore check for `manual_non_exhaustive` lint
r? @blyxyas
> Remove underscore check for `manual_non_exhaustive` lint

- book/src/development/adding_lints.md
This adds a little reminder to update the documentation in the book using `cargo collect-metadata` after changing the lint configuration since this can easily be missed (been there done that 🙈).
> Yeah a note would be good, would be good for us to see if we can make it automatic also
_Originally posted by @Alexendoo in https://github.com/rust-lang/rust-clippy/issues/11757#issuecomment-1823474156_
Regarding the automation Im not sure whats the best option here. I thought about a kind of a "semi-automated" way, e.g. a `cargo dev` command which runs the "is the documentation updated" check (and maybe other useful checks) locally and reminds the user of updating the documentation so this gets caught before pushing.  
> Add documentation update hint using `cargo collect-metadata`

- clippy_lints/src/methods/mod.rs
- clippy_lints/src/methods/result_map_or_else_none.rs
- tests/ui/result_map_or_into_option.fixed
- tests/ui/result_map_or_into_option.rs
- tests/ui/result_map_or_into_option.stderr
Fixes https://github.com/rust-lang/rust-clippy/issues/10365.
As indicated in the title, it extends the `result_map_or_into_option` lint to handle `Result::map_or_else(|_| None, Some)`.
changelog: extension of the `result_map_or_into_option` lint to handle `Result::map_or_else(|_| None, Some)`
r? @blyxyas
> Extend `result_map_or_into_option` lint to handle `Result::map_or_else(|_| None, Some)`

- clippy_lints/src/methods/map_unwrap_or.rs
- clippy_lints/src/methods/option_as_ref_deref.rs
- clippy_lints/src/methods/option_map_or_none.rs
- clippy_lints/src/methods/option_map_unwrap_or.rs
- tests/ui/map_unwrap_or.stderr
- tests/ui/map_unwrap_or_fixable.stderr
- tests/ui/option_as_ref_deref.stderr
- tests/ui/option_map_or_none.stderr
- tests/ui/result_map_or_into_option.fixed
- tests/ui/result_map_or_into_option.rs
- tests/ui/result_map_or_into_option.stderr
Following review in https://github.com/rust-lang/rust-clippy/pull/11845, since there is already suggestions, no need to add the second part of the sentence every time.
r? @flip1995 
changelog: Improve some error messages
> Improve error messages format

- clippy_lints/src/missing_asserts_for_indexing.rs
- tests/ui/missing_asserts_for_indexing_unfixable.rs
- tests/ui/missing_asserts_for_indexing_unfixable.stderr
Fixes #11856
Before this change, this lint would check blocks independently of each other, which means that it misses `assert!()`s from parent blocks.
```rs
// check_block
assert!(x.len() > 1);
{
// check_block
// no assert here
let _ = x[0] + x[1];
}
```
This PR changes it to work with bodies rather than individual blocks. That means that a function will be checked in one go and we can remember if an `assert!` occurred anywhere.
Eventually it would be nice to have a more control flow-aware analysis, possibly by rewriting it as a MIR lint, but that's more complicated and I wanted this fixed first.
changelog: [`missing_asserts_for_indexing`]: accept `assert!`s from parent blocks
> [`missing_asserts_for_indexing`]: work with bodies instead of blocks separately

- clippy_lints/src/attrs.rs
- tests/ui/attrs.rs
"TBD" is allowed by rustdoc, saying that it will be deprecated in a future version. rustc will also not actually warn on it.
I found this while checking the rust-lang/rust with clippy.
changelog: [`deprecated_semver`]: allow using `since = "TBD"`
> [`deprecated_semver`]: Allow `#[deprecated(since = "TBD")]`

- clippy_lints/src/eta_reduction.rs
I think formatting `matches!` with `if` guards is [still unsupported](https://github.com/rust-lang/rustfmt/issues/5547), which is probably why this was missed.
> Nit re `matches!` formatting

- clippy_lints/src/loops/single_element_loop.rs
- tests/ui/single_element_loop.fixed
- tests/ui/single_element_loop.stderr
works towards #7125
changelog: [`single_element_loop`]: suggest better syntax when iterating over an array of a single range
@thinkerdreamer and myself worked on this issue during a workshop by @llogiq at the RustLab 2023 conference. It is our first contribution to clippy. 
When iterating over an array of only one element, _which is a range_, our change suggests to replace the array with the contained range itself. Additionally, a hint is printed stating that the user probably intended to iterate over the range and not the array. If the single element in the array is not a range, the previous suggestion in the form of `let {pat_snip} = {prefix}{arg_snip};{block_str}`is used.
This change lints the array with the single range directly, so any prefixes or suffixes are covered as well.
> suggest alternatives to iterate an array of ranges

- clippy_lints/src/methods/result_map_or_else_none.rs
As mentioned in https://github.com/rust-lang/rust-clippy/pull/11864.
r? @flip1995 
changelog: Simplify code for `result_map_or_else_none`
> Simplify code for `result_map_or_else_none`

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/methods/mod.rs
- clippy_lints/src/methods/option_map_or_err_ok.rs
- tests/ui/manual_ok_or.stderr
- tests/ui/option_map_or_err_ok.fixed
- tests/ui/option_map_or_err_ok.rs
- tests/ui/option_map_or_err_ok.stderr
Fixes #10045.
For the following code:
```rust
let opt = Some(1);
opt.map_or(Err("error"), Ok);
```
It suggests to instead write:
```rust
let opt = Some(1);
opt.ok_or("error");
```
r? @flip1995 
changelog: Create new lint `option_map_or_err_ok`
> Create new lint `option_map_or_err_ok`

- clippy_lints/src/box_default.rs
- tests/ui/box_default.fixed
- tests/ui/box_default.rs
Fix #11868 
changelog: [`box_default`]: do not warn on `Box::new(vec![])` if the `vec![]` comes from a macro argument
> Fix `box_default` behaviour with empty `vec![]` coming from macro arg

- clippy_lints/src/implied_bounds_in_impls.rs
This lint was originally in the complexity category when I PR'd it. It was then moved to nursery by me due to a number of issues (a false positive, an invalid suggestion and an ICE), but that was probably an overreaction and all of the issues were fixed quickly after.
This is a useful lint imo and there hasn't been any issues with it in a few months, so I say we should give it another try and move it back to complexity.
I did a lintcheck run on the top 400 crates and all of them are legitimate, with 18 warnings. Most of them are from anstyle having a `impl Display + Copy + Clone` return type, or the bitvec crate with a return type like `impl Iterator + DoubleEndedIterator`.
changelog: Move [`implied_bounds_in_impls`] to `complexity` (Now warn-by-default) …
> Move `implied_bounds_in_impls` back to complexity

- book/src/development/type_checking.md
> `TypeckResults::node_type()` can be used inside of bodies

- clippy_lints/src/methods/manual_try_fold.rs
- tests/ui/manual_try_fold.rs
Fix #11876
changelog: [`manual_try_fold`]: suggest using `try_fold` only for `Iterator::fold` uses
> `manual_try_fold`: check that `fold` is really `Iterator::fold`

- clippy_lints/src/floating_point_arithmetic.rs
- tests/ui/floating_point_mul_add.fixed
- tests/ui/floating_point_mul_add.rs
clippy::suboptimal_flops used to not check if the second parameter to f32/f64.mul_add() was float. Since the method is only defined to take `Self` as parameters, the suggestion was wrong.
Fixes #11831
changelog: [`suboptimal_float`]: Don't suggest `a.mul_add(b, c)` if parameters are not f32/f64
> Don't suggest `a.mul_add(b, c)` if parameters are not float

- clippy_lints/src/doc/mod.rs
- clippy_lints/src/lib.rs
Followup of #11801
This was discussed in todays meeting: https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Meeting.202023-11-28/near/404667082
Decided to go with `Documentation`, because this would also make it consistent with how `Attributes` is named in `attrs.rs` (and it also sounds good).
> rename `DocMarkdown` pass to `Documentation`

- clippy_lints/src/redundant_closure_call.rs
- tests/ui/redundant_closure_call_fixable.fixed
- tests/ui/redundant_closure_call_fixable.rs
- tests/ui/redundant_closure_call_fixable.stderr
close #11357
----
changelog: [`redundant_closure_call`]: avoid duplicated `async` keyword when triggering on closure that returns `async` block
> [`redundant_closure_call`]: avoid duplicated `async` keyword when triggering on closure that returns `async` block

- clippy_lints/src/manual_async_fn.rs
- clippy_lints/src/matches/redundant_guards.rs
- tests/ui/redundant_guards.fixed
- tests/ui/redundant_guards.rs
- tests/ui/redundant_guards.stderr
Fixes #11807
Few things worth mentioning:
- Taking `snippet`s is now done at callsite, instead of passing a span and doing it in `emit_redundant_guards`. This is because we now need custom suggestion strings in certain places, like `""` for `str::is_empty`.
- This now uses `snippet` instead of `snippet_with_applicability`. I don't think this really makes any difference for `MaybeIncorrect`, though?
- This could also lint byte strings, as they're of type `&[u8; N]`, but that can be ugly so I decided to leave it out for now
changelog: [`redundant_guards`]: catch `str::is_empty`, `slice::is_empty`, `slice::starts_with` and `slice::ends_with`
> [`redundant_guards`]: catch `is_empty`, `starts_with` and `ends_with` on slices and `str`s

- clippy_lints/src/upper_case_acronyms.rs
- tests/ui/upper_case_acronyms.fixed
- tests/ui/upper_case_acronyms.rs
- tests/ui/upper_case_acronyms.stderr
Fixes #7708
changelog: [`upper_case_acronyms`]: allow `allow`ing on enum variants
> Allow `allow`ing `upper_case_acronyms` on enum variants

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/repeat_vec_with_capacity.rs
- tests/ui/repeat_vec_with_capacity.fixed
- tests/ui/repeat_vec_with_capacity.rs
- tests/ui/repeat_vec_with_capacity.stderr
Closes #11537
[Lint description](https://github.com/y21/rust-clippy/blob/repeat_vec_with_capacity/clippy_lints/src/repeat_vec_with_capacity.rs#L14) should explain this PR :)
changelog: new lint: `repeat_vec_with_capacity`
> new lint: `repeat_vec_with_capacity`

- clippy_lints/src/missing_asserts_for_indexing.rs
- tests/ui/missing_asserts_for_indexing.fixed
- tests/ui/missing_asserts_for_indexing.rs
- tests/ui/missing_asserts_for_indexing.stderr
Fixes #11835
The lint now allows indexing with indices 0 and 1 when an `assert!(x.len() == 2);` is found.
(Also fixed a typo in the doc example)
changelog: [`missing_asserts_for_indexing`]: accept len equality checks as a valid assertion
> [`missing_asserts_for_indexing`]: accept length equality checks

- clippy_lints/src/manual_string_new.rs
This is a style fix: the outer `if` check was useless.
> Do not check twice whether `qpath` is a `QPath::TypeRelative` variant

- clippy_lints/Cargo.toml
- tests/ui/regex.rs
From the regex v1.10.0 release notes [1]:
This is a new minor release of regex that adds support for start
and end word boundary assertions. [...]
The new word boundary assertions are:
• \< or \b{start}: a Unicode start-of-word boundary (\W|\A
on the left, \w on the right).
• \> or \b{end}: a Unicode end-of-word boundary (\w on the
left, \W|\z on the right)).
• \b{start-half}: half of a Unicode start-of-word boundary
(\W|\A on the left).
• \b{end-half}: half of a Unicode end-of-word boundary
(\W|\z on the right).
[1]: https://github.com/rust-lang/regex/blob/master/CHANGELOG.md#1100-2023-10-09
changelog: [`regex`]: add support for start and end word boundary assertions ("\<", "\b{start}", etc.) introduced in regex v0.10
> Update regex-syntax to support new word boundry assertions

- clippy_lints/src/explicit_write.rs
close #11918 
changelog: [`explicit_write`]: add missing backtick to document to complete code snippet
> docs(explicit_write): add missing backtick to complete code snippet

- clippy_lints/src/needless_borrows_for_generic_args.rs
- tests/ui/needless_borrows_for_generic_args.fixed
- tests/ui/needless_borrows_for_generic_args.rs
Before this fix, the lint had a false positive, namely when a reference was taken to a field when the field operand implements a custom Drop. The compiler will refuse to partially move a type that implements Drop, because that would put the type in a weird state.
```rs
struct CustomDrop(String);
impl Drop for CustomDrop {
fn drop(&mut self) {}
}
fn check_str<P: AsRef<str>>(_to: P) {}
fn test() {
let owner = CustomDrop(String::default());
check_str(&owner.0); // Don't lint. `owner` can't be partially moved because it impl Drop
}
``` 
changelog: [`needless_borrows_for_generic_args`]: Handle when field operand impl Drop
> needless_borrows_for_generic_args: Handle when field operand impl Drop

- clippy_lints/src/casts/ptr_as_ptr.rs
- tests/ui/ptr_as_ptr.fixed
- tests/ui/ptr_as_ptr.rs
- tests/ui/ptr_as_ptr.stderr
close rust-lang#11066
close rust-lang#11665
close rust-lang#11911
changelog: [`ptr_as_ptr`]: handle `std::ptr::null` and `std::ptr::null_mut`
> fix(ptr_as_ptr): handle `std::ptr::null{_mut}`

- clippy_dev/src/lint.rs
- clippy_dev/src/serve.rs
- clippy_lints/src/utils/internal_lints/metadata_collector.rs
- lintcheck/src/main.rs
- src/main.rs
Currently, clippy will ignore $CARGO when spawning cargo commands, which can be problematic for `cargo clippy` and interop with other tools. This commit induces clippy to respect $CARGO in every case it seems likely to matter.
Fixes:
- #11943 
changelog: clippy now respects setting the `CARGO` environment variable
> Check $CARGO before $PATH

- triagebot.toml
I have a surgery this Wednesday, so I won't be able to review anything from that day up to (at least) Dec. 22, I'll open another PR by then.
I'm not sure if `users_on_vacation` will work here, if it doesn't work, I'll just remove myself from the reviewer rotation
changelog:none
> Add `blyxyas` to `users_on_vacation`

- clippy_lints/src/as_conversions.rs
- clippy_lints/src/borrow_deref_ref.rs
- clippy_lints/src/manual_float_methods.rs
- clippy_lints/src/methods/unnecessary_lazy_eval.rs
- clippy_lints/src/needless_if.rs
- clippy_lints/src/operators/arithmetic_side_effects.rs
- clippy_lints/src/single_call_fn.rs
- clippy_utils/src/check_proc_macro.rs
- tests/ui/doc_unsafe.rs
- tests/ui/needless_pass_by_ref_mut.rs
- tests/ui/needless_pass_by_ref_mut.stderr
- tests/ui/unnecessary_unsafety_doc.rs
> Fix `is_from_proc_macro` patterns

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/uninhabited_references.rs
- tests/ui/infallible_destructuring_match.fixed
- tests/ui/infallible_destructuring_match.rs
- tests/ui/uninhabited_references.rs
- tests/ui/uninhabited_references.stderr
Close #11851
The lint is implemented on function parameters and return types, as this is the place where the risk of exchanging references to uninhabited types is the highest. Other constructs, such as in a local variable,
would require the use of `unsafe` and will clearly be done on purpose.
changelog: [`uninhabited_reference`]: new lint
> uninhabited_reference: new lint

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/ineffective_open_options.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/methods/mod.rs
- tests/ui/ineffective_open_options.fixed
- tests/ui/ineffective_open_options.rs
- tests/ui/ineffective_open_options.stderr
Fixes https://github.com/rust-lang/rust-clippy/issues/9628.
For `OpenOptions`, in case you call both `write(true)` and `append(true)` on `OpenOptions`, then `write(true)` is actually useless since `append(true)` does it.
r? @flip1995 
changelog: Add `ineffective_open_options` lint
> Add `ineffective_open_options` lint

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/loops/infinite_loop.rs
- clippy_lints/src/loops/infinite_loops.rs
- clippy_lints/src/loops/mod.rs
- tests/ui/infinite_loops.rs
- tests/ui/infinite_loops.stderr
closes: #11438 
changelog: add new lint to detect infinite loop
~*I'll change the lint name*~. Should I name it  `infinite_loop` or `infinite_loops` is fine? Ahhhh, English is hard...
> new lint to detect infinite loop

- clippy_lints/src/lib.rs
- clippy_lints/src/vec.rs
- tests/ui/vec.fixed
- tests/ui/vec.rs
- tests/ui/vec.stderr
changelog: [`useless_vec`]: fix false positive in macros.
fixes #11861
We delay the emission of `useless_vec` lints to the check_crate_post stage, which allows us to effectively undo lints if we find that a `vec![]` expression is being used multiple times after macro expansion.
> Useless vec false positive

- clippy_lints/src/doc/markdown.rs
- clippy_lints/src/missing_asserts_for_indexing.rs
- tests/ui/doc/doc-fixable.fixed
- tests/ui/doc/doc-fixable.rs
- tests/ui/doc/doc-fixable.stderr
changelog: [`doc_markdown`] Recognize words followed by empty parentheses for quoting, e.g. `func()`.
---
Developers often write function/method names with trailing `()`, but `doc_markdown` lint did not consider that.
Old clippy suggestion was not very good:
```patch
-/// There is no try (do() or do_not()).
+/// There is no try (do() or `do_not`()).
```
New behavior recognizes function names such as `do()` even they contain no `_`/`::`; and backticks are suggested outside of the `()`:
```patch
-/// There is no try (do() or do_not()).
+/// There is no try (`do()` or `do_not()`).
```
> [`doc_markdown`] Recognize words followed by empty parentheses `()` for quoting

- clippy_lints/src/methods/unnecessary_to_owned.rs
- tests/ui/unnecessary_to_owned.fixed
- tests/ui/unnecessary_to_owned.rs
- tests/ui/unnecessary_to_owned.stderr
fixes #11952
The use of `rebind` instead of `EarlyBinder::bind` isn't technically needed, but it is the semantically correct operation.
> Fix binder handling in `unnecessary_to_owned`

- clippy_lints/src/format_push_string.rs
- clippy_lints/src/loops/manual_flatten.rs
- clippy_lints/src/loops/while_let_on_iterator.rs
- clippy_lints/src/manual_let_else.rs
- clippy_lints/src/matches/collapsible_match.rs
- clippy_lints/src/matches/mod.rs
- clippy_lints/src/matches/redundant_pattern_match.rs
- clippy_lints/src/methods/filter_map.rs
- clippy_lints/src/option_if_let_else.rs
- clippy_lints/src/question_mark.rs
- clippy_lints/src/utils/author.rs
- clippy_utils/src/higher.rs
- tests/ui/author/loop.rs
- tests/ui/branches_sharing_code/shared_at_bottom.rs
- tests/ui/branches_sharing_code/shared_at_bottom.stderr
- tests/ui/collapsible_if.fixed
- tests/ui/collapsible_if.rs
- tests/ui/collapsible_if.stderr
- tests/ui/if_then_some_else_none.rs
- tests/ui/if_then_some_else_none.stderr
- tests/ui/needless_if.fixed
- tests/ui/needless_if.rs
- tests/ui/needless_if.stderr
- tests/ui/nonminimal_bool.rs
- tests/ui/nonminimal_bool.stderr
- tests/ui/redundant_pattern_matching_if_let_true.fixed
- tests/ui/redundant_pattern_matching_if_let_true.rs
- tests/ui/redundant_pattern_matching_if_let_true.stderr
Closes #11917
This could also lint e.g. `if let (true, true, false) = (a, b, c)` and suggest `if a && b && c`, but that's a change in semantics (going from eager to lazy, so I just left it out for now. Could be a future improvement.
changelog: [`redundant_pattern_matching`]: lint `if let true`, `while let true`, `matches!(.., true)`
> [`redundant_pattern_matching`]: lint `if let true`, `while let true`, `matches!(.., true)` 

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/unconditional_recursion.rs
- tests/ui/unconditional_recursion.rs
- tests/ui/unconditional_recursion.stderr
Currently, rustc `unconditional_recursion` doesn't detect cases like:
```rust
enum Foo {
A,
B,
}
impl PartialEq for Foo {
fn eq(&self, other: &Self) -> bool {
self == other
}
}
```
This is because the lint is currently implemented only for one level, and in the above code, `self == other` will then call `impl PartialEq for &T`, escaping from the detection. The fix for it seems to be a bit tricky (I started investigating potential solution to add one extra level of recursion [here](https://github.com/rust-lang/rust/compare/master...GuillaumeGomez:rust:trait-impl-recursion?expand=1) but completely broken at the moment).
I expect that this situation will remain for a while. In the meantime, I think it's acceptable to check it directly into clippy for the time being as a lot of easy cases …
> Add new `unconditional_recursion` lint

- clippy_utils/src/visitors.rs
- tests/ui/crashes/ice-11939.rs
Fixes #11939
This ICE happened in `if_let_some_else_none`, but the root problem is in one of the utils that it uses.
It is (was) possible for `is_const_evalutable` to visit nested bodies which would lead to it trying to get the type of one of the expressions with the wrong typeck table, which won't have the type stored.
Notably, for the expression `Bytes::from_static(&[0; 256 * 1024]);` in the linked issue, the array length is an anonymous const in which type checking happens on its own, so we can't use the typeck table of the enclosing function in there.
Visiting nested bodies is also not needed for checking whether an expression can be const, so I think it's safe to ignore just ignore them altogether.
changelog: Fix ICE when checking for constness in nested bodies
> don't visit nested bodies in `is_const_evaluatable`

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/methods/filter_map.rs
- clippy_lints/src/methods/mod.rs
- tests/ui/option_filter_map.fixed
- tests/ui/option_filter_map.rs
- tests/ui/option_filter_map.stderr
- tests/ui/result_filter_map.fixed
- tests/ui/result_filter_map.rs
- tests/ui/result_filter_map.stderr
Added the `Result` mirror of `option_filter_map`.
changelog: New Lint: [`result_filter_map`]
I had to move around some code because the function def was too long 🙃.
I have also added some pattern checks on `option_filter_map`
> New Lint: `result_filter_map` / Mirror of `option_filter_map`

- clippy_lints/src/assertions_on_constants.rs
- tests/ui/assertions_on_constants.rs
- tests/ui/assertions_on_constants.stderr
Fixes #8159
```rust
pub fn f() {
// warning
assert!(true);
assert!(usize::BITS >= 32);
// ok
const _: () = assert!(usize::BITS >= 32);
}
```
changelog: Fix `const _: () = assert!(expr)` false positive on `assertions_on_constants` lint
> Do not lint `assertions_on_constants` for `const _: () = assert!(expr)`

- util/gh-pages/index.html
> fix: broken GitHub corner

- clippy_lints/src/needless_bool.rs
- tests/ui/bool_comparison.fixed
- tests/ui/bool_comparison.rs
- tests/ui/bool_comparison.stderr
fixes: #9907 
---
changelog: stop [`bool_comparison`]'s suggestion from consuming parentheses
> stop [`bool_comparison`]'s suggestion from consuming parentheses

- clippy_lints/src/indexing_slicing.rs
- tests/ui-toml/suppress_lint_in_const/test.rs
- tests/ui-toml/suppress_lint_in_const/test.stderr
- tests/ui/crashes/ice-5497.rs
- tests/ui/crashes/ice-5497.stderr
- tests/ui/get_unwrap.fixed
- tests/ui/get_unwrap.rs
- tests/ui/get_unwrap.stderr
- tests/ui/indexing_slicing_index.rs
- tests/ui/indexing_slicing_index.stderr
fixes [Issue#11762](https://github.com/rust-lang/rust-clippy/issues/11762)
Issue#11762 points that `Array references with known length are not flagged when indexed out of bounds`.
To fix this problem, it is needed to add check for `Expr::Index`. We expand this issue include reference and direct accessing a array. 
When we access a array with a constant index `off`, and already know the length `size`, if `off >= size`, these code will throw an error, instead rustc's lint checking them or runtime panic happening.
changelog: [`out_of_bound_indexing`]: Add check for illegal accessing known length array with a constant index
> Check whether out of bound when access a known length array with a constant index

- clippy_lints/src/default_constructed_unit_structs.rs
- clippy_lints/src/implied_bounds_in_impls.rs
- clippy_lints/src/ineffective_open_options.rs
> Fixing some other typos

- clippy_lints/src/methods/unnecessary_to_owned.rs
- tests/ui/unnecessary_to_owned_on_split.fixed
- tests/ui/unnecessary_to_owned_on_split.rs
- tests/ui/unnecessary_to_owned_on_split.stderr
Fixes https://github.com/rust-lang/rust-clippy/issues/9965.
When you have `to_string().split('a')` or equivalent, it'll suggest to remove the `to_owned`/`to_string` part.
r? @flip1995 
changelog: Extend `UNNECESSARY_TO_OWNED` to handle `split`
> Extend `UNNECESSARY_TO_OWNED` to handle `split`

- clippy_lints/src/loops/infinite_loop.rs
- tests/ui/infinite_loops.stderr
changelog: This fixes a small typo introduced in https://github.com/rust-lang/rust-clippy/pull/11829
> fix typo in infinite loop lint

- clippy_lints/src/matches/manual_utils.rs
- clippy_lints/src/matches/redundant_pattern_match.rs
- clippy_lints/src/question_mark.rs
- clippy_lints/src/undocumented_unsafe_blocks.rs
- tests/ui/manual_let_else_question_mark.fixed
- tests/ui/manual_let_else_question_mark.rs
- tests/ui/manual_let_else_question_mark.stderr
This fixes the false negative mentioned in #11993: the lint only used to check for `return` expressions, and not a statement containing a `return` expression (doesn't close the issue tho since there's still a useful suggestion that we could make, which is to suggest `.ok_or()?`/`.ok_or_else()?` for `else { return Err(..) }`)
changelog: [`question_mark`]: also trigger on `return` statements
> [`question_mark`]: also trigger on `return` statements

- clippy_lints/src/uninhabited_references.rs
I think this lint has too many false positives and should be put in pedantic. See #11984 and #11985 for context.
The lint is already in beta and is causing trouble for us, so I would also like this PR to be backported to beta as well.
changelog: Moved [`uninhabited_references`] to `nursery` (Now allow-by-default)
[#11997](https://github.com/rust-lang/rust-clippy/pull/11997)
(Check if this has been backported)
Fixes #11984.
> Move `uninhabited_references` to `nursery`

- clippy_lints/src/redundant_async_block.rs
- tests/ui/redundant_async_block.fixed
- tests/ui/redundant_async_block.rs
changelog: [`redundant_async_block`]: do not trigger on `IntoFuture` instances
Fix #11959
> Do not consider `async { (impl IntoFuture).await }` as redundant

- CHANGELOG.md
- clippy_lints/src/iter_without_into_iter.rs
- clippy_lints/src/manual_hash_one.rs
Roses are red,
Another year of development,
And a strong team, too
---
<sub>The cat for the next release can be nominated in the comments</sub>
---
> Changelog for Rust 1.75 :christmas_tree:

- CHANGELOG.md
Roses are red,
another typo fixed,
thanks to you @llogiq 
---
r? @llogiq 
> Fix typo in changelog for 1.75

- book/src/lint_configuration.md
- clippy_config/src/conf.rs
- tests/ui/doc/doc-fixable.fixed
- tests/ui/doc/doc-fixable.rs
changelog: [`doc_markdown`]: Add "WebGL2", "WebGPU" to default `doc_valid_idents`
> [doc_markdown]: Add "WebGL2", "WebGPU" to default `doc_valid_idents`

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/transmute/eager_transmute.rs
- clippy_lints/src/transmute/mod.rs
- tests/ui/eager_transmute.fixed
- tests/ui/eager_transmute.rs
- tests/ui/eager_transmute.stderr
A small but still hopefully useful lint that looks for patterns such as `(x < 5).then_some(transmute(x))`.
This is almost certainly wrong because it evaluates the transmute eagerly and can lead to surprises such as the check being completely removed and always evaluating to `Some` no matter what `x` is (it is UB after all when the integer is not a valid bitpattern for the transmuted-to type). [Example](https://godbolt.org/z/xoY34fPzh).
The user most likely meant to use `then` instead.
I can't remember where I saw this but this is inspired by a real bug that happened in practice.
This could probably be a correctness lint?
changelog: new lint: [`eager_int_transmute`]
> new lint: `eager_transmute`

- clippy_lints/src/matches/redundant_pattern_match.rs
- tests/ui/redundant_pattern_matching_ipaddr.fixed
- tests/ui/redundant_pattern_matching_ipaddr.rs
- tests/ui/redundant_pattern_matching_ipaddr.stderr
- tests/ui/redundant_pattern_matching_poll.fixed
- tests/ui/redundant_pattern_matching_poll.rs
- tests/ui/redundant_pattern_matching_poll.stderr
Fixes #6459.
```
changelog: [`redundant_pattern_matching`]: Add checks for `Poll::{Ready,Pending}` and `IpAddr::{V4,V6}` in `matches!`
```
> 6459: Check for redundant `matches!` with `Ready`, `Pending`, `V4`, `V6`

- clippy_lints/src/methods/unnecessary_to_owned.rs
This change https://github.com/rust-lang/rust/pull/118420/files#r1419874371 adds a missing `write_args` to properly record node args for lang-item calls.
Thus, in the `unnecessary_to_owned` lint, this ensures that the `call_generic_args` extracted by `get_callee_generic_args_and_args` are always correct, and we can remove the mitigation for #9504 and #10021 since the root cause has been fixed.
I'm not sure if there is other now-unnecessary code that can be removed, but this is the one I found when investigating https://github.com/rust-lang/rust-clippy/issues/11965#issuecomment-1871732518.
> Remove mitigations for incorrect node args

- clippy_lints/src/iter_without_into_iter.rs
- tests/ui/into_iter_without_iter.rs
- tests/ui/into_iter_without_iter.stderr
- tests/ui/iter_without_into_iter.rs
- tests/ui/iter_without_into_iter.stderr
Fixes #12037
I think it's useful to still lint on local macros, since the user should still be able to add another impl with the `IntoIterator` or `iter` method. I think it's also fairly common to write a macro for generating many impls (e.g. for many similar types), so it'd be nice if we can continue linting in those cases.
For that reason I went with `in_external_macro`.
I also added a test for `#[allow]`ing the lint while I was at it.
changelog: [`iter_without_into_iter`]: don't lint if the `iter` method is defined in an external macro
changelog: [`into_iter_without_iter`]: don't lint if the `IntoIterator` impl is defined in an external macro
> add external macro checks to `iter_without_into_iter` and `into_iter_without_iter`

- clippy_lints/src/mutex_atomic.rs
- tests/ui/mutex_atomic.rs
- tests/ui/mutex_atomic.stderr
fixes: #9872 
---
changelog: [`mutex_atomic`] now suggests more specific atomic types and skips mutex i128 and u128
> make [`mutex_atomic`] more type aware

- clippy_lints/src/default_numeric_fallback.rs
- tests/ui/default_numeric_fallback_f64.fixed
- tests/ui/default_numeric_fallback_f64.rs
- tests/ui/default_numeric_fallback_f64.stderr
- tests/ui/default_numeric_fallback_i32.fixed
- tests/ui/default_numeric_fallback_i32.rs
- tests/ui/default_numeric_fallback_i32.stderr
fixes: #11535 
changelog: don't lint [`default_numeric_fallback`] on return and local assigned macro calls with type stated
> don't lint [`default_numeric_fallback`] on return and local assigned macro calls with type stated

- clippy_lints/src/unconditional_recursion.rs
- tests/ui/unconditional_recursion.rs
- tests/ui/unconditional_recursion.stderr
Follow-up of https://github.com/rust-lang/rust-clippy/pull/11938.
r? @llogiq 
changelog: Extend `UNCONDITIONAL_RECURSION` to check for `ToString` implementations
> Extend UNCONDITIONAL_RECURSION to check for ToString implementations

- clippy_lints/src/methods/mod.rs
> Add `.front()` to `get_first` lint description

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/thread_local_initializer_can_be_made_const.rs
- tests/ui/thread_local_initializer_can_be_made_const.fixed
- tests/ui/thread_local_initializer_can_be_made_const.rs
- tests/ui/thread_local_initializer_can_be_made_const.stderr
Adds a new lint to suggest using `const` on `thread_local!` initializers that can be evaluated at compile time.
Impl details:
The lint relies on the expansion of `thread_local!`. For non const-labelled initializers, `thread_local!` produces a function called `__init` that lazily initializes the value. We check the function and decide whether the body can be const. If so, we lint that the initializer value can be made const.
changelog: new lint [`thread_local_initializer_can_be_made_const`]
fixes: #12015
> New Lint: [`thread_local_initializer_can_be_made_const`]

- book/src/development/macro_expansions.md
- clippy_lints/src/methods/mod.rs
- clippy_lints/src/missing_asserts_for_indexing.rs
- clippy_lints/src/no_effect.rs
- clippy_lints/src/serde_api.rs
- clippy_lints/src/wildcard_imports.rs
- clippy_utils/src/ty/type_certainty/mod.rs
- tests/ui/as_conversions.rs
- tests/ui/default_numeric_fallback_i32.fixed
- tests/ui/default_numeric_fallback_i32.rs
- tests/ui/redundant_as_str.fixed
- tests/ui/redundant_as_str.rs
- tests/ui/regex.rs
- tests/ui/struct_fields.rs
- tests/ui/useless_conversion.fixed
- tests/ui/useless_conversion.rs
> Fix some typos

- clippy_lints/src/operators/identity_op.rs
- tests/ui/identity_op.fixed
- tests/ui/identity_op.rs
- tests/ui/identity_op.stderr
When `identity_op` identifies a `no_op`, provides a suggestion, it also checks the type of the type of the variable. If the variable is a reference that's been coerced into a value, e.g.
```
let x = &0i32;
let _ = x + 0;
```
the suggestion will now use a derefence. This is done by identifying whether the variable is a reference to an integral value, and then whether it gets dereferenced.
changelog: false positive: [`identity_op`]: corrected suggestion for reference coerced to value.
fixes: #12050
> Fixes: #12050 - `identity_op` correctly suggests a deference for coerced references

- clippy_lints/src/unconditional_recursion.rs
- tests/ui/unconditional_recursion.rs
- tests/ui/unconditional_recursion.stderr
Fixes #12052.
Only checking if both variables are `local` was not enough, we also need to confirm they have the same type as `Self`.
changelog: Fix false positive for `unconditional_recursion` lint
> Fix false positive `unconditional_recursion`

- clippy_lints/src/instant_subtraction.rs
See <https://rust-lang.github.io/rust-clippy/master/index.html#unchecked_duration_subtraction>
changelog: [`unchecked_duration_subtraction`]: remove deadlinks
> Remove deadlinks from `unchecked_duration_subtraction`

- clippy_lints/src/transmute/eager_transmute.rs
- tests/ui/eager_transmute.fixed
- tests/ui/eager_transmute.rs
- tests/ui/eager_transmute.stderr
This PR makes the lint a bit stronger. Previously it would only lint `(x < 4).then_some(transmute(x))` (that is, a single binary op in the condition). With this change, it understands:
- multiple, nested binary ops: `(x < 4 && x > 1).then_some(...)`
- local references with projections: `(x.field < 4 && x.field > 1).then_some(transmute(x.field))`
changelog: [`eager_transmute`]: lint nested binary operations and look through field/array accesses
r? llogiq (since you reviewed my initial PR #11981, I figured you have the most context here, sorry if you are too busy with other PRs, feel free to reassign to someone else then)
> Lint nested binary operations and handle field projections in `eager_transmute`

- COPYRIGHT
- LICENSE-APACHE
- LICENSE-MIT
- README.md
- rustc_tools_util/README.md
Our license was outdated by a year (+ change in the main README.md)
changelog:none
> Update copyright year for Clippy (2024 edition)

- book/src/SUMMARY.md
- book/src/continuous_integration/gitlab.md
Fixes #12012
changelog: Docs: [`Continuous Integration`] now includes how to use clippy in GitLab CI.
> Include GitLab in the CI section of the clippy doc book

- clippy_config/src/conf.rs
- clippy_config/src/metadata.rs
fixes #12042 
This PR addresses the issue where the `metadata collector` incorrectly generates the `Affected Lints` section when a comma is included in the configuration documentation.
I made adjustments; however, if the `/// Lint: SOMETHING` section ends with `.` it always produces the correct output.
For example, 
```rust
/// Lint: PUB_UNDERSCORE_FIELDS
```
should be
```rust
/// Lint: PUB_UNDERSCORE_FIELDS.
```
> fix: metadata-collector lists wrong affected lints

- clippy_lints/src/lib.rs
- clippy_lints/src/unconditional_recursion.rs
- tests/ui/unconditional_recursion.rs
- tests/ui/unconditional_recursion.stderr
In case the `Default` trait is implemented manually and is calling a static method (let's call it `a`) and then `a` is using `Self::default()`, it makes an infinite call recursion difficult to see without debugging. This extension checks that there is no such recursion possible.
r? @llogiq 
changelog: Extend `unconditional_recursion` lint to check for `Default` trait implementation
> Extend `unconditional_recursion` lint to check for `Default` trait implementation

- CHANGELOG.md
- README.md
- book/src/README.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/methods/mod.rs
- clippy_lints/src/methods/option_as_ref_cloned.rs
- tests/ui/option_as_ref_cloned.fixed
- tests/ui/option_as_ref_cloned.rs
- tests/ui/option_as_ref_cloned.stderr
Closes #12009
Adds a new lint that looks for `.as_ref().cloned()` on `Option`s. That's the same as just `.clone()`-ing the option directly.
changelog: new lint: [`option_as_ref_cloned`]
> new lint: `option_as_ref_cloned`

- clippy_lints/src/methods/unnecessary_to_owned.rs
- tests/ui/unnecessary_to_owned_on_split.fixed
- tests/ui/unnecessary_to_owned_on_split.rs
- tests/ui/unnecessary_to_owned_on_split.stderr
The case of `.to_owned().split(…)` is treated specially in the `unnecessary_to_owned` lint. Test cases check that it works both for slices and for strings, but they missed a corner case: `x.to_string().split(…)` when `x` implements `AsRef<str>` but not `Deref<Target = str>`. In this case, it is wrong to suggest to remove `.to_string()` without adding `.as_ref()` instead.
Fix #12068
changelog: [`unnecessary_to_owned`]: suggest replacing `.to_string()` by `.as_ref()`
> Add .as_ref() to suggestion to remove .to_string()

- clippy_lints/src/undocumented_unsafe_blocks.rs
- tests/ui/unnecessary_safety_comment.rs
Fixes #12048.
What happened in the linked issue is that the lint checks for lines that start with `//` and have `SAFETY:` somewhere in it above the function item.
This works for regular comments, but when the `//` is the start of a doc comment (e.g. `/// // SAFETY: ...`) and it's part of a doc test (i.e. within \`\`\`), we probably shouldn't lint that, since the user most likely meant to refer to a different node than the one currently being checked. For example in the linked issue, the safety comment refers to `unsafe { *five_pointer }`, but the lint believes it's part of the function item.
We also can't really easily test whether the `// SAFETY:` comment within a doc comment is necessary or not, since I think that would require creating a new compiler session to re-parse the contents of …
> Don't look for safety comments in doc tests

- clippy_lints/src/missing_enforced_import_rename.rs
* Fixes a typo in the name of the lint (`enforce-import-renames` instead of `enforced-import-renames`).
* Copyedit “Why” paragraph.
* Make the example configuration use a multi-line list, since it is not particularly expected that a real project will have *exactly one* rename to enforce (and the old formatting had unbalanced whitespace).
> Polish `missing_enforced_import_renames` documentation

- clippy_lints/src/item_name_repetitions.rs
- tests/ui/struct_fields.rs
- tests/ui/struct_fields.stderr
Fixes #11936.
I only checked that all fields are booleans and not the prefix (nor the suffix) because when I started to list accepted prefixes (like "is", "has", "should", "could", etc), the list was starting to get a bit too long and I thought it was not really worth for such a small change.
r? @llogiq 
changelog: Don't emit `struct_field_names` lint if all fields are booleans and don't start with the type's name
> Don't emit `struct_field_names` lint if all fields are booleans and don't start with the type's name

- clippy_utils/src/eager_or_lazy.rs
- tests/ui/unnecessary_lazy_eval.fixed
- tests/ui/unnecessary_lazy_eval.rs
- tests/ui/unnecessary_lazy_eval.stderr
Fixes the bug reported by @ju1ius in https://github.com/rust-lang/rust-clippy/issues/9427#issuecomment-1878428001.
`eager_or_lazy` already understands to suppress eagerness changes when the expression type has a significant drop impl, but only for initialization of tuple structs or unit structs. This changes it to also avoid changing it for `Self { .. }` and `TypeWithDrop { .. }`
changelog: [`unnecessary_lazy_eval`]: don't suggest changing eagerness for struct literal syntax when type has a significant drop impl
> don't change eagerness for struct literal syntax with significant drop

- clippy_lints/src/methods/map_clone.rs
- clippy_utils/src/macros.rs
- tests/ui/useless_asref.fixed
- tests/ui/useless_asref.rs
- tests/ui/useless_asref.stderr
I found it weird that this case was not handled by the current line so I added it. The only thing is that I don't see an obvious way to infer the current type to determine if it's copyable or not, so for now I always suggest `cloned` and I added a FIXME.
r? @llogiq 
changelog: Extend `map_clone` lint to also work on non-explicit closures
> Extend `map_clone` lint to also work on non-explicit closures

- clippy_lints/src/vec.rs
- tests/ui/vec.fixed
- tests/ui/vec.rs
changelog: [`useless_vec`]: do not suggest replacing `&vec![T; N]` by `&[T; N]` if `T` is not `Copy`
Fix #11958
> Do not suggest `[T; n]` instead of `vec![T; n]` if `T` is not `Copy`

- clippy_lints/src/casts/cast_sign_loss.rs
- tests/ui/cast.rs
- tests/ui/cast.stderr
fixes: #11642 
changelog: improve [`cast_sign_loss`] to skip warning on always positive expressions
Turns out this is change became quite big, and I still can't cover all the cases, like method calls such as `POSITIVE_NUM.mul(POSITIVE_NUM)`, or `NEGATIVE_NUM.div(NEGATIVE_NUM)`... but well, if I do, I'm scared that this will goes forever, so I stopped, unless it needs to be done, lol.
> improve [`cast_sign_loss`], to skip warning on always positive expressions

- clippy_lints/src/if_then_some_else_none.rs
- tests/ui/if_then_some_else_none.rs
Fix #12103
changelog: [`if_then_some_else_none`]: Do not trigger in `const` contexts
> Do not suggest `bool::then()` and `bool::then_some` in `const` contexts

- clippy_lints/src/methods/map_clone.rs
- tests/ui/map_clone.fixed
- tests/ui/map_clone.rs
- tests/ui/map_clone.stderr
Follow-up of https://github.com/rust-lang/rust-clippy/pull/12104.
I just realized that I didn't handle the case where the `clone` method was made as a call and not a method call.
r? @llogiq 
changelog: Handle "calls" inside the closure as well in `map_clone` lint
> Handle "calls" inside the closure as well in `map_clone` lint

- clippy_lints/src/methods/filter_map.rs
- clippy_lints/src/methods/iter_filter.rs
- tests/ui/iter_filter_is_ok.fixed
- tests/ui/iter_filter_is_ok.rs
- tests/ui/iter_filter_is_ok.stderr
- tests/ui/iter_filter_is_some.fixed
- tests/ui/iter_filter_is_some.rs
- tests/ui/iter_filter_is_some.stderr
Issue: in https://github.com/rust-lang/rust-clippy/pull/12004, we emit a lint for `filter(Option::is_some)`. If the
parent expression is a `.map` we don't emit that lint as there exists a
more specialized lint for that.
The ICE introduced in https://github.com/rust-lang/rust-clippy/pull/12004 is a consequence of the assumption that a
parent expression after a filter would be a method call with the filter
call being the receiver. However, it is entirely possible to have a
closure of the form
```
|| { vec![Some(1), None].into_iter().filter(Option::is_some) }
```
The previous implementation looked at the parent expression; namely the
closure, and tried to check the parameters by indexing [0] on an empty
list.
This commit is an overhaul of the lint with significantly more FP tests
and checks. …
> Fixed ICE introduced in #12004

- clippy_lints/src/non_octal_unix_permissions.rs
- tests/ui/non_octal_unix_permissions.fixed
- tests/ui/non_octal_unix_permissions.rs
- tests/ui/non_octal_unix_permissions.stderr
fixes [Issue#11243](https://github.com/rust-lang/rust-clippy/issues/11243)
Issue#11243 suggest lint `non_octal_unix_permissions` should not report binary format literal unix permissions as an error, and we think binary format is a good way to understand these permissions.
To solve this problem, we need to add check for binary literal, which is written in function `check_binary_unix_permissions` , only `binary, 3 groups and each group length equals to 3` is a legal format.
changelog: [`non_octal_unix_permissions`]: Add check for binary format literal unix permissions like 0b111_111_111
> fix/issue#11243: allow 3-digit-grouped binary in non_octal_unix_permissions

- clippy_lints/src/methods/map_clone.rs
- clippy_lints/src/methods/useless_asref.rs
- tests/ui/map_clone.fixed
- tests/ui/map_clone.rs
- tests/ui/map_clone.stderr
- tests/ui/useless_asref.fixed
- tests/ui/useless_asref.rs
- tests/ui/useless_asref.stderr
If you have code like:
```rust
Some(String::new()).as_ref().map(Clone::clone)
```
the `as_ref` call is unneeded.
Interestingly enough, this lint and `map_clone` are starting to share a same "space" where both lints warn about different things for the same code. Not sure what's the policy about such cases though...
r? @llogiq 
changelog: Extend `useless_asref` lint on `map(clone)`
> Extend `useless_asref` lint on `map(clone)`

- triagebot.toml
I've been less active in Clippy recently because I'm so busy that I don't have time for maintaining Clippy in my spare time. So, I remove myself from the reviewer rotation once. I hope to come back again.
I'll reassign the PRs later.
> Remove giraffate from the reviewer rotation

- triagebot.toml
A few weeks ago I opened #12011 removing me from `users_on_vacation`, it got merged. The subtree sync reverted this change (weirdly)
r? @xFrednet
> I'm not on vacation (again)

- clippy_lints/src/methods/map_clone.rs
- tests/ui/map_clone.fixed
- tests/ui/map_clone.rs
- tests/ui/map_clone.stderr
Follow-up of https://github.com/rust-lang/rust-clippy/pull/12104.
It was missing this check to suggest the correct method.
r? @llogiq 
changelog: Fix suggestion for `map_clone` lint on types implementing `Copy`
> Fix suggestion for `map_clone` lint on types implementing `Copy`

- clippy_lints/src/unconditional_recursion.rs
- tests/ui/unconditional_recursion.rs
- tests/ui/unconditional_recursion.stderr
Fixes https://github.com/rust-lang/rust-clippy/issues/12133.
We needed to check for the type of the previous element <del>in case it's a field</del>.
EDIT: After some extra thoughts, no need to check if it's a field, just if it's the same type as `Self`.
r? @llogiq 
changelog: Fix false positive in `PartialEq` check in `unconditional_recursion` lint
> Fix false positive in `PartialEq` check in `unconditional_recursion` lint

- clippy_lints/src/methods/search_is_some.rs
- tests/ui/crashes/ice-9041.stderr
- tests/ui/search_is_some.stderr
- tests/ui/search_is_some_fixable_none.stderr
- tests/ui/search_is_some_fixable_some.stderr
Fixes #11681.
Like mentioned in the issue, we tend to use the formulation "consider using", which we didn't in this case. I think it clears both the confusion and also makes help message more coherent overall.
r? @llogiq 
changelog: Improve help message for `search_is_some` lint
> Improve help message for `search_is_some` lint

- clippy_utils/src/hir_utils.rs
- tests/ui/branches_sharing_code/shared_at_top.rs
- tests/ui/branches_sharing_code/shared_at_top.stderr
- tests/ui/branches_sharing_code/valid_if_blocks.rs
- tests/ui/branches_sharing_code/valid_if_blocks.stderr
- tests/ui/if_same_then_else.rs
- tests/ui/if_same_then_else.stderr
- tests/ui/if_same_then_else2.rs
- tests/ui/if_same_then_else2.stderr
- tests/ui/match_same_arms2.rs
- tests/ui/match_same_arms2.stderr
This PR:
- now makes `HirEqInterExpr::eq_block` take comments into account. Identical code with varying comments will no longer be considered equal.
- makes necessary adjustments to UI tests.
Closes #12044 
**Lintcheck Changes**
- `match_same_arms` 53 => 52
- `if_same_then_else` 3 => 0
changelog: [`if_same_then_else`]: Blocks with different comments will no longer trigger this lint.
changelog: [`match_same_arms`]: Arms with different comments will no longer trigger this lint.
```
> Make `HirEqInterExpr::eq_block` take comments into account while checking if two blocks are equal

- clippy_lints/src/arc_with_non_send_sync.rs
Arc's documentation uses the term "thread"; aligning to that terminology. Fix casing of "Rc".
> ['arc_with_non_send_sync`] documentation edits

- clippy_lints/src/from_over_into.rs
- tests/ui/from_over_into.fixed
- tests/ui/from_over_into.rs
- tests/ui/from_over_into.stderr
changelog: [`from_over_into`]: suggest a correct conversion to `()`
Fix #12138
> from_over_into: suggest a correct conversion to ()

- clippy_lints/src/methods/useless_asref.rs
- tests/ui/useless_asref.fixed
- tests/ui/useless_asref.rs
- tests/ui/useless_asref.stderr
Fixes #12135
There was no check for the receiver of the `clone` call in the map closure. This makes sure that it's a path to the parameter.
changelog: [`useless_asref`]: check that the clone receiver is the closure parameter
> [`useless_asref`]: check that the clone receiver is the parameter

- book/src/lint_configuration.md
- clippy_config/src/conf.rs
- tests/ui/doc/doc-fixable.fixed
- tests/ui/doc/doc-fixable.rs
The OpenTelemetry project's name is all one word (see https://opentelemetry.io), so currently triggers a false positive in the `doc_markdown` lint.
The project is increasing rapidly in popularity, so it seems like a worthy contender for inclusion in the default `doc_valid_idents` configuration.
I've also moved the existing "OpenDNS" entry earlier in the list, to restore the alphabetical ordering of that "Open*" row.
The docs changes were generated using `cargo collect-metadata`.
changelog: [`doc_markdown`]: Add `OpenTelemetry` to the default configuration as an allowed identifier
> Add "OpenTelemetry" to default `doc_valid_idents`

- clippy_lints/src/default_instead_of_iter_empty.rs
- clippy_lints/src/mem_replace.rs
- clippy_lints/src/methods/iter_on_single_or_empty_collections.rs
- clippy_lints/src/methods/unnecessary_sort_by.rs
- clippy_lints/src/operators/ptr_eq.rs
- clippy_lints/src/transmute/transmute_int_to_char.rs
- clippy_lints/src/transmute/transmute_ref_to_ref.rs
- tests/ui/default_instead_of_iter_empty_no_std.fixed
- tests/ui/default_instead_of_iter_empty_no_std.rs
- tests/ui/default_instead_of_iter_empty_no_std.stderr
- tests/ui/mem_replace_no_std.fixed
- tests/ui/mem_replace_no_std.rs
- tests/ui/mem_replace_no_std.stderr
- tests/ui/ptr_eq_no_std.fixed
- tests/ui/ptr_eq_no_std.rs
- tests/ui/ptr_eq_no_std.stderr
- tests/ui/transmute.rs
- tests/ui/transmute.stderr
- tests/ui/transmute_int_to_char.fixed
- tests/ui/transmute_int_to_char.rs
- tests/ui/transmute_int_to_char.stderr
- tests/ui/transmute_int_to_char_no_std.fixed
- tests/ui/transmute_int_to_char_no_std.rs
- tests/ui/transmute_int_to_char_no_std.stderr
- tests/ui/transmute_ref_to_ref.stderr
- tests/ui/transmute_ref_to_ref_no_std.rs
- tests/ui/transmute_ref_to_ref_no_std.stderr
- tests/ui/unnecessary_sort_by.stderr
A few lints emit suggestions using `std` paths whether or not this is a `no_std` crate, which is an issue when running `rustfix` afterwards. So in case this is an item that is defined in both `std` and `core`, we need to check if the crate is `no_std` to emit the right path.
r? @llogiq 
changelog: Correctly suggest std or core path depending if this is a `no_std` crate
> Correctly suggest std or core path depending if this is a `no_std` crate

- clippy_lints/src/arc_with_non_send_sync.rs
changelog: [`arc_with_non_send_sync`]: Improve wording and fix dead link.
> Try to improve wording and fix dead link in description of arc_with_non_send_sync lint.

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/methods/mod.rs
- clippy_lints/src/methods/open_options.rs
- clippy_utils/src/paths.rs
- tests/ui/ineffective_open_options.fixed
- tests/ui/ineffective_open_options.rs
- tests/ui/open_options.rs
- tests/ui/open_options.stderr
- tests/ui/open_options_fixable.fixed
- tests/ui/open_options_fixable.rs
- tests/ui/open_options_fixable.stderr
- tests/ui/seek_to_start_instead_of_rewind.fixed
- tests/ui/seek_to_start_instead_of_rewind.rs
- tests/ui/seek_to_start_instead_of_rewind.stderr
changelog: [`suspicious_open_options`]: Checks for the suspicious use of std::fs::OpenOptions::create() without an explicit OpenOptions::truncate().
create() alone will either create a new file or open an existing file. If the file already exists, it will be overwritten when written to, but the file will not be truncated by default. If less data is written to the file than it already contains, the remainder of the file will remain unchanged, and the end of the file will contain old data.
In most cases, one should either use `create_new` to ensure the file is created from scratch, or ensure `truncate` is called so that the truncation behaviour is explicit. `truncate(true)` will ensure the file is entirely overwritten with new data, whereas `truncate(false)` will explicitely keep the …
> Add suspicious_open_options lint.

- clippy_lints/src/read_zero_byte_vec.rs
- tests/ui/read_zero_byte_vec.rs
- tests/ui/read_zero_byte_vec.stderr
Fixes #9274 
Previously, the implementation of `read_zero_byte_vec` only checks for the next statement after the vec init. This fails when there is a block with statements that are expanded and walked by the old visitor.
This PR refactors so that:
1. It checks if there is a `resize`	on the vec
2. It works on blocks properly
e.g. This should properly lint now:
```
let mut v = Vec::new();
{
f.read(&mut v)?;
//~^ ERROR: reading zero byte data to `Vec`
}
```
changelog: [`read_zero_byte_vec`] Refactored for better heuristics
> `read_zero_byte_vec` refactor for better heuristics

- clippy_lints/src/trait_bounds.rs
- tests/ui/trait_duplication_in_bounds.fixed
- tests/ui/trait_duplication_in_bounds.rs
Fixes #9961.
The generic bounds were not correctly checked and left out `QPath::TypeRelative`, making different bounds look the same and generating invalid errors (and fix).
r? @blyxyas 
changelog: [`trait_duplication_in_bounds`]: Correctly handle type relative.
> Correctly handle type relative in trait_duplication_in_bounds lint

- clippy_lints/src/cargo/multiple_crate_versions.rs
- tests/ui-cargo/multiple_crate_versions/12145_with_dashes/Cargo.stderr
- tests/ui-cargo/multiple_crate_versions/12145_with_dashes/Cargo.toml
- tests/ui-cargo/multiple_crate_versions/12145_with_dashes/src/main.rs
Fixes #12145 
changelog: [`multiple_crate_versions`]: correctly normalize package name
> Fix [`multiple_crate_versions`] to correctly normalize package names to avoid missing the local one

- clippy_lints/src/default_numeric_fallback.rs
- tests/ui/default_numeric_fallback_i32.fixed
- tests/ui/default_numeric_fallback_i32.rs
Fixes #12159
The lint didn't actually recognize any of the associated consts (in the linked issue), because in those cases the parent is an `ImplItem` and not an `Item`, but it only actually emitted a lint for i32 and f64 because the other cases failed the very last check here
https://github.com/rust-lang/rust-clippy/blob/bb2d4973648b1af18d7ba6a3028ed7c92fde07fb/clippy_lints/src/default_numeric_fallback.rs#L91-L96
A better check for detecting constness would be using `body_const_context`, which is what this PR does.
changelog: [`default_numeric_fallback`]: recognize associated consts
> [`default_numeric_fallback`]: improve const context detection

- clippy_lints/src/semicolon_if_nothing_returned.rs
- tests/ui/auxiliary/proc_macro_attr.rs
- tests/ui/semicolon_if_nothing_returned.fixed
- tests/ui/semicolon_if_nothing_returned.rs
- tests/ui/semicolon_if_nothing_returned.stderr
fixes: #12123 
---
changelog: fix FP on [`semicolon_if_nothing_returned`] which suggesting adding semicolon after attr macro
> fix FP on [`semicolon_if_nothing_returned`]

- clippy_lints/src/blocks_in_conditions.rs
- tests/ui/blocks_in_conditions.fixed
- tests/ui/blocks_in_conditions.rs
changelog: [`blocks_in_conditions`]: do not warn if condition comes from macro
Fix #12162
> blocks_in_conditions: do not warn if condition comes from macro

- clippy_lints/src/no_effect.rs
- tests/ui/no_effect.stderr
fixes [Issue#12045](https://github.com/rust-lang/rust-clippy/issues/12045)
In issue#12045, unexpected warning span occurs on attribute `#[derive(typed_builder::TypedBuilder)]`, actually the warning should underline `_lifetime`.
In the source code we can find that the original intend is to warning on `ident.span`, but in this case, `stmt.span` is unequal with `ident.span`. So, fix the nit here is fine.
Besides, `ident.span` have an accurate range than `stmt.span`.
changelog: [`no_effect_underscore_binding`]: correct warning span
> Fix error warning span for issue12045

- clippy_lints/src/needless_pass_by_ref_mut.rs
This removes a visitor that existed to collect paths to functions in a context where the exact signature is required in order to cancel the lint.
E.g. when there's a `let _: fn(&mut i32) = path_to_fn_ref_mut_i32;` statement somewhere in the crate, we shouldn't suggest removing the mutable reference in the function signature.
It was doing a whole pass through the crate at the end, which seems unnecessary.
It seems like we should be able to add entries to the map in the same lint pass.
The map is untouched all the way until `check_crate_post` (at which point it will be populated by the visitor and finally checked), so it doesn't seem like this changes behavior: it will only be fully populated by the time we reach `check_crate_post` no matter what.
I don't think this will have a significant …
> Find function path references early in the same lint pass

- book/src/lint_configuration.md
- clippy_config/src/conf.rs
- clippy_config/src/types.rs
- clippy_lints/src/pub_underscore_fields.rs
- tests/ui-toml/pub_underscore_fields/exported/clippy.toml
Fixes https://github.com/rust-lang/rust-clippy/pull/10283#issuecomment-1890600381
In the "/// Lint: " list on each configuration option, you have to end with a dot. If the lint list doesn't have a dot, the configuration won't have documentation.
This PR adds those missing dots in some of the configuration, thus also adding their documentation.
changelog: Fix bug where a lot of config documentation wasn't showing.
changelog: Fix typo in `pub_underscore_fields_behavior` (`PublicallyExported` -> `PubliclyExported`)
> Add . to end of lint lists in configuration + Fix typo in pub_underscore_fields_behavior

- clippy_lints/src/lib.rs
- clippy_lints/src/no_effect.rs
- tests/ui/no_effect.rs
Prefixing a variable with a `_` does not mean that it will not be used. If such a variable is used later, do not warn about the fact that its initialization does not have a side effect as this is fine.
changelog: [`no_effect_underscore_binding`]: warn only if variable is unused
Fix #12166
> no_effect_underscore_binding: _ prefixed variables can be used

- clippy_lints/src/unused_io_amount.rs
- tests/ui/unused_io_amount.rs
- tests/ui/unused_io_amount.stderr
Partial rewrite of `unused_io_amount` to lint over `Ok(_)` and `Ok(..)`.
Moved the check to `check_block` to simplify context checking for expressions and allow us to check only some expressions.
For match (expr, arms) we emit a lint for io ops used on `expr` when an arm is `Ok(_)|Ok(..)`. Also considers the cases when there are guards in the arms and `if let Ok(_) = ...` cases.
For `Ok(_)` and `Ok(..)` it emits a note indicating where the value is ignored.
changelog: False Negatives [`unused_io_amount`]: Extended `unused_io_amount` to catch `Ok(_)`s in `If let` and match exprs.
Closes #11713 
r? @giraffate
> `unused_io_amount` captures `Ok(_)`s

- clippy_lints/src/loops/same_item_push.rs
- clippy_lints/src/methods/join_absolute_paths.rs
- clippy_lints/src/methods/manual_saturating_arithmetic.rs
- clippy_lints/src/methods/option_as_ref_deref.rs
- clippy_lints/src/methods/option_map_or_err_ok.rs
- clippy_lints/src/methods/option_map_or_none.rs
- clippy_lints/src/methods/result_map_or_else_none.rs
- clippy_lints/src/methods/single_char_pattern.rs
- clippy_lints/src/methods/unnecessary_join.rs
- clippy_lints/src/utils/internal_lints/almost_standard_lint_formulation.rs
- tests/ui-internal/check_formulation.stderr
- tests/ui/join_absolute_paths.stderr
- tests/ui/manual_ok_or.stderr
- tests/ui/manual_saturating_arithmetic.stderr
- tests/ui/option_as_ref_deref.stderr
- tests/ui/option_map_or_err_ok.stderr
- tests/ui/option_map_or_none.stderr
- tests/ui/result_map_or_into_option.stderr
- tests/ui/same_item_push.stderr
- tests/ui/single_char_pattern.stderr
- tests/ui/unnecessary_join.stderr
Follow-up of https://github.com/rust-lang/rust-clippy/pull/12140.
r? @llogiq 
changelog: Improve wording for suggestion messages
> Improve wording for suggestion messages

- clippy_lints/src/derive.rs
- clippy_utils/src/attrs.rs
- tests/ui/derive_partial_eq_without_eq.fixed
- tests/ui/derive_partial_eq_without_eq.rs
Part of https://github.com/rust-lang/rust-clippy/issues/9063.
If a type has a field/variant with the `#[non_exhaustive]` attribute or the type itself has it, then do no emit the `derive_partial_eq_without_eq` lint.
changelog: Don't emit `derive_partial_eq_without_eq` lint if the type has the `non_exhaustive` attribute
> Don't emit `derive_partial_eq_without_eq` lint if the type has the `non_exhaustive` attribute

- clippy_lints/src/single_call_fn.rs
- tests/ui/single_call_fn.rs
Fixes #12182
If we delay linting to `check_crate_post`, we need to use `span_lint_hir_and_then`, since otherwise it would only respect those lint level attributes at the crate root.
<sub>... maybe we can have an internal lint for this somehow?</sub>
changelog: respect `#[allow]` attributes in `single_call_fn` lint
> respect `#[allow]` attributes in `single_call_fn` lint

- CHANGELOG.md
- book/src/lint_configuration.md
- clippy_config/src/conf.rs
- clippy_lints/src/cargo/mod.rs
- clippy_lints/src/cargo/multiple_crate_versions.rs
- clippy_lints/src/lib.rs
- tests/ui-cargo/multiple_crate_versions/12176_allow_duplicate_crates/Cargo.toml
- tests/ui-cargo/multiple_crate_versions/12176_allow_duplicate_crates/clippy.toml
- tests/ui-cargo/multiple_crate_versions/12176_allow_duplicate_crates/src/main.rs
- tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
Closes #12176
changelog: [`multiple_crate_versions`]: add a configuration option for allowed duplicate crates
> [`multiple_crate_versions`]: add a configuration option for allowed duplicate crates

- clippy_config/src/conf.rs
- clippy_config/src/lib.rs
- tests/ui-toml/toml_unknown_key/clippy.toml
- tests/ui-toml/toml_unknown_key/conf_unknown_key.rs
- tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
While working on/testing #12179, I made the mistake of using underscores instead of dashes for the field name in the clippy.toml file and ended up being confused for a few minutes until I found out what's wrong. With this change, clippy will suggest an existing field if there's one that's similar.
```
1 | allow_mixed_uninlined_format_args = true
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: perhaps you meant: `allow-mixed-uninlined-format-args`
```
(in hindsight, the current behavior of printing all the config options makes it obvious in most cases but I still think a suggestion like this would be nice to have)
I had to play around with the value a bit. A max distance of 5 seemed a bit too strong since it'd suggest changing `foobar` to `msrv`, which seemed odd, and 4 seemed just good enough …
> Suggest existing configuration option if one is found

- clippy_lints/src/eta_reduction.rs
- tests/ui/eta.fixed
- tests/ui/eta.rs
- tests/ui/eta.stderr
Fixes #12199
Not sure if there's a nicer way to detect functions marked `#[track_caller]` other than by just looking at its attributes 🤔 
changelog: [`redundant_closure`]: [`redundant_closure_for_method_calls`]: avoid linting closures where the function being called is marked `#[track_caller]`
> Avoid linting redundant closure when callee is marked `#[track_caller]`

- CHANGELOG.md
- clippy_config/src/msrvs.rs
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/incompatible_msrv.rs
- clippy_lints/src/lib.rs
- tests/ui-toml/min_rust_version/min_rust_version.fixed
- tests/ui-toml/min_rust_version/min_rust_version.rs
- tests/ui/incompatible_msrv.rs
- tests/ui/incompatible_msrv.stderr
Part of https://github.com/rust-lang/rust-clippy/issues/6324.
~~Currently, the lint is not working for the simple reason that the `stable` attribute is not kept in dependencies. I'll send a PR to rustc to see if they'd be okay with keeping it.~~
EDIT: There was actually a `lookup_stability` function providing this information, so all good now!
cc @epage
changelog: create new [`incompatible_msrv`] lint
> Warn if an item coming from more recent version than MSRV is used 

- clippy_lints/src/redundant_closure_call.rs
- tests/ui/redundant_closure_call_fixable.fixed
- tests/ui/redundant_closure_call_fixable.rs
There are cases where the closure call is needed in some macros, this in particular occurs when the closure has parameters. To handle this case, we allow the lint when there are no parameters in the closure, or the closure is outside a macro invocation.
fixes: #11274 #1553
changelog: FP: [`redundant_closure_call`] when closures with parameters are passed in macros.
> Fixed FP in `redundant_closure_call` when closures are passed to macros

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/returns.rs
- clippy_lints/src/to_string_trait_impl.rs
- tests/ui/format_args.fixed
- tests/ui/format_args.rs
- tests/ui/format_args.stderr
- tests/ui/to_string_trait_impl.rs
- tests/ui/to_string_trait_impl.stderr
- tests/ui/unconditional_recursion.rs
- tests/ui/unconditional_recursion.stderr
- tests/ui/unnecessary_to_owned.fixed
- tests/ui/unnecessary_to_owned.rs
- tests/ui/unnecessary_to_owned.stderr
- tests/ui/unnecessary_to_owned_on_split.fixed
- tests/ui/unnecessary_to_owned_on_split.rs
- tests/ui/unnecessary_to_owned_on_split.stderr
closes #12076
changelog: [`to_string_trait_impl`]: add lint for direct `ToString` implementations
> add to_string_trait_impl lint

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/methods/map_unwrap_or.rs
- clippy_lints/src/methods/mod.rs
- clippy_lints/src/methods/unnecessary_result_map_or_else.rs
- tests/ui/unnecessary_result_map_or_else.fixed
- tests/ui/unnecessary_result_map_or_else.rs
- tests/ui/unnecessary_result_map_or_else.stderr
Fixes https://github.com/rust-lang/rust-clippy/issues/7328.
r? @llogiq 
changelog: Add new `unnecessary_result_map_or_else` lint
> Add new `unnecessary_result_map_or_else` lint

- clippy_lints/src/loops/never_loop.rs
- tests/ui/never_loop.rs
Fixes #12205
The old code assumed that only blocks with an explicit label can be jumped to (using `break`). This is mostly correct except for `try` desugaring, where the `?` operator is rewritten to a `break` to that block, even without a label on the block. `Block::targeted_by_break` is a little more accurate than just checking if a block has a label in that regard, so we should just use that instead
changelog: [`never_loop`]: avoid linting when `?` is used inside of a try block
> [`never_loop`]: recognize desugared `try` blocks

- clippy_lints/src/booleans.rs
- tests/ui/nonminimal_bool.rs
fixes [Issue#11932](https://github.com/rust-lang/rust-clippy/issues/11932)
After `assert`, `assert_eq`, `assert_ne`, etc, assert family marcos unrolling in multi-condition expressions, lint `nonminimal_bool` will recognize whole expression as a entirety, analyze each simple condition expr of them, and check whether can simplify them.
But `assert` itself is a entirety to programmers, we don't need to lint on `assert`. This commit add check whether lint snippet contains `assert` when try to warning to an expression.
changelog: [`nonminimal_bool`] add check for condition expression
> Fix/Issue11932: assert* in multi-condition after unrolling will cause lint `nonminimal_bool` emit warning

- clippy_lints/src/manual_retain.rs
- tests/ui/manual_retain.fixed
- tests/ui/manual_retain.rs
- tests/ui/manual_retain.stderr
fixes #10393, fixes #11457, fixes #12081
#10393: In the current implementation of `manual_retain`, if the argument to the closure is matched using tuple, they are all treated as the result of a call to `map.into_iter().filter(<f>)`. However, such tuple pattern matching can also occur in many different containers that stores tuples internally. The correct approach is to apply different lint policies depending on whether the receiver of `into_iter` is a map or not.
#11457 and #12081: In the current implementation of `manual_retain`, if the argument to the closure is `Binding`, the closure will be used directly in the `retain` method, which will result in incorrect suggestion because the first argument to the `retain` closure may be of a different type. In addition, if the argument to the …
> fix: incorrect suggestions generated by `manual_retain` lint

- clippy_lints/src/returns.rs
- tests/ui/needless_return_with_question_mark.fixed
- tests/ui/needless_return_with_question_mark.rs
- tests/ui/needless_return_with_question_mark.stderr
Return with a question mark was triggered in situations where the `?` desuraging was performing error conversion via `Into`/`From`.
The desugared `?` produces a match over an expression with type `std::ops::ControlFlow<B,C>` with `B:Result<Infallible, E:Error>` and `C:Result<_, E':Error>`, and the arms perform the conversion. The patch adds another check in the lint that checks that `E == E'`. If `E == E'`, then the `?` is indeed unnecessary.
changelog: False Positive: [`needless_return_with_question_mark`] when implicit Error Conversion occurs.
fixes: #11982
> FP: `needless_return_with_question_mark` with implicit Error Conversion

- clippy_lints/src/eta_reduction.rs
- clippy_utils/src/lib.rs
- tests/ui/eta.fixed
- tests/ui/eta.rs
- tests/ui/eta.stderr
Fixes #10854.
Currently, `redundant_closure_for_method_calls` suggest incorrect paths when a method defined on a struct within inline mod is referenced (see the description in the aforementioned issue for an example; also see [this playground link](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=f7d3c5b2663c9bd3ab7abdb0bd38ee43) for the current-version output for the test cases added in this PR). It will now try to construct a relative path path to the module and suggest it instead.
changelog: [`redundant_closure_for_method_calls`] Fix incorrect path suggestions for types within local modules
> [fix] [`redundant_closure_for_method_calls`] Suggest relative paths for local modules

- .github/driver.sh
- src/driver.rs
Fixes https://github.com/rust-lang/rust-clippy/issues/12201
---
cc: @UebelAndre @illicitonion
> Makes clippy-driver check for --sysroot in arg files

- clippy_lints/src/methods/unnecessary_fold.rs
- tests/ui/unnecessary_fold.fixed
- tests/ui/unnecessary_fold.rs
- tests/ui/unnecessary_fold.stderr
Fixes #2371.
#2371 seems to already be handled correctly in the lint. This PR adds a ui regression test so we can close it.
r? @blyxyas 
changelog: Add regression ui test for #2371
> Add regression ui test for #2371

- clippy_lints/src/no_effect.rs
- tests/ui/unnecessary_operation.fixed
- tests/ui/unnecessary_operation.rs
Fix #11575.
changelog: [`unnecessary_operation`]: skip labeled blocks
> Avoid deleting labeled blocks

- CHANGELOG.md
- clippy_lints/src/doc/mod.rs
- clippy_lints/src/iter_over_hash_type.rs
- clippy_lints/src/loops/mod.rs
- clippy_lints/src/repeat_vec_with_capacity.rs
Roses are red,
So many cute cats,
How to choose?
---
The cat for the next release can be voted on: [here](https://docs.google.com/forms/d/e/1FAIpQLSfERam31AEi3_5uVsugi1-JHGF9Po1oC7OIiLs8jglprZNy_g/viewform)
The cat for the next next release can be nominated in the comments and will be voted in the next changelog PR (Submission deadline is 2024-02-06 23:59CET)
---
> Changelog for Clippy 1.76 🐈

- clippy_lints/src/redundant_locals.rs
- tests/ui/redundant_locals.rs
- tests/ui/redundant_locals.stderr
Fixes #12225
The same problem in the linked issue can happen to regular closures too, and conveniently async blocks are closures in the HIR so fixing closures will fix async blocks as well.
changelog: [`redundant_locals`]: avoid linting when redefined variable is captured by-value
> [`redundant_locals`]: take by-value closure captures into account

- CHANGELOG.md
Fixes a typo in #12224
CC: @xFrednet @Manishearth
---
> Fix release year in CHANGELOG.md

- clippy_utils/src/lib.rs
- clippy_utils/src/ty.rs
- tests/ui/ignored_unit_patterns.fixed
- tests/ui/ignored_unit_patterns.rs
- tests/ui/ignored_unit_patterns.stderr
- tests/ui/needless_borrow.fixed
- tests/ui/needless_borrow.rs
- tests/ui/needless_borrow.stderr
- tests/ui/while_let_on_iterator.fixed
- tests/ui/while_let_on_iterator.rs
- tests/ui/while_let_on_iterator.stderr
fixes #11786
supersedes #11097
The code removed in the first commit would have needed changes due to the second commit. Since it's useless it just gets removed instead.
changelog: `needless_borrow`: Fix linting in tuple and array expressions.
> Return `Some` from `walk_to_expr_usage` more

- clippy_lints/src/redundant_type_annotations.rs
- tests/ui/redundant_type_annotations.rs
- tests/ui/redundant_type_annotations.stderr
This PR changes the `redundant_type_annotations` lint to allow slice type annotations (i.e., `&[u8]`) for byte string literals. It will still consider _array_ type annotations (i.e., `&[u8; 4]`) as redundant. The reasoning behind this is that the type of byte string literals is by default a reference to an array, but, by using a type annotation, you can force it to be a slice. For example:
```rust
let a: &[u8; 4] = b"test";
let b: &[u8] = b"test";
```
Now, the type annotation for `a` will still be linted (as it is still redundant), but the type annotation for `b` will not.
Fixes #12212.
changelog: [`redundant_type_annotations`]: Fix false positive with byte string literals
> Fix false positive in `redundant_type_annotations` lint

- clippy_lints/src/unconditional_recursion.rs
- tests/ui/unconditional_recursion.rs
Fixes #12154
Fixes #12181 (this was later edited in, so the rest of the description refers to the first linked issue)
Before this change, the lint would work with `DefId`s and use those to compare types. This PR changes it to compare types directly. It fixes the linked issue, but also other false positives I found in a lintcheck run. For example, one of the issues is that some types don't have `DefId`s (primitives, references, etc., leading to possible FNs), and the helper function used to extract a `DefId` didn't handle type parameters.
Another issue was that the lint would use `.peel_refs()` in a few places where that could lead to false positives (one such FP was in the `http` crate). See the doc comment on one of the added functions and also the test case for what I mean.
The code in …
> [`unconditional_recursion`]: compare by `Ty`s instead of `DefId`s

- triagebot.toml
We are at Feb. 9, I have done practically nothing in regards to performance and bors just keeps giving me reviews, so I'm going to set myself on vacation on this repo and reroll some PRs. Sadly I cannot postpone performance for reviews.
I'll revert this commit on 12-15 days. I'd love to the discussion in this [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/review.20queue.20.26.20capacity) to make some progress so that I don't have to get into version control my busyness status.
changelog:none
r? ghost
> Temporary review vacation to focus on performance

- clippy_lints/src/methods/unnecessary_fallible_conversions.rs
- tests/ui/unnecessary_fallible_conversions.fixed
- tests/ui/unnecessary_fallible_conversions.rs
- tests/ui/unnecessary_fallible_conversions.stderr
fixes #12034
Currently, the `unnecessary_fallible_conversions` lint was capable of autofixing expressions like `0i32.try_into().unwrap()`. However, it couldn't autofix expressions in the form of `i64::try_from(0i32).unwrap()` or `<i64 as TryFrom<i32>>::try_from(0).unwrap()`.
This pull request extends the functionality to correctly autofix these latter forms as well.
changelog: [`unnecessary_fallible_conversions`]: Add autofixes for more forms
> Fix issue #12034: add autofixes for unnecessary_fallible_conversions

- clippy_lints/src/item_name_repetitions.rs
- clippy_lints/src/non_expressive_names.rs
- clippy_lints/src/operators/double_comparison.rs
- clippy_lints/src/operators/op_ref.rs
- clippy_utils/src/ast_utils.rs
- clippy_utils/src/hir_utils.rs
- clippy_utils/src/qualify_min_const_fn.rs
- tests/ui/approx_const.rs
- tests/ui/approx_const.stderr
- tests/ui/similar_names.rs
- tests/ui/similar_names.stderr
A lot of cases of the "noise" cases of `similar_names` come from two idents with a different first letter, which is easy enough to differentiate visually but causes this lint to be raised.
Do not raise the lint in these cases, as long as the first character does not have a lookalike.
Helps with https://github.com/rust-lang/rust-clippy/issues/10926 (does not fix)
This is per-commit reviewable, the first commit is just refactoring.
changelog: [`similar_names`]: don't raise if the first character is different
> [`similar_names`]: don't raise if the first character is different

- clippy_lints/src/to_string_trait_impl.rs
- tests/ui/to_string_trait_impl.rs
- tests/ui/to_string_trait_impl.stderr
Fixes #12263
Oh well... https://github.com/rust-lang/rust-clippy/pull/12122#issuecomment-1887765238 🙃 
changelog: [`to_string_trait_impl`]: avoid linting if the impl is a specialization
> [`to_string_trait_impl`]: avoid linting if the impl is a specialization

- clippy_lints/src/incompatible_msrv.rs
- tests/ui/incompatible_msrv.rs
fixes #12257
changelog: `incompatible_msrv`: Don't lint in test code
> Don't lint `incompatible_msrv` in test code

- book/src/lint_configuration.md
- clippy_config/src/conf.rs
Pretty sure it's meant to be `struct_field_names` and not `struct_variant_names`.
This change is gargantuan!!! review carefully
> Fix broken URL in `Lint Configuration`

- clippy_lints/src/blocks_in_conditions.rs
- tests/ui/auxiliary/proc_macro_attr.rs
- tests/ui/blocks_in_conditions.fixed
- tests/ui/blocks_in_conditions.rs
- tests/ui/blocks_in_conditions.stderr
should fixes: #12016 
---
changelog: [`blocks_in_conditions`] - fix FP on `match` with weird attr macro
This might not be the best solution, as the root cause (i think?) is the `span` of block was incorrectly given by the compiler?
I'm open to better solutions
> stop linting [`blocks_in_conditions`] on `match` with weird attr macro case

- clippy_lints/src/implied_bounds_in_impls.rs
Some refactors in `implied_bounds_in_impls` that I wanted to make while working on something else in that file, but I found them "large" enough that I didn't want them in the same PR and instead wanted them reviewed separately (since itd just be distracting).
This just splits up the two phases of "collect all the supertraits from each of the `impl Trait` bounds" and "find those `impl Trait` bounds that are mentioned in one of the previously-collected supertraits" into separate functions. Before, this was all in a single function.
Reviewing it commit by commit might make it easier. I can squash it down later.
> Refactor `implied_bounds_in_impls` lint

- clippy_lints/src/format_impl.rs
Move all linting logic into a single format implementations struct
This should help with the future format-args improvements.
TODO: do the same with format_args.rs, perhaps in the same PR
**NOTE TO REVIEWERS**:  use "hide whitespace" in the github diff -- most of the code has shifted, but relatively low number of lines actually modified.
> Minor refactor format-impls

- triagebot.toml
https://github.com/rust-lang/team/pull/1342
r? @ghost, when you're ready to be added to the rotation `@bors r+` this @y21
> Add y21 to the review rotation

- clippy_lints/src/booleans.rs
- tests/ui/bool_comparison.fixed
- tests/ui/bool_comparison.rs
- tests/ui/nonminimal_bool.rs
- tests/ui/nonminimal_bool.stderr
Fixes #5794.
r? @blyxyas 
changelog: Extend `NONMINIMAL_BOOL` lint
> Extend `NONMINIMAL_BOOL` lint

- clippy_lints/src/disallowed_macros.rs
- tests/ui-toml/disallowed_macros/auxiliary/proc_macros.rs
- tests/ui-toml/disallowed_macros/clippy.toml
- tests/ui-toml/disallowed_macros/disallowed_macros.rs
- tests/ui-toml/disallowed_macros/disallowed_macros.stderr
fixes #12254
The implementation is a bit of a hack, but "works". A derive expanding to another derive won't work properly, but we shouldn't be linting those anyways.
changelog: `disallowed_macros`: Don't allow derive macros to silence their own expansion
> Don't allow derive macros to silence `disallowed_macros`

- clippy_lints/src/indexing_slicing.rs
- tests/ui/crashes/ice-12253.rs
fixes #12253 
This PR fixes ICE in `indexing_slicing` as it panics when the index of the array exceeds `usize`.
> fix: ICE when array index exceeds usize

- clippy_lints/src/format_args.rs
* Move all linting logic into a single format implementations struct
This should help with the future format-args improvements.
**NOTE TO REVIEWERS**:  use "hide whitespace" in the github diff -- most of the code has shifted, but relatively low number of lines actually modified.
Followig up from #12274
r? @xFrednet 
---
> Minor refactor format-args

- clippy_lints/src/mem_replace.rs
- tests/ui/mem_replace.fixed
- tests/ui/mem_replace.rs
- tests/ui/mem_replace.stderr
- tests/ui/mem_replace_macro.rs
- tests/ui/mem_replace_macro.stderr
changelog:[`mem_replace_with_default`]: No longer triggers on unused expression
Change [`mem_replace_with_default`] to not trigger on unused expression because the lint from `#[must_use]` handle this case better.
fixes: #5586
> [`mem_replace_with_default`] No longer triggers on unused expression

- clippy_lints/src/implied_bounds_in_impls.rs
- tests/ui/implied_bounds_in_impls.fixed
- tests/ui/implied_bounds_in_impls.rs
- tests/ui/implied_bounds_in_impls.stderr
Fixes #11880
Before this change, we were simply ignoring associated types (except for suggestion purposes), because of an incorrect assumption (see the comment that I also removed).
For something like 
```rs
trait X { type T; }
trait Y: X { type T; }
// Can't constrain `X::T` through `Y`
fn f() -> impl X<T = i32> + Y<T = u32> { ... }
```
We now avoid linting if the implied bound (`X<T = i32>`) "names" associated types that also exists in the implying trait (`trait Y`). Here that would be the case.
But if we only wrote `impl X + Y<T = u32>` then that's ok because `X::T` was never constrained in the first place.
I haven't really thought about how this interacts with GATs, but I think it's fine. Fine as in, it might create false negatives, but hopefully no false positives.
(The diff is …
> [`implied_bounds_in_impls`]: avoid linting on overlapping associated tys

- clippy_lints/src/incompatible_msrv.rs
- tests/ui/incompatible_msrv.rs
- tests/ui/incompatible_msrv.stderr
Fixes #12273
changelog: [`incompatible_msrv`]: don't lint on the `IntoFuture::into_future` call desugared by `.await`
> [`incompatible_msrv`]: allow expressions that come from desugaring

- clippy_lints/src/min_ident_chars.rs
- tests/ui-toml/min_ident_chars/auxiliary/extern_types.rs
- tests/ui-toml/min_ident_chars/min_ident_chars.rs
- tests/ui-toml/min_ident_chars/min_ident_chars.stderr
Suppress the `min_ident_chars` warning for items whose name we cannot control. Do not warn for `use a::b`, but warn for `use a::b as c`, since `c` is a local identifier.
Fixes #12232 
---
changelog: [`min_ident_chars`]: Do not warn on non-local identifiers
> Ignore imported items in `min_ident_chars`

- clippy_lints/src/methods/case_sensitive_file_extension_comparisons.rs
- tests/ui/case_sensitive_file_extension_comparisons.fixed
- tests/ui/case_sensitive_file_extension_comparisons.rs
If we find a file extension check with only digits (`.123`), do not trigger `case_sensitive_file_extension_comparisons`.
Fixes #12252 
---
changelog: [`case_sensitive_file_extension_comparisons`]: Don't trigger on digits-only extensions
> [`case_sensitive_file_extension_comparisons`]: Don't trigger on digits-only extensions

- clippy_lints/src/blocks_in_conditions.rs
Updated documentation + example of `blocks_in_conditions` lint, which has been updated recently to include `match` statements as well.
> fix: documentation of `blocks_in_conditions` lint

- clippy_lints/src/new_without_default.rs
- tests/ui/new_without_default.fixed
- tests/ui/new_without_default.rs
- tests/ui/new_without_default.stderr
While `Default::default` is not const, it can still call `const new`; there's no reason this shouldn't be linted as well.
fixes #10877
changelog: [`new_without_default`]: Now emits on const fns
> [`new_without_default`]: Now emits on const fns

- clippy_lints/src/min_ident_chars.rs
- tests/ui/min_ident_chars.rs
- tests/ui/min_ident_chars.stderr
Fix #12237.
changelog: [`min_ident_chars`]: check trait items
> Check trait items in `min_ident_chars`

- clippy_lints/src/pub_underscore_fields.rs
- tests/ui-toml/pub_underscore_fields/pub_underscore_fields.rs
Closes #12286 
changelog: `#[allow(clippy::pub_underscore_fields)]` now works on linted field
> fix: make `#[allow]` work on field for `pub_underscore_fields`

- clippy_lints/src/casts/cast_possible_truncation.rs
- clippy_lints/src/matches/match_same_arms.rs
- tests/ui/match_same_arms2.rs
- tests/ui/match_same_arms2.stderr
fixes #11223
In the current `match_same_arms` implementation, if arms have guards, they are considered different. This commit adds equality checking for guards: arms are now considered equivalent only when they either both have no guards or their guards are identical.
The portion responsible for checking guard equality is refactored to reuse the existing code for checking body equality. This is abstracted into a function called `check_eq_with_pat`. To optimize performance, `check_same_guard` and `check_same_body` here use closures for lazy evaluation, ensuring that the calculation is only performed when `!(backwards_blocking_idxs...)` is true.
changelog: [`match_same_arms`]: Add check for identical guards
> Fix issue 11223: add check for identical guards in lint `match_same_arms`

- tests/compile-test.rs
https://github.com/oli-obk/ui_test/pull/175 got rid of the `bool` that controlled the default handling so we need to specify it ourselves
r? @flip1995
> Default test output conflict handling to error

- clippy_lints/src/no_effect.rs
- tests/ui/no_effect_async_fn.rs
- tests/ui/no_effect_async_fn.stderr
Fixes #12279 
changelog: Fix [`no_effect_underscore_binding`])
The warning is no longer displayed when an underscore is given in the parameter name of an asynchronous function.
> Fix: no_effect_underscore_binding fires on ignored parameters of async fns

- clippy_config/src/conf.rs
- clippy_lints/src/methods/unnecessary_to_owned.rs
- clippy_lints/src/min_ident_chars.rs
- tests/ui/unnecessary_to_owned.fixed
- tests/ui/unnecessary_to_owned.rs
- tests/ui/unnecessary_to_owned.stderr
Fixes https://github.com/rust-lang/rust-clippy/issues/8088.
Alternative to #12315.
r? @y21 
changelog: Extend `unnecessary_to_owned` to handle `Borrow` trait in map types
> Extend `unnecessary_to_owned` to handle `Borrow` trait in map types 

- clippy_lints/src/loops/infinite_loop.rs
- tests/ui/infinite_loops.rs
- tests/ui/infinite_loops.stderr
changelog: Fix #12291 #[tracing::instrument()] triggers infinite_loop
Added an in_external_macro and is_from_proc_macro check to the [infinite_loop] lint
> Add check for 'in_external_macro' and 'is_from_proc_macro' inside

- CHANGELOG.md
- clippy_lints/src/attrs.rs
- clippy_lints/src/declared_lints.rs
- tests/ui/unnecessary_clippy_cfg.rs
- tests/ui/unnecessary_clippy_cfg.stderr
Follow-up of https://github.com/rust-lang/rust-clippy/pull/12292.
r? @flip1995 
changelog: Add `unnecessary_clippy_cfg` lint
> Add `unnecessary_clippy_cfg` lint

- triagebot.toml
After this current CPP period, in which I set myself as on-vacation to focus on performance, I'm now available again. I'd love if my vacation status wasn't present in version control
changelog:none
r? ghost
> Coming back to reviewer rotation

- clippy_lints/src/attrs.rs
- tests/ui/useless_attribute.fixed
- tests/ui/useless_attribute.rs
Fixes https://github.com/rust-lang/rust-clippy/issues/12223.
Both `unused_import_braces` and `unused_imports` are valid on `use`-items, additional to the two previously allowed. 
changelog: [`useless_attribute`]: Allow `rustc_lint` `unused_import_braces` and `unused_imports` on `use`-items
> Allow unused_imports, and unused_import_braces on `use`

- clippy_lints/src/unused_unit.rs
- tests/ui/unused_unit.fixed
- tests/ui/unused_unit.rs
Fix #9949.
changelog: [`unused_unit`]: skip expressions with attributes
> Be careful with expressions with attributes

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/multiple_bound_locations.rs
- tests/ui/multiple_bound_locations.rs
- tests/ui/multiple_bound_locations.stderr
- tests/ui/trait_duplication_in_bounds_unfixable.rs
- tests/ui/trait_duplication_in_bounds_unfixable.stderr
- tests/ui/type_repetition_in_bounds.rs
- tests/ui/unnecessary_cast.fixed
- tests/ui/unnecessary_cast.rs
- tests/ui/unnecessary_cast.stderr
Fixes #7181.
r? @llogiq 
changelog: Add new `multiple_bound_locations` lint
> Add new `multiple_bound_locations` lint

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/methods/mod.rs
- clippy_lints/src/methods/unnecessary_get_then_check.rs
- lintcheck/src/main.rs
- tests/ui/iter_filter_is_some.fixed
- tests/ui/iter_filter_is_some.rs
- tests/ui/iter_filter_is_some.stderr
- tests/ui/unnecessary_get_then_check.fixed
- tests/ui/unnecessary_get_then_check.rs
- tests/ui/unnecessary_get_then_check.stderr
No issue linked to this as far as I can see. It's a lint I discovered that could be added when I worked on another lint.
r? @llogiq 
changelog: Add new `unnecessary_get_then_check` lint
> Add new `unnecessary_get_then_check` lint

- clippy_lints/src/matches/redundant_guards.rs
- tests/ui/redundant_guards.fixed
- tests/ui/redundant_guards.rs
- tests/ui/redundant_guards.stderr
Fixed #12243 
changelog: Fix[`redundant_guards`]
I have made a correction so that no warning does  appear when y.is_empty() is used within a constant function as follows.
```rust
pub const fn const_fn(x: &str) {
match x {
// Shouldn't lint.
y if y.is_empty() => {},
_ => {},
}
}
```
> FIX(12243): redundant_guards

- clippy_lints/src/box_default.rs
- clippy_lints/src/casts/unnecessary_cast.rs
- clippy_lints/src/collection_is_never_read.rs
- clippy_lints/src/dereference.rs
- clippy_lints/src/drop_forget_ref.rs
- clippy_lints/src/iter_not_returning_iterator.rs
- clippy_lints/src/matches/needless_match.rs
- clippy_lints/src/methods/clone_on_copy.rs
- clippy_lints/src/methods/needless_collect.rs
- clippy_lints/src/needless_bool.rs
- clippy_lints/src/needless_pass_by_ref_mut.rs
- clippy_lints/src/no_effect.rs
- clippy_lints/src/non_canonical_impls.rs
- clippy_lints/src/only_used_in_recursion.rs
- clippy_lints/src/question_mark.rs
- clippy_lints/src/redundant_closure_call.rs
- clippy_lints/src/strlen_on_c_strings.rs
- clippy_lints/src/undocumented_unsafe_blocks.rs
- clippy_lints/src/unit_types/let_unit_value.rs
- clippy_utils/src/lib.rs
Since it's forwarding to a single method it seems reasonable to use that one directly instead
> Remove `clippy_utils::get_parent_node`

- clippy_lints/src/lib.rs
- clippy_lints/src/single_call_fn.rs
- tests/ui/single_call_fn.rs
- tests/ui/single_call_fn.stderr
The `single_call_fn` lint worked by first collecting a list of function definitions in the lint pass, then populating the list of uses for each function in a second visitor after the crate is checked.
Doing another pass through the crate shouldn't be needed, and we should be able to do it in the same lint pass, by looking for path references to functions only and then processing them post-crate. 
Other changes:
- `FxHashMap` -> `FxIndexMap` so that we emit warnings in a consistent order, as we see them (making the diff a bit confusing to look at, because warnings were moved around)
- no longer storing a `Vec<Span>` per function: an enum representing "seen once" or "seen more than once" should be enough (only the first element is used later)
- "used here" help is now a note
I also noticed …
> Merge `single_call_fn` post-crate visitor into lint pass

- clippy_lints/src/implied_bounds_in_impls.rs
- tests/ui/implied_bounds_in_impls.fixed
- tests/ui/implied_bounds_in_impls.rs
- tests/ui/implied_bounds_in_impls.stderr
With this, we lint `impl Trait` implied bounds in more positions:
- Type alias impl trait
- Associated type position impl trait
- Argument position impl trait
- these are not opaque types, but instead are desugared to `where` clauses, so we need extra logic for finding them (`check_generics`), however the rest of the logic is the same
Before this, we'd only lint RPIT `impl Trait`s.
"Hide whitespaces" and reviewing commits individually might make this easier
changelog: [`implied_bounds_in_impls`]: start linting implied bounds in APIT, ATPIT, TAIT
> Look for `implied_bounds_in_impls` in more positions

- util/gh-pages/index.html
fixes #12349.
changelog: sync site GitHub Corner colors
> style: sync GitHub Corner colors

- book/src/configuration.md
changelog: add cargo.toml lint section way of adding lints in the book
as from [discussion on zulip](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/.E2.9C.94.20clippy.20config)
> add cargo.toml lint section way of adding lints in the book

- clippy_lints/src/box_default.rs
- tests/ui/box_default.fixed
- tests/ui/box_default.rs
- tests/ui/box_default.stderr
When encountering code such as:
```rs
Box::new(outer::Inner::default())
```
clippy would suggest replacing with `Box::<Inner>::default()`, dropping the `outer::` segment. This behavior is incorrect and that commit fixes it.
What it does is it checks the contents of the `Box::new` and, if it is of the form `A::B::default`, does a text replacement, inserting `A::B` in the `Box`'s quickfix generic list.
If the source does not match that pattern (including `Vec::from(..)` or other `T::new()` calls), we then fallback to the original code.
Fixes #11927
changelog: [`box_default`]: Preserve required path segments
> [`box_default`]: Preserve required path segments

- clippy_lints/src/vec.rs
- tests/ui/vec.fixed
- tests/ui/vec.rs
- tests/ui/vec.stderr
fixes: #12101 
---
changelog: fix suggestion error in [`useless_vec`]
r+ @matthiaskrgr since they opened the issue?
> fix suggestion error in [`useless_vec`]

- clippy_lints/src/methods/mod.rs
- clippy_lints/src/methods/read_line_without_trim.rs
- tests/ui/read_line_without_trim.fixed
- tests/ui/read_line_without_trim.rs
- tests/ui/read_line_without_trim.stderr
This lint now also realizes that a comparison like `s == "foo"` and calls such as `s.ends_with("foo")` will fail if `s` was initialized by a call to `Stdin::read_line` (because of the trailing newline).
changelog: [`read_line_without_trim`]: detect string literal comparison and `.ends_with()` calls
r? @giraffate assigning you because you reviewed #10970 that added this lint, so this is kinda a followup PR ^^
> [`read_line_without_trim`]: detect string literal comparison and `.ends_with()` calls

- clippy_lints/src/casts/cast_sign_loss.rs
- tests/ui/cast.rs
- tests/ui/cast.stderr
**Note: anyone should feel free to move this PR forward, I might not see notifications from reviewers.**
changelog: [`cast_sign_loss`]: Fix sign-handling bugs and false negatives
This PR fixes some arithmetic bugs and false negatives in PR #11883 (and maybe earlier PRs).
Cc @J-ZhengLi
I haven't updated the tests yet. I was hoping for some initial feedback before adding tests to cover the cases listed below.
Here are the issues I've attempted to fix:
Example:
```rust
i32::MIN.abs()
```
https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=022d200f9ef6ee72f629c0c9c1af11b8
Docs: https://doc.rust-lang.org/std/primitive.i32.html#method.abs
Other overflows that produce negative values could cause false negatives (and underflows could produce false positives), but they're …
> Fix sign-handling bugs and false negatives in `cast_sign_loss`

- Cargo.toml
- tests/ui/crashes/ice-6255.rs
- tests/ui/declare_interior_mutable_const/others.rs
- tests/ui/declare_interior_mutable_const/others.stderr
- tests/ui/declare_interior_mutable_const/traits.rs
- tests/ui/declare_interior_mutable_const/traits.stderr
- tests/ui/struct_fields.rs
- tests/ui/struct_fields.stderr
- tests/ui/unconditional_recursion.rs
- tests/ui/unconditional_recursion.stderr
test changes are due to https://github.com/oli-obk/ui_test/pull/201 (cc @Jarcho)
> lower `bstr` version requirement to `1.6.0`

- clippy_lints/src/casts/unnecessary_cast.rs
- tests/ui/unnecessary_cast.fixed
- tests/ui/unnecessary_cast.rs
- tests/ui/unnecessary_cast.stderr
If the whole cast expression is a unary expression (`(*x as T)`) or an  addressof expression (`(&x as T)`), then not surrounding the suggestion  into a block risks us changing the precedence of operators if the cast  expression is followed by an operation with higher precedence than the  unary operator (`(*x as T).foo()` would become `*x.foo()`, which  changes what the `*` applies on).
The same is true if the expression encompassing the cast expression is a unary expression or an addressof expression.
The lint supports the latter case, but missed the former one. This PR fixes that.
Fixes #11968
changelog: [`unnecessary_cast`]: Avoid breaking precedence with unary operators (`(*x as T).foo()` -- …
> [`unnecessary_cast`]: Avoid breaking precedence

- clippy_lints/src/entry.rs
- tests/ui/entry.fixed
- tests/ui/entry.rs
The lint makes sure that the map is not used (borrowed) before the call to `insert`. Since the lint creates a mutable borrow on the map with the `Entry`, it wouldn't be possible to replace such code with `Entry`. However, expressions up to the `insert` call are checked, but not expressions for the arguments of the `insert` call itself. This commit fixes that.
Fixes #11935
----
changelog: [`map_entry`]: Fix false positive when borrowing the map in the `insert` call
> [`map_entry`]: Check insert expression for map use

- clippy_lints/src/attrs.rs
Since https://github.com/rust-lang/rust/pull/121230 was merged, we can now rely on `Level` directly instead of keeping the list of symbols to check in clippy.
changelog: Improve `is_lint_level` code
> Improve `is_lint_level` code

- clippy_lints/src/booleans.rs
- tests/ui/nonminimal_bool.rs
Fixes #12371.
Fixes #12369.
cc @RalfJung 
The problem was an invalid condition. Shame on me...
changelog: Fix `nonminimal_bool` lint regression
> Fix `nonminimal_bool` lint regression

- clippy_lints/src/redundant_closure_call.rs
- tests/ui/redundant_closure_call_fixable.fixed
- tests/ui/redundant_closure_call_fixable.rs
The following code used to trigger the lint:
```rs
macro_rules! make_closure {
() => {
(|| {})
};
}
make_closure!()();
```
The lint would suggest to replace `make_closure!()()` with `make_closure!()`, which changes the code and removes the call to the closure from the macro. This commit fixes that.
Fixes #12358
----
changelog: [`redundant_closure_call`]: If `x!()` returns a closure, don't suggest replacing `x!()()` with `x!()`
> [`redundant_closure_call`]: Don't lint if closure origins from a macro

- CHANGELOG.md
- clippy_lints/src/attrs.rs
- clippy_lints/src/declared_lints.rs
- tests/ui/empty_docs.rs
- tests/ui/empty_docs.stderr
- tests/ui/mixed_attributes_style.rs
- tests/ui/mixed_attributes_style.stderr
Add a new lint to detect cases where both inner and outer attributes are used on a same item.
r? @llogiq 
----
changelog: Add new [`mixed_attributes_style`] lint
> Add new `mixed_attributes_style` lint

- .github/driver.sh
- .github/workflows/clippy.yml
- .github/workflows/clippy_bors.yml
I looked into the random failures we've been getting on macOS CI, not entirely sure what is going on but it seems to be an issue out of our department. A [plain driver](https://github.com/Alexendoo/rust-clippy/blob/314425001df19a82c295952b26664704d06e9348/src/driver.rs) being ran on the test files [without `ui_test` or any special flags](https://github.com/Alexendoo/rust-clippy/blob/314425001df19a82c295952b26664704d06e9348/src/driver.rs) hit the same issue
It didn't occur on `macos-13` the few times I tried it though so let's upgrade to that. [The current `macos-latest` refers to `macos-12`](https://github.com/actions/runner-images?tab=readme-ov-file#available-images), later this year it will refer to `macos-14` which runs on `aarch64` so specifying the version for our x64 macOS tests …
> Bump macOS CI version to 13

- clippy_lints/src/thread_local_initializer_can_be_made_const.rs
- tests/ui/thread_local_initializer_can_be_made_const.fixed
- tests/ui/thread_local_initializer_can_be_made_const.rs
- tests/ui/thread_local_initializer_can_be_made_const.stderr
**Issue**: The lint always triggers for some targets.   
**Why**: The lint assumes an `__init` function is not present for const initializers.   
This does not hold for all targets. Some targets always have an initializer function.  
**Fix**: If an initializer function exists, we check that it is not a `const` fn.
Lint overview before the patch:
1. Outside `threadlocal!`, then exit early.   
2. In `threadlocal!` and `__init` does not exist => is const already, exit early.     
3. In `threadlocal!` and `__init` exists and `__init` body can be `const` => we lint.
Lint overview after the patch:
1. Outside `threadlocal!`, then exit early.   
2. In `threadlocal!` and `__init` does not exist => is const already, exit early.     
3. In `threadlocal!` and `__init` exists and is `const fn` => is …
> Fix FP in `threadlocal!` when falling back to `os_local`

- clippy_lints/src/loops/manual_memcpy.rs
- tests/ui/manual_memcpy/without_loop_counters.rs
- tests/ui/manual_memcpy/without_loop_counters.stderr
fixes: #9334
This PR fixes an invalid suggestion for multi-dimensional arrays.
For example, 
```rust
let src = vec![vec![0; 5]; 5];
let mut dst = vec![0; 5];
for i in 0..5 {
dst[i] = src[i][i];
}
```
For the above code, Clippy suggests `dst.copy_from_slice(&src[i]);`, but it is not compilable because `i` is only used to loop the array.
I adjusted it so that Clippy `manual_memcpy` works properly for multi-dimensional arrays.
changelog: [`manual_memcpy`]: Fixes invalid indexing suggestions for multi-dimensional arrays
> fix: `manual_memcpy` wrong indexing for multi dimensional arrays

- src/main.rs
All built-in cargo commands have this output included when run with `cargo foo --help`. Clippy is the only exception, so I have copied the text here. As far as I can tell, the flags come from Cargo itself and not clippy, but the user almost certainly does not care about that.
```text
Manifest Options:
--manifest-path <PATH>  Path to Cargo.toml
--frozen                Require Cargo.lock and cache are up to date
--locked                Require Cargo.lock is up to date
--offline               Run without accessing the network
```
changelog: Add the standard Manifest Options section to the `--help` output
> Document manifest options

- clippy_lints/src/let_underscore.rs
- tests/ui/let_underscore_untyped.rs
changelog: [`let_underscore_untyped`]: fix false positive on async function
Fix #12395
> [`let_underscore_untyped`]: fix false positive on async function

- clippy_lints/src/std_instead_of_core.rs
- tests/ui/std_instead_of_core.fixed
- tests/ui/std_instead_of_core.rs
- tests/ui/std_instead_of_core.stderr
Relates to #12379.
Instead of checking that the paths have an identical span, it checks that the relevant `std` part of the path segment's span is identical. Added a multiline test, because my first implementation was worse and failed that, then I realized that you could grab the span off the first_segment `Ident`.  
I did find another bug that isn't addressed by this, and that exists on master as well.
The path:
```Rust
use std::{io::Write, fmt::Display};
```
Will get fixed into:
```Rust
use core::{io::Write, fmt::Display};
```
Which doesn't compile since `io::Write` isn't in `core`, if any of those paths are present in `core` it'll do the replace and cause a miscompilation. Do you think I should file a separate bug for that? Since `rustfmt` default splits those up it isn't that big of a …
> Dedup std_instead_of_core by using first segment span for uniqueness

- clippy_lints/src/transmute/mod.rs
- clippy_lints/src/transmute/transmutes_expressible_as_ptr_casts.rs
- tests/ui/transmutes_expressible_as_ptr_casts.fixed
- tests/ui/transmutes_expressible_as_ptr_casts.rs
Fix #12402
changelog: [`transmutes_expressible_as_ptr_casts`]: do not suggest invalid const casts
> Pointers cannot be converted to integers at compile time

- clippy_lints/src/derive.rs
- tests/ui/derive_partial_eq_without_eq.fixed
- tests/ui/derive_partial_eq_without_eq.rs
- tests/ui/derive_partial_eq_without_eq.stderr
fixes: #9413 #9319 
---
changelog: fix [`derive_partial_eq_without_eq`] FP on trait projection
Well, this is awkward, it works but I don't understand why, why `clippy_utils::ty::implements_trait` couldn't detects the existance of `Eq` trait, even thought it's obviously present in the derive attribute.
> fix [`derive_partial_eq_without_eq`] FP on trait projection

- clippy_lints/src/question_mark.rs
- tests/ui/manual_let_else.rs
- tests/ui/manual_let_else.stderr
- tests/ui/question_mark.fixed
- tests/ui/question_mark.rs
Fixes #12337
I split this PR up into two commits since this moves a method out of an `impl`, which makes for a pretty bad diff (the `&self` parameter is now unused, and there isn't a reason for that function to be part of the `impl` now).
The first commit is the actual relevant change and the 2nd commit just moves stuff (github's "hide whitespace" makes the diff easier to look at)
------------
Now for the actual issue:
`?` within `try {}` blocks desugars to a `break` to the block, rather than a `return`, so that changes behavior in those cases.
The lint has multiple patterns to look for and in *some* of them it already does correctly check whether we're in a try block, but this isn't done for all of its patterns.
We could add another `self.inside_try_block()` check to the function that …
> Check for try blocks in `question_mark` more consistently

- clippy_lints/src/operators/identity_op.rs
- tests/ui/identity_op.fixed
- tests/ui/identity_op.rs
- tests/ui/identity_op.stderr
In the `identity_op` lint, the following diagnostic was emitted two times
```
--> tests/ui/identity_op.rs:156:5
|
LL |     1 * 1;
|     ^^^^^ help: consider reducing it to: `1`
|
```
because both of the left operand and the right operand are the identity element of the multiplication.
This PR fixes the issue so that if a diagnostic is created for an operand, the check of the other operand will be skipped. It's fine because the result is always the same in the affected operators.
---
changelog: [`identity_op`]: Fix duplicate diagnostics
> [`identity_op`]: Fix duplicate diagnostics

- clippy_lints/src/methods/mod.rs
Noticed this while generating our lint completions failed in rust-analyzer (separate PR from https://github.com/rust-lang/rust-clippy/pull/12415 as I made these via the github interface quickly)
> Add missing header for `manual_is_variant_and`

- clippy_lints/src/doc/markdown.rs
- tests/ui/doc/doc-fixable.fixed
- tests/ui/doc/doc-fixable.rs
- tests/ui/doc/doc-fixable.stderr
Prevent `doc_markdown` from triggering on words like `OSes` and `UXes`.
changelog: handle plural acronyms in `doc_markdown`
> Handle plural acronyms in `doc_markdown`

- clippy_lints/src/doc/markdown.rs
- clippy_lints/src/doc/mod.rs
- tests/ui/doc/issue_9473.fixed
- tests/ui/doc/issue_9473.rs
- tests/ui/doc/issue_9473.stderr
Fixes #9473.
changelog: Don't emit "missing backticks" lint if the element is wrapped in `<code>` HTML tags
> Don't emit "missing backticks" lint if the element is wrapped in `<code>` HTML tags

- clippy_lints/src/operators/misrefactored_assign_op.rs
- tests/ui/assign_ops2.rs
- tests/ui/assign_ops2.stderr
Relate to #12379
The following diagnostics appear twice
```
--> tests/ui/assign_ops2.rs:26:5
|
LL |     a *= a * a;
|     ^^^^^^^^^^
|
help: did you mean `a = a * a` or `a = a * a * a`? Consider replacing it with
```
because `a` (lhs) appears in both left operand and right operand in the right hand side.
This PR fixes the issue so that if a diagnostic is created for an operand, the check of the other operand will be skipped. It's fine because the result is always the same in the affected operators.
changelog: [`misrefactored_assign_op`]: Fix duplicate diagnostics
> [`misrefactored_assign_op`]: Fix duplicate diagnostics

- CHANGELOG.md
- clippy_lints/src/assigning_clones.rs
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/lib.rs
- clippy_utils/src/sugg.rs
- tests/missing-test-files.rs
- tests/ui/assigning_clones.fixed
- tests/ui/assigning_clones.rs
- tests/ui/assigning_clones.stderr
- tests/ui/field_reassign_with_default.rs
- tests/ui/field_reassign_with_default.stderr
- tests/ui/manual_memcpy/without_loop_counters.rs
- tests/ui/manual_memcpy/without_loop_counters.stderr
- tests/ui/non_canonical_clone_impl.fixed
- tests/ui/non_canonical_clone_impl.rs
- tests/ui/non_canonical_clone_impl.stderr
This PR is a "revival" of https://github.com/rust-lang/rust-clippy/pull/10613 (with @kpreid's permission).
I tried to resolve most of the unresolved things from the mentioned PR:
1) The lint now checks properly if we indeed call the functions `std::clone::Clone::clone` or `std::borrow::ToOwned::to_owned`.
2) It now supports both method and function (UFCS) calls.
3) A heuristic has been added to decide if the lint should apply. It will only apply if the type on which the method is called has a custom implementation of `clone_from/clone_into`. Notably, it will not trigger for types that use `#[derive(Clone)]`.
4) `Deref` handling has been (hopefully) a bit improved, but I'm not sure if it's ideal yet.
I also added a bunch of additional tests.
There are a few things that could be improved, …
> Add `assigning_clones` lint

- clippy_lints/src/booleans.rs
- tests/ui/nonminimal_bool.rs
- tests/ui/nonminimal_bool.stderr
Related to #12379.
Previously the code manually checked nested binop exprs in unary exprs, but those were caught anyway by `check_expr`. Removed that code path, the path is used in the tests.
---
changelog: [`nonminimal_bool`] Remove duplicate output on nested Binops in Unary exprs.
> Remove double expr lint

- clippy_lints/src/redundant_field_names.rs
- tests/ui/redundant_field_names.fixed
- tests/ui/redundant_field_names.rs
- tests/ui/redundant_field_names.stderr
Fixes #12426
The `field.span.eq_ctxt(field.ident.span)` addition is the relevant line for the bugfix
The current implementation checks that the field's name and the path are in the same context by comparing the idents, but not that the two are in the same context as the entire field itself, so in local macros `SomeStruct { $ident: $ident }` would get linted  
> Don't lint `redundant_field_names` across macro boundaries

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/methods/is_empty.rs
- clippy_lints/src/methods/mod.rs
- clippy_utils/src/consts.rs
- tests/ui/bool_assert_comparison.fixed
- tests/ui/bool_assert_comparison.rs
- tests/ui/const_is_empty.rs
- tests/ui/const_is_empty.stderr
- tests/ui/len_zero.fixed
- tests/ui/len_zero.rs
- tests/ui/len_zero.stderr
- tests/ui/needless_bitwise_bool.fixed
- tests/ui/needless_bitwise_bool.rs
- tests/ui/needless_bitwise_bool.stderr
- tests/ui/redundant_as_str.fixed
- tests/ui/redundant_as_str.rs
- tests/ui/redundant_as_str.stderr
This lint detects calls to `.is_empty()` on an entity initialized from a string literal and flag them as suspicious. To avoid triggering on macros called from generated code, it checks that the `.is_empty()` receiver, the call itself and the initialization come from the same context.
Fixes #12307
changelog: [`const_is_empty`]: new lint
> New lint `const_is_empty`

- clippy_lints/src/methods/no_effect_replace.rs
- tests/ui/no_effect_replace.rs
- tests/ui/no_effect_replace.stderr
Fixes `no_effect_replace` duplicate diagnostics
---
changelog: [`no_effect_replace`]: Fix duplicate diagnostics
> [`no_effect_replace`]: Fix duplicate diagnostics

- clippy_lints/src/mut_mut.rs
- tests/ui/mut_mut.rs
- tests/ui/mut_mut.stderr
The `mut_mut` lint produced two diagnostics for each `mut mut` pattern in `ty` inside  `block`s because `MutVisitor::visit_ty` was called from `MutMut::check_ty` and  `MutMut::check_block` independently. This PR fixes the issue.
---
changelog: [`mut_mut`]: Fix duplicate diagnostics
> [`mut_mut`]: Fix duplicate diags

- clippy_lints/src/let_if_seq.rs
- clippy_lints/src/mut_mut.rs
- clippy_lints/src/read_zero_byte_vec.rs
- clippy_lints/src/redundant_closure_call.rs
- clippy_lints/src/returns.rs
- clippy_lints/src/unused_io_amount.rs
- clippy_lints/src/unused_peekable.rs
- tests/ui/let_if_seq.rs
- tests/ui/let_if_seq.stderr
- tests/ui/mut_mut.rs
- tests/ui/needless_return.fixed
- tests/ui/needless_return.rs
- tests/ui/read_zero_byte_vec.rs
- tests/ui/unused_io_amount.rs
- tests/ui/unused_peekable.rs
Decided to grep for `check_(fn|block)` and look where `span_lint` is used, since some lints lint will then emit a lint on a statement or expression in that function, which would use the wrong lint level attributes
The `LintContext` keeps track of the last entered HIR node that had any attributes, and uses those (and its parents) for figuring out the lint level when a lint is emitted
However, this only works when we actually emit a lint at the same node as the `check_*` function we are in.
If we're in `check_fn` and we emit a lint on a statement within that function, then there is no way to allow the lint only for that one statement (if `span_lint` is used). It would only count allow attributes on the function
changelog: [`needless_return`]: [`useless_let_if_seq`]: [`mut_mut`]: …
> use `span_lint_hir` instead of `span_lint` in more lints

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/zero_repeat_side_effects.rs
- tests/ui/zero_repeat_side_effects.fixed
- tests/ui/zero_repeat_side_effects.rs
- tests/ui/zero_repeat_side_effects.stderr
Fixes https://github.com/rust-lang/rust-clippy/issues/6439
Adds a new `suspicious` lint zero_repeat_side_effects. This lint warns the user when initializing an array or `Vec` using the `Repeat` syntax, i.e., `[x; y]`. If `x` is an `Expr::Call/MethodCall` or contains an `Expr::Call/MethodCall` and `y` is zero, then there is a chance that the internal call can produce side effects, such as printing to console, which is not very obvious.
This lint warns against this and instead suggests to separate out the function call and the array/Vec initialization.
changelog: Add new lint `zero_repeat_side_effects`
> Add new lint `zero_repeat_side_effects`

- clippy_lints/src/std_instead_of_core.rs
- tests/ui/std_instead_of_core.fixed
- tests/ui/std_instead_of_core.stderr
Fixes #12438.
Boy-scouting removed two paths that checks for duplication since I thought they were unused. However, that's just because I didn't spot it in the diff.
I installed [difftastic](https://github.com/Wilfred/difftastic) and ran it on the old one:
And the new one (fixed):
New one (stderr):
Good teachings for the future when inspecting diffs with a lot of line changes, should've thought of that before, sorry for the trouble!
changelog: [`std_instead_of_core`] Fix false positive for crates that are in `std` but not `core`
> Fix #12438 std_instead_of_core regression

- clippy.toml
- clippy_utils/src/diagnostics.rs
- tests/ui-internal/disallow_span_lint.stderr
As far as I could tell, these weren't documented anywhere, and since this is sometimes needed over `span_lint` for `#[allow]` attrs to work, I thought I would add a little bit of documentation.
When I started with clippy development, I also had no idea what these functions were for.
> add documentation to the `span_lint_hir` functions

- clippy_lints/src/matches/single_match.rs
- tests/ui/single_match.fixed
- tests/ui/single_match.rs
- tests/ui/single_match.stderr
- tests/ui/single_match_else.fixed
- tests/ui/single_match_else.rs
- tests/ui/single_match_else.stderr
edit two test file
`tests/ui/single_match_else.rs`
`tests/ui/single_match.rs`
those two test file point to the same lint
---
changelog: [`single_match`] Fix duplicate diagnostics
> [`single_match`]: Fix duplicate diagnostics

- CHANGELOG.md
- clippy_dev/src/update_lints.rs
- clippy_lints/src/attrs/duplicated_attributes.rs
- clippy_lints/src/attrs/mod.rs
- clippy_lints/src/declared_lints.rs
- tests/ui/allow_attributes_without_reason.rs
- tests/ui/allow_attributes_without_reason.stderr
- tests/ui/duplicated_attributes.rs
- tests/ui/duplicated_attributes.stderr
- tests/ui/empty_line_after_doc_comments.rs
- tests/ui/empty_line_after_outer_attribute.rs
- tests/ui/mixed_attributes_style.rs
- tests/ui/mixed_attributes_style.stderr
- tests/ui/rename.fixed
- tests/ui/rename.rs
- tests/ui/rename.stderr
It's a lint idea that @llogiq gave me while reviewing another PR.
There are some limitations, in particular for the "output". Initially I wanted to make it possible for directly lint against the whole attribute if its parts were all duplicated, but then I realized that the output would be chaotic if the duplicates were coming from different attributes, so I preferred to go to the simplest way and simply emit a warning for each entry. Not the best, but makes the implementation much easier.
Another limitation is that `cfg_attr` would be a bit more tricky to implement because we need to check if two `cfg` sets are exactly the same. I added a FIXME and will likely come back to it later.
And finally, I updated the `cargo dev update_lints` command because the generated `tests/ui/rename.rs` file …
> Add new `duplicated_attributes` lint

- clippy_lints/src/manual_retain.rs
- tests/ui/manual_retain.fixed
- tests/ui/manual_retain.rs
- tests/ui/manual_retain.stderr
Relates to: #12379
The first lint guard executed in `LateLintPass::check_expr` was testing if the parent was of type `ExprKind::Assign`.  This meant the lint emitted on both sides of the assignment operator when `check_expr` is called on either `Expr`.  The guard in the fix only lints once when the `Expr` is of kind `Assign`.
changelog:  Fix duplicate lint diagnostic emission from [`manual_retain`]
> [`manual_retain`]: Fix duplicate diagnostics

- clippy_lints/src/methods/iter_nth.rs
- clippy_lints/src/methods/mod.rs
- tests/ui/iter_nth.fixed
- tests/ui/iter_nth.stderr
There's no `O(n)` involved with `.iter().nth()` on the linted types since the iterator implementations provide `nth` and/or `advance_by` that operate in `O(1)`
For slice iterators the codegen is equivalent, `VecDeque`'s iterator seems to codegen differently but that doesn't seem significant enough to keep it as a perf lint
changelog: [`iter_nth`] Move to `style`
r? @flip1995
> Move `iter_nth` to `style`, add machine applicable suggestion

- clippy_lints/src/methods/mod.rs
- clippy_lints/src/wildcard_imports.rs
Thank you for making Clippy better!
We're collecting our changelog from pull request descriptions.
If your PR only includes internal changes, you can just write
`changelog: none`. Otherwise, please write a short comment
explaining your change.
It's also helpful for us that the lint name is put within backticks (`` ` ` ``),
and then encapsulated by square brackets (`[]`), for example:
```
changelog: [`lint_name`]: your change
```
If your PR fixes an issue, you can add `fixes #issue_number` into this
PR description. This way the issue will be automatically closed when
your PR is merged.
- \[ ] Added passing UI tests …
> chore: fix some typos

- clippy_lints/src/casts/cast_lossless.rs
- clippy_lints/src/casts/mod.rs
- tests/ui/cast_lossless_bool.fixed
- tests/ui/cast_lossless_bool.rs
- tests/ui/cast_lossless_bool.stderr
- tests/ui/cast_lossless_float.fixed
- tests/ui/cast_lossless_float.rs
- tests/ui/cast_lossless_float.stderr
- tests/ui/cast_lossless_integer.fixed
- tests/ui/cast_lossless_integer.rs
- tests/ui/cast_lossless_integer.stderr
Fixes #11285
Still an issue with the "from" side, i.e., `I8::from(1) as I64` shows as `i8 to I64`, but this should be ok. Not possible to reliably fix currently anyway.
changelog: [`cast_lossless`]: Suggest type alias instead of the aliased type
> [`cast_lossless`]: Suggest type alias instead of the aliased type

- clippy_lints/src/doc/mod.rs
- tests/ui/auxiliary/proc_macro_attr.rs
- tests/ui/empty_docs.rs
- tests/ui/empty_docs.stderr
fixes: #12377 
---
changelog: fix [`empty_docs`] trigger in proc-macros
> fix [`empty_docs`] trigger in proc-macro

- clippy_lints/src/unconditional_recursion.rs
- clippy_utils/src/lib.rs
- tests/ui/unconditional_recursion.rs
- tests/ui/unconditional_recursion.stderr
Closes #11150
```
warning: function cannot return without recursing
--> x.rs:9:9
|
9  | /         fn from(value: f32) -> Self {
10 | |             value.into()
11 | |         }
| |_________^
|
note: recursive call site
--> x.rs:10:13
|
10 |             value.into()
|             ^^^^^^^^^^^^
```
I'm also thinking that we can probably generalize this lint to #11032 at some point (instead of hardcoding a bunch of impls), like how rustc's `unconditional_recursion` works, at least up to one indirect call, but this still seems useful for now :)
I've also noticed that we use `fn_def_id` in a bunch of lints and then try to get the node args of the call in a separate step, so I made a helper function that does both in one. I intend to refactor a bunch of uses of `fn_def_id` to use this later
I …
> lint when calling the blanket `Into` impl from a `From` impl

- Cargo.toml
Clippy makes a use of `filetime::FileTime::now()`, which is new in `filetime` 0.2.9.
> filetime::FileTime::now() is new in 0.2.9

- clippy_lints/src/methods/map_clone.rs
- tests/ui/map_clone.fixed
- tests/ui/map_clone.rs
- tests/ui/map_clone.stderr
- Fixes https://github.com/rust-lang/rust-clippy/issues/12271
- (This is my first contribution to clippy and any suggestion would be appreciated)
changelog: [`map_clone`]: Handle false positive with `map_clone` lint
> Handle false positive with `map_clone` lint

- clippy_lints/src/use_self.rs
- tests/ui/use_self.fixed
- tests/ui/use_self.rs
- tests/ui/use_self.stderr
Have the lint trigger even if `Self` has generic lifetime parameters.
```rs
impl<'a> Foo<'a> {
type Item = Foo<'a>; // Can be replaced with Self
fn new() -> Self {
Foo { // No lifetime, but they are inferred to be that of Self
// Can be replaced as well
...
}
}
// Don't replace `Foo<'b>`, the lifetime is different!
fn eq<'b>(self, other: Foo<'b>) -> bool {
..
}
```
Fixes #12381
changelog: [`use_self`]: Have the lint trigger even if `Self` has generic lifetime parameters
> [`use_self`]: Make it aware of lifetimes

- clippy_lints/src/doc/markdown.rs
- clippy_lints/src/doc/mod.rs
- tests/ui/doc/issue_10262.fixed
- tests/ui/doc/issue_10262.rs
- tests/ui/doc/issue_10262.stderr
Fixes #10262.
changelog: Don't emit `doc_markdown` lint for missing backticks if it's inside a quote
> Don't emit `doc_markdown` lint for missing backticks if it's inside a quote

- clippy_lints/src/returns.rs
- tests/ui/crashes/ice-12491.fixed
- tests/ui/crashes/ice-12491.rs
- tests/ui/crashes/ice-12491.stderr
Fixes #12491
Probably fixes #12328 as well, but that one has no reproducer, so 🤷 
The bug was that the lint used `rfind()` for finding the byte index of the start of the previous non-whitespace character:
```
// abc\n     return;
^
```
... then subtracting one to get the byte index of the actual whitespace (the `\n` here).
(Subtracting instead of adding because it treats this as the length from the `return` token to the `\n`)
That's correct for ascii, like here, and will get us to the `\n`, however for non ascii, the `c` could be multiple bytes wide, which would put us in the middle of a codepoint if we simply subtract 1 and is what caused the ICE.
There's probably a lot of ways we could fix this.
This PR changes it to iterate backwards using bytes instead of characters, so that when …
> fix span calculation for non-ascii in `needless_return`

- clippy_lints/src/else_if_without_else.rs
- tests/ui/else_if_without_else.rs
- tests/ui/else_if_without_else.stderr
Relates to: #12379 
changelog:  Fix duplicate lint diagnostic emission from [`else_if_without_else`]
> [`else_if_without_else`]: Fix duplicate diagnostics

- clippy_lints/src/dbg_macro.rs
- tests/ui-toml/dbg_macro/dbg_macro.fixed
- tests/ui-toml/dbg_macro/dbg_macro.stderr
- tests/ui/dbg_macro/dbg_macro.fixed
- tests/ui/dbg_macro/dbg_macro.rs
- tests/ui/dbg_macro/dbg_macro.stderr
- tests/ui/dbg_macro/dbg_macro_unfixable.rs
- tests/ui/dbg_macro/dbg_macro_unfixable.stderr
fixes: #12131 
It appears that [`root_macro_call_first_node`] only detects `println!` in the following example: 
```rust
println!("{:?}", dbg!(s));
```
---
changelog: fix [`dbg_macro`] FN when `dbg` is inside some complex macros
(re-opening b'cuz bors doesn't like my previous one)
> fix [`dbg_macro`] FN when dbg is inside some complex macros

- clippy_lints/src/methods/mod.rs
- tests/ui/await_holding_lock.rs
- tests/ui/await_holding_lock.stderr
[There haven't been any issues](https://github.com/rust-lang/rust-clippy/issues?q=is%3Aissue+readonly_write_lock) since its creation and it's a pretty useful lint I think, so I'd say it's worth giving it a try?
Did a lintcheck run on 300 crates with no results, but I guess `RwLock` is usually not something that's used much in libraries.
changelog: move [`readonly_write_lock`] to perf (now warn-by-default)
> move `readonly_write_lock` to perf

- clippy_lints/src/types/mod.rs
- tests/ui/option_option.rs
- tests/ui/option_option.stderr
This `option_option` lint change skips checks against `ty`s inside `field_def`s defined by external macro to prevent duplicate diagnostics to the same span `ty` by multiple `Struct` definitions.
---
changelog: [`option_option`]: Fix duplicate diagnostics
> [`option_option`]: Fix duplicate diagnostics

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/integer_division_remainder_used.rs
- clippy_lints/src/lib.rs
- tests/ui/integer_division_remainder_used.rs
- tests/ui/integer_division_remainder_used.stderr
Fixes https://github.com/rust-lang/rust-clippy/issues/12391
Introduces a restriction lint which disallows the use of `/` and `%` operators on any `Int` or `Uint` types (i.e., any that use the default `Div` or `Rem` trait implementations). Custom implementations of these traits are ignored.
----
changelog: Add new restriction lint [`integer_division_remainder_used`]
> new restriction lint: `integer_division_remainder_used`

- clippy_lints/src/entry.rs
- tests/ui/entry.fixed
- tests/ui/entry.rs
- tests/ui/entry.stderr
Fixes #12489
The lint already has all the logic it needs for figuring out if it can or can't suggest a closure if it sees control flow expressions like `break` or `continue`, but it was ignoring the local's else block, which meant that it didn't see the `return None;` in a `let..else`.
changelog: [`map_entry`]: suggest `if let` instead of a closure when `return` expressions exist in the else block of a `let..else`
> [`map_entry`]: call the visitor on the local's `else` block

- clippy_lints/src/assigning_clones.rs
- tests/ui/assigning_clones.fixed
- tests/ui/assigning_clones.rs
- tests/ui/assigning_clones.stderr
Continuation of #12511
`clone_into` is the only suggestion subject to the 1.63 MSRV requirement, and the lint should still emit other suggestions regardless of the MSRV.
changelog: [assigning_clones]: only apply MSRV check to `clone_into` suggestions.
> Make `assigning_clones` MSRV check more precise

- clippy_lints/src/casts/cast_lossless.rs
- tests/ui/cast_lossless_integer.fixed
- tests/ui/cast_lossless_integer.rs
- tests/ui/cast_lossless_integer.stderr
Fixes https://github.com/rust-lang/rust-clippy/issues/12492
Disables `cast_lossless` when casting to u128 from any int or uint type. The lint states that when casting to any int type, there can potentially be lossy behaviour if the source type ever exceeds the size of the destination type in the future, which is impossible with a destination of u128.
It's possible this is a bit of a niche edge case which is better addressed by just disabling the lint in code, but I personally couldn't think of any good reason to still lint in this specific case - maybe except if the source is a bool, for readability reasons :).
changelog: FP: `cast_lossless`: disable lint when casting to u128 from any (u)int type
> Disable `cast_lossless` when casting to u128 from any (u)int type

- clippy_lints/src/methods/mod.rs
This fixes a typo in the `iter_filter_is_some` and `iter_filter_is_ok` lint documentation.
> Fix documentation typo "appects" > "affects"

- clippy_lints/src/incompatible_msrv.rs
Unsure what happened here
Probably what caused https://github.com/rust-lang/blog.rust-lang.org/issues/1277
> Correct version for incompatible_msrv

- clippy_lints/src/methods/mod.rs
The previous documentation for `flat_map_option` mentioned only readability benefits, but there is also at least one performance benefit: the `size_hint()` upper bound is preserved, whereas `flat_map().size_hint()` is always `(0, None)`.
Program demonstrating this difference:
```rust
fn main() {
let evens = |i| if i % 2 == 0 { Some(i) } else { None };
dbg!(
[1, 2, 3].iter().flat_map(evens).size_hint(),
[1, 2, 3].iter().filter_map(evens).size_hint(),
);
}
```
changelog: [`flat_map_option`]: Mention the benefit to `size_hint()`.
> Mention `size_hint()` effect in `flat_map_option` lint documentation.

- clippy_lints/src/casts/cast_sign_loss.rs
- tests/ui/cast.rs
- tests/ui/cast.stderr
Fixes #12506
The lint wants to peel method calls but didn't actually reassign the expression, leading to an infinite loop.
----
changelog: Fix infinite loop in [`cast_sign_loss`] when having two chained `.unwrap()` calls
> Fix infinite loop in `cast_sign_loss` when peeling unwrap method calls

- clippy_lints/src/methods/map_clone.rs
- tests/ui/map_clone.fixed
- tests/ui/map_clone.rs
Those constructions are idiomatic, and using `Arc::clone(x)` and `Rc::clone(x)` is often the recommended way of cloning a `Arc` or a `Rc`.
Fix #12528
changelog: [`map_clone`]: do not warn on `.map(_::clone)` for `Arc`, `Rc`, and their `Weak` variants
> Do not warn on .map(_::clone) for Arc, Rc, and their weak variants

- clippy_lints/src/manual_unwrap_or_default.rs
- tests/ui/manual_unwrap_or_default.fixed
- tests/ui/manual_unwrap_or_default.rs
- tests/ui/manual_unwrap_or_default.stderr
Fix #12531
----
changelog: [`manual_unwrap_or_default`]: add parentheses to suggestion when appropriate
> Add necessary parentheses to `manual_unwrap_or_default` lint output

- clippy_lints/src/exhaustive_items.rs
> Fix typo in exhaustive_items.rs

- clippy_lints/src/attrs/mixed_attributes_style.rs
- clippy_lints/src/attrs/mod.rs
- tests/ui/mixed_attributes_style.rs
- tests/ui/mixed_attributes_style.stderr
- tests/ui/mixed_attributes_style/auxiliary/submodule.rs
- tests/ui/mixed_attributes_style/global_allow.rs
- tests/ui/mixed_attributes_style/mod_declaration.rs
- tests/ui/mixed_attributes_style/mod_declaration.stderr
fixes: #12435 
fixes: #12436 
fixes: #12530
---
changelog: don't lint [`mixed_attributes_style`] when mixing different kind of attrs; and move it to late pass;
> don't lint [`mixed_attributes_style`] when mixing docs and other attrs

- clippy_lints/src/methods/map_clone.rs
- clippy_lints/src/methods/useless_asref.rs
- clippy_utils/src/ty.rs
- tests/ui/useless_asref.fixed
- tests/ui/useless_asref.rs
- tests/ui/useless_asref.stderr
This applies to `Arc`, `Rc`, and their weak variants. Using `.clone()` would be less idiomatic.
This follows the discussion in <https://github.com/rust-lang/rust-clippy/issues/12528#issuecomment-2014444305>.
changelog: [`useless_asref`]: do not lint `.as_ref().map(Arc::clone)` and similar
> `useless_asref`: do not lint `.as_ref().map(Arc::clone)`

- clippy_lints/src/unconditional_recursion.rs
I don't think such changes should be reflected in the changelog.
> Remove unnecessary dot in the 'unconditional recursion' lint description

- clippy_lints/src/matches/mod.rs
- clippy_lints/src/returns.rs
- clippy_utils/src/attrs.rs
- tests/ui/let_and_return.fixed
- tests/ui/let_and_return.rs
Fixes #9150
This moves `span_contains_cfg` to utils and starts using it in `let_and_return` as well.
changelog: [`let_and_return`]: avoid linting when code between the last statement and the final return expression is `#[cfg]`ed out
> [`let_and_return`]: avoid linting when code between last stmt and return expr is cfg'd out

- clippy_lints/src/manual_assert.rs
- clippy_lints/src/needless_bool.rs
- clippy_utils/src/lib.rs
- tests/ui/manual_assert.edition2018.fixed
- tests/ui/manual_assert.edition2018.stderr
- tests/ui/manual_assert.edition2021.fixed
- tests/ui/manual_assert.edition2021.stderr
- tests/ui/manual_assert.rs
Fixes #12505
changelog: [`manual_assert`]: do not add extra semicolon to suggestion
> `manual_assert`: do not add extra semicolon

- clippy_lints/src/assigning_clones.rs
Before we deal with https://github.com/rust-lang/rust-clippy/pull/12473 and the borrow checker errors, I think that it would be better to downgrade this lint, since it can break code.
changelog: Change the applicability of `assigning_clones` to `Unspecified`
r? @blyxyas
> Change applicability of `assigning_clones` to `Unspecified`

- clippy_utils/src/lib.rs
Unused_IO_amount relies on `match_trait_method` in order to match trait methods that exist in Tokio traits as the corresponding symbols don't exist.
With this commit we remove the unwrap that caused #12366.
Note: author (@m-rph) and @GuillaumeGomez couldn't replicate #12366.
changelog:none
r? @blyxyas
> Remove `unwrap` from `match_trait_method`

- book/src/SUMMARY.md
- book/src/development/the_team.md
First the big announcement:
**We want to add a new subteam for regular contributors to give them triage rights.**
---
This PR adds a new section to the book which describes the Clippy and Clippy-Contributor teams, with their duties and membership requirements. This is just an initial draft, that outlines what, I think, their responsibilities should be.
I hope everyone in the team is okay with me posting this directly to GitHub. I think a PR makes collaboration a bit easier.
[:framed_picture: Rendered :framed_picture:](https://github.com/xFrednet/rust-clippy/blob/add-team-docs/book/src/development/the_team.md)
---
Once we've decided on this document, I'll create a PR to add the new team on GitHub. As part of this, we'll also reach out to some active contributors, to ask if they would like …
> RFC: Document Clippy's teams and team duties

- clippy_lints/src/attrs/duplicated_attributes.rs
- tests/ui/duplicated_attributes.rs
- tests/ui/duplicated_attributes.stderr
Part of #12537.
changelog: Don't emit `duplicated_attribute` lint on "complex" `cfg`s
> Don't emit `duplicated_attribute` lint on "complex" `cfg`s

- clippy_lints/src/attrs/mod.rs
> It currently is in suspicious. I wouldn't say that the linted code is "most likely wrong or useless"
[...]
> :sweat_smile: I would still argue that this doesn't belong in the suspicious group, but rather in the style group. 
These are some good points made [on zulip](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/mixed_attributes_style.20on.20outlined.20modules/near/429823328).
----
changelog: Move [`mixed_attributes_style`] to the `style` category
> Move `mixed_attributes_style` to style

- clippy_lints/src/manual_unwrap_or_default.rs
- tests/ui/manual_unwrap_or_default.fixed
- tests/ui/manual_unwrap_or_default.rs
closes: #12568 
---
changelog: allow [`manual_unwrap_or_default`] in const function
This is a small fix, I was originally decided to fix it along with `#12568` but there are some problems needs to be addressed (which is why my branch is called `issue12569` 😆 ), so I decide to open a separated PR to fix them one at a time.
> allow [`manual_unwrap_or_default`] in const function

- clippy_lints/src/large_stack_frames.rs
- tests/ui-toml/large_stack_frames/large_stack_frames.rs
- tests/ui-toml/large_stack_frames/large_stack_frames.stderr
- tests/ui/large_stack_frames.rs
- tests/ui/large_stack_frames.stderr
Instead of just saying “this function's stack frame is big”, report:
* the (presumed) size of the frame
* the size and type of the largest local contributing to that size
* the configurable limit that was exceeded (once)
Known issues:
* The lint may report an over-estimate because codegen may be able to overlap some of these locals. However, that already affected whether the lint fired at all; I believe this change is still an improvement because it gives the user much more actionable information about _why_ the lint fired.
* Please tell me a better way to determine whether a local has a variable name.
changelog: [`large_stack_frames`]: print total size and largest component.
> `large_stack_frames`: print total size and largest component.

- clippy_lints/src/manual_clamp.rs
- tests/ui/manual_clamp.fixed
- tests/ui/manual_clamp.rs
- tests/ui/manual_clamp.stderr
Implements the plan that I described in https://github.com/rust-lang/rust-clippy/pull/9484#issuecomment-1374522054
This does two things primarily
1. Restrict `manual_clamp` such that it will only trigger if we are able to guarantee that `clamp` won't panic at runtime.
2. Bring `manual_clamp` out of nursery status and move it into the complexity group.
changelog: [`manual_clamp`]: Restrict this lint such that it only triggers if max and min are const, and max is greater than or equal to min. Then bring it out of the nursery group.
> restrict manual_clamp to const case, bring it out of nursery

- clippy_lints/src/manual_unwrap_or_default.rs
- tests/ui/manual_unwrap_or_default.fixed
- tests/ui/manual_unwrap_or_default.rs
fixes: #12569 
closes: #12580 
change applicability to `MaybeIncorrect` when the expression contains a comment base on suggestion in [this zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/.60manual_unwrap_or_default.60.20suggestion.20removes.20comments)
---
changelog: fix [`manual_unwrap_or_default`] suggestion ignoring side-effects, and adjust its applicability.
> fix [`manual_unwrap_or_default`] suggestion ignoring side-effects

- clippy_lints/src/question_mark.rs
- tests/ui/question_mark.fixed
- tests/ui/question_mark.rs
- tests/ui/question_mark.stderr
(indirectly) fixes: #12412 and fixes: #11983
---
changelog: make sure checked type implements `Try` trait when linting [`question_mark`]
> make sure checked type implements `Try` trait when linting [`question_mark`]

- clippy_lints/src/methods/mod.rs
- clippy_lints/src/methods/type_id_on_box.rs
- tests/ui/type_id_on_box.fixed
- tests/ui/type_id_on_box.rs
- tests/ui/type_id_on_box.stderr
- tests/ui/type_id_on_box_unfixable.rs
- tests/ui/type_id_on_box_unfixable.stderr
Closes #11349.
It now not only lints when calling `.type_id()` on the type `Box<dyn Any>`, but also on any `Box<dyn Trait>` where `Trait` is a subtrait of `Any`
changelog: FN: [`type_id_on_box`]: lint if `Any` is a sub trait
> [`type_id_on_box`]: lint on any `Box<dyn _>`

- clippy_lints/src/methods/filter_map_identity.rs
- tests/ui/filter_map_identity.fixed
- tests/ui/filter_map_identity.rs
- tests/ui/filter_map_identity.stderr
This extends the `filter_map_identity` lint to support typed closures.
For untyped closures, we know that the program compiles, and therefore we can safely suggest using flatten.
For typed closures, they may participate in type resolution. In this case we use `Applicability::MaybeIncorrect`.
Details:
https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Should.20.60filter_map_identity.60.20lint.20when.20closures.20are.20typed.3F
changelog: `filter_map_identity` will now suggest using flatten for typed closures.
r? @y21 && @Centri3
> Allow `filter_map_identity` when the closure is typed

- clippy_lints/src/box_default.rs
- tests/ui/box_default.fixed
- tests/ui/box_default.rs
- tests/ui/box_default.stderr
`Box::default()` [had its `#[rustc_box]` attribute removed](https://github.com/rust-lang/rust/pull/108476/files#r1120930164) in 1.69 so is no longer a perf related lint
The lint is moved to style but no longer produces suggestions containing turbofishes, as they're often longer/more annoying to type
changelog: [`box_default`]: Move to style
r? @llogiq
> Move `box_default` to style, do not suggest turbofishes

- clippy_lints/src/len_zero.rs
- tests/ui/len_zero.fixed
- tests/ui/len_zero.rs
- tests/ui/len_zero.stderr
fixes: #11992 
changelog: fix suggestion for [`len_zero`] with macros
> fix suggestion for [`len_zero`] with macros

- clippy_lints/src/unit_types/let_unit_value.rs
- tests/ui/let_unit.fixed
- tests/ui/let_unit.rs
- tests/ui/let_unit.stderr
Situation: `let_unit` lints when an expression binds a unit (`()`) to a variable. In some cases this binding may be passed down to another function. Currently, the lint removes the binding without considering usage.
fixes: #12594 
changelog: Suggestion Fix [`let_unit`]. Clippy will remove unit bindings and replace all their instances in the body with `()`.
> Elide unit variables linted by `let_unit` and use `()` directly instead

- triagebot.toml
Exams are coming up for me and I want to focus on that, so I'd like to pause PR assignments to me for a bit until that's over (will still continue to look at PRs that are assigned to me and might steal some PRs to review if I find the time). :)
--------------
> Pause review rotation for y21

- clippy_lints/src/assigning_clones.rs
- tests/ui/assigning_clones.fixed
- tests/ui/assigning_clones.rs
- tests/ui/assigning_clones.stderr
This PR modifies `assigning_clones` to detect situations where the `clone` call is inside a `Clone` impl, and avoids suggesting the lint in such situations.
r? @blyxyas
Fixes: https://github.com/rust-lang/rust-clippy/issues/12600
changelog: Do not invoke `assigning_clones` inside `Clone` impl
> Do not suggest `assigning_clones` in `Clone` impl

- clippy_lints/src/swap.rs
- tests/ui/manual_swap_auto_fix.fixed
- tests/ui/manual_swap_auto_fix.rs
- tests/ui/manual_swap_auto_fix.stderr
Fixed: #12334 
Initialization expressions are now generated as needed if the slice index is bound to a variable.
----
changelog: Fix [`manual_swap`]
> FIX(12334): manual_swap auto fix

- clippy_lints/src/arc_with_non_send_sync.rs
- tests/ui/arc_with_non_send_sync.rs
- tests/ui/arc_with_non_send_sync.stderr
Addresses https://github.com/rust-lang/rust-clippy/issues/12608#issuecomment-2029688054
Makes the note more concise and reframes the `Rc` suggestion around whether it crosses threads currently due to a manual `Send`/`Sync` impl or may do in the future
> Reword `arc_with_non_send_sync` note and help messages

- clippy_utils/src/ty/type_certainty/mod.rs
- tests/ui/crashes/ice-12585.rs
Fixes #12585
The root cause of the ICE in the linked issue was in the expression `one.x`, in the array literal.
The type of `one` is the `One` struct: an adt with a DefId, so its certainty is `Certain(def_id_of_one)`. However, the field access `.x` can then change the type (to `i32` here) and that should update that `DefId` accordingly. It does do that correctly when `one.x` would be another adt with a DefId:
https://github.com/rust-lang/rust-clippy/blob/97ba291d5aa026353ad93e48cf00e06f08c73830/clippy_utils/src/ty/type_certainty/mod.rs#L90-L91
but when it *isn't* an adt and there is no def id (which is the case in the linked issue: `one.x` is an i32), it keeps the `DefId` of `One`, even though that's the wrong type (which would then lead to a contradiction later when joining …
> type certainty: clear `DefId` when an expression's type changes to non-adt

- clippy_lints/src/casts/mod.rs
- tests/ui/cast.rs
- tests/ui/cast.stderr
closes: #11738
Removed the `from_expansion` guard clause for cast lints, so that these warnings can be generated for internal macros.
changelog: allow `cast` lints in macros
> Allow `cast` lints in macros

- lintcheck/src/main.rs
Fixes https://github.com/rust-lang/rust-clippy/issues/12185
This PR fixes the lack of reported ICEs within lintcheck by modifying the way in which data is collected from each crate being linted.
Instead of lintcheck only reading `stdout` for warnings, it now also reads `stderr` for any potential ICE (although admittedly, it is not the cleanest method of doing so). If it is detected, it parses the ICE into its message and backtrace separately, and then adds them to the list of outputs via clippy.
Once all outputs are collected, the formatter then proceeds to generate the file as normal.
Note that this PR also has a couple of side effects:
- When clippy fails to process a package, but said failure is not an ICE, the `stderr` will be sent to the console;
- Instead of `ClippyWarning` being …
> fix ice reporting in lintcheck

- triagebot.toml
When commenting r? clippy, rustbot takes a random member from the team. I'm setting you kings and queen to be on vacation, so that rustbot doesn't target you.
---
cc: @matthiaskrgr @giraffate and @Centri3
> Prevent PR assignments to `@matthiaskrgr`, `@giraffate`, and `@Centri3`

- clippy_lints/src/manual_unwrap_or_default.rs
- tests/ui/manual_unwrap_or_default.fixed
- tests/ui/manual_unwrap_or_default.rs
- tests/ui/manual_unwrap_or_default.stderr
Fixes #12564 
changelog: Fix [`manual_unwrap_or_default`] false positive when initial `match`/`if let` condition doesn't implement `Default` but the return type does.
> [`manual_unwrap_or_default`]: Check for Default trait implementation in initial condition when linting and use `IfLetOrMatch`

- clippy_lints/src/booleans.rs
- tests/ui/nonminimal_bool_methods.fixed
- tests/ui/nonminimal_bool_methods.rs
- tests/ui/nonminimal_bool_methods.stderr
fixes #12625
The expression  `!(a as type >= b)` got simplified to `a as type < b`, but because of rust's parsing rules that `<` is interpreted as a start of generic arguments for `type`.  This is fixed by recognizing this case and adding extra parens around the left-hand side of the comparison.
changelog: [`nonminimal_bool`]: fix incorrect suggestion for  `!(a as type >= b)`
> fix incorrect suggestion for `!(a as type >= b)`

- clippy_lints/src/dereference.rs
- tests/ui/needless_borrow.fixed
- tests/ui/needless_borrow.rs
- tests/ui/needless_borrow.stderr
This fixes #12268 
Clippy no longer adds unnecessary parentheses in suggestions when the expression is part of a tuple.
---
changelog: Fix [`needless_borrow`] unnecessary parentheses in suggestion.
> Correct parentheses for [`needless_borrow`] suggestion

- clippy_lints/src/methods/mod.rs
changelog: [`str_split_at_newline`] Fix formatting of docs
> Fix markdown syntax in str_split_at_newline docs

- book/src/README.md
The lint table and the restriction group description was improved in #10385, but only in the README. Apply the same changes to the book.
r? @xFrednet 
I noticed that I left review comments about this in #10385, but never submitted them. So to this day they are listed as "pending" in the GitHub UI.
This is just copy and paste of the current README file on `master`.
> Consistent lint group table in book and README

- clippy_lints/src/attrs/duplicated_attributes.rs
- clippy_lints/src/attrs/mod.rs
- tests/ui/auxiliary/proc_macro_attr.rs
- tests/ui/duplicated_attributes.rs
- tests/ui/duplicated_attributes.stderr
- tests/ui/unnecessary_clippy_cfg.stderr
- tests/ui/useless_attribute.fixed
- tests/ui/useless_attribute.rs
Fixes #12537.
changelog: Turn `duplicated_attributes` into a late lint
> Turn `duplicated_attributes` into a late lint

- .github/workflows/remark.yml
Pins the remark versions to the ones from before the most recent set of updates which errors on [some line lengths](https://github.com/remarkjs/remark-lint/issues/318) that aren't clear how to resolve
Currently blocking CI
changelog:  none
> Pin `remark-lint-maximum-line-length` version

- clippy_lints/src/needless_borrows_for_generic_args.rs
> Fix typo in needless_borrows_for_generic_args.rs

- clippy_lints/src/derive.rs
changelog: [`unsafe_derive_deserialize`]: Correct `Why is this bad?` explanation typo
> unsafe_derive_deserialize: `Why is this bad?` explanation typo

- CHANGELOG.md
- book/src/lint_configuration.md
- clippy_config/src/conf.rs
- clippy_lints/src/item_name_repetitions.rs
- clippy_lints/src/lib.rs
- tests/ui-toml/item_name_repetitions/allowed_prefixes/clippy.toml
- tests/ui-toml/item_name_repetitions/allowed_prefixes/item_name_repetitions.rs
- tests/ui-toml/item_name_repetitions/allowed_prefixes/item_name_repetitions.stderr
- tests/ui-toml/item_name_repetitions/allowed_prefixes_extend/clippy.toml
- tests/ui-toml/item_name_repetitions/allowed_prefixes_extend/item_name_repetitions.rs
- tests/ui-toml/item_name_repetitions/allowed_prefixes_extend/item_name_repetitions.stderr
- tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
- tests/ui/module_name_repetitions.rs
Fixes #12544 
changelog: [`module_name_repetition`]: don't report an item name if it consists only of a prefix from `allowed-prefixes` list and a module name (e.g. `AsFoo` in module `foo`). Prefixes allowed by default: [`to`, `from`, `into`, `as`, `try_into`, `try_from`]
> [`module_name_repetition`] Recognize common prepositions

- clippy_lints/src/methods/search_is_some.rs
- tests/ui/search_is_some_fixable_none.fixed
- tests/ui/search_is_some_fixable_none.rs
- tests/ui/search_is_some_fixable_none.stderr
fixes #11910 
In the current implementation of `search_is_some`, if a `.is_none` call is followed by a `.then` or `.then_some` call, the generated `!` will incorrectly negate the values returned by the `then` and `.then_some` calls. To fix this, we need to add parentheses to the generated suggestions when appropriate.
changelog: [`search_is_some`]: add parenthesis to suggestions when appropriate
> fix: incorrect suggestions when `.then` and `.then_some` is used

- rust-toolchain
r? @ghost
This should unblock CI without doing a full sync. Proper sync on Thursday.
> Bump nightly version -> 2024-04-05

- clippy_lints/src/casts/mod.rs
- tests/ui/crashes/ice-12616.stderr
- tests/ui/ptr_as_ptr.fixed
- tests/ui/ptr_as_ptr.rs
- tests/ui/ptr_as_ptr.stderr
Relates to https://github.com/rust-lang/rust-clippy/issues/12379
`ptr_as_ptr::check` is called twice in `clippy_lints/src/casts/mod.rs`
---
changelog: [`ptr_as_ptr`]: Fix duplicate diagnostics
> [`ptr_as_ptr`]: Fix duplicate diagnostics

- book/src/development/adding_lints.md
- clippy_dev/src/fmt.rs
- clippy_dev/src/lib.rs
- clippy_dev/src/main.rs
- clippy_dev/src/new_lint.rs
- clippy_dev/src/setup/mod.rs
- clippy_dev/src/setup/toolchain.rs
Adds a `cargo dev setup toolchain` subcommand that creates a rustup toolchain with symlinks to the local `cargo-clippy` and `clippy-driver`. Allows you to then do `cargo +clippy clippy` in other projects to run the locally built Clippy
Sometimes more convenient when you're testing changes on a separate project than `cd`ing back & forth to use `cargo dev lint [project]`
> Add `cargo dev setup toolchain`

- tests/ui/multiple_unsafe_ops_per_block.rs
- tests/ui/multiple_unsafe_ops_per_block.stderr
> The `multiple_unsafe_ops_per_block` test needs `asm!`

- clippy_lints/src/needless_pass_by_ref_mut.rs
- tests/ui/needless_pass_by_ref_mut.rs
- tests/ui/needless_pass_by_ref_mut.stderr
- tests/ui/needless_pass_by_ref_mut2.fixed
- tests/ui/needless_pass_by_ref_mut2.rs
- tests/ui/needless_pass_by_ref_mut2.stderr
Fixes https://github.com/rust-lang/rust-clippy/issues/12589.
Fixes https://github.com/rust-lang/rust-clippy/issues/9591.
The first commit fixes a bug I uncovered while working on this: sometimes, the mutable borrow "event" happens before the alias one, which makes some argument detected as not used mutably even if they are. The fix was simply to fill the map with the aliases afterwards.
The second commit removes the restriction to not run `self` argument for the `needless_pass_by_ref_mut` lint.
changelog: emit the `needless_pass_by_ref_mut` lint on `self` arguments as well
> Emit the `needless_pass_by_ref_mut` lint on `self` arguments as well

- clippy_lints/src/thread_local_initializer_can_be_made_const.rs
- tests/ui/thread_local_initializer_can_be_made_const.fixed
- tests/ui/thread_local_initializer_can_be_made_const.rs
This commit introduces a check to ensure that the lint won't trigger when the initializer is unreachable, such as:
```
thread_local! {
static STATE: Cell<usize> = panic!();
}
```
This is achieved by looking at the unpeeled initializer expression and ensuring that the parent macro is not `panic!()`, `todo!()`, `unreachable!()`, `unimplemented!()`.
fixes #12637
changelog: [`threadlocal_initializer_can_be_made_const`] will no longer trigger on `unreachable` macros.
> Threadlocal_initializer_can_be_made_const will not trigger for unreachable initializers

- book/src/lint_configuration.md
- clippy_config/src/conf.rs
- clippy_lints/src/copies.rs
- clippy_lints/src/mut_key.rs
- clippy_lints/src/non_copy_const.rs
- clippy_lints/src/trait_bounds.rs
- clippy_utils/src/lib.rs
- clippy_utils/src/ty.rs
- tests/ui-toml/mut_key/mut_key.rs
- tests/ui/borrow_interior_mutable_const/traits.rs
- tests/ui/borrow_interior_mutable_const/traits.stderr
- tests/ui/declare_interior_mutable_const/traits.rs
- tests/ui/declare_interior_mutable_const/traits.stderr
- tests/ui/mut_key.rs
- tests/ui/mut_key.stderr
Replaces the existing interior mutability detection, the two main changes being
- It now follows references/pointers e.g. `struct S(&Cell)`
- `mutable_key_type` ignores pointers as it did before
- The `ignore_interior_mutability` config now applies to types containing the ignored type, e.g. `http::HeaderName`
Fixes https://github.com/rust-lang/rust-clippy/issues/7752
Fixes https://github.com/rust-lang/rust-clippy/issues/9776
Fixes https://github.com/rust-lang/rust-clippy/issues/9801
changelog: [`mutable_key_type`], [`declare_interior_mutable_const`]: now considers types that have references to interior mutable types as interior mutable
> Rework interior mutability detection

- clippy_utils/src/lib.rs
- tests/ui/disallowed_names.rs
The rustdoc comment for `is_test_module_or_function` states: https://github.com/rust-lang/rust-clippy/blob/2795a6018944a5918b7d276267165484f5d62d6a/clippy_utils/src/lib.rs#L2561-L2566
Given `item`, the function calls `is_in_test_function` with `item.hir_id()`. However, `is_in_test_function` considers only `item`'s parents, not `item` itself. This PR fixes the problem.
The `test_with_disallowed_name` test fails without the fix, but passes once applied.
> Fix `is_test_module_or_function`

- clippy_lints/src/methods/mod.rs
- clippy_lints/src/methods/single_char_insert_string.rs
- clippy_lints/src/methods/single_char_pattern.rs
- clippy_lints/src/methods/single_char_push_string.rs
- clippy_lints/src/methods/utils.rs
- tests/ui/single_char_pattern.fixed
- tests/ui/single_char_pattern.rs
- tests/ui/single_char_pattern.stderr
This should mostly fix the `single_char_pattern` lint, because with a single byte, the optimizer will usually see through the char-to-string-expansion and single loop iteration. This fixes #11675 and #8111.
Update: As per the meeting on November 28th, 2023, we voted to also downgrade the lint to pedantic.
---
changelog: downgrade [`single_char_pattern`] to `pedantic`
> reduce `single_char_pattern` to only lint on ascii chars

- clippy_lints/src/operators/arithmetic_side_effects.rs
- tests/ui/arithmetic_side_effects.rs
- tests/ui/arithmetic_side_effects.stderr
Fix #12318
changelog: [arithmetic_side_effects]: Consider method calls that correspond to arithmetic symbols
> [arithmetic_side_effects] Fix #12318

- clippy_lints/src/non_canonical_impls.rs
- tests/ui/non_canonical_partial_ord_impl.fixed
- tests/ui/non_canonical_partial_ord_impl.rs
fixes #12683
---
changelog: fix [`non_canonical_partial_ord_impl`] emitting warnings which conflict with `needless_return`
> [`non_canonical_partial_ord_impl`]: Fix emitting warnings which conflict with `needless_return`

- clippy_lints/src/format_args.rs
- clippy_lints/src/large_stack_arrays.rs
- clippy_lints/src/manual_assert.rs
- clippy_lints/src/manual_is_ascii_check.rs
- clippy_lints/src/methods/filter_map.rs
- clippy_lints/src/repeat_vec_with_capacity.rs
- clippy_lints/src/slow_vector_initialization.rs
- clippy_utils/src/macros.rs
- tests/ui/auxiliary/proc_macros.rs
- tests/ui/large_stack_arrays.rs
- tests/ui/large_stack_arrays.stderr
fixes: #12586 
this PR also adds a wrapper function `matching_root_macro_call` to `clippy_utils::macros`, considering how often that same pattern appears in the codebase.
(I'm always very indecisive towards naming, so, if anyone have better idea of how that function should be named, feel free to suggest it)
---
changelog: fix [`large_stack_arrays`] linting in `vec` macro; add `matching_root_macro_call` to clippy_utils
> fix [`large_stack_arrays`] linting in `vec` macro

- clippy_lints/src/casts/cast_possible_truncation.rs
- tests/ui/cast.rs
- tests/ui/cast.stderr
Fixes [#12721](https://github.com/rust-lang/rust-clippy/issues/12721)
changelog: [`cast_possible_truncation`]:  Separated checking whether integer constant has sufficient leading zeroes to be safely casted when getting remainder from bitwise and, since the latter allows a constant on either side of the operator to increase the number of leading zeroes that can be guaranteed.
> Fix false positive in `cast_possible_truncation`

- CHANGELOG.md
- book/src/lint_configuration.md
- clippy_config/src/conf.rs
- clippy_lints/src/dbg_macro.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/vec.rs
- clippy_utils/src/lib.rs
- tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
- tests/ui-toml/useless_vec/clippy.toml
- tests/ui-toml/useless_vec/useless_vec.fixed
- tests/ui-toml/useless_vec/useless_vec.rs
- tests/ui-toml/useless_vec/useless_vec.stderr
This adds a `àllow-useless-vec-in-test` configuration which, when set to `true` will allow the `useless_vec` lint in `#[test]` functions and code within `#[cfg(test)]`. It also moves a `is_in_test` helper to `clippy_utils`.
---
changelog: configurably allow [`useless_vec`] in test code
> configurably allow `useless_vec` in tests

- clippy_lints/src/collection_is_never_read.rs
- tests/ui/collection_is_never_read.rs
fixes: #11783 
---
changelog: fix [`collection_is_never_read`] misfires when use `retain` for iteration
> check if closure as method arg has read access in [`collection_is_never_read`]

- clippy_lints/src/matches/single_match.rs
```
changelog: [`single_match`]: make the lint machine-applicable
changelog: [`single_match_else`]: make the lint machine-applicable
```
---
The lint doesn't use placeholders. I've tried it on my codebases, and all instances of it applied without problems.
> clippy::single_match(_else) may be machine applicable

- clippy_lints/src/types/mod.rs
- tests/ui/type_complexity.rs
- tests/ui/type_complexity.stderr
Relates to #12379 
Following message was duplicated:
```
LL |     fn def_method(&self, p: Vec<Vec<Box<(u32, u32, u32, u32)>>>) {}
|                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: duplicate diagnostic emitted due to `-Z deduplicate-diagnostics=no`
error: very complex type used. Consider factoring parts into `type` definitions
--> tests/ui/type_complexity.rs:55:15
```
Methods `check_trait_item` and `check_fn` were both checking method named def_method.
Now `check_trait_item` only checks methods without body.
---
changelog: [`type_complexity`]: Fix duplicate diagnostics
> [`type_complexity`]: Fix duplicate errors

- clippy_lints/src/box_default.rs
- tests/ui/box_default.fixed
- tests/ui/box_default.rs
- tests/ui/box_default.stderr
> Don't suggest `Box::default()` in functions with differing generics

- clippy_lints/src/manual_is_ascii_check.rs
- tests/ui/manual_is_ascii_check.fixed
- tests/ui/manual_is_ascii_check.rs
- tests/ui/manual_is_ascii_check.stderr
fixes: #11324 
fixes: #11776 
changelog: improve [`manual_is_ascii_check`] to suggest labeling type in closure, fix FP with type generics, and improve linting on ref expressions.
> fix suggestion error for [`manual_is_ascii_check`] with missing type

- Cargo.toml
- tests/compile-test.rs
Notable changes: more control over run/rustfix/... and other rustc-specific features. All of these can in theory now be implemented entirely out of tree
> Bump ui_test to 0.23

- clippy_lints/src/needless_for_each.rs
- tests/ui/needless_for_each_fixable.fixed
- tests/ui/needless_for_each_fixable.rs
fixes #12514
----
changelog: [`needless_for_each`]: unsafe block in for loop body suggestion
> fix `for x in y unsafe { }`

- clippy_lints/src/matches/collapsible_match.rs
- clippy_lints/src/matches/mod.rs
- clippy_lints/src/matches/redundant_guards.rs
- tests/ui/collapsible_match.rs
- tests/ui/collapsible_match.stderr
- tests/ui/redundant_guards.fixed
- tests/ui/redundant_guards.rs
- tests/ui/redundant_guards.stderr
Nested `or` patterns have been stable since 1.53, so we should be able to suggest `Some(1 | 2)` if the MSRV isn't set below that.
This change adds an msrv check and also moves it to `matches/mod.rs`, because it's also needed by `redundant_guards`.
changelog: [`collapsible_match`]: suggest collapsing nested or patterns if the MSRV allows it
> Suggest collapsing nested or patterns if the MSRV allows it

- clippy_lints/src/assigning_clones.rs
This PR adds, for consistency reasons, an empty line to the example in the doc of the `assigning_clones` lint.
> `assigning_clones`: add empty line to doc

- clippy_lints/src/explicit_write.rs
- clippy_lints/src/format.rs
- clippy_lints/src/format_args.rs
- clippy_lints/src/format_impl.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/methods/expect_fun_call.rs
- clippy_lints/src/methods/mod.rs
- clippy_lints/src/utils/format_args_collector.rs
- clippy_lints/src/write.rs
- clippy_utils/src/macros.rs
Fixes #11886
The initial way I thought of was a little gross so I never opened a PR for it, I thought of a nicer way today that no longer involves any `thread_local`s or `static`s
`rustc_data_strucutres::sync::{Lrc, OnceLock}` implement `DynSend` + `DynSync` so we can pass them to the lint passes that need the storage
r? @flip1995
> Fix `FormatArgs` storage when `-Zthreads` > 1

- clippy_lints/src/attrs/mod.rs
- clippy_lints/src/attrs/useless_attribute.rs
- tests/ui-toml/toml_disallowed_types/conf_disallowed_types.rs
- tests/ui/useless_attribute.fixed
- tests/ui/useless_attribute.rs
Fixes #12753 
Fixes #4467 
Fixes #11595 
Fixes #10878
changelog: [`useless_attribute`]: Attributes allowed on `use` items now include `ambiguous_glob_exports`, `hidden_glob_reexports`, `dead_code`, `unused_braces`, and `clippy::disallowed_types`.
> Allow more attributes in `clippy::useless_attribute`

- clippy_lints/src/methods/unnecessary_iter_cloned.rs
- tests/ui/unnecessary_iter_cloned.fixed
- tests/ui/unnecessary_iter_cloned.rs
- tests/ui/unnecessary_iter_cloned.stderr
fixes [Issue#12098](https://github.com/rust-lang/rust-clippy/issues/12098)
In issue#12098, the former code doesn't consider the caller for clone is mutable, and suggests to delete clone function.
In this change, we first get the inner caller requests for clone, 
and if it's immutable, the following code will suggest deleting clone.
If it's mutable, the loop will check whether a borrow check violation exists, 
if exists, the lint should not execute, and the function will directly return; 
otherwise, the following code will handle this.
changelog: [`clippy::unnecessary_to_owned`]: fix false positive
> fix false positive in Issue/12098 because lack of consideration of mutable caller

- clippy_lints/src/assigning_clones.rs
- tests/ui/assigning_clones.fixed
- tests/ui/assigning_clones.rs
- tests/ui/assigning_clones.stderr
The `assigning_clones` lint is producing wrong output when the assignment is a macro call.
Since Applicability level `Unspecified` will never be changed inside `hir_with_applicability`, so it is safe here to replace `hir_with_applicability` with `hir_with_context` to generate snippets of the macro call instead of the expansion.
fixes #12776
changelog: [`assigning_clones`]: use `hir_with_context` to produce correct snippets
> fix: use hir_with_context to produce correct snippets for assigning_clones

- clippy_lints/src/strings.rs
Includes the `string_to_string` and `str_to_string` lints.
changelog: [`str_to_string`]: Ignore code from expansion
changelog: [`string_to_string`]: Ignore code from expansion
> Ignore `_to_string` lints in code `from_expansion`

- CHANGELOG.md
- clippy_lints/src/casts/cast_sign_loss.rs
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/doc/lazy_continuation.rs
- clippy_lints/src/doc/mod.rs
- clippy_lints/src/manual_clamp.rs
- clippy_lints/src/methods/iter_filter.rs
- clippy_lints/src/methods/iter_kv_map.rs
- clippy_lints/src/methods/utils.rs
- clippy_lints/src/needless_continue.rs
- clippy_utils/src/lib.rs
- clippy_utils/src/source.rs
- clippy_utils/src/sugg.rs
- tests/ui/doc/doc_lazy_blockquote.fixed
- tests/ui/doc/doc_lazy_blockquote.rs
- tests/ui/doc/doc_lazy_blockquote.stderr
- tests/ui/doc/doc_lazy_list.fixed
- tests/ui/doc/doc_lazy_list.rs
- tests/ui/doc/doc_lazy_list.stderr
changelog: [`doc_lazy_continuation`]: add lint that warns on so-called "lazy paragraph continuations"
This is a follow-up for https://github.com/rust-lang/rust/pull/121659, since most cases of unintended block quotes are lazy continuations. The lint is designed to be more generally useful than that, though, because it will also catch unintended list items and unintended block quotes that didn't coincidentally hit a pulldown-cmark bug.
The second commit is the result of running `cargo dev dogfood --fix`, and manually fixing anything that seems wrong. NOTE: this lint's suggestions should never change the parser's interpretation of the markdown, but in many cases, it seems that doc comments in clippy were written without regard for this feature of Markdown (which, I suppose, is why this lint …
> Add new lint `doc_lazy_continuation`

- clippy_lints/src/attrs/duplicated_attributes.rs
- tests/ui/duplicated_attributes.rs
```rust
#[rustc_on_unimplemented(
on(
_Self = "&str",
label = "`a"
),
on(
_Self = "alloc::string::String",
label = "a"
),
)]
```
The lint treats this as a repetition because `rustc_on_unimplemented::on::label` appears twice, but that's ok.
Fixes #12619
changelog: [`duplicated_attributes`]: fix handling of `rustc_on_unimplemented`
> Handle `rustc_on_unimplemented` in duplicated_attributes

- clippy_lints/src/cargo/lint_groups_priority.rs
- tests/ui-cargo/lint_groups_priority/fail/Cargo.stderr
- tests/ui-cargo/lint_groups_priority/fail/Cargo.toml
Partially addresses #12729
This still doesn't do any workspace resolution stuff, so it will not catch any virtual workspaces or conflicts from inherited definitions. But while we're parsing the `Cargo.toml` we might as well check the workspace definitions if we find them
> Lint direct priority conflicts in `[workspace.lints]`

- clippy_lints/src/from_str_radix_10.rs
- tests/ui/from_str_radix_10.fixed
- tests/ui/from_str_radix_10.rs
- tests/ui/from_str_radix_10.stderr
fixes: #12731 
---
changelog: make [`from_str_radix_10`] skip constant context
> make [`from_str_radix_10`] skip constant context

- clippy_lints/src/matches/significant_drop_in_scrutinee.rs
- tests/ui/significant_drop_in_scrutinee.rs
- tests/ui/significant_drop_in_scrutinee.stderr
Place expressions do not really create temporaries, so they will not create significant drops. For example, the following code snippet is quite good (#8963):
```rust
fn main() {
let x = std::sync::Mutex::new(vec![1, 2, 3]);
let x_guard = x.lock().unwrap();
match x_guard[0] {
1 => println!("1!"),
x => println!("{x}"),
}
drop(x_guard); // Some "usage"
}
```
Also, the previous logic thinks that references like `&MutexGuard<_>`/`Ref<'_, MutexGuard<'_, _>>` have significant drops, which is simply not true, so it is fixed together in this PR.
Fixes https://github.com/rust-lang/rust-clippy/issues/8963
Fixes https://github.com/rust-lang/rust-clippy/issues/9072
changelog: [`significant_drop_in_scrutinee`]: Fix false positives due to false drops of place expressions.
r? @blyxyas
> `significant_drop_in_scrutinee`: Fix false positives due to false drops of place expressions

- clippy_lints/src/no_effect.rs
- tests/ui/no_effect.rs
- tests/ui/no_effect.stderr
The rustc lint `path_statements` covers this case
Fixes #11547
> Don't lint path statements in no_effect

- clippy_lints/src/assigning_clones.rs
In a nutshell, the `assigning_clones` lint suggests to make your code less readable for a small performance gain. See #12778 for more motivation.
fixes #12778 
changelog: [`assigning_clones`]: move to the `pedantic` group
> `assigning_clones`: move to `pedantic` so it is allow by default

- clippy_lints/src/doc/missing_headers.rs
- clippy_lints/src/doc/mod.rs
- tests/ui/missing_panics_doc.rs
Fix #12760
```
changelog: [missing_panics_doc]: Ignore panics in compile time
```
> Fix #12760

- clippy_lints/src/needless_borrows_for_generic_args.rs
- tests/ui/needless_borrows_for_generic_args.fixed
- tests/ui/needless_borrows_for_generic_args.rs
- tests/ui/needless_borrows_for_generic_args.stderr
Current implementation looks for significant drops, that can change the behavior, but that's not enough - value might not have a `Drop` itself but one of its children might have it.
A good example is passing a reference to `PathBuf` to `std::fs::File::open`. There's no benefits to pass `PathBuf` by value, but since `clippy` can't see `Drop` on `Vec` several layers down it complains forcing pass by value and making it impossible to use the same name later.
New implementation only looks at copy values or values created in place     so existing variable will never be moved but things that take a string reference created and value is created inplace `&"".to_owned()` will make it to suggest to use `"".to_owned()` still.
Fixes https://github.com/rust-lang/rust-clippy/issues/12454
changelog: …
> less aggressive needless_borrows_for_generic_args

- .github/driver.sh
- .github/workflows/clippy.yml
- .github/workflows/clippy_bors.yml
Fixes https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Windows.20CI.20failing
Rustup 1.27.1 no longer adds `[SYSROOT]/bin` to `PATH` by default - https://github.com/rust-lang/rustup/issues/3825. This is fine for the packaged binaries since windows loads `dll`s from the folder the executable is in, but our built one is in a different folder
There's an environment variable to get the old behaviour back, but as it's deprecated and not much code I think returning to setting it manually is fine
> Manually set library paths in .github/driver.sh

- CHANGELOG.md
- book/src/lint_configuration.md
- clippy_config/src/conf.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/panic_unimplemented.rs
- tests/ui-toml/panic/clippy.toml
- tests/ui-toml/panic/panic.rs
- tests/ui-toml/panic/panic.stderr
- tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
```
changelog: [`panic`]: Now can be disabled in tests with the `allow-panic-in-tests` option
```
I often find myself using `panic!(…)` in tests a lot, where I often do something like:
```rust
match enam {
Enam::A => …,
Enam::B => …,
_ => panic!("This should not happen at all."),
}
```
I think this patch should go nicely with already existing `allow-unwrap-in-tests` and `allow-expect-in-tests`.
> Add configuration option for ignoring `panic!()` in tests

- clippy_lints/src/doc/mod.rs
- tests/ui/doc/doc_lazy_list.fixed
- tests/ui/doc/doc_lazy_list.rs
- tests/ui/doc/doc_lazy_list.stderr
```
```
This avoids event spans that would otherwise cause crashes, since an
End's span covers the range of the tag (which will be earlier than the
line break within the tag).
> doc_lazy_continuation: do not warn on End events

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/loops/mod.rs
- clippy_lints/src/loops/while_float.rs
- tests/ui/while_float.rs
- tests/ui/while_float.stderr
This PR adds a nursery lint that checks for while loops comparing floating point values.
changelog:
```
changelog: [`while_float`]: Checks for while loops comparing floating point values.
```
Fixes #758
> Add new lint `while_float`

- clippy_lints/src/derive.rs
- tests/ui/unsafe_derive_deserialize.rs
- tests/ui/unsafe_derive_deserialize.stderr
The utility function `clippy_utils::fulfill_or_allowed` is not used because using it would require to move the check for allowed after the check iterating over all inherent impls of the type, doing possibly unnecessary work.
Instead, `is_lint_allowed` is called as before, but additionally, once certain that the lint should be emitted, `span_lint_hir_and_then` is called instead of `span_lint_and_help` to also fulfill expectations.
Note: as this is my first contribution, please feel free to nitpick or request changes. I am happy to adjust the implementation.
fixes: #12802
changelog: fulfill expectations in [`unsafe_derive_deserialize`]
> fulfill expectations in `check_unsafe_derive_deserialize`

- clippy_lints/src/init_numbered_fields.rs
- tests/ui/numbered_fields.fixed
- tests/ui/numbered_fields.rs
- tests/ui/numbered_fields.stderr
fixes #12367
changelog: [`numbered_fields`]: fix macro expand message error.
> bug fix: lint numbered_fields message error

- clippy_lints/src/empty_enum.rs
* Remove incorrect claim that “wrappers around it are the conventional way to define an uninhabited type”.
* Discuss why one would use `!`, a newtype struct, or keep the enum.
* Add links to relevant documentation.
Before writing this change, I asked the community via [IRLO](https://internals.rust-lang.org/t/idiomatic-definition-of-uninhabited-never-newtypes/20877) and [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/Never.20type.20wrappers.20.2F.20defining.20uninhabited.20newtypes) for feedback. The broad consensus seemed to me to be that in a world where both `never_type` and `min_exhaustive_patterns` are stable and therefore available for general use, we _might_ want to `!` or newtypes of it — but it's certainly not “conventional” _yet._ Therefore, I've …
> Rephrase and expand `empty_enum` documentation.

- clippy_lints/src/derive.rs
- tests/ui/derive_partial_eq_without_eq.fixed
- tests/ui/derive_partial_eq_without_eq.rs
- tests/ui/derive_partial_eq_without_eq.stderr
This is a followup to #12804, fixing a similar issue for `derive_partial_eq_without_eq` by using `span_lint_hir_and_then` instead of `span_lint_and_sugg`.
Additionally tests for both `#[allow(clippy::derive_partial_eq_without_eq)]` and `#[expect(clippy::derive_partial_eq_without_eq)]` are added.
changelog:[`derive_partial_eq_without_eq`]: fulfill expectations
> fulfill expectations in `check_partial_eq_without_eq`

- clippy_lints/src/doc/markdown.rs
- tests/ui/doc/doc-fixable.fixed
- tests/ui/doc/doc-fixable.rs
- tests/ui/doc/doc-fixable.stderr
closes #12835.
changelog: [`clippy::doc_markdown`]: `Quick Fix` for `bare URLs`
> feat: `Quick Fix` for `bare URLs`

- clippy_lints/src/doc/markdown.rs
- tests/ui/doc/issue_12795.fixed
- tests/ui/doc/issue_12795.rs
- tests/ui/doc/issue_12795.stderr
Fixes #12795.
changelog: Correctly handle closing parens in `doc_markdown` lint
> Correctly handle closing parens in `missing_backticks` doc lint

- clippy_lints/src/matches/significant_drop_in_scrutinee.rs
- tests/ui/significant_drop_in_scrutinee.rs
- tests/ui/significant_drop_in_scrutinee.stderr
I want to argue that the following code snippet should not trigger `significant_drop_in_scrutinee` (https://github.com/rust-lang/rust-clippy/issues/8987). The iterator holds a reference to the locked data, so it is expected that the mutex guard must be alive until the entire loop is finished.
```rust
use std::sync::Mutex;
fn main() {
let mutex_vec = Mutex::new(vec![1, 2, 3]);
for number in mutex_vec.lock().unwrap().iter() {
dbg!(number);
}
}
```
However, the lint should be triggered when we clone the vector. In this case, the iterator does not hold any reference to the locked data.
```diff
-     for number in mutex_vec.lock().unwrap().iter() {
+     for number in mutex_vec.lock().unwrap().clone().iter() {
```
Unfortunately, it seems that regions on the types of local variables are mostly …
> `significant_drop_in_scrutinee`: Trigger lint only if lifetime allows early significant drop

- clippy_lints/src/dereference.rs
- clippy_lints/src/needless_bool.rs
- clippy_lints/src/returns.rs
- clippy_utils/src/lib.rs
- tests/ui/let_and_return.fixed
- tests/ui/let_and_return.rs
- tests/ui/let_and_return.stderr
- tests/ui/needless_return.fixed
- tests/ui/needless_return.rs
- tests/ui/needless_return.stderr
closes: #12801 
---
changelog: suggest adding parentheses when linting [`let_and_return`] and [`needless_return`]
> add parentheses to [`let_and_return`]'s suggestion

- book/src/configuration.md
Fix example code of the "Disabling evaluation of certain code" section in the configuration chapter.
> book: Fix example code

- clippy_lints/src/methods/unnecessary_iter_cloned.rs
- clippy_lints/src/methods/utils.rs
- tests/ui/unnecessary_iter_cloned.fixed
- tests/ui/unnecessary_iter_cloned.rs
- tests/ui/unnecessary_iter_cloned.stderr
- tests/ui/unnecessary_to_owned.stderr
fixes #12821 
In the case of an unnecessary `.iter().cloned()`, the lint `unnecessary_to_owned` might suggest to remove the `&` from references without checking if such references are inside a macro expansion. This can lead to unexpected behavior or even broken code if the lint suggestion is applied blindly. See issue #12821 for an example.
This PR checks if such references are inside macro expansions and skips this part of the lint suggestion in these cases.
changelog: [`unnecessary_to_owned`]: Don't suggest to remove `&` inside macro expansion
> Fix `unnecessary_to_owned` interaction with macro expansion

- clippy_lints/src/methods/iter_on_single_or_empty_collections.rs
- tests/ui/iter_on_empty_collections.fixed
- tests/ui/iter_on_empty_collections.rs
- tests/ui/iter_on_empty_collections.stderr
> Suppress `iter_on_empty_collections` if the iterator's concrete type is relied upon

- clippy_lints/src/reference.rs
- tests/ui/deref_addrof.fixed
- tests/ui/deref_addrof.rs
- tests/ui/deref_addrof.stderr
Split from https://github.com/rust-lang/rust-clippy/pull/12854
changelog: ignore array from `deref_addrof` lint
r? y21
> ignore array from `deref_addrof` lint

- clippy_lints/src/non_canonical_impls.rs
- tests/ui/auxiliary/proc_macro_derive.rs
- tests/ui/non_canonical_clone_impl.fixed
- tests/ui/non_canonical_clone_impl.rs
- tests/ui/non_canonical_clone_impl.stderr
Fixed #12788
Although the issue only mentions `NON_CANONICAL_CLONE_IMPL`, this fix will also affect `NON_CANONICAL_PARTIAL_ORD_IMPL` because I saw
> Because of these unforeseeable or unstable behaviors, macro expansion should often not be regarded as a part of the stable API.
on Clippy Documentation and these two lints are similar, so I think it might be good, not sure if it's right or not.
--- 
changelog: `NON_CANONICAL_CLONE_IMPL`, `NON_CANONICAL_PARTIAL_ORD_IMPL` will skip proc marco now
> fix: let non_canonical_impls skip proc marco

- clippy_lints/src/eta_reduction.rs
- tests/ui/eta.fixed
- tests/ui/eta.rs
- tests/ui/eta.stderr
fixes: #12853 
---
changelog: fix [`redundant_closure`] suggesting incorrect code with `F: Fn()`
> fix [`redundant_closure`] suggesting incorrect code with `F: Fn()`

- clippy_lints/src/indexing_slicing.rs
- clippy_lints/src/iter_without_into_iter.rs
- clippy_utils/src/ty.rs
- tests/ui/indexing_slicing_slice.rs
- tests/ui/indexing_slicing_slice.stderr
Fixes https://github.com/rust-lang/rust-clippy/issues/11525
Disables `indexing_slicing` for custom Index impls, specifically any implementations that also do not have a `get` method anywhere along the deref chain (so, for example, it still lints on Vec, which has its `get` method as part of the deref chain).
Thanks @y21 for pointing me in the right direction with a couple of handy util functions for deref chain and inherent methods, saved a headache there!
changelog: FP: Disable `indexing_slicing` for custom Index impls
> Disable `indexing_slicing` for custom Index impls

- clippy_lints/src/strings.rs
- tests/ui/str_to_string.fixed
- tests/ui/str_to_string.stderr
Fixes https://github.com/rust-lang/rust-clippy/issues/12768
I'm not sure if there is any potential for edge cases with this - since it only ever acts on `&str` types I can't think of any, and especially since the methods do the same thing anyway.
changelog: allow `str_to_string` lint to be automatically applied
> Modify str_to_string to be machine-applicable

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/methods/mod.rs
- clippy_lints/src/methods/needless_character_iteration.rs
- clippy_lints/src/methods/unnecessary_result_map_or_else.rs
- clippy_lints/src/methods/utils.rs
- tests/ui/needless_character_iteration.fixed
- tests/ui/needless_character_iteration.rs
- tests/ui/needless_character_iteration.stderr
Fixes #4817.
r? @xFrednet 
changelog: Add `needless_character_iteration` lint
> Add `needless_character_iteration` lint

- README.md
- book/src/configuration.md
- book/src/development/basics.md
- book/src/development/defining_lints.md
- book/src/development/proposals/syntax-tree-patterns.md
- clippy_dummy/PUBLISH.md
- clippy_dummy/crates-readme.md
- lintcheck/README.md
I was reading some documentation (specially the book) and I notice some few usages of the word `clippy` when refering to the Project/Tool. As we already have in the majority of the documentation, in those cases, Clippy is a proper noun, and because of that should be used capitalized. 
This is, for sure, not an exhaustive change: quite the opposite, it was just some cases that I could verify with not so much effort.
changelog: Docs: capitalizing the `clippy` word in some usages.
> Using Clippy as a proper noun when refering to the unique entity Clippy

- clippy_lints/src/floating_point_arithmetic.rs
- clippy_utils/src/lib.rs
- tests/ui/floating_point_log.fixed
- tests/ui/floating_point_log.rs
Fixes #12881
`suboptimal_flops` was making the wrong assumption that a `.log()` method call on a float literal must choose the inherent log method that will always have an argument present (in which case `args[0]` indexing would be fine), but that wasn't the case in the linked issue because at the point of the method call, the exact float type hadn't been inferred yet (and method selection can't select inherent methods when the exact float type has not yet been inferred, in which case it falls back to looking for trait impls and chooses the one that didn't have any parameters).
This fixes it by actually making sure it's a call to an inherent method (could also fix the linked ICE by simply using fallibly indexing via `.get()`, but this felt like it'd fix the root cause: even if there were …
> Only run `suboptimal_flops` on inherent method calls

- clippy_lints/src/methods/mod.rs
- clippy_lints/src/methods/needless_character_iteration.rs
- tests/ui/needless_character_iteration.fixed
- tests/ui/needless_character_iteration.rs
- tests/ui/needless_character_iteration.stderr
Fixes #12879.
changelog: Fix false positive for `needless_character_iteration` lint
> Fix false positive for `needless_character_iteration` lint

- clippy_lints/src/booleans.rs
- tests/ui/overly_complex_bool_expr.fixed
- tests/ui/overly_complex_bool_expr.rs
fixes #12689 
---
changelog: fix [`overly_complex_bool_expr`] triggers wrongly on never type
> [`overly_complex_bool_expr`]: Fix trigger wrongly on never type

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/needless_maybe_sized.rs
- tests/ui-toml/type_repetition_in_bounds/main.rs
- tests/ui-toml/type_repetition_in_bounds/main.stderr
- tests/ui/auxiliary/proc_macros.rs
- tests/ui/needless_maybe_sized.fixed
- tests/ui/needless_maybe_sized.rs
- tests/ui/needless_maybe_sized.stderr
- tests/ui/type_repetition_in_bounds.rs
- tests/ui/type_repetition_in_bounds.stderr
changelog: new lint: [`needless_maybe_sized`]
Closes #10600
> Add `needless_maybe_sized` lint

- clippy_lints/src/cargo/lint_groups_priority.rs
- tests/ui-cargo/lint_groups_priority/fail/Cargo.stderr
- tests/ui-cargo/lint_groups_priority/fail/Cargo.toml
- tests/ui-cargo/lint_groups_priority/pass/Cargo.toml
> `lint_groups_priority`: ignore lints & groups at the same level

- clippy_lints/src/manual_unwrap_or_default.rs
- tests/ui/manual_unwrap_or_default.fixed
- tests/ui/manual_unwrap_or_default.rs
- tests/ui/manual_unwrap_or_default.stderr
- tests/ui/useless_conversion_try.rs
- tests/ui/useless_conversion_try.stderr
This PR is modifying the  `manual_unwrap_or_default` to be applied/linted for `Result`s as well. It is part of the fixes desired by https://github.com/rust-lang/rust-clippy/issues/12618
changelog:[`manual_unwrap_or_default`]: Lint for Result types.
> Lint `manual_unwrap_or_default` for Result as well

- clippy_utils/src/ty/type_certainty/mod.rs
- tests/ui/or_fun_call.fixed
- tests/ui/or_fun_call.rs
This fixes a (debug) ICE in `type_certainty` that happened in the [k256 crate]. (I'm sure you can also specifically construct an edge test case that will run into type_certainty false positives visible outside of debug builds from this bug)
<details>
<summary>Minimal ICE repro</summary>
```rs
use std::ops::Add;
Add::add(1_i32, 1).add(i32::MIN);
```
</details>
The subtraction here overflowed:
https://github.com/rust-lang/rust-clippy/blob/436675b4772049a0ff535bd46d944689c90ed750/clippy_utils/src/ty/type_certainty/mod.rs#L209
... when we have something like `Add::add` where `add` fn has 0 generic params but the `host_effect_index` is `Some(2)` (inherited from the parent generics, the const trait `Add`), and we end up executing `0 - 1`.
(Even if the own generics weren't empty and we didn't …
> Handle const effects inherited from parent correctly in `type_certainty`

- clippy_lints/src/format_args.rs
- tests/ui/format_args.fixed
- tests/ui/format_args.rs
- tests/ui/format_args.stderr
> Fix `to_string_in_format_args` with macro call receiver

- CHANGELOG.md
- clippy_lints/src/attrs/mod.rs
- clippy_lints/src/integer_division_remainder_used.rs
- clippy_lints/src/legacy_numeric_constants.rs
- clippy_lints/src/manual_unwrap_or_default.rs
- clippy_lints/src/methods/mod.rs
- clippy_lints/src/transmute/mod.rs
- clippy_lints/src/zero_repeat_side_effects.rs
Two cat ears from waffle,
A tail and a dress,
That's our Jyn,
The magnificent cat
~ =^.^=
---
---
> Changelog for Clippy 1.79 🎓

- tests/ui/match_same_arms2.fixed
- tests/ui/match_same_arms2.rs
- tests/ui/match_same_arms2.stderr
> [`match_same_arms`]: add a test case with lifetimes

- clippy_lints/src/methods/search_is_some.rs
- clippy_lints/src/needless_bool.rs
- clippy_utils/src/lib.rs
- tests/ui/needless_bool/fixable.fixed
- tests/ui/needless_bool/fixable.rs
- tests/ui/needless_bool/fixable.stderr
Fix #12846
changelog: [`needless_bool`]: Add missing parentheses around method receiver
> Add required parentheses around method receiver

- util/gh-pages/script.js
Cosmetic fix
Don't see the reason that now filter on gh-pages is starting work after 3 symbols typing so remove this condition
Before:
https://github.com/rust-lang/rust-clippy/assets/5480441/fa3b780e-30dc-4fdb-bf2d-5a99337eca4e
After:
https://github.com/rust-lang/rust-clippy/assets/5480441/977e15af-8be5-462c-a703-f10c05e6109c
changelog: gh-pages
> Filter from first typed symbol on gh-pages

- clippy_lints/src/methods/single_char_insert_string.rs
- clippy_lints/src/methods/single_char_push_string.rs
- tests/ui/single_char_add_str.fixed
- tests/ui/single_char_add_str.rs
- tests/ui/single_char_add_str.stderr
Add support for single chars / literals with `to_string()` call for `push_str()` and `insert_str()`. 
changelog: [`single_char_add_str`]: handle single chars with `to_string()` call
Closes #12775
> Handle single chars with `to_string()` for `single_char_add_str`

- clippy_lints/src/indexing_slicing.rs
- tests/ui/indexing_slicing_index.rs
- tests/ui/indexing_slicing_index.stderr
- tests/ui/indexing_slicing_slice.rs
- tests/ui/indexing_slicing_slice.stderr
This pr fixes https://github.com/rust-lang/rust-clippy/issues/12824
Even though the issue mentions the indexing case only, it was easy to apply the fix to the slicing case as well.
changelog: [`out_of_bounds_indexing`, `indexing_slicing`]: Don't lint on procedural macros.
> Don't lint indexing_slicing lints on proc macros

- clippy_lints/src/missing_const_for_fn.rs
- clippy_utils/src/qualify_min_const_fn.rs
- tests/ui/missing_const_for_fn/could_be_const.rs
- tests/ui/missing_const_for_fn/could_be_const.stderr
Fixes #12677
The `method_accepts_droppable` check that was there seemed overly conservative.
> Returns true if any of the method parameters is a type that implements `Drop`.
> The method can't be made const then, because `drop` can't be const-evaluated.
Accepting parameters that implement `Drop` should still be fine as long as the parameter isn't actually dropped, as is the case in the linked issue where the droppable is moved into the return place. This more accurate analysis ("is there a `drop` terminator") is already done by `qualify_min_const_fn` [here](https://github.com/rust-lang/rust-clippy/blob/f5e250180c342bb52808c9a934c962a8fe40afc7/clippy_utils/src/qualify_min_const_fn.rs#L298), so I don't think this additional check is really necessary?
Fixing the other, second case in the …
> Let `qualify_min_const_fn` deal with drop terminators

- clippy_lints/src/utils/author.rs
- tests/ui/author.stdout
- tests/ui/author/blocks.stdout
- tests/ui/author/call.stdout
- tests/ui/author/if.stdout
- tests/ui/author/issue_3849.stdout
- tests/ui/author/loop.stdout
- tests/ui/author/macro_in_closure.stdout
- tests/ui/author/matches.stdout
> Fix typos of author lint

- clippy_lints/src/allow_attributes.rs
- clippy_lints/src/arc_with_non_send_sync.rs
- clippy_lints/src/attrs/mod.rs
- clippy_lints/src/loops/mod.rs
- clippy_lints/src/needless_for_each.rs
Clippy is wonderful, and reading its lints is a great way to learn about Rust. While doing this, I noticed a few little copyedits, such as adding trailing periods to sentences, or tweaking wording very slightly to improve its readability. I hope you will accept these suggestions as an act of love for the project, with my thanks for all the maintainers' hard work.
changelog: Docs [ mut_range_bound ]: fix doc nits
changelog: Docs [ needless_for_each ]: fix doc nits
changelog: Docs [ arc_with_non_send_sync ]: fix doc nits
changelog: Docs [ allow_attributes ]: fix doc nits
changelog: Docs [ allow_attributes_without_reason ]: fix doc nits
> Fix doc nits

- clippy_lints/src/assigning_clones.rs
- clippy_utils/src/mir/possible_borrower.rs
- tests/ui/assigning_clones.fixed
- tests/ui/assigning_clones.rs
Fixes #12444 
Fixes #12460
Fixes #12749
Fixes #12757
Fixes #12929
I think the documentation for the function should describe what- and how this is fixing the issues well.
It avoids emitting a warning when the data being cloned borrows from the place to clone into, which is information that we can get from `PossibleBorrowerMap`. Unfortunately, it is a tiny bit tedious to match on the MIR like that and I'm not sure if this is possibly relying a bit too much on the exact MIR lowering for assignments.
Things left to do:
changelog: [`assigning_clones`]: avoid warning when the suggestion would lead to a borrow-check error
> Avoid emitting `assigning_clones` when cloned data borrows from the place to clone into

- .github/workflows/lintcheck.yml
- lintcheck/Cargo.toml
- lintcheck/src/config.rs
- lintcheck/src/json.rs
- lintcheck/src/main.rs
This is an MVP of sorts, it consists of #9764 + a GitHub action that feeds the output to the [job summary](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary). It doesn't yet do anything fancy like `--recursive` or adding comments to the PR, so you'd have to click through to the action to see the results
Example output of a change (https://github.com/Alexendoo/rust-clippy/commit/0be1ab82f8d1d37c164bd964689770af948840d4): https://github.com/Alexendoo/rust-clippy/actions/runs/4264858870#summary-11583333018
r? @flip1995
> Run a diff of lintcheck against the merge base for pull requests

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/field_scoped_visibility_modifiers.rs
- clippy_lints/src/lib.rs
- tests/ui/field_scoped_visibility_modifiers.rs
- tests/ui/field_scoped_visibility_modifiers.stderr
changelog: [`field_scoped_visibility_modifiers`]: Add a lint which checks for struct fields using Restricted (not inherited, not public) visibility modifiers.
> Add field_scoped_visibility_modifiers lint

- CHANGELOG.md
- clippy_config/src/msrvs.rs
- clippy_lints/src/casts/ref_as_ptr.rs
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/dereference.rs
- clippy_lints/src/methods/manual_inspect.rs
- clippy_lints/src/methods/mod.rs
- clippy_lints/src/needless_borrows_for_generic_args.rs
- clippy_utils/src/lib.rs
- clippy_utils/src/source.rs
- clippy_utils/src/ty.rs
- tests/ui/copy_iterator.rs
- tests/ui/copy_iterator.stderr
- tests/ui/manual_inspect.fixed
- tests/ui/manual_inspect.rs
- tests/ui/manual_inspect.stderr
fixes #12250 
A great example of a lint that sounds super simple, but has a pile of edge cases.
----
changelog: Add lint `manual_inspect`
> Add lint `manual_inspect`

- clippy_utils/src/higher.rs
> Use symbols when raising range expressions.

- triagebot.toml
I'm only removing myself from the assignment roulette as I want to allow `r? xFrednet` for `gh-pages` and other updates. So feel free to still `r?` me.
r? @ghost
> Pause assignments to @xFrednet for summer break :beach_umbrella:

- clippy_lints/src/upper_case_acronyms.rs
- tests/ui/crashes/ice-12284.rs
fixes #12284
The logic has been rewritten to avoid allocations. The old version allocated multiple vecs and strings for each identifier. The new logic allocates a single string only when the lint triggers.
This also no longer lints on strings which don't start with an uppercase letter (e.g. `something_FOO`).
> Fix ICE in `upper_case_acronyms`

- clippy_lints/src/octal_escapes.rs
- tests/ui/octal_escapes.rs
- tests/ui/octal_escapes.stderr
Main changes are not doing UTF-8 decoding, noting each occurrence as an individual lint emission, and narrowing the span to point to the escape itself.
> Rework `octal_escapes`

- clippy_lints/src/matches/manual_unwrap_or.rs
- clippy_lints/src/matches/mod.rs
- tests/ui/manual_unwrap_or.fixed
- tests/ui/manual_unwrap_or.rs
- tests/ui/manual_unwrap_or.stderr
- tests/ui/manual_unwrap_or_default.fixed
- tests/ui/manual_unwrap_or_default.rs
- tests/ui/match_result_ok.fixed
- tests/ui/match_result_ok.rs
- tests/ui/match_result_ok.stderr
- tests/ui/option_if_let_else.fixed
- tests/ui/option_if_let_else.rs
- tests/ui/option_if_let_else.stderr
This PR modifies `manual_unwrap_or` to lint for `if let` cases as well. This effort is part of the fixes desired by https://github.com/rust-lang/rust-clippy/issues/12618
changelog:[`manual_unwrap_or`]: Lint for `if let` cases.
> Lint `manual_unwrap_or` for it let cases

- util/gh-pages/index.html
- util/gh-pages/script.js
changelog: Add applicability filter to lint list website.
Fixes #7958
Desktop view:
Mobile view:
> Add applicability filter to lint list page

- clippy_lints/src/allow_attributes.rs
- clippy_lints/src/attrs/allow_attributes_without_reason.rs
- clippy_utils/src/check_proc_macro.rs
I've been running through going through all the lint implementations to clean them up. I'll be separating out the changes into small PRs to make reviewing easier.
> Add more types to `is_from_proc_macro`

- clippy_lints/src/implicit_return.rs
- tests/ui/implicit_return.fixed
- tests/ui/implicit_return.rs
- tests/ui/implicit_return.stderr
This pr fixes https://github.com/rust-lang/rust-clippy/issues/12872
changelog: [`implicit_return`]: Don't lint on procedural macros.
> Don't lint `implicit_return` on proc macros

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/methods/mod.rs
- clippy_lints/src/methods/unnecessary_min_or_max.rs
- clippy_utils/src/consts.rs
- tests/ui/auxiliary/external_consts.rs
- tests/ui/cast.rs
- tests/ui/cast.stderr
- tests/ui/unnecessary_min_or_max.fixed
- tests/ui/unnecessary_min_or_max.rs
- tests/ui/unnecessary_min_or_max.stderr
Continuation of https://github.com/rust-lang/rust-clippy/pull/12061
Fix https://github.com/rust-lang/rust-clippy/issues/11901 and https://github.com/rust-lang/rust-clippy/issues/11924
This implementation only deal with literal int, like `i32::MAX`, `-6_i32`, `0`
changelog: added lint [`unnecessary_min_max`]
> Unnecessary call to min/max method

- clippy_lints/src/cognitive_complexity.rs
- clippy_lints/src/copies.rs
- clippy_lints/src/implicit_hasher.rs
- clippy_lints/src/matches/single_match.rs
- clippy_lints/src/methods/manual_inspect.rs
- clippy_lints/src/missing_doc.rs
- clippy_lints/src/multiple_bound_locations.rs
- clippy_lints/src/needless_else.rs
- clippy_lints/src/needless_if.rs
- clippy_lints/src/non_octal_unix_permissions.rs
- clippy_lints/src/octal_escapes.rs
- clippy_lints/src/ranges.rs
- clippy_utils/src/consts.rs
- clippy_utils/src/hir_utils.rs
- clippy_utils/src/source.rs
The none-generic versions of the functions exist to help with both compile times and codegen.
> Add new span related utils

- clippy_lints/src/manual_unwrap_or_default.rs
- tests/ui/manual_unwrap_or_default.fixed
- tests/ui/manual_unwrap_or_default.rs
Fixes #12928.
If this not a "simple" pattern, better not emit the lint.
changelog: Fix incorrect suggestion for `manual_unwrap_or_default`
> Fix incorrect suggestion for `manual_unwrap_or_default`

- tests/integration.rs
While checking #12983, bors came upon a cargo change that put "E0463" into the standard error (as part of a test case code snippet), which the integration test picked up to fail the build. Talk about unforeseen consequences.
So this PR just changes the integration test to use short message format in order to not include the code snippets in the output. Hopefully that will fix the problem.
r? @Alexendoo 
---
> use short message format in integration test

- clippy_lints/src/missing_const_for_fn.rs
- tests/ui/missing_const_for_fn/could_be_const.fixed
- tests/ui/missing_const_for_fn/could_be_const.stderr
Add a machine-applicable suggestion to the `missing_const_for_fn` lint.
changelog: [`missing_const_for_fn`]: add machine-applicable suggestion
> [`missing_const_for_fn`]: add machine-applicable suggestion

- .github/workflows/lintcheck.yml
- lintcheck/src/main.rs
Always trims ~40s off the `diff` job as it no longer needs to install the rust toolchain or compile lintcheck. Saves a further ~20s for the `base`/`head` jobs when the cache is warm
It now uses artifacts for restoring the JSON between jobs as per https://github.com/rust-lang/rust-clippy/pull/10398#discussion_r1642364392, cc @flip1995
The lintcheck changes are to make `./target/debug/lintcheck` work, running `cargo-clippy`/`clippy-driver` directly doesn't work without `LD_LIBRARY_PATH`/etc being set which is currently being done by `cargo run`. By merging the `--recursive` and normal cases to both go via regular `cargo check` we can have Cargo set up the environment for us
r? @xFrednet 
> Cache lintcheck binary in ci

- book/src/lint_configuration.md
- clippy_config/src/conf.rs
This fixes an issue where the word "DevOps" ends up as a false positive for the `doc_markdown` lint.
In a doc comment like this
```rust
/// Call the Azure DevOps REST API.
pub fn example() {}
```
the word "DevOps" is highlighted as something which should be in backticks.
```
warning: item in documentation is missing backticks
--> src/lib.rs:1:20
|
1 | /// Call the Azure DevOps REST API.
|                    ^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#doc_markdown
= note: requested on the command line with `-W clippy::doc-markdown`
help: try
|
1 | /// Call the Azure `DevOps` REST API.
|                    ~~~~~~~~
warning: `example` (lib) generated 1 warning (run `cargo clippy --fix --lib -p example` to apply 1 suggestion) …
```
> Fix doc_markdown DevOps false positive

- lintcheck/Cargo.toml
- lintcheck/src/main.rs
This bumps `strip-ansi-escapes` to remove arrayvec from it's deps (https://github.com/luser/strip-ansi-escapes/pull/8)
Should Cargo.lock be commited too to track it's working state?
> bump strip-ansi-escapes

- clippy_lints/src/doc/lazy_continuation.rs
- clippy_lints/src/doc/mod.rs
- tests/ui/doc/doc_lazy_blank_line.fixed
- tests/ui/doc/doc_lazy_blank_line.rs
- tests/ui/doc/doc_lazy_blank_line.stderr
- tests/ui/doc/doc_lazy_blockquote.fixed
- tests/ui/doc/doc_lazy_blockquote.rs
- tests/ui/doc/doc_lazy_blockquote.stderr
- tests/ui/doc/doc_lazy_list.fixed
- tests/ui/doc/doc_lazy_list.rs
- tests/ui/doc/doc_lazy_list.stderr
This change addresses cases where doc comments are separated by blank lines, comments, or non-doc-comment attributes, like this:
```rust
/// - first line
// not part of doc comment
/// second line
```
Before this commit, Clippy gave a pedantically-correct warning about how you needed to indent the second line. This is unlikely to be what the user intends, and has been described as a "false positive." Since Clippy is warning you about a highly unintuitive behavior [that Rustdoc actually has](https://notriddle.com/rustdoc-html-demo-11/lazy-continuation-bad/test_dingus_2024/constant.D.html), we definitely want it to output *something*, but the suggestion to indent was poor.
Fixes #12917 
```
changelog: [`doc_lazy_continuation`]: suggest blank line for likely-unintended lazy continuations
```
> doc_lazy_continuation: blank comment line for gap

- clippy_lints/src/methods/manual_inspect.rs
- tests/ui/manual_inspect.stderr
> Add error message to manual_inspect lint

- clippy_dev/src/new_lint.rs
> fix wrong msrv import in `new_lint` template

- clippy_lints/src/methods/mod.rs
Although `manual_inspect`'s PR started some months ago, the lint is only available in the current nightly (1.81.0), rather than 1.78.0.
```
changelog: [`manual_inspect`]: fix `clippy::version` from 1.78.0 to 1.81.0
```
> `manual_inspect`: fix `clippy::version` from 1.78.0 to 1.81.0

- book/src/lint_configuration.md
- clippy_config/src/conf.rs
False positives for idents in markdown
changelog: Add "WebP", "OpenExr", "YcbCr", "sRGB" to `doc-valid-idents` default.
> Image-related valid idents

- clippy_lints/src/assertions_on_constants.rs
- clippy_lints/src/default_numeric_fallback.rs
- clippy_lints/src/no_effect.rs
- clippy_utils/src/lib.rs
- tests/ui/assertions_on_constants.rs
- tests/ui/assertions_on_constants.stderr
- tests/ui/unnecessary_operation.fixed
- tests/ui/unnecessary_operation.rs
- tests/ui/unnecessary_operation.stderr
close #12816
close #12847
cc #12817
----
changelog: Fix false positives in consts for `assertions_on_constants` and `unnecessary_operation`.
> Don't lint `assertions_on_constants` on any const assertions

- rust-toolchain
> build: Skip installing rust-docs with minimal rustup profile

- clippy_utils/src/ty.rs
- tests/ui/into_iter_without_iter.rs
changelog: FP: `into_iter_without_iter`: No longer lints when the `iter` or `iter_mut` implementation is not within the first `impl` block
fixes #12964
---
I'm pretty new to this open-source thing, so hopefully I did everything right. Got a little annoyed this false positive was happening in my code and the issue was inactive for two weeks so I thought I'd fix it myself.
As an aside, maybe `iter.map(...).next()` could be linted against? I don't see that ever being preferred over `iter.next().map(...)`, and it could've prevented the bug here.
> Fix #12964 - false positive with `into_iter_without_iter`

- clippy_lints/src/doc/mod.rs
- tests/ui/doc/unbalanced_ticks.rs
- tests/ui/doc/unbalanced_ticks.stderr
```
changelog: [`doc_markdown`]: correctly detect backslash-escaped `` ` ``
```
> doc_markdown: detect escaped `` ` `` when checking unmatched

- clippy_lints/src/dereference.rs
- clippy_utils/src/lib.rs
- tests/ui/explicit_auto_deref.fixed
- tests/ui/explicit_auto_deref.rs
- tests/ui/explicit_auto_deref.stderr
changelog: [`explicit_auto_deref`] Fix some false-positive cases
Fix part of #9841
Fix  #12969
r? xFrednet
> Fix some false-positive cases of `explicit_auto_deref`

- clippy_lints/src/returns.rs
- tests/ui/needless_return.fixed
- tests/ui/needless_return.rs
- tests/ui/needless_return.stderr
A fix for https://github.com/rust-lang/rust-clippy/issues/9361 suppresses `clippy::needless_return` if there are any attributes on the `return` statement. This leads to some unexpected behavior, as described in https://github.com/rust-lang/rust-clippy/issues/12998, where adding `#[expect(clippy::needless_return)]` suppresses the lint, but doesn't fulfill the expectation.
I now decided to manually fulfill any expectations, if they are before the attribute check.
---
Closes: https://github.com/rust-lang/rust-clippy/issues/12998
> `needless_return`: Support `#[expect]` on the return statement

- CHANGELOG.md
- clippy_lints/src/byte_char_slices.rs
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/lib.rs
- tests/ui/byte_char_slices.fixed
- tests/ui/byte_char_slices.rs
- tests/ui/byte_char_slices.stderr
This patch adds a new lint that checks for potentially harder to read byte char slices: `&[b'a', b'b']` and suggests to replace them with the easier to read `b"ab"` form.
Fixes #10147 
---
changelog: new lint: [`byte_char_slices`]
[#10155](https://github.com/rust-lang/rust-clippy/pull/10155)
> Add new lint for byte char slices

- clippy_lints/src/methods/unnecessary_to_owned.rs
- clippy_utils/src/paths.rs
- tests/ui/unnecessary_to_owned.fixed
- tests/ui/unnecessary_to_owned.rs
- tests/ui/unnecessary_to_owned.stderr
Closes #11648
Detects the pattern `&String::from_utf8(bytes.to_vec()).unwrap()` and suggests `core::str::from_utf8(bytes).unwrap()`, which avoids the unnecessary intermediate allocation.
I decided to put this in the existing `unnecessary_to_owned` lint (rather than creating a new lint) for a few reasons:
- we get to use some of its logic (for example, recognizing any of the functions in the `to_owned` family, e.g. `to_vec`)
- the actual inefficient operation that can be avoided here is the call to `.to_vec()`, so this is in a way similar to the other cases caught by `unnecessary_to_owned`, just through a bunch of type conversions
- we can make this more "generic" later and catch other cases, so imo it's best not to tie this lint specifically to the `String` type
changelog: …
> [`unnecessary_to_owned`]: catch `to_owned` on byte slice to create temporary `&str`

- clippy_lints/src/disallowed_script_idents.rs
Minor change to use `find_map` instead of a loop. Not important, but it's easier to read.
> Refactor `disallowed_script_idents`

- clippy_lints/src/disallowed_names.rs
- clippy_lints/src/functions/impl_trait_in_params.rs
- clippy_lints/src/incompatible_msrv.rs
- clippy_lints/src/methods/unwrap_expect_used.rs
- clippy_lints/src/missing_assert_message.rs
- clippy_lints/src/wildcard_imports.rs
- clippy_lints/src/write.rs
- clippy_utils/src/lib.rs
- tests/ui/disallowed_names.rs
- tests/ui/wildcard_imports.fixed
- tests/ui/wildcard_imports.rs
- tests/ui/wildcard_imports.stderr
- tests/ui/wildcard_imports_2021.edition2018.fixed
- tests/ui/wildcard_imports_2021.edition2018.stderr
- tests/ui/wildcard_imports_2021.edition2021.fixed
- tests/ui/wildcard_imports_2021.edition2021.stderr
- tests/ui/wildcard_imports_2021.rs
Uses are replaced with `is_in_test` for consistency with other lints and to simplify the implementation of the lints. This means the module name is no longer checked, but that was a horrible hack from a time when late passes couldn't see `#[cfg(..)]` attributes.
> Remove `is_in_test_module_or_function`

- CHANGELOG.md
- clippy_lints/src/cfg_not_test.rs
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/lib.rs
- tests/ui/cfg_not_test.rs
- tests/ui/cfg_not_test.stderr
Fixes #11234 
changelog: new lint: [`cfg_not_test`]
I don't know whether to lint only the `attr` or also the item associated to it. I guess this would mean putting the check in another place than `check_attribute` but I can't find a way to get the associated item to the attribute.
Also, I'm not sure how to document this lint, I feel like my explications are bad.
> feat: add cfg_not_test lint

- clippy_lints/src/default.rs
- clippy_lints/src/misc.rs
- clippy_lints/src/no_effect.rs
- clippy_utils/src/lib.rs
This brings us in line with how rustc checks for the attribute. Also note that `unused_attributes` will trigger if it's placed anywhere else.
See:
https://github.com/rust-lang/rust/blob/9a21ac8e7efe9ea26a8065d0959a976ca32039bb/compiler/rustc_passes/src/dead.rs#L400-L403
https://github.com/rust-lang/rust/blob/9a21ac8e7efe9ea26a8065d0959a976ca32039bb/compiler/rustc_passes/src/liveness.rs#L143-L148
> Only check for `automatically_derived` on impl blocks

- clippy_lints/src/operators/mod.rs
changelog: [`modulo_one`]: (docs) Clarify that it only applies to integers
This might be nitpicky, but it's more technically correct.
It also helps if a user skims through the docs, because they may believe it also applies to `{float}`s. This doc edit minimizes that possibility
> Clarify that `modulo_one` only applies to ints

- clippy_lints/src/disallowed_methods.rs
- tests/ui-internal/disallow_span_lint.stderr
- tests/ui-toml/toml_disallowed_methods/conf_disallowed_methods.stderr
Using the span of the call site just produces noisy diagnostics for long calls. Especially multi-line calls.
> Refactor `disallowed_methods` and narrow span

- .github/workflows/lintcheck.yml
- lintcheck/README.md
- lintcheck/src/config.rs
- lintcheck/src/main.rs
This PR adds a new `--warn-all` flag to lintcheck. This is intended for our CI, as it currently doesn't detect changes of `nursery` and `restriction` lints.
I only made it the default for the CI, as `restriction` lints tend to generate A LOT of lint triggers. Looking at you [`clippy::implicit_return`](https://rust-lang.github.io/rust-clippy/master/index.html#/clippy::implicit_return)
That's it. Should hopefully be easy to review.
Also, a bit thanks again to @Alexendoo for adding this to our CI :heart: 
---
r? @Alexendoo 
> Lintcheck: Add `--warn-all` and make it the CI default

- clippy_lints/src/init_numbered_fields.rs
- clippy_lints/src/lib.rs
- tests/ui/init_numbered_fields.fixed
- tests/ui/init_numbered_fields.rs
- tests/ui/init_numbered_fields.stderr
Two behaviour changes:
* Not linting in macros
* Not linting when side effects might be reordered
changelog: `init_numbered_fields`: Don't suggest reordering side effects.
> Rework `init_numbered_fields`

- clippy_lints/src/missing_const_for_fn.rs
- tests/ui/missing_const_for_fn/cant_be_const.rs
- tests/ui/missing_const_for_fn/could_be_const.fixed
- tests/ui/missing_const_for_fn/could_be_const.rs
- tests/ui/missing_const_for_fn/could_be_const.stderr
closes: #13009 
---
changelog: [`missing_const_for_fn`]: fix FP when arg ty is impl trait alias ty
> [`missing_const_for_fn`]: fix FP when arg ty is impl trait alias ty

- lintcheck/Cargo.toml
- lintcheck/src/driver.rs
- lintcheck/src/json.rs
- lintcheck/src/main.rs
- lintcheck/src/recursive.rs
Saves about 80% of the size by picking out what we need rather than serialising the whole diagnostic
r? @xFrednet
> Reduce the size of lintcheck JSON output

- clippy_lints/src/matches/mod.rs
- clippy_lints/src/matches/significant_drop_in_scrutinee.rs
- tests/ui/significant_drop_in_scrutinee.rs
- tests/ui/significant_drop_in_scrutinee.stderr
This lint should also work for `if let` and `while let`, so this PR makes it actually work.
For `while let`, I can't think of any reason why this lint shouldn't be enabled. The only problem is that the lint suggests moving the significant drop above the `while let`, which is clearly invalid in the case of `while let`. I don't know if this is fixable, but this PR simply disables the wrong suggestions.
For `if let`, it seems that another lint called `if_let_mutex` has some overlapping functionality. But `significant_drop_in_scrutinee` is a bit stricter, as it will trigger even if the `else` branch does not try to lock the same mutex.
changelog: [`significant_drop_in_scrutinee`]: Trigger lint also for scrutinees in `while let` and `if let`.
r? @blyxyas (the third PR as promised in …
> `significant_drop_in_scrutinee`: Trigger lint also for scrutinees in `while let` and `if let`

- clippy_lints/src/assigning_clones.rs
Short list of changes:
* Inline and simplify `extract_call`
* Inline `is_ok_to_suggest`
* Inline `skip_drop_block`
* Check the HIR tree before the macro check
* Don't call `outer_expn_data`
* Use `find` instead of a loop in `clone_source_borrows_from_dest` 
> Refactor `assigning_clones`

- clippy_lints/src/bool_to_int_with_if.rs
Rearranges things to check the HIR tree first and simplifies how the literals are read.
> Refactor `bool_to_int_with_if`

- clippy_lints/src/len_zero.rs
- clippy_lints/src/let_if_seq.rs
- clippy_lints/src/let_underscore.rs
- clippy_lints/src/let_with_type_underscore.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/literal_representation.rs
- clippy_lints/src/manual_bits.rs
- clippy_lints/src/manual_float_methods.rs
- clippy_lints/src/manual_let_else.rs
- clippy_lints/src/manual_main_separator_str.rs
- clippy_lints/src/manual_non_exhaustive.rs
- clippy_lints/src/manual_range_patterns.rs
- clippy_lints/src/manual_rem_euclid.rs
- clippy_lints/src/manual_retain.rs
- clippy_lints/src/manual_slice_size_calculation.rs
- clippy_lints/src/manual_strip.rs
- clippy_lints/src/manual_unwrap_or_default.rs
- clippy_lints/src/map_unit_fn.rs
- clippy_lints/src/minmax.rs
And even more rearrangements to check the HIR tree before other checks.
> Misc refactorings part 4

- lintcheck/lintcheck_crates.toml
- lintcheck/src/input.rs
- lintcheck/src/main.rs
- lintcheck/src/output.rs
- lintcheck/src/popular_crates.rs
- lintcheck/src/recursive.rs
For some time now I had the feeling that lintcheck's main file has been too large. This PR simply moves some structs into new submodules.
I've also changed the `.toml` structure slightly to only accept one version per crate. AFAIK, we haven't use multiple versions before. If we want to test different versions, we can simply just add a second entry. That's what lintcheck does internally anyways.
I wanted to have these changes in separate commits, but then accidentally squashed them... So sorry :sweat_smile: 
---
r? @Alexendoo If you think this is not really worth a proper review, since it's mostly a move refactoring in an internal tool, you can also `r=xFrednet` on this PR.
> Lintcheck: Refactor structs and only take one version per crate

- clippy_lints/src/operators/float_cmp.rs
- clippy_lints/src/operators/mod.rs
- tests/ui/float_cmp.rs
- tests/ui/float_cmp.stderr
- tests/ui/float_cmp_const.rs
- tests/ui/float_cmp_const.stderr
Using `f32::EPSILON` or `f64::EPSILON` as the floating-point equality comparison error margin is incorrect, yet `float_cmp` has until now recommended this be done. This change fixes the given guidance (both in docs and compiler hints) to not reference these unsuitable constants.
Instead, the guidance now clarifies that the scenarios in which an absolute error margin is usable, provides a sample implementation for using a user-defined absolute error margin (as an absolute error margin can only be used-defined and may be different for different comparisons) and references the floating point guide for a reference implementation of relative error based equality comparison for cases where absolute error margins cannot be identified.
changelog: [`float_cmp`] Fix guidance to not incorrectly …
> Fix guidance of [`float_cmp`] and [`float_cmp_const`] to not incorrectly recommend `f__::EPSILON` as the error margin.

- tests/ui/iter_next_loop.rs
- tests/ui/iter_next_loop.stderr
I'm uncovering bugs while working on https://github.com/rust-lang/rust-clippy/pull/11421. ^^'
> Fix `iter_next_loop.rs` ui test

- util/gh-pages/index.html
- util/gh-pages/script.js
changelog: Add 'Expand All' and 'Collapse All' buttons to the website.
Fixes #12542
Desktop view:
Mobile view:
I did have some slight performance issues with lots of tabs being open. In the future it may be worth it to consider virtual scrolling. I'm not sure if this would allow ctrl+f finding on all the lints since the DOM won't contain the text of all the lints, just those that need to be immediately shown.
> Add 'Expand All' & 'Collapse All' to the website

- clippy_lints/src/casts/mod.rs
Fix two small syntax errors to make the examples compile.
> Fix syntax errors in example code (clippy::cast_nan_to_int)

- clippy_lints/src/methods/or_fun_call.rs
- tests/ui/or_fun_call.fixed
- tests/ui/or_fun_call.rs
fixes: #10228 
---
changelog: [`unwrap_or_default`]: skip warning when calling inside of suggested method's implementation
> [`unwrap_or_default`]: skip warning when calling inside of suggested method's implementation

- clippy_lints/src/matches/manual_unwrap_or.rs
- tests/ui/manual_unwrap_or.fixed
- tests/ui/manual_unwrap_or.rs
- tests/ui/manual_unwrap_or.stderr
changelog: [`manual_unwrap_or`]: fix false positive of `if let Option<T>`
Closes #13018
> Fix `manual_unwrap_or` false positive

- clippy_lints/src/checked_conversions.rs
Removes redundant checks across functions and check the HIR tree before anything else.
> Refactor `checked_conversions`

- clippy_utils/src/lib.rs
- tests/ui/needless_option_as_deref.fixed
- tests/ui/needless_option_as_deref.rs
- tests/ui/needless_option_as_deref.stderr
changelog: [`needless_option_as_deref`] Fix false-positive on struct literals.
Fixes #13077 .
r?  Alexendoo
> Fix `needless_option_as_deref` false-positive on struct literals

- clippy_utils/src/numeric_literal.rs
- tests/ui/excessive_precision.fixed
- tests/ui/excessive_precision.rs
- tests/ui/excessive_precision.stderr
fixes #12954
changelog: fix [`excessive_precision`] suggestions on float literal written in scientific notation
> fix [`excessive_precision`] suggestions on floats written in scientific notation

- .cargo/config.toml
- Cargo.toml
- tests/dogfood.rs
Outputs the regular cargo progress in colour when running the dogfood test, helpful to see because it can take a long time to run
> Show progress while running dogfood test

- clippy_lints/src/zero_repeat_side_effects.rs
- tests/ui/zero_repeat_side_effects.fixed
- tests/ui/zero_repeat_side_effects.rs
- tests/ui/zero_repeat_side_effects.stderr
changelog: [`zero_repeat_side_effects` ] Lint only if array length is a literal zero
Fixes #13110 .
r? y21
> Lint `zero_repeat_side_effects`  only if array length is a literal zero

- clippy_lints/src/loops/single_element_loop.rs
- tests/ui/single_element_loop.fixed
- tests/ui/single_element_loop.rs
- tests/ui/single_element_loop.stderr
Fixes https://github.com/rust-lang/rust-clippy/issues/12782.
changelog: Fix missing parens in `single_element_loop` suggestion
> Fix wrong suggestion for `single_element_loop` where parens were missing

- lintcheck/lintcheck_crates.toml
- lintcheck/src/driver.rs
- lintcheck/src/input.rs
- lintcheck/src/json.rs
- lintcheck/src/main.rs
- lintcheck/src/output.rs
- lintcheck/src/recursive.rs
This PR adds links to the emission code in our lintcheck CI. When reviewing changes, I would like to be able to see the bigger context, which isn't always included in the lint message. This PR adds a nice link to the lintcheck diff that allows for simple investigation of the code in question.
At first, I wanted to simply use the doc.rs links and call it a day, but then I figured out that some crates might have their source files remapped. Cargo was the crate that made me notice this. As a response, I made the link configurable. (See https://github.com/rust-lang/docs.rs/issues/2551 for a detailed explanation and possible solution to remove this workaround in the future.)
It's probably easiest to review the individual commits. The last one is just a dummy to showcase the change. …
> Lintcheck: Add URL to lint emission place in diff

- triagebot.toml
What the title says.
---
cc: https://github.com/rust-lang/rust-clippy/pull/12947
r? @ghost
> Add xFrednet back to Clippy's reviewer roulette

- lintcheck/src/json.rs
- lintcheck/src/main.rs
- lintcheck/src/output.rs
- lintcheck/src/recursive.rs
This PR makes three changes to lintcheck's job summary:
* Adds links to the *Added*, *Removed*, *Changed* sections
* Added the crate name to the warning info
* Removes empty lines from the rendered output
This is what the new output roughly looks like:
[:framed_picture: Old Output :framed_picture:](https://github.com/xFrednet/rust-clippy/actions/runs/10019681444)
[:framed_picture: New Output :framed_picture:](https://github.com/xFrednet/rust-clippy/actions/runs/10019598141)
The links for the sections are a bit weird as you have to click on them twice. I believe this is a bug from GH's side. But it works reasonably well :D
---
r? @Alexendoo
> Lintcheck: Cleanup of Lintcheck's CI summery

- clippy_lints/src/unnecessary_struct_initialization.rs
- tests/ui/unnecessary_struct_initialization.fixed
- tests/ui/unnecessary_struct_initialization.rs
- tests/ui/unnecessary_struct_initialization.stderr
This lint makes Clippy warn about situations where an owned struct is
essentially recreated by moving all its fields into a new instance of
the struct. The lint is not machine-applicable because the source
struct may have been partially moved.
This lint originated in something I spotted during peer review. While
working on their branch a colleague ended up with a commit where a
function returned a struct that 1:1 replicated one of its owned inputs
from its members. Initially I suspected they hadn’t run their code
through Clippy but AFAICS there is no lint for this situation yet.
changelog: new lint: [`redundant_owned_struct_recreation`]
- \[+] Followed [lint naming conventions][lint_naming]
- \[+] Added passing UI tests (including committed `.stderr` file)
- \[+] `cargo test` passes …
> add lint for recreation of an entire struct

- clippy_lints/src/double_parens.rs
- clippy_lints/src/endian_bytes.rs
- clippy_lints/src/excessive_bools.rs
- clippy_lints/src/extra_unused_type_parameters.rs
- clippy_lints/src/future_not_send.rs
- clippy_lints/src/if_let_mutex.rs
- clippy_lints/src/if_not_else.rs
- clippy_lints/src/if_then_some_else_none.rs
- clippy_lints/src/ignored_unit_patterns.rs
- clippy_lints/src/inconsistent_struct_constructor.rs
- clippy_lints/src/index_refutable_slice.rs
- clippy_lints/src/indexing_slicing.rs
- clippy_lints/src/infinite_iter.rs
A couple of theses are a bit more involved. No behaviour changes included in this set.
> Misc refactorings part 2

- clippy_lints/src/misc.rs
- clippy_lints/src/mismatching_type_param_order.rs
- clippy_lints/src/mut_mut.rs
- clippy_lints/src/needless_borrowed_ref.rs
- clippy_lints/src/needless_for_each.rs
- clippy_lints/src/neg_cmp_op_on_partial_ord.rs
- clippy_lints/src/option_env_unwrap.rs
- clippy_lints/src/permissions_set_readonly_false.rs
- clippy_lints/src/raw_strings.rs
- tests/ui/toplevel_ref_arg.fixed
- tests/ui/toplevel_ref_arg.rs
`toplevel_ref_arg` gets a small fix so it can be allowed on function arguments. Otherwise just some rearrangements.
> Misc refactorings part 5

- clippy_lints/src/arc_with_non_send_sync.rs
- clippy_lints/src/borrow_deref_ref.rs
- clippy_lints/src/collapsible_if.rs
- clippy_lints/src/collection_is_never_read.rs
- clippy_lints/src/crate_in_macro_def.rs
- clippy_lints/src/else_if_without_else.rs
- clippy_lints/src/empty_enum.rs
- clippy_lints/src/equatable_if_let.rs
- clippy_lints/src/error_impl_error.rs
- clippy_lints/src/exhaustive_items.rs
- clippy_lints/src/exit.rs
- clippy_lints/src/float_literal.rs
- clippy_lints/src/from_over_into.rs
- clippy_lints/src/from_str_radix_10.rs
Various small re-orderings to check the HIR tree or AST before doing other checks. Also includes a small bug fix for `arc_with_small_send_sync` not actually checking for `Arc::new`.
> Misc refactorings

- lintcheck/src/input.rs
The generated URLs use `{krate}` for the crate name. This works well for the first part of the docs.rs domain, but the second part is actually the root module, which requires a replacement of all dashes with underscores. This PR adds `{krate_}` for the root module name.
Diff:
```diff
Removed `clippy::needless_borrows_for_generic_args` in `rustls-pemfile` at
-https://docs.rs/rustls-pemfile/2.1.2/src/rustls-pemfile/pemfile.rs.html#194
+https://docs.rs/rustls-pemfile/2.1.2/src/rustls_pemfile/pemfile.rs.html#194
```
> Example before: https://github.com/xFrednet/rust-clippy/actions/runs/10054236377?pr=4
> Example after: https://github.com/xFrednet/rust-clippy/actions/runs/10054878594?pr=4
---
r? @Alexendoo
> Lintcheck: Support underscores replacement in URL crate names

- clippy_lints/src/casts/ptr_cast_constness.rs
- clippy_lints/src/transmute/mod.rs
- clippy_lints/src/transmute/transmute_ptr_to_ptr.rs
- tests/ui/ptr_cast_constness.fixed
- tests/ui/ptr_cast_constness.rs
- tests/ui/ptr_cast_constness.stderr
- tests/ui/transmute_ptr_to_ptr.fixed
- tests/ui/transmute_ptr_to_ptr.rs
- tests/ui/transmute_ptr_to_ptr.stderr
- tests/ui/transmutes_expressible_as_ptr_casts.fixed
- tests/ui/transmutes_expressible_as_ptr_casts.stderr
Essentially pre-applies `ptr_as_ptr` - https://github.com/rust-lang/rust-clippy/issues/6372#issuecomment-1830438907
> Suggest `.cast`/`.cast_const`/`.cast_mut` in `transmute_ptr_as_ptr`

- triagebot.toml
I'm going to focus on the project goal and my own contributions, this + medical stuff leaves me not enough time to review.
I'll still review any performance related PR, and you can still request from me a benchmark for a PR, and will finish the PRs that I'm still assign to.
> Temporarily remove myself from reviewer rotation

- tests/compile-test.rs
`ui_test` itself has `cargo nextest` support which we now use - https://github.com/oli-obk/ui_test/pull/161
It prints `ui_test` as its test name whereas we printed `compile_test`, this ended up being treated as a test name filter causing all the tests to be filtered out
> Fix running compile-test under cargo nextest

- clippy.toml
- clippy_lints/src/methods/bind_instead_of_map.rs
- clippy_lints/src/methods/mod.rs
Makes it codegen once instead of three times
> Make `BindInsteadOfMap` a struct

- clippy_lints/src/lib.rs
- clippy_lints/src/lifetimes.rs
- clippy_lints/src/loops/mut_range_bound.rs
- clippy_lints/src/loops/while_immutable_condition.rs
- clippy_lints/src/methods/option_map_unwrap_or.rs
- clippy_lints/src/redundant_closure_call.rs
- clippy_lints/src/unconditional_recursion.rs
- clippy_lints/src/unused_peekable.rs
- clippy_utils/src/visitors.rs
Now, instead of manually using variables in visitors to signify that a visit is "done" and that the visitor should stop traversing. We use the trait type "Result" to signify this (in relevant places).
I'll schedule a perf run, I don't think it will be much of a difference, but every bit of performance is welcomed :)
changelog: Improve performance, less memory use in visitors
Fixes #12829
r? @y21
> Use ControlFlow in more places

- clippy_utils/src/visitors.rs
Small refactor in the `for_each_expr*` visitors. This should not change anything functionally.
Instead of storing the final value `Option<B>` in the visitor and setting it to `Some` when we get a `ControlFlow::Break(B)` from the closure, we can just directly return it from the visitor itself now that visitors support that.
cc #12829 and https://github.com/rust-lang/rust-clippy/pull/12830#discussion_r1627882827
> Remove unnecessary `res` field in `for_each_expr` visitors

- clippy_lints/src/needless_borrows_for_generic_args.rs
- tests/ui/needless_borrows_for_generic_args.fixed
- tests/ui/needless_borrows_for_generic_args.rs
This commit fixes a bug introduced in #12706, where the behavior of the lint has been changed, to avoid suggestions that introduce a move. The motivation in the commit message is quite poor (if the detection for significant drops is not sufficient because it's not transitive, the proper fix would be to make it transitive). However, #12454, the linked issue, provides a good reason for the change — if the value being borrowed is bound to a variable, then moving it will only introduce friction into future refactorings.
Thus #12706 changes the logic so that the lint triggers if the value being borrowed is Copy, or is the result of a function call, simplifying the logic to the point where analysing "is this the only use of this value" isn't necessary.
However, said PR also introduces an …
> needless_borrows_for_generic_args: Fix for &mut

- clippy_lints/src/assigning_clones.rs
- tests/ui/assigning_clones.fixed
- tests/ui/assigning_clones.rs
- tests/ui/assigning_clones.stderr
The `assigning_clones` lint had a special case for producing a bit nicer code for mutable references:
```rust
fn clone_function_lhs_mut_ref(mut_thing: &mut HasCloneFrom, ref_thing: &HasCloneFrom) {
*mut_thing = Clone::clone(ref_thing);
}
//v
fn clone_function_lhs_mut_ref(mut_thing: &mut HasCloneFrom, ref_thing: &HasCloneFrom) {
Clone::clone_from(mut_thing, ref_thing);
}
```
However, this could [break](https://github.com/rust-lang/rust-clippy/issues/12437) when combined with `Deref`.
This PR removes the special case, so that the generated code should work more generally. Later we can improve the detection of `Deref` and put the special case back in a way that does not break code.
Fixes: https://github.com/rust-lang/rust-clippy/issues/12437
r? @blyxyas
changelog: [`assigning_clones`]: …
> Fix handling of `Deref` in `assigning_clones`

- clippy_lints/src/asm_syntax.rs
- clippy_lints/src/drop_forget_ref.rs
- clippy_lints/src/float_literal.rs
- clippy_lints/src/inherent_impl.rs
- clippy_lints/src/large_include_file.rs
- clippy_lints/src/let_underscore.rs
- clippy_lints/src/methods/map_err_ignore.rs
- clippy_lints/src/missing_assert_message.rs
- clippy_lints/src/missing_trait_methods.rs
- clippy_lints/src/mixed_read_write_in_expression.rs
- clippy_lints/src/module_style.rs
- clippy_lints/src/operators/integer_division.rs
- clippy_lints/src/partial_pub_fields.rs
- clippy_lints/src/pattern_type_mismatch.rs
- clippy_lints/src/pub_use.rs
- clippy_lints/src/unicode.rs
- clippy_lints/src/visibility.rs
- tests/ui/excessive_precision.stderr
- tests/ui/lossy_float_literal.stderr
- tests/ui/needless_pub_self.stderr
This migrates a few restriction lints to use `span_lint_and_then`. This change is motivated by https://github.com/rust-lang/rust-clippy/issues/7797.
I've also cleaned up some lint message. Mostly minor stuff. For example: suggestions with a longer message than `"try"` now use `SuggestionStyle::ShowAlways`
---
cc: https://github.com/rust-lang/rust-clippy/issues/7797
brother PR of: https://github.com/rust-lang/rust-clippy/pull/13136
> Make restriction lint's use `span_lint_and_then` (i -> p)

- clippy_lints/src/approx_const.rs
- clippy_lints/src/default.rs
- clippy_lints/src/methods/open_options.rs
- clippy_lints/src/methods/wrong_self_convention.rs
- clippy_lints/src/no_effect.rs
- clippy_lints/src/types/borrowed_box.rs
Clean up a few minor refs in `format!` macro, as it has a performance cost. Apparently the compiler is unable to inline `format!("{}", &variable)`, and does a run-time double-reference instead (format macro already does one level referencing).
Inlining format args prevents accidental `&` misuse.
See also https://github.com/rust-lang/rust/issues/112156
> Avoid ref when using format!

- clippy_lints/src/lib.rs
- clippy_lints/src/std_instead_of_core.rs
- tests/ui/std_instead_of_core.fixed
- tests/ui/std_instead_of_core.rs
- tests/ui/std_instead_of_core.stderr
For #13158, this catches some things e.g. `core::net` and the recently stable `core::error` but not things moved individually like `UnwindSafe`, as far as I can see the version for those isn't easily available
Beta nominating since ideally we'd get this change in the same version as `core::error` becomes stable
cc @kpreid
> Make `std_instead_of_core` somewhat MSRV aware

- clippy_lints/src/lib.rs
- clippy_lints/src/set_contains_or_insert.rs
- tests/ui/set_contains_or_insert.rs
- tests/ui/set_contains_or_insert.stderr
* Detect `BTreeSet::contains` + `BTreeSet::insert` usage in the same way as with the `HashSet`.
CC: @lochetti @bitfield
----
changelog: [`set_contains_or_insert`]: Handle `BTreeSet` in addition to `HashSet`
> Add `BTreeSet` detection to the `set_contains_or_insert` lint

- clippy_lints/src/loops/while_let_on_iterator.rs
- clippy_utils/src/higher.rs
- tests/ui/while_let_on_iterator.fixed
- tests/ui/while_let_on_iterator.rs
- tests/ui/while_let_on_iterator.stderr
Loop label was not persisted when displaying help and was therefore producing broken rust code when applying fixes.
Solution was to store the `ast::Label` when creating a `higher::WhileLet` from an expression and add the label name to the lint suggestion and diagnostics.
---
Fixes: https://github.com/rust-lang/rust-clippy/issues/13123
changelog: [`while_let_on_iterator`]: Fix issue dropping loop label when displaying help and applying fixes.
> Fix while_let_on_iterator dropping loop label when applying fix.

- clippy_lints/src/missing_trait_methods.rs
- tests/ui/missing_trait_methods.rs
- tests/ui/missing_trait_methods.stderr
Lintcheck for #13157 showed a bunch of changes for `missing_trait_methods`
This is because `values_sorted` was sorting the entries by the key's [`DefPathHash`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_span/def_id/struct.DefPathHash.html), this is stable for a given compiler but can change across versions
> `missing_trait_methods`: lint methods in definition order

- clippy_config/src/metadata.rs
- clippy_lints/src/utils/internal_lints/metadata_collector.rs
Fixes https://github.com/rust-lang/rust-clippy/issues/13051.
It was simply some empty lines missing between configs. With this fix it looks like expected:
r? @xFrednet 
changelog: Fix display of configs in clippy doc page
> Fix display of configs in clippy doc page

- clippy_lints/src/if_let_mutex.rs
- tests/ui/if_let_mutex.rs
- tests/ui/if_let_mutex.stderr
Currently (master, not nightly nor stable) `if_let_mutex` does not emit a warning here:
```rs
let m1 = Mutex::new(10);
let m2 = Mutex::new(());
if let 100..=200 = *m1.lock().unwrap() {
m2.lock();
} else {
m1.lock();
}
```
It currently looks for the first call to `.lock()` on *any* mutex receiver inside of the if/else body, and only later (outside of the visitor) checks that the receiver matches the mutex in the scrutinee. That means that in cases like the above, it finds the `m2.lock()` expression, stops the visitor, fails the check that it's the same mutex (`m2` != `m1`) and then does not look for any other `.lock()` calls.
So, just make the receiver check also part of the visitor so that we only stop the visitor when we also find the right receiver.
The first commit has the actual …
> Emit `if_let_mutex` in presence of other mutexes

- util/gh-pages/index.html
- util/gh-pages/script.js
This PR adds the possibility to focus on the search input with `S` or `/` like in rustdoc and `mdbook` and `docs.rs` (unification++). Pressing escape will blur it.
r? @Alexendoo 
changelog: Add possibility to focus on search input using keyboard
> Add possibility to focus on search input using keyboard

- clippy_dev/src/serve.rs
- clippy_lints/src/incompatible_msrv.rs
- clippy_lints/src/indexing_slicing.rs
- clippy_lints/src/infinite_iter.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/methods/iter_kv_map.rs
- clippy_lints/src/methods/mod.rs
- clippy_lints/src/only_used_in_recursion.rs
- clippy_utils/src/lib.rs
Some were unneeded, others were removed by fixing/removing the thing they allow
> Remove some miscellaneous `#[allow]`s

- clippy_config/src/metadata.rs
- clippy_lints/src/utils/internal_lints/metadata_collector.rs
Follow-up of #13166.
Finally figured out that it was a transformation and not the source that was the problem. It now looks like this:
r? @xFrednet 
> Fix broken list for lints config

- clippy_lints/src/doc/mod.rs
- tests/ui/doc/footnote_issue_13183.rs
Fixes #13183.
changelog: Fix false positive for `missing_backticks` in footnote references
> Fix false positive for `missing_backticks` in footnote references

- clippy_lints/src/eta_reduction.rs
- tests/ui/eta.fixed
- tests/ui/eta.rs
- tests/ui/eta.stderr
Fix #13073 .
Please enable "ignore white-space change" settings in github UI for easy reviewing.
HACK: The third commit contains a hack to check if a type `T: 'static` when `fn() -> U where U: 'static`.
I don't have a clean way to check for it.
changelog: [`redundant_closure`] Fix false positive with closures has return type contains  `'static`
> Fix `redundant_closure` false positive with closures has return type contains  `'static`

- clippy_lints/src/redundant_slicing.rs
- tests/ui/deref_by_slicing.fixed
- tests/ui/deref_by_slicing.rs
- tests/ui/deref_by_slicing.stderr
Fixes #12751
changelog: Fix [`redundant_slicing`] when the slice is behind a mutable reference and a immutable reference is expected.
> Fix [`redundant_slicing`] when the slice is behind a mutable reference

- clippy_lints/src/dereference.rs
- clippy_lints/src/matches/single_match.rs
- clippy_lints/src/methods/implicit_clone.rs
- clippy_lints/src/methods/unnecessary_to_owned.rs
- clippy_lints/src/redundant_slicing.rs
- clippy_lints/src/size_of_ref.rs
- clippy_utils/src/ty.rs
TODO: Should we move `ty::peel_mid_ty_refs_is_mutable` to super module too?
> Remove duplicated `peel_middle_ty_refs`

- tests/ui/try_err.fixed
- tests/ui/try_err.rs
Fixes #5757
Turns out the current `try_err` implementation already skips expressions inside of a try block.
When inside of a try block, `Err(_)?` is desugared to a `break` instead of normal `return` . This makes `find_return_type()` function at [this line](https://github.com/rust-lang/rust-clippy/blob/eb4d88e690c431691bc0fd8eaa9f7096ecc2a723/clippy_lints/src/matches/try_err.rs#L29) always returns `None` and skips the check.
I just added a test case for try block.
> Add test for `try_err` lint within try blocks.

- clippy_lints/src/methods/mod.rs
Close #13147
As mentioned at #13147 we should prefer to use collect depends on situation so clarify this at documentation and provide examples this cases.
> Add clarification for from_iter_instead_of_collect

- clippy_lints/src/booleans.rs
- tests/ui/nonminimal_bool.rs
Fixes https://github.com/rust-lang/rust-clippy/issues/11257
Fixes https://github.com/rust-lang/rust-clippy/issues/13206
> Limit number of `nonminimal_bool` ops

- clippy_lints/src/loops/for_kv_map.rs
- clippy_lints/src/loops/manual_while_let_some.rs
- clippy_lints/src/loops/needless_range_loop.rs
- clippy_lints/src/loops/unused_enumerate_index.rs
- clippy_lints/src/manual_strip.rs
- clippy_lints/src/matches/match_ref_pats.rs
- clippy_lints/src/methods/bind_instead_of_map.rs
- clippy_lints/src/methods/unused_enumerate_index.rs
- clippy_lints/src/needless_pass_by_value.rs
- clippy_lints/src/operators/op_ref.rs
- clippy_lints/src/semicolon_block.rs
- clippy_lints/src/utils/internal_lints/metadata_collector.rs
- clippy_utils/src/diagnostics.rs
- tests/ui/bind_instead_of_map_multipart.stderr
They're thin wrappers over the corresponding diag method so we should just use that instead
> Remove `multispan_sugg[_with_applicability]`

- rustc_tools_util/src/lib.rs
Using `git rev-parse --short` in rustc_tools_util causes nondeterministic compilation of projects that use `setup_version_info!` and `get_version_info!` when built from the exact same source code and git commit. The number of digits printed by `--short` is sensitive to how many other branches and tags in the repository have been fetched so far, what other commits have been worked on in other branches, how recently you had run `git gc`, platform-specific variation in git's default configuration, and platform differences in the sequence of steps performed by the release pipeline. Someone can compile a tool from a particular commit, switch branches to work on a different commit (or simply do a git fetch), go back to the first commit and be unable to reproduce the binary that was built from …
> Use a deterministic number of digits in rustc_tools_util commit hashes

- clippy_lints/src/matches/match_wild_enum.rs
- clippy_lints/src/matches/rest_pat_in_fully_bound_struct.rs
- clippy_lints/src/matches/try_err.rs
- clippy_lints/src/methods/verbose_file_reads.rs
- clippy_lints/src/misc_early/literal_suffix.rs
- clippy_lints/src/misc_early/unneeded_field_pattern.rs
- clippy_lints/src/question_mark_used.rs
- clippy_lints/src/ref_patterns.rs
- clippy_lints/src/shadow.rs
- clippy_lints/src/single_char_lifetime_names.rs
- clippy_lints/src/std_instead_of_core.rs
- clippy_lints/src/strings.rs
- clippy_lints/src/suspicious_xor_used_as_pow.rs
- clippy_lints/src/tests_outside_test_module.rs
- clippy_lints/src/types/rc_buffer.rs
- clippy_lints/src/types/rc_mutex.rs
- clippy_lints/src/undocumented_unsafe_blocks.rs
- tests/ui/suspicious_xor_used_as_pow.stderr
This migrates a few restriction lints to use `span_lint_and_then`. This change is motivated by https://github.com/rust-lang/rust-clippy/issues/7797.
I've also cleaned up some lint message. Mostly minor stuff. For example: suggestions with a longer message than `"try"` now use `SuggestionStyle::ShowAlways`
---
cc: https://github.com/rust-lang/rust-clippy/issues/7797
sister PR of: https://github.com/rust-lang/rust-clippy/pull/13136
> Make restriction lint's use `span_lint_and_then` (q -> w)

- .github/workflows/lintcheck.yml
- lintcheck/src/config.rs
- lintcheck/src/main.rs
It occurred to me that like `--filter` we could use `--force-warn` for normal operations, we especially want to see lints that crates decided were too annoying or were false positives
Also excludes `clippy::cargo` from the default set as nobody is really writing those and it slows things down
r? @xFrednet
> lintcheck: force warn all lints

- .github/workflows/clippy.yml
- .github/workflows/clippy_bors.yml
- .github/workflows/clippy_dev.yml
- Cargo.toml
- clippy_config/Cargo.toml
- clippy_config/src/lib.rs
- clippy_dev/Cargo.toml
- clippy_dev/src/lib.rs
- clippy_dev/src/main.rs
- clippy_lints/Cargo.toml
- clippy_lints/src/lib.rs
- clippy_utils/Cargo.toml
- clippy_utils/src/lib.rs
- declare_clippy_lint/Cargo.toml
- declare_clippy_lint/src/lib.rs
- lintcheck/Cargo.toml
- rustc_tools_util/Cargo.toml
- rustc_tools_util/src/lib.rs
- src/driver.rs
- src/main.rs
- tests/check-fmt.rs
- tests/compile-test.rs
- tests/dogfood.rs
- tests/integration.rs
- tests/lint_message_convention.rs
- tests/missing-test-files.rs
- tests/versioncheck.rs
- tests/workspace_test/path_dep/Cargo.toml
> Use `-D warnings` instead of `deny-warnings` feature.

- CHANGELOG.md
- clippy_dev/src/update_lints.rs
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/unused_result_ok.rs
- tests/ui/unused_result_ok.fixed
- tests/ui/unused_result_ok.rs
- tests/ui/unused_result_ok.stderr
This PR adds a lint to capture the use of `expr.ok();` when the result is not _really_ used.
This could be interpreted as the result being checked (like it is with `unwrap()` or `expect`) but
it actually only ignores the result.
`let _ = expr;` expresses that intent better.
This was also mentionned in #8994 (although not being the main topic of that issue).
changelog: [`misleading_use_of_ok`]: Add new lint to capture `.ok();` when the result is not _really_ used.
> Add lint for `unused_result_ok`

- .cargo/config.toml
`cargo dev` and `cargo lintcheck` use `--manifest-path` to select the package to compile, with this Cargo changes the CWD to the package's containing directory meaning paths in diagnostics start from e.g. `src/` instead of `clippy_dev/src/`
Lintcheck uses a `--remap-path-prefix` trick when linting crates to re-add the directory name in diagnostics: 
https://github.com/rust-lang/rust-clippy/blob/5ead90f13ae3e03f0c346aea3198f18298960d83/lintcheck/src/main.rs#L93-L94
https://github.com/rust-lang/rust-clippy/blob/5ead90f13ae3e03f0c346aea3198f18298960d83/lintcheck/src/main.rs#L102-L103
It works well as far as I can tell, when absolute paths appear they stay absolute and do not have the prefix added
[`profile-rustflags`](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#profile-rus …
> Add path prefixes back when compiling `clippy_dev` and `lintcheck`

- lintcheck/src/main.rs
Removes the `help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#...` line to make the reports more concise
r? @xFrednet
> lintcheck: disable doc links

- clippy_lints/src/matches/match_wild_enum.rs
- clippy_lints/src/matches/overlapping_arms.rs
- clippy_lints/src/matches/single_match.rs
- tests/ui-toml/excessive_nesting/excessive_nesting.rs
- tests/ui-toml/excessive_nesting/excessive_nesting.stderr
- tests/ui/crashes/ice-6254.rs
- tests/ui/patterns.fixed
- tests/ui/patterns.rs
- tests/ui/single_match.fixed
- tests/ui/single_match.rs
- tests/ui/single_match.stderr
- tests/ui/unneeded_field_pattern.rs
fixes #11365
This approach has false-negatives, but fixing them will require a significant amount of additional state tracking. The comment in `add_and_pats` has the explanation.
changelog: `single_match`: correct checking if the match explicitly matches all of an enum's variants.
> `single_match`: fix checking of explicitly matched enums

- clippy_lints/src/bool_to_int_with_if.rs
- clippy_lints/src/casts/cast_lossless.rs
- clippy_lints/src/casts/zero_ptr.rs
- clippy_lints/src/checked_conversions.rs
- clippy_lints/src/comparison_chain.rs
- clippy_lints/src/doc/mod.rs
- clippy_lints/src/floating_point_arithmetic.rs
- clippy_lints/src/from_str_radix_10.rs
- clippy_lints/src/if_then_some_else_none.rs
- clippy_lints/src/manual_clamp.rs
- clippy_lints/src/manual_is_ascii_check.rs
- clippy_lints/src/manual_rem_euclid.rs
- clippy_lints/src/manual_slice_size_calculation.rs
- clippy_lints/src/manual_unwrap_or_default.rs
- clippy_lints/src/matches/match_wild_err_arm.rs
- clippy_lints/src/matches/mod.rs
- clippy_lints/src/matches/redundant_guards.rs
- clippy_lints/src/non_copy_const.rs
- clippy_lints/src/option_if_let_else.rs
- clippy_lints/src/question_mark.rs
- clippy_lints/src/ranges.rs
- clippy_lints/src/swap.rs
- clippy_lints/src/transmute/mod.rs
- clippy_utils/src/lib.rs
> Don't walk the HIR tree when checking for a const context

- clippy_lints/src/inconsistent_struct_constructor.rs
- tests/ui/inconsistent_struct_constructor.fixed
- tests/ui/inconsistent_struct_constructor.rs
- tests/ui/inconsistent_struct_constructor.stderr
Closes #13203 
Now we check if the target type is marked with `#[allow(clippy:inconsistent_struct_constructor)]` before lining.
As a side-effect of this change, The rule in the subject no longer runs on non-local `AdtDef`s. However, as suggested by @Jarcho it shouldn't be a big deal since most of the time we didn't have access to this information anyway.
> You can't get lint attributes from other crates. I would probably just restrict the lint to only work with types from the current crate while you're at it. Upstream crates don't have a definition order from the point of view of the current crate (with the exception of #[repr(C)] structs).
changelog: Respect allow `inconsistent_struct_constructor` on the struct definition.
> Respect allow `inconsistent_struct_constructor` on the struct definition

- clippy_lints/src/macro_metavars_in_unsafe.rs
- tests/ui-toml/macro_metavars_in_unsafe/default/test.rs
- tests/ui-toml/macro_metavars_in_unsafe/default/test.stderr
Fixes #13219
`macro_metavars_in_unsafe` keeps track of the current "expansion depth" (incremented/decremented when entering/leaving a macro span) to tell if an expression from the root context is contained within a macro (see the doc comment I added for a hopefully better explanation)
Before this PR, we didn't increment said `expn_depth` for `unsafe` blocks within macros, because we already do that in `visit_stmt` anyway, so it would work fine for statements, but that's not enough for tail expressions of an unsafe block.
So we now also increment it for macro unsafe blocks.
Also updated the comment for `expn_depth` while I'm at it because "This is not necessary for correctness" isn't correct now that I think about it
------
> [`macro_metavars_in_unsafe`]: recognize metavariables in tail expressions

- clippy_lints/src/doc/markdown.rs
- tests/ui/doc/doc_markdown-issue_13097.fixed
- tests/ui/doc/doc_markdown-issue_13097.rs
- tests/ui/doc/doc_markdown-issue_13097.stderr
Fixes #13097.
r? @Alexendoo 
changelog: Fix case where doc_markdown is triggered on words ending with "ified"
> Fix case where doc_markdown is triggered on words ending with "ified"

- lintcheck/src/json.rs
- lintcheck/src/output.rs
Before: https://github.com/rust-lang/rust-clippy/actions/runs/10305798317
After: https://github.com/Alexendoo/rust-clippy/actions/runs/10333749860
If a single lint emits e.g. twice on the same line and the messages change for both there would still be two changed entries
Also slightly changes the output, the URL is no longer visible
r? @xFrednet
> lintcheck: key lints on line start rather than byte start/end

- clippy_lints/src/attrs/empty_line_after.rs
- clippy_lints/src/attrs/non_minimal_cfg.rs
- clippy_lints/src/attrs/unnecessary_clippy_cfg.rs
- clippy_lints/src/attrs/useless_attribute.rs
- clippy_lints/src/casts/as_ptr_cast_mut.rs
- clippy_lints/src/manual_async_fn.rs
- clippy_lints/src/matches/single_match.rs
- clippy_lints/src/needless_pass_by_value.rs
- clippy_lints/src/pathbuf_init_then_push.rs
- clippy_lints/src/ptr.rs
- clippy_lints/src/ptr_offset_with_cast.rs
- clippy_lints/src/redundant_clone.rs
- clippy_lints/src/reference.rs
- clippy_lints/src/regex.rs
- clippy_lints/src/returns.rs
- clippy_lints/src/single_range_in_vec_init.rs
- clippy_lints/src/trait_bounds.rs
- clippy_lints/src/unused_unit.rs
- clippy_lints/src/visibility.rs
- clippy_lints/src/write.rs
- clippy_utils/src/consts.rs
- clippy_utils/src/hir_utils.rs
- clippy_utils/src/source.rs
First commit is the same as #13244
> Remove more `snippet_opt` calls

- clippy_lints/src/doc/mod.rs
- clippy_lints/src/methods/mod.rs
- clippy_lints/src/utils/internal_lints/metadata_collector.rs
The metadata collector script was treating the space lines all start with as indentation. This caused code block's triple backticks to get a space in front of it, like this:
```
```rust
^ this space
```
Code after that that is indented with 4 spaces will only have 3 of those rendered.
Example (taken from [here](https://rust-lang.github.io/rust-clippy/master/index.html#/missing_panics_doc)):
```rust
...
pub fn divide_by(x: i32, y: i32) -> i32 {
if y == 0 {                      // 3 spaces
panic!("Cannot divide by 0") // 7 spaces
...
```
Also added 'compile_fail' alongside the other rustdoc directives (second code block [here](https://rust-lang.github.io/rust-clippy/master/index.html#/macro_metavars_in_unsafe) had no highlighting), fixed a doc comment using 'rs' instead of 'rust' and …
```
> fix code blocks in doc comments inconsistently using 3 or 4 spaces of indentation

- tests/ui/crashes/ice-3717.fixed
- tests/ui/crashes/ice-3717.stderr
this PR is a part of https://github.com/rust-lang/rust-clippy/issues/13099.
Based on the changes introduced in #13098 for introduce ui_test, we will update the uitest output.
This is a fix for `ice-3717.rs`.
Although fixes have already been made in #13216, it seems that he is a first-time contributor.
I thought it might be better for him to refer to my PR, so I created it accordingly.
Since this is my first contribution in a while, please let me know if there are any issues or required changes.
r! @flip1995
> Add a test for ice-3717.rs

- clippy_lints/src/attrs/mod.rs
- clippy_lints/src/operators/mod.rs
- declare_clippy_lint/src/lib.rs
Links to github ('View Source') were broken by [pull request 13221](https://github.com/rust-lang/rust-clippy/pull/13221/files#diff-dcd0f8da3873f35e9777182474a9d0f287f478c0c02650a1d3fefffe1c8c1d30R159).
also fixed some indentation in docs
> Fix lint source location github link (missing a letter 'L')

- clippy_lints/src/unwrap.rs
- tests/ui/checked_unwrap/complex_conditionals_nested.stderr
- tests/ui/checked_unwrap/simple_conditionals.stderr
Close #10217
As mentioned at #10217 message for `unwrap` uses `..` like `Some(..)` which can confuse with slice and other places mostly use `<item>` like `for (i, <item>) in target_groups_json.iter().enumerate().skip(1) {` So replace  `..` to `<item>`
changelog: [`unnecessary_unwrap`] clarify suggestion message
> Clarify suggestion message for unwrap lint

- clippy_lints/src/from_str_radix_10.rs
`<expression>` was being treated as an opening HTML tag
> Fix code snippet in from_str_radix_10 docs

- clippy_lints/src/assigning_clones.rs
- tests/ui/assigning_clones.fixed
- tests/ui/assigning_clones.rs
Close: #12752 
As mentioned at #12752 when a test struct is initialized with some default string, this inverts the order of assignee/assignment and makes a bit harder to read/write code
changelog: [`assigning_clones.rs`]: disable assigning_clones for tests
> Disable assigning_clones for tests

- clippy_lints/src/format.rs
- clippy_lints/src/format_args.rs
- clippy_lints/src/format_impl.rs
- clippy_utils/src/macros.rs
If the function fails where it shouldn't we can fix that directly, but the fallback path is untested as I'm not aware of a case where it would fail
> Remove `find_format_arg_expr` AST fallback

- clippy_lints/src/strings.rs
- tests/ui/string_slice.rs
- tests/ui/string_slice.stderr
Close #12708
changelog: [`string_slice`]: trigger lint if expression is reference to `&str`
>  Trigger [`string_slice`] if expression is reference to `&str`

- clippy_lints/src/cfg_not_test.rs
Found this typo while looking at Clippy lints
> fix typo in cfg_not_test lint description

- clippy_lints/src/functions/must_use.rs
- tests/ui/double_must_use.rs
- tests/ui/double_must_use.stderr
Close #13003 
As mentioned at #13003 it isn't quite clear what it means "an empty `#[must_use]` attribute" so clarify it
changelog: [none]
> Fix confusing message in double_must_use lint

- clippy_lints/src/non_copy_const.rs
- tests/ui/declare_interior_mutable_const/others.rs
- tests/ui/declare_interior_mutable_const/others.stderr
fixes #12951
fixes #13233
changelog: `declare_interior_mutable_const`: Ignore pointer types.
> `declare_interior_mutable_const`: Ignore pointer types.

- clippy_lints/src/returns.rs
- clippy_lints/src/use_self.rs
> Fix a couple of typos.

- clippy_lints/src/booleans.rs
- clippy_lints/src/borrow_deref_ref.rs
- clippy_lints/src/format.rs
- clippy_lints/src/format_args.rs
- clippy_lints/src/from_over_into.rs
- clippy_lints/src/int_plus_one.rs
- clippy_lints/src/items_after_test_module.rs
- clippy_lints/src/large_stack_frames.rs
- clippy_lints/src/len_zero.rs
- clippy_lints/src/literal_representation.rs
- clippy_lints/src/manual_float_methods.rs
- clippy_lints/src/manual_hash_one.rs
- clippy_lints/src/manual_non_exhaustive.rs
- clippy_lints/src/manual_range_patterns.rs
- clippy_lints/src/methods/unnecessary_iter_cloned.rs
- clippy_lints/src/misc_early/unneeded_field_pattern.rs
- clippy_lints/src/missing_enforced_import_rename.rs
- clippy_lints/src/needless_if.rs
- clippy_lints/src/needless_late_init.rs
- clippy_lints/src/no_effect.rs
- clippy_lints/src/nonstandard_macro_braces.rs
- clippy_lints/src/operators/assign_op_pattern.rs
- clippy_lints/src/operators/misrefactored_assign_op.rs
- clippy_lints/src/operators/needless_bitwise_bool.rs
- clippy_lints/src/operators/ptr_eq.rs
- clippy_lints/src/unit_types/unit_arg.rs
- clippy_lints/src/utils/format_args_collector.rs
- clippy_utils/src/attrs.rs
- clippy_utils/src/hir_utils.rs
Continuing the job of removing unnecessary allocations.
> Start removing `snippet_opt` in favor of `get_source_text`

- clippy_lints/src/casts/cast_lossless.rs
- clippy_lints/src/casts/unnecessary_cast.rs
- clippy_lints/src/casts/zero_ptr.rs
- clippy_lints/src/functions/must_use.rs
- clippy_lints/src/functions/too_many_lines.rs
- clippy_lints/src/matches/manual_unwrap_or.rs
- clippy_lints/src/methods/case_sensitive_file_extension_comparisons.rs
- clippy_lints/src/methods/filter_map_bool_then.rs
- clippy_lints/src/methods/from_iter_instead_of_collect.rs
- clippy_lints/src/methods/join_absolute_paths.rs
- clippy_lints/src/methods/manual_ok_or.rs
- clippy_lints/src/methods/manual_try_fold.rs
- clippy_lints/src/methods/needless_character_iteration.rs
- clippy_lints/src/methods/needless_option_as_deref.rs
- clippy_lints/src/methods/string_lit_chars_any.rs
- clippy_lints/src/methods/unnecessary_get_then_check.rs
- clippy_lints/src/methods/unnecessary_to_owned.rs
- clippy_lints/src/methods/unused_enumerate_index.rs
- clippy_lints/src/vec.rs
- clippy_utils/src/source.rs
Almost all calls are removed after this.
> Replace more uses of `snippet_opt`.

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/doc/mod.rs
- clippy_lints/src/doc/too_long_first_doc_paragraph.rs
- clippy_utils/src/lib.rs
- clippy_utils/src/macros.rs
- clippy_utils/src/source.rs
- clippy_utils/src/ty.rs
- tests/ui/too_long_first_doc_paragraph-fix.fixed
- tests/ui/too_long_first_doc_paragraph-fix.rs
- tests/ui/too_long_first_doc_paragraph-fix.stderr
- tests/ui/too_long_first_doc_paragraph.rs
- tests/ui/too_long_first_doc_paragraph.stderr
Fixes https://github.com/rust-lang/rust-clippy/issues/12989.
changelog: Add new `too_long_first_doc_paragraph` first paragraph lint
> Add new `too_long_first_doc_paragraph` first paragraph lint

- clippy_lints/src/mixed_read_write_in_expression.rs
- tests/ui/diverging_sub_expression.rs
As per #10243  it is not that helpful to point out that a subexpression diverges, so do not fire on todo 
changelog: [`diverging_sub_expression`]: do not trigger on todo
> Diverging subexpression lint should not fire on todo!()

- clippy_lints/src/needless_pass_by_value.rs
- tests/ui/needless_pass_by_value.rs
- tests/ui/needless_pass_by_value.stderr
When a user explicitly tags a param as unused (yet?), there is no need to raise another lint on it.
fixes #7295
Note that I had to rename all `_*` params in the tests, but kept the variable name length to avoid extra changes in the expected output.
changelog: [`needless_pass_by_value`]: do not warn if the argument name starts with an `_`
> Ignore underscore-prefixed args for needless_pass_by_value lint

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/misc.rs
- tests/ui/auxiliary/external_item.rs
- tests/ui/used_underscore_binding.stderr
- tests/ui/used_underscore_items.rs
- tests/ui/used_underscore_items.stderr
Closes #13260 
---
changelog: new [`used_underscore_items`] lint against using items with a single leading underscore
> Add new lint: `used_underscore_items`

- clippy_lints/src/methods/unnecessary_min_or_max.rs
- tests/ui/unnecessary_min_or_max.fixed
- tests/ui/unnecessary_min_or_max.rs
close #13191 
This PR fixes the false positives in `unnecessary_min_or_max `.
We should use `is_diagnostic_item` for checking def_ids in this lint.
----
changelog: fix false positive in `unnecessary_min_or_max `.
> Use `is_diagnostic_item` for checking a def_id in `unnecessary_min_or_max`.

- src/driver.rs
Roses are red,
Fixme was written,
And now it's due
---
changelog: **Important Change** Removed the implicit `cargo-clippy` feature set by Clippy as announced here: <https://blog.rust-lang.org/2024/02/28/Clippy-deprecating-feature-cargo-clippy.html>
[#13246](https://github.com/rust-lang/rust-clippy/pull/13246)
Follow-up of: rust-lang/rust-clippy#12292
r? @flip1995 
cc: @GuillaumeGomez
> Remove `feature=cargo-clippy` argument

- clippy_lints/src/methods/mod.rs
Provide more clear example for `WRONG_SELF_CONVENTION` 
> Provide more clear example for `WRONG_SELF_CONVENTION`

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/pointers_in_nomem_asm_block.rs
- tests/ui/pointers_in_nomem_asm_block.rs
- tests/ui/pointers_in_nomem_asm_block.stderr
changelog: Add new check for passing pointers to an `asm!` block with `nomem` option
Continuing work from https://github.com/rust-lang/rust/pull/127063
> Add new check for passing pointers to an `asm!` block with `nomem` option

- clippy_lints/src/methods/mod.rs
IMO the suggestion to use `c""` literals over a hardcoded `\0` byte string literal has some fairly strong upsides (no need to manually null-terminate it and the compiler checks for intermediary null bytes) that this should just be enabled by default.
It's also written slightly conservatively to only emit a warning when we can be reasonably confident that the lint is *actually* applicable (that is, lint on e.g. `b"foo\0".as_ptr()` but not `b"foo\0"`. The latter looks like a c-string but its type is `&[u8; _]`, and if it's used in a context where a byte slice is needed then you have no nice way to convert to it from a `c"foo"` literal of type `&CStr`).
changelog: move [`manual_c_str_literals`] to complexity (now warn-by-default)
> move `manual_c_str_literals` to complexity

- .github/workflows/clippy_bors.yml
> Bump actions/download-artifact from 3 to 4

- CHANGELOG.md
- clippy_lints/src/byte_char_slices.rs
- clippy_lints/src/cfg_not_test.rs
- clippy_lints/src/field_scoped_visibility_modifiers.rs
- clippy_lints/src/methods/mod.rs
- clippy_lints/src/needless_maybe_sized.rs
- clippy_lints/src/set_contains_or_insert.rs
- clippy_lints/src/string_patterns.rs
Roses are red,
Expectations are stable,
And reasons are set
---
---
> Changelog for Clippy 1.81 :beginner:

- clippy_lints/src/lib.rs
- clippy_lints/src/manual_non_exhaustive.rs
- tests/ui/manual_non_exhaustive_enum.rs
- tests/ui/manual_non_exhaustive_enum.stderr
- tests/ui/manual_non_exhaustive_struct.rs
- tests/ui/manual_non_exhaustive_struct.stderr
For types that are not exported the attribute doesn't make a difference, but the manual pattern can still be used to achieve module level non exhaustiveness
Fixes https://github.com/rust-lang/rust-clippy/issues/10301
Fixes https://github.com/rust-lang/rust-clippy/issues/12106
> Only lint `manual_non_exhaustive` for exported types

- clippy_lints/src/doc/mod.rs
`too_long_first_doc_paragraph` is, empirically, not in the Rust 1.81.0 release.
changelog: [`too_long_first_doc_paragraph`]: correct Rust version number in documentation.
> Correct version of `too_long_first_doc_paragraph`

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/manual_is_power_of_two.rs
- tests/ui/manual_is_power_of_two.fixed
- tests/ui/manual_is_power_of_two.rs
- tests/ui/manual_is_power_of_two.stderr
Suggest using `is_power_of_two()` instead of the manual implementations for some basic cases
Part of https://github.com/rust-lang/rust-clippy/issues/12894
----
changelog: new [`manual_is_power_of_two`] lint
> Add new lint `manual_is_power_of_two`

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/non_zero_suggestions.rs
- tests/ui/non_zero_suggestions.fixed
- tests/ui/non_zero_suggestions.rs
- tests/ui/non_zero_suggestions.stderr
- tests/ui/non_zero_suggestions_unfixable.rs
- tests/ui/non_zero_suggestions_unfixable.stderr
Created lint based on the suggestions in #7291
----
changelog: new [`non_zero_suggestions`] lint
> Added new `non_zero_suggestions` lint

- clippy_lints/src/returns.rs
- clippy_lints/src/useless_conversion.rs
- tests/ui/needless_return.fixed
- tests/ui/needless_return.rs
- tests/ui/needless_return.stderr
Fixes #12907
changelog: Fix [`needless_return`] false negative when returned expression borrows a value.
> Fix [`needless_return`] false negative 

- clippy_lints/src/matches/single_match.rs
- tests/ui/single_match.fixed
- tests/ui/single_match.rs
- tests/ui/single_match.stderr
- tests/ui/single_match_else.fixed
- tests/ui/single_match_else.rs
- tests/ui/single_match_else.stderr
fixes #13012
changelog:[`single_match`, `single_match_else`]: fix suggestion when `match` irrefutable
> [`single_match`, `single_match_else`] fix suggestion when match irrefutable

- clippy_lints/src/ptr.rs
This fixes a possible typo in the [`ptr_arg`](https://rust-lang.github.io/rust-clippy/master/index.html#/ptr_arg) lint. I'm new to Rust, so apologies if I misunderstood the meaning of this lint.
changelog: [`ptr_arg`]: Fix typo ("size" -> "type")
> Fix possible typo in `ptr_arg` lint

- clippy_lints/src/methods/unnecessary_to_owned.rs
- tests/ui/crashes/ice-3969.rs
- tests/ui/crashes/ice-6251.rs
- tests/ui/floating_point_arithmetic_nostd.rs
- tests/ui/unsafe_removed_from_name.rs
changelog: Remove unnecessary symbols and add missing symbols
> Remove unnecessary symbols and add missing symbols

- clippy_utils/src/ty.rs
- tests/ui/uninit_vec.rs
- tests/ui/uninit_vec.stderr
This makes the fallback a bit more consistent with the other checks and rustc.
Fixes #13364. When using a generic type as the `Vec` element type like the issue title says, rustc's uninit check fails and our fallback is used, which didn't look at struct fields when it could.
> Visit struct fields recursively in uninit fallback check

- clippy_lints/src/loops/mod.rs
> Fix doc for `while_let_loop` 

- clippy_lints/src/transmute/mod.rs
Fixes #13339
changelog: [`missing_transmute_annotations `]: Expand docs, raison d'être
> Expand missing_transmute_annotations docs

- clippy_lints/src/casts/mod.rs
- clippy_lints/src/casts/ptr_cast_constness.rs
- tests/ui/ptr_cast_constness.fixed
- tests/ui/ptr_cast_constness.rs
- tests/ui/ptr_cast_constness.stderr
This implements the suggestions from #13361. It fits into the existing `ptr_cast_constness` lint, as this is a specialized version. However,
1. I have not modified the lint MSRV, so the documentation for this lint will still show that it applies only from Rust 1.72.0. This is true in the general case, but the lint for null pointers will trigger even before this version as `null()` and `null_mut()` were already present in Rust 1.0 and there is no reason not to apply this lint. I guess this is only a minor documentation issue that can be ignored.
2. I have not covered the `core::ptr::null::<T>().cast_mut()` (could be made into `core::ptr::null_mut::<T>()`) and `cotr::ptr::null_mut::<T>().cast_const()` (could be made into `core::ptr::null::<T>()`) cases. Should they be covered? If they …
> Special-case suggestions for null pointers constness cast

- clippy_lints/src/attrs/duplicated_attributes.rs
- tests/ui/duplicated_attributes.rs
As at #13355 we shoudn't  trigger `duplicated_attributes` on duplicate reasons attr
changelog: [`duplicated_attributes`]: not trigger `duplicated_attributes` on duplicate reasons
> Not trigger `duplicated_attributes` on duplicate reasons

- clippy_lints/src/needless_pass_by_value.rs
- tests/ui/crashes/needless_pass_by_value-w-late-bound.stderr
- tests/ui/needless_pass_by_value.stderr
`needless_pass_by_value` sometimes suggest marking the concerned type as `Copy`. Adding a `or` before this suggestion makes it clearer that this is not the second part of the original suggestion, but an alternative one.
Inspired by a misunderstanding in #13321 
> Make it clearer that the suggestion is an alternative one

- clippy_lints/src/doc/too_long_first_doc_paragraph.rs
- tests/ui/too_long_first_doc_paragraph.rs
- tests/ui/too_long_first_doc_paragraph.stderr
fixes #13309 
Comment form is now a variable and a new test for too_long_first_doc_paragraph was added.
> fix: Fixed incorrect comment form suggestion for too_long_first_doc_paragraph lint

- clippy_lints/src/ptr.rs
- tests/ui/ptr_arg.rs
- tests/ui/ptr_arg.stderr
This simplifies the implementation of the `ptr_arg` lint a bit and:
Fixes #13308
Fixes #10612
Currently, the lint checks if e.g. a `&String` parameter is only used in contexts where a `&str` could work. Part of it worked by looking for path exprs to that parameter in function call position specifically, looking at the callee signature and checking if that parameter type without refs is `String` (or one of a bunch of other special cases).
This simplified version removes the special casing of function calls and looking at the parameter type and instead just looks at the **adjusted type**, regardless of the expression it's in. This naturally also covers what the previous version was doing (if the expression is in a function call argument position expecting a `&str`, then it will have that …
> Look at adjusted types instead of fn signature types in `ptr_arg`

- clippy_lints/src/panic_in_result_fn.rs
- tests/ui/panic_in_result_fn.rs
Fix #13381
Makes `missing_panics_doc` act like other "panicking" lints (`unwrap_used`, `panic`, etc) in constant environments.
changelog: Ignore `missing_panics_doc` in constant environments
> [`missing_panics_doc`] Fix #13381

- .github/deploy.sh
- util/gh-pages/versions.html
- util/versions.py
Generates the page at https://rust-lang.github.io/rust-clippy/ directly rather than creating a JSON file to load
Also fixes https://github.com/rust-lang/rust-clippy/issues/13413
r? @flip1995
> Generate versions HTML directly

- CHANGELOG.md
- clippy_lints/src/declared_lints.rs
- clippy_lints/src/methods/mod.rs
- clippy_lints/src/methods/unnecessary_first_then_check.rs
- tests/ui/unnecessary_first_then_check.fixed
- tests/ui/unnecessary_first_then_check.rs
- tests/ui/unnecessary_first_then_check.stderr
Fixes #11212
Checks for `{slice/vec/Box<[]>}.first().is_some()` and suggests replacing the unnecessary `Option`-construct with a direct `{slice/...}.is_empty()`. Other lints guide constructs like `if let Some(_) = v.get(0)` into this, which end up as `!v.is_empty()`.
changelog: [`unnecessary_first_then_check`]: Initial implementation
> Initial impl of `unnecessary_first_then_check`

- tests/dogfood.rs
> Remove unused `collect_metadata` function

- clippy_lints/src/types/mod.rs
As mentioned #13387 it's not clear how to fix issue with complexity so add example for this
> Clarify example for `type_complexity`

- clippy_lints/src/if_then_some_else_none.rs
- tests/ui/if_then_some_else_none.fixed
- tests/ui/if_then_some_else_none.rs
- tests/ui/if_then_some_else_none.stderr
Fixes #13407 
#13407 works in current stable. The suggestion-generating code got trampled over in 053210424727ff279515f4b9a7f0cf6e5632acf3 :-)
changelog: [`if_then_some_else_none`]: Fix missing closure in suggestion
> Fix `if_then_some_else_none` sugg missing closure intro

- Cargo.toml
While doing some profiling I noticed that debug clippy running on the `clippy_lints` crate spends 35s out of 160s in one specific code path of `nonminimal_bool`, which seemed a bit excessive.
I've found that just enabling optimizations for quine-mc_cluskey (used by nonminimal_bool) cuts down the part that took 35s to 3s
While this doesn't really change anything for users, this helps dogfood a bit as it cuts off about half a minute of runtime (in some of my tests, at least).
Something similar was attempted in #10576, however that involved compiling everything in release mode including clippy itself, whereas this only affects a single dependency that's compiled in parallel with something that takes longer so this should hopefully not have a negative impact in any case (and changing clippy …
> Build quine-mc_cluskey with `opt-level=3` in dev builds

- clippy_lints/src/doc/empty_line_after.rs
- tests/ui/empty_line_after/outer_attribute.1.fixed
- tests/ui/empty_line_after/outer_attribute.2.fixed
- tests/ui/empty_line_after/outer_attribute.rs
- tests/ui/empty_line_after/outer_attribute.stderr
Replacing an empty span (which an empty line is) with an empty string triggers a debug assertion in rustc. This fixes the debug assertion by using contiguous spans, with the same resulting suggestion.
r? @Alexendoo 
This unblocks the sync
> Use contiguous spans for empty_line_after_* suggestion
