clippy_lints/src/regex.rs
clippy_utils/src/lib.rs

`def_path_res` previously had two jobs:
1. looking up the crates to find the path in
2. looking up path in said crates
This splits that job up into two functions, keeping `def_path_res` as an adapter between the both, to avoid repeating the first step when repeatedly looking up items in the same crate.

Split def_path_res into two parts

---

clippy_lints/src/len_zero.rs
tests/ui/comparison_to_empty.fixed
tests/ui/comparison_to_empty.rs
tests/ui/comparison_to_empty.stderr

changelog: [`comparison_to_empty`]: Also  detect comparaisons using `PartialEq` methods
Fix #13401

Lint comparison to empty slice using `PartialEq` methods

---

.github/workflows/remark.yml

Required for using Node.js 20.x in CI
* Changelog for actions/checkout@v4 https://github.com/actions/checkout/blob/main/CHANGELOG.md?rgh-link-date=2024-09-04T18%3A38%3A10Z#v400
* GitHub Blog post https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
Example warning: https://github.com/rust-lang/rust-clippy/actions/runs/11003847751
> The following actions use a deprecated Node.js version and will be forced to run on node20: actions/setup-node@v3.

Update actions/setup-node to v4

---

clippy_lints/src/ptr.rs
tests/ui/invalid_null_ptr_usage.fixed
tests/ui/invalid_null_ptr_usage.rs
tests/ui/invalid_null_ptr_usage.stderr

fixes #13445
changelog: [`invalid_null_ptr_usage`]: fix false positives for `std::ptr::slice_from_raw_parts` functions

`invalid_null_ptr_usage`: fix false positives for `std::ptr::slice_from_raw_parts` functions

---

tests/ui/as_ptr_cast_mut.rs
tests/ui/borrow_box.fixed
tests/ui/borrow_box.stderr
tests/ui/bytecount.rs
tests/ui/deref_addrof_double_trigger.rs
tests/ui/float_cmp.rs
tests/ui/float_cmp_const.rs
tests/ui/float_cmp_const.stderr
tests/ui/float_equality_without_abs.rs
tests/ui/unused_format_specs.1.fixed
tests/ui/unused_format_specs.2.fixed
tests/ui/unused_format_specs.rs
tests/ui/unused_format_specs.stderr

Add reasons for or remove some `//@no-rustfix` annotations

---

clippy_lints/src/casts/borrow_as_ptr.rs
clippy_lints/src/casts/ref_as_ptr.rs
clippy_lints/src/loops/missing_spin_loop.rs

This is a cleanup commit. It replaces hand-crafted tests by the a call to the `std_or_core()` utility function.

Use std_or_core to determine the correct prefix

---

clippy_lints/src/returns.rs
tests/ui/needless_return.fixed
tests/ui/needless_return.rs

fix: Specifying reason in expect(clippy::needless_return) no longer triggers false positive

---

clippy_lints/src/matches/mod.rs
clippy_lints/src/matches/wild_in_or_pats.rs
tests/ui/wild_in_or_pats.rs
tests/ui/wild_in_or_pats.stderr

fix(clippy_lints/matches): wildcard_in_or_patterns will no longer be triggered for types annotated with #[nonexhaustive]

---

src/driver.rs

Fixes https://github.com/rust-lang/rust-clippy/issues/12623
Fixes https://github.com/rust-lang/cargo/issues/14385
r? @flip1995

Ignore `--print`/`-Vv` requests in `clippy-driver`

---

clippy_lints/src/unused_async.rs
tests/ui/unused_async.rs
tests/ui/unused_async.stderr

Fixes the false positive mentioned in https://github.com/rust-lang/rust-clippy/issues/13466#issuecomment-2380025514.
The false negative in the OP would be nice to fix too, but I'd rather do that in a separate PR because it's much more involved
Before this change, the `unused_async` lint would check if the async fn is also used anywhere and avoid linting if so. The exception is if the async function is immediately called, because the returned future handling can be easily removed (and also if we don't have some exceptions then the lint wouldn't trigger anywhere) *or* if it's a method call receiver.
I'm not exactly sure why I implemented that special casing for method call receivers in #11200, but it doesn't make much sense in hindsight imo. Especially given that method calls are …

Remove method call receiver special casing in `unused_async` lint

---

CHANGELOG.md
book/src/lint_configuration.md
clippy_config/src/conf.rs
clippy_lints/src/declared_lints.rs
clippy_lints/src/functions/mod.rs
clippy_lints/src/functions/ref_option.rs
tests/ui/ref_option/all/clippy.toml
tests/ui/ref_option/private/clippy.toml
tests/ui/ref_option/ref_option.all.fixed
tests/ui/ref_option/ref_option.all.stderr
tests/ui/ref_option/ref_option.private.fixed
tests/ui/ref_option/ref_option.private.stderr
tests/ui/ref_option/ref_option.rs
tests/ui/ref_option/ref_option_traits.all.stderr
tests/ui/ref_option/ref_option_traits.private.stderr
tests/ui/ref_option/ref_option_traits.rs

closes #13054
```rust
// bad code
fn foo(a: &Option<T>) {}
fn bar(&self) -> &Option<T> {}
// Use instead
fn foo(a: Option<&T>) {}
fn bar(&self) -> Option<&T> {}
```
Handles argument types and return types in functions, methods, and closures with explicit types.  Honors `avoid_breaking_exported_api` parameter.
See this great [YouTube video](https://www.youtube.com/watch?v=6c7pZYP_iIE) with the in-depth explanation.
These are not blocking, and could be done in separate PRs if needed.
These cases might also be good to handle, probably in a separate PR.
```rust
fn lambdas() {
let x = |a: &Option<String>| {};
let x = |a: &Option<String>| -> &Option<String> { todo!() };
}
fn mut_ref_to_ref(a: &mut &Option<u8>) {}
```
changelog: [`ref_option`]: Suggest `Option<&T>` instead of `&Option<T>`

Suggest `Option<&T>` instead of `&Option<T>`

---

clippy_lints/src/cargo/common_metadata.rs
clippy_lints/src/functions/mod.rs
clippy_lints/src/unnested_or_patterns.rs
clippy_utils/src/ast_utils.rs
clippy_utils/src/hir_utils.rs
lintcheck/src/main.rs
src/driver.rs

Run `ref_option` (#13336) on the Clippy's own code, quiet a few hits. Per mentioned video, this may actually improve performance as well.  Switch lint to `pedantic`
----
changelog: [`ref_option`]: upgrade lint to `pedantic`

Convert `&Option<T>` to `Option<&T>`

---

clippy_lints/src/zombie_processes.rs
tests/ui/zombie_processes.rs

Fixes #13459
Small oversight. We weren't considering uses of the local in closures.

`zombie_processes`: consider `wait()` calls in nested bodies

---

clippy_lints/src/methods/mut_mutex_lock.rs
tests/ui/mut_mutex_lock.fixed
tests/ui/mut_mutex_lock.rs
tests/ui/mut_mutex_lock.stderr

When there is are multiple references where one of the references isn't mutable then this results in a false-positive for `mut_mutex_lock` as it only checks the mutability of the first reference level.
Fix this by using `peel_mid_ty_refs_is_mutable` which correctly determines whether the reference is ultimately mutable and thus whether `Mutex::get_lock()` can actually be used.
Fixes #9854
changelog: [`mut_mutex_lock`]: No longer lints if the mutex is behind multiple references and one of those references isn't mutable

Fix `mut_mutex_lock` when reference not ultimately mutable

---

clippy_config/src/msrvs.rs
clippy_lints/src/booleans.rs
clippy_lints/src/lib.rs
tests/ui/nonminimal_bool_methods.fixed
tests/ui/nonminimal_bool_methods.rs
tests/ui/nonminimal_bool_methods.stderr
tests/ui/nonminimal_bool_methods_unfixable.rs
tests/ui/nonminimal_bool_methods_unfixable.stderr

Closes #13436.
Improved based on the existing lint `nonminimal_bool`, since there is already handling of similar methods `Option::{is_some,is_none}` and `Result::{is_ok,is_err}`, and there is a lot of reusable code.
When `is_some_and` or `is_none_or` have a negation, we invert it into another method by removing the Not sign and inverting the expression in the closure.
For the case where the closure block has statements, currently no simplification is implemented. (Should we do it?)
```rust
// Currently will not simplify this
_ = !opt.is_some_and(|x| {
let complex_block = 100;
x == complex_block
});
```
changelog: [`nonminimal_bool`]: Simplify negative `Option::{is_some_and,is_none_or}`

Simplify negative `Option::{is_some_and,is_none_or}`

---

clippy_lints/src/trait_bounds.rs
clippy_utils/src/hir_utils.rs
tests/ui/trait_duplication_in_bounds.fixed
tests/ui/trait_duplication_in_bounds.rs
tests/ui/trait_duplication_in_bounds.stderr

Fixes #13476
Fixes #11067
Fixes #9915
Fixes #9626
Currently, the `trait_duplication_in_bounds` lints has a helper type for a trait reference that can be used for comparison and hashing, represented as `{trait: Res, generic_args: Vec<Res>}`. However, there are a lot of issues with this. For one, a `Res` can't represent e.g. references, slices, or lots of other types, as well as const generics and associated type equality. In those cases, the lint simply ignores them and has no way of checking if they're actually the same.
So, instead of using `Res` for this, use `SpanlessEq` and `SpanlessHash` for comparisons with the trait path for checking if there are duplicates.
However, using `SpanlessEq` as is alone lead to a false negative in the test. `std::clone::Clone` + `foo::Clone` wasn't …

Compare trait references in `trait_duplication_in_bounds` correctly

---

CHANGELOG.md
clippy_lints/src/declared_lints.rs
clippy_lints/src/regex.rs
tests/ui/regex.rs
tests/ui/regex.stderr

Closes #598.
Seems like a pretty simple one, I'm not sure if I sorted out all the lint plumbing correctly because I was adding it to the existing regex pass, but seems to work. The name is a bit jank and I'm super open to suggestions for changing it.
changelog: [`regex_creation_in_loops`]: Added lint for Regex compilation inside loops.

Implement lint for regex::Regex compilation inside a loop

---

book/src/lint_configuration.md
clippy_config/src/conf.rs
clippy_lints/src/large_stack_arrays.rs
clippy_lints/src/methods/mod.rs
tests/ui-toml/array_size_threshold/array_size_threshold.stderr
tests/ui/large_const_arrays.fixed
tests/ui/large_const_arrays.rs
tests/ui/large_stack_arrays.rs
tests/ui/large_stack_arrays.stderr

As-is this threshold is `512kb`, but as #9449 points out this is way too high for most people to consider sensible (why would you want to copy `256kb` of data around on the stack or duplicate it via `const`) and didn't get any discussion when originally added. This PR reduces it the threshold to `1kb`, which is higher than the issue says ("a few cpu words") but helps out for actual codebases.
While reducing this, I found that `large_stack_arrays` was triggering for statically promoted arrays in constants/statics, so I also fixed that up as seen in the difference to [array_size_threshold.stderr](https://github.com/rust-lang/rust-clippy/compare/master...GnomedDev:rust-clippy:reduce-large-threshold?expand=1#diff-4c2a2a855d9ff7777f1d385be0c1bede2a3fc8aaab94837cde27a35235233fc7).
Closes #9449. …

Reduce default 'large array' threshold

---

clippy_lints/src/unused_result_ok.rs

unused_result_ok: added in Clippy 1.82.0, not 1.70.0

---

clippy_lints/src/loops/infinite_loop.rs

Using `saturating_sub()` here in code which cannot fail brings a false sense of security. If for any reason a logic error was introduced and caused `self.loop_depth` to reach 0 before being decremented, using `saturating_sub(1)` would silently mask the programming error instead of panicking loudly as it should (at least in dev profile).

Style: do not defensively use `saturating_sub()`

---

clippy_lints/src/mut_key.rs
clippy_utils/src/ty.rs
tests/ui/mut_key.stderr

Fixes #10619
Just ran into this myself and I definitely agree it's not very nice to have to manually go through all the types involved to figure out why this happens and to evaluate if this is really a problem (knowing if the field of a struct is something that a hash impl relies on), so this changes the lint to emit notes for each step involved.

Show interior mutability chain in `mutable_key_type`

---

Cargo.toml
rustc_tools_util/CHANGELOG.md
rustc_tools_util/Cargo.toml
rustc_tools_util/README.md
rustc_tools_util/src/lib.rs

Fixes https://github.com/rust-lang/rust-clippy/issues/13312

rustc_tools_util: rerun when git commit changes

---

clippy_lints/src/loops/infinite_loop.rs
tests/ui/infinite_loops.rs
tests/ui/infinite_loops.stderr

changelog: [`infinite_loop`]: detect a `continue` targeting an outer loop
Fix #13511

`infinite_loop`: continuing an outer loop leaves the inner loop

---

clippy_lints/src/returns.rs
clippy_utils/src/check_proc_macro.rs
tests/ui/dbg_macro/dbg_macro.fixed
tests/ui/dbg_macro/dbg_macro.rs
tests/ui/needless_return.fixed
tests/ui/needless_return.rs
tests/ui/needless_return.stderr

Fixes #13458
Fixes #13457
Fixes #13467
Fixes #13479
Fixes #13481
Fixes #13526
Fixes #13486
The fix is unfortunately a little more convoluted than just simply adding a `is_from_proc_macro`. That check *does*  fix the issue, however it also introduces a bunch of false negatives in the tests, specifically when the returned expression is in a different syntax context, e.g. `return format!(..)`.
The proc macro check builds up a start and end pattern based on the HIR nodes and compares it to a snippet of the span, however that would currently fail for `return format!(..)` because we would have the patterns `("return", <something inside of the format macro>)`, which doesn't compare equal. So we now return an empty string pattern for when it's in a different syntax context.
"Hide whitespace" …

Don't warn on proc macro generated code in `needless_return`

---

clippy_lints/src/implicit_saturating_sub.rs
tests/ui/implicit_saturating_sub.fixed
tests/ui/implicit_saturating_sub.rs
tests/ui/implicit_saturating_sub.stderr
tests/ui/manual_arithmetic_check.fixed
tests/ui/manual_arithmetic_check.stderr

Fixes #13524
changelog: [`implicit_saturating_sub`]: Fix span issue on else blocks

Fix span issue on `implicit_saturating_sub`

---

clippy_lints/src/large_stack_arrays.rs
tests/ui/large_stack_arrays.rs
tests/ui/large_stack_arrays.stderr

Fixes #13529.
r? @flip1995
changelog: [`large_stack_arrays`]: No longer triggers in static/const context when using nested items

Fix large_stack_arrays triggering when nesting const items

---

clippy_lints/src/methods/manual_c_str_literals.rs
tests/ui/manual_c_str_literals.edition2021.fixed
tests/ui/manual_c_str_literals.edition2021.stderr
tests/ui/manual_c_str_literals.rs

Only emit `manual_c_str_literals` in >= Edition 2021

---

.github/deploy.sh
.gitignore
Cargo.toml
clippy_dev/src/serve.rs
rinja.toml
tests/compile-test.rs
util/gh-pages/index_template.html
util/gh-pages/script.js
util/gh-pages/style.css
util/gh-pages/theme.js

This PR has multiple goals:
* Make lints page to work without needing a web server by removing the json file.
* Prepare the field to also make the page work with JS (not done in this PR but should be straightforward).
* Remove angular dependency.
r? @Alexendoo 
changelog: make lint page work without web server

Rewrite lints page

---

clippy_lints/src/byte_char_slices.rs
clippy_lints/src/methods/unnecessary_first_then_check.rs

I don't really see situations where this isn't Applicable that aren't weird edge cases where the lint should be disabled.

Mark unnecessary_first_then_check and byte_char_slices as Applicable

---

CHANGELOG.md
clippy_lints/src/declared_lints.rs
clippy_lints/src/lib.rs
clippy_lints/src/manual_ignore_case_cmp.rs
tests/ui/manual_ignore_case_cmp.fixed
tests/ui/manual_ignore_case_cmp.rs
tests/ui/manual_ignore_case_cmp.stderr

```rust
// bad
fn compare(a: &str, b: &str) -> bool {
a.to_ascii_lowercase() == b.to_ascii_lowercase()
|| a.to_ascii_lowercase() == "abc"
}
// good
fn compare(a: &str, b: &str) -> bool {
a.eq_ignore_ascii_case(b)
|| a.eq_ignore_ascii_case("abc")
}
```
changelog: New lint: [`manual_ignore_case_cmp`] `perf`
[#13334](https://github.com/rust-lang/rust-clippy/pull/13334)
Closes #13204

Add manual_ignore_cast_cmp lint

---

clippy_config/src/msrvs.rs
clippy_lints/src/lib.rs
clippy_lints/src/manual_float_methods.rs
tests/ui/manual_float_methods.rs
tests/ui/manual_float_methods.stderr

As mentioned at #13508 `const_float_classify` has been stabilized recently in https://github.com/rust-lang/rust/pull/130157 and can be cleanup
Close #13508
changelog: [none]

Cleanup `const_float_classify`

---

clippy_lints/src/implicit_saturating_sub.rs
tests/ui/implicit_saturating_sub.fixed
tests/ui/implicit_saturating_sub.rs
tests/ui/implicit_saturating_sub.stderr
tests/ui/manual_arithmetic_check.fixed
tests/ui/manual_arithmetic_check.stderr

Related to #13533, such and obvious mistake got pass my watch, quite embarassing :/
Revert #13533 and implement a more robust solution.
Revert "Fix span issue on `implicit_saturating_sub`
This reverts commit 140a1275f24ab951ffb0daee568385049de153d5.
changelog: [`lint_name`]: Fix suggestion for `if {} else if {} else {}` cases
r? @y21

[`implicit_saturating_sub`] Fix suggestion with a less volatile approach

---

clippy_lints/src/manual_slice_size_calculation.rs
tests/ui/manual_slice_size_calculation.fixed
tests/ui/manual_slice_size_calculation.rs
tests/ui/manual_slice_size_calculation.stderr

When a slice is ref more than once, current suggestion given by `manual_slice_size_calculation` is wrong. For example:
```rs
let s: &[i32] = &[1, 2][..];
let ss: &&[i32] = &s;  // <-----
let _ = size_of::<i32>() * ss.len();
```
clippy now suggests:
```patch
- let _ = size_of::<i32>() * ss.len();
+ let _ = size_of_val(ss);
```
However, this can result in calculating the size of `&[i32]`, instead of `[i32]` (this wrong suggestion also leads to `size_of_ref` warning: https://rust-lang.github.io/rust-clippy/master/index.html#/size_of_ref )
Now I am sending this PR to fix this bug, so that clippy will suggest (some deref added):
```patch
- let _ = size_of::<i32>() * ss.len();
+ let _ = size_of_val(*ss);
```
As I am not familiar with current clippy code-base, please correct me if I am not doing …

Fix lint `manual_slice_size_calculation` when a slice is ref more than once

---

clippy_lints/src/item_name_repetitions.rs
clippy_lints/src/literal_representation.rs
clippy_lints/src/macro_use.rs
clippy_lints/src/vec.rs

Rational:
- Too pedantic IMO, I use `#[warn(pedantic)]` in my personal projects, but then always allow this lint. The fact that we had a few `#[expect(clippy::module_name_repetitions)]` also underlines this point IMO
- STD doesn't do this either. Examples:
- std::vec::Vec
- std::collections::vec_deque::VecDequeue
- #7666 commonly ignored
---
changelog: Move [`module_name_repetitions`] to `restriction` (from `pedantic`)
[#13541](https://github.com/rust-lang/rust-clippy/pull/13541)

Move `clippy::module_name_repetitions` to `restriction` (from `pedantic`)

---

clippy_lints/src/doc/mod.rs

See: https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/too_long_first_doc_paragraph.20to.20nursery.3F/near/476448239
I'll update the changelog as well.

Move `too_long_first_doc_paragraph` to `nursery`

---

clippy_lints/src/manual_is_power_of_two.rs

Fixes #13547.
The value being checked might be a bit flag, suggesting `is_power_of_two` for it would make the code unreadable.
changelog: [`manual_is_power_of_two`]: Change the category to `pedantic`

Change the category of `manual_is_power_of_two` to `pedantic`

---

clippy_lints/src/methods/mod.rs
util/gh-pages/index_template.html

- In [the page describing the lints](https://rust-lang.github.io/rust-clippy/master/index.html), the View Source links are incorrect. This PR removes the extra segment causing them to fail.
- Example before: https://github.com/rust-lang/rust-clippy/blob/master/clippy_lints/clippy_lints/src/absolute_paths.rs#L13
- Example after: https://github.com/rust-lang/rust-clippy/blob/master/clippy_lints/src/absolute_paths.rs#L13
- I think this was introduced in #13269.
- I've only checked a few of the lints with the new template, but from what I can tell the metadata is generated in the same way for all of them. The `id_location` contains the full path of the lint declaration in the repository, which is why `clippy_lints` was repeated in the URL.
- Separately, fixing a typo in the explanation of …

Documentation fixes

---

CHANGELOG.md
clippy_lints/src/pathbuf_init_then_push.rs

```
Roses are red,
EuroRust in Austria,
RustConf in Canada.
```
---
---

Changelog for Clippy 1.82 :airplane: 

---

tests/compile-test.rs
util/gh-pages/index_template.html
util/gh-pages/script.js
util/gh-pages/style.css

Fixes #13536.
This is the follow-up of https://github.com/rust-lang/rust-clippy/pull/13269.
This PR makes it possible to expand/collapse lints (individually) without JS. To achieve this result, there are two ways:
1. Use `details` and `summary` tags. Problem with this approach is that the web browser search may open the `details` tags automatically if content matching it is inside. From a previous discussion with @Alexendoo, it seems to not be a desired behaviour.
2. Use a little trick where you use a `label` and a checkbox where the checkbox is in fact hidden. Then it's just a matter of CSS.
r? @Alexendoo 
changelog: Allow to go through clippy lints page without JS

Allow to go through clippy lints page without javascript

---

clippy_lints/src/manual_bits.rs
tests/ui/manual_bits.fixed
tests/ui/manual_bits.rs

Closes #13563.
changelog: [`manual_bits`] No longer lints in macro-generated code

Stop linting manual_bits in any macro invoke

---

clippy_lints/src/functions/mod.rs

Close #13566
As mentioned at #13566 `ref_option` [was merged](https://github.com/rust-lang/rust-clippy/pull/13336) after 1.82.0 so it wasn't include in this version

Fix version for `ref_option`

---

clippy_lints/src/from_over_into.rs
clippy_lints/src/semicolon_block.rs
clippy_utils/src/diagnostics.rs
clippy_utils/src/lib.rs
tests/ui/semicolon_outside_block.fixed
tests/ui/semicolon_outside_block.rs
tests/ui/semicolon_outside_block.stderr

rustc has debug assertions [^1] [^2] that check that a substitution doesn't have an empty suggestion string and an empty span at the same time, as well as that spans in multipart suggestions don't overlap.
However, since we link to the rustc-dev distributed compiler, these debug assertions are always disabled and so we never actually run them.
This leads to the problem that the debug ICE is not necessarily caught in the PR and only triggered in the rust repo sync, and in one of the last syncs this was a blocker and delayed the sync by several weeks because the fix was not obvious.
So this PR essentially copies the checks over and runs them in clippy debug builds as well, so that we can catch these errors in PRs directly.
-----
As for the second commit, this also *did* cause an ICE in a …

Add debug assertions for empty replacements and overlapping spans

---

util/gh-pages/index_template.html

the typo was (seemingly) ignored by browsers, so the change isn't visible to users

docs: remove stray comma

---

util/gh-pages/index_template.html
util/gh-pages/script.js

As spotted by @flip1995, the anchor button is currently not working. Problem was the JS that was preventing the web browser from adding the hash at the end of the URL.
For the second bug fixed, the JS was stripping two characters instead of just stripping the `#` at the beginning.
changelog: Fix clippy page lint anchor (generation and filtering)
r? @flip1995

Fix not working lint anchor (generation and filtering)

---

clippy_lints/src/methods/is_empty.rs
tests/ui/const_is_empty.rs
tests/ui/const_is_empty.stderr

Close #13106
Considered case was described [here](https://github.com/rust-lang/rust-clippy/pull/13114#issuecomment-2266629991)
changelog: [`const_is_empty`]: skip const_is_empty for inline const assertions

Don't trigger `const_is_empty` for inline const assertions

---

clippy_lints/src/doc/mod.rs

The documentation for too_long_first_doc_paragraph incorrectly says "line" where it should say "paragraph".
Fix a minor typo: doscstring -> docstring.
Also do a few tiny edits to attempt to make the wording slightly shorter and clearer.
changelog: [`too_long_first_doc_paragraph`]: Edit documentation

docs: Fix too_long_first_doc_paragraph: line -> paragraph

---

clippy_config/src/conf.rs

Fixes #13568
Follow up to #13359, I didn't catch that it swapped the `strip_prefix` out for a `trim` but they aren't interchangeable here

Fix indentation of website code snippets

---

clippy_lints/src/unused_io_amount.rs
tests/ui/unused_io_amount.rs

Closes #4836
changelog: [`unused_io_amount`] No longer lints inside `io::Read`/`io::Write`, and async variants.

Stop linting unused_io_amount in io traits

---

clippy_lints/src/borrow_deref_ref.rs
tests/ui/borrow_deref_ref.fixed
tests/ui/borrow_deref_ref.rs

changelog: [`borrow_deref_ref`]: do not trigger on `&raw` references
Fix #13584

borrow_deref_ref: do not trigger on `&raw` references

---

tests/ui-toml/private-doc-errors/doc_lints.rs

Add test case for `missing_errors_doc` at tests with option `check-private-item=true` to proof that rust-lang/rust-clippy#13391 is not an issue anymore
Closes: rust-lang/rust-clippy#13391

Add test case for `missing_errors_doc` at tests with option `check-private-item=true`

---

clippy_lints/src/methods/unnecessary_filter_map.rs
tests/ui/unnecessary_filter_map.rs
tests/ui/unnecessary_filter_map.stderr
tests/ui/unnecessary_find_map.rs
tests/ui/unnecessary_find_map.stderr

fixes https://github.com/rust-lang/rust-clippy/issues/12556
(Fixed version of https://github.com/rust-lang/rust-clippy/pull/12766)
changelog: [unnecessary_filter_map]: filter map improvements

fix: remove unnecessary filter_map usages

---

clippy_config/src/lib.rs
clippy_config/src/msrvs.rs

Currently, `Msrv` is cloned around a lot in order to handle the `#[clippy::msrv]` attribute. This attribute, however, means `RustcVersion` will be heap allocated if there is only one source of an msrv (eg: `rust-version` in `Cargo.toml`).
This PR optimizes for said case, while keeping the external interface the same by swapping the internal representation to `SmallVec<[RustcVersion; 2]>`.

Optimise Msrv for common one item case

---

clippy_lints/src/booleans.rs
tests/ui/nonminimal_bool.stderr
tests/ui/nonminimal_bool_methods.fixed
tests/ui/nonminimal_bool_methods.rs
tests/ui/nonminimal_bool_methods.stderr

fixes #12761 
The expression `!(a >= b) as i32 == c` got simplified to `a < b as i32 == c`, but this is a syntax error.
The result we want is `(a < b) as i32 == c`.
This is fixed by adding a parenthesis to the suggestion given in `check_simplify_not` when the boolean expression is casted.
changelog: [`nonminimal_bool`]: fix incorrect suggestion for `!(a >= b) as i32 == c`

fix incorrect suggestion for `!(a >= b) as i32 == c`

---

.github/workflows/deploy.yml

fix: usage of `a deprecated Node.js version`

---

clippy_lints/src/large_const_arrays.rs
tests/ui/large_const_arrays.fixed
tests/ui/large_const_arrays.rs
tests/ui/large_const_arrays.stderr

changelog: [`large_const_arrays`]: Lint now fires when the length is determined by an expression

Fire large_const_arrays for computed array lengths

---

CHANGELOG.md
README.md
book/src/README.md
clippy_lints/src/declared_lints.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/needless_as_bytes.rs
tests/ui/needless_as_bytes.fixed
tests/ui/needless_as_bytes.rs
tests/ui/needless_as_bytes.stderr

changelog: [`needless_as_bytes`]: new lint
Fix #13434

New lint `needless_as_bytes`

---

CHANGELOG.md
clippy_lints/src/casts/unnecessary_cast.rs
clippy_lints/src/declared_lints.rs
clippy_lints/src/methods/map_all_any_identity.rs
clippy_lints/src/methods/mod.rs
tests/ui/map_all_any_identity.fixed
tests/ui/map_all_any_identity.rs
tests/ui/map_all_any_identity.stderr

This lint has been inspired by code encountered in Clippy itself (see the first commit).
changelog: [`map_all_any_identity`]: new lint

New lint `map_all_any_identity`

---

CHANGELOG.md
book/src/lint_configuration.md
clippy_config/src/conf.rs
clippy_config/src/msrvs.rs
clippy_lints/src/declared_lints.rs
clippy_lints/src/matches/single_match.rs
clippy_lints/src/methods/map_with_unused_argument_over_ranges.rs
clippy_lints/src/methods/mod.rs
tests/ui/map_with_unused_argument_over_ranges.fixed
tests/ui/map_with_unused_argument_over_ranges.rs
tests/ui/map_with_unused_argument_over_ranges.stderr
tests/ui/repeat_vec_with_capacity.fixed
tests/ui/repeat_vec_with_capacity.rs
tests/ui/repeat_vec_with_capacity.stderr
tests/ui/suspicious_map.rs
tests/ui/suspicious_map.stderr

This lint checks for code that looks like
```rust
let something : Vec<_> = (0..100).map(|_| {
1 + 2 + 3
}).collect();
```
which is more clear as
```rust
let something : Vec<_> = std::iter::repeat_with(|| {
1 + 2 + 3
}).take(100).collect();
```
That is, a map over a range which does nothing with the parameter passed to it is simply a function (or closure) being called `n` times and could be more semantically expressed using `take`.
changelog: new lint: [`trivial_map_over_range`] `restriction`

Add new `trivial_map_over_range` lint

---

clippy_utils/src/check_proc_macro.rs
tests/ui/allow_attributes.fixed
tests/ui/allow_attributes.rs
tests/ui/allow_attributes.stderr
tests/ui/auxiliary/proc_macro_derive.rs

fixes #13349 
The issue here was that the start pattern being matched on the original source code was not specific enough. When using derive macros or in the issue case a `#[repr(C)]` the `#` would match the start pattern meaning that the expanded macro appeared to be unchanged and clippy would lint it.
The change I made was to make the matching more specific by matching `#[ident` at the start. We still need the second string to match just the ident on its own because of things like `#[cfg_attr(panic = "unwind", allow(unused))]`.
I also noticed some typos with start and end, these code paths weren't being reached so this doesn't fix anything.
changelog: FP: [`allow_attributes`]: don't trigger when expanded from some macros

Fix allow_attributes when expanded from some macros

---

clippy_lints/src/large_include_file.rs
tests/ui-toml/large_include_file/large_include_file.rs
tests/ui-toml/large_include_file/large_include_file.stderr

I realized randomly while working on another lint that `large_include_file` was not emitted on attributes. This PR fixes that.
changelog: Extend `large_include_file` lint to also work on attributes

Extend `large_include_file` lint to also work on attributes

---

clippy_lints/src/functions/ref_option.rs

`gen` will be a reserved word in Rust 2024.

Do not use `gen` as a variable name

---

clippy_lints/src/iter_without_into_iter.rs
tests/ui/iter_without_into_iter.stderr

Reorder the suggested code for the `IntoIterator` to match the ordering of the trait declaration:
```rust
impl IntoIterator for ... {
type Item = ...;
type IntoIter = ...;
```

Cleanup code suggestion for `into_iter_without_iter`

---

clippy_utils/src/consts.rs

When I initially found this, I was wondering why clippy wasn't just using miri, but after some discussion with some rustc folks let's document why.

Explain why clippy's HIR const eval exists

---

clippy_lints/src/loops/infinite_loop.rs
tests/ui/infinite_loops.rs
tests/ui/infinite_loops.stderr

closes: #12338
I intend to fix this in #12421 but got distracted by some other problems in the same lint, delaying the process of closing the actual issue. So here's a separated PR that only focus on the issue and nothing else.
---
changelog: [`infinite_loops`]: fix suggestion error on async functions/closures

[`infinite_loops`]: fix incorrect suggestions on async functions/closures

---

util/gh-pages/index_template.html
util/gh-pages/noscript.css
util/gh-pages/style.css
util/gh-pages/theme.js

There is no point in displaying the settings menu and the filters if JS is disabled. So in this case, this PR simply hides it:
For the theme handling though, I need to send a fix to mdBook first. But once done, it'll look as expected (dark if system is in dark mode).
changelog: Improve clippy lints page display when JS is disabled.
r? @Alexendoo

Improve display of clippy lints page when JS is disabled

---

clippy_lints/src/missing_doc.rs
tests/ui/missing_doc.rs
tests/ui/missing_doc.stderr

With this change we no longer require doc comments for `const _: ()` items as well as nested items in functions or other bodies. In both of those cases, rustdoc generates no documentation even with `--document-private-items`.
Fixes #13427 (first commit)
Fixes #13298 (second commit)
cc https://github.com/rust-lang/rust-clippy/issues/5736#issuecomment-668524296
changelog: [`missing_docs_in_private_items`]: avoid linting in more cases where rustdoc generates no documentation

Don't lint unnamed consts and nested items within functions in `missing_docs_in_private_items`

---

clippy_utils/src/lib.rs

In Rust 2024, by default lifetimes will be captured which does not reflect the reality since we return an iterator of `DefId` which do not capture the input parameters.

Return iterator must not capture lifetimes in Rust 2024

---

clippy_lints/src/no_mangle_with_rust_abi.rs
tests/ui/no_mangle_with_rust_abi_2021.rs
tests/ui/no_mangle_with_rust_abi_2021.stderr

Tests without unsafe must not run in edition 2024. Also, error messages have been modified to include the full attribute, so that a use of `#[unsafe(no_mangle)]` does not produce an error message containing `#[no_mangle]`.
changelog: [`no_mangle_attribute`]: handle `#[unsafe(no_mangle)]` as well

no_mangle attribute requires unsafe in Rust 2024

---

clippy_lints/src/needless_continue.rs
tests/ui/needless_continue.rs
tests/ui/needless_continue.stderr

changelog: [`needless_continue`]: check labels before warning about `continue` as the last statement in a loop body
Fix #13641

needless_continue: check labels consistency before warning

---

clippy_lints/src/copies.rs
clippy_lints/src/derive.rs
clippy_lints/src/from_over_into.rs
clippy_lints/src/loops/while_immutable_condition.rs
clippy_lints/src/loops/while_let_on_iterator.rs
clippy_lints/src/matches/match_str_case_mismatch.rs
clippy_utils/src/lib.rs
clippy_utils/src/usage.rs
clippy_utils/src/visitors.rs

I noticed that a bunch of visitors had a `poison` or `success` field, when they could just be returning `ControlFlow`.

Swap Visitors to early exit, instead of storing poison flag

---

clippy_lints/src/no_mangle_with_rust_abi.rs
tests/ui/no_mangle_with_rust_abi.rs
tests/ui/no_mangle_with_rust_abi.stderr

Fix #13656
changelog: [`no_mangle_with_rust_abi`]: properly position the suggested ABI

no_mangle_with_rust_abi: properly position the suggested ABI

---

.github/workflows/clippy_dev.yml
.github/workflows/clippy_mq.yml
.github/workflows/clippy_pr.yml
.github/workflows/remark.yml
CONTRIBUTING.md
book/src/development/README.md

Context: https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/Reducing.20the.20amount.20of.20repos.20that.20use.20bors.2Fhomu
This should be merged with cooperation from an infra-admin.
Opening as a draft, because the CI on this repo is.. interesting :) So I want to make sure that the changes make sense. I renamed `clippy_bors.yml` to `clippy.yml` and `clippy.yml` to `clippy_pr.yml`, which makes the diff a bit.. tricky.
changelog: Move Clippy from bors to merge queues

Switch CI from bors to merge queue

---

clippy_lints/src/disallowed_macros.rs
clippy_lints/src/lib.rs
clippy_lints/src/utils/attr_collector.rs
clippy_lints/src/utils/mod.rs
tests/ui-toml/disallowed_macros/disallowed_macros.stderr

filed here instead of rust-lang/rust (old: https://github.com/rust-lang/rust/pull/132645)

collect attribute spans early for disallowed macros

---

clippy_lints/src/operators/identity_op.rs
tests/ui/identity_op.fixed
tests/ui/identity_op.rs
tests/ui/identity_op.stderr

The `identity_op` lint was suggesting code fixes that resulted in incorrect or broken code, due to missing parenthesis in the fix that changed the semantics of the code.
For a binary expression, `left op right`, if the `left` was redundant, it would check if the right side needed parenthesis, but if the `right` was redundant, it would just assume that the left side did not need parenthesis.
This can result in rustfix generating broken code and failing, or generating code that has different behavior than before the fix. e.g. `-(x + y + 0)` would turn into `-x + y`, changing the behavior, and `1u64 + (x + y + 0i32) as u64` where `x: i32` and `y: i32` would turn into `1u64 + x + y as u64`, creating an error where `x` cannot be added to the other values, as it was never cast to `u64`.
This …

fix: `identity_op` suggestions use correct parenthesis

---

clippy_lints/src/large_include_file.rs
tests/ui-toml/large_include_file/large_include_file.rs

Fixes #13670.
Bug was that I forgot to add the comparison with the included file content length...
changelog: Fix `large_include_file` lint being triggered all the time by doc comments

Fix `large_include_file` lint being triggered all the time by doc comments

---

clippy_lints/src/question_mark.rs
tests/ui/question_mark.fixed
tests/ui/question_mark.rs
tests/ui/question_mark.stderr

Closes #10.
changelog: [`question_mark`]: Now lints for match-based manual try

Add match-based manual try to clippy::question_mark

---

book/src/SUMMARY.md
book/src/attribs.md
clippy_utils/src/attrs.rs
clippy_utils/src/macros.rs
tests/ui/format_args_unfixable.rs
tests/ui/format_args_unfixable.stderr
tests/ui/uninlined_format_args.fixed
tests/ui/uninlined_format_args.rs
tests/ui/uninlined_format_args.stderr
tests/ui/unused_format_specs.1.fixed
tests/ui/unused_format_specs.2.fixed
tests/ui/unused_format_specs.rs
tests/ui/unused_format_specs.stderr

Add support for `#[clippy::format_args]` attribute that can be attached to any macro to indicate that it functions the same as the built-in format macros like `format!`, `println!` and `write!`
---
changelog: Enhancement: [`format_in_format_args`], [`recursive_format_impl`], [`to_string_in_format_args`], [`uninlined_format_args`], [`unused_format_specs`]: Recognizes `#[clippy::format_args]` to support custom 3rs party format macros.

Support user format-like macros

---

clippy_lints/src/matches/redundant_guards.rs
tests/ui/redundant_guards.fixed
tests/ui/redundant_guards.rs
tests/ui/redundant_guards.stderr

Two changes to `redundant_guards`:
- Lint float literals. We used to do that before but that was changed in #11305 because at the time there was a future compat warning and it was planned to make pattern matching floats a hard error.
In rust-lang/rust#116284 it was decided to actually remove the lint and only make matching `NAN` specifically a hard error. The `NAN` part isn't relevant/important here because this PR only changes what literals are warned and `f64::NAN` isn't a literal, but I've added a test anyway to make sure we continue to not lint there.
- Don't lint CStr literals because that can't be a pattern right now (fixes #13681)

Don't lint CStr literals, do lint float literals in `redundant_guards`

---

clippy_lints/src/if_let_mutex.rs
tests/ui/if_let_mutex.edition2021.stderr
tests/ui/if_let_mutex.rs

Close #13679
changelog: [`if_let_mutex`]: disable lint from Edition 2024 since [stabilized if_let_rescope ](https://github.com/rust-lang/rust/issues/131154)

Do not trigger `if_let_mutex` starting from Edition 2024

---

clippy_lints/src/doc/mod.rs

changelog: [`missing_safety_doc`]: accept uppercase "SAFETY"
In [Oxc](https://github.com/oxc-project/oxc)'s codebase, we try to draw attention as clearly as possible to the safety constraints of unsafe code by including an uppercase `# SAFETY` doc comment.
Clippy's `missing_safety_doc` lint does not recognise "SAFETY" in upper case, so we also need to include `#[expect(clippy::missing_safety_doc)]` on every unsafe function, to avoid a false positive. Unfortunately this defeats the purpose of the lint, as if someone later removes the safety docs, the lint rule does not trigger.
I don't know how common this style of documenting unsafe functions is, but I don't imagine also supporting `# SAFETY` would disturb other users who prefer `# Safety`.

`missing_safety_doc` accept uppercase "SAFETY"

---

tests/ui/missing_const_for_fn/could_be_const.fixed
tests/ui/missing_const_for_fn/could_be_const.rs
tests/ui/missing_const_for_fn/could_be_const.stderr

On arm64 I get
```
error[E0570]: `"vectorcall"` is not a supported ABI for the current target
```
We don't seem to be doing any ABI specific handling so it seems fine to just remove this one since there are other tests

Remove extern vectorcall tests

---

clippy_lints/src/lifetimes.rs
tests/ui/extra_unused_lifetimes.rs

Fixes #13578
r? @Alexendoo
changelog: don't consider lifetimes in bounded types unused (fix `extra_unused_lifetimes` FP #13578)

Don't consider lifetimes in bounded types unused (fix `extra_unused_lifetimes` FP)

---

clippy_lints/src/methods/unnecessary_map_or.rs
tests/ui/unnecessary_map_or.stderr

Suggested by, and closes #13704.
changelog: [`unnecessary_map_or`]: use a clearer lint message

Use a better message for unnecessary_map_or lint

---

CHANGELOG.md
README.md
book/src/README.md
clippy_config/src/conf.rs
clippy_lints/src/declared_lints.rs
clippy_lints/src/doc/include_in_doc_without_cfg.rs
clippy_lints/src/doc/mod.rs
tests/ui/doc/doc_include_without_cfg.fixed
tests/ui/doc/doc_include_without_cfg.rs
tests/ui/doc/doc_include_without_cfg.stderr
tests/ui/missing_doc_crate.rs

It's becoming more and more common to see people including markdown files in their code using `doc = include_str!("...")`, which is great. However, often there is no condition on this include, which is not great because it slows down compilation and might trigger recompilation if these files are updated.
This lint aims at fixing this situation.
changelog: Add new lint `doc_include_without_cfg`

Add new lint `doc_include_without_cfg`

---

clippy_lints/src/doc/mod.rs

For example, we definitely wouldn't want to do this in libcore.

Add note about caveat for `cfg(doc)`

---

book/src/lint_configuration.md
clippy_config/src/conf.rs

Remove the documentation incorrectly saying there is no default, followed by the default.
changelog: [`trivially_copy_pass_by_ref`]: Removed incorrect documentation suggesting the default has no limit.

Remove incorrect "default there is no limit" documentation from trivial_copy_size_limit

---

clippy_utils/src/hir_utils.rs
tests/ui/trait_duplication_in_bounds.fixed
tests/ui/trait_duplication_in_bounds.rs

Fix #13706 
changelog: [`trait_duplication_in_bounds`]: fix ICE on duplicate type or constant bound

Prevent ICE in case of a bound constraint on generic argument

---

clippy_lints/src/methods/mod.rs

unnecessary_map_or: fix version for lint addition

---

clippy_lints/src/derivable_impls.rs
tests/ui/derivable_impls.fixed
tests/ui/derivable_impls.stderr

This should address  #13099 for the `derivable_impls` test. As I've not contributed to clippy before, I'd like to make sure i'm on the right track before doing more :) 
changelog: [`derivable_impls`]: Use multipart_suggestion to aggregate feedback

Fix: Use multipart_suggestion for derivable_impls

---

clippy_utils/src/hir_utils.rs
tests/ui/trait_duplication_in_bounds.fixed
tests/ui/trait_duplication_in_bounds.rs
tests/ui/trait_duplication_in_bounds.stderr

changelog: [`trait_duplication_in_bounds`]: trigger on duplicate const associated constraint as well
~~The first commit is part of #13722 which must be merged first.~~

Handle repetition of associated constant constraint as well

---

clippy_lints/src/operators/bit_mask.rs

`clap-3.1.6` was not compiling on the rustc-perf benchmarks because of this lint. Also, the user could not allow the lint on the macro itself because it was checking Exprs, not whatever the input of `bitflags!` is.
```
error: &-masking with zero
--> src/build/arg_settings.rs:197:1
|
(#[allow] here) 
197 | / bitflags! {
198 | |     struct Flags: u32 {
199 | |         const REQUIRED         ...
200 | |         const MULTIPLE_OCC     ...
...   |
226 | |     }
227 | | }
| |_^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#bad_bit_mask
= note: this error originates in the macro `__impl_bitflags` which comes from the expansion of the macro `bitflags` (in Nightly builds, run with -Z macro-backtrace for more info)
```
changelog: …

[`bad_bit_mask`] Fix FP on proc macros

---

CHANGELOG.md
clippy_lints/src/manual_div_ceil.rs
clippy_lints/src/manual_is_power_of_two.rs
clippy_lints/src/misc.rs
clippy_lints/src/non_zero_suggestions.rs
clippy_lints/src/zombie_processes.rs

This is in honor of `@bors` who is no longer used in this repo. I've been saving this poem for a special PR, but it just seems fitting to use it now:
Bors the bot,
Handsome and strong!
Will you go with me,
To prom?
---
---

Changelog for Clippy 1.83 🤖

---

book/src/development/infrastructure/backport.md
book/src/development/infrastructure/release.md
book/src/development/infrastructure/sync.md

This updates the documentation after #13694. It is not based on that PR chain and can be merged independently, but should be merged after that PR.
This is partly pulled from #12762, but removing the Josh parts.
This includes instructions on how to publish `clippy_utils`.
Closes https://github.com/rust-lang/rust-clippy/issues/13556 (yes, this is the final PR :slightly_smiling_face:)
r? @blyxyas 
changelog: `clippy_utils` is now published to crates.io

Update backport, release and sync documentation

---

clippy_lints/src/shadow.rs
tests/ui/shadow.rs
tests/ui/shadow.stderr

Fixes https://github.com/rust-lang/rust-clippy/issues/10780
We correctly no longer give a warning when a closure is passed to a method, where one of the arguments to that method uses the variable which would be shadowed by an argument to that closure.
Uses is defined loosely as any expression used in the calling expression mentions the shadowee binding (except for the closure itself):
```rust
#![deny(clippy::shadow_unrelated)]
let x = Some(1);
let y = x.map(|x| x + 1);
```
will now succeed.
See https://github.com/linebender/xilem/pull/745 - without this change, all of the `expect(shadow_unrelated)` in the repository are met; with it, none of them are.
changelog: [`shadow_unrelated`]: Don't treat closures arguments as unrelated when the calling function uses them

Fix `shadow_unrelated`'s behaviour with closures

---

clippy_lints/src/indexing_slicing.rs

Mention `string_slice` in `indexing_slicing` documentation

---

clippy_lints/src/matches/needless_match.rs
tests/ui/needless_match.fixed
tests/ui/needless_match.rs
tests/ui/needless_match.stderr

Closes #13574
Make sure that `needless_match` doesn't simplify:
```
if let Some(_) = a() {
// ..
} else let Some(_) = b() {
// ..
}
```
to:
```
a()
```
changelog: [`needless_match`]: Fix false-positive on if lets

Fix needless_match FP on if-lets

---

clippy_lints/src/derive.rs

I'm assuming the duplicated `env` was a typo. Apologies if I've made a mistake. (cc: @lcnr)
---

`typing_env_env_for_derived_eq` -> `typing_env_for_derived_eq`

---

clippy_lints/src/methods/mod.rs
clippy_lints/src/useless_conversion.rs
tests/ui/useless_conversion.fixed
tests/ui/useless_conversion.rs
tests/ui/useless_conversion.stderr

The new cases are the application of `Into::into` or `From::from` through the following functions with no effect:
- `Option::map()`
- `Result::map()` and `Result::map_err()`
- `ControlFlow::map_break()` and `ControlFlow::map_err()`
- `Iterator::map()`
changelog: [`useless_conversion`]: detect useless calls to `Into::into` and `From::from` application through `map*` methods

Add more cases to the `useless_conversion` lint

---

CHANGELOG.md
clippy_lints/src/declared_lints.rs
clippy_lints/src/doc/mod.rs
tests/ui/doc/doc_nested_refdef_blockquote.fixed
tests/ui/doc/doc_nested_refdef_blockquote.rs
tests/ui/doc/doc_nested_refdef_blockquote.stderr
tests/ui/doc/doc_nested_refdef_list_item.fixed
tests/ui/doc/doc_nested_refdef_list_item.rs
tests/ui/doc/doc_nested_refdef_list_item.stderr

https://github.com/rust-lang/rust/issues/133150
This is more likely to be intended as an intra-doc link than it is to be intended as a refdef. If a refdef is intended, it does not need to be nested within a list item.
```markdown
- [`LONG_INTRA_DOC_LINK`]: this
looks like an intra-doc link,
but is actually a refdef.
The first line will seem to
disappear when rendered as HTML.
```
> - [`LONG_INTRA_DOC_LINK`]: this
>   looks like an intra-doc link,
>   but is actually a refdef.
>   The first line will seem to
>   disappear when rendered as HTML.
changelog: [`doc_nested_refdefs`]: add suspicious lint for link def at start of list items and block quotes

doc_nested_refdefs: new lint for suspicious list syntax

---

clippy_lints/src/lifetimes.rs

Tiny change to make `report_elidable_impl_lifetimes`'s doc comment consistent with #13752. (cc: @samueltardieu)
---

Correct `report_elidable_impl_lifetimes` comment following #13752

---

clippy_lints/src/doc/mod.rs
tests/ui/doc/doc_lazy_list.fixed
tests/ui/doc/doc_lazy_list.rs

changelog: [`doc_lazy_continuation`]: correctly count indent with backslashes
Fixes #13705

doc_lazy_continuation: Correctly count indent with backslashes

---

clippy_lints/src/casts/borrow_as_ptr.rs
clippy_lints/src/casts/mod.rs
clippy_utils/src/msrvs.rs
tests/ui/borrow_and_ref_as_ptr.fixed
tests/ui/borrow_and_ref_as_ptr.rs
tests/ui/borrow_and_ref_as_ptr.stderr
tests/ui/borrow_as_ptr_raw_ref.fixed
tests/ui/borrow_as_ptr_raw_ref.rs
tests/ui/borrow_as_ptr_raw_ref.stderr

This PR updates the `borrow_as_ptr` lint to no longer suggest `addr_of!` and `addr_of_mut!` and instead use the preferred `&raw const` and `&raw mut` syntax.
Not sure about two things:
1. Do I need to set or update a MSRV for the lint anywhere?
2. There is a `borrow_as_ptr_no_std` test as well as a `borrow_as_ptr` test. They used to be more relevant as the lint needed to select `std` or `core`, but that is gone now, so maybe the `borrow_as_ptr_no_std` should be deleted?
changelog: update `borrow_as_ptr` to suggest `&raw` syntax

update `borrow_as_ptr` to suggest `&raw` syntax

---

clippy_lints/src/manual_is_power_of_two.rs
clippy_lints/src/methods/map_with_unused_argument_over_ranges.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/question_mark.rs
clippy_lints/src/unit_types/unit_arg.rs
clippy_lints/src/unnecessary_literal_bound.rs
clippy_lints/src/utils/internal_lints/slow_symbol_comparisons.rs
src/driver.rs
util/gh-pages/script.js

I ran [Typos](https://github.com/crate-ci/typos) on the project and fixed all of the easy spelling mistakes! I made sure to avoid UI tests, since those changes are more challenging to review due to the changes in `.stderr` files.
```
changelog: Fixed several typos.
```

Fix various typos

---

clippy_lints/src/methods/str_splitn.rs
tests/ui/manual_split_once.fixed
tests/ui/manual_split_once.stderr

This addresses #13099 for the manual_split_once test, using the str_splitn lint. 
changelog: [str_splitn]: Updated str_splitn to use multipart_suggestions where appropriate

chore: use multipart_suggestions for str_splitn

---

CHANGELOG.md
clippy_lints/src/casts/as_pointer_underscore.rs
clippy_lints/src/casts/mod.rs
clippy_lints/src/declared_lints.rs
tests/ui/as_pointer_underscore.fixed
tests/ui/as_pointer_underscore.rs
tests/ui/as_pointer_underscore.stderr

changelog: New lint for as *const _ and as *mut _ pointer casts
EDIT: lets go with the simpler version

New lint for `as *const _` and `as *mut _` pointer casts

---

clippy_lints/src/default_numeric_fallback.rs

The existing known problem is not actually true, and the many false positives and false negatives should be mentioned.
Allowing the lint on a single statement: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=328de43690af13ed126f7c00c15cd695
changelog: [`default_numeric_fallback`]: update known problems docs

Update known problems for default_numeric_fallback

---

clippy_lints/src/manual_async_fn.rs
tests/ui/manual_async_fn.fixed
tests/ui/manual_async_fn.stderr

This addresses #13099 for the manual_async_fn test.
changelog: [manual_async_fn]: Updated manual_async_fn to use multipart_suggestions where appropriate

chore: use multipart_suggestions for manual_async_fn

---

clippy_lints/src/disallowed_macros.rs
clippy_lints/src/disallowed_methods.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/missing_const_for_thread_local.rs
clippy_lints/src/strings.rs

remove unnecessary notations

---

clippy_lints/src/index_refutable_slice.rs
tests/ui-toml/max_suggested_slice_pattern_length/index_refutable_slice.fixed
tests/ui-toml/max_suggested_slice_pattern_length/index_refutable_slice.stderr
tests/ui/index_refutable_slice/if_let_slice_binding.fixed
tests/ui/index_refutable_slice/if_let_slice_binding.stderr
tests/ui/index_refutable_slice/slice_indexing_in_macro.fixed
tests/ui/index_refutable_slice/slice_indexing_in_macro.stderr

This should address #13099 for the derivable_impls test. As this combines everything into a single multipart_suggestion, the feedback message is a little less "targeted" than it was before, but now it provides a complete`--fix`able suggestion - e.g.:
```
error: this binding can be a slice pattern to avoid indexing
--> tests/ui-toml/max_suggested_slice_pattern_length/index_refutable_slice.rs:5:17
|
LL |     if let Some(slice) = slice {
|                 ^^^^^
|
note: the lint level is defined here
--> tests/ui-toml/max_suggested_slice_pattern_length/index_refutable_slice.rs:1:9
|
LL | #![deny(clippy::index_refutable_slice)]
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: replace the binding and indexed access with a slice pattern
|
LL ~     if let Some([_, _, _, _, _, _, _, slice_7, ..]) = …
```

Fix:  fixed multipart_suggestion in index_refutable_slice uitest

---

clippy_lints/src/comparison_chain.rs
tests/ui/comparison_chain.rs
tests/ui/comparison_chain.stderr

changelog: [`comparison_chain`]: give explicit help message showing a clear suggestion
Close #13739

Better help message for comparison_chain lint

---

clippy_lints/src/shadow.rs
tests/ui/shadow.rs
tests/ui/shadow.stderr

Fix #13795
changelog: [`shadow_same`]: detect shadowing as a pattern field

Detect shadowing in pattern field

---

clippy_lints/src/arbitrary_source_item_ordering.rs

fix #13818 
The `arbitrary_source_item_ordering` lint does not exist in v1.82.0, so I think it needs to be fixed.
changelog: [`arbitrary_source_item_ordering`]: corrected available version information for this lint

fix version attribute for `arbitrary_source_item_ordering` lint

---

clippy_lints/src/matches/mod.rs
clippy_utils/src/lib.rs
tests/ui/single_match.fixed
tests/ui/single_match.rs
tests/ui/single_match.stderr

We realized when running `clippy --fix` on rustdoc (PR comment [here](https://github.com/rust-lang/rust/pull/133537/files#r1861377721)) that some comments were removed, which is problematic. This PR checks that comments outside of `match` arms are taken into account before emitting the lint.
changelog: Fix `single_match` lint being emitted when it should not

Fix `single_match` lint being emitted when it should not

---

clippy_lints/src/matches/single_match.rs
tests/ui/single_match.fixed
tests/ui/single_match.rs
tests/ui/single_match.stderr

fix #12758
The `single_match` lint makes incorrect suggestions when comparing with byte string literals. There seems to be an issue with the logic that calculates the number of refs when creating suggestions.
changelog: [`single_match`]: No longer make incorrect suggestions when comparing with byte string literals.

correct `single_match` lint suggestion

---

clippy_lints/src/indexing_slicing.rs

changelog: [`indexing_slicing`]: Clarify the relationship between indexing_slicing and out_of_bound_indexing, clarify that this lint is about possible panics based on runtime values, and fix array example to not trigger the out_of_bound_indexing lint.

indexing_slicing: Clarify documentation

---

clippy_lints/src/significant_drop_tightening.rs
tests/ui/significant_drop_tightening.fixed
tests/ui/significant_drop_tightening.stderr

This addresses https://github.com/rust-lang/rust-clippy/issues/13099 for the significant_drop_tightening lint.

chore: use multipart_suggestion in significant_drop_tightening lint

---

clippy_lints/src/functions/must_use.rs
tests/ui/must_use_unit.fixed
tests/ui/must_use_unit.rs
tests/ui/must_use_unit.stderr

fix #12320 
When there're multiple attributes, clippy suggests leaving an extra comma and it makes an error.
changelog: [`must_use_unit`]:  No longer make incorrect suggestions when multiple attributes present.

fix `must_use_unit` suggestion when there're multiple attributes

---

clippy_lints/src/matches/match_same_arms.rs
tests/ui/match_same_arms.stderr
tests/ui/match_same_arms2.fixed
tests/ui/match_same_arms2.stderr

This addresses https://github.com/rust-lang/rust-clippy/issues/13099 for the match_same_arms lint.
changelog: [match_same_arms]: Updated match_same_arms to use multipart_suggestions where appropriate

chore: use multipart_suggestions for match_same_arms

---

clippy_lints/src/operators/numeric_arithmetic.rs

Looks like typo for me.
Looking at blame https://github.com/rust-lang/rust-clippy/commit/b76b0aeb63948fecca6d6f603f47c6648059048a#diff-ac15e787d7d276b24f251f4f5bdedf1e6ac81aa1e2ea0db27219e9a7fa8b0b30L66 the same typo was before.
Is logic here actually correct? Tests passed locally, but i expected some changes.

fix typo in `numeric_arithmetic` logic

---

clippy_lints/src/methods/unnecessary_sort_by.rs
tests/ui/unnecessary_sort_by_no_std.fixed
tests/ui/unnecessary_sort_by_no_std.rs
tests/ui/unnecessary_sort_by_no_std.stderr

fix #11524 
In a `no_std` environment, we can use `core::cmp::Reverse` instead of `std::cmp::Reverse`.
----
changelog: [`unnecessary_sort_by`]: correct suggestion in `no_std`

correct suggestion for `unnecessary_sort_by` in `no_std`

---

clippy_lints/src/methods/filter_map_identity.rs
tests/ui/filter_map_identity.fixed
tests/ui/filter_map_identity.rs

fix #12653
changelog: [`filter_map_identity`]: don't lint for creating an iterator from an empty array

Don't trigger `filter_map_identity` with an iterator from an empty array

---

clippy_lints/src/methods/unnecessary_iter_cloned.rs
tests/ui/unnecessary_iter_cloned.fixed
tests/ui/unnecessary_iter_cloned.stderr
tests/ui/unnecessary_to_owned.stderr

This will address https://github.com/rust-lang/rust-clippy/issues/13099 for the unnecessary_iter_cloned test.
changelog: [unnecessary_iter_cloned]: unnecessary_iter_cloned manual_assert to use multipart_suggestions where appropriate

chore: starting to fix unnecessary_iter_cloned

---

tests/ui/unnecessary_to_owned.fixed
tests/ui/unnecessary_to_owned.stderr

It is related to https://github.com/rust-lang/rust-clippy/issues/13099
What was done:
- removed `@no-rustfix` from `tests/ui/unnecessary_to_owned.rs`
- checked for suggestions in `src/methods/unnecessary_to_owned.rs` (there is already one multipart_suggestion, and I don't see any other)
- ran `cargo uibless`
I am new to Rust, and this is my first PR.

Use multipart suggestion in `unnecessary_to_owned`

---

CHANGELOG.md
book/src/lint_configuration.md
clippy_config/src/conf.rs
clippy_lints/src/indexing_slicing.rs
tests/ui-toml/indexing_slicing/clippy.toml
tests/ui-toml/indexing_slicing/indexing_slicing.rs
tests/ui-toml/indexing_slicing/indexing_slicing.stderr
tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr

Close #13842
changelog: [`indexing_slicing`]: add allow-indexing-slicing-in-tests option to be able ignore at test

Add allow-indexing-slicing-in-tests option

---

clippy_utils/src/ty/mod.rs

Fix `has_iter_method` documentation

---

clippy_lints/src/unit_types/let_unit_value.rs
tests/ui/let_unit.fixed
tests/ui/let_unit.stderr

This should address #13099 for the let_unit test. 
changelog: [let_unit]: Updated let_unit to use multipart_suggestions where appropriate

chore: multipart suggestions for let_unit_value lint

---

clippy_lints/src/if_not_else.rs
tests/ui/if_not_else.fixed
tests/ui/if_not_else.rs
tests/ui/if_not_else.stderr

fix #13411 
The `if_not_else` lint can be fixed automatically, but the issue above reports that there is no implementation to do so. Therefore, this PR implements it.
----
changelog: [`if_not_else`]: make suggestions for modified code

auto-fix `if_not_else`

---

clippy_utils/src/lib.rs

`is_integer_const()` does the const folding.

Remove obsolete comment

---

clippy_lints/src/manual_div_ceil.rs
tests/ui/manual_div_ceil.fixed
tests/ui/manual_div_ceil.rs
tests/ui/manual_div_ceil.stderr
tests/ui/manual_div_ceil_with_feature.fixed
tests/ui/manual_div_ceil_with_feature.rs
tests/ui/manual_div_ceil_with_feature.stderr

fix #13843
The `manual_div_ceil` lint makes incorrect suggestion when type suffixes need to be made explicit in the suggested code.
changelog: [`manual_div_ceil`]: suggested code now includes appropriate type suffixes where necessary

correct suggestion for `manual_div_ceil` lint

---

clippy_lints/src/matches/mod.rs

The "known problems" pointed out in the `match_same_arms` lint seem to have already been resolved.

remove description of known problems in `match_same_arms` that have already been resolved

---

book/src/development/method_checking.md

fix arguments of `ExprKind::MethodCall`

---

clippy_lints/src/trailing_empty_array.rs
tests/ui/trailing_empty_array.rs

Close #13837
changelog: [`trailing_empty_array`]: do not trigger on tests

Do not trigger `trailing_empty_array` in tests

---

clippy_lints/src/doc/missing_headers.rs
tests/ui/crashes/ice-13862.rs

Fixes #13862 
`missing_headers::check` is sometimes called from outside of a body (specifically, from `check_attributes`, where the LateContext's ParamEnv is not yet properly initialized for that item). Using that empty ParamEnv for trait solving things from within the body can then lead to various ICEs, like the linked issue where we have a const generic parameter `DMA_INST` without a `ConstArgHasType` bound in the ParamEnv so the const parameter has no type, which is normally not supposed to happen.
We have the item's DefId so we can just get its ParamEnv/TypingEnv from there, and using that one for trait solving should be safe.

use the correct `ParamEnv` when checking future's output type

---

clippy_lints/src/non_copy_const.rs
tests/ui/borrow_interior_mutable_const/others.rs
tests/ui/borrow_interior_mutable_const/others.stderr

This PR just makes sure that we exit the function before getting an ICE and adds a regression test. Related to #12979. We would need to keep researching the issue, but as the ICEing code isn't that complicated, getting a hotfix into nightly is urgent.
changelog:[`borrow_interior_mutable_const`] Fix ICE #12979

`borrow_interior_mutable_const` ICE into FN

---

clippy_lints/src/casts/borrow_as_ptr.rs
clippy_lints/src/casts/mod.rs
tests/ui/borrow_as_ptr.fixed
tests/ui/borrow_as_ptr.rs
tests/ui/borrow_as_ptr.stderr

Also, simplify boolean shortcut expression, and ensure that applicability is properly applied, as it was ignored and `MachineApplicable` was always used.
changelog: [`borrow_as_ptr`]: do not remove required parentheses in autofix suggestion
Close #13882

Do not remove required parentheses in `borrow_as_ptr` suggestion

---

clippy_lints/src/methods/needless_character_iteration.rs
clippy_lints/src/methods/read_line_without_trim.rs
clippy_lints/src/utils/internal_lints/invalid_paths.rs
clippy_utils/src/paths.rs

I discovered that there were paths declared in `clippy_utils::paths` in https://github.com/rust-lang/rust-clippy/pull/13829 so moving a few remaining hardcoded ones in one place.
changelog: Move more def paths into `clippy_utils::paths`
r? @y21

Move more def paths into `clippy_utils::paths`

---

clippy_lints/src/needless_arbitrary_self_type.rs
tests/ui/needless_arbitrary_self_type.fixed
tests/ui/needless_arbitrary_self_type.rs
tests/ui/needless_arbitrary_self_type.stderr

Using `lifetime.ident.name` in suggestions will not output the raw modifier. For example, `'r#struct` will be rendered as `'struct` which would be incorrect.
Fix #13899 
changelog: [`needless_arbitrary_self_type`]: use the raw lifetime name in suggestions

Use the full lifetime name in suggestions

---

tests/ui/crashes/ice-10972-tait.rs

`asked to assemble constituent types of unexpected type: Binder(Foo, [])`
Fixes #10972

add test for ICE

---

clippy_lints/src/eta_reduction.rs
clippy_lints/src/len_zero.rs
tests/ui/len_zero.fixed
tests/ui/len_zero.rs
tests/ui/len_zero.stderr

In this case, the lint can be triggered as well as `is_empty()` will be found on the target type.
One such case was found in Clippy sources (first commit)
changelog: [`len_zero`]: trigger if deref target implements `is_empty()`
Close #13861

Check if deref target implements `is_empty` for `len_zero` lint

---

clippy_lints/src/slow_vector_initialization.rs
tests/ui/slow_vector_initialization.rs
tests/ui/slow_vector_initialization.stderr

close #13781
The `slow_vector_initialization` lint currently only suggests using the `vec!` macro with size, but it does not suggest removing the `resize` method call.
changelog: [`slow_vector_initialization`]: improve `slow_vector_initialization` suggestion

Improve `slow_vector_initialization` suggestion

---

.github/workflows/clippy_dev.yml
.github/workflows/clippy_mq.yml
.github/workflows/clippy_pr.yml
.github/workflows/deploy.yml
.github/workflows/lintcheck.yml
.github/workflows/remark.yml

This PR fixes two vulnerabilities in our CI, found with [zizmor](https://github.com/woodruffw/zizmor). One could be exploited by someone with tag-pushing permissions to execute arbitrary code in our CI (see`deploy.yml`). The second vulnerability would expose our tokens to a supply chain attack via a `build.rs` in one of the dependencies (See the rest of the files, and https://github.com/actions/checkout/issues/485)
Pre-reviewed by @flip1995 in our DMs.
changelog:none

Make CI a little bit safer

---

clippy_lints/src/methods/unnecessary_to_owned.rs
clippy_lints/src/needless_continue.rs
clippy_lints/src/redundant_else.rs
clippy_lints/src/transmute/transmute_undefined_repr.rs
tests/missing-test-files.rs
tests/ui/needless_continue.rs
tests/ui/needless_continue.stderr

fixes: #4077
Continuation of #11546. r? @y21 if you don't mind?
changelog: [`needless_continue`] lint if the last stmt in loop is `continue` recurisvely

[`needless_continue`]: lint if the last stmt in loop is `continue` recurisvely

---

clippy_lints/src/vec.rs
tests/ui/useless_vec.rs
tests/ui/useless_vec.stderr

Fixes #13692.
If the `vec!` macro call contains comments, we should not provide suggestions and let users handle it however they see fit.
changelog: Only emit `useless_vec` suggestion if the macro does not contain code comments

Only emit `useless_vec` suggestion if the macro does not contain code comments

---

CHANGELOG.md
book/src/development/infrastructure/changelog_update.md
clippy_lints/src/manual_ignore_case_cmp.rs
clippy_lints/src/regex.rs
clippy_lints/src/unnecessary_literal_bound.rs

Roses are red,
Happy new year,
full of happiness and cheer!
---
---
I've also updated the template to include the text I usually use for moves, renames, or new lints.
---
That's it happy new year, kings, queens, and all other royalty! :heart:

Changelog for Clippy 1.84  🧨

---

clippy_lints/src/missing_const_for_fn.rs
tests/ui/missing_const_for_fn/cant_be_const.rs

Close #13938
changelog: [`missing_const_for_fn`]: do not trigger for tests

Do not trigger `missing_const_for_fn` for tests

---

clippy_lints/src/redundant_locals.rs

Even its documentation says so. According to the documentation, it might either be a "suspicious" or a "perf" lint.
changelog: [`redundant_locals`]: Reclassify as "suspicious" lint.

`clippy::redundant_locals` is not a correctness lint

---

clippy_lints/src/methods/map_flatten.rs
tests/ui/map_flatten.rs
tests/ui/map_flatten.stderr

Fixes https://github.com/rust-lang/rust-clippy/issues/8528.
Similar to #13911, if there are code comments, we don't want to remove them automatically.
changelog: Don't emit machine applicable `map_flatten` lint if there are code comments
r? @xFrednet

Don't emit machine applicable `map_flatten` lint if there are code comments

---

.github/workflows/clippy_mq.yml
.github/workflows/clippy_pr.yml

`rustup show active-toolchain` will no longer install the default toolchain starting from Rustup 1.28.0, and `rustup toolchain install` without extra arguments is not supported in Rustup pre-1.28.0.
The Rustup change and proposed solution is described in <https://internals.rust-lang.org/t/seeking-beta-testers-for-rustup-v1-28-0/22060>.

CI: be compatible with both Rustup pre-1.28.0 and 1.28.0

---

clippy_lints/src/methods/unnecessary_map_or.rs
tests/ui/unnecessary_map_or.fixed
tests/ui/unnecessary_map_or.rs
tests/ui/unnecessary_map_or.stderr

When the expression is transformed into an equality, parentheses are needed only if the resulting equality is used:
- as a receiver in a method call
- as part of a binary or unary expression
- as part of a cast
In other cases, which will be the majority, no parentheses are required. This makes the lint suggestions cleaner.
changelog: `none`

Remove unneeded parentheses in `unnecessary_map_or` lint output

---

clippy_lints/src/methods/map_identity.rs
tests/ui/map_identity.fixed
tests/ui/map_identity.rs
tests/ui/map_identity.stderr

Removing `.map(identity)` may result in invalid code if the receiver of `map()` is an immutable binding, and the result of `map()` is used as the receiver of a method call expecting a mutable reference.
Fix #13904
changelog: [`map_identity`]: do not lint if this would cause mandatory mutability to be lost

Do not remove identity mapping if mandatory mutability would be lost

---

clippy_lints/src/manual_is_ascii_check.rs
tests/ui/manual_is_ascii_check.fixed
tests/ui/manual_is_ascii_check.rs
tests/ui/manual_is_ascii_check.stderr

Fixes #13913 .
changelog: [`manual_is_ascii_check`]: fix type suggestions for references
Previously it only derived `char` and `u8` types, now it should always annotate the lambda parameter with the correct type (e.g. `&char`).
I'm quite new to Rust and this is my first contact with clippy, so I'm open for suggetions :)

 Fix type suggestion for manual_is_ascii_check

---

clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/needless_as_bytes.rs
tests/ui/needless_as_bytes.fixed
tests/ui/needless_as_bytes.rs
tests/ui/needless_as_bytes.stderr

I ran Clippy on some projects after upgrading to 1.84, which found a [needless use of `as_bytes()`](https://github.com/rust-lang/rust-clippy/pull/13437). It made me notice that the code was also using `bytes()` needlessly in other places. This PR improves on the `as_bytes()` lint to also lint `bytes()`.
----

Improve `needless_as_bytes` to also detect `str::bytes()`

---

clippy_lints/src/no_mangle_with_rust_abi.rs

The code should not attempt to obtain a snippet by capping the function signature span with its identifier span without checking that they are in the same context.
This is the only instance I could identify where placeholders were used instead of the real snippet when running the CI lintcheck. Moreover, the placeholders were not even used, as they snippet was obtained prematurely.
Found in the context of #13941 

Do not intersect spans coming from different contexts

---

CONTRIBUTING.md

At CONTRIBUTING.md there are mentioned [`l-crash`](https://github.com/rust-lang/rust-clippy/issues?q=is%3Aopen+label%3Al-crash) and [`l-bug`](https://github.com/rust-lang/rust-clippy/issues?q=is%3Aopen%20label%3Al-bug) labels which are never used, so correct them to [`I-ICE`](https://github.com/rust-lang/rust-clippy/issues?q=is%3Aopen%20label%3AI-ICE) and  [`C-bug`](https://github.com/rust-lang/rust-clippy/issues?q=is%3Aopen%20label%3AC-bug)

Mention existing labels at CONTRIBUTING

---

.github/workflows/clippy_changelog.yml
.github/workflows/clippy_mq.yml

Checking it only in the merge queue leads to deferred failures once the decision to merge has been taken already.

CI: check the presence of the changelog line in every pull request

---

clippy_lints/src/missing_fields_in_debug.rs

This removes the last call to `LateContext::match_def_path()` in Clippy's code. The `LateContext::match_def_path()` in the compiler sources was only kept for Clippy's usage.
Once this PR is merged and after the rustup, I will submit one to remove `LateContext::match_def_path()` from the compiler.
r? @flip1995

Use diagnostic item instead of path for `core::fmt::Debug`

---

.github/workflows/clippy_changelog.yml

Rerunning the PR checks when a PR is synchronized (new commits added, or force-pushed) seems to remove the changelog checks from the UI while keeping the PR mergeable from the maintainer's interface.
This PR reruns the cheap changelog check when a PR is synchronized.
r? @flip1995

CI: rerun the changelog check on PR synchronization

---

CHANGELOG.md
clippy_lints/src/declared_lints.rs
clippy_lints/src/matches/manual_ok_err.rs
clippy_lints/src/matches/mod.rs
clippy_utils/src/ty/mod.rs
tests/ui/manual_ok_err.fixed
tests/ui/manual_ok_err.rs
tests/ui/manual_ok_err.stderr

changelog: [`manual_ok_err`]: new lint
Detect manual implementations of `.ok()` or `.err()`, as in
```rust
let a = match func() {
Ok(v) => Some(v),
Err(_) => None,
};
let b = if let Err(v) = func() {
Some(v)
} else {
None
};
```
which can be replaced by
```rust
let a = func().ok();
let b = func().err();
```
This pattern was detected in the wild in the Rust reimplementation of coreutils: https://github.com/uutils/coreutils/pull/6886#pullrequestreview-2465160137

New lint: manual_ok_err

---

clippy_lints/src/literal_string_with_formatting_args.rs

It claims to be in 1.83 but in fact will not be until 1.85.
Evidence: <https://github.com/rust-lang/rust/pull/134788> is where it was merged into rust-lang/rust, and has a milestone of 1.85.

Correct version of `literal_string_with_formatting_args`

---

CHANGELOG.md
clippy_lints/src/arbitrary_source_item_ordering.rs
clippy_lints/src/declared_lints.rs
clippy_lints/src/lib.rs
clippy_lints/src/unneeded_struct_pattern.rs
tests/ui/auxiliary/non-exhaustive-enum.rs
tests/ui/unneeded_struct_pattern.fixed
tests/ui/unneeded_struct_pattern.rs
tests/ui/unneeded_struct_pattern.stderr

Closes #13400.
changelog: [`unneeded_struct_pattern`]: Add new lint

Add new lint `unneeded_struct_pattern`

---

clippy_lints/src/redundant_pub_crate.rs
tests/ui/redundant_pub_crate.fixed
tests/ui/redundant_pub_crate.rs
tests/ui/redundant_pub_crate.stderr

Some widely used crates, such as `pin-project-lite`, make use of a `pub(crate)` construct in a private module inside a public macro. This makes unrelated project trigger the lint.
There is also an unfortunate situation for Clippy itself: when a new version of `pin-project-lite` or similar lint-trigerring crates is released, those lints which can be found in hundreds of occurrences in dependent crates will change, and appear as diffs in unrelated Clippy PR because the base lintcheck run will be cached with the ancient release of the crates. We currently have the situation [here](https://github.com/rust-lang/rust-clippy/actions/runs/12635410895?pr=13851#user-content-redundant-pub-crate-removed), which 219 lints removed and 219 lints added because of a `pin-project-lite` version change …

Do not trigger `redundant_pub_crate` in external macros

---

clippy_lints/src/methods/unnecessary_to_owned.rs
tests/ui/unnecessary_to_owned.fixed
tests/ui/unnecessary_to_owned.rs

fix #13624 
changelog:  [`unnecessary_to_owned`]: don't suggest to use `cloned` on `Cow` in `unnecessary_to_owned`

don't suggest to use `cloned` for `Cow` in `unnecessary_to_owned`

---

book/src/development/common_tools_writing_lints.md

Some of the links are wrong since lead to non existing docs so fix them

Fix not found links at Book

---

book/src/development/defining_lints.md

`define_clippy_lints` does not exist, `declare_clippy_lint` exists.

Fix macro name in the Book

---

book/src/development/infrastructure/release.md

Since we do release tag it makes more sense to refer to tags page then empty releases page 

Fix link to release tags

---

book/src/development/adding_lints.md

changelog: none 
This PR fixes explaining the difference in usage between early and late lint passes in the book.

fix(adding_lints): usage of early vs late lint pass

---

clippy_lints/src/slow_vector_initialization.rs
tests/ui/slow_vector_initialization.fixed
tests/ui/slow_vector_initialization.rs

changelog: [`slow_vector_initialization`]: auto-fix when appropriate
I made a change for `slow_vector_initialization` lint suggestion to use `vec!` with size and remove the unneeded `resize` (or similar one) call in #13912, while only the former one was suggested in the previous implementation. Now, I think this lint can be automatically fixed with no unnecessary code in some cases. I wrote “in some cases” because if there are comments between vector declaration and `resize`, Clippy shouldn't apply auto-fix because the comment may informational.

auto-fix `slow_vector_initialization` in some cases

---

clippy_lints/src/matches/significant_drop_in_scrutinee.rs
tests/ui/significant_drop_in_scrutinee.rs
tests/ui/significant_drop_in_scrutinee.stderr

Temporaries created inside the expansion of `.await` will be dropped and need no checking. Looking inside the expansion will trigger false positives.
changelog: [`significant_drop_in_scrutinee`]: do not falsely warn for temporaries created by `.await` expansion
Fix #13927

Do not look for significant drop inside `.await` expansion

---

CHANGELOG.md
clippy_lints/src/declared_lints.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/useless_nonzero_new_unchecked.rs
clippy_utils/src/msrvs.rs
tests/ui/useless_nonzero_new_unchecked.fixed
tests/ui/useless_nonzero_new_unchecked.rs
tests/ui/useless_nonzero_new_unchecked.stderr

changelog: [`useless-nonzero-new_unchecked`]: new lint
Close #13991
Checks for `NonZero*::new_unchecked(<literal>)` being used in a `const` context.
Using `NonZero*::new_unchecked()` is an `unsafe` function and requires an `unsafe` context. When used with an
integer literal in a `const` context, `NonZero*::new().unwrap()` will provide the same result with identical
runtime performances while not requiring `unsafe`.
```no_run
const PLAYERS: NonZeroUsize = unsafe { NonZeroUsize::new_unchecked(3) };
```
Use instead:
```no_run
const PLAYERS: NonZeroUsize = NonZeroUsize::new(3).unwrap();
```

New lint `useless-nonzero-new_unchecked`

---

triagebot.toml

I'll take a short break from auto assignments. My last few weeks have been busy and I feel like getting my inbox back in order and taking a short breather will be the best for me.
I still plan to review the PRs I'm currently assigned to and writing the changelogs.
Jup that's it, have a good day, who ever is reading this =^.^=

Pause assignments for @xFrednet

---

clippy_lints/src/cargo/mod.rs

Currently https://rust-lang.github.io/rust-clippy/master/index.html#wildcard_dependencies doc doesn't contain explanation how it should be so added more details
----

Update doc wildcard_dependencies

---

clippy_lints/src/eta_reduction.rs

I noticed this because I failed to find this `check_closure` by grepping.

Fix typo in `check_clousure` function name

---

clippy_lints/src/literal_string_with_formatting_args.rs

This PR changes literal_string_with_formatting_args category from `suspicious` to `nursery` since there are thousands of false positive on GitHub.
Closes #13989 since it's no longer problematic with such false positive with ~~`pedantic`~~ `nursery` category.
changelog: [`literal_string_with_formatting_args` ] change category to `nursery` from `suspicious`

change `literal_string_with_formatting_args` lint category to nursery

---

CHANGELOG.md
clippy_lints/src/declared_lints.rs
clippy_lints/src/doc/lazy_continuation.rs
clippy_lints/src/methods/manual_repeat_n.rs
clippy_lints/src/methods/mod.rs
clippy_utils/src/lib.rs
tests/ui/from_iter_instead_of_collect.fixed
tests/ui/from_iter_instead_of_collect.rs
tests/ui/manual_repeat_n.fixed
tests/ui/manual_repeat_n.rs
tests/ui/manual_repeat_n.stderr
tests/ui/manual_str_repeat.fixed
tests/ui/manual_str_repeat.rs
tests/ui/slow_vector_initialization.fixed
tests/ui/slow_vector_initialization.rs
tests/ui/slow_vector_initialization.stderr

close #13271 
changelog: add new `manual_repeat_n` lint

add a new lint for `repeat().take()` that can be replaced with `repeat_n()`

---

clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/unnecessary_map_or.rs
tests/ui/unnecessary_map_or.stderr

A multipart suggestion will be used whenever the method call can be replaced by another one with the first argument removed. It helps place the new method call in context, especially when it is part of a larger expression.
This fixes #13995 by applying a suggestion made by @y21.
r? @y21 
changelog: [`unnecessary_map_or`]: better representation of suggestions by placing them in context

Use clearer multipart suggestions for `unnecessary_map_or` lint

---

clippy_lints/src/matches/significant_drop_in_scrutinee.rs
tests/ui/significant_drop_in_scrutinee.rs
tests/ui/significant_drop_in_scrutinee.stderr

This PR fixes an issue with the `significant_drop_in_scrutinee`, where the lint generates invalid Rust syntax when suggesting fixes for match expressions that are part of larger expressions, such as in assignment contexts. For example:
```rust
let mutex = Mutex::new(State {});
let _ = match mutex.lock().unwrap().foo() {
true => 0,
false => 1,
};
```
would suggest:
```rust
let _ = let value = mutex.lock().unwrap().foo();
match value {
```
With this PR, it now suggests:
```rust
let value = mutex.lock().unwrap().foo();
let _ = match value {
```
closes: #13986
changelog: [`significant_drop_in_scrutinee`] Fix incorrect suggestion for `significant_drop_in_scrutinee` lint in expression context

fix: correct suggestion for significant_drop_in_scrutinee in expressions

---

clippy_lints/src/needless_late_init.rs
tests/ui/needless_late_init.fixed
tests/ui/needless_late_init.rs

fix #13776
changelog: [`needless_late_init`]: don't trigger `needless_late_init` when the first usage is in macro

don't trigger `needless_late_init` when the first usage is in macro

---

clippy_lints/src/misc.rs
tests/ui/short_circuit_statement.fixed
tests/ui/short_circuit_statement.rs
tests/ui/short_circuit_statement.stderr

- The lint no longer triggers if one of the operands in the boolean expression comes from a macro expansion.
- Parenthesis are now removed inside the generated block if they are no longer necessary.
- Error markers have been added.
changelog: [`short_circuit_statement`]: better handling of macros and better looking suggestions

`short_circuit_statement`: handle macros and parenthesis better

---

book/src/lint_configuration.md
clippy_config/src/conf.rs
clippy_lints/src/loops/mod.rs
clippy_lints/src/loops/same_item_push.rs
tests/ui/same_item_push.rs
tests/ui/same_item_push.stderr

Using `Vec::extend(std::iter::repeat_n(item, N))` allows to use the more natural number of elements to add `N`, as is probably done in the original loop, instead of computing the difference between the existing number of elements and the wanted one.
Before MSRV 1.82, the older suggestion to use `Vec::resize()` is still issued.
Inspired by #6156 (which predates `repeat_n()`).
changelog: [`same_item_push`]: recommend using `Vec::extend()` to extend a vector

Suggest using `Vec::extend()` in `same_item_push`

---

clippy_lints/src/lib.rs
clippy_lints/src/returns.rs
clippy_lints/src/unnecessary_semicolon.rs
clippy_utils/src/lib.rs
tests/ui/unnecessary_semicolon.edition2021.fixed
tests/ui/unnecessary_semicolon.edition2021.stderr
tests/ui/unnecessary_semicolon.edition2024.fixed
tests/ui/unnecessary_semicolon.edition2024.stderr

Before edition 2024, some temporaries used in scrutinees of a `match` used as the last expression of a block may outlive some referenced local variables. Prevent those cases from happening by checking that alive temporaries with significant drop do have a static lifetime.
The check is performed only for edition 2021 and earlier, and for the last statement if it would become the last expression of the block.
changelog: [`unnecessary_semicolon`]: prevent borrow errors in editions lower than 2024
r? @y21

`unnecessary_semicolon`: do not lint if it may cause borrow errors

---

clippy_lints/src/matches/match_bool.rs
tests/ui/match_bool.fixed
tests/ui/match_bool.rs
tests/ui/match_bool.stderr

Without this check, the lint would suggest that
```rust
match test {
true if option == 5 => 10,
_ => 1,
};
```
is replaced by `if test { 10 } else { 1 }`.
changelog: [`match_bool`]: omit suggestion when guards are present in `match` expression

`match_bool`: fix suggestion if guard is present

---

clippy_lints/src/operators/arithmetic_side_effects.rs
tests/ui/arithmetic_side_effects.rs
tests/ui/arithmetic_side_effects.stderr

Fix #14054
changelog: [`arithmetic_side_effects`]: warn about more cases when `Deref` is involved

`arithmetic_side_effects`: check adjusted expression types

---

clippy_lints/src/methods/unnecessary_sort_by.rs

This comment was left behind when the method receiver was split out from the method arguments in 4bcaddeeb23544eb2c86b600c3d775e2773758c2.

Fix out-of-date comment

---

clippy_lints/src/useless_conversion.rs
tests/ui/useless_conversion.fixed
tests/ui/useless_conversion.rs
tests/ui/useless_conversion.stderr

Fix #11819
changelog: [`useless_conversion`]: add necessary adjustments to suggestion to remove redundant `.into_iter()` calls

Add necessary adjustments to suggestion to remove redundant `.into_iter()` calls

---

clippy_lints/src/operators/mod.rs

`x & 15 == 0` is not equivalent to `x.trailing_zeros() > 4`, as `x = 0b10000` is true for the former and false for the latter.
In fact, clippy itself suggests the following:
```rust
pub fn src(x: i32) -> bool {
x & 15 == 0 // ~error: bit mask could be simplified with a call to `trailing_zeros`
^^^^^^^^^^^ help: try: `x.trailing_zeros() >= 4`
}
```

docs: fix verbose-bit-mask example

---

clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/obfuscated_if_else.rs
tests/ui/obfuscated_if_else.fixed
tests/ui/obfuscated_if_else.rs
tests/ui/obfuscated_if_else.stderr

part of https://github.com/rust-lang/rust-clippy/issues/9100
The `obfuscated_if_else` lint currently only triggers for the pattern `.then_some(..).unwrap_or(..)`, but there're other cases where this lint should be triggered, one of which is `.then(..).unwrap_or(..)`. 
changelog: [`obfuscated_if_else`]: trigger lint for the `.then(..).unwrap_or(..)` pattern as well

trigger `obfuscated_if_else` for `.then(..).unwrap_or(..)`

---

.github/workflows/clippy_changelog.yml

I noticed that default PR messages could pass the changelog checking CI.
For example, if a PR is submitted without modifying the PR template, the following line is mistakenly treated as a valid changelog by the CI:
```
changelog: [`lint_name`]: your change
```
r? flip1995

set default PR messages to fail the changelog CI

---

book/src/lint_configuration.md
clippy_config/src/conf.rs

I added `manual_repeat_n` lint before, which has the `MSRV` option. However, I forgot to add this lint to the lint configuration.

fixed a missing description of the MSRV option for `manual_repeat_n`

---

clippy_lints/src/non_copy_const.rs

Remove "Known problems" section for `borrow_interior_mutable_const` since issue were fixed some time ago - #6110, #5812

Remove "Known problems" section for `borrow_interior_mutable_const`

---

clippy_lints/src/eta_reduction.rs
clippy_lints/src/methods/drain_collect.rs
clippy_lints/src/methods/map_with_unused_argument_over_ranges.rs
clippy_lints/src/repeat_vec_with_capacity.rs
clippy_lints/src/single_range_in_vec_init.rs
tests/ui/drain_collect_nostd.fixed
tests/ui/drain_collect_nostd.rs
tests/ui/drain_collect_nostd.stderr
tests/ui/eta_nostd.fixed
tests/ui/eta_nostd.rs
tests/ui/eta_nostd.stderr
tests/ui/map_with_unused_argument_over_ranges_nostd.fixed
tests/ui/map_with_unused_argument_over_ranges_nostd.rs
tests/ui/map_with_unused_argument_over_ranges_nostd.stderr
tests/ui/repeat_vec_with_capacity_nostd.fixed
tests/ui/repeat_vec_with_capacity_nostd.rs
tests/ui/repeat_vec_with_capacity_nostd.stderr

I opened https://github.com/rust-lang/rust-clippy/pull/13896 before. However, I found that there're more cases where Clippy suggests to use modules that belong to the `std` crate even in a `no_std` environment. Therefore, this PR include the changes I've made in #13896 and new changes to fix cases I found this time to prevent wrong suggestions in `no_std` environments as well.
changelog: [`redundant_closure`]: correct suggestion in `no_std`
changelog: [`repeat_vec_with_capacity`]: correct suggestion in `no_std`
changelog: [`single_range_in_vec_init`]: don't emit suggestion to use `Vec` in `no_std`
changelog: [`drain_collect`]: correct suggestion in `no_std`
changelog: [`map_with_unused_argument_over_ranges`]: correct suggestion in `no_std`
also close #13895

correct suggestions in `no_std`

---

clippy_lints/src/methods/obfuscated_if_else.rs
tests/ui/obfuscated_if_else.fixed
tests/ui/obfuscated_if_else.rs
tests/ui/obfuscated_if_else.stderr

fix #14034 
The currect implementation of `obfuscated_if_else` sometimes makes incorrect suggestions when the original code have side effects (see the example in the above issue). I think this can be fixed by changing the applicability depending on whether it can have side effects or not.
changelog: [`obfuscated_if_else`]: change applicability when the original code can have side effects

proper applicability for `obfuscated_if_else`

---

CHANGELOG.md
README.md
clippy_lints/src/declared_lints.rs
clippy_lints/src/doc/lazy_continuation.rs
clippy_lints/src/doc/mod.rs
tests/ui/doc/doc_lazy_list.fixed
tests/ui/doc/doc_lazy_list.rs
tests/ui/doc/doc_lazy_list.stderr
tests/ui/doc/doc_overindented_list_items.fixed
tests/ui/doc/doc_overindented_list_items.rs
tests/ui/doc/doc_overindented_list_items.stderr

Add a new lint `doc_overindented_list_items` to detect and fix list items
in docs that are overindented.
For example,
```rs
/// - first line
///      second line
fn foo() {}
```
this would be fixed to:
```rs
/// - first line
///   second line
fn foo() {}
```
This lint improves readabiliy and consistency in doc.
---
[lint_naming]: https://rust-lang.github.io/rfcs/0344-conventions-galore.html#lints
changelog: [`doc_overindented_list_items`]: Added a new lint that detects overindented list items in docs
fixes: #13601

Add new lint `doc_overindented_list_items`

---

.github/workflows/lintcheck.yml

Currently, the CI pipeline triggers `Lintcheck` for all PRs. However, this check takes significant amount of time and seems unnecessary for some certain directories that are frequently updated.
r? flip1995

exclude some directories from `Lintcheck` CI

---

clippy_lints/src/methods/needless_option_take.rs
tests/ui/needless_option_take.fixed
tests/ui/needless_option_take.stderr

changelog: [`needless_option_take`]: add autofix

`needless_option_take`: add autofix

---

clippy_lints/src/write.rs
tests/ui/print_literal.fixed
tests/ui/print_literal.rs
tests/ui/print_literal.stderr
tests/ui/write_literal.fixed
tests/ui/write_literal.rs
tests/ui/write_literal.stderr

fix #13959 
The current implementation of the `write_literal` and `print_literal` lint performs escaping for the second argument of `write!` ,`writeln!`, `print!` and `println!` of the suggestion by first replacing `"` with `\"`, and then replacing `\` with `\\`. Performing these replacements in this order may lead to unnecessary backslashes being added if the original code contains `"` (e.g. `"` -> `\\"`), potentially resulting in a suggestion that causes the code to fail to compile.
In the issue mentioned above, it’s suggested to use raw strings as raw strings, but implementing this would require an ad-hoc change to the current implementation, so it has been deferred. (I'll implement this in another PR)
changelog: [`write_literal`]: fix incorrect escaping of suggestions
changelog: …

Fix escaping problem in `write_literal` and `print_literal` lint suggestion

---

clippy_dev/src/new_lint.rs
clippy_lints/src/endian_bytes.rs
clippy_lints/src/format_push_string.rs
clippy_lints/src/methods/mod.rs

Closes #11434 by moving `format_push_string` and `format_collect` to pedantic.
changelog: Move `format_push_string` and `format_collect` to pedantic

Move `format_push_string` and `format_collect` to pedantic

---

clippy_lints/src/redundant_else.rs
tests/ui/redundant_else.fixed
tests/ui/redundant_else.stderr

changelog: [`redundant_else`]: autofix for some cases
`redundant_else` can be fixed automatically.

autofix for `redundant_else` lint

---

clippy_lints/src/eta_reduction.rs
tests/ui/eta.fixed
tests/ui/eta.rs
tests/ui/eta.stderr

Fix #14096
changelog: [`redundant_closure_for_method_calls`]: repeat generic args in suggestion

Include generic arguments when suggesting a closure η-reduction

---

CHANGELOG.md
clippy_lints/src/declared_lints.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/return_and_then.rs
clippy_lints/src/methods/unnecessary_lazy_eval.rs
tests/ui/return_and_then.fixed
tests/ui/return_and_then.rs
tests/ui/return_and_then.stderr

close #6436 
changelog: [`return_and_then`]: new lint

feat: new lint for `and_then` when returning Option or Result

---

CHANGELOG.md
clippy_lints/src/declared_lints.rs
clippy_lints/src/precedence.rs
tests/ui/precedence.stderr
tests/ui/precedence_bits.fixed
tests/ui/precedence_bits.rs
tests/ui/precedence_bits.stderr

Commit 25505302665a707bedee68ca1f3faf2a09f12c00 has extended the `precedence` lint to include bitmasking and shift operations. The lint is warn by default, and this generates many hits, especially in embedded or system code, where it is very idiomatic to use expressions such as `1 << 3 | 1 << 5` without parentheses.
This commit splits the recent addition into a new lint, which is put into the "restriction" category, while the original one stays in "complexity", because mixing bitmasking and arithmetic operations is less typical.
Fix #14097
changelog: [`precedence_bits`]: new lint

New lint: `precedence_bits`, with recent additions to `precedence`

---

clippy_lints/src/methods/mod.rs

`sliced_string_as_bytes`: fix typo in lint description

---

clippy_lints/src/unnecessary_semicolon.rs
tests/ui/unnecessary_semicolon.edition2021.fixed
tests/ui/unnecessary_semicolon.edition2024.fixed
tests/ui/unnecessary_semicolon.rs

Removing the semicolon of the last statement of an expressionless block may change the block type even if the statement's type is `()`. If the block type is `!` because of a systematic early return, typing it as `()` may make it incompatible with the expected type for the block (to which `!` is cast).
Fix #14100
changelog: [`unnecessary_semicolon`]: do not remove semicolon if it could change the block type from `!` to `()`

Do not remove semicolon if it changes the block type

---

clippy_lints/src/misc.rs
tests/ui/toplevel_ref_arg_non_rustfix.stderr

A `ref` pattern applied to an argument is not ignored. It creates a reference as expected, but still requires the function to take ownership of the argument given to it.
Fix #14131 
changelog: [`toplevel_ref_arg`]: use a clearer lint message

Use a better message for `toplevel_ref_arg` lint

---

util/gh-pages/index_template.html
util/gh-pages/script.js
util/gh-pages/style.css
util/gh-pages/theme.js

This fixes the buttons that expand/collapse all the lints in the list, it also makes code block syntax highlighting only happen when the specific lint enters the viewport since highlighting them all at once was fairly heavy
There's also a few miscellaneous inline event handler removals
`script.js` and highlightjs are now loaded with `defer` so that the download can start earlier
Also fixes https://github.com/rust-lang/rust-clippy/issues/14048, we were calling highlight on the `pre` in `<pre><code>...</code></pre>` but highlightjs wants us to call it on the `code` element

Fix expand/collapse all on site, make highlightjs lazier

---

clippy_lints/src/ptr.rs
tests/ui/cmp_null.fixed
tests/ui/cmp_null.stderr

changelog: [`cmp_null`]: add autofix

autofix for `cmp_null`

---

clippy_lints/src/operators/mod.rs

remove "Known problems" of `verbose_bit_mask`

---

lintcheck/src/config.rs
lintcheck/src/main.rs

Turns out I was completely overcomplicating myself,
there was no need for an external tool such as becnhv2
or even the original becnh, we already had the benchmarking
infrastructure right under our noses!
This PR implements a new **lintcheck** option called
--perf, using it as a flag will mean that lintcheck
builds Clippy as a release package and hooks perf to it.
The realization that lintcheck is already 90% of what
a benchmarking tool needs came to me in a dream :cloud:
changelog:none

Implement --perf flag to lintcheck for benchmarking

---

CHANGELOG.md
clippy_lints/src/declared_lints.rs
clippy_lints/src/lib.rs
clippy_lints/src/manual_option_as_slice.rs
clippy_lints/src/matches/match_as_ref.rs
clippy_utils/src/lib.rs
clippy_utils/src/msrvs.rs
tests/ui/manual_option_as_slice.fixed
tests/ui/manual_option_as_slice.rs
tests/ui/manual_option_as_slice.stderr

Hey folks. It's been a while since I added the `as_slice` method to `Option`, and I totally forgot about a lint to suggest it. Well, I had some time around Christmas, so here it is now.
---
changelog: add [`manual_option_as_slice`] lint

new `manual_option_as_slice` lint

---

clippy_lints/src/mutex_atomic.rs

Similar to https://github.com/rust-lang/rust-clippy/pull/10115 (for `mutex_atomic`), but for `mutex_integer`.
This also improve docs of `mutex_integer`/`mutex_atomic` (extend known problems section to mention condvar issue (https://github.com/rust-lang/rust-clippy/issues/1516) and portability issue).
changelog: Moved [`mutex_integer`] to `restriction`

Move mutex_integer to restriction and improve mutex_{integer,atomic} docs

---

clippy_lints/src/manual_unwrap_or_default.rs
tests/ui/manual_unwrap_or_default_unfixable.rs
tests/ui/manual_unwrap_or_default_unfixable.stderr

fixes #12670
Continuation of #12688. r? @Jarcho if you don't mind?
changelog: [`manual_unwrap_or_default`] fix wrong suggestions when condition type is uncertain

fix: `manual_unwrap_or_default` suggests falsely when condition type is uncertain

---

clippy_lints/src/unneeded_struct_pattern.rs

This lint was merged recently https://github.com/rust-lang/rust-clippy/pull/13465 and should go with the next version 1.86.0 https://github.com/rust-lang/rust-clippy/tags

Update version for unneeded_struct_pattern

---

clippy_lints/src/size_of_in_element_count.rs
tests/ui/size_of_in_element_count/expressions.rs
tests/ui/size_of_in_element_count/expressions.stderr
tests/ui/size_of_in_element_count/functions.rs
tests/ui/size_of_in_element_count/functions.stderr

Counting in bytes for a pointer to `u8` is legitimate and must not trigger the lint. Also, this prevents linting the
`{std,core}::ptr::write_bytes` as it manipulates bytes.
Fix #6590
changelog: [`size_of_in_element_count`]: do not lint if the pointee type is `u8`

Do not trigger `[size_of_in_element_count]` for `u8`

---

book/src/lints.md

[RFC](https://github.com/rust-lang/rfcs/blob/master/text/2476-clippy-uno.md#lint-audit-and-categories) has more groups so add them

Add Nursery and Deprecated groups section at Book

---

book/src/attribs.md

Fix docs for `#[clippy::format_args]`

---

clippy_lints/src/use_self.rs
clippy_lints/src/zero_sized_map_values.rs
clippy_utils/src/lib.rs
clippy_utils/src/ty/mod.rs
tests/ui/use_self.fixed
tests/ui/use_self.rs
tests/ui/use_self.stderr

changelog: [`use_self`] Skip if inside macro expansions of a `impl Self` block
Fixes #13092.
r? Alexendoo

Skip `use_self` inside macro expansions of a `impl Self` block

---

clippy_lints/src/manual_async_fn.rs
tests/ui/manual_async_fn.fixed
tests/ui/manual_async_fn.rs

fixes #12407 
I think it is meaningful to emit a warning even if the span is in a macro.
changelog: [`manual_async_fn`]: don't emit suggestion inside macro

don't emit suggestion inside macro in `manual_async_fn`

---

clippy_utils/src/source.rs
tests/ui/match_bool.fixed
tests/ui/match_bool.rs
tests/ui/match_bool.stderr

Labeled blocks cannot be used as-is in the "then" or "else" part of an `if` expression. They must be enclosed in an anonymous block.
Fix #14099
changelog: [`match_bool`]: fix suggestion when the rewritten block has a label

Don't use labeled block as top-level blocks

---

clippy_lints/src/if_then_some_else_none.rs

`MachineApplicable` is appropriate for the applicability of this lint.
changelog: [`if_then_some_else_none`]: change the applicability to `MachineApplicable`

change the applicability of `if_then_some_else_none` to `MachineApplicable`

---

clippy_dev/src/lint.rs
clippy_dev/src/main.rs

This part has been missed when switching Clippy to edition 2024 a while back.

Use edition 2024 when running `cargo dev lint`

---

clippy_lints/src/copies.rs
clippy_lints/src/entry.rs
clippy_lints/src/if_not_else.rs
clippy_lints/src/matches/manual_unwrap_or.rs
clippy_lints/src/methods/case_sensitive_file_extension_comparisons.rs
clippy_lints/src/methods/filter_map.rs
clippy_lints/src/methods/iter_filter.rs
clippy_lints/src/methods/manual_ok_or.rs
clippy_lints/src/methods/return_and_then.rs
clippy_lints/src/needless_continue.rs
clippy_lints/src/redundant_else.rs
clippy_lints/src/unit_types/unit_arg.rs
clippy_utils/src/source.rs

- `reindent_multiline()` always returns the result of `reindent_multiline_inner()` which returns a `String`. Make `reindent_multiline()` return a `String` as well, instead of a systematically owned `Cow<'_, str>`.
- There is no reason for `reindent_multiline()` to force a caller to build a `Cow<'_, str>` instead of passing a `&str` directly, especially considering that a `String` will always be returned.
Also, both the input parameter and return value (of type `Cow<'_, str>`) shared the same (elided) lifetime for no reason: this worked only because the result was always the `Cow::Owned` variant which is compatible with any lifetime.
As a consequence, the signature changes from:
```rust
fn reindent_multiline(s: Cow<'_, str>, …) -> Cow<'_, str> { … }
```
to
```rust
fn reindent_multiline(s: …
```

Simplify `reindent_multiline()` signature

---

clippy_lints/src/doc/mod.rs

Fix the version of `doc_overindented_list_items`. It actually will be in 1.86.0, not 1.80.0.
(https://github.com/rust-lang/rust/pull/136209 has a milestone of 1.86.0)

Correct version of `doc_overindented_list_items`

---

clippy_lints/src/mut_reference.rs

Fix ICE in `unnecessary_mut_passed`

---

clippy_lints/src/methods/path_buf_push_overwrite.rs

Proposing to replace
```rust
let mut x = PathBuf::from("/foo");
x.push("/bar");
```
by
```rust
let mut x = PathBuf::from("/foo");
x.push("bar");
```
changes the content of `x` (`/bar` ⇒ `/foo/bar`). This is not equivalent and should not be `MachineApplicable`, even if the original code is suspicious.

[`path_buf_push_overwrite`]: mark suggestion as `MaybeIncorrect`

---

clippy_lints/src/transmute/mod.rs

The `useless_transmute` already belongs to the complexity lint.

remove an outdated line in `transmute/mod.rs`

---

book/src/lint_configuration.md
clippy_config/src/conf.rs

`manual_option_as_slice` takes MSRV into account, but this is not mentioned in the lint documentation.

add `manual_option_as_slice` MSRV to the lint documentation

---

clippy_utils/src/ty/mod.rs
tests/ui/crashes/ice-10508a.rs
tests/ui/crashes/ice-10508b.rs
tests/ui/crashes/ice-10508c.rs
tests/ui/large_enum_variant.32bit.stderr
tests/ui/large_enum_variant.64bit.stderr
tests/ui/large_enum_variant.rs

By assuming that a recursive type is normalizable within the deeper calls to `is_normalizable_helper()`, more cases can be handled by this function.
In order to fix stack overflows, a recursion limit has also been added for recursive generic type instantiations.
Fix #9798
Fix #10508 
Fix #11915 
changelog: [`large_enum_variant`]: more precise detection of variants with large size differences

Handle more cases in `is_normalizable`

---

clippy_lints/src/methods/useless_asref.rs
tests/ui/useless_asref.fixed
tests/ui/useless_asref.rs

Removing the `.as_ref()` or `.as_mut()` as the top-level expression in a closure may change the type of the result. In this case, it may be better not to lint rather than proposing a fix that would not work.
changelog: [`useless_asref`]: do not remove the `.as_ref()` or `.as_mut()` call if this would change the type of the enclosing closure
Fix #14088

`useless_asref`: no lint if in a closure to change the ref depth

---

clippy_lints/src/invalid_upcast_comparisons.rs

Remove `Known problems` section `invalid_upcast_comparisons` since issue was fixed #886

Remove `Known problems` section `invalid_upcast_comparisons`

---

book/src/lint_configuration.md
clippy_config/src/conf.rs
clippy_lints/src/loops/manual_flatten.rs
clippy_lints/src/loops/mod.rs

`manual_flatten` should respect MSRV.
changelog: [`manual_flatten`]: add MSRV check

add MSRV check for `manual_flatten`

---

tests/ui/string_add.rs
tests/ui/string_add.stderr

Since `assign_op_pattern` is a style lint, not explicitly allowing it can lead to undesirable output in other lint checks.

allow `assign_op_pattern` in the test of `string_add`

---

clippy_lints/src/copies.rs

remove "Known problems" section for `branches_sharing_code`

---

clippy_lints/src/methods/obfuscated_if_else.rs
tests/ui/obfuscated_if_else.fixed
tests/ui/obfuscated_if_else.rs
tests/ui/obfuscated_if_else.stderr

An `if … { … } else { … }` used as the left operand of a binary expression requires parentheses to be parsed as an expression.
Fix #11141
changelog: [`obfuscated_if_else`]: fix bug in suggestion by issuing required parentheses around the left side of a binary expression

Fix `obfuscated_if_else` suggestion on left side of a binary expr

---

clippy_lints/src/matches/manual_utils.rs
clippy_utils/src/lib.rs
tests/ui/manual_map_option.fixed
tests/ui/manual_map_option.rs
tests/ui/manual_map_option.stderr
tests/ui/manual_map_option_2.fixed
tests/ui/manual_map_option_2.rs
tests/ui/manual_map_option_2.stderr

fixes: #12659 
[`manual_map`] and [`manual_filter`] shares the same check logic, but this issue doesn't seems like it could affect `manual_filter` (?)
---
changelog: make [`manual_map`] ignore types that contain `dyn`

make [`manual_map`] ignore types that contain `dyn`

---

CHANGELOG.md
clippy_lints/src/declared_lints.rs
clippy_lints/src/lib.rs
clippy_lints/src/single_option_map.rs
tests/ui/single_option_map.rs
tests/ui/single_option_map.stderr

Checks for functions with method calls to `.map(_)` on an arg of type `Option` as the outermost expression.
Fixes #774 
```
changelog: [`single_option_map`]: Checks for functions with method calls to `.map(_)` on an arg of type `Option` as the outermost expression.
```

Add `single_option_map` lint

---

clippy_lints/src/matches/significant_drop_in_scrutinee.rs
clippy_lints/src/returns.rs
tests/ui/let_and_return.edition2021.fixed
tests/ui/let_and_return.edition2021.stderr
tests/ui/let_and_return.edition2024.fixed
tests/ui/let_and_return.edition2024.stderr
tests/ui/let_and_return.fixed
tests/ui/let_and_return.rs

The first commit fixes #14164 by making sure that temporaries with non-static references are also looked for in expressions coming from expansion. The shortcut that was done skipped those parts and reported an absence of short-lived temporaries, which was incorrect.
The second commit distinguishes between edition 2024 and earlier ones. Starting from edition 2024, the problematic drop order has been fixed, and block variables, which might be referenced in a block expression, are freed after the block expression itself. This allows more `let_and_return` cases to be reported starting with edition 2024, whereas in earlier editions an intermediary variable was necessary to reorder the drops.
Incidentally, since Clippy is compiled in edition 2024 mode, the second commit has led to a fix in …

Fix `let_and_return` with temporary variables, and distinguish between Rust editions

---

book/src/lint_configuration.md
clippy_config/src/conf.rs

The `needless_raw_string_hashes` lint was implemented in #10884. However, the name originally considered might have been `unnecessary_raw_string_hashes`, so this part refers to a non-existent lint.
r? flip1995

correct "Affected lints" for `allow-one-hash-in-raw-strings`

---

clippy_lints/src/methods/or_fun_call.rs
clippy_utils/src/lib.rs
tests/ui/derivable_impls.fixed
tests/ui/derivable_impls.rs
tests/ui/derivable_impls.stderr
tests/ui/mem_replace.fixed
tests/ui/mem_replace.rs
tests/ui/mem_replace.stderr

When looking for `Default` impls that could be derived, we look at the body of their `fn default()` and if it is an fn call or literal we check if they are equivalent to what `#[derive(Default)]` would have used.
Now, when checking those fn calls in the `fn default()` body, we also compare against the corresponding type's `Default::default` body to see if our call is equivalent to that one.
For example, given
```rust
struct S;
impl S {
fn new() -> S { S }
}
impl Default for S {
fn default() -> S { S::new() }
}
```
`<S as Default>::default()` and `S::new()` are considered equivalent. Given that, if the user also writes
```rust
struct R {
s: S,
}
impl Default for R {
fn default() -> R {
R { s: S::new() }
}
}
```
the `derivable_impls` lint will now trigger.
changelog: [`derivable_impls`]: …

Use MIR body to identify more "default equivalent" calls for `derivable_impls`

---

clippy_dev/src/fmt.rs
clippy_lints/src/non_expressive_names.rs
tests/ui/syntax-error-recovery/non_expressive_names_error_recovery.fixed
tests/ui/syntax-error-recovery/non_expressive_names_error_recovery.rs
tests/ui/syntax-error-recovery/non_expressive_names_error_recovery.stderr

Fixes #12302
changelog: [`just_underscores_and_digits`]: fix false positive in error recovery scenario

just_underscores_and_digits: fix false positive in error recovery scenario

---

CHANGELOG.md
book/src/lint_configuration.md
clippy_config/src/conf.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/unwrap_expect_used.rs
tests/ui-toml/expect_used/clippy.toml
tests/ui-toml/expect_used/expect_used.rs
tests/ui-toml/expect_used/expect_used.stderr
tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
tests/ui-toml/unwrap_used/clippy.toml
tests/ui-toml/unwrap_used/unwrap_used_const.rs
tests/ui-toml/unwrap_used/unwrap_used_const.stderr
tests/ui/unwrap_expect_used.rs

By default, do not lint `.unwrap()` and `.expect(…)` in always const contexts, as a failure would be detected at compile time anyway.
New options `allow_expect_in_consts` and `allow_unwrap_in_consts`, defaulting to `true`, can be turned unset to still lint in always const contexts.
Close #14198
changelog: [`unwrap_used`, `expect_used`]: add new option to lint in always constant contexts

`{expect,unwrap}_used`: add options to lint at compilation time

---

CHANGELOG.md
clippy_lints/src/declared_lints.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/unbuffered_bytes.rs
clippy_utils/src/paths.rs
tests/ui/bytes_count_to_len.fixed
tests/ui/bytes_count_to_len.rs
tests/ui/unbuffered_bytes.rs
tests/ui/unbuffered_bytes.stderr

Checks for `Read::bytes()` on an unbuffered Read type.
The default implementation calls `read` for each byte, which can be very inefficient for data that’s not in memory, such as `File`.
Considerations which I'd like to have feedback on:
* Currently this lint triggers when `.bytes()` is called on any type that implements `std::io::Read` but not `std::io::BufRead`. This is quite aggressive and in and may result in false positives. Alternatives:
* Only trigger on concrete types, not generic types. This does mean that cases where a function is generic over a `R: Read` and calls `.bytes()` are not caught by the lint, which could be quite a nasty case of this bug.
* Only trigger on an allowlist of stdlib types
* Compromise: Is it possible to make this lint `pedantic` on types that are not on a …

New lint: `unbuffered_bytes`

---

clippy_lints/src/loops/manual_slice_fill.rs
tests/ui/manual_slice_fill.fixed
tests/ui/manual_slice_fill.rs

fix #14192 
changelog: [`manual_slice_fill`]: resolve FP caused by missing index checks for the slice

add index checks for the slice in `manual_slice_fill`

---

Cargo.toml
rustc_tools_util/Cargo.toml
rustc_tools_util/README.md
rustc_tools_util/src/lib.rs
tests/versioncheck.rs

changelog: Fix rustc_tools_util's `version.host_compiler` release channel, expose the rustc version, and add tests.
Previously the host_compiler would be set to "nighly" on the stable channel. Generally, the field felt a bit neglected neither being printed not tested.

Fix rustc_tools_util's `version.host_compiler` release channel, expose the rustc version, and add tests

---

CHANGELOG.md
clippy_lints/src/declared_lints.rs
clippy_lints/src/doc/mod.rs
tests/ui/doc/link_adjacent.fixed
tests/ui/doc/link_adjacent.rs
tests/ui/doc/link_adjacent.stderr

This is the lint described at https://github.com/rust-lang/rust/pull/136308#issuecomment-2625485331 that recommends using HTML to nest links inside code.
changelog: [`doc_link_code`]: warn when a link with code and a code span are back-to-back

doc_link_code: add check for links with code spans that render weird

---

Cargo.toml
rustc_tools_util/Cargo.toml
rustc_tools_util/README.md
rustc_tools_util/src/lib.rs

Between the release of v0.4.0 and v0.4.1 the edition was pushed to 2024 by https://github.com/rust-lang/rust-clippy/commit/a4805ff61049d746b8193ba125af525d9d6165fa
changelog: Use edition=2021 in `rustc_tools_util`

Make rust_tools_util package compatible with current stable by lowering rust edition to 2021.

---

clippy_lints/src/methods/unnecessary_map_or.rs
tests/ui/unnecessary_map_or.fixed
tests/ui/unnecessary_map_or.rs
tests/ui/unnecessary_map_or.stderr

Fix #14201
changelog: [`unnecessary_map_or`]: do not consume the comparison value if it does not implement `Copy`

`unnecessary_map_or`: do not consume the comparison value if it does not implement `Copy`

---

clippy_lints/src/misc.rs
tests/ui/used_underscore_items.rs

Fix `used_underscore_items` lint uses of foreign functions

---

CHANGELOG.md
clippy_lints/src/booleans.rs
clippy_lints/src/casts/cast_sign_loss.rs
clippy_lints/src/declared_lints.rs
clippy_lints/src/methods/manual_contains.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/size_of_in_element_count.rs
tests/ui/manual_contains.fixed
tests/ui/manual_contains.rs
tests/ui/manual_contains.stderr
tests/ui/needless_collect.fixed
tests/ui/needless_collect.rs
tests/ui/needless_collect.stderr
tests/ui/search_is_some_fixable_none.fixed
tests/ui/search_is_some_fixable_none.rs
tests/ui/search_is_some_fixable_some.fixed
tests/ui/search_is_some_fixable_some.rs

close #13353
Using `contains()` for slices are more efficient than using `iter().any()`.
changelog: [`manual_contains`]: new lint

new lint: `manual_contains`

---

clippy_dev/src/dogfood.rs
clippy_dev/src/main.rs

Some developers might prefer to use alternate VCS, such as Jujutsu, which are not detected by `cargo fix`. This forwards the `--allow-no-vcs` command line argument to `cargo fix`.

Add `--allow-no-vcs` to `cargo dev dogfood --fix`

---

clippy_dev/src/main.rs
clippy_dev/src/setup/toolchain.rs

Allows creating a toolchain that's independent of the local build, for example to make two separate toolchains with slight differences without requiring two checkouts of clippy

Add `cargo dev setup toolchain --standalone`

---

clippy_lints/src/matches/manual_ok_err.rs
tests/ui/manual_ok_err.fixed
tests/ui/manual_ok_err.rs
tests/ui/manual_ok_err.stderr

If the part being replaced is an `if` expression following an `else`, the replacement expression must be blockified.
Fix #14239
changelog: [`manual_ok_err`]: fix replacement expression if it follows an `else`

`manual_ok_err`: blockify the replacement of an `else if …`

---

clippy_lints/src/as_conversions.rs

This lint was renamed in 50da77521e922f17735b9d97461925ca0f3dec1c.
While I'm here convert the list of separate lints into a proper list for
ease of use.

Update mention of `ref_to_mut` to `invalid_reference_casting`

---

clippy_utils/src/lib.rs
tests/ui/needless_option_as_deref.fixed
tests/ui/needless_option_as_deref.rs

fixes #14148
Another case of #13077 and #8646  
changelog: [`needless_option_as_deref`]: fix FP in trait

fix: `needless_option_as_deref` FP in trait

---

clippy_lints/src/lib.rs

It seems as if `#![feature(binary_heap_into_iter_sorted)]` is not required anymore.

remove an unneeded `#![feature]`

---

book/src/development/adding_lints.md
book/src/development/writing_tests.md

Since `rustfix` was moved to `@rust-lang/cargo`, the old link may be confusing for readers.
r? flip1995

update `rustfix` link in docs

---

clippy_lints/src/methods/double_ended_iterator_last.rs
clippy_lints/src/unnecessary_struct_initialization.rs
clippy_utils/src/lib.rs
tests/ui/double_ended_iterator_last.fixed
tests/ui/double_ended_iterator_last.rs
tests/ui/double_ended_iterator_last.stderr
tests/ui/double_ended_iterator_last_unfixable.rs
tests/ui/double_ended_iterator_last_unfixable.stderr

In the case where `iter` is a `DoubleEndedIterator`, replacing a call to `iter.last()` (which consumes `iter`) by `iter.next_back()` (which requires a mutable reference to `iter`) cannot be done when `iter` is a non-mutable binding which is not a mutable reference. When possible, a local immutable binding is made into a mutable one.
Also, the applicability is switched to `MaybeIncorrect` and a note is added to the output when the element types have a significant drop, because the drop order will potentially be modified because `.next_back()` does not consume the iterator nor the elements before the last one.
Fix #14139
changelog: [`double_ended_iterator_last`]: do not trigger on non-reference immutable receiver, and warn about possible drop order change

`.last()` to `.next_back()` requires a mutable receiver

---

clippy_lints/src/entry.rs
tests/ui/entry.fixed
tests/ui/entry.rs

fixes #13934 
I modified the part for checking if the map is used so that it can check field and index exprs.
changelog: [`map_entry`]: fix FP on struct member

fix: `map_entry` FP on struct member

---

CHANGELOG.md
clippy_lints/src/attrs/mod.rs
clippy_lints/src/casts/mod.rs
clippy_lints/src/doc/mod.rs

Roses are red,
Biolets are blue,
A typo happened,
too late now
You might be asking,
what are Biolets now?
And to be honest,
I have no clue
---
The cat of this release is `Vera` nominated by @and-reas-se
---

Changelog for Clippy 1.85 🦜

---

CHANGELOG.md
book/src/lint_configuration.md
clippy_config/src/conf.rs
clippy_lints/src/declared_lints.rs
clippy_lints/src/types/mod.rs
clippy_lints/src/types/owned_cow.rs
tests/ui/owned_cow.fixed
tests/ui/owned_cow.rs
tests/ui/owned_cow.stderr
tests/ui/unnecessary_to_owned.fixed
tests/ui/unnecessary_to_owned.rs
tests/ui/unnecessary_to_owned.stderr

Closes #13697.
---
changelog: add [`owned_cow`] lint

add `owned_cow` lint

---

clippy_lints/src/methods/unbuffered_bytes.rs

The `IoBufRead` diagnostic has been added during the latest rustup.

Remove obsolete comment and simplify code

---

clippy_lints/src/methods/useless_asref.rs
tests/ui/useless_asref.fixed
tests/ui/useless_asref.rs
tests/ui/useless_asref.stderr

fixes #12357 
changelog: [`useless_asref`]: don't suggest to use `.clone()` if the target type doesn't implement the `Clone` trait

`useless_asref`: add a check for `Clone` before suggesting the use of `.clone()`

---

clippy_lints/src/loops/manual_slice_fill.rs
tests/ui/manual_slice_fill.fixed
tests/ui/manual_slice_fill.rs

```rust
let mut tmp = vec![1, 2, 3];
for b in &mut tmp {
*b = !*b;
}
```
must not suggest the invalid `tmp.fill(!*b)`.
In addition, there is another commit which cleans up two function calls with no effect. 
Fix #14189
changelog: [`manual_slice_fill`]: ensure that the initialization expression doesn't reference the iterator

`manual_slice_fill`: do not initialize from the iterator

---

book/src/lint_configuration.md
clippy_config/src/conf.rs
clippy_lints/src/lib.rs
clippy_lints/src/repeat_vec_with_capacity.rs
tests/ui/repeat_vec_with_capacity.fixed
tests/ui/repeat_vec_with_capacity.rs

changelog: [`repeat_vec_with_capacity`]: add MSRV check

add MSRV check for `repeat_vec_with_capacity`

---

clippy_lints/src/doc/too_long_first_doc_paragraph.rs
tests/ui/too_long_first_doc_paragraph.rs
tests/ui/too_long_first_doc_paragraph.stderr

Fixes #14274
changelog: [`too_long_first_doc_paragraph`]: fix wrong suggestion when first line too long

fix: `too_long_first_doc_paragraph` suggests wrongly when first line too long

---

clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/obfuscated_if_else.rs
tests/ui/obfuscated_if_else.fixed
tests/ui/obfuscated_if_else.rs
tests/ui/obfuscated_if_else.stderr

These method chains can be expressed concisely with `if`/`else`.
changelog: [`obfuscated_if_else`]: support `then().unwrap_or_else()` and `then_some().unwrap_or_else()`

extend `obfuscated_if_else` to support `{then(), then_some()}.unwrap_or_else()`

---

clippy_utils/src/macros.rs

For some reason, the `todo!` and `unimplemented!` macros were not included in the list of format-supporting macros list. Since they seem to behave exactly the same as all others like `write!` and `assert!`, adding them now.
I wonder if we should delete the `FORMAT_MACRO_DIAG_ITEMS`, and instead tag all macros with the `#[clippy::format_args]`?
changelog: all format-handling lints will now validate `todo!` and `unimplemented!` macros.

Add `todo!` & `unimplemented!` to format macros list

---

clippy_lints/src/manual_strip.rs
tests/ui/manual_strip.rs
tests/ui/manual_strip.stderr
tests/ui/manual_strip_fixable.fixed
tests/ui/manual_strip_fixable.rs
tests/ui/manual_strip_fixable.stderr

When the manually stripped entity receives a name as the first use through a simple `let` statement, this name can be used in the generated `if let Some(…)` expression instead of a placeholder.
Fix #14183 
changelog: [`manual_strip`]: reuse existing identifier in suggestion when possible

`manual_strip`: use existing identifier instead of placeholder

---

CHANGELOG.md
clippy_lints/src/declared_lints.rs
clippy_lints/src/lifetimes.rs
tests/ui/crashes/elidable_lifetime_names_impl_trait.fixed
tests/ui/crashes/elidable_lifetime_names_impl_trait.rs
tests/ui/crashes/elidable_lifetime_names_impl_trait.stderr
tests/ui/elidable_lifetime_names.fixed
tests/ui/elidable_lifetime_names.rs
tests/ui/elidable_lifetime_names.stderr
tests/ui/methods.rs
tests/ui/methods.stderr
tests/ui/needless_lifetimes.fixed
tests/ui/needless_lifetimes.rs
tests/ui/needless_lifetimes.stderr

Fixes https://github.com/rust-lang/rust-clippy/issues/13514
changelog: Added [`elidable_lifetime_names`] to `pedantic` (Split off from [`needless_lifetime`] for suggestions with `'_`)
[#13960](https://github.com/rust-lang/rust-clippy/pull/13960)
changelog: Enhancement: [`needless_lifetime`] No longer lints for elidable lifetimes `'_`, use [`elidable_lifetime_names`] to lint these.
[#13960](https://github.com/rust-lang/rust-clippy/pull/13960)

Split `needless_lifetime` `'_` suggestions into `elidable_lifetime_names`

---

clippy_lints/src/doc/mod.rs
tests/ui/doc/doc_nested_refdef_list_item.fixed
tests/ui/doc/doc_nested_refdef_list_item.rs
tests/ui/doc/doc_nested_refdef_list_item.stderr

The `looks_like_refdef` function was assuming the range was valid, this just adds a check to ensure that is the case. It also works around a subtraction underflow due to the same invalid range.
changelog: [`doc_nested_refdefs`]: Fix #14287 by avoiding invalid ranges

fix: Avoid ICE in `doc_nested_refdefs` check by checking range

---

clippy_lints/src/macro_use.rs
tests/ui/crashes/ice-14303.rs

It is not possible to write a declarative macro, that produces an attribute w/o
an item attached to it. This means that the `check_item` will already insert the
span in the map, if it came from an expansion. So additionally checking if the
macro came from an expansion doesn't add anything here. So the
`check_attribute` function, and with that the problematic `attr.span()` call can
be completely removed.
Fixes https://github.com/rust-lang/rust-clippy/issues/14303
r? @y21 
cc @jdonszelmann 
changelog: Fix ICE in [`macro_use_import`] lint

macro_use_import: Don't check is attribute comes from expansion

---

CHANGELOG.md
book/src/lint_configuration.md
clippy_config/src/conf.rs
clippy_lints/src/declared_lints.rs
clippy_lints/src/operators/manual_midpoint.rs
clippy_lints/src/operators/mod.rs
clippy_utils/src/lib.rs
clippy_utils/src/msrvs.rs
tests/ui/manual_midpoint.fixed
tests/ui/manual_midpoint.rs
tests/ui/manual_midpoint.stderr
tests/ui/option_if_let_else.fixed
tests/ui/option_if_let_else.rs
tests/ui/option_if_let_else.stderr
tests/ui/suspicious_operation_groupings.fixed
tests/ui/suspicious_operation_groupings.rs

changelog: [`manual_midpoint`]: new lint
Closes #13849

New lint: `manual_midpoint`

---

clippy_utils/src/lib.rs
tests/ui/crashes/ice-14325.rs

node_args doesn't work with struct literals and expr_ty must be used instead
r? @y21 
(No changelog, as this ICE didn't make it to the Rust repo, as it was caught during the sync)
Fixes #14325

Fix ICE in manual_map lint

---

clippy_lints/src/doc/mod.rs
clippy_lints/src/implicit_saturating_sub.rs
tests/ui/implicit_saturating_sub.fixed
tests/ui/implicit_saturating_sub.rs
tests/ui/implicit_saturating_sub.stderr
tests/ui/manual_arithmetic_check-2.rs
tests/ui/manual_arithmetic_check-2.stderr

changelog: [`implicit_saturating_sub`, `inverted_saturating_sub`]: extend lints from local variables to side-effect free expressions
Noticed when #14308 introduced an implicit `saturating_sub` operation and didn't get tagged.

Extend `{implicit,inverted}_saturating_sub` to expressions

---

clippy_utils/src/diagnostics.rs

Using `#[allow]` will also apply to child HIR nodes, while `#[expect]` will ensure that the proper HIR node has been used for positioning the lint.

Suggest using `#[expect]` to check lint positioning

---

clippy_lints/src/comparison_chain.rs
tests/ui/crashes/if_same_then_else.rs
tests/ui/ifs_same_cond.rs
tests/ui/ifs_same_cond.stderr
tests/ui/same_functions_in_if_condition.rs
tests/ui/same_functions_in_if_condition.stderr

The `comparison_chain` lint might suggest code which seems less natural to beginners.
[Discussion](https://rust-lang.zulipchat.com/#narrow/channel/257328-clippy/topic/demote.20some.20lints.20to.20.60pedantic.60)
changelog: [`comparison_chain`]: change lint category to `pedantic`

`comparison_chain`: `style` → `pedantic`

---

clippy_lints/src/undocumented_unsafe_blocks.rs
tests/ui-toml/undocumented_unsafe_blocks/undocumented_unsafe_blocks.default.stderr
tests/ui-toml/undocumented_unsafe_blocks/undocumented_unsafe_blocks.disabled.stderr
tests/ui-toml/undocumented_unsafe_blocks/undocumented_unsafe_blocks.rs

fixes #11709
Continuation of #12672. r? @Alexendoo if you don't mind?
changelog: [`undocumented_unsafe_blocks`] fix FP on trait/impl items

fix: `undocumented_unsafe_blocks` FP on trait/impl items

---

clippy_lints/src/entry.rs
tests/ui/entry_unfixable.rs
tests/ui/entry_unfixable.stderr

Closes #13306
Closes #9925 
Closes #9470 
Closes #9305 
Clippy gives wrong suggestions when the key is not `Copy`. As suggested in #9925, in such cases Clippy will simply warn but no fix.
changelog: [`map_entry`]: fix wrong suggestions when key is not `Copy`

fix: `map_entry` suggest wrongly when key is not `Copy`

---

clippy_lints/src/methods/needless_collect.rs
tests/ui/needless_collect.fixed
tests/ui/needless_collect.rs

changelog: [`needless_collect`]: avoid warning if non-`Iterator` methods are called on the result of `into_iter`
Fixes #13430

needless_collect: avoid warning if non-iterator methods are used

---

clippy_lints/src/misc_early/mixed_case_hex_literals.rs
tests/ui/literals.rs
tests/ui/literals.stderr

It can be error-prone for developers to manually change literals with mixed uppercase and lowercase letters into consistently all-lowercase or all-uppercase literals. Therefore, this lint rule should suggest alternative literals.
changelog: [`mixed_case_hex_literals`]: add alternative suggestions

better help for `mixed_case_hex_literals`

---

clippy_lints/src/format_args.rs
tests/ui/unnecessary_path_debug_formatting.rs

close #14345 
changelog: [`unnecessary_debug_formatting`]: don't lint in tests

don't trigger `unnecessary_debug_formatting` in tests

---

clippy_lints/src/methods/io_other_error.rs
tests/ui/io_other_error.fixed
tests/ui/io_other_error.rs
tests/ui/io_other_error.stderr

Since the error kind (`io::ErrorKind::other`) is in the root context, the error message must be found in the root context as well to compute the correct span to remove.
Fix #14346 
changelog: [`io_error_other`]: fix non-applicable suggestion
r? @llogiq

Walk back to the root context to compute the span

---

clippy_lints/src/types/mod.rs

Remove Known problems section for `vec_box` since [issue](https://github.com/rust-lang/rust-clippy/issues/3530#issuecomment-446058452)
> Vec<Box<T: Sized>> makes sense if T is a large type 
can be handled 
> The lint already checks that the type's size is lower than a threshold to avoid linting on large types. 

Remove Known problems section for `vec_box`

---

clippy_lints/src/manual_bits.rs
clippy_lints/src/manual_slice_size_calculation.rs
clippy_lints/src/size_of_in_element_count.rs
clippy_lints/src/size_of_ref.rs
tests/ui/manual_bits.stderr
tests/ui/size_of_ref.stderr

Use `std::mem::{size_of, size_of_val, align_of, align_of_val}` from the prelude instead of importing or qualifying them.
These functions were added to all preludes in Rust 1.80.

Use `size_of` from the prelude instead of imported

---

clippy_lints/src/item_name_repetitions.rs
tests/ui/struct_fields.rs
tests/ui/struct_fields.stderr

Currently, If a struct is `pub` and its field is private, and `avoid-breaking-exported-api = true` (default), then `struct_field_names` will not lint the field, even though changing the field’s name is not a breaking change. This is because the breaking-exported-api condition was checking the visibility of the struct, not its fields (perhaps because the same code was used for enums). With this change, Clippy will check the field’s effective visibility only.
Note: This change is large because some functions were moved into an `impl` to be able to access more configuration. Consider viewing the diff with whitespace ignored.
changelog: [`struct_field_names`]: also check private fields of public structs

Make `struct_field_names` check private fields of public structs.

---

clippy_lints/src/casts/borrow_as_ptr.rs
clippy_lints/src/methods/unnecessary_to_owned.rs
clippy_utils/src/lib.rs
tests/ui/unnecessary_to_owned.fixed
tests/ui/unnecessary_to_owned.rs
tests/ui/unnecessary_to_owned.stderr

fix #14242 
changelog: [`unnecessary_to_owned`]: don't call `iter` on a temporary object

`unnecessary_to_owned`: don't call `iter()` on a temporary object

---

clippy_lints/src/excessive_bools.rs

Adds the reasoning to the docs for this rule on why enums are generally better for representing state machines than structs with  many bool fields.
changelog: [struct_excessive_bools]: Improve documentation

docs: update rationale for excessive-bools

---

clippy_lints/src/manual_let_else.rs
tests/ui/manual_let_else.rs
tests/ui/manual_let_else.stderr

fixes #13768 
The existing implemention forgets to handle the binding mode (i.e. `ref` and `ref mut`), so I just modified it to cover these cases.
changelog: [`manual_let_else`]: fix missing binding mode

fix: `manual_let_else` missing binding mode

---

clippy_lints/src/blocks_in_conditions.rs
tests/ui/blocks_in_conditions.fixed
tests/ui/blocks_in_conditions.rs

fixes #9911
changelog: [`blocks_in_conditions`]: don't trigger the lint when the condition contains a `return`

don't trigger `blocks_in_conditions` when the condition contains a `return`

---

util/gh-pages/index_template.html

Currently, some parts of the [website](https://rust-lang.github.io/rust-clippy/master/index.html)'s CSS are not being applied. This seems to be due to a broken link to the originally referenced CSS. I suspect https://github.com/rust-lang/mdBook/pull/1368.

fix broken theme CSS links in the website

---

lintcheck/src/json.rs

Add top-level documentation comments to improve code readability and maintainability in the json.rs module.
- Add module-level documentation describing JSON serialization and diff functionality
- Document LintJson struct
- Add function-level documentation to explain purpose and behavior
- Document missing constants and structs

docs: Add documentation to json.rs module

---

clippy_lints/src/undocumented_unsafe_blocks.rs
tests/ui-toml/undocumented_unsafe_blocks/undocumented_unsafe_blocks.default.stderr
tests/ui-toml/undocumented_unsafe_blocks/undocumented_unsafe_blocks.disabled.stderr
tests/ui-toml/undocumented_unsafe_blocks/undocumented_unsafe_blocks.rs

Closes #13039
changelog: [`unnecessary_safety_comment`]: fix FP on desugared assign

fix: `unnecessary_safety_comment` FP on desugared assign

---

Cargo.toml
clippy_lints/src/utils/internal_lints/produce_ice.rs
tests/compile-test.rs
tests/lint_message_convention.rs
tests/ui-internal/custom_ice_message.rs
tests/ui-internal/custom_ice_message.stderr

Last part of https://github.com/rust-lang/rust-clippy/pull/11421.
Now all ui tests require annotations.
The change in `ui_test` is to add `ICE:` errors.
changelog: Make internals ui tests annotations mandatory
r? @flip1995

Make annotations mandatory for internal ui tests

---

clippy_lints/src/needless_pass_by_value.rs
clippy_utils/src/lib.rs
tests/ui/crashes/needless_pass_by_value-w-late-bound.stderr
tests/ui/needless_pass_by_value.rs
tests/ui/needless_pass_by_value.stderr

If types such as `Option<Option<String>>` are not used by value, then `Option<Option<&String>>` will be suggested, instead of `Option<&Option<String>>`.
changelog: [`needless_pass_by_value`]: suggest using a reference on the innermost `Option` content
fix #14375

`needless_pass_by_value`: reference the innermost `Option` content

---

clippy_lints/src/incompatible_msrv.rs
tests/ui/incompatible_msrv.rs
tests/ui/incompatible_msrv.stderr

The lint for function calls was previously restricted to functions taking exactly one argument. This was not documented.
Generalizing the lint to an arbitrary number of arguments in the function call requires special casing some macro expansions from the standard library. Macros such as `panic!()` or `assert_eq!()` exist since Rust 1.0.0, but modern stdlib expand those macros into calls to functions introduced in later Rust versions. While it is desirable to lint code inside macros, using MSRV-incompatible functions coming from `core` in macro expansions has been special-cased to not trigger this lint.
Also, code coming from compiler desugaring may contain function calls (for example, `a..=b` is now desugared into `RangeInclusive::new(a, b)`. Those should not be linted either as the …

`incompatible_msrv`: lint function calls with any argument count

---

clippy_lints/src/from_over_into.rs
tests/ui/from_over_into.fixed
tests/ui/from_over_into.rs
tests/ui/from_over_into.stderr

fixes [#112502](https://github.com/rust-lang/rust/issues/112502)
changelog: [`from_over_into`]: fix invalid code suggestion when self parameter has type annotation

Fix `from_over_into` lint suggesting invalid code

---

clippy_utils/src/lib.rs
tests/ui/needless_return.fixed
tests/ui/needless_return.rs
tests/ui/needless_return.stderr

close #12157 
`needless_return` sometimes makes incorrect suggestions by omitting necessary enclosing parentheses. This PR resolves the issue by using `clippy_utils::sugg::Sugg`.
changelog: [`needless_return`]: now makes correct suggestions which require enclosing parentheses

fix incorrect suggestions related to parentheses in `needless_return`

---

clippy_lints/src/question_mark.rs
tests/ui/question_mark.fixed
tests/ui/question_mark.rs
tests/ui/question_mark.stderr

changelog: [`question_mark`]: avoid incorrect suggestion when `ref` binding used
Fixes #13417

question_mark: avoid incorrect suggestion when `ref` binding used

---

clippy_lints/src/strings.rs
tests/ui/string_to_string.rs
tests/ui/string_to_string.stderr
tests/ui/string_to_string_in_map.fixed
tests/ui/string_to_string_in_map.rs
tests/ui/string_to_string_in_map.stderr

Fixes https://github.com/rust-lang/rust-clippy/issues/14175.
There are two "big" cases to handle: `.map(|x| x.to_string())` and `.map(String::to_string)`. If the closure has more than one expression, we should not suggest `.cloned()`.
changelog: Improve `string_to_string` lint in case it is in a map call
r? @samueltardieu

Improve `string_to_string` lint in case it is in a map call

---

clippy_lints/src/matches/mod.rs
clippy_lints/src/matches/single_match.rs
tests/ui/single_match.fixed
tests/ui/single_match.rs
tests/ui/single_match.stderr
tests/ui/single_match_else.fixed
tests/ui/single_match_else.rs
tests/ui/single_match_else.stderr

Commit efe3fe9b8c5f16bbf39af7415bbde9441bc54dbb removed the ability for `single_match` and `single_match_else` to trigger if comments were present outside of the arms, as those comments would be lost while rewriting the `match` expression.
This reinstates the lint, but prevents the suggestion from being applied automatically in the presence of comments by using the `MaybeIncorrect` applicability. Also, a note is added to the lint message to warn the user about the need to preserve the comments if acting upon the suggestion.
changelog: [`single_match`, `single_match_else`]: reinstate lint when comments are inside the `match` but do not autofix the code
Fix #14418

Reinstate `single_match`/`single_match_else` lints with comments

---

book/src/lint_configuration.md
clippy_config/src/conf.rs
clippy_lints/src/question_mark.rs
clippy_utils/src/msrvs.rs
tests/ui/question_mark.fixed
tests/ui/question_mark.rs
tests/ui/question_mark.stderr

changelog: [`question_mark`]: Now respects the [`msrv`] configuration

Add MSRV check for `question_mark`

---

clippy_lints/src/needless_late_init.rs
tests/ui/needless_late_init.fixed
tests/ui/needless_late_init.rs
tests/ui/needless_late_init.stderr

fixes #9895 
changelog: [`needless_late_init`]: correct suggestion when assignments have enclosing parentheses

fix suggestion for assignments have enclosing parentheses under `needless_late_init`

---

clippy_lints/src/loops/never_loop.rs
tests/ui/never_loop.rs
tests/ui/never_loop.stderr
tests/ui/never_loop_fixable.fixed
tests/ui/never_loop_fixable.rs
tests/ui/never_loop_fixable.stderr

The applicability of `never_loop` is currently set to `Unspecified`, but if the loop block does not contain `break` or `continue`, it can be `MachineApplicable`.
changelog: [`never_loop`]: the applicability is now `MachineApplicable` when the loop block contains neither `break` nor `continue`

make `never_loop` applicability more flexible

---

clippy_utils/src/qualify_min_const_fn.rs
tests/ui/missing_const_for_fn/cant_be_const.rs

Closes #14020
Closes #14290
Closes #14091 
Add checks for unstable const traits.
changelog: [`missing_const_for_fn`] fix FP on unstable const traits

fix: `missing_const_for_fn` FP on unstable const traits

---

clippy_lints/src/neg_multiply.rs
tests/ui/neg_multiply.fixed
tests/ui/neg_multiply.rs
tests/ui/neg_multiply.stderr

changelog: [`neg_multiply`]: lint float numbers as well

expand `neg_multiply` to lint float numbers as well

---

.github/workflows/lintcheck.yml
lintcheck/ci-config/clippy.toml

By default, lintcheck will use the `clippy.toml` file found at the toplevel of the repository (`CARGO_MANIFEST_DIR`). This file is meant for configuration of Clippy applied to Clippy sources.
This creates a new `lintcheck/ci-config/clippy.toml` file which is used by the CI when running lintcheck. By default this uses the default Clippy configuration.

Use a lintcheck specific Clippy configuration file in the CI

---

clippy_lints/src/loops/manual_find.rs
tests/ui/manual_find.rs

Closes #9521 
changelog: [`manual_find`]: fix wrong suggestions when early return

fix: `manual_find` suggests wrongly when early return

---

clippy_lints/src/borrow_deref_ref.rs
tests/ui/borrow_deref_ref.fixed
tests/ui/borrow_deref_ref.rs
tests/ui/borrow_deref_ref.stderr

Closes #11346.
Partially fix #9905. The first case in this issue is a little tricky as the coerce does not happen in the borrowing.
changelog: [`borrow_deref_ref`]: fix wrong suggestions when coerce to mut

fix: `borrow_deref_ref` suggests wrongly when coerce to mut

---

book/src/development/adding_lints.md
book/src/development/writing_tests.md

Fix missing comment annotations in the clippy book

Add comment annotations

---

clippy_lints/src/operators/op_ref.rs
tests/ui/op_ref.fixed
tests/ui/op_ref.rs

#2597 appears to be already resolved, so the applicability of `op_ref` can be set to `MachineApplicable`.
close #2597
changelog: [`op_ref`]: set the applicability to `MachineApplicable`

set the applicability of `op_ref` to `MachineApplicable`

---

clippy_lints/src/matches/collapsible_match.rs
tests/ui/collapsible_match.rs

Fixes https://github.com/rust-lang/rust-clippy/issues/14281

Emit `collapsible_match` at the right node

---

tests/ui/suspicious_doc_comments.fixed
tests/ui/suspicious_doc_comments.rs

Related to #14265 which was fixed automatically by the latest rustup.
*Edit: description, changelog, keep only tests*

Add regression tests for `suspicious_doc_comments`

---

CHANGELOG.md
clippy_lints/src/attrs/mod.rs
clippy_lints/src/declared_lints.rs
tests/ui/ignore_without_reason.rs
tests/ui/ignore_without_reason.stderr

Closes #13066 (tests that are ignored with no reason message).
changelog: Add `ignore_without_reason` lint

Add `ignore_without_reason` lint

---

book/src/SUMMARY.md
book/src/development/infrastructure/benchmarking.md
lintcheck/src/main.rs

In #14116 we added a benchmarking option for Lintcheck, this commit adds a new chapter to the book AND improves that option into a more usable state.
It's recommended to review one commit at a time.
- **Document how to benchmark with lintcheck --perf**
- **Several improvements on lintcheck perf (desc.)**
- Now lintcheck perf deletes target directory after benchmarking,
benchmarking with a cache isn't very useful or telling of any
precise outcome.
- Support for benchmarking several times without having to do
a cargo clean.
- Compress perf.data

Document and improve (a lot) lintcheck --perf

---

CHANGELOG.md
book/src/lint_configuration.md
clippy_config/src/conf.rs
clippy_lints/src/collapsible_if.rs
clippy_lints/src/lib.rs
tests/ui-toml/collapsible_if/clippy.toml
tests/ui-toml/collapsible_if/collapsible_if.fixed
tests/ui-toml/collapsible_if/collapsible_if.rs
tests/ui-toml/collapsible_if/collapsible_if.stderr
tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
tests/ui/collapsible_if.fixed
tests/ui/collapsible_if.rs
tests/ui/collapsible_if.stderr

Replace the use of `Sugg::ast()` which prevented combining `if` together when they contained comments by span manipulation.
A new configuration option `lint_commented_code`, which is `true` by default, allows opting out from this behavior.
If reviewed on GitHub, the second commit of this PR is best looked at side by side, with whitespace differences turned off.
changelog: [`collapsible_if`]: lint more cases

Lint more cases in `collapsible_if`

---

clippy_lints/src/booleans.rs
tests/ui/nonminimal_bool.rs
tests/ui/nonminimal_bool.stderr

Closes #14404 
changelog: [`nonminimal_bool`]: fix macro definition wrongly showed in suggestions.

fix: `nonminimal_bool` wrongly showed the macro definition

---

.github/workflows/deploy.yml
book/src/development/infrastructure/release.md

In the current GitHub Actions CI/CD setup, the `deploy` job is not triggered when a PR is enqueued in the merge queue but only when it is merged. Since concurrency is not configured for this job, deployments may fail for later PRs if multiple PRs are merged in quick succession. (e.g. the deployment for [this commit](https://github.com/rust-lang/rust-clippy/commit/c4187145180effa06c87295e44bdf135128866fe) was successful, but the deployment for [this commit](https://github.com/rust-lang/rust-clippy/commit/0a141ab7b882387528eac4140df67e9938e5d257) that was pushed to `main` immediately afterward failed. (edit: the latter deployment seems to be rerun))
r? flip1995

set concurrency for the `deploy` job

---

clippy_lints/src/unconditional_recursion.rs

Clarify example for unconditional_recursion

Clarify example for unconditional_recursion

---

clippy_lints/src/as_conversions.rs

Use `code` for references to other lints in as_conversions docs

---

CHANGELOG.md
book/src/lint_configuration.md
clippy.toml
clippy_config/src/conf.rs
clippy_lints/src/inconsistent_struct_constructor.rs
tests/ui-toml/toml_inconsistent_struct_constructor/clippy.toml
tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr

This PR does two things:
- It renames `inconsistent_struct_constructor`'s configuration from `lint-inconsistent-struct-field-initializers` to `check-inconsistent-struct-field-initializers`. (I should have suggested `check-...` in [#13737](https://github.com/rust-lang/rust-clippy/pull/13737#discussion_r1875118516).)
- It causes Clippy to no longer suggest deprecated configurations. (Previously, Clippy would suggest `cyclomatic-complexity-threshold`, for example.)
r? @y21
changelog: Rename `lint-inconsistent-struct-field-initializers` to `check-inconsistent-struct-field-initializers`
changelog: No longer suggest deprecated configurations

Rename `inconsistent_struct_constructor` configuration; don't suggest deprecated configurations

---

clippy_lints/src/methods/case_sensitive_file_extension_comparisons.rs
clippy_lints/src/methods/mod.rs
tests/ui/case_sensitive_file_extension_comparisons.fixed
tests/ui/case_sensitive_file_extension_comparisons.rs
tests/ui/case_sensitive_file_extension_comparisons.stderr

close #14357
changelog: [`case_sensitive_file_extension_comparisons`]: suggest `is_some_and` to suppress other lint warnings

suggest `is_some_and` instead of `map_or` in `case_sensitive_file_extension_comparions`

---

clippy.toml
clippy_lints/src/escape.rs
clippy_lints/src/item_name_repetitions.rs
clippy_lints/src/mem_replace.rs
clippy_lints/src/methods/map_clone.rs
clippy_lints/src/methods/seek_from_current.rs
clippy_lints/src/mixed_read_write_in_expression.rs
lintcheck/ci-config/clippy.toml
tests/clippy.toml

This PR enables the new ability to collapse `if` statements containing comments (without losing them) in Clippy sources, excluding tests and lintcheck, where the default behaviour (no collapsing in presence of comments) is preserved.
To be applied after #14231. When it is applied, #14455 will be marked as ready for review, then #14228 afterwards.
r? ghost

Apply collapsible if to Clippy sources

---

clippy_lints/src/attrs/repr_attributes.rs
clippy_lints/src/copies.rs
clippy_lints/src/methods/unnecessary_map_or.rs
clippy_lints/src/non_std_lazy_statics.rs
clippy_lints/src/shadow.rs
clippy_lints/src/zombie_processes.rs
clippy_utils/src/str_utils.rs
clippy_utils/src/ty/mod.rs
lintcheck/src/recursive.rs
tests/ui/non_std_lazy_static/non_std_lazy_static_fixable.fixed
tests/ui/non_std_lazy_static/non_std_lazy_static_fixable.rs
tests/ui/non_std_lazy_static/non_std_lazy_static_fixable.stderr
tests/ui/non_std_lazy_static/non_std_lazy_static_unfixable.rs
tests/ui/non_std_lazy_static/non_std_lazy_static_unfixable.stderr
tests/ui/repr_packed_without_abi.stderr

Fix various typos in lint messages, descriptions and comments

---

clippy_lints/src/option_if_let_else.rs
tests/ui/option_if_let_else.fixed
tests/ui/option_if_let_else.rs

Closes #11059
changelog: `option_if_let_else`: fix wrong suggestion when coersion requires explicit cast

fix: `option_if_let_else` suggests wrongly when coercion requires explicit cast

---

clippy_lints/src/operators/identity_op.rs
rustc_tools_util/src/lib.rs

remove redundant words in comment

chore: fix some comments

---

clippy_utils/src/source.rs
tests/ui-toml/collapsible_if/collapsible_if.fixed
tests/ui-toml/collapsible_if/collapsible_if.stderr
tests/ui/collapsible_if.fixed
tests/ui/collapsible_if.rs
tests/ui/collapsible_if.stderr
tests/ui/manual_inspect.fixed
tests/ui/manual_inspect.rs
tests/ui/manual_inspect.stderr

This extra condition prevents a problem when removing the '}' in:
```rust
( // There was an opening bracket after the parenthesis, which has been removed
// This is a comment
})
```
Removing the whitespaces, including the linefeed, before the '}', would put the closing parenthesis at the end of the `// This is a comment` line, which would make it part of the comment as well. In this case, it is best to keep the span on the '}' alone.
Note to reviewer: `manual_inspect` and `collapsible_if` were two lints exhibiting this problem in cooked up test cases, which have been included as non-regression tests.

Prevent including preceeding whitespaces if line contains non blanks

---

clippy_lints/src/operators/cmp_owned.rs
tests/ui/cmp_owned/with_suggestion.fixed
tests/ui/cmp_owned/with_suggestion.rs
tests/ui/cmp_owned/with_suggestion.stderr

Dereferencing string literals in suggestions is redundant.
changelog: [`cmp_owned`]: more natural suggestions are provided for string literals now
fixes #8103

more natural suggestions for `cmp_owned`

---

clippy_lints/src/methods/mod.rs

It looks like `ok_expect` already [checks](https://github.com/rust-lang/rust-clippy/blob/b27a2bbe26b5d4499ca71091e955e7bc7b8b1a4a/clippy_lints/src/methods/ok_expect.rs#L16) for the presence of the `Debug`.

remove obsolete "Known Problems" in `ok_expect`

---

clippy_lints/src/shadow.rs
tests/ui/shadow.rs

When lowering a destructuring assignment from AST to HIR, the compiler will reuse the same identifier name (namely `sym::lhs`) for all the fields. The desugaring must be checked for to avoid a false positive  of the `shadow_unrelated` lint.
Fix #10279
Fix #14377 
changelog: [`shadow_unrelated`]: prevent false positive in destructuring assignments

Do not warn about shadowing in a destructuring assigment

---

clippy_lints/src/methods/unnecessary_filter_map.rs
tests/ui/unnecessary_filter_map.rs
tests/ui/unnecessary_filter_map.stderr
tests/ui/unnecessary_find_map.rs
tests/ui/unnecessary_find_map.stderr

The `unnecessary_filter_map` and `unnecessary_find_map` lints were making partial suggestions, proposing to replace the whole expression by only the method name, or a subexpression which contained explicit placeholders.
Since even `MaybeIncorrect` suggestions must generate code that compiles, this changes those lints to recommandation lints with no code suggestion.
Fixes #14486
changelog: [`unnecessary_find_map`, `unnecessary_filter_map`]: do not make suggestions that will not compile

Do not make incomplete or invalid suggestions

---

clippy_lints/src/missing_const_for_fn.rs

The main reason for this is that we might transform MIR in the optimization passes in a way that doesn't work with const-eval, but it is irrelevant since const-eval uses another MIR (`mir_for_ctfe`).
Specifically this came up when adding a new check in debug builds (https://github.com/rust-lang/rust/pull/134424), which is added as part of an optimization pass.

Make missing_const_for_fn operate on non-optimized MIR

---

clippy_lints/src/unnested_or_patterns.rs
tests/ui/unnested_or_patterns.fixed
tests/ui/unnested_or_patterns.rs
tests/ui/unnested_or_patterns.stderr

Closes #9952
changelog: [`unnested_or_patterns`] fix wrong suggestion in `let`

fix: `unnested_or_patterns` suggests wrongly in `let`

---

.github/workflows/clippy_changelog.yml

I sometimes run lintcheck/CI experiments by opening a PR on my own clippy fork. This has recently "stopped" working (as in, fails CI) when the changelog CI was added because the repository is hardcoded as "rust-lang/rust-clippy", where the PR number won't match with the one on my repo.
r? flip1995

Don't hardcode repository in changelog CI

---

clippy_lints/src/derivable_impls.rs
clippy_lints/src/derive.rs
clippy_lints/src/missing_fields_in_debug.rs
clippy_lints/src/partialeq_ne_impl.rs
clippy_lints/src/unconditional_recursion.rs

`has_attr(def_id, sym::automatically_derived)` is as same as `is_automatically_derived(def_id)`.

use `is_automatically_derived()` instead of `has_attr()`

---

clippy_config/src/conf.rs

This is a small refactor of `ConfVisitor`'s `visit_map` method.
It adds comments and reduces `match` nesting by adding `continue` statements.
IMHO, the code is easier to read in this form. No one asked for this, so I hope the maintainers agree it is an improvement.

Make `visit_map` happy path more evident

---

clippy_lints/src/len_zero.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/obfuscated_if_else.rs
tests/ui/obfuscated_if_else.fixed
tests/ui/obfuscated_if_else.rs
tests/ui/obfuscated_if_else.stderr

These method chains can be expressed concisely with `if` / `else`.
changelog: [`obfuscated_if_else`]: support `then().unwrap_or_default()` and `then_some().unwrap_or_default()`

expand `obfuscated_if_else` to support `{then(), then_some()}.unwrap_or_default()`

---

clippy_lints/src/matches/single_match.rs
tests/ui/single_match.fixed
tests/ui/single_match.rs
tests/ui/single_match.stderr

Having a macro call as the scrutinee is supported. However, the proposed suggestion must use the macro call itself, not its expansion.
When the scrutinee is a macro call, do not complain about an irrefutable match, as the user may not be aware of the result of the macro. A comparaison will be suggested instead, as if we couldn't see the outcome of the macro.
Similarly, do not accept macro calls as arm patterns.
changelog: [`single_match`]: proper suggestions in presence of macros
Fixes #14493

Properly handle expansion in `single_match`

---

tests/compile-test.rs

Suggest `./x test src/tools/clippy --bless` when in `rust-lang/rust`

---

triagebot.toml

Since we migrated away from bors I've missed this feature, fortunately triagebot supports it too - https://forge.rust-lang.org/triagebot/merge-conflicts.html 
r? @flip1995

Enable triagebot's merge conflict notifications

---

clippy_lints/src/methods/mod.rs

correct version attribute for `io_other_error`

---

clippy_lints/src/redundant_pub_crate.rs
tests/ui/redundant_pub_crate.fixed
tests/ui/redundant_pub_crate.rs
tests/ui/redundant_pub_crate.stderr

Found this while reviewing PR https://github.com/rust-lang/rust/pull/138384: See https://github.com/rust-lang/rust/pull/138384#discussion_r1996111087 in which I suggested a FIXME to be added that I'm now fixing in this PR.
---
Before this PR, `redundant_pub_crate` computed a broken primary Span when flagging items (`hir::Item`s) that never bear a name (`ForeignMod`, `GlobalAsm`, `Impl`, `Use(UseKind::Glob)`, `Use(UseKind::ListStem)`). Namely, it created a span whose high byte index is `DUMMY_SP.hi()` which is quite broken (`DUMMY_SP` is synonymous with `0..0` wrt. the entire `SourceMap` meaning it points at the start of the very first source file in the `SourceMap`).
Why did this happen? Before PR https://github.com/rust-lang/rust/pull/138384, the offending line looked like `let span = …

Fix the primary span of `redundant_pub_crate` when flagging nameless items

---

.github/workflows/lintcheck.yml
lintcheck/ci_crates.toml

A discrepancy between the `cmake` version available on the runners and the one required by the `aws-lc-sys` dependency prevents the crate from building.
r? @flip1995  
cc @Alexendoo

Do not build `tokio-rustls` in the CI for the time being

---

clippy.toml
clippy_config/src/conf.rs
clippy_config/src/lib.rs
clippy_config/src/types.rs
clippy_lints/src/await_holding_invalid.rs
clippy_lints/src/disallowed_macros.rs
clippy_lints/src/disallowed_methods.rs
clippy_lints/src/disallowed_types.rs
tests/ui-toml/await_holding_invalid_type_with_replacement/await_holding_invalid_type.stderr
tests/ui-toml/toml_invalid_path/clippy.toml
tests/ui-toml/toml_invalid_path/conf_invalid_path.rs
tests/ui-toml/toml_invalid_path/conf_invalid_path.stderr

This PR resolves #11432 by checking that paths resolve in `disallowed_*` configurations.
It also does some lightweight validation of definition kinds. For example, only paths that resolve to `DefKind::Macro` definitions are allowed in `disallowed_macro` configurations.
~The PR is currently two commits. The first is #14376 (cc: @Jarcho), which I submitted just a few days ago. The second commit is everything else.~
Side note: For me, the most difficult part of this PR was getting the spans of the individual `DisallowedPath` configurations. There is some discussion at https://github.com/toml-rs/toml/discussions/840, if interested.
changelog:  validate paths in `disallowed_*` configurations

Validate paths in `disallowed_*` configurations

---

clippy_lints/src/manual_option_as_slice.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/non_std_lazy_statics.rs

r? @y21 
Completely forgot about the version update during CHANGELOG creation. I have to re-learn how to do all that.

Update versions of 1.86 lints

---

clippy_lints/src/missing_asserts_for_indexing.rs
tests/ui/missing_asserts_for_indexing.fixed
tests/ui/missing_asserts_for_indexing.rs
tests/ui/missing_asserts_for_indexing_unfixable.rs
tests/ui/missing_asserts_for_indexing_unfixable.stderr

This PR fixes issues with the `missing_asserts_for_indexing` lint.
- false positive when the first index is the highest(or equal) value in a list of indexes:
```rust
pub fn foo(slice: &[i32]) -> i32{
slice[1] * slice[0]
}
```
- false negative when an assert statement if found after the indexing operation.
```rust
pub fn bar(slice: &[i32]) -> i32 {
let product = slice[0] * slice[1];
assert!(slice.len() > 1);
product
}
```
examples: https://godbolt.org/z/s7Y47vKdE
closes: #14079
changelog: [`missing_asserts_for_indexing`]: ignore asserts found after indexing, and do not require asserts if the first index is highest.

Fixes for `missing_asserts_for_indexing`

---

triagebot.toml

This PR enables to the canonicalization of issue links in triagebot.
Documentation pending at https://github.com/rust-lang/rust-forge/pull/825
changelog: add `[canonicalize-issue-links]` in `triagebot.toml`

Enable canonicalization of issue links in triagebot

---

clippy_lints/src/ptr.rs
tests/ui/ptr_eq.fixed
tests/ui/ptr_eq.rs
tests/ui/ptr_eq.stderr

We do not want to remove casts done inside macros. Also, when printing the suggestion, take it from the same context as the origin expression (the root context).
Problems found while working on #14526, but should be merged even if #14526 is not.

Ensure that peeling does not recurse into macros

---

clippy_lints/src/methods/iter_cloned_collect.rs
tests/ui/iter_cloned_collect.fixed
tests/ui/iter_cloned_collect.rs
tests/ui/iter_cloned_collect.stderr

Closes #9119
changelog: [`iter_cloned_collect`]: fix FP with custom `From`/`IntoIterator` impl

fix: `iter_cloned_collect` FP with custom `From`/`IntoIterator` impl

---

clippy_lints/src/non_canonical_impls.rs
tests/ui/non_canonical_partial_ord_impl.fixed
tests/ui/non_canonical_partial_ord_impl.rs
tests/ui/non_canonical_partial_ord_impl.stderr

`non_canonical_partial_ord_impl` will now recognize two forms of canonical implementations: `Some(self.cmp(other))` and `self.cmp(other).into()`.
changelog: [`non_canonical_partial_ord_impl`]: recognize `self.cmp(other).into()` as a canonical implementation of `PartialOrd::partial_cmp()`.
Fixes rust-lang/rust-clippy#13640

Accept `self.cmp(other).into()` as canonical `PartialOrd` impl

---

triagebot.toml

Enable GitHub review synchronization with S-waiting-on-* labels

---

clippy_lints/src/default_constructed_unit_structs.rs
tests/ui/default_constructed_unit_structs.fixed
tests/ui/default_constructed_unit_structs.rs
tests/ui/default_constructed_unit_structs.stderr

There were two bugs here. Let's assume `T` is a singleton type implementing `Default` and that `f()` takes a `T`:
- `f(<T>::default())` cannot be replaced by `f(<T)` as it was (incorrect spans – this is tricky because the type relative path uses a base span covering only `T`, not `<T>`) (third commit)
- The argument of `f(<_>::default())` is inferred correctly, but cannot be replaced by `<_>` or `_`, as this cannot be used to infer an instance of a singleton type (first commit).
The second commit offers better error messages by pointing at the whole expression.
Fix #12654 
changelog: [`default_constructed_unit_struct`]: do not suggest incorrect fix when using a type surrounded by brackets

Correctly handle bracketed type in `default_constructed_unit_struct`

---

clippy_lints/src/arbitrary_source_item_ordering.rs

This contributes towards https://github.com/rust-lang/rust/issues/137978.

Avoid some uses of empty identifiers

---

triagebot.toml

This PR enables the no-mentions in commits handler in triagebot.
Documentation pending at https://github.com/rust-lang/rust-forge/pull/827
Original motivation in https://github.com/rust-lang/rust/issues/137990.
changelog: add `[no-mentions]` in `triagebot.toml`

Enable no mentions in commits of triagebot

---

triagebot.toml

`triagebot.toml` is related to the repo behavior wrt interactions, and must be kept inline with what is done in the CI.
r? @flip1995

Assign PR touching `triagebot.toml` to Philipp

---

lintcheck/ci_crates.toml

`cmake` has been pinned to version 3.31.6 in Ubuntu runner images. Reference: https://github.com/actions/runner-images/pull/11933

Reinstate checking of `tokio-rustls` in lintcheck

---

clippy_lints/src/implicit_return.rs
clippy_lints/src/redundant_async_block.rs
clippy_utils/src/lib.rs
tests/ui/implicit_return.fixed
tests/ui/implicit_return.rs
tests/ui/implicit_return.stderr

Blocks created by desugaring will not contain an explicit `return`. Do not suggest to add it when the user has no control over the desugared code.
Also, ensure that in a `xxx.await` expression, the suggested `return` is emitted before the whole expression, not before the `await` keyword.
Fix #14411
changelog: [`implicit_return`]: fix proposed `return` position in the presence of asynchronous code

`implicit_return`: better handling of asynchronous code

---

clippy_lints/src/redundant_clone.rs
tests/ui/redundant_clone.fixed
tests/ui/redundant_clone.rs

fixes #13900 
changelog: [`redundant_clone`]: fix FP in overlapping lifetime

fix: `redundant_clone` FP in overlapping lifetime

---

tests/dogfood.rs

This prevents forgotten `dbg!()` calls from entering Clippy codebase by mistake.
Suggested by @y21 when one of my PR forgot to remove one `dbg!()` call.

dogfood: run with `-D clippy::dbg_macro`

---

book/src/development/adding_lints.md

This is a recent change, and no error marker is inserted by default in the file generated by `cargo dev new_lint`.
r? @y21

book: indicate that at least one error marker is required

---

clippy_lints/src/derive.rs
tests/ui/derive.rs
tests/ui/derive.stderr

`unsafe_fields` is an incomplete feature; comments have been put near `#![expect(incomplete_features)]` to ensure that we revisit the situation when the feature becomes complete.
changelog: [`expl_impl_clone_on_copy`]: do not lint in the presence of `unsafe` fields
Fixes #14558

Do not propose to auto-derive `Clone` in presence of unsafe fields

---

clippy_lints/src/cognitive_complexity.rs
tests/ui/cognitive_complexity.rs

changelog: [`cognitive_complexity`]: Consecutive return calls decreased complexity level of the function by 1.
fixes rust-lang/rust-clippy#14422

Consecutive returns dont decrease cognitive Complexity level anymore

---

clippy_lints/src/len_zero.rs
tests/ui/len_without_is_empty_expect.rs
tests/ui/len_without_is_empty_expect.stderr

`clippy::len_without_is_empty` can be allowed at the type declaration site, and this will prevent the lint from triggering even though the lint is shown on the `len()` method definition.
This allows the lint to be expected even though it is allowed at the type declaration site.
changelog: [`len_without_is_empty`]: the lint can now be `#[expect]`ed on the `len()` method even when it is `#[allow]`ed on the definining type.
Fixes rust-lang/rust-clippy#14597

Fulfill the lint expectation even if allowed at the type level

---

clippy_lints/src/ptr.rs
tests/ui/mut_from_ref.rs
tests/ui/mut_from_ref.stderr

fixes #7749.
This issue proposes searching for `DerefMut` impls, which is not done here: every lifetime parameter (aka `<'a>`) is the input types is considered to be potentially mutable, and thus deactivates the lint.
changelog: [`mut_from_ref`]: Fixes false positive, where lifetimes nested in the type (e.g. `Box<&'a mut T>`) were not considered.

Consider nested lifetimes in `mut_from_ref`

---

clippy_lints/src/missing_asserts_for_indexing.rs
tests/ui/missing_asserts_for_indexing.fixed
tests/ui/missing_asserts_for_indexing.rs
tests/ui/missing_asserts_for_indexing.stderr
tests/ui/missing_asserts_for_indexing_unfixable.rs
tests/ui/missing_asserts_for_indexing_unfixable.stderr

`assert_eq!()` and `assert_ne!()` are not expanded the same way as `assert!()` (they use a `match` instead of a `if`). This makes them being recognized as well.
Fix rust-lang/rust-clippy#14255
changelog: [`missing_asserts_for_indexing`]: consider `assert_eq!()` as well

`missing_asserts_for_indexing`: consider `assert_eq!()` as well

---

clippy_lints/src/arbitrary_source_item_ordering.rs

To avoid crashing Clippy, the `bug!()` is used only when debug assertions are enabled. In regular usage, the result will be the same as before, but without the extra line printed on the standard output which has the potential for disrupting shell scripts.

Replace stray `println!()` in lint code by `bug!()`

---

CHANGELOG.md
clippy_lints/src/declared_lints.rs
clippy_lints/src/lib.rs
clippy_lints/src/redundant_test_prefix.rs
clippy_utils/src/lib.rs
tests/ui/redundant_test_prefix.fixed
tests/ui/redundant_test_prefix.rs
tests/ui/redundant_test_prefix.stderr
tests/ui/redundant_test_prefix_noautofix.rs
tests/ui/redundant_test_prefix_noautofix.stderr

This PR has started as an effort to proceed from the feedback in rust-lang/rust-clippy#12861. 
- Checks test functions (functions marked with `#[test]` annotation) for redundant "test_" prefix.
- Auto-fix is supported (and handles collisions gracefully, see below).
- If removing "test_" prefix from, say, `test_foo()` results in a name collision (either because function `foo()` is already defined within the current scope, or because the `foo()` call exists within function -- thus creating an unwanted recursion), lint suggests function rename, warning the user that a simple trimming of `test_` prefix will result in a name collision.
- If removing "test_" prefix results in invalid identifier (consider `test_const`, `test_`, `test_42`), then again no auto-fix is suggested, user is asked to …

New lint: `redundant_test_prefix`

---

clippy_lints/src/methods/from_iter_instead_of_collect.rs
tests/ui/from_iter_instead_of_collect.fixed
tests/ui/from_iter_instead_of_collect.rs
tests/ui/from_iter_instead_of_collect.stderr

Instead of looking for angle brackets in the source code, use the HIR and Ty interfaces to either copy the original type, or complete it with `_` placeholders if all type and const generic arguments are inferred.
Fixes rust-lang/rust-clippy#14581 
changelog: [`from_iter_instead_of_collect`]: show correct type in suggestion

Build complete usable type from a type-relative prefix

---

clippy_lints/src/bool_to_int_with_if.rs
tests/ui/bool_to_int_with_if.fixed
tests/ui/bool_to_int_with_if.rs
tests/ui/bool_to_int_with_if.stderr

- Do not replace macro results in then/else branches
- Extract condition snippet from the right context
- Make suggestion `MaybeIncorrect` if it would lead to losing comments
changelog: [`bool_to_int_with_if`]: properly handle macros
Fixes rust-lang/rust-clippy#14628

`bool_to_int_with_if`: properly handle macros

---

triagebot.toml

This will let people [add summary notes](https://forge.rust-lang.org/triagebot/note.html) to an issue, for example to add that an issue is best kept for first-timers.
I wanted to use it in https://github.com/rust-lang/rust-clippy/issues/14617#issuecomment-2807090281.

Add `note` feature to triagebot's config

---

clippy_lints/src/significant_drop_tightening.rs
tests/ui/crashes/ice-13544-original.rs
tests/ui/crashes/ice-13544-reduced.rs

Limit the recursion depth, as each level of nesting adds another deeper projection.
There might be a more complex way of handling the problem, but infinite recursions are bad, and don't allow Clippy to terminate properly.
changelog: [`significant_drop_tightening`]: do not recurse forever when checking for attribute on type or its constituent
Fixes rust-lang/rust-clippy#13544
@rustbot label +L-nursery

Do not recurse forever in `significant_drop_tightening`

---

CHANGELOG.md
clippy_lints/src/declared_lints.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/swap_with_temporary.rs
tests/ui/swap_with_temporary.fixed
tests/ui/swap_with_temporary.rs
tests/ui/swap_with_temporary.stderr
tests/ui/swap_with_temporary_unfixable.rs
tests/ui/swap_with_temporary_unfixable.stderr

This lint detects inefficient or useless `{std,core}::mem::swap()` calls such as:
```rust
// Should be `a = temp();`
swap(&mut a, &mut temp());
// Should be `*b = temp();`
swap(b, &mut temp());
// Should be `temp1(); temp2();` if we want to keep the side effects
swap(&mut temp1(), &mut temp2());
```
It also takes care of using a form appropriate for a `()` context if `swap()` is part of a larger expression (don't ask me why this wouldn't happen, I have no idea), by suggesting `{ x = y; }` (statement in block) or `{std,core}::mem::drop((temp1(), temp2())`.
changelog: [`swap_with_temporary`]: new lint
Close #1968

New lint: `swap_with_temporary`

---

clippy_lints/src/matches/match_single_binding.rs
tests/ui/match_single_binding.fixed
tests/ui/match_single_binding.rs
tests/ui/match_single_binding.stderr

changelog: [`match_single_binding`]: allow macros in scrutinee and patterns
Fixes rust-lang/rust-clippy#14634

`match_single_binding`: allow macros in scrutinee and patterns

---

clippy_lints/src/empty_with_brackets.rs
clippy_lints/src/lib.rs
tests/ui/empty_enum_variants_with_brackets.fixed
tests/ui/empty_enum_variants_with_brackets.rs
tests/ui/empty_enum_variants_with_brackets.stderr

Fixes #12551 
changelog: [`empty_enum_variants_with_brackets`]: Do not lint reachable enums or enums which are used as functions within the same crate.
r? @xFrednet

`empty_enum_variants_with_brackets`: Do not lint reachable enums and enum variants used as functions in the same crate

---

clippy_lints/src/casts/ptr_cast_constness.rs
tests/ui/ptr_cast_constness.fixed
tests/ui/ptr_cast_constness.rs
tests/ui/ptr_cast_constness.stderr

changelog: [`ptr_cast_constness`]: do not replace suggestion by content of macro
Fixes rust-lang/rust-clippy#14621

`ptr_cast_constness`: show snippet from the right context

---

clippy_lints/src/methods/iter_kv_map.rs
tests/ui/iter_kv_map.fixed
tests/ui/iter_kv_map.rs
tests/ui/iter_kv_map.stderr

Fix rust-lang/rust-clippy#14595 
changelog: [`iter_kv_map`]: recognize references on maps as well

`iter_kv_map`: recognize references on maps as well

---

clippy_lints/src/casts/borrow_as_ptr.rs
clippy_lints/src/casts/mod.rs
clippy_lints/src/non_copy_const.rs
tests/ui/borrow_as_ptr.fixed
tests/ui/borrow_as_ptr.rs
tests/ui/borrow_as_ptr.stderr

While I like replacing `&x` by `&raw const x` and `&mut x` by `&raw mut x`, I'm less sure I like the suggested reborrows such as `&raw const *p`. There was one in Clippy sources, see the PR diff.
@RalfJung, any opinion on this?
Fix #14406
changelog: [`borrow_as_ptr`]: lint implicit casts as well

Make `borrow_as_ptr` flag implicit casts as well

---

clippy_lints/src/question_mark.rs
tests/ui/question_mark.fixed
tests/ui/question_mark.rs
tests/ui/question_mark.stderr

Close rust-lang/rust-clippy#14615
changelog: [`question_mark`]: when type is behind Deref include parentheses

Fix question_mark suggesting when type is behind Deref include parentheses

---

clippy_lints/src/ptr.rs
tests/ui/ptr_eq.fixed
tests/ui/ptr_eq.rs
tests/ui/ptr_eq.stderr
tests/ui/ptr_eq_no_std.fixed
tests/ui/ptr_eq_no_std.rs
tests/ui/ptr_eq_no_std.stderr

`ptr_eq` was recently enhanced to lint on more cases of raw pointers comparison:
- lint on all raw pointer comparison, by proposing to use `[core|std]::ptr::eq(lhs, rhs)` instead of `lhs == rhs`;
- removing one symetric `as usize` on each size if needed
- peeling any level of `as *[const|mut] _` if the remaining expression can still be coerced into the original one (i.e., is a ref or raw pointer to the same type as before)
The current change restricts the lint to the cases where at least one level of symetric `as usize`, or any conversion to a raw pointer, could be removed. For example, a direct comparaison of two raw pointers will not trigger the lint anymore.
changelog: [`ptr_eq`]: do not lint when comparing two raw pointers directly with no casts involved
Fixes …

Restrict the cases where `ptr_eq` triggers

---

util/etc/pre-commit.sh

it was added back in 6035e050e83cc991f94797eef4d720c0b61d8955, at which time there were some files matching it, e.g.
https://github.com/rust-lang/rust-clippy/blob/6035e050e83cc991f94797eef4d720c0b61d8955/clippy_lints/src/lib.deprecated.rs
fixes rust-lang/rust-clippy#14670

remove non-existent pathspec from pre-commit hook

---

clippy_lints/src/needless_question_mark.rs
tests/ui/needless_question_mark.stderr
tests/ui/question_mark.fixed
tests/ui/question_mark.rs
tests/ui/question_mark.stderr

Fixes https://github.com/rust-lang/rust-clippy/issues/14675 by making it clearer that the constructor needs to be removed as well
Also fixes https://github.com/rust-lang/rust-clippy/issues/8392

Reword `needless_question_mark` diagnostics and docs

---

clippy_lints/src/types/vec_box.rs

`cargo dev fmt` seems to not work for some reason (possibly because of all the comments in the let-chain), so I formatted it manually -- I hope it's right

style: pull one more `if` into the let-chain

---

clippy_lints/src/casts/unnecessary_cast.rs
tests/ui/unnecessary_cast.fixed
tests/ui/unnecessary_cast.rs
tests/ui/unnecessary_cast.stderr

Closes rust-lang/rust-clippy#14640 
changelog: [`unnecessary_cast`] fix extra brackets in suggestions when in macro

fix: `unnecessary_cast` suggests extra brackets when in macro

---

clippy_lints/src/equatable_if_let.rs
tests/ui/equatable_if_let.fixed
tests/ui/equatable_if_let.rs
tests/ui/equatable_if_let.stderr

Closes #8710
changelog: [`equatable_if_let`] fix wrong suggestions when involving reference

fix: `equatable_if_let` suggests wrongly when involving reference

---

clippy_lints/src/manual_div_ceil.rs
tests/ui/manual_div_ceil.fixed
tests/ui/manual_div_ceil.rs
tests/ui/manual_div_ceil.stderr

here is my small fix
changelog: fix suggestion span to avoid showing macro name in `.div_ceil()` suggestion
i changed this line
`let divisor_snippet = snippet_with_applicability(cx, rhs.spansource_callsite(), "..", applicability);`
to this line
`let divisor_snippet = snippet_with_applicability(cx, rhs.span, "..", applicability);`
to fix problem where this warning in macro expands like this
```rust
4  |         let _ = (x + 7) / 8;
|                 ^^^^^^^^^^^ help: consider using `.div_ceil()`: `x.div_ceil(y!())`
```
[play it yourself](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=397aa8cd2ffffb24a286fbddbc75446c)
as you can see here it looks like `x.div_ceil(y!())` and contains macro signature
so i fixed this problem, i will look closely if there any more …

`manual_div_ceil`: fix suggestions when macro is involved

---

clippy_lints/src/lib.rs
clippy_lints/src/unused_unit.rs
tests/ui/unused_unit.edition2021.fixed
tests/ui/unused_unit.edition2021.stderr
tests/ui/unused_unit.edition2024.fixed
tests/ui/unused_unit.edition2024.stderr
tests/ui/unused_unit.rs

Closes rust-lang/rust-clippy#14577.
Migrate this lint to late pass and avoids `unit_never_type_fallback` since it is no longer permitted in Rust 2024.
changelog: [`unused_unit`] fix wrong suggestions when unit never type fallback

fix: `unused_unit` suggests wrongly when unit never type fallback

---

clippy_lints/src/casts/manual_dangling_ptr.rs
clippy_lints/src/transmute/eager_transmute.rs
clippy_lints/src/zero_sized_map_values.rs
clippy_utils/src/ty/mod.rs

Supersedes rust-lang/rust-clippy#12550
`layout_of` no longer contains a `delay_bug` so there's no need for this anymore.

Remove `is_normalizable`

---

clippy_dev/src/new_lint.rs

I'm working on https://github.com/rust-lang/rust-clippy/issues/14542 and I decided to name the lint `unnecessary_map` originally. However when I ran the command, I got:
```
thread 'main' panicked at clippy_dev/src/new_lint.rs:450:5:
Lint `unnecessary_map` already defined in `/home/imperio/rust/clippy/clippy_lints/src/methods/mod.rs`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
It's because there is already a `unnecessary_map_or`, which matches the `.contains()` call. This PR strengthens this check.
changelog: Fix `new_lint` clippy command
r? @flip1995

Fix `new_lint` clippy command

---

clippy_config/src/types.rs
tests/ui-toml/toml_unloaded_crate/clippy.toml
tests/ui-toml/toml_unloaded_crate/conf_unloaded_crate.rs
tests/ui-toml/toml_unloaded_crate/conf_unloaded_crate.stderr

Fixes https://github.com/rust-lang/rust-clippy/pull/14397#issuecomment-2848328221
r? @samueltardieu
changelog: Don't warn about clippy.toml disallowed paths for crates that were not loaded

Don't warn about unloaded crates

---

clippy_lints/src/unused_async.rs
tests/ui/unused_async.rs

Closes rust-lang/rust-clippy#14704
changelog: [`unused_async`] fix FP on default impl

fix: `unused_async` FP on default impl

---

.github/workflows/clippy_changelog.yml

Simplifies the implementation a bit, also makes the message an error annotation

Read PR body from event in clippy_changelog action

---

clippy_lints/src/matches/manual_unwrap_or.rs
tests/ui/manual_unwrap_or_default.fixed
tests/ui/manual_unwrap_or_default.rs

Closes rust-lang/rust-clippy#14716
changelog: [`manual_unwrap_or_default`] fix FP on ref binding

Fix `manual_unwrap_or_default` FP on ref binding

---

clippy_lints/src/collapsible_if.rs
tests/ui/collapsible_if.fixed
tests/ui/collapsible_if.rs

Closes rust-lang/rust-clippy#14722 
changelog: [`collapsible_if`] fix FP on block stmt before expr

Fix `collapsible_if` FP on block stmt before expr

---

CHANGELOG.md
book/src/lint_configuration.md
clippy_config/src/conf.rs
clippy_lints/src/missing_doc.rs
tests/ui-toml/missing_docs_allow_unused/clippy.toml
tests/ui-toml/missing_docs_allow_unused/missing_docs_allow_unused.rs
tests/ui-toml/missing_docs_allow_unused/missing_docs_allow_unused.stderr
tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr

fixes #14413 
add allow_unused config to missing_docs_in_private_items for underscored field
changelog: [`missing_docs_in_private_items`]: add allow_unused config to missing_docs_in_private_items for underscored field
Explaination (quoted from the issue's author): When writing structures that must adhere to a specific format (such as memory mapped I/O structures) there are inevitably fields that are "reserved" by specifications and thus need no documentation. In cases where private docs are preferred but reserved fields need no explanation, having to #[allow/expect] this lint removes the ability to check for otherwise used fields' documentation.

add allow_unused config to missing_docs_in_private_items

---

clippy_lints/src/item_name_repetitions.rs
tests/ui/enum_variants.rs

fix rust-lang/rust-clippy#13637
As suggested in the PR above, we should not lint enum variants containing matching path names.
changelog: [`item_name_repetitions`]: exclude enum variants with identical path components

`item_name_repetitions`: exclude enum variants with identical path components

---

clippy_lints/src/methods/mod.rs
tests/ui/unwrap_expect_used.rs
tests/ui/unwrap_expect_used.stderr

changelog: [`unwrap_used`, `expect_used`]: lint even when the receiver is a macro expansion result
This also paves the way for expanding more method call lints to expanded receivers or arguments.
Fixes rust-lang/rust-clippy#13455

`unwrap_used`, `expect_used`: accept macro result as receiver

---

clippy_lints/src/let_with_type_underscore.rs
tests/ui/let_with_type_underscore.fixed
tests/ui/let_with_type_underscore.stderr

Make `let_with_type_underscore` help message into a suggestion

---

clippy_lints/src/manual_let_else.rs
tests/ui/manual_let_else.rs
tests/ui/manual_let_else.stderr

Closes rust-lang/rust-clippy#14598 
Implemented checks for simple enum variants when checking if match arms are disjointed.
changelog: [`manual_let_else`] fix FN when diverges on simple enum variant

Fix `manual_let_else` FN when diverges on simple enum variant

---

triagebot.toml

It is useful, and happened in https://github.com/rust-lang/rust-clippy/issues/12806#issuecomment-2863646739

Allow any rust-lang team member to close an issue with rustbot

---

book/src/development/basics.md

Use `cargo dev setup toolchain` in install from source docs

---

clippy_lints/src/unwrap.rs

This cleans up `unwrap.rs`:
- use interned symbols instead of strings
- update names to reflect the current implementation
- replaced a cascaded `if` by a shorter `match`

`unwrap.rs` cleanup

---

clippy_lints/src/operators/integer_division.rs
tests/ui/integer_division.rs
tests/ui/integer_division.stderr

Close rust-lang/rust-clippy#14652
changelog: [`integer_division`]: fix false negative for NonZero denominators

Fix integer_division false negative for NonZero denominators

---

book/src/lint_configuration.md
clippy_config/src/conf.rs
clippy_lints/src/lib.rs
clippy_lints/src/to_digit_is_some.rs
clippy_utils/src/msrvs.rs
tests/ui/to_digit_is_some.fixed
tests/ui/to_digit_is_some.rs
tests/ui/to_digit_is_some.stderr

The `to_digit_is_some()` lint suggests using `char::is_digit()`. It should not trigger in const contexts before Rust 1.87.
changelog: [`to_digit_is_some`]: Do not lint in const contexts when MSRV is below 1.87

`char::is_digit()` is const-stable only since Rust 1.87

---

clippy_lints/src/unwrap.rs
tests/ui/checked_unwrap/simple_conditionals.rs
tests/ui/checked_unwrap/simple_conditionals.stderr

The problem is that `check_fn` is triggered by both function and closure, and `visit_expr` can visit expressions in another closures within a function or closure.
So just skip walking in a inner closure.
changelog: Fix [`unnecessary_unwrap`] emitted twice in closure which inside in a function or another closure.
Fixes: rust-lang/rust-clippy#14763

Fix `unnecessary_unwrap` emitted twice in closure (#14763)

---

clippy_utils/src/paths.rs
tests/ui-toml/toml_disallowed_methods/clippy.toml
tests/ui-toml/toml_disallowed_methods/conf_disallowed_methods.rs
tests/ui-toml/toml_disallowed_methods/conf_disallowed_methods.stderr

Fixes https://github.com/rust-lang/rust-clippy/issues/14767
A long standing issue revealed by https://github.com/rust-lang/rust-clippy/pull/14397

Resolve through local re-exports in `lookup_path`

---

clippy_lints/src/missing_const_for_fn.rs
tests/ui/crashes/missing_const_for_fn_14774.fixed
tests/ui/crashes/missing_const_for_fn_14774.rs
tests/ui/crashes/missing_const_for_fn_14774.stderr

The `mir_drops_elaborated_and_const_checked` query result has been stolen already and cannot be borrowed again. Use the `optimized_mir` query result instead.
changelog: [`missing_const_for_fn`]: fix ICE with some compilation options
Fixes rust-lang/rust-clippy#14774 
r? @Jarcho

Fix ICE in `missing_const_for_fn`

---

Cargo.toml
tests/integration.rs

`tempfile` has deprecated `TempDir::into_path()` (replacing it by `TempDir::keep()` between version `3.3` which Clippy required and version `3.20` which is the latest semver-compatible version. Since Clippy doesn't use a `Cargo.lock` file, the latest version of `tempfile` is used which leads to CI failure.
r? @flip1995

Use `tempfile::TempDir::keep()` instead of deprecated `into_path()`

---

book/src/development/adding_lints.md

This PR update the sample code in the development guide because `ident` was moved to the struct `Fn` in https://github.com/rust-lang/rust/pull/138740 .

book: modify FnKind::Fn matching

---

clippy_lints/src/attrs/mod.rs
clippy_lints/src/casts/mod.rs
clippy_lints/src/doc/mod.rs
clippy_lints/src/implicit_saturating_sub.rs
clippy_lints/src/lifetimes.rs
clippy_lints/src/loops/mod.rs
clippy_lints/src/manual_abs_diff.rs
clippy_lints/src/mem_replace.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/single_option_map.rs
clippy_lints/src/types/mod.rs

relates to rust-lang/rust-clippy#14653
changelog: [`elidable_lifetime_names`]: Fix clippy version that this lint was introduced in.
It might be good to have some automation to check that the version is correct.
IIUC the version should be the current nightly version at the time a PR is merged.
If a release happens while a PR is open, the version needs to be bumped - this is easy to forget.

Fix clippy::version of elidable_lifetime_names to 1.87

---

clippy_lints/src/methods/return_and_then.rs
tests/ui/return_and_then.fixed
tests/ui/return_and_then.rs
tests/ui/return_and_then.stderr

If an expression is not going to return from the current function of closure, it should not get linted.
This also allows `return` expression to be linted, in addition to the final expression. Those require blockification and proper indentation.
changelog: [`return_and_then`]: only lint returning expressions
Fixes rust-lang/rust-clippy#14781

`return_and_then`: only lint returning expressions

---

clippy_lints/src/trait_bounds.rs
tests/ui-toml/type_repetition_in_bounds/main.rs
tests/ui-toml/type_repetition_in_bounds/main.stderr
tests/ui/type_repetition_in_bounds.rs
tests/ui/type_repetition_in_bounds.stderr

changelog: [`type_repetition_in_bounds`]: include all generic bounds in suggestion, clearer message which now includes the repeated type name
Fixes rust-lang/rust-clippy#14744

Fix messages for `type_repetition_in_bounds`

---

book/src/development/infrastructure/changelog_update.md

Update "Changelog update walkthrough" section based on rust-lang/rust-clippy#14748 discussion 

Update "Changelog update walkthrough" section

---

Cargo.toml
tests/ui/let_underscore_untyped.rs
tests/ui/let_underscore_untyped.stderr

Do not use `clippy_utils` from UI tests

---

clippy_lints/src/non_std_lazy_statics.rs
tests/ui/non_std_lazy_static/non_std_lazy_static_fixable.fixed
tests/ui/non_std_lazy_static/non_std_lazy_static_fixable.rs

When a `non_std_lazy_statics` warning is generated about an item type which can be replaced by a standard library one, ensure that the lint happens on the item HIR node so that it can be expected.
changelog: [`non_std_lazy_statics`]: generate the warning onto the right node
Fixes rust-lang/rust-clippy#14729 
Note that this doesn't change anything on lints generated for the `lazy_static::lazy_static` macro because the `expect` attribute cannot be applied to a macro.

Post `non_std_lazy_statics` type warnings onto the right node

---

clippy_lints/src/useless_conversion.rs
tests/ui/useless_conversion.fixed
tests/ui/useless_conversion.rs
tests/ui/useless_conversion.stderr

Fixes: rust-lang/rust-clippy#14656 
changelog: Fix [`useless_conversion`] false positive when using `.into_iter().any()`.

Fix false positive of `useless_conversion` when using `.into_iter().any()`

---

clippy_lints/src/comparison_chain.rs
tests/ui/comparison_chain.rs
tests/ui/comparison_chain.stderr

Clippy should not lint 2 blocks expression for comparison_chain.
Fixes rust-lang/rust-clippy#4725
changelog: [`comparison_chain`]: do not lint 2 blocks expression

comparison_chain: do not lint on 2 blocks expression

---

clippy_lints/src/copies.rs
clippy_lints/src/matches/match_same_arms.rs
clippy_utils/src/lib.rs
tests/ui-toml/ifs_same_cond/ifs_same_cond.rs
tests/ui-toml/ifs_same_cond/ifs_same_cond.stderr
tests/ui/ifs_same_cond.rs
tests/ui/ifs_same_cond.stderr
tests/ui/match_same_arms.fixed
tests/ui/match_same_arms.stderr
tests/ui/match_same_arms2.fixed
tests/ui/match_same_arms2.rs
tests/ui/match_same_arms2.stderr
tests/ui/match_same_arms_non_exhaustive.fixed
tests/ui/match_same_arms_non_exhaustive.rs
tests/ui/match_same_arms_non_exhaustive.stderr
tests/ui/same_functions_in_if_condition.rs
tests/ui/same_functions_in_if_condition.stderr

A large fraction of the lints emitted in CI lintcheck come from [this `match`](https://github.com/unicode-rs/unicode-normalization/blob/v0.1.23/src/tables.rs#L34289), currently for `n` same arms `((n - 1) * n)/2` lints are emitted, with this change it will be emitted as a single lint
Also fixes https://github.com/rust-lang/rust-clippy/issues/13835

`match_same_arms`, `ifs_same_cond`: lint once per same arm/condition

---

clippy_lints/src/unnecessary_wraps.rs
tests/ui/unnecessary_wraps.stderr

Using the function declaration, by stripping the body, is enough to convey the lint message.
changelog: [`unnecessary_wraps`]: do not include the whole body in the lint span
Closes rust-lang/rust-clippy#14773

`unnecessary_wraps`: do not include the whole body in the lint span

---

clippy_lints/src/dereference.rs
tests/ui/explicit_deref_methods.fixed
tests/ui/explicit_deref_methods.rs
tests/ui/explicit_deref_methods.stderr

Was disabled in rust-lang/rust-clippy#10855 due to a broken suggestion. This will only lint if a type is not proveded (e.g. `T::deref`).

Reenable linting on UFCS `deref` calls

---

clippy_lints/src/arbitrary_source_item_ordering.rs
tests/ui-toml/arbitrary_source_item_ordering/ordering_mixed.default.stderr
tests/ui-toml/arbitrary_source_item_ordering/ordering_mixed.default_exp.stderr
tests/ui-toml/arbitrary_source_item_ordering/ordering_mixed.ord_within.stderr
tests/ui-toml/arbitrary_source_item_ordering/ordering_mixed.rs

A representation attribute `#[repr(…)]` might indicate that the ordering of the fields or the variants is dictated by the API the code is interfacing with. Better not lint with `arbitrary_source_item_ordering` in this case.
changelog: [`arbitrary_source_item_ordering`]: do not lint inside items with `#[repr]` attribute

Skip inner ordering checking in presence of `#[repr(…)]`

---

clippy_lints/src/float_literal.rs
tests/ui/excessive_precision.fixed
tests/ui/excessive_precision.rs
tests/ui/excessive_precision.stderr

Fixes rust-lang/rust-clippy#6341.
changelog: [`excessive_precision`] no longer triggers on an exponent with leading zeros

excessive_precision: Fix false positive when exponent has leading zero

---

clippy_lints/src/empty_with_brackets.rs
tests/ui/empty_structs_with_brackets.fixed
tests/ui/empty_structs_with_brackets.rs

Do not attempt to fetch a snippet from expansion. Without this change, the inside of macros could[*] be shown as the source of the problem.
[*] Due to the way the source code is processed and reparsed in this macro, the declarative macro has to be located outside the current source file for the bug to appear. Otherwise, the macro call itself will be (mis)identified as a potential `struct` field definition and the lint will not trigger.
changelog: [`empty_struct_with_brackets`]: do not lint code coming from macro expansion

`empty_struct_with_brackets`: do not lint code coming from macro expansion

---

book/src/development/basics.md

fix minor typo in book: toolcahin => toolchain

Fixing minor typo in book

---

clippy_lints/src/methods/useless_asref.rs
tests/ui/useless_asref.fixed
tests/ui/useless_asref.rs

changelog: [`useless_as_ref`]: fix ICE on trait method
Fixes rust-lang/rust-clippy#14828

Do not call `TyCtxt::type_of()` on a trait

---

clippy_lints/src/methods/unnecessary_to_owned.rs
tests/ui/unnecessary_to_owned.fixed
tests/ui/unnecessary_to_owned.rs

Closes rust-lang/rust-clippy#14833
changelog: [`unnecessary_to_owned`] fix FP when map key is a reference

fix: `unnecessary_to_owned` FP when map key is a reference

---

CONTRIBUTING.md
book/src/development/the_team.md
triagebot.toml

This unifies the Clippy repo with the rest of the rust org repos.

Docs: Use spaces in `good first issue` label

---

clippy_lints/src/no_effect.rs
tests/ui/no_effect.rs
tests/ui/single_range_in_vec_init.rs

It is not enough to check if an expression type implements `Drop` to determine whether it can have a significant side-effect.
Also, add tests for unchecked cases which were explicitly handled in the code, such as checking for side effect in a `struct`'s fields, or in its base expression.
Fix rust-lang/rust-clippy#14592 
changelog: [`no_effect_underscore_binding`]: do not propose to remove the assignment of an object if dropping it might indirectly have a visible side effect

Check if dropping an expression may have indirect side-effects

---

src/driver.rs

Remove obsolete restriction in code

---

clippy_lints/src/matches/needless_match.rs
tests/ui/needless_match.fixed
tests/ui/needless_match.rs
tests/ui/needless_match.stderr

A `return` in an expression makes it divergent and cannot be removed blindly. While this stripping might have been introduced as a way to catch more cases, it was improperly used, and no tests exhibit a failure when this special handling is removed.
changelog: [`needless_match`]: do not strip `return` as it might make the `if let` or `match` divergent in some cases
Fixes rust-lang/rust-clippy#14754

`needless_match`: do not pretend that `return` is not significant in an expression

---

clippy_lints/src/zero_sized_map_values.rs
tests/ui/crashes/ice-6840.rs
tests/ui/zero_sized_hashmap_values.rs
tests/ui/zero_sized_hashmap_values.stderr

If a type is incomplete, for example if generic parameters are not available yet, although they are not escaping, its layout may not be computable. Calling `TyCtxt::layout_of()` would create a delayed bug in the compiler.
changelog: [`zero_sized_map_values`]: fix ICE
Fixes rust-lang/rust-clippy#14822 
r? @Jarcho

Fix ICE while computing type layout

---

clippy_lints/src/returns.rs
tests/ui/crashes/ice-12491.fixed
tests/ui/crashes/ice-12491.rs
tests/ui/crashes/ice-12491.stderr
tests/ui/needless_return.fixed
tests/ui/needless_return.rs
tests/ui/needless_return.stderr

Fixes rust-lang/rust-clippy#14750 by reducing the lint span for needless_return.
changelog: [`needless_return`]: Lint span no longer wraps to previous line

Make lint span smaller for needless return

---

clippy_lints/src/loops/explicit_into_iter_loop.rs
clippy_lints/src/loops/explicit_iter_loop.rs
clippy_lints/src/loops/mod.rs
tests/ui/explicit_into_iter_loop.fixed
tests/ui/explicit_into_iter_loop.rs
tests/ui/explicit_into_iter_loop.stderr
tests/ui/explicit_iter_loop.fixed
tests/ui/explicit_iter_loop.rs
tests/ui/explicit_iter_loop.stderr
tests/ui/iter_next_loop.rs
tests/ui/iter_next_loop.stderr

The `explicit_into_iter_loop`, `explicit_iter_loop` and `iter_next_loop` will now:
- trigger only when the triggering expression is not located into macro code;
- properly expose code rewrite proposal with code coming from the root context.
changelog: [`explicit_into_iter_loop`, `explicit_iter_loop`, `iter_next_loop`]: behave in macro context
Fixes rust-lang/rust-clippy#14630

Various macro fixes for loop lints

---

clippy_lints/src/doc/markdown.rs
clippy_lints/src/doc/mod.rs
tests/ui/doc/doc_markdown-issue_13097.fixed
tests/ui/doc/doc_markdown-issue_13097.rs
tests/ui/doc/doc_markdown-issue_13097.stderr

Turns out that `doc_markdown` uses a non-cheap rustdoc function to convert from markdown ranges into source spans. And it was using it a lot (about once every 17 lines of documentation on `tokio`, which ends up being about 2000 times).
This ended up being about 18% of the total Clippy runtime as discovered by lintcheck --perf in docs-heavy crates. This PR optimizes one of the cases in which Clippy calls the function, and a future PR once pulldown-cmark/pulldown-cmark#1034 is merged will be opened. This PR lands the use of the function into the single-digit zone.
Note that not all crates were affected by this crate equally, those with more docs are affected far more than those light ones.
changelog:[`clippy::doc_markdown`] has been optimized by 50%

[Perf] Optimize documentation lints **a lot** (1/2) (18% -> 10%)

---

clippy_lints/src/needless_for_each.rs
lintcheck/src/output.rs
tests/ui/needless_for_each_fixable.fixed
tests/ui/needless_for_each_fixable.rs
tests/ui/needless_for_each_fixable.stderr

Closes rust-lang/rust-clippy#14734 
changelog: [`needless_for_each`] wrong suggestions when closure has no braces

Fix `needless_for_each` suggests wrongly when closure has no braces

---

clippy_lints/src/operators/assign_op_pattern.rs
clippy_lints/src/operators/mod.rs
clippy_utils/src/qualify_min_const_fn.rs
tests/ui/assign_ops.fixed
tests/ui/assign_ops.rs
tests/ui/assign_ops.stderr

Closes rust-lang/rust-clippy#14871 
----
changelog: [`assign_op_pattern`]: fix false positive on unstable const trait

Fix `assign_op_pattern` FP on unstable const trait

---

Cargo.toml

No breaking changes for clippy in this update (which only impacts the lint page).
The askama release information is [here](https://github.com/askama-rs/askama/releases/tag/v0.14.0).
r? @samueltardieu 
changelog: update askama version to `0.14.0`

Update `askama` to `0.14.0` version

---

clippy_lints/src/loops/manual_find.rs
tests/ui/manual_find_fixable.fixed
tests/ui/manual_find_fixable.rs
tests/ui/manual_find_fixable.stderr

Closes rust-lang/rust-clippy#14826 
changelog: [`manual_find`] fix wrong suggestions when return type needs adjustment

Fix `manual_find` suggests wrongly when return type needs adjustment

---

clippy_lints/src/methods/manual_is_variant_and.rs
clippy_lints/src/methods/mod.rs
tests/ui/manual_is_variant_and.fixed
tests/ui/manual_is_variant_and.rs
tests/ui/manual_is_variant_and.stderr

Fixes rust-lang/rust-clippy#14542.
changelog: [`manual_is_variant_and`]: Extend to check for boolean map comparisons
r? @samueltardieu

Extend `manual_is_variant_and lint` to check for boolean map comparisons

---

book/src/development/trait_checking.md

Fix the argument in the example for "Trait Checking".

[book] fix the trait checking example code

---

clippy_lints/src/panic_unimplemented.rs
clippy_lints/src/returns.rs
tests/ui/needless_return.fixed
tests/ui/needless_return.rs
tests/ui/needless_return.stderr

`if` expressions don't necessarily contain a block in the `else` part in the presence of an `else if`. The `else` part, if present, must be handled as a regular expression, not necessarily as a block expression.
Found while applying Clippy to triagebot and looking at the result. This also found an issue in Clippy itself.
changelog: [`needless_return`]: look inside `else if` parts as well

`needless_return`: look inside `else if` parts as well

---

clippy_lints/src/unit_return_expecting_ord.rs

This lint was previously written very clumsily, not short-circuiting and doing a lot of unnecessary work.
Now it makes sure to do the cheaper functions earlier and in general, is just smarter.
(I specifically focused on minimizing binder instantiation
Sadly, I'm not finding any relevant result in a benchmark. Still with the LLVM coverage instruments, the expensive bits are called lots of less times (The binder instantiation that I care about is reduced from 95k to 10k throughout our test suite).
changelog:[`unit_return_expecting_ord`]: Optimize the lint

Optimize `unit_return_expecting_ord`

---

clippy_lints/src/methods/mod.rs

This is mainly to avoid the phrase "more fast" since that is not idiomatic English
changelog: [`manual_contains`]: Improved documentation wording

Improve wording of `manual_contains` docs

---

util/gh-pages/index_template.html
util/gh-pages/script.js

Suppose it might be interesting to see up to date total number of lints something like this  

Show total count lints

---

clippy_lints/src/operators/modulo_arithmetic.rs

clean-up `modulo_arithmetic`

---

CHANGELOG.md
clippy_lints/src/declared_lints.rs
clippy_lints/src/format_args.rs
tests/ui/pointer_format.rs
tests/ui/pointer_format.stderr

I read a blog post about kernel security, and how various features might get lost while porting to Rust. In kernel C, they have some guardrails against divulging pointers. An easy way to replicate that in Rust is a lint for pointer formatting. So that's what this lint does.
---
changelog: new [`pointer_format`] lint

new restriction lint: pointer_format

---

util/gh-pages/script.js

In order to be consistent with our documentation, deprecated lints should not be counted when displaying the total number of lints on the [web site](https://rust-lang.github.io/rust-clippy/master/index.html).
For example, as of 2025-06-01, there are 784 non-deprecated lints which are referred to as "over 750 lints" in the documentation, but the web site displays "Total number: 799". When one new lint will be added, there will be a discrepancy ("over 750 lints" vs. "Total number: 800") if this is not fixed.
r? @llogiq

Do not count deprecated lints in lint total

---

clippy_lints/src/casts/cast_lossless.rs
clippy_lints/src/casts/cast_possible_truncation.rs
clippy_lints/src/casts/cast_possible_wrap.rs
clippy_lints/src/casts/cast_precision_loss.rs
clippy_lints/src/casts/fn_to_numeric_cast.rs
clippy_lints/src/casts/fn_to_numeric_cast_with_truncation.rs
clippy_lints/src/casts/utils.rs

`clippy_lints::casts::utils::int_ty_to_nbits` used to return `0` to indicate that the argument was not an integral type. It is more idiomatic to use `Option<u64>` as a return type.
Also, I've added a few `FIXME:` at places where only `f32` and `f64` are considered, as we now have `f16` and `f128` to deal with.

Use `None::<u64>` instead of `0` to denote an absence of value

---

clippy_utils/src/qualify_min_const_fn.rs
tests/ui/missing_const_for_fn/const_trait.fixed
tests/ui/missing_const_for_fn/const_trait.rs
tests/ui/missing_const_for_fn/const_trait.stderr

When determining when a function or method can be called from a `const` context, the determination must be made on the instance, not on the declaration. This makes a difference, for example, with `const_trait` traits whose implementations may or may not be `const`.
changelog: [`missing_const_for_fn`]: when checking if a function or method can be called from a `const` context, look at the concrete implementation rather than at the trait definition
Fixes rust-lang/rust-clippy#14658
r? @Jarcho

`missing_const_for_fn`: consider constness of instance

---

clippy_lints/src/disallowed_names.rs
tests/ui/disallowed_names.rs
tests/ui/disallowed_names.stderr

Fixes rust-lang/rust-clippy#14958
`disallowed_names` was used to lint code generated by macros. This behavior can confuse programmers who did not write the macro themselves. This change suppresses lints for code originating from macros, including external ones.
changelog: [`disallowed_names`] do not lint macro generated codes

Do not lint macro generated codes

---

CHANGELOG.md
clippy_lints/src/coerce_container_to_any.rs
clippy_lints/src/declared_lints.rs
clippy_lints/src/lib.rs
tests/ui/coerce_container_to_any.fixed
tests/ui/coerce_container_to_any.rs
tests/ui/coerce_container_to_any.stderr

This PR introduces a lint which detects when `&Box<dyn Any>` is coerced to `&dyn Any`, which is usually a mistake where the intent was to directly pass the `dyn Any` inside the box without coercion.
cc @llogiq 
Remaining work:
----
changelog: add [`coerce_container_to_any`] lint

Introduce coerce_container_to_any

---

clippy_utils/src/ty/mod.rs
tests/ui/crashes/ice-14935.rs

`clippy_utils::ty::InteriorMut::interior_mut_ty_chain` must stop recursing forever when types are chained indefinitely due to the use of associated types in generics. A false negative is acceptable, and documented here.
Should this situation be later identified specifically, a conversion of `Option` to `Result` would allow separating the infinitely recursive case from a negative one.
changelog: [`mutable_key_type`]: fix ICE when infinitely associated generic types are used
Fixes rust-lang/rust-clippy#14935

Do not recurse indefinitely while checking for inner mutability

---

clippy_lints/src/unused_unit.rs
tests/ui/unused_unit.edition2021.fixed
tests/ui/unused_unit.edition2024.fixed
tests/ui/unused_unit.rs

Given a type alias as follows, clippy would detect a false positive for `unused_unit`.
```rust
type UnusedParensButNoUnit = Box<dyn (Fn())>;
```
changelog: [`unused_unit`]: fix false positive for `Fn` bounds

Fix false positive for unused_unit

---

clippy_lints/src/cloned_ref_to_slice_refs.rs

Add missing word to `cloned_ref_to_slice_refs` docs

---

clippy_lints/src/ptr.rs
tests/ui/cmp_null.fixed
tests/ui/cmp_null.rs
tests/ui/cmp_null.stderr

Fixes rust-lang/rust-clippy#15010 
----
changelog: [`cmp_null`]: emit proper suggestion when pointer is checked for non-nullness

Invert suggestion if pointer is tested for non-nullness

---

clippy_lints/src/matches/match_single_binding.rs
tests/ui/match_single_binding.fixed
tests/ui/match_single_binding.rs
tests/ui/match_single_binding.stderr

Closes rust-lang/rust-clippy#14991 
----
changelog: [`match_single_binding`] fix missing curlies on type signatures

Fix `match_single_binding` misses curlies on type signatures

---

clippy_lints/src/loops/manual_flatten.rs
tests/ui/manual_flatten.fixed
tests/ui/manual_flatten.stderr

Closes rust-lang/rust-clippy#14692
The suggestion of `manual_flatten` does not includes the replacement of `if let` so far despite of `.flatten()` suggestion.
This PR eliminates a redundant `if let`.
changelog: [`manual_flatten`] the suggestion removes `if let`

Fixes `manual_flatten` removes the useless if let

---

clippy_lints/src/default.rs
clippy_lints/src/unit_types/unit_arg.rs
clippy_utils/src/lib.rs
tests/ui/unit_arg.rs
tests/ui/unit_arg.stderr
tests/ui/unit_arg_fixable.fixed
tests/ui/unit_arg_fixable.rs
tests/ui/unit_arg_fixable.stderr

Closes rust-lang/rust-clippy#14857 
changelog: [`unit_arg`] fix wrong suggestion for `Default::default`

Fix `unit_arg` suggests wrongly for `Default::default`

---

book/src/lint_configuration.md
clippy_config/src/conf.rs
clippy_lints/src/collapsible_if.rs
clippy_lints/src/loops/same_item_push.rs
clippy_lints/src/single_component_path_imports.rs
clippy_lints/src/undocumented_unsafe_blocks.rs
clippy_utils/src/lib.rs
tests/ui-toml/collapsible_if/collapsible_else_if.fixed
tests/ui-toml/collapsible_if/collapsible_else_if.rs
tests/ui-toml/collapsible_if/collapsible_else_if.stderr
tests/ui/collapsible_else_if.fixed
tests/ui/collapsible_else_if.rs
tests/ui/collapsible_if.fixed
tests/ui/collapsible_if.rs

Closes rust-lang/rust-clippy#14799 
changelog: [`collapsible_else_if`] fix FP on conditionally compiled stmt

Fix `collapsible_else_if` FP on conditionally compiled stmt

---

clippy_lints/src/doc/needless_doctest_main.rs
tests/ui/doc/needless_doctest_main.rs

Closes rust-lang/rust-clippy#8244 
Closes rust-lang/rust-clippy#15041
This feels like a bug with the compiler, because the panic happens when `Diag` is getting unwinded. However, `drop()` is already called in `.cancel()` so this should not happen. 
In this PR, I find a workaround to just call `emit()`, since the `DiagCtxt` here is just a `io::sink`, nothing will happen and the panic just goes away.
changelog: [`needless_doctest_main`] fix panic when doctest is invalid

Fix `needless_doctest_main` panic when doctest is invalid

---

clippy_utils/src/diagnostics.rs

Some of the docs in `clippy_utils/src/diagnostics.rs` were missing links to `span_lint`.

docs: add link to span_lint in diagnostics.rs.

---

clippy_lints/src/exhaustive_items.rs
tests/ui/exhaustive_items.fixed
tests/ui/exhaustive_items.rs
tests/ui/exhaustive_items.stderr

Closes rust-lang/rust-clippy#14992 
changelog: [`exhaustive_structs`] fix FP on structs with default valued field

Fix `exhaustive_structs` FP on structs with default valued field

---

clippy_lints/src/question_mark.rs
tests/ui/question_mark.fixed
tests/ui/question_mark.rs

Fixes rust-lang/rust-clippy#13642
changelog: Fix false positive in [`question_mark`] when else branch of let-else contains `#[cfg]`

Fix `clippy::question_mark` on let-else with cfg

---

clippy_lints/src/non_copy_const.rs
tests/ui/borrow_interior_mutable_const.rs

fixes rust-lang/rust-clippy#15069
----

Fix `non_copy_const` ICE

---

clippy_lints/src/empty_line_after.rs
tests/ui/empty_line_after/outer_attribute.1.fixed
tests/ui/empty_line_after/outer_attribute.2.fixed
tests/ui/empty_line_after/outer_attribute.rs
tests/ui/empty_line_after/outer_attribute.stderr

Fixes: rust-lang/rust-clippy#14980
changelog: Fix suggestion-cases-error of [`empty_line_after_outer_attr`]

Fix suggestion-cases-error of `empty_line_after_outer_attr`

---

clippy_lints/src/copies.rs
tests/ui/branches_sharing_code/shared_at_bottom.rs
tests/ui/branches_sharing_code/shared_at_bottom.stderr

The lint will note `the end suggestion probably needs some adjustments to use the expression result correctly` when the expr's is not unit. So I extend this note to also appear when the expr is in an assignment.
changelog: [`branches_sharing_code`] fix misleading suggestions when in assignment

Fix `branches_sharing_code` suggests misleadingly when in assignment

---

clippy_lints/src/matches/manual_ok_err.rs
tests/ui/manual_ok_err.fixed
tests/ui/manual_ok_err.rs
tests/ui/manual_ok_err.stderr

Closes rust-lang/rust-clippy#15051 
changelog: [`manual_ok_err`] fix wrong suggestions with references

Fix `manual_ok_err` suggests wrongly with references

---

clippy_lints/src/doc/needless_doctest_main.rs
tests/ui/doc/needless_doctest_main.rs
tests/ui/doc/needless_doctest_main.stderr

Optimize `needless_doctest_main`, make it short-circuit, make sure that we don't spin up a new compiler on EVERY code block.
---
The old implementation was creating a new compiler, new parser, new thread, new SessionGlobals, new everything for each code block. No matter if they actually didn't even contain `fn main()` or anything relevant.
On callgrind, seems that we're reducing about a 6.7242% de cycle count (which turns out to be a 38 million instruction difference, great!). Benchmarked in `bumpalo-3.16.0`. Also on bumpalo we spawn 78 less threads. This moves `SessionGlobals::new` from the top time-consuming function by itself in some benchmarks, into one not even in the top 500.
Also, populate the test files.
changelog:[`needless_doctest_main`]: Avoid spawning so many threads in …

[PERF] Don't spawn so many compilers (3/2) (19m -> 250k)

---

clippy_utils/src/sugg.rs
tests/ui/nonminimal_bool.stderr

For example, adding `*` in front of `*expression` is best shown as `**expression` rather than `*(*expression)`.
This is not perfect, as it checks whether the operator is already a prefix of the expression, but it is better than it was before. For example, `&`+`&mut x` will get `&&mut x` but `&mut `+`&x` will get `&mut (&x)` as it did before this change.

`Sugg`: do not parenthesize a double unary operator

---

clippy_lints/src/borrow_deref_ref.rs
tests/ui/borrow_deref_ref.fixed
tests/ui/borrow_deref_ref.rs
tests/ui/borrow_deref_ref.stderr

If a reborrow is itself borrowed mutably, do not propose to replace it by the original reference.
Fixes: rust-lang/rust-clippy#14934 
changelog: [`borrow_deref_ref`]: do not propose replacing a reborrow by the original reference if the reborrow is itself mutably borrowed

Fix false positive of `borrow_deref_ref`

---

clippy_dev/src/lint.rs
clippy_dev/src/serve.rs
clippy_lints/src/attrs/utils.rs
clippy_lints/src/methods/or_fun_call.rs
clippy_utils/src/sym.rs
lintcheck/src/main.rs
src/main.rs
tests/ui/or_fun_call.fixed
tests/ui/or_fun_call.rs
tests/ui/or_fun_call.stderr

Extend `or_fun_call` lint with new checks for Option::get_or_insert, Result::map_or.
changelog: [`or_fun_call`]: lint more methods

or_fun_call: lint more methods

---

tests/ui/unnecessary_os_str_debug_formatting.rs
tests/ui/unnecessary_os_str_debug_formatting.stderr

`unnecessary_debug_formatting` suggests display() respected for
MSRV but lacking of tests. This adds tests to check MSRV for OsStr.

Add MSRV test for `unnecessary_debug_formatting` with `OsStr`

---

CHANGELOG.md

changelog: link to the correct PR

---

CHANGELOG.md

Add beta-accepted to CHANGELOG for 1.88 since it was missed at rust-lang/rust-clippy#5095
r? flip1995

Add beta-accepted to CHANGELOG for 1.88

---

clippy_lints/src/doc/mod.rs
tests/ui/doc/doc_nested_refdef_list_item.fixed
tests/ui/doc/doc_nested_refdef_list_item.rs
tests/ui/doc/doc_nested_refdef_list_item.stderr

changelog: [`doc_nested_refdefs`]: fix false positive where [task lists](http://pulldown-cmark.github.io/pulldown-cmark/third_party/gfm_tasklist.html) are reported as refdefs

doc_nested_refdefs: do not falsely report checkboxes as refdefs

---

triagebot.toml

This is a newly added triagebot capability, which allows registering and then resolving concerns with an issue or a pull request. The concerns are gathered by Triagebot in the issue/PR summary.
Concerns are different from notes: when a concern is resolved, it is striked through in the issue/PR summary, and a link to the comment resolving it is also added, whereas a note can only be removed and then disappears from the summary.
The `has-concerns` label, which must be created at the time of merging this change, will be automatically set on issues/PRs that have unresolved concerns, and cleared when all concerns are resolved.

Add Triagebot's `concern` capability to the Clippy repository

---

util/gh-pages/index_template.html
util/gh-pages/style.css

This is the first pass of "reducing the size of the clippy lints page" I'm currently going through. This first one reduces the size page but mostly reduces the number of DOM elements.
Page size change:
* Before this PR: 1938957
* With this PR: 1876167
* Reduction: -3.2%
r? @Alexendoo 
changelog: Reduce page size and number of DOM elements on clippy lints page

Reduce page size and number of DOM elements on clippy lints page

---

util/gh-pages/index_template.html
util/gh-pages/script.js
util/gh-pages/style.css

Follow-up of rust-lang/rust-clippy#15140.
This time, I removed some unneeded `<span>` wrappings and some unneeded CSS classes. As usual, no changes in the UI.
Before this PR: 1876091
With this PR: 1751097
Reduction: -6.6%
r? @samueltardieu 
changelog: Reduce page size and number of DOM elements on clippy lints page

Simplify clippy lints page further

---

triagebot.toml

As I said in my on-vacation PR (a little bit late) I'm getting reincorporated into the review queue. Something that I'd like to do is implement the reviewer capacity system into Clippy, but seems that it's not supported yet. https://github.com/rust-lang/triagebot/issues/2007
r? @ghost
changelog:none

Not on vacation, again!

---

clippy_lints/src/no_effect.rs
tests/ui/unnecessary_operation.fixed
tests/ui/unnecessary_operation.rs

While `expr as T` can be removed as a statement if `expr` has no side-effect, the `as T` part alone cannot be removed if the type of `expr` would be ambiguous without the cast.
changelog: [`unnecessary_operation`]: do not remove casts if they are useful to type the expression
Fixes rust-lang/rust-clippy#15173

Do not remove `as` if it changes the type

---

clippy_lints/src/redundant_closure_call.rs
tests/ui/redundant_closure_call_fixable.fixed
tests/ui/redundant_closure_call_fixable.rs
tests/ui/redundant_closure_call_fixable.stderr

Fixes rust-lang/rust-clippy#9583 
When a closure with no parameters is called immediately after being defined, clippy can now suggest replacing the entire expression with just the closure's body.
----
changelog: [`redundant_closure_call`]: add fixes for closures with block

fix:  redundant_closure_call lint for closures with block

---

clippy_lints/src/neg_multiply.rs
tests/ui/neg_multiply.fixed
tests/ui/neg_multiply.rs
tests/ui/neg_multiply.stderr

Hi,
I noticed that the lint [neg_multiply](https://rust-lang.github.io/rust-clippy/master/index.html#neg_multiply) generates bad code when we call a method on the expression.
Consider `((a.delta - 0.5).abs() * -1.0).total_cmp(&1.0)`. Currently this would be changed by clippy to `-(a.delta - 0.5).abs() .total_cmp(&1.0)` - which does not compile because we are trying to negate an ordering enum - but what we really want is `(-(a.delta - 0.5).abs()).total_cmp(&1.0)`. 
This PR fixes this.
changelog: [`neg_multiply`] does not remove parenthesis anymore if a method is being called on the affected expression
NOTE: This is the first time I am contributing to clippy or the rust repo in general. So I am not sure whether my approach to fixing this issue is goo, if there are better solutions or if I …

FIX: NegMultiply should preserve parenthesis when method is called

---

clippy_lints/src/manual_let_else.rs
tests/ui/manual_let_else_match.fixed
tests/ui/manual_let_else_match.rs
tests/ui/manual_let_else_match.stderr

This commit also adds more test cases, which already worked but were mentioned in the issue.
Fixes rust-lang/rust-clippy#9939
changelog: [`manual_let_else`]: correctly handle binding subpattern with unused name

Handle potentially-shadowing bindings in `manual_let_else`

---

clippy_lints/src/methods/return_and_then.rs
clippy_utils/src/lib.rs
tests/ui/return_and_then.fixed
tests/ui/return_and_then.rs
tests/ui/return_and_then.stderr

The `TyCtxt::hir_get_fn_id_for_return_block()` function was too broad, as it will return positively even when given part of an expression that can be used as a return value. A new `potential_return_of_enclosing_body()` utility function has been made to represent the fact that an expression might be directly returned from its enclosing body.
changelog: [`return_and_then`]: prevent false positives in case of a partially used expression
Fixes rust-lang/rust-clippy#15111 
Fixes rust-lang/rust-clippy#14927
- [Beta-nomination](https://github.com/rust-lang/rust-clippy/pull/15115#issuecomment-2996222332) by [samueltardieu](https://github.com/samueltardieu)
*Managed by `@rustbot`—see [help](https://forge.rust-lang.org/triagebot/note.html) for details*

Properly check that an expression might be the one returned

---

clippy_lints/src/methods/or_fun_call.rs
tests/ui/or_fun_call.fixed
tests/ui/or_fun_call.rs
tests/ui/or_fun_call.stderr

<strike>build on top of rust-lang/rust-clippy#15071</strike>
This also adds ability to lint Option/Result::and method. Yes, this is not `or` method, but uses the same eager/lazy linting logic. Should i update lint description to list all checked structs/methods?
changelog: [`or_fun_call`]: lint Option/Result::and

or_fun_call: also lint `and` method for Option/Result

---

.github/workflows/lintcheck.yml
.github/workflows/lintcheck_summary.yml
lintcheck/src/config.rs
lintcheck/src/json.rs
lintcheck/src/main.rs

Previously https://github.com/rust-lang/triagebot/pull/1985
After a lintcheck run a comment will be created in the PR thread with an overview of the changes, example here https://github.com/Alexendoo/rust-clippy/pull/18#issuecomment-2880441316 (plus the normal GHA debugging experience)
It will only comment if there are some changes, if there's already an existing comment it will be updated for each run
Similar to https://github.com/rust-lang/team/blob/master/.github/workflows/dry-run.yml
The PR number is supplied by the lintcheck run, so technically someone could forge it to be annoying and edit the summaries in other threads, but that is pretty low impact and easy to deal with. There is a `pull_requests` field on the event but as @Kobzol [pointed out to …

Create summary comment for lintcheck runs

---

triagebot.toml

I think it's pretty common for a lint to be proposed for clippy only for consensus to be it belongs in rustc, and additionally sometimes bugs get filed here when the fault is actually with rustc.
https://forge.rust-lang.org/triagebot/transfer.html#issue-transfer

triagebot: enable issue transfer

---

clippy_lints/src/methods/unnecessary_map_or.rs
tests/ui/unnecessary_map_or.fixed
tests/ui/unnecessary_map_or.rs
tests/ui/unnecessary_map_or.stderr

Propose to replace `x.map_or(false, |y| y == z)` by `x == Some(z)` only if `x` is not adjusted. Otherwise, the type of `x` in the comparaison may not be the expected one, as it may be the product of an auto-deref.
changelog: [`unnecessary_map_or`]: do not propose to replace the `map_or` call by a comparaison if types wouldn't be correct
Fixes rust-lang/rust-clippy#15180

Do not remove method call if type is adjusted

---

clippy_lints/src/methods/manual_is_variant_and.rs
tests/ui/manual_is_variant_and.fixed
tests/ui/manual_is_variant_and.rs
tests/ui/manual_is_variant_and.stderr

When comparing `x.map(func) == Some(bool_lit)`, the value of `bool_lit` was ignored, despite the fact that its value should determine the value of the proposed expression.
`func` can be either a closure or a path. For the latter, η-expansion will be used if needed to invert the result of the function call.
changelog: [`manual_is_variant_and`]: fix inverted suggestions that could lead to code with different semantics
Fixes rust-lang/rust-clippy#15202 
- [Beta-nomination](https://github.com/rust-lang/rust-clippy/pull/15206#issuecomment-3034006613) by [samueltardieu](https://github.com/samueltardieu)
*Managed by `@rustbot`—see [help](https://forge.rust-lang.org/triagebot/note.html) for details*

Fix `manual_is_variant_and` condition generation

---

clippy_lints/src/needless_bool.rs
clippy_lints/src/operators/op_ref.rs
tests/ui/needless_bool_assign.fixed
tests/ui/needless_bool_assign.rs
tests/ui/needless_bool_assign.stderr
tests/ui/op_ref.fixed
tests/ui/op_ref.rs
tests/ui/op_ref.stderr

Closes rust-lang/rust-clippy#15063 
----
changelog: [`op_ref`]: fix wrongly showed macro definition in suggestions
changelog: [`needless_bool_assign`]: fix missing curlies when on else if

Fix multiple problems in #15063

---

.github/workflows/feature_freeze.yml

Delete the step and the conditional that checks `changes != '[]'` (`github.event.pull_request.changed_file`s returns the number of files changed in the pull request - not the list of changed files)
Escape newlines in the comment body safely
Use Bearer instead of deprecated token

Cleanup feature_freeze workflow

---

clippy_lints/src/disallowed_macros.rs
tests/ui/auxiliary/external_item.rs
tests/ui/used_underscore_items.rs

Fix few typos

---

clippy_lints/src/methods/or_fun_call.rs
clippy_lints/src/needless_pass_by_value.rs
clippy_utils/src/diagnostics.rs
tests/ui/or_fun_call.fixed
tests/ui/or_fun_call.rs
tests/ui/or_fun_call.stderr

<strike>blocked on rust-lang/rust-clippy#15073</strike>
Lint method calls inside `map_or` too, so for this, lint will be showed:
```rust
Some(4).map_or("asd".to_string().len() as i32, f);
```
previously it worked only for:
```rust
Some(4).map_or(slow_fun(), f);
```
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=bfcda42a6af446e69bc883a8b45eb13c
Sorry for multiple `or_fun_call` PRs.
changelog: [`or_fun_call`]: lint method calls inside map_or first arg

or_fun_call: lint method calls inside map_or first arg

---

clippy_lints/src/legacy_numeric_constants.rs
tests/ui/legacy_numeric_constants.fixed
tests/ui/legacy_numeric_constants.rs
tests/ui/legacy_numeric_constants.stderr

Fixes rust-lang/rust-clippy#15008
changelog: [`legacy_numeric_constants`]: fix suggestion when call is inside parentheses like `(i32::max_value())`

fix `legacy_numeric_constants` suggestion when call is wrapped in parens

---

clippy_lints/src/format_args.rs

Before this, you had to guess how to fix a `{:?}` formatting argument. I have happened to guess `{:?var}` in the past, got frustrated, and disabled the lint. This additional example would have saved me a bit of trouble.
changelog: [`uninlined_format_args`]: added an example of how to fix a `{:?}` parameter.

Add `uninlined_format_args` example for `{:?}`

---

clippy_utils/src/lib.rs
tests/ui/flat_map_identity.fixed
tests/ui/flat_map_identity.rs
tests/ui/flat_map_identity.stderr
tests/ui/map_identity.fixed
tests/ui/map_identity.rs
tests/ui/map_identity.stderr

changelog: [`map_identity`,`flat_map_identity`]: also recognize `|[x, y]| [x, y]`
fixes rust-lang/rust-clippy#15198

`{flat_,}map_identity`: recognize `|[x, y]| [x, y]` as an identity function as well

---

clippy_lints/src/approx_const.rs
tests/ui/approx_const.rs
tests/ui/approx_const.stderr

Fix some cases for `approx_const`:
- When the literal has more digits than significant ones, the string comparison wasn't working
- When numbers are formatted in a non trivial way (with leading `0`s or using `_`) the lint now finds those cases
changelog: [`approx_const`]: Fix when used over overly precise literals and non trivially formatted numerals
Fixes rust-lang/rust-clippy#15194

Fix `approx_const` for some new cases

---

clippy_lints/src/methods/mod.rs

Update `manual_is_variant_and` documentation to include equality comparison patterns
This commit updates the documentation for the `manual_is_variant_and` lint to include all linted cases. Previously, the documentation only mentioned the `.map(f).unwrap_or_default()` pattern, but the lint also catches equality comparison patterns like `option.map(f) == Some(true)` and `result.map(f) == Ok(true)`.
changelog: [`manual_is_variant_and`]: Update documentation to include equality comparison patterns
fixes rust-lang/rust-clippy#15217

Update manual_is_variant_and documentation to include equality comparison

---

clippy_lints/src/manual_abs_diff.rs
tests/ui/manual_abs_diff.fixed
tests/ui/manual_abs_diff.rs
tests/ui/manual_abs_diff.stderr

Closes rust-lang/rust-clippy#15254 
changelog: [`manual_abs_diff`] fix wrong suggestions behind refs

Fix `manual_abs_diff` suggests wrongly behind refs

---

clippy_lints/src/manual_assert.rs
tests/ui/manual_assert.edition2018.stderr
tests/ui/manual_assert.edition2021.stderr
tests/ui/manual_assert.rs

Closes rust-lang/rust-clippy#15227 
changelog: [`manual_assert`] fix wrong suggestions for macros

Fix `manual_assert` suggests wrongly for macros

---

clippy_lints/src/operators/manual_is_multiple_of.rs
clippy_utils/src/ty/type_certainty/mod.rs
tests/ui/manual_is_multiple_of.fixed
tests/ui/manual_is_multiple_of.rs
tests/ui/manual_is_multiple_of.stderr

Fix several issues with `manual_is_multiple_of`
- `&a % &b == 0` compiles, but requires dereferencing `b` when replacing with `a.is_multiple_of(b)`.
- In `a % b == 0`, if type of `a` is not certain, `a.is_multiple_of(b)` might not be typable.
- In `a % b == 0`, `a` and `b` must be unsigned integers, not any arbitrary types implementing `Rem` and outputing an integer.
Those fixes have required increasing the precision of type certainty determination in the two first patches.
Fixes rust-lang/rust-clippy#15203 
Fixes rust-lang/rust-clippy#15204 
changelog: [`manual_is_multiple_of`]: fix various false positive

Fix manual is multiple of

---

clippy_lints/src/methods/expect_fun_call.rs
tests/ui/expect_fun_call.fixed
tests/ui/expect_fun_call.rs
tests/ui/expect_fun_call.stderr

Previously expect_fun_call would too eagerly convert cases like `foo.expect(if | block | match)` into `foo.unwrap_or_else`. Additionally, it would also add to_string() even though the argument is being passed into format!() which can accept a &str. I also discovered some other cases where this lint would either produce invalid results, or be triggered unnecessarily:
- Clippy would suggest changing expect to unwrap_or_else even if the expression inside expect contains a return statement
- opt.expect(const_fn()) no longer triggers the lint
- The lint would always add braces to the closure body, even if the body of expect is a single expression
- opt.expect({"literal"}) used to get turned into ```opt.unwrap_or_else(|| panic!("{}", {"literal"}.to_string()))```
Fixes …

Fix expect_fun_call producing invalid suggestions

---

clippy_lints/src/methods/mod.rs
clippy_lints/src/useless_conversion.rs

Needed to split the lints crate.

`useless_conversion`: move all the impl to the same lint pass

---

util/gh-pages/index_template.html

This removes preserved spaces after lint name, marginally reducing page size.
Changing `~}}` into `-}}` will break things: lint name will touch copy buttons on it's right side.
cc @GuillaumeGomez as one who touched this last time

gh-pages: reduce page size by skipping spaces

---

rustc_tools_util/src/lib.rs

Fixes rust-lang/rust-clippy#15249
For the builtin rustc, it should return "dev" as the release channel. Clippy tests pass with this patch in both the Clippy standalone repository and from within the compiler repository.

Use `$RUSTC` instead of `rustc` to get version if var is available

---

clippy_lints/src/ptr.rs
tests/ui/ptr_arg.rs
tests/ui/ptr_arg.stderr

No longer suggests `&[i32]` or `&mut [i32]` instead of `&Vec<i32>` or `&mut Vec<i32>` (also: `Path` and `PathBuf`, etc.) for the parameter type when the parameter name starts with an underscore (or, if that does not start with one, then a local `let` binding in the function body, pointing to the same value, does) – (Fixes rust-lang/rust-clippy#13489, fixes rust-lang/rust-clippy#13728)
~changelog: fix false positive: [`ptr_arg`] no longer triggers with underscore binding to `&mut` argument~
changelog: fix false positive: [`ptr_arg`] no longer triggers with underscore binding to `&T` or `&mut T` argument
*Edit:* This change has been extended to all references, not just mutable ones. See [discussion below](#issuecomment-3006386877).

Fix `ptr_arg` suggests changes when it's actually better not to bother

---

clippy_lints/src/format_args.rs

Fixes https://github.com/rust-lang/rust-clippy/issues/15151
See also https://rust-lang.zulipchat.com/#narrow/channel/257328-clippy/topic/uninlined_format_args.20is.20contentious/
changelog: Move [`uninlined_format_args`] to `pedantic`

Move `uninlined_format_args` to `pedantic`

---

clippy_lints/src/cognitive_complexity.rs
clippy_lints/src/doc/mod.rs
clippy_lints/src/methods/manual_inspect.rs
clippy_lints/src/ranges.rs
tests/ui/range_plus_minus_one.fixed
tests/ui/range_plus_minus_one.rs
tests/ui/range_plus_minus_one.stderr

To avoid false positives, the `range_plus_one` and `range_minus_one` lints will restrict themselves to situations where the iterator types can be easily switched from exclusive to inclusive or vice-versa. This includes situations where the range is used as an iterator, or is used for indexing.
On the other hand, assignments of the range to variables, including automatically typed ones or wildcards, will no longer trigger the lint. However, the cases where such an assignment would benefit from the lint are probably rare.
In a second commit, the `range_plus_one` and `range_minus_one` logic are unified, in order to properly emit parentheses around the suggestion when needed.
Fix rust-lang/rust-clippy#3307
Fix rust-lang/rust-clippy#9908
changelog: [`range_plus_one`, `range_minus_one`]: …

Propose to exchange ranges only when it is safe to do so

---

clippy_lints/src/incompatible_msrv.rs
tests/ui-toml/check_incompatible_msrv_in_tests/check_incompatible_msrv_in_tests.enabled.stderr
tests/ui/checked_conversions.fixed
tests/ui/checked_conversions.rs
tests/ui/checked_conversions.stderr
tests/ui/incompatible_msrv.rs
tests/ui/incompatible_msrv.stderr

This PR supersedes #14328 following the [2025-03-18 Clippy meeting discussion](https://rust-lang.zulipchat.com/#narrow/channel/257328-clippy/topic/Meeting.202025-03-18/with/506527762). It uses a simpler approach than what was proposed initially in #14328 and does not add new options.
First, it documents how `cfg_attr` can be used to change the MSRV considered by Clippy to trigger the lint. This allows the MSRV to be feature gated, or to be raised in tests.
Also, the lint stops warning about items which have been explicitly allowed through a rustc feature. This works even if the feature has been stabilized since. It allows using an older compiler with some features turned on, as is done in Rust for Linux. This fixes #14425.
Then, if the lint triggers, and it looks like the code is located …

Various improvements to the `incompatible_msrv` lint

---

clippy_lints/src/casts/ptr_as_ptr.rs
tests/ui/ptr_as_ptr.fixed
tests/ui/ptr_as_ptr.rs
tests/ui/ptr_as_ptr.stderr

Closes rust-lang/rust-clippy#15283 
----
changelog: [`ptr_as_ptr`]: fix wrong suggestions with turbo fish

Fix `ptr_as_ptr` suggests wrongly with turbo fish

---

clippy_lints/src/incompatible_msrv.rs
tests/ui/incompatible_msrv.rs
tests/ui/incompatible_msrv.stderr

For example, the `Duration` type from the standard library was only introduced in Rust 1.3.0.
changelog: [`incompatible_msrv`]: recognize types exceeding MSRV as well
r? Jarcho @rustbot label +C-bug +I-false-negative

Warn about types not meeting MSRV

---

clippy_lints/src/incompatible_msrv.rs
tests/ui/incompatible_msrv.rs
tests/ui/incompatible_msrv.stderr

This makes `const` contexts use the `const`-stability version information instead of the regular stability one, as `const`-stability may happen much later than stability in non-`const` contexts.
~~It includes the content of PR rust-lang/rust-clippy#15296 as its first commit. I separated them because this one is more complex, and rust-lang/rust-clippy#15296 may be merged more rapidly.~~
changelog: [`incompatible_msrv`]: check the right MSRV when in a `const` context
r? Jarcho @rustbot label +C-bug +I-false-negative

Warn about `const` instability wrt MSRV

---

clippy_lints/src/functions/must_use.rs
tests/ui/must_use_candidates.fixed
tests/ui/must_use_candidates.stderr

This is blocking rust-lang/rust-clippy#14724

Simplify `must_use_candidate` spans

---

clippy_lints/src/loops/needless_range_loop.rs
tests/ui/needless_range_loop.rs

Closes rust-lang/rust-clippy#15309 
changelog: [`needless_range_loop`] fix FP on array literals

Fix `needless_range_loop` FP on array literals

---

clippy_lints/src/methods/filter_map_bool_then.rs
tests/ui/filter_map_bool_then.fixed
tests/ui/filter_map_bool_then.rs
tests/ui/filter_map_bool_then.stderr

Closes rust-lang/rust-clippy#15047 
changelog: [`filter_map_bool_then`] fix wrongly showed macro definitions in suggestions

Fix `filter_map_bool_then` wrongly suggests macro definitions

---

clippy_lints/src/matches/single_match.rs
tests/ui/single_match_else_deref_patterns.fixed
tests/ui/single_match_else_deref_patterns.rs
tests/ui/single_match_else_deref_patterns.stderr

Fixes rust-lang/rust-clippy#14882
changelog: [`single_match`]: fix ICE with deref patterns and string literals

Fix capacity overflow in `single_match` with deref patterns

---

clippy_lints/src/large_enum_variant.rs
tests/ui-toml/enum_variant_size/enum_variant_size.stderr
tests/ui/large_enum_variant.32bit.stderr
tests/ui/large_enum_variant.64bit.stderr
tests/ui/large_enum_variant_no_std.rs
tests/ui/large_enum_variant_no_std.stderr

Fixes rust-lang/rust-clippy#15192 by adding checks for no_std while giving out Box recommendation
```
changelog: [`large_enum_variant`]: Dont suggest `Box` in `no_std` mode
```

Fixed issue #15192

---

clippy_lints/src/attrs/useless_attribute.rs
clippy_utils/src/sym.rs
tests/ui/useless_attribute.fixed
tests/ui/useless_attribute.rs

Fix false positive in `useless_attribute` with `redundant_imports`
Add `redundant_imports` to the list of allowed lints on use items to prevent
`useless_attribute` from triggering false positives when `#[expect(redundant_imports)]`
or similar attributes are used on use statements.
fixes rust-lang/rust-clippy#15316
---
changelog: [`useless_attribute`]: fix false positive when using `#[expect(redundant_imports)]` and similar lint attributes on `use` statements

Fix false positive in useless_attribute with redundant_imports

---

clippy_lints/src/item_name_repetitions.rs
tests/ui/module_name_repetitions.rs

Closes rust-lang/rust-clippy#14095 
changelog: [`module_name_repetitions`] fix FP on exported macros

Fix `module_name_repetitions` FP on exported macros

---

clippy_lints/src/if_then_some_else_none.rs
clippy_utils/src/lib.rs
tests/ui/if_then_some_else_none.fixed
tests/ui/if_then_some_else_none.rs
tests/ui/if_then_some_else_none.stderr
tests/ui/if_then_some_else_none_unfixable.rs
tests/ui/if_then_some_else_none_unfixable.stderr

Closes rust-lang/rust-clippy#15257 
changelog: [`if_then_some_else_none`] fix FP when require type coercion

Fix `if_then_some_else_none` FP when require type coercion

---

clippy_lints/src/empty_with_brackets.rs
tests/ui/empty_structs_with_brackets.fixed
tests/ui/empty_structs_with_brackets.rs
tests/ui/empty_structs_with_brackets.stderr

Closes rust-lang/rust-clippy#15349
changelog: [`empty_structs_with_brackets`] fix wrong suggestions on generics

Fix `empty_structs_with_brackets` suggests wrongly on generics

---

clippy_lints/src/lib.rs
clippy_lints/src/unit_types/let_unit_value.rs
clippy_lints/src/unit_types/mod.rs
tests/ui/let_unit.fixed
tests/ui/let_unit.rs
tests/ui/let_unit.stderr

Closes rust-lang/rust-clippy#15061
changelog: [`let_unit_value`] fix wrong suggestions for format macros

Fix `let_unit_value` suggests wrongly for format macros

---

clippy_lints/src/non_std_lazy_statics.rs

Changes `MaybeIncorret` to `MaybeIncorrect`.
And since this is part of a doc comment, it might as well be a link.

Fix typo non_std_lazy_statics.rs

---

clippy_lints/src/casts/cast_lossless.rs
tests/ui/cast_lossless_integer_unfixable.rs

Closes rust-lang/rust-clippy#15348 
The span of the `as` expr is also incorrect, but I believe it is not a bug from Clippy.
changelog: [`cast-lossless`] fix wrong suggestions when casting type is from macro input

Fix `cast-lossless` should not suggest when casting type is from macro input

---

clippy_lints/src/four_forward_slashes.rs
tests/ui/four_forward_slashes_bare_cr.rs
tests/ui/four_forward_slashes_bare_cr.stderr

When a bare CR is present in a four slashes comment, keep triggering the lint but do not issue a fix suggestion as bare CRs are not supported in doc comments. An extra note is added to the diagnostic to warn the user about it. 
I have put the test in a separate file to make it clear that the bare CR is not a formatting error.
Fixes rust-lang/rust-clippy#15174 
changelog: [`four_forward_slashes`]: warn about bare CR in comment, and do not propose invalid autofix

Do not autofix comments containing bare CR

---

clippy_lints/src/methods/iter_on_single_or_empty_collections.rs
clippy_utils/src/ty/mod.rs
tests/ui/iter_on_single_items.fixed
tests/ui/iter_on_single_items.rs

Closes rust-lang/rust-clippy#14981
changelog: [`iter_on_single_items`] fix FP on function pointers and let stmts

Fix `iter_on_single_items` FP on function pointers and let stmts

---

clippy_lints/src/floating_point_arithmetic.rs
clippy_utils/src/sugg.rs
tests/ui/nonminimal_bool.rs
tests/ui/nonminimal_bool.stderr

When an expression is made of a `!` or `-` unary operator which does not change the type of the expression, use a new variant in `Sugg` to denote it. This allows replacing an extra application of the same operator by the removal of the original operator instead.
Some suggestions will now be shown as `x` instead of `!!x`. Right now, no suggestion seems to produce `--x`.

Optimize some usages of `!!` and `--` in suggestions

---

lintcheck/src/json.rs

The data in the table needs to be in the same order as the headings.
Fixes rust-lang/rust-clippy#15370

Output lintcheck summary HTML markdown in order

---

clippy_lints/src/index_refutable_slice.rs
clippy_test_deps/Cargo.lock
clippy_test_deps/Cargo.toml
clippy_utils/src/sym.rs
tests/compile-test.rs
tests/ui/index_refutable_slice/slice_indexing_in_macro.fixed
tests/ui/index_refutable_slice/slice_indexing_in_macro.rs
tests/ui/index_refutable_slice/slice_indexing_in_macro.stderr

Now that `if let` chains have been introduced, the `if_chain` external crate is no longer necessary. Dropping special support for it also alleviates the need to keep the crate as a dependency in tests.
This is a cleanup PR.

Do not specialize for `if_chain` any longer

---

clippy_lints/src/let_with_type_underscore.rs
tests/ui/let_with_type_underscore.fixed
tests/ui/let_with_type_underscore.rs
tests/ui/let_with_type_underscore.stderr

Apparently, one can surround a pattern with an arbitrary number of parens, and the resulting `Pat` won't include the span of those parens. And the previous approach extended the to-be-deleted span all the way to the end of `Pat`'s span, so it included the closing paren.
I think the new approach is more robust anyway, since all we care to remove (besides the `_`) is the `:`, so we search just for that.
~This does leave one extra whitespace in one of the test cases, but I'd say let rustfmt handle that.~ fixed in the third commit
changelog: [`let_with_type_underscore`]: don't eat closing paren in `let (i): _ = 0;`
fixes https://github.com/rust-lang/rust-clippy/issues/15377

fix: `let_with_type_underscore` don't eat closing paren in `let (i): _ = 0;`

---

clippy_utils/src/lib.rs
tests/ui/map_identity.fixed
tests/ui/map_identity.rs
tests/ui/map_identity.stderr

Follow-up of rust-lang/rust-clippy#15229, as described in https://github.com/rust-lang/rust-clippy/pull/15229#issuecomment-3050279790 -- it turned out to be not that difficult after all!
changelog: [`map_identity`,`flat_map_identity`]: also recognize (tuple) struct de- and resctructuring
r? @y21

`{flat_,}map_identity`: recognize (tuple) struct de- and restructuring

---

clippy_lints/src/manual_assert.rs
tests/ui/manual_assert.edition2018.stderr
tests/ui/manual_assert.edition2021.stderr

Fixes rust-lang/rust-clippy#15359
changelog: [`manual_assert`]: simplify boolean expression

Simplify boolean expression in `manual_assert`

---

clippy_lints/src/option_if_let_else.rs
tests/ui/option_if_let_else.fixed
tests/ui/option_if_let_else.rs
tests/ui/option_if_let_else.stderr

some simple twists
Fixes rust-lang/rust-clippy#15002 
Fixes rust-lang/rust-clippy#15379 
changelog: [`option_if_let_else`]: Don't remove raw pointer derefs in suggestions
changelog: [`option_if_let_else`]: Don't suggest passing argless functions to `Result::map_or_else`

fix option-if-let-else lint

---

clippy_lints/src/semicolon_block.rs

clean-up `semicolon_inside_block`

---

util/gh-pages/script.js

As discussed at rust-lang/rust-clippy#15387 revert changes https://github.com/rust-lang/rust-clippy/pull/15315 to show deprecated. 

Fix not showing deprecated lints

---

CONTRIBUTING.md

We can actualize "Issue and PR triage" section. Seems labels [P-medium](https://github.com/rust-lang/rust-clippy/labels/P-medium), [P-high](https://github.com/rust-lang/rust-clippy/labels/P-high), [L-sync-blocker](https://github.com/rust-lang/rust-clippy/labels/L-sync-blocker) are not relevant anymore. Suppose that we can save the priority from [feature freeze](https://github.com/alex-semenyuk/rust-clippy/blob/master/book/src/development/feature_freeze.md?plain=1) since the only difference accepting new lints. 

Issues priority

---

CHANGELOG.md
clippy_lints/src/declared_lints.rs
clippy_lints/src/formatting.rs
tests/ui/suspicious_else_formatting.rs
tests/ui/suspicious_else_formatting.stderr

This has always been one lint (added in rust-lang/rust-clippy#720), but the two cases are also quite distinct.
changelog: Split `possible_missing_else` from `suspicious_else_formatting`
- [Feature-freeze](https://github.com/rust-lang/rust-clippy/pull/15317#issuecomment-3094592022) by [github-actions[bot]](https://github.com/github-actions[bot])
*Managed by `@rustbot`—see [help](https://forge.rust-lang.org/triagebot/note.html) for details*

Split `possible_missing_else` from `suspicious_else_formatting`

---

clippy_lints/src/wildcard_imports.rs
tests/ui-toml/wildcard_imports/wildcard_imports.fixed
tests/ui-toml/wildcard_imports/wildcard_imports.rs
tests/ui-toml/wildcard_imports/wildcard_imports.stderr

Fixes rust-lang/rust-clippy#15412 
changelog: [`wildcard_imports`]: do not lint code coming from an external macro

Do not lint for `wildcard_imports` in external macro

---

.github/ISSUE_TEMPLATE/new_lint.yml

When I first tried contributing to clippy,
I encountered the problem that a lot of lint suggestions overlapped with existing lints, so I would spend a bunch of time implementing something only to figure out it wasn't actually needed.
The "comparison with existing lints" field should hopefully reduce this somewhat, while not incresing the burden of
requesting a new lint too much due to not being mandatory.

expand the issue template for new lints

---

clippy_lints/src/needless_bool.rs

Two optimizations have been done when checking for the context in which to apply the lint:
- Checking for the mere presence of comments does not require building a `String` with the comment to then check if it is empty and discard it.
- Checking for the presence of comment can be done after we have checked that we do have a `if` construct that we intend to lint instead of for every expression.
r? blyxyas

Optimize `needless_bool` lint

---

.github/ISSUE_TEMPLATE/new_lint.yml

Small typo I found while looking at recent lint requests/issues.

Fix typo in lint issue template

---

clippy_lints/src/eta_reduction.rs
tests/ui/eta.fixed
tests/ui/eta.rs
tests/ui/eta.stderr

fixes https://github.com/rust-lang/rust-clippy/issues/8817
changelog: [`eta_reduction`]: don't refer to ADT constructors as "function"s

`eta_reduction`: don't refer to ADT constructors as "function"s

---

clippy_lints/src/loops/infinite_loop.rs
tests/ui/infinite_loops.rs
tests/ui/infinite_loops.stderr

changelog: [infinite_loop]: Improve handling of infinite loops in async blocks
Fix rust-lang/rust-clippy#14000 
This PR refines the [infinite_loop] lint to avoid false positives when infinite loops occur inside async blocks that are not awaited (such as those that are spawned or assigned to variables for later use). The lint will now only trigger when the async block containing the loop is directly awaited.

[[infinite_loop] fix infinite loop false positive

---

book/src/development/common_tools_writing_lints.md

see https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or

doc: use `is_some_and` instead of `map_or(false, _)`

---

clippy_lints/src/non_copy_const.rs

Per the root readme, `clippy::style` is a category with
> code that should be written in a more idiomatic way
description.
The code this lint guards from may be much worse than badly styled:
```rs
use std::sync::LazyLock;
// `const` instead of `static` causes `dbg!` to be printed 10 times
// instead of one.
const LICENSE_FILE_NAME_REGEX: LazyLock<String> = LazyLock::new(|| {
dbg!("I am a large regex initialized in a lazy lock!");
format!("Hello {}", "World".to_string())
});
fn main() {
for _ in 0..10 {
let _ = LICENSE_FILE_NAME_REGEX.split(" ");
}
}
```
In large projects, it's unfortunate but sometimes possible to see style lints suppressed with
```toml
[workspace.lints.clippy]
style = { level = "allow", priority = -1 }
```
effectively turning off crucial checks for the code like above. …

Adjust `declare_interior_mutable_const` lint's category

---

clippy_lints/src/functions/result.rs

`result_large_err`: get `DefId` from `AdtDef` instead of `expect`ing

---

clippy_lints/src/no_effect.rs
tests/ui/unnecessary_operation.fixed
tests/ui/unnecessary_operation.stderr

makes the suggestion a bit more legible
changelog: [`unnecessary_operation`]: add space between stmts in suggestion

`unnecessary_operation`: add space between stmts in suggestion

---

clippy_lints/src/unwrap.rs

clean-up `unnecessary_unwrap` a bit

---

clippy_lints/src/non_expressive_names.rs
clippy_utils/src/ast_utils/mod.rs
tests/ui/similar_names.rs
tests/ui/similar_names.stderr

fixes rust-lang/rust-clippy#14869
Added a simple check if both chars are of length 3
If they are, we skip the check for that pair.
This won't handle the 4 v 3 case.
Not sure if this was the intent of the issue.
Also saw we have some hardcoded exemptions for `set, get` and `lhs, rhs`
Tried removing them thinking they would be handled by the new condition.
But we have to keep because they allow for `bla_lhs` v `bla_rhs` to be skipped
changelog:[`similar_names`]: Stop triggering for 3-character names

`similar_names` stop linting for 3-char names

---

clippy_lints/src/collapsible_if.rs

clean-up `collapsible_if` a bit

---

clippy_lints/src/matches/match_bool.rs
tests/ui/match_bool.fixed
tests/ui/match_bool.rs

changelog: [`match_bool`]: do not replace `match` by `if` if any arm contains a binding
Fixes rust-lang/rust-clippy#15351

Do not replace `match` by `if` if any arm contains a binding

---

clippy_lints/src/ptr.rs

`ptr_arg`: clean-up a bit

---

clippy_lints/src/functions/renamed_function_params.rs

`renamed_function_params`: clean-up a bit

---

CHANGELOG.md

https://github.com/rust-lang/rust-clippy/issues?q=state%3Aclosed%20label%3Abeta-accepted
Those were missed in the prior backport. The two beta-accepted issues that were not added were done as reverts of the prior changes they fixed. So no reason to add them to the changelog.

Add 1.89 beta-accepted changes to changelog

---

clippy_utils/src/ast_utils/mod.rs
clippy_utils/src/hir_utils.rs
clippy_utils/src/lib.rs

This makes the last arm significantly shorter, but marginally shortens the other ones as well
- I first removed the length comparisons from the match guards since they were already present in `(unordered_)over`, but then brought them back since they are quite a helpful "guard clause"
- It's a bit unfortunate that the `Slice`/`Array` arm can't use `over` as well, which creates some asymmetry, but changing the signature of `over` to accept arbitrary iterators felt like too much to me, especially because we'd lose the ability to compare the lengths of the two inputs (which could've been mitigated by `ExactLenIterator::len`, but that method is still unstable AFAIR)
One other option would be to only use `unordered_over` in the last arm, and not `over`, but I think `over` is not that bad.. …

`is_expr_identity_of_pat`: simplify using `(unordered_)over`

---

clippy_lints/src/needless_bool.rs
tests/ui/bool_comparison.fixed
tests/ui/bool_comparison.rs
tests/ui/bool_comparison.stderr

Fixes https://github.com/rust-lang/rust-clippy/issues/15497
changelog: [`bool_comparison`]: fix incorrect suggestion with `>`/`<` and macros

bool_comparison: fix incorrect suggestion with `>`/`<` and macros

---

clippy_lints/src/needless_bool.rs
tests/ui/bool_comparison.fixed
tests/ui/bool_comparison.rs
tests/ui/bool_comparison.stderr
tests/ui/needless_bool/fixable.stderr
tests/ui/nonminimal_bool.rs
tests/ui/nonminimal_bool.stderr

The issue that this PR was opened to fix (https://github.com/rust-lang/rust-clippy/issues/15367), talked about how, for `!x == false`, this lint suggests both:
1. `x != false`
2. `x`
I initially wanted to make the lint short-circuit after emitting the first suggestion (since that was the easier change code-wise), but that was not optimal for two reasons:
1. suggestion 2 is obviously better (the other one requires one more round of Clippy)
2. suggestion 1 is actually already covered by `nonminimal_bool`
And so I instead decided to completely remove the code path that emits suggestion 1.  
Fixes https://github.com/rust-lang/rust-clippy/issues/15367
changelog: [`bool_comparison`]: no longer lint on `!x != y`

`bool_comparison`: no longer lint on `!x != y`

---

clippy_lints/src/derivable_impls.rs
clippy_lints/src/matches/significant_drop_in_scrutinee.rs
tests/ui/derivable_impls.fixed
tests/ui/derivable_impls.rs
tests/ui/derivable_impls.stderr
tests/ui/derivable_impls_derive_const.fixed
tests/ui/derivable_impls_derive_const.rs
tests/ui/derivable_impls_derive_const.stderr

Closes rust-lang/rust-clippy#15493 
Closes rust-lang/rust-clippy#15536
changelog: [`derivable_impls`] fix wrong suggestions on `derive_const`

Fix `derivable_impls` suggests wrongly on `derive_const`

---

clippy_lints/src/unnested_or_patterns.rs
tests/ui/unnested_or_patterns.fixed
tests/ui/unnested_or_patterns.rs
tests/ui/unnested_or_patterns.stderr

changelog: [`unnested_or_patterns`]: FP on structs with only shorthand field patterns
fixes rust-lang/rust-clippy#15219

fix: `unnested_or_patterns` FP on structs with only shorthand field pats

---

clippy_lints/src/casts/ptr_cast_constness.rs

clean-up `ptr_cast_constness`

---

clippy_lints/src/methods/or_then_unwrap.rs
tests/ui/or_then_unwrap.fixed
tests/ui/or_then_unwrap.rs
tests/ui/or_then_unwrap.stderr

Before this change, the suggestion for
`Option.or(Some(vec![])).unwrap()` expanded the `vec!` macro which broke the code, both in terms of readability, and because the expansion references `$crate` which cannot be inlined.
changelog: [`or_then_unwrap`]: Preserve macro calls rather than expanding them
Relates to rust-lang/rust-clippy#6851

fix `or_then_unwrap`: suggestion preserves macro calls

---

clippy_lints/src/operators/float_equality_without_abs.rs
tests/ui/float_equality_without_abs.rs
tests/ui/float_equality_without_abs.stderr

followup of https://github.com/rust-lang/rust/pull/141874
cc https://github.com/rust-lang/rust/issues/116909
changelog: check f16 and f128 in float_equality_without_abs

check f16 and f128 in float_equality_without_abs

---

clippy_lints/src/casts/cast_ptr_alignment.rs
clippy_lints/src/casts/mod.rs

This lint consists of two distinct cases: one for the `as` cast, and one for `.cast()`. Splitting them in two separate functions allowed moving the `as` one into the `if let ExprKind::Cast` branch of `casts/mod.rs`, and reusing the variables created there

split `cast_ptr_alignment`

---

clippy_lints/src/semicolon_block.rs
tests/ui/semicolon_inside_block.fixed
tests/ui/semicolon_inside_block.rs
tests/ui/semicolon_inside_block_stmt_expr_attrs.fixed
tests/ui/semicolon_inside_block_stmt_expr_attrs.rs
tests/ui/semicolon_inside_block_stmt_expr_attrs.stderr

Closes rust-lang/rust-clippy#15388 
changelog: [`semicolon_inside_block`] fix FP when attribute over expr is not enabled

Fix `semicolon_inside_block` FP when attribute over expr is not enabled

---

clippy_lints/src/mut_reference.rs
tests/ui/mut_reference.fixed
tests/ui/mut_reference.stderr

resolves https://github.com/rust-lang/rust-clippy/issues/8943
changelog: [`unnecessary_mut_passed`]: add structured suggestion

`unnecessary_mut_passed`: add structured suggestion

---

clippy_lints/src/unused_unit.rs
tests/ui/unused_unit.edition2021.fixed
tests/ui/unused_unit.edition2021.stderr
tests/ui/unused_unit.edition2024.fixed
tests/ui/unused_unit.rs

As discussed in [#clippy > #15035](https://rust-lang.zulipchat.com/#narrow/channel/257328-clippy/topic/.2315035)
Fixes https://github.com/rust-lang/rust-clippy/issues/15035
changelog: [`unused_unit`] don't lint on closure return types

`unused_unit`: don't lint on closure return types

---

clippy_utils/src/lib.rs

Noticed when reviewing rust-lang/rust-clippy#15562.
Part of rust-lang/rust-clippy#15569.

Document `is_unit_expr()`

---

clippy_lints/src/matches/collapsible_match.rs
clippy_lints/src/matches/mod.rs
clippy_utils/src/lib.rs
tests/ui/collapsible_match.rs
tests/ui/collapsible_match.stderr
tests/ui/collapsible_match2.stderr

Fixes: #14155
If an expression is borrowed/dereferenced, suggest using `.as_ref()` or `.copied()` respectively in the outer conditional statement.
changelog: [`collapsible_match`] suggests ref/dereferencing when needed.

fix: `collapsible_match` suggests ref/derefs when needed

---

triagebot.toml

[This feature](https://forge.rust-lang.org/triagebot/review-changes-since.html) adds a handy link to each review message (it doesn't create a new comment) that allows the reviewer or other people to check what has been changed in the PR since the review took place.
r? flip1995

triagebot: Amend a review to include a link to what was changed since

---

clippy_lints/src/methods/map_identity.rs
tests/ui/map_identity.fixed
tests/ui/map_identity.rs
tests/ui/map_identity.stderr

While working on rust-lang/rust-clippy#15229, I noticed a test case in `map_identity` which avoids linting in the case where removing the `.map()` would require the iterator variable to be made mutable. But then I saw rust-lang/rust-clippy#14140, and thought I'd try to adapt its approach, by suggesting both removing the `.map()` _and_ making the variable mutable.
This is WIP only because I'm not sure about the very last `diag.span_note` -- I think having a method chained immediately after the `.map()` is the only case which requires adding `mut`, so it should be safe to say that `method_requiring_mut` is always `Some`. I'd like to do a lintcheck run to see if that's actually true.
@samueltardieu do you think this is a good approach? Maybe there are more lints where we could lint + suggest …

`map_identity`: suggest making the variable mutable when necessary

---

clippy_lints/src/write.rs
tests/ui/print_literal.fixed
tests/ui/print_literal.rs
tests/ui/print_literal.stderr

Closes rust-lang/rust-clippy#15576 
changelog: [`numbered arg`] fix wrong suggestions for inline literal following a numbered arg

Fix `print_literal` suggests wrongly for inline literal following a numbered arg

---

clippy_lints/src/loops/needless_range_loop.rs
tests/ui/needless_range_loop.rs
tests/ui/needless_range_loop.stderr

Fixes  rust-lang/rust-clippy#15068
changelog: Fix [`needless_range_loop`] false positive and false negative when meeting multidimensional array

Fix FP of `needless_range_loop` when meeting multidimensional array

---

clippy_lints/src/if_then_some_else_none.rs
tests/ui/if_then_some_else_none.fixed
tests/ui/if_then_some_else_none.rs
tests/ui/if_then_some_else_none.stderr

The first statement of the block might have been in a different context from the expression. Walk up to the right context to get bounds properly.
Also, switch to `snippet_with_applicability()` since we know that we are in the right context already.
changelog: [`if_then_some_else_none`]: emit well-formed suggestion, and do not lint inside macros
Fixes rust-lang/rust-clippy#15005

Get the block content from the proper context

---

clippy_lints/src/assertions_on_result_states.rs
tests/ui/assertions_on_result_states.fixed
tests/ui/assertions_on_result_states.rs
tests/ui/assertions_on_result_states.stderr

Fixes https://github.com/rust-lang/rust-clippy/issues/9916
changelog: [`assertions_on_result_states`]: avoid changing return type in more cases

fix: `assertions_on_result_states` avoid changing return type in more cases

---

clippy_lints/src/map_unit_fn.rs
tests/ui/option_map_unit_fn_fixable.fixed
tests/ui/option_map_unit_fn_fixable.rs
tests/ui/option_map_unit_fn_fixable.stderr

changelog: [`option_map_unit`]: preserve `unsafe` blocks
Fixes rust-lang/rust-clippy#15568

Preserve `unsafe` blocks in `option_map_unit` suggestion

---

clippy_lints/src/semicolon_block.rs
tests/ui/semicolon_inside_block.fixed
tests/ui/semicolon_inside_block.rs
tests/ui/semicolon_inside_block.stderr

Decided not to lint in this case after all, as per https://github.com/rust-lang/rust-clippy/pull/15391#issuecomment-3146878801
Supersedes https://github.com/rust-lang/rust-clippy/pull/15421, fixes https://github.com/rust-lang/rust-clippy/issues/15380, fixes https://github.com/rust-lang/rust-clippy/issues/15389
changelog: [`semicolon_inside_block`]: don't lint if block is in parens

fix(semicolon_inside_block): don't lint if block is in parens

---

clippy_lints/src/returns/needless_return.rs
tests/ui/needless_return.fixed
tests/ui/needless_return.rs

Fixes https://github.com/rust-lang/rust-clippy/issues/14474
changelog: [`needless_return`]: FP with `cfg`d code after `return`

fix(needless_return): FP with `cfg`d code after `return`

---

clippy_lints/src/uninit_vec.rs

Remove expected `collapsible_span_lint_calls` and use `span_lint_and_help` since rust-lang/rust-clippy#7698 was resolved 
changelog:none

Remove expect `collapsible_span_lint_calls` and use `span_lint_and_help`

---

clippy_utils/src/source.rs

This is useful for using it with `dbg!()`.
r? Jarcho

Implement `Debug` for `SourceText`

---

clippy_lints/src/multiple_unsafe_ops_per_block.rs
tests/ui/multiple_unsafe_ops_per_block.rs
tests/ui/multiple_unsafe_ops_per_block.stderr

Fixes https://github.com/rust-lang/rust-clippy/issues/13879
changelog: [`multiple_unsafe_ops_per_block`]: ignore unsafe ops from `.await` desugaring

fix(multiple_unsafe_ops_per_block): ignore unsafe ops from `.await` desugaring

---

tests/ui/never_loop_fixable.fixed
tests/ui/never_loop_fixable.rs

Noticed while working on rust-lang/rust-clippy#15673.

Remove unnecessary `#![allow]` in test

---

clippy_lints/src/question_mark.rs
tests/ui/question_mark.fixed
tests/ui/question_mark.rs
tests/ui/question_mark.stderr

This recognizes the following expression as being equivalent to the question mark:
```rust
match x {
Ok(v) => v,
Err(e) => return Err(e.into()), // or `Into::into(x)` or `<T as Into<U>>::into(x)`
}
```
Fixes rust-lang/rust-clippy#15679 
changelog: [`question_mark`]: recognizes a match with an early return with a call to `.into()` as possibly equivalent to a question mark

Recognize canonical `?` pattern with `Result`

---

clippy_lints/src/transmute/transmute_ptr_to_ref.rs
tests/ui/transmute_ptr_to_ref.fixed
tests/ui/transmute_ptr_to_ref.rs
tests/ui/transmute_ptr_to_ref.stderr

Fixes https://github.com/rust-lang/rust-clippy/issues/13357
Determining the exact placement of the `if !to_ref_ty.is_sized()`s required meticulously constructing the suggestion/truth table of `is_sized`, `msrv.meets` and `has_erased_regions`. The test cases should hopefully cover all the new combinations.
changelog: [`transmute_ptr_to_ref`]: don't suggest `.cast` when to-type is DST

fix(transmute_ptr_to_ref): don't suggest `.cast` when to-type is DST

---

clippy_lints/src/unwrap.rs
tests/ui/checked_unwrap/simple_conditionals.rs
tests/ui/checked_unwrap/simple_conditionals.stderr

Fix `unnecessary_unwrap` false negative when unwrapping a known value inside a macro call
Fixes rust-lang/rust-clippy#12295
Produces no changes to `lintcheck`
changelog: [`unnecessary_unwrap`]: Fix false negative when unwrapping a known value inside a macro call
I made sue to run `cargo dev fmt`.
I also ran the following checks (in order) on a fresh clone of mi fork:
1. `cargo build`
2. `cargo test`
3. `cargo lintcheck`
Running `cargo test` after `lintcheck` causes a test to fail, but this also happens on a clean fork without my changes

Fix `unnecessary_unwrap` false negative (#12295)

---

tests/no-profile-in-cargo-toml.rs

This test, which checks that we do not define new profiles directly in Clippy's multiple `Cargo.toml` files, must not look inside `target` as `lintcheck` might place some third-party sources there. Of course those third-party sources are allowed to define profiles in their `Cargo.toml`.

Do not look for `Cargo.toml` inside `target`

---

clippy_lints/src/item_name_repetitions.rs
tests/ui/module_inception.rs

* Don't check for repetition if the previous module crosses a body boundary.
* Don't take a snippet of the entire item.
* Check each item's visibility once.
* Use `is_from_proc_macro` before linting

Rework `module_inception`

---

clippy_lints/src/nonstandard_macro_braces.rs
tests/ui-toml/nonstandard_macro_braces/conf_nonstandard_macro_braces.fixed
tests/ui-toml/nonstandard_macro_braces/conf_nonstandard_macro_braces.rs
tests/ui-toml/nonstandard_macro_braces/conf_nonstandard_macro_braces.stderr

Fixes https://github.com/rust-lang/rust-clippy/issues/9913
changelog: [`nonstandard_macro_braces`]: suggest trailing semicolon when needed

fix `nonstandard_macro_braces`: suggest trailing semicolon when needed

---

clippy_lints/src/matches/single_match.rs
tests/ui/single_match.fixed
tests/ui/single_match.rs
tests/ui/single_match.stderr

clean-up `single_match` a bit

---

clippy_lints/src/derive/derive_ord_xor_partial_ord.rs
clippy_lints/src/derive/derive_partial_eq_without_eq.rs
clippy_lints/src/derive/derived_hash_with_manual_eq.rs
clippy_lints/src/derive/expl_impl_clone_on_copy.rs
clippy_lints/src/derive/mod.rs
clippy_lints/src/derive/unsafe_derive_deserialize.rs
tests/ui/derive.rs
tests/ui/derive.stderr
tests/ui/derive_ord_xor_partial_ord.rs
tests/ui/derived_hash_with_manual_eq.rs

Out of the 5 lints in the `derive` directory, only two of them (`unsafe_derive_deserialize` and `derive_partial_eq_without_eq`) posted the lint on the ADT node. This fixes the situation for the three other lints:
- `derived_hash_with_manual_eq`
- `derive_ord_xor_partial_ord`
- `expl_impl_clone_on_copy`
This allows `#[expect]` to be used on the ADT to silence the lint.
Also, this makes `expl_impl_clone_on_copy` properly use an "help" message instead of a "note" one when suggesting a fix.
Fixes rust-lang/rust-clippy#15708
Fixes rust-lang/rust-clippy#13356
changelog: [`derived_hash_with_manual_eq`]: honor the use of `#[expect]` on the type to which the lint applies
changelog: [`derive_ord_xor_partial_ord`]: honor the use of `#[expect]` on the type to which the lint applies
changelog: …

Post lint on the type HIR node

---

clippy_lints/src/default_constructed_unit_structs.rs

`default_constructed_unit_structs`: use `check_source_text`

---

clippy_lints/src/lib.rs
clippy_lints/src/mut_mut.rs
tests/ui/mut_mut.fixed
tests/ui/mut_mut.rs
tests/ui/mut_mut.stderr
tests/ui/mut_mut_unfixable.rs
tests/ui/mut_mut_unfixable.stderr

This PR:
- adds structured suggestions to all 3 lint scenarios
- adds more examples of linted patterns, and recommended fixes
- moves some test cases to `_unfixable.rs`, to allow running rustfix on the main file
- stops the lint from firing multiple times on types like `&mut &mut &mut T`
Open questions:
- I'd like to add a note explaining why chained `&mut` are useless.. but can't really come up with something consice. I very much don't like the one in the docs -- it's a bit too condescending imo.
- see comments in the diff for more
I do realize that the PR ended up being quite wide-scoped, but that's primarily because once I added structured suggestions to one of the lint cases, `ui_test` started complaining about warnings remaining after the rustfix run, which of course had to with the …

overhaul `mut_mut`

---

clippy_lints/src/methods/lib.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/should_implement_trait.rs
clippy_lints/src/methods/wrong_self_convention.rs
tests/ui/should_impl_trait/method_list_1.edition2015.stderr
tests/ui/should_impl_trait/method_list_1.edition2021.stderr
tests/ui/should_impl_trait/method_list_1.rs
tests/ui/should_impl_trait/method_list_2.edition2015.stderr
tests/ui/should_impl_trait/method_list_2.edition2021.stderr
tests/ui/should_impl_trait/method_list_2.rs

Fixes https://github.com/rust-lang/rust-clippy/issues/6752
changelog: [should_implement_trait]: only suggest traits that are in the prelude

fix(should_implement_trait): only suggest traits that are in the prelude

---

clippy_lints/src/double_parens.rs
tests/ui/double_parens.fixed
tests/ui/double_parens.rs
tests/ui/double_parens.stderr

The issue that I saw made me rethink the lint design by quite a lot, so I decided to include that change in this PR
fixes rust-lang/rust-clippy#9000
changelog: [`double_parens`]: add structured suggestions
changelog: [`double_parens`]: fix FP when macros are involved

`double_parens`: add structured suggestions, fix bug

---

clippy_lints/src/mem_replace.rs
tests/ui/mem_replace.fixed
tests/ui/mem_replace.rs
tests/ui/mem_replace.stderr

Closes rust-lang/rust-clippy#15785 
changelog: [`mem_replace_with_default`] fix wrongly unmangled macros

Fix `mem_replace_with_default` wrongly unmangled macros

---

clippy_lints/src/matches/match_same_arms.rs

clean-up `match_same_arms` a bit

---

book/src/lint_configuration.md
clippy_config/src/conf.rs
clippy_lints/src/collapsible_if.rs
clippy_lints/src/lib.rs
clippy_lints/src/unwrap.rs
clippy_utils/src/lib.rs
tests/ui/checked_unwrap/if_let_chains.rs
tests/ui/checked_unwrap/if_let_chains.stderr

This might be due to a low edition (< 2024) or too low a MSRV. In this case, we will suggest only `match`.
Fixes rust-lang/rust-clippy#15744 
changelog: [`unnecessary_unwrap`]: do not suggest using `if let` chains if this is not supported with the current edition or MSRV
changelog:[`collapsible_if`]: Do not suggest using `if let` if this is not supported with the current edition or MSRV

Do not suggest using a `if let` chain if it is not supported

---

clippy_lints/src/methods/map_identity.rs

Instead of calling `span_lint_and_*` in multiple places, call
`span_lint_and_then` once and then use the `Diag` methods.
Diff best viewed with whitespace ignored

`map_identity`: simplify lint emission

---

clippy_lints/src/unit_types/let_unit_value.rs
tests/ui/let_unit.fixed
tests/ui/let_unit.rs
tests/ui/let_unit.stderr

Closes rust-lang/rust-clippy#15789 
changelog: [`let_unit_value`] fix wrong suggestions for field init shorthand

Fix `let_unit_value` suggests wrongly for field init shorthand

---

clippy_lints/src/zero_repeat_side_effects.rs
tests/ui/zero_repeat_side_effects.fixed
tests/ui/zero_repeat_side_effects.rs
tests/ui/zero_repeat_side_effects.stderr

Fixes https://github.com/rust-lang/rust-clippy/issues/14681
changelog: [`zero_repeat_side_effects`]: better identify exprs with side effects

fix(zero_repeat_side_effects): better identify exprs with side effects

---

clippy_lints/src/matches/redundant_pattern_match.rs

- cast `&[Arm]` to `&[Arm; 2]` early on to hopefully avoid bounds checks
- use `if let [pattern] = X { .. }` instead of `if let patterns = X { let pattern = patterns[0]; .. }`
- use `Symbol`s instead of `&str`s
- reduce indentation
Diff best viewed with whitespace ignored

`redundant_pattern_match`: clean-up

---

clippy_lints/src/methods/should_implement_trait.rs

This might positively affect performances of the `should_implement_trait` lint.
r? blyxyas

Cleanup `should_implement_trait` lint code

---

clippy_lints/src/deprecated_lints.rs

Some lints had a wrong deprecated version on the documentation (I didn't check all of them, just recent ones).
Fixes rust-lang/rust-clippy#15811 
changelog: [`match_on_vec_items`]: Fixed the deprecation version to "1.88.0"
changelog: [`option_map_or_err_ok `]: Fixed the deprecation version to "1.87.0"
changelog: [`string_to_string `]: Fixed the deprecation version to "1.91.0"

Fixed some lint deprecated versions in the documentation

---

clippy_lints/src/matches/collapsible_match.rs
tests/ui/collapsible_match.rs
tests/ui/collapsible_match.stderr

Fixes https://github.com/rust-lang/rust-clippy/issues/13287
changelog: [`collapsible_match`]: exclude binding modes from struct field pattern suggestions

fix(collapsible_match): exclude binding modes from struct field pattern suggestions

---

CHANGELOG.md
clippy_lints/src/declared_lints.rs
clippy_lints/src/lib.rs
clippy_lints/src/replace_box.rs
tests/ui/replace_box.fixed
tests/ui/replace_box.rs
tests/ui/replace_box.stderr

Adds a new lint that detects `var = Default::default()` when `var` is `Box<T>` and `T` implements `Default`.
changelog: [`replace_box`]: new lint

Add `replace_box` lint
