- Cargo.toml
- README.md
- src/bit_mask.rs
- src/eq_op.rs
- src/lib.rs
- tests/compile-fail/bit_masks.rs
- tests/compile-fail/eq_op.rs
- tests/compile-test.rs
I just merged my lints from the extra_lints project. Maybe you can help me refactor it to integrate better with your lints, e.g. I see you are already checking some expressions (e.g. `.to_string()`).
I also cleaned up some small warnings and added myself to the `authors` field in Cargo.toml.
Since those are not exactly beginner mistakes, but rather oversights that can happen to the best of us when we're low on coffee or whatever, I extended the REAME.md to say so. Also I think that calling them "newbie mistakes" may seem patronizing to some coders, which may put someone off. Perhaps we should consider a more neutral wording?
Regards,
Andre
> Merge extra_lints

- README.md
- src/approx_const.rs
- src/lib.rs
- tests/compile-fail/approx_const.rs
> New lint: approx_const

- src/lib.rs
- src/misc.rs
- tests/compile-fail/cmp_nan.rs
This time I extended misc.rs instead of creating a new file. Btw. Is that the preferred method of adding new lints?
> new lint to check for doomed comparisons to NAN

- src/bit_mask.rs
I found this running Clippy on one of my repositories.
> Fix panic during constant lookup.

- src/types.rs
> Fix Box<Vec<T>> test.

- README.md
- src/identity_op.rs
- src/lib.rs
- tests/compile-fail/bit_masks.rs
- tests/compile-fail/eq_op.rs
- tests/compile-fail/identity_op.rs
> new lint: identity_op, refactored bit_masks a bit

- README.md
- src/lib.rs
- src/mut_mut.rs
- tests/compile-fail/mut_mut.rs
> New lint: mut_mut

- README.md
- src/lib.rs
- src/misc.rs
- tests/compile-fail/cmp_owned.rs
This is a lint for issue #16.
Open question: Are other things that should match?
> new lint: cmp_owned

- src/bit_mask.rs
- src/eq_op.rs
- src/misc.rs
- src/mut_mut.rs
- src/ptr_arg.rs
Time to use some of my newfound Rust-fu :smile:
> refactored Option usage and fn argument types, improved formatting

- src/misc.rs
@Manishearth thanks for the suggestion. Like this?
> check for str type of .to_owned() callee

- src/mut_mut.rs
- src/ptr_arg.rs
> Issue #69 fixed

- README.md
- src/eq_op.rs
- src/lib.rs
- src/strings.rs
- src/utils.rs
- tests/compile-fail/strings.rs
This is the first part of #121, also I reformatted and refactored the source a bit.
> New string_add_assign lint 

- src/misc.rs
- src/utils.rs
- tests/compile-fail/match_if_let.rs
This is the method I mentioned in #96.
> added parent method, also changed match-if-let note to help

- src/lib.rs
- src/misc.rs
- tests/compile-fail/needless_return.rs
I don't know if "misc" is the right file. Let me know if you want this to be in a separate file!
> Add a lint for unneeded return statements that should be written as exprs

- src/lib.rs
- src/misc.rs
- tests/compile-fail/modulo_one.rs
It seemed pretty small so I just put it in misc. Is the word modulo okay, or should I change it to remainder?
Cheers
> Implements #45 - any number mod 1 will be 0

- src/len_zero.rs
- src/lib.rs
- src/methods.rs
- src/misc.rs
- src/strings.rs
- src/utils.rs
- tests/compile-fail/methods.rs
> Lint for Result/Option.unwrap()

- src/types.rs
I guess "help" instead of "note" is fine as well, so we can
get rid of the extra function.
> types: remove almost duplicate helper function

- src/lib.rs
- src/returns.rs
- src/utils.rs
> utils: implement if_let_chain macro as suggested by isHavvy

- src/approx_const.rs
- src/attrs.rs
- src/bit_mask.rs
- src/collapsible_if.rs
- src/eta_reduction.rs
- src/identity_op.rs
- src/len_zero.rs
- src/misc.rs
- src/mut_mut.rs
- src/needless_bool.rs
- src/ptr_arg.rs
- src/returns.rs
- src/strings.rs
- src/types.rs
- src/unicode.rs
- tests/compile-fail/attrs.rs
- tests/compile-fail/box_vec.rs
- tests/compile-fail/collapsible_if.rs
- tests/compile-fail/eta.rs
- tests/compile-fail/len_zero.rs
- tests/compile-fail/match_if_let.rs
- tests/compile-fail/modulo_one.rs
- tests/compile-fail/ptr_arg.rs
- tests/compile-fail/unicode.rs
Please check if this is the style you want to have. I think it should be consistent in any case.
> all: make style of lint messages consistent

- src/collapsible_if.rs
Instead, pretty-print the inner block and use the same style as for
the "single match => if let" lint.
> collapsible_if: do not show Debug display of expression

- .travis.yml
- src/collapsible_if.rs
- src/eq_op.rs
- src/lib.rs
- src/lifetimes.rs
- src/loops.rs
- src/misc.rs
- src/utils.rs
- tests/compile-fail/lifetimes.rs
- util/dogfood.sh
```
cargo build --lib && cp -R target target_recur && cargo rustc -- -Zextra-plugins=clippy -Ltarget_recur/debug   -Dclippy 
```
We have some false positives with needless-lifetimes and collapsible-if
```
$ cargo build --lib && cp -R target target_recur && cargo rustc -- -Zextra-plugins=clippy -Ltarget_recur/debug   -Dclippy 
Compiling clippy v0.0.11 (file:///home/manishearth/Mozilla/Wall/rust-clippy)
Compiling clippy v0.0.11 (file:///home/manishearth/Mozilla/Wall/rust-clippy)
src/utils.rs:122:12: 122:46 error: this if statement can be collapsed [-D collapsible-if]
src/utils.rs:122            if_let_chain!{ [$($tt)+], $block }
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/utils.rs:119:1: 140:2 note: in expansion of if_let_chain!
src/utils.rs:122:12: 122:46 note: expansion site
note: in expansion …
```
> Start dogfooding clippy

- src/collapsible_if.rs
- src/lib.rs
- src/misc.rs
- src/utils.rs
- tests/trim_multiline.rs
(not yet completely used everywhere, but up for preliminary review)
> Add trim_multiline utility (fixes #139)

- tests/compile-fail/cmp_owned.rs
> removed String::from_str(..) to fix build with 1.4.0-nightly/2015-08-14

- src/eq_op.rs
- src/eta_reduction.rs
- tests/compile-fail/eta.rs
This closes #116 – it's not perfect, but at least gets some value out of it.
> fixed false positives (at the cost of some false negatives)

- CONTRIBUTING.md
- tests/compile-fail/cmp_owned.rs
Since we have added this to the build, it'd be good to warn potential contributors. Feel free to suggest improvements regarding wording, grammar, etc., though.
> add a few words on dogfood + update_lints

- src/misc.rs
- tests/compile-fail/match_if_let.rs
Alternate change for #172 that only fixes the bug.
> misc: fix check for unit body in "match -> if let" lint (fixes #172)

- README.md
- src/lib.rs
- src/loops.rs
- tests/compile-fail/for_loop.rs
Hope that the way I'm checking for implementing the trait is ok. This required an extensive look through `ty.rs` :)
> new lint: iterating over any Iterator::next() result (fixes #182)

- src/consts.rs
- tests/consts.rs
What it says on the tin :smile:
> Mul and Div for integers

- src/bit_mask.rs
- tests/compile-fail/bit_masks.rs
> Extend and correct the ineffective_bit_mask check

- src/eq_op.rs
- src/strings.rs
- tests/compile-fail/eq_op.rs
> Eq op const

- README.md
- util/update_lints.py
Since I found it interesting to know how many lints we have, I added a counter and improved the README while I was at it. So this inadvertently closes #225. :smile:
> improved README, added lint counter

- src/approx_const.rs
- src/attrs.rs
- src/bit_mask.rs
- src/misc.rs
- src/returns.rs
- src/shadow.rs
- src/strings.rs
- src/types.rs
This is the first batch of `span_help_and_lint`s with links to our wiki. This relates to the second part of #210.
> added helpful links to lints that have wiki entries

- src/consts.rs
- src/identity_op.rs
- src/matches.rs
- src/returns.rs
- src/types.rs
- src/utils.rs
> Improve macro checks

- src/misc.rs
- tests/compile-fail/float_cmp.rs
> check item name for eq, fixes #268

- README.md
- src/matches.rs
- src/types.rs
"Did you mean to ..." sounds a bit condescending to me, since
if I meant to write "if let" I probably wouldn't have written "match" :)
> don't say "did you mean to" - use the standard "consider..."

- src/methods.rs
These can be static method predicates.  (Found one in rust-copperline,
called Term::is_unsupported_term().)
> methods: allow multiple self kinds for "is_" methods

- src/approx_const.rs
- src/attrs.rs
- src/bit_mask.rs
- src/collapsible_if.rs
- src/consts.rs
- src/eq_op.rs
- src/eta_reduction.rs
- src/identity_op.rs
- src/len_zero.rs
- src/lib.rs
- src/lifetimes.rs
- src/loops.rs
- src/matches.rs
- src/methods.rs
- src/misc.rs
- src/mut_mut.rs
- src/needless_bool.rs
- src/precedence.rs
- src/ptr_arg.rs
- src/ranges.rs
- src/returns.rs
- src/shadow.rs
- src/strings.rs
- src/types.rs
- src/unicode.rs
- src/utils.rs
- tests/consts.rs
Contains HIR, plus my fixes for lints. Needs next nightly (half a day)to land.
> Update rust to 0efb9dab8c7c07fa28e9df0eccc5c07ea3c17fbb

- README.md
- src/consts.rs
- src/lib.rs
- src/minmax.rs
- tests/compile-fail/min_max.rs
> new lint: min_max

- src/attrs.rs
- src/collapsible_if.rs
- src/identity_op.rs
- src/loops.rs
- src/mut_mut.rs
- src/types.rs
- src/utils.rs
This is the foundation for #301. It also pares back on the closure stuff because making the utils functions self-contained is better in code.
@Manishearth r?
> More strict macro check

- src/types.rs
> macro check for unit_cmp

- src/len_zero.rs
- src/misc.rs
- src/utils.rs
> fix false positive len_zero in is_empty()

- README.md
- src/lib.rs
- src/methods.rs
> split wrong_self_convention in pub/default visibility part

- README.md
> add warning about different rustc versions

- src/types.rs
- tests/compile-fail/let_unit.rs
- tests/compile-fail/unit_cmp.rs
> additional macro check + more tests

- src/matches.rs
- tests/compile-fail/matches.rs
> ref matches: false positive with only wildcard pattern match

- README.md
- src/misc.rs
- tests/compile-fail/matches.rs
- tests/compile-fail/toplevel_ref_arg.rs
> Handle let ref in toplevel_ref_arg as well

- Cargo.toml
- src/consts.rs
- src/shadow.rs
> rustup 2015-09-24

- src/loops.rs
- tests/compile-fail/while_loop.rs
This should probably fix #359 (and I've updated some comments). But well, we should definitely rustup, because there's no way to test it right now :/
> fix for the while_let_loop!

- README.md
- src/lib.rs
- src/open_options.rs
- src/utils.rs
- tests/compile-fail/open_options.rs
This PR closes issue #297. I'm not sure about the error messages though. I would appreciate any feedback. :smile:
> Add "nonsensical OpenOptions" lint

- src/matches.rs
- tests/compile-fail/matches.rs
This adds nice help messages to `match_bool`.
> added code snippet help to match_bool

- src/consts.rs
- src/loops.rs
- tests/compile-fail/for_loop.rs
Adds a Display impl for Constant, because that might come in handy
elsewhere as well.
> Fix reverse_range_loop not taking sign into account (fixes #409)

- README.md
- src/lib.rs
- src/temporary_assignment.rs
- tests/compile-fail/temporary_assignment.rs
This is an implementation of rust-lang/rust#26557.
> New lint for assignment to temporary

- README.md
- src/lib.rs
- src/transmute.rs
- tests/compile-fail/transmute.rs
> Add lint for useless transmutes

- src/minmax.rs
- tests/compile-fail/min_max.rs
> Match `min` and `max` functions using `DefId`

- src/minmax.rs
- src/mut_mut.rs
- src/needless_bool.rs
- src/needless_features.rs
- src/precedence.rs
- src/strings.rs
- src/zero_div_zero.rs
These are hopefully uncontroversial changes from rustfmt so that we can focus on controversial ones.
> rustfmt a little

- src/attrs.rs
- src/eq_op.rs
- src/len_zero.rs
- src/lifetimes.rs
- src/loops.rs
- src/methods.rs
- src/misc.rs
- src/ptr_arg.rs
- src/shadow.rs
- src/types.rs
Fixes breakage caused by https://github.com/rust-lang/rust/commit/4a850159cd56805aa0a79ab9cb0ab1f831a97144 and https://github.com/rust-lang/rust/commit/eaaa60dbea0aad371116cda05542cd4039942e26
> Update to latest rust nightly

- src/approx_const.rs
- src/attrs.rs
- src/bit_mask.rs
- src/len_zero.rs
- src/lifetimes.rs
- src/matches.rs
- src/misc.rs
- src/mutex_atomic.rs
- src/ptr_arg.rs
- src/ranges.rs
- src/shadow.rs
- src/strings.rs
- tests/compile-fail/matches.rs
> Extend match_ref_pats to desugared matches

- src/consts.rs
> Fixes to build with current rust nightly

- README.md
- src/escape.rs
- src/lib.rs
- tests/compile-fail/escape_analysis.rs
Not sure if this should be merged yet, but it seems to work so far.
We probably won't see any results from this until I add Vec<T> and String to this; I haven't seen much Box-abuse.
> Rudimentary escape analysis for Box<T>

- README.md
- src/lib.rs
- src/lifetimes.rs
- tests/compile-fail/lifetimes.rs
- tests/compile-fail/unused_lt.rs
> Add lint for unused lifetimes (fixes #459)

- src/lifetimes.rs
- tests/compile-fail/unused_lt.rs
> Check for unused lifetimes in bounds (fixes #489)

- .travis.yml
Dogfooding is now done in `tests/dogfood.rs`.
> Don't dogfood twice

- README.md
- src/array_indexing.rs
- src/lib.rs
- tests/compile-fail/array_indexing.rs
A simple one to see how it works :)
Did I miss something or `src/lib.rs` needs to be updated both with `./util/update_lints.py` and manually when adding a lint?
> Implement #364

- src/methods.rs
- src/utils.rs
This is the refactor discussed in #504 ([here](https://github.com/Manishearth/rust-clippy/issues/504#issuecomment-167162982))
> Refactor `check_expr()` impl for `MethodsPass`

- src/misc_early.rs
> Add help on field binding

- README.md
- src/lib.rs
- src/matches.rs
- tests/compile-fail/matches.rs
- tests/matches.rs
> Implement #471

- README.md
- src/eq_op.rs
- src/hashmap.rs
- src/lib.rs
- src/loops.rs
- src/strings.rs
- src/utils.rs
- tests/compile-fail/hashmap.rs
This is a WIP, I still have to figure out how to handle this:
```rust
fn insert_other_if_absent<K: Eq + Hash, V>(m: &mut HashMap<K, V>, k: K, o: K, v: V) {
if !m.contains_key(&k) { m.insert(o, v); }
//                  ^             ^
}
```
and probably lots of other potential problems.
> Implement  #433

- Cargo.toml
- README.md
- src/attrs.rs
- src/lib.rs
- tests/compile-fail/attrs.rs
This is the first part of #465, the other parts will follow when I get around to it.
Note that this adds semver (and with it, nom) to our dependency tree.
@Manishearth r?
> added semver lint

- src/matches.rs
- src/utils.rs
- tests/compile-fail/matches.rs
> Improve the single_match lint

- src/methods.rs
- src/misc.rs
- src/utils.rs
- tests/compile-fail/cmp_owned.rs
> Check types in the CMP_OWNED lint

- src/eta_reduction.rs
- tests/compile-fail/eta.rs
> Fix redundant_closure false positive

- README.md
- src/lib.rs
- src/types.rs
- tests/compile-fail/char_lit_as_u8.rs
- util/update_lints.py
> Add a lint for casts from char literals to u8

- README.md
- src/lib.rs
- src/methods.rs
- tests/compile-fail/methods.rs
> extend_from_slice lint

- README.md
- src/lib.rs
- src/utils.rs
- src/vec.rs
- tests/compile-fail/vec.rs
> Add a lint to warn about &vec![_] if &[_] would do

- README.md
- src/lib.rs
- src/loops.rs
- tests/compile-fail/for_loop.rs
> Add for_loop_over_option lint

- src/escape.rs
- tests/compile-fail/escape_analysis.rs
> Skip escape analysis for closure arguments

- src/escape.rs
- tests/compile-fail/escape_analysis.rs
This adds a boxed trait check as well as tests. Thus we fix #606.
@Manishearth r?
> fixed #606

- README.md
- src/escape.rs
- src/lib.rs
- src/types.rs
- tests/compile-fail/absurd_unsigned_comparisons.rs
> Add a lint to suggest uint == 0 over uint <= 0

- README.md
- src/methods.rs
- tests/compile-fail/methods.rs
> Fix confusing message for `STRING_TO_STRING`

- README.md
- src/lib.rs
- src/methods.rs
- tests/compile-fail/methods.rs
> Lint on cloning double pointer

- README.md
- src/lib.rs
- src/lifetimes.rs
- src/loops.rs
- tests/compile-fail/for_loop.rs
> Lint looping on maps ignoring the keys or values

- README.md
- src/approx_const.rs
- src/bit_mask.rs
- src/consts.rs
- src/enum_glob_use.rs
- src/len_zero.rs
- src/lib.rs
- src/minmax.rs
- src/needless_bool.rs
- src/types.rs
- src/unicode.rs
- src/utils.rs
- tests/compile-fail/enum_glob_use.rs
cc #541 
not sure if a full fix, the discussion expanded on more than just glob imports
> lint against glob imports of enum variants

- src/enum_glob_use.rs
- tests/compile-test.rs
- tests/run-pass/enum-glob-import-crate.rs
> prevent panic in enum glob import lint if a crate's elements are glob imported

- Cargo.toml
- src/approx_const.rs
- src/attrs.rs
- src/bit_mask.rs
- src/consts.rs
- src/derive.rs
- src/enum_variants.rs
- src/identity_op.rs
- src/items_after_statements.rs
- src/len_zero.rs
- src/matches.rs
- src/mutex_atomic.rs
- src/needless_bool.rs
- src/open_options.rs
- src/panic.rs
- src/precedence.rs
- src/regex.rs
- src/returns.rs
- src/strings.rs
- src/types.rs
- src/unicode.rs
- src/utils.rs
- tests/consts.rs
breakage from https://github.com/rust-lang/rust/pull/31487
waiting on regex_macros: https://github.com/rust-lang-nursery/regex/pull/162
> WIP: fix nightly breakage

- src/utils/hir.rs
- tests/compile-fail/copies.rs
> Fix false positive for `ifs_same_cond` and `cfg!`

- README.md
- src/derive.rs
- src/lib.rs
- tests/compile-fail/derive.rs
> Make DERIVE_HASH_NOT_EQ symmetric

- src/misc_early.rs
- src/returns.rs
Waiting on https://github.com/rust-lang-nursery/regex/pull/167.
> Rustup to 1.8.0-nightly (57c357d89 2016-02-16)

- src/enum_glob_use.rs
- tests/compile-fail/enum_glob_use.rs
I basically implemented a non-panicking version of `get_if_local` :/
fixes #686
> fix enum glob use (again)

- src/copies.rs
- src/eta_reduction.rs
- src/loops.rs
- src/map_clone.rs
- src/matches.rs
- src/misc.rs
- src/shadow.rs
- src/utils/hir.rs
https://github.com/rust-lang/rust/commit/9b40e1e5b3d75c101b1ad78a1e2160962e955174
> fix nightly (2016-02-17)

- src/utils/mod.rs
- tests/run-pass/ice-700.rs
> Fix ICE with match_def_path

- src/len_zero.rs
- src/loops.rs
- tests/compile-fail/len_zero.rs
- tests/compile-fail/while_loop.rs
> `span_suggestion` and macro checks

- src/loops.rs
- tests/compile-fail/for_loop.rs
> Fix false positive in `FOR_KV_MAP` and `&mut` refs

- src/cyclomatic_complexity.rs
previously the HIR was unnecessarily traversed twice
> simplify cyclomatic complexity auxiliarly value computation

- Cargo.toml
- src/loops.rs
- tests/compile-fail/for_loop.rs
>  Fix ICE in for_loop with globals

- src/utils/mod.rs
Ref https://github.com/Manishearth/rust-clippy/pull/756#issuecomment-195501984.
> Fix `unsugar_range` with `..`

- src/len_zero.rs
- src/panic.rs
- src/utils/mod.rs
- tests/compile-fail/len_zero.rs
- tests/compile-fail/panic.rs
Found [in the wild](https://github.com/nickel-org/rust-mustache/pull/30). Ref #759.
> Small fix × 2

- src/new_without_default.rs
- src/utils/mod.rs
- tests/compile-fail/new_without_default.rs
> Fix `new_without_default` with lts and generics

- README.md
- src/lib.rs
- src/transmute.rs
- src/utils/mod.rs
- tests/compile-fail/transmute.rs
Added lint for transmute between `T` and `*T` as specified in #749.
> Added crosspointer transmute error and tests 

- src/enum_glob_use.rs
- src/methods.rs
- src/new_without_default.rs
- src/types.rs
- src/utils/mod.rs
- tests/compile-fail/methods.rs
h/t @eddyb for help with the region stuff
> ICE fixes and other things

- README.md
- src/lib.rs
- src/misc.rs
- src/ranges.rs
- src/transmute.rs
- tests/compile-fail/transmute.rs
cc @bluss: is [this](https://github.com/Manishearth/rust-clippy/commit/0c4c7a1e83da45ec6a92816f14a420c3b72af4cb#diff-3a1203a4358d4f7dab7fbe98450c817fR22) what you wanted in #775?
Fix #775.
> Lint transmute from ptr to ref

- src/eta_reduction.rs
- tests/compile-fail/eta.rs
> Fix FP in `REDUNDANT_CLOSURE` with divergent functions

- src/non_expressive_names.rs
- tests/compile-fail/non_expressive_names.rs
> whitelist more non-expressive-name false positives

- Cargo.toml
- src/booleans.rs
- tests/issue-825.rs
> Ignore pathological cases in boolean lint

- Cargo.toml
- src/cyclomatic_complexity.rs
- src/escape.rs
- src/matches.rs
> Rustup to 1.9.0-nightly (5ab11d72c 2016-04-02)

- src/doc.rs
- src/lib.rs
- src/utils/conf.rs
- tests/compile-fail/doc.rs
> Fix false positive with `DOC_MARKDOWN` and `32MiB`

- src/doc.rs
- src/utils/conf.rs
- tests/compile-fail/attrs.rs
- tests/compile-fail/doc.rs
> More tests for `DOC_MARKDOWN`

- CHANGELOG.md
- README.md
- src/lib.rs
- src/unsafe_removed_from_name.rs
- tests/compile-fail/unsafe_removed_from_name.rs
> Add UNSAFE_REMOVED_FROM_NAME lint

- src/cyclomatic_complexity.rs
- tests/compile-fail/cyclomatic_complexity.rs
> cc: early returns are special

- src/new_without_default.rs
Could be clearer from discussion in IRC
> Improve new_without_default docs

- src/non_expressive_names.rs
> make similar names allow-by-default

- src/doc.rs
- tests/compile-fail/doc.rs
Fix #897. Fix #900. Test #883.
> Fix DOC_MARKDOWN

- src/lib.rs
> Support either rustup or multirust environment variables

- tests/compile-fail/conf_non_existant.rs
- tests/compile-fail/enums_clike.rs
- tests/compile-test.rs
- tests/dogfood.rs
there's a commit "fixing" every word in the title :)
> German windows 32bit

- src/lib.rs
cc https://github.com/Manishearth/rust-clippy/issues/935
> Don't panic if cargo rustc fails

- src/lib.rs
This will make stuff like `cargo clippy --lib -- -D clippy` actually useful inside a git hook or a `.travis.yml` file.
> Let cargo-clippy exit with a code > 0 if some error occured

- src/no_effect.rs
- tests/compile-fail/no_effect.rs
> fix no_effect lint

- Cargo.toml
- clippy_lints/Cargo.toml
- util/update_lints.py
> Auto-update/check clippy_lints dependency version

- clippy_lints/src/utils/cargo.rs
- src/main.rs
partially fixes #973
That metadata format is a mess and I couldn't find a formal description of it...
> process more kinds of metadata

- clippy_lints/src/new_without_default.rs
- tests/compile-fail/new_without_default.rs
> Make new_without_default ignore const fns

- clippy_lints/src/let_if_seq.rs
- tests/compile-fail/let_if_seq.rs
> Correctly check for variable use in `useless_let_if_seq`

- clippy_lints/src/swap.rs
Fix https://github.com/Manishearth/rust-clippy/issues/981#issuecomment-223812029.
> Fix wrong suggestion in `MANUAL_SWAP`

- clippy_lints/Cargo.toml
- clippy_lints/src/block_in_if_condition.rs
- clippy_lints/src/derive.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/methods.rs
- clippy_lints/src/misc.rs
- clippy_lints/src/swap.rs
- tests/compile-fail/swap.rs
>  Fix wrong suggestion with `MANUAL_SWAP` and slices

- CHANGELOG.md
- README.md
- clippy_lints/src/utils/mod.rs
- tests/compile-fail/booleans.rs
- tests/compile-fail/non_expressive_names.rs
- tests/compile-test.rs
As discussed in https://github.com/laumann/compiletest-rs/pull/38#issuecomment-223828391.
> Add environment variable to deactivate wiki links

- clippy_lints/src/utils/conf.rs
> added GPLv{2,3} to doc-valid-idents

- clippy_lints/src/loops.rs
- tests/compile-fail/while_loop.rs
> Fix FP with `WHILE_LET_LOOP` and break expressions

- .travis.yml
> speed up travis by not recompiling clippy just to test `cargo clippy`

- clippy_lints/src/methods.rs
- clippy_lints/src/new_without_default.rs
- clippy_lints/src/shadow.rs
- clippy_lints/src/utils/mod.rs
> use span_lint_and_then instead of adding to the `DiagnosticWrapper`

- README.md
> readme formatting nit

- clippy_lints/src/transmute.rs
- tests/compile-fail/transmute.rs
> Add parentheses when necessary in transmute suggestion (fixes #1049)

- CHANGELOG.md
- README.md
- clippy_lints/src/lib.rs
- clippy_lints/src/misc_early.rs
- tests/compile-fail/double_neg.rs
> new lint: double_neg

- clippy_lints/src/utils/conf.rs
> Add "JavaScript" to doc-valid-idents

- clippy_lints/src/consts.rs
- tests/compile-fail/copies.rs
- tests/consts.rs
> Fix #1086-Added sign check on Constant f64 PartialEq implementation

- clippy_lints/src/methods.rs
- clippy_lints/src/non_expressive_names.rs
- clippy_lints/src/returns.rs
- clippy_lints/src/utils/mod.rs
- clippy_lints/src/vec.rs
- tests/compile-fail/needless_return.rs
- tests/compile-fail/vec.rs
> Some small fixes

- clippy_lints/src/misc.rs
- tests/compile-fail/toplevel_ref_arg.rs
> Suggest mutability and fix type in toplevel-ref-arg

- clippy_lints/src/enum_variants.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/utils/conf.rs
- tests/compile-fail/enum_variants.rs
> Add a configurable threshold for enum variants before name lints trigger

- clippy_lints/src/functions.rs
- tests/compile-fail/functions.rs
> extern fns often need to adhere to a specific api -> don't suggest api changes

- .travis.yml
- tests/dogfood.rs
> don't run clippy on itself twice in travis

- clippy_lints/src/methods.rs
- tests/compile-fail/wrong_self_convention.rs
> enable changing wrong_self_convention's lint level at the function level

- clippy_lints/src/utils/mod.rs
https://github.com/rust-lang/rust/pull/35091/commits/d1d16c94c5ec007ce91ec306bdf06c8ee6f2d29a
> Update to rustc 1.12.0-nightly (1deb02ea6 2016-08-12)

- CHANGELOG.md
- clippy_lints/src/misc_early.rs
- tests/compile-fail/literals.rs
> Fix FP in `ZERO_PREFIXED_LITERAL` and `0b`/`Oo`

- CHANGELOG.md
- README.md
- clippy_lints/src/eval_order_dependence.rs
- clippy_lints/src/lib.rs
- tests/compile-fail/diverging_sub_expression.rs
> lint diverging expressions that are sub-expressions of others

- clippy_lints/src/transmute.rs
- tests/compile-fail/transmute.rs
> Fix wrong suggestion in `TRANSMUTE_PTR_TO_REF` with lts

- clippy_lints/src/eval_order_dependence.rs
- tests/compile-fail/diverging_sub_expression.rs
> correctly traverse match expressions for diverging_sub_expr

- clippy_lints/src/lib.rs
- clippy_lints/src/utils/inspector.rs
- clippy_lints/src/utils/mod.rs
cc #1234
I left a lot of stuff commented out, since I want to implement it but haven't yet. Hope that's alright with everyone.
> initial implementation of the code inspector lint

- clippy_lints/src/methods.rs
- tests/compile-fail/wrong_self_convention.rs
> Fix false positive for `wrong_self_convention`

- clippy_lints/src/lib.rs
- clippy_lints/src/utils/conf.rs
Also search for `.clippy.toml` for consistency with *rustfmt*.
Fix  #909.
Fix #1294.
Does not fix  #1293, because we get:
> ```
thread 'main' panicked at 'could not find matching package'
```
@oli-obk: has `cargo clippy` ever worked outside the root of the project (independently of `cargo.toml`)?
> Search for `clippy.toml` recursively

- clippy_lints/src/utils/mod.rs
- tests/compile-fail/cyclomatic_complexity.rs
- tests/compile-fail/cyclomatic_complexity_attr_used.rs
> mark cyclomatic complexity attribute as used

- src/main.rs
> fixed callback changes from rustc 1.14.0-nightly (7c69b0d5a 2016-11-01)

- src/main.rs
> --sysroot isn't necessary anymore for the outer cargo clippy call

- src/main.rs
fix for issue described in #1331
> fixed #1331

- CHANGELOG.md
- README.md
- clippy_lints/src/lib.rs
- clippy_lints/src/methods.rs
- tests/compile-fail/methods.rs
> Implement `get_unwrap` lint

- CHANGELOG.md
- README.md
- clippy_lints/src/lib.rs
- clippy_lints/src/reference.rs
- tests/compile-fail/formatting.rs
- tests/compile-fail/no_effect.rs
- tests/compile-fail/reference.rs
> Lint usage of `*&` and `*&mut`

- clippy_lints/src/escape.rs
- tests/compile-fail/escape_analysis.rs
> fix an ice related to associated types

- clippy_lints/src/types.rs
- tests/compile-fail/absurd-extreme-comparisons.rs
> fix absurd extreme comparisons false positive

- clippy_lints/src/lifetimes.rs
- tests/run-pass/needless_lifetimes_impl_trait.rs
> support impl trait for needless lifetimes

- CHANGELOG.md
- README.md
- clippy_lints/src/double_parens.rs
- clippy_lints/src/lib.rs
- tests/compile-fail/double_parens.rs
- tests/compile-fail/eq_op.rs
- tests/compile-fail/identity_op.rs
- tests/compile-fail/reference.rs
> Add double_parens lint

- CHANGELOG.md
- Cargo.toml
- clippy_lints/Cargo.toml
- clippy_lints/src/methods.rs
- tests/compile-fail/wrong_self_convention.rs
> Fix false positive in wrong_self_convention

- .travis.yml
- README.md
- appveyor.yml
This adds OSX jobs to travis & various windows jopbs on appveyor.
Let's see if this works.
> more CI integration

- .travis.yml
This should only run on Linux.
cc @mcarton
> Fix Travis after_success

- README.md
- clippy_lints/src/deprecated_lints.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/methods.rs
- tests/compile-fail/methods.rs
> deprecate extend_from_slice lint

- clippy_lints/src/methods.rs
- src/main.rs
- tests/compile-fail/methods.rs
This fixes #1415 – and we even have one instance in main. :smile:
> Extend or_fun_call to also cover methods

- clippy_lints/src/map_clone.rs
- clippy_lints/src/utils/mod.rs
Adjust `multispan_sugg` to rust-lang/rust#38955
Rustfmtup to 0.7.1
> Rustup to nightly from 2017-01-20

- CHANGELOG.md
- Cargo.toml
- clippy_lints/Cargo.toml
> Bump to 0.0.111

- clippy_lints/src/precedence.rs
- tests/compile-fail/precedence.rs
> Use `span_suggestion` in the `precedence` lint

- clippy_lints/src/methods.rs
- tests/compile-fail/methods.rs
thanks @Nashenas88 for finding those
> fix false negatives introduced in the rustup

- CHANGELOG.md
- README.md
- clippy_lints/src/formatting.rs
- clippy_lints/src/lib.rs
- tests/compile-fail/formatting.rs
> Lint for possible missing comma in an array #1177

- CHANGELOG.md
- README.md
- clippy_lints/src/lib.rs
- clippy_lints/src/ptr.rs
- src/main.rs
- tests/ui/mut_from_ref.rs
- tests/ui/mut_from_ref.stderr
> New mut_from_ref lint

- CHANGELOG.md
- README.md
- clippy_lints/src/lib.rs
- clippy_lints/src/matches.rs
- tests/ui/matches.rs
- tests/ui/matches.stderr
> Lint on `Err(_)` arm of a match

- clippy_lints/src/loops.rs
- clippy_lints/src/utils/mod.rs
- tests/ui/for_loop.rs
- tests/ui/for_loop.stderr
fixes #1398 
fixes #1493
rebase of other PR
> fix explicit_into_iter_loop on references

- clippy_lints/Cargo.toml
Trying to get people onto more recent semvers in the run up to semver 1.0.
> update semver version

- CHANGELOG.md
- Cargo.toml
- appveyor.yml
- clippy_lints/Cargo.toml
- src/main.rs
fixes #1244 
diff best viewed [without whitespace](https://github.com/Manishearth/rust-clippy/pull/1581/files?w=1)
> Get cargo clippy working on 64 bit windows again

- clippy_lints/src/needless_pass_by_value.rs
> Don't panic if traits not found

- clippy_lints/src/needless_pass_by_value.rs
- tests/ui/needless_pass_by_value_proc_macro.rs
> Filter out proc_macro_derive functions

- CHANGELOG.md
- Cargo.toml
- clippy_lints/Cargo.toml
- clippy_lints/src/enum_clike.rs
Version: 1.18.0-nightly (9f2abadca 2017-04-18)
> Fixes compilation error with latest nightly rust 

- README.md
This confused me and led to #1701, hopefully it's clearer now
> Clarify that -L needs the path to clippy_so's directory

- CHANGELOG.md
- Cargo.toml
- clippy_lints/Cargo.toml
- clippy_lints/src/len_zero.rs
- clippy_lints/src/lifetimes.rs
>  Rustup to *rustc 1.19.0-nightly (06fb4d256 2017-04-30)* and bump to 0.0.129

- clippy_lints/src/zero_div_zero.rs
> Fix a future compat lint that we triggered

- clippy_lints/src/blacklisted_name.rs
- tests/ui/blacklisted_name.rs
- tests/ui/blacklisted_name.stderr
- tests/ui/conf_french_blacklisted_name.stderr
> Fix span in `blacklisted_name`

- clippy_lints/src/should_assert_eq.rs
- tests/ui/should_assert_eq.rs
- tests/ui/should_assert_eq.stderr
> distinguish debug_assert

- CHANGELOG.md
- Cargo.toml
- clippy_lints/Cargo.toml
- clippy_lints/src/utils/mod.rs
> Rustup to rustc 1.19.0-nightly (557967766 2017-05-26)

- clippy_lints/src/methods.rs
- clippy_lints/src/utils/paths.rs
- clippy_tests/examples/wrong_self_convention.rs
- clippy_tests/examples/wrong_self_convention.stderr
> Check for AsRef/AsMut arguments in wrong_self_convention

- clippy_lints/src/utils/mod.rs
> Pass extra parameter to CrateStore::item_children for rustc nightly

- clippy_lints/src/utils/higher.rs
> Fix for loop detection

- CHANGELOG.md
- Cargo.toml
- clippy_lints/Cargo.toml
- clippy_lints/src/cyclomatic_complexity.rs
- clippy_lints/src/doc.rs
- clippy_lints/src/eta_reduction.rs
- clippy_lints/src/eval_order_dependence.rs
- clippy_lints/src/functions.rs
- clippy_lints/src/len_zero.rs
- clippy_lints/src/loops.rs
- clippy_lints/src/map_clone.rs
- clippy_lints/src/matches.rs
- clippy_lints/src/methods.rs
- clippy_lints/src/mut_reference.rs
- clippy_lints/src/needless_borrowed_ref.rs
- clippy_lints/src/needless_pass_by_value.rs
- clippy_lints/src/precedence.rs
- clippy_lints/src/ptr.rs
- clippy_lints/src/ranges.rs
- clippy_lints/src/reference.rs
- clippy_lints/src/returns.rs
- clippy_lints/src/types.rs
- clippy_lints/src/utils/mod.rs
> Fix compilation on rustc 1.20.0-nightly (69c65d296 2017-06-28)

- src/main.rs
> Use `--emit=metadata` instead of `-Zno-trans`

- clippy_lints/src/utils/sugg.rs
> Use token_to_string instead of binop_to_string

- clippy_lints/src/utils/mod.rs
> Set show_code_when_inline to true

- .gitignore
- .travis.yml
- clippy_lints/src/bit_mask.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/literal_digit_grouping.rs
- clippy_lints/src/utils/author.rs
- clippy_lints/src/utils/mod.rs
- clippy_tests/examples/bit_masks.stderr
- clippy_tests/examples/trailing_zeros.rs
- clippy_tests/examples/trailing_zeros.stderr
- clippy_tests/examples/trailing_zeros.stdout
- tests/examples.rs
I created a new attribute (`#[clippy(author)]`) which will autogenerate an `if_let_chain` that pattern matches the HIR that you attached the attribute to. I have multiple more attributes planned to make this tool more useful, but wanted to get it out for early review. The idea is that you annotate the code you want to lint and don't have to write all of the lint yourself.
> Lint authoring tool

- clippy_lints/src/types.rs
Thanks @oli-obk for the detailed instructions.
Fixes #1957.
> Fix int_ty_to_nbits

- clippy_lints/src/types.rs
- clippy_lints/src/utils/paths.rs
- tests/ui/borrow_box.rs
> Fix borrowed_box lint for Box<Any>

- clippy_lints/src/len_zero.rs
- tests/ui/len_zero.rs
- tests/ui/len_zero.stderr
This tries to fix #1740. Let me know if I need to change anything.
Cheers
> len_without_is_empty false positive #1740

- clippy_lints/src/loops.rs
- tests/ui/while_loop.rs
> `while_let_loop` doesn't take into account break-with-value #1948

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- clippy_lints/Cargo.toml
- clippy_lints/src/bit_mask.rs
- clippy_lints/src/consts.rs
- clippy_lints/src/derive.rs
- clippy_lints/src/eq_op.rs
- clippy_lints/src/methods.rs
- clippy_lints/src/misc.rs
- clippy_lints/src/needless_pass_by_value.rs
- clippy_lints/src/partialeq_ne_impl.rs
- clippy_lints/src/should_assert_eq.rs
- clippy_lints/src/types.rs
- clippy_lints/src/utils/inspector.rs
- clippy_lints/src/utils/mod.rs
This is mainly due to https://github.com/rust-lang/rust/commit/dead08cb33134
> Update for latest Rust

- clippy_lints/src/approx_const.rs
- clippy_lints/src/is_unit_expr.rs
- clippy_lints/src/regex.rs
Fixes rendering on the documentation page.
> Small documentation fixes

- Cargo.lock
- clippy_lints/src/loops.rs
- tests/ui/never_loop.rs
- tests/ui/never_loop.stderr
> Add ExprLoop to contains_continue_expr()

- clippy_lints/src/needless_borrow.rs
- tests/ui/eta.stderr
- tests/ui/needless_borrow.stderr
> Add suggestion to needless_borrow 

- clippy_lints/src/loops.rs
- tests/ui/for_loop.rs
- tests/ui/for_loop.stderr
Extension to https://github.com/rust-lang-nursery/rust-clippy/pull/2021.
> Also detect manual slice cloning

- Cargo.lock
- clippy_lints/Cargo.toml
- clippy_lints/src/doc.rs
- clippy_lints/src/lib.rs
- tests/ui/doc.rs
- tests/ui/doc.stderr
> Don't lint autolinks in `doc_markdown`

- clippy_lints/src/loops.rs
- tests/ui/never_loop.rs
> Fix never_loop

- clippy_lints/src/needless_pass_by_value.rs
- mini-macro/src/lib.rs
- tests/run-pass/procedural_macro.rs
> needless_pass_by_value false-positive in annotation

- clippy_lints/src/methods.rs
- tests/ui/useless_asref.rs
- tests/ui/useless_asref.stderr
> Add lint for useless `as_ref` calls

- README.md
- rust-update
Sorry for taking so long. This is for #2108.
I'm not sure if I'm really good at writing READMEs, so if its the wrong style or something, feel free to adjust or point it out.
> Include a conditional update script

- clippy_lints/src/lib.rs
- clippy_lints/src/methods.rs
- tests/ui/methods.rs
- tests/ui/methods.stderr
I started working on #1590. However, I didn't find how to trigger the UI tests that I wrote for my new lint.
> Start working on #1590

- CHANGELOG.md
- clippy_lints/src/const_static_lifetime.rs
- clippy_lints/src/doc.rs
- src/driver.rs
This is the result of me testing out a WIP source code spell-checker
and your project was the random target this time.
> fix some typos

- clippy_lints/src/functions.rs
- clippy_lints/src/len_zero.rs
- clippy_lints/src/missing_doc.rs
- clippy_lints/src/needless_pass_by_value.rs
- clippy_lints/src/utils/inspector.rs
> Fix compilation errors with rustc 1.23.0-nightly (d762b1d6c 2017-11-04)

- Cargo.toml
- tests/compile-test.rs
- tests/ui/cstring.stderr
Brings better diffs for failed ui tests.
> Use compiletest 0.3

- clippy_lints/src/loops.rs
- tests/ui/needless_range_loop.rs
- tests/ui/needless_range_loop.stderr
> Improve `needless_range_loop`

- clippy_lints/src/booleans.rs
Here is a first attempt at simplifying the `suggest` function. It's still far more complicated than what I would have hoped for but seems a little simpler than before.
The changes are:
- Move the simplification bits in a separate function.
- Avoid returning the result string as we're mutating it over already. Actually it would probably feel nicer to return the string and not mutate it but maybe there are some performance concerns.
- Some other small tweaks.
> Simplify the boolean expression suggestion function

- CONTRIBUTING.md
- clippy_lints/src/const_static_lifetime.rs
- tests/ui/const_static_lifetime.rs
- tests/ui/const_static_lifetime.stderr
- tests/ui/update-all-references.sh
And a few documentation nits I noticed.
> Fixup "const static lifetime" lint for non-path types

- clippy_lints/src/utils/mod.rs
Fixes #2239. Minor changes only.
> Fixes #2239

- clippy_lints/src/enum_variants.rs
- tests/ui/stutter.rs
- tests/ui/stutter.stderr
> Check for word beginning in stutter lint

- clippy_lints/src/types.rs
> Disable cast_lossless on const/static items

- clippy_lints/src/print.rs
- tests/ui/println_empty_string.stderr
> Add auto-fixable `println!()` suggestion

- clippy_lints/src/missing_doc.rs
- tests/ui/missing-doc.stderr
> Don't warn about missing docs for main()

- clippy_lints/src/needless_pass_by_value.rs
- clippy_lints/src/utils/paths.rs
- tests/ui/needless_pass_by_value.rs
- tests/ui/needless_pass_by_value.stderr
> Various needless_pass_by_value false positive fixes

- clippy_lints/src/precedence.rs
- tests/ui/precedence.rs
- tests/ui/precedence.stderr
> Add macro check to precedence lint

- src/driver.rs
> Rustup to rustc 1.25.0-nightly (97520ccb1 2018-01-21)

- clippy_lints/src/regex.rs
- tests/ui/regex.rs
- tests/ui/regex.stderr
> Let invalid_regex point to the right place for raw strings

- clippy_lints/src/loops.rs
- clippy_lints/src/unused_label.rs
- clippy_lints/src/utils/hir_utils.rs
Fix the compilation broken by these two changes:
+ https://github.com/rust-lang/rust/commit/2d56abfbebdc905dafc9cf9edc0a6f58e4de7cbd#diff-7fceb7ede15b205bf5ad812c31d75384L1459
+ https://github.com/rust-lang/rust/commit/ccf0d8399e1ef3ed6bf7005650ce42aa646b5cc7#diff-64b696b0ef6ad44140e973801ed82b25L2771
Closes https://github.com/rust-lang-nursery/rust-clippy/issues/2402
> Fix compilation

- clippy_lints/src/utils/mod.rs
Fixes #2429 
One line quick fix :)
> set CodeSuggestion approximate to false. fixes #2429

- clippy_lints/src/utils/mod.rs
> Rustup to rustc 1.25.0-nightly (0c6091fbd 2018-02-04)

- README.md
> Simplify recommended command

- util/lintlib.py
> Fix name of configuration parameters in documentation

- clippy_lints/src/derive.rs
Fix for the latest nightly rustc 1.26.0-nightly (322d7f7b9 2018-02-25).
> Fix for rustc 1.26.0-nightly (322d7f7b9 2018-02-25)

- clippy_lints/src/suspicious_trait_impl.rs
- tests/ui/suspicious_arithmetic_impl.rs
> UnNeg and UnNot count as additional operations now

- clippy_lints/src/loops.rs
- tests/ui/infinite_loop.rs
- tests/ui/infinite_loop.stderr
Following discussions in: #2514
> lint: while immutable condition: do not lint constants

- tests/ui/eq_op.rs
- tests/ui/eq_op.stderr
The issue was probably fixed by ff32d5f7. Closes #2420.
> Add tests to ensure that issue #2420 is resolved

- src/main.rs
> Undo a temporary fix for a cargo bug

- clippy_lints/src/lib.rs
- tests/ui/replace_consts.rs
- tests/ui/replace_consts.stderr
cc https://github.com/rust-lang/rust/pull/49101
> i128 is stabilizing

- clippy_lints/src/derive.rs
> Update hash_xor_eq docs to match behavior

- README.md
> Explain nursery lints

- .github/deploy.sh
- .travis.yml
I made the deploy script echo a few more lines and also added `set -x` for now.
Hope that this helps us in the future. Not sure what's going on in the `.github/deploy.sh` script sometimes.
cc #2656
> Debug deployment script issues

- .travis.yml
> Run remark-lint on all markdown files in root

- clippy_lints/src/format.rs
- tests/ui/format.rs
- tests/ui/format.stderr
> Fix useless_format false negative

- .gitignore
- clippy_lints/src/doc.rs
- clippy_lints/src/write.rs
- tests/ui/println_empty_string.rs
- tests/ui/println_empty_string.stderr
- tests/ui/writeln_empty_string.stderr
fixes #2648. trying to update the message to better reflect what should be replaced
> fixEmptyPrintln

- CONTRIBUTING.md
This is partly taken from the [rustfmt CONTRIBUTING.md][contrib].
Part of #2666 
[contrib]: https://github.com/rust-lang-nursery/rustfmt/blob/master/Contributing.md
> Add intro and mention IRC in CONTRIBUTING.md

- clippy_lints/src/types.rs
- tests/ui/cast_alignment.stderr
re: https://github.com/rust-lang-nursery/rust-clippy/issues/2693
`cargo test`: OK
> Fix for https://github.com/rust-lang-nursery/rust-clippy/issues/2693

- clippy_lints/src/utils/mod.rs
> Simplify some internal code

- CHANGELOG.md
- Cargo.toml
- README.md
- clippy_lints/Cargo.toml
> Version bump

- rustfmt.toml
> Remove removed rustfmt options

- clippy_lints/src/needless_pass_by_value.rs
Fixes #2757
Do I need to change some other file for `min_version.txt` to update?
> Update for rust-lang/rust#50536

- .travis.yml
- ci/base-tests.sh
- ci/integration-tests.sh
This adds a couple more integration tests and closes #2736 .
> Add more integration tests

- src/driver.rs
Rustup to 2018-05-18
Ref: rust-lang/rust#50615
> Rename trans to codegen

- src/driver.rs
not sure if this works, but it's worth a try
> Stop compilation after linting

- CONTRIBUTING.md
- clippy_lints/src/lib.rs
- clippy_lints/src/utils/author.rs
- clippy_lints/src/utils/inspector.rs
- clippy_lints/src/utils/mod.rs
- tests/ui/author.rs
- tests/ui/author/for_loop.rs
- tests/ui/author/matches.rs
- tests/ui/cyclomatic_complexity.rs
- tests/ui/cyclomatic_complexity_attr_used.rs
- tests/ui/excessive_precision.rs
- tests/ui/for_loop.rs
- tests/ui/trailing_zeros.rs
- tests/ui/trailing_zeros.stderr
> Use the new scoped tool attributes

- build.rs
- clippy_lints/src/approx_const.rs
- clippy_lints/src/arithmetic.rs
- clippy_lints/src/array_indexing.rs
- clippy_lints/src/assign_ops.rs
- clippy_lints/src/attrs.rs
- clippy_lints/src/consts.rs
- clippy_lints/src/enum_clike.rs
- clippy_lints/src/eq_op.rs
- clippy_lints/src/misc.rs
- clippy_lints/src/needless_pass_by_value.rs
- clippy_lints/src/shadow.rs
- clippy_lints/src/utils/hir_utils.rs
- clippy_lints/src/utils/inspector.rs
- clippy_lints/src/utils/mod.rs
- src/driver.rs
- src/lib.rs
- tests/compile-test.rs
- tests/versioncheck.rs
- tests/without_block_comments.rs
Fixes #2788 
Since previous review I've changed `body_id.body` to `anon_const.body` because it was odd.
>  Update to nightly 2018-05-22 

- clippy_lints/src/approx_const.rs
- clippy_lints/src/arithmetic.rs
- clippy_lints/src/array_indexing.rs
- clippy_lints/src/assign_ops.rs
- src/driver.rs
- tests/compile-test.rs
Do **not** merge until next nightly build is produced (or merge to different branch).
Builds and passes tests with rust commit c131bdcaff68d35f96e954baac4340206779335f
Fixes #2838
> Upcoming breakage

- .travis.yml
They have all been working for some time now.
> No more allowed failures in integration tests

- README.md
> Link to correct AppVeyor project in Readme

- clippy_lints/src/fallible_impl_from.rs
- tests/run-pass/ice-2865.rs
Fixes #2865
Thanks @mati865 for the quick investigation and the provided example!
> Use utils::opt_def_id() instead of def_id() to prevent ICE

- clippy_lints/src/default_trait_access.rs
This is a pretty common pattern, I think.
> Move default_trait_access to pedantic

- README.md
https://github.com/rust-lang-nursery/rust-clippy/issues/2901
> Update readme for new clippy install method

- .travis.yml
I don't think this is intended?
cc @phansch
> Remove duplication of the cargo and rls repos from travis

- clippy_lints/src/attrs.rs
- tests/ui/useless_attribute.rs
> Fix useless_attribute lint for extern crate items with macro_use

- clippy_lints/src/missing_doc.rs
- clippy_lints/src/missing_inline.rs
- clippy_lints/src/utils/inspector.rs
- clippy_lints/src/utils/mod.rs
Fixes fallout from https://github.com/rust-lang/rust/pull/52024.
> Update to nightly

- clippy_lints/src/assign_ops.rs
> Expand on misrefactored_assign_op known problems

- clippy_lints/src/eta_reduction.rs
Documenting https://github.com/rust-lang-nursery/rust-clippy/issues/1439 until it gets fixed.
> Add known problem for redundant_closure lint

- util/lintlib.py
> lintlib: Use Python 3 compatible print

- tests/ui/redundant_field_names.rs
- tests/ui/redundant_field_names.stderr
> Add a test to ensure that #2799 is fixed

- clippy_lints/src/write.rs
- tests/ui/writeln_empty_string.rs
- tests/ui/writeln_empty_string.stderr
> #3016 writeln_empty_string Hardcoded suggestion

- src/driver.rs
for https://github.com/rust-lang/rust/pull/53624
> Use the compilers exit code computation instead of rolling our own

- ci/integration-tests.sh
`clippy_pedantic` -> `clippy::pedantic`
`clippy_nursery` -> `clippy::nursery`
r? @phansch
> Update travis integration tests to tool_lints

- ci/base-tests.sh
- rustc_tools_util/src/lib.rs
> rustc_tools_util: add tests

- clippy_lints/src/inherent_impl.rs
- src/driver.rs
> Fix pedantic filter_map warnings

- .travis.yml
clippy-service hasn't been working for a long time now.
and maybe this helps with #3239
> Remove clippy-service update from CI

- README.md
> Mention -A and -W in readme

- clippy_lints/src/consts.rs
> ScalarMaybeUndef -> Scalar (Rustup to e812ca472a2a5284e9f15cd9af32285d7ff3fd39)

- clippy_lints/src/format.rs
- tests/ui/format.rs
- tests/ui/format.stderr
> Fix 2796 and 3020

- .travis.yml
> make sure travis fails when clippy does not build.

- clippy_lints/src/lifetimes.rs
We were failing tests already so this PR snuck in under the radar
r? @oli-obk
> Rustup for https://github.com/rust-lang/rust/pull/54741

- clippy_lints/src/methods/mod.rs
This will hopefully address #3254
> Adding more detail to filter_map lint documentation.

- clippy_lints/src/new_without_default.rs
- tests/ui/new_without_default.rs
this should solve https://github.com/rust-lang-nursery/rust-clippy/issues/2875
> new_without_default should not warn about unsafe new

- clippy_lints/src/consts.rs
- clippy_lints/src/methods/mod.rs
- clippy_lints/src/utils/higher.rs
- clippy_lints/src/write.rs
> Pedantic dogfood: `items_after_statements`

- clippy_lints/src/misc.rs
- tests/ui/cmp_owned.rs
- tests/ui/cmp_owned.stderr
> cmp_owned false positive

- clippy_lints/src/consts.rs
- clippy_lints/src/enum_clike.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/regex.rs
- clippy_lints/src/utils/mod.rs
- clippy_lints/src/utils/sugg.rs
- src/driver.rs
> Pedantic dogfood: casts

- README.md
- clippy_lints/src/lib.rs
> Specify which categories are enabled by default

- clippy_lints/src/misc.rs
- tests/ui/cmp_owned.rs
- tests/ui/cmp_owned.stderr
> cmp_owned wording and false positive

- .travis.yml
From https://travis-ci.community/t/rust-error-could-not-compile-winapi/268/5
> Install Windows SDK 10.0 on travis

- CHANGELOG.md
- clippy_lints/src/deprecated_lints.rs
- clippy_lints/src/if_let_redundant_pattern_matching.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/redundant_pattern_matching.rs
- tests/ui/if_let_redundant_pattern_matching.rs
- tests/ui/if_let_redundant_pattern_matching.stderr
- tests/ui/matches.rs
- tests/ui/needless_pass_by_value.rs
- tests/ui/redundant_pattern_matching.rs
- tests/ui/redundant_pattern_matching.stderr
> Add lint for redundant pattern matching for explicit return boolean

- clippy_lints/src/collapsible_if.rs
- tests/ui/collapsible_if.rs
- tests/ui/collapsible_if.stderr
> Check for comments in collapsible ifs

- clippy_lints/src/multiple_crate_versions.rs
- clippy_lints/src/wildcard_dependencies.rs
I missed these warnings during review, should have checked the Travis log first.
> Fix warnings introduced by #3349

- clippy_lints/src/indexing_slicing.rs
- tests/ui/indexing_slicing.rs
- tests/ui/indexing_slicing.stderr
> OUT_OF_BOUNDS_INDEXING false negative

- .travis.yml
Upstream ticket: https://github.com/rust-lang/rust/issues/55376
> travis: work around temporary test failure due to rustc crashing on hyper

- clippy_lints/src/use_self.rs
- tests/ui/use_self.rs
- tests/ui/use_self.stderr
> Check existential types in `use_self`

- clippy_lints/src/booleans.rs
Caused by https://github.com/rust-lang/rust/pull/55536
> Fix clippy build failure on latest master

- clippy_lints/src/use_self.rs
- tests/ui/use_self.rs
> Fix `use_self` false positive on `use` statements

- README.md
Served me well on my travis setups so far :)
> readme: tell how to install clippy on travis from git if it is not shipped with a nightly.

- CONTRIBUTING.md
> Mention triage procedure in contributing.md

- clippy_lints/src/redundant_clone.rs
Travis started failing after the latest nightly update
> Fix rustfmt format

- README.md
> Remove -preview suffix from README

- tests/ui/unused_unit.rs
- tests/ui/unused_unit.stderr
Starting to work on #2376, this annotation got in the way. Going to
remove it for now.
> Remove a run-rustfix annotation (for now)

- tests/ui/absurd-extreme-comparisons.rs
- tests/ui/absurd-extreme-comparisons.stderr
- tests/ui/arithmetic.rs
- tests/ui/arithmetic.stderr
- tests/ui/collapsible_if.rs
- tests/ui/collapsible_if.stderr
- tests/ui/cyclomatic_complexity.rs
- tests/ui/cyclomatic_complexity.stderr
- tests/ui/doc.rs
- tests/ui/doc.stderr
- tests/ui/double_parens.rs
- tests/ui/double_parens.stderr
- tests/ui/empty_line_after_outer_attribute.rs
- tests/ui/empty_line_after_outer_attribute.stderr
- tests/ui/eq_op.rs
- tests/ui/eq_op.stderr
- tests/ui/format.rs
- tests/ui/format.stderr
- tests/ui/methods.rs
- tests/ui/methods.stderr
- tests/ui/replace_consts.rs
- tests/ui/replace_consts.stderr
- tests/ui/unused_unit.rs
- tests/ui/unused_unit.stderr
> add rustfmt::skip attributes to a couple of tests

- clippy_lints/src/excessive_precision.rs
> Remove allow(doc_markdown) in excessive_precision.rs

- .travis.yml
- clippy_lints/src/doc.rs
- tests/ui/cast_alignment.rs
- tests/ui/doc.rs
- tests/ui/doc.stderr
Successful merges:
- #3509 (Fix doc_markdown off by one issue)
- #3539 (Fix rvm/gpg bug in travis osx build)
- #3540 (rustup https://github.com/rust-lang/rust/pull/56092)
Failed merges:
r? @ghost
> Rollup of 3 pull requests

- clippy_lints/src/methods/mod.rs
- tests/ui/useful_asref.rs
> Fix false positive in useless_asref

- ci/integration-tests.sh
> Make integration tests fail on 'E0463'

- tests/ui/for_kv_map.rs
> Add ui/for_kv_map test for false positive in #1279

- clippy_lints/src/loops.rs
- tests/ui/while_loop.rs
Don't suggest a `for` loop if the iterator is used inside the `while` loop.
Closes #3670
> Fix bad `while_let_on_iterator` suggestion.

- clippy_lints/src/types.rs
- tests/ui/unit_arg.fixed
- tests/ui/unit_arg.rs
Ignore arguments with the question mark operator.
Closes #2945
> Fix `unit_arg` false positive

- clippy_dev/src/lib.rs
- clippy_lints/src/attrs.rs
- clippy_lints/src/cargo_common_metadata.rs
- clippy_lints/src/eta_reduction.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/methods/mod.rs
- clippy_lints/src/non_expressive_names.rs
- clippy_lints/src/utils/conf.rs
- clippy_lints/src/utils/mod.rs
- rustc_tools_util/src/lib.rs
- src/driver.rs
- tests/missing-test-files.rs
- tests/ui/eta.rs
- tests/ui/eta.stderr
- tests/ui/map_clone.fixed
- tests/ui/map_clone.rs
- tests/ui/map_clone.stderr
> Redundant closure for methods

- util/gh-pages/index.html
The improvement is that you can click on the label and it'll select the form field.
> Use normal HTML label semantics for filter

- clippy_lints/src/methods/mod.rs
- tests/ui/unnecessary_clone.rs
- tests/ui/unnecessary_clone.stderr
> Improve `iter_cloned_collect` suggestions

- clippy_lints/src/eta_reduction.rs
> do not trigger redundant_closure for external macros

- clippy_lints/src/eta_reduction.rs
- clippy_lints/src/functions.rs
- clippy_lints/src/let_if_seq.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/loops.rs
- clippy_lints/src/matches.rs
- clippy_lints/src/missing_inline.rs
- clippy_lints/src/needless_pass_by_value.rs
- clippy_lints/src/unused_io_amount.rs
- clippy_lints/src/utils/internal_lints.rs
- clippy_lints/src/utils/mod.rs
Some adjustments needed after the most recent round of HirIdification.
> Align with rust-lang/rust/#58992

- clippy_lints/src/redundant_clone.rs
commit: 4122d2221ec65232bc211a266d0796a4713e0d39
> rustup https://github.com/rust-lang/rust/pull/59657

- tests/ui/dlist.rs
- tests/ui/dlist.stderr
> Rust upgrade to rustc 1.35.0-nightly (00856722b 2019-04-13)

- CHANGELOG.md
Maintain a changelog for beta so the release team can easily include important additions in the release blog posts.
r? @phansch, @oli-obk
> Beta changelog

- clippy_lints/src/misc_early.rs
> Rustup to rustc 1.36.0-nightly (fe0a415b4 2019-04-23)

- tests/ui/or_fun_call.rs
- tests/ui/or_fun_call.stderr
> Add test for or_fun_call macro suggestion

- clippy_lints/src/utils/author.rs
- clippy_lints/src/utils/sugg.rs
cc https://github.com/rust-lang/rust/issues/60623
> rustup https://github.com/rust-lang/rust/pull/60586

- tests/ui/identity_conversion.rs
- tests/ui/identity_conversion.stderr
> Add regression test for identity_conversion FP

- clippy_lints/src/write.rs
- tests/ui/crashes/ice-3891.stderr
https://github.com/rust-lang/rust/pull/60965
> Rustup to https://github.com/rust-lang/rust/pull/60965

- clippy_lints/Cargo.toml
- clippy_lints/src/consts.rs
> update if_chain to 1.0.0

- Cargo.toml
- build.rs
- clippy_lints/Cargo.toml
- clippy_lints/src/consts.rs
- rustc_tools_util/Cargo.toml
- rustc_tools_util/README.md
- rustc_tools_util/src/lib.rs
Successful merges:
- #4129 (update if_chain to 1.0.0)
- #4130 (bump rustc_tools_util to 0.2.0 )
Failed merges:
r? @ghost
> Rollup of 2 pull requests

- clippy_lints/src/utils/sugg.rs
> rustup https://github.com/rust-lang/rust/pull/60803/

- clippy_lints/src/write.rs
> Rustup to https://github.com/rust-lang/rust/pull/61026

- clippy_lints/src/consts.rs
- clippy_lints/src/types.rs
- clippy_lints/src/utils/mod.rs
> Rustup to rustc 1.36.0-nightly (fa40a111f 2019-05-27)

- clippy_lints/src/misc.rs
- clippy_lints/src/panic_unimplemented.rs
- clippy_lints/src/ranges.rs
- clippy_lints/src/returns.rs
- clippy_lints/src/utils/internal_lints.rs
- clippy_lints/src/utils/mod.rs
- clippy_lints/src/vec.rs
Find by simple command: `git grep -w expn_info`.
Closes #4151
> Make use of new `outer_expn_info()` function

- clippy_lints/src/implicit_return.rs
> Fix implicit_return docs

- clippy_lints/src/attrs.rs
- clippy_lints/src/double_comparison.rs
- clippy_lints/src/functions.rs
- clippy_lints/src/indexing_slicing.rs
- clippy_lints/src/needless_bool.rs
- clippy_lints/src/types.rs
Just some minor grammar issues and typos in documentation.
> Typos and minor grammar corrections

- clippy_lints/src/escape.rs
- clippy_lints/src/eval_order_dependence.rs
- clippy_lints/src/functions.rs
- clippy_lints/src/loops.rs
- clippy_lints/src/methods/mod.rs
- clippy_lints/src/needless_bool.rs
- clippy_lints/src/needless_pass_by_value.rs
- clippy_lints/src/non_copy_const.rs
- clippy_lints/src/ptr.rs
- clippy_lints/src/suspicious_trait_impl.rs
- clippy_lints/src/trivially_copy_pass_by_ref.rs
- clippy_lints/src/types.rs
- clippy_lints/src/utils/mod.rs
Fixes fallout from https://github.com/rust-lang/rust/pull/62091/files
> Rustup to 5f9c0448dde167128d668da4555879f64e56af1d

- clippy_lints/src/panic_unimplemented.rs
- clippy_lints/src/question_mark.rs
- clippy_lints/src/redundant_pattern_matching.rs
- clippy_lints/src/utils/hir_utils.rs
> rustup https://github.com/rust-lang/rust/pull/61995

- clippy_lints/src/trivially_copy_pass_by_ref.rs
> Remove unused import

- clippy_lints/src/lib.rs
- clippy_lints/src/types.rs
> Fix unknown lint warnings

- clippy_lints/src/types.rs
Refs #2881.
changelog: Mention know problems for cast_ptr_alignment
> cast_ptr_alignment: Mention legal use under known problems

- Cargo.toml
- ci/base-tests.sh
- clippy_lints/src/lib.rs
- src/driver.rs
- src/main.rs
> Deny warnings in CI

- .travis.yml
cc #4031 but now on the auto and try branches. (https://github.com/rust-lang/rust-clippy/issues/3955#issuecomment-502230021)
> Check for changelog entry in PR bodies

- src/driver.rs
> rustup https://github.com/rust-lang/rust/pull/62679/

- .travis.yml
- appveyor.yml
- clippy_dev/src/fmt.rs
- clippy_lints/src/consts.rs
- clippy_lints/src/misc_early.rs
- clippy_lints/src/open_options.rs
- clippy_lints/src/redundant_static_lifetimes.rs
- clippy_lints/src/use_self.rs
- rustc_tools_util/src/lib.rs
- tests/fmt.rs
- tests/ui/checked_unwrap/simple_conditionals.rs
- tests/ui/drop_forget_ref.rs
- tests/ui/use_self.fixed
- tests/ui/use_self.rs
> Make fmt test and command more robust

- clippy_lints/src/try_err.rs
- tests/ui/try_err.fixed
- tests/ui/try_err.rs
- tests/ui/try_err.stderr
> Fix macro expansion in try_err lint

- clippy_lints/src/implicit_return.rs
> Use source_callsite() instead of recursive outer_expn_info()

- clippy_lints/src/methods/mod.rs
- tests/ui/cstring.rs
- tests/ui/cstring.stderr
> Fix lint_cstring_as_ptr for expect

- clippy_lints/src/write.rs
> Fixed repeated word

- clippy_lints/Cargo.toml
> update url dependency from 1.7.0 to 2.1.0

- doc/adding_lints.md
> Update if_chain doc link

- tests/ui/issue_4266.rs
- tests/ui/issue_4266.stderr
- tests/ui/methods.rs
- tests/ui/methods.stderr
async/await is stablized in https://github.com/rust-lang/rust/pull/63209 :tada:
> Remove feature gate for async_await

- clippy_lints/src/utils/author.rs
> Add missing field to LitKind::Str

- clippy_lints/src/missing_doc.rs
- clippy_lints/src/utils/author.rs
> Rustup to https://github.com/rust-lang/rust/pull/63854

- clippy_lints/src/consts.rs
> Rustup to rust-lang/rust#63561

- clippy_lints/src/non_expressive_names.rs
> Rustup to rust-lang/rust#64111

- clippy_lints/src/loops.rs
- clippy_lints/src/methods/mod.rs
- clippy_lints/src/needless_pass_by_value.rs
- clippy_lints/src/ptr.rs
- clippy_lints/src/swap.rs
- clippy_lints/src/utils/mod.rs
- tests/ui/or_fun_call.fixed
- tests/ui/or_fun_call.rs
I was getting local `cargo test` failures because of this, yet travis was green.
> run rustfmt

- tests/ui/wildcard_enum_match_arm.fixed
- tests/ui/wildcard_enum_match_arm.stderr
> Add run-rustfix for wildcard_enum_match_arm lint

- tests/ui/builtin-type-shadow.stderr
> rustup https://github.com/rust-lang/rust/pull/64666

- .travis.yml
> Re enable OSX builders

- clippy_lints/src/derive.rs
- clippy_lints/src/utils/mod.rs
> rustup https://github.com/rust-lang/rust/pull/64515

- clippy_lints/src/utils/hir_utils.rs
> Rustup rust-lang/rust#63492

- clippy_lints/src/booleans.rs
- clippy_lints/src/functions.rs
> Rustup to rustc 1.40.0-nightly (237d54ff6 2019-10-15)

- .travis.yml
- appveyor.yml
> build: use rustup minimal profile to speed up Rust installation time

- clippy_lints/src/functions.rs
- clippy_lints/src/methods/mod.rs
cc https://github.com/rust-lang/rust/issues/65585
> rustup https://github.com/rust-lang/rust/pull/65535

- tests/ui/assign_ops2.stderr
- tests/ui/booleans.stderr
- tests/ui/collapsible_if.stderr
- tests/ui/dbg_macro.stderr
- tests/ui/for_kv_map.stderr
- tests/ui/for_loop_fixable.stderr
- tests/ui/implicit_hasher.stderr
- tests/ui/large_enum_variant.stderr
- tests/ui/let_return.stderr
- tests/ui/let_unit.stderr
- tests/ui/literals.stderr
- tests/ui/manual_memcpy.stderr
- tests/ui/match_bool.stderr
- tests/ui/match_ref_pats.stderr
- tests/ui/needless_pass_by_value.stderr
- tests/ui/needless_range_loop.stderr
- tests/ui/new_without_default.stderr
- tests/ui/option_map_or_none.stderr
- tests/ui/print_with_newline.stderr
- tests/ui/ptr_arg.stderr
- tests/ui/unit_arg.stderr
- tests/ui/write_with_newline.stderr
> Rustup to rust-lang/rust#65773

- clippy_lints/src/approx_const.rs
> Simplify approx const truncation check

- clippy_lints/src/write.rs
> Rustup to rustc 1.40.0-nightly (ac162c6ab 2019-11-09)

- clippy_lints/src/functions.rs
- clippy_lints/src/loops.rs
- clippy_lints/src/matches.rs
- clippy_lints/src/mem_replace.rs
- clippy_lints/src/methods/mod.rs
- clippy_lints/src/misc.rs
- clippy_lints/src/mut_mut.rs
- clippy_lints/src/mut_reference.rs
- clippy_lints/src/mutable_debug_assertion.rs
- clippy_lints/src/needless_borrow.rs
- clippy_lints/src/needless_borrowed_ref.rs
- clippy_lints/src/ptr.rs
- clippy_lints/src/transmute.rs
- clippy_lints/src/trivially_copy_pass_by_ref.rs
- clippy_lints/src/types.rs
- clippy_lints/src/utils/author.rs
- clippy_lints/src/utils/hir_utils.rs
- clippy_lints/src/utils/internal_lints.rs
- tests/ui/author/for_loop.stdout
> Rustup to rustc 1.40.0-nightly (56237d75b 2019-11-11)

- clippy_lints/src/consts.rs
> Rustup rust-lang/rust#66233

- setup-toolchain.sh
> build: check if RTIM is not installed

- .github/deploy.sh
It should work now: https://travis-ci.com/lzutao/rust-clippy/jobs/261801929
Closes #4785
> deploy: cd to out/ before adding files to git

- clippy_lints/src/redundant_clone.rs
- tests/ui/custom_ice_message.rs
cc rust-lang/rust#64736
Fixes #4872 
> Rustup to rust-lang/rust#64736

- clippy_lints/src/non_expressive_names.rs
> rustup https://github.com/rust-lang/rust/pull/67455

- README.md
> There are no per-file copyright headers anymore

- Cargo.toml
> deps: bump git2 from 0.10 to 0.11

- clippy_lints/src/len_zero.rs
> Correct documentation for `len_zero`

- clippy_lints/src/missing_doc.rs
> Rustup to rust-lang/rust#67151

- clippy_lints/src/assertions_on_constants.rs
- clippy_lints/src/escape.rs
- clippy_lints/src/new_without_default.rs
- clippy_lints/src/panic_unimplemented.rs
> Rustup to rust-lang/rust#67803 and rust-lang/rust#67137

- .travis.yml
> Travis: Use windows-msvc target for Windows build

- COPYRIGHT
> update license year to 2020

- clippy_lints/src/lib.rs
- tests/ui/patterns.fixed
- tests/ui/patterns.rs
- tests/ui/patterns.stderr
slice_patterns have been stabilized.
> rustup https://github.com/rust-lang/rust/pull/67712

- clippy_lints/src/needless_pass_by_value.rs
- clippy_lints/src/utils/mod.rs
> Rustup to rust-lang/rust#68140

- clippy_lints/src/redundant_clone.rs
> Rustup to rust-lang/rust#68512

- clippy_lints/src/lib.rs
- clippy_lints/src/utils/mod.rs
- clippy_lints/src/utils/sugg.rs
> Rustup to rust-lang/rust#68133

- clippy_dev/Cargo.toml
- clippy_dev/src/stderr_length_check.rs
- clippy_lints/src/missing_doc.rs
> dev: Use bytecount for faster line count

- clippy_lints/src/needless_pass_by_value.rs
cc https://github.com/rust-lang/rust/pull/65232
> Rustup "index ReEmpty by universe"

- clippy_lints/src/len_zero.rs
- clippy_lints/src/use_self.rs
> Rustup to rust-lang/rust#68911

- .github/workflows/deploy.yml
I just want to test some things here currently.
> Fix tag deployment on GHA

- .github/workflows/clippy.yml
- .github/workflows/clippy_bors.yml
> gha: install cargo-cache with ci-autoclean feature which speeds up build time by a large margin.

- clippy_lints/src/doc.rs
> needless_doctest_main: False positive for async fn

- clippy_lints/src/booleans.rs
- clippy_lints/src/consts.rs
- clippy_lints/src/escape.rs
- clippy_lints/src/indexing_slicing.rs
- clippy_lints/src/loops.rs
- clippy_lints/src/matches.rs
- clippy_lints/src/ptr.rs
- clippy_lints/src/ptr_offset_with_cast.rs
- clippy_lints/src/shadow.rs
- clippy_lints/src/temporary_assignment.rs
- clippy_lints/src/utils/internal_lints.rs
- clippy_lints/src/utils/sugg.rs
- Use `Vec::with_capacity()` as possible
- Clean up imports
> Minor cleanup

- clippy_lints/src/excessive_bools.rs
- clippy_lints/src/non_expressive_names.rs
> Rustup to rust-lang/rust#69194

- clippy_lints/src/len_zero.rs
- clippy_lints/src/use_self.rs
> Rustup to rust-lang/rust#69072

- tests/ui/missing-doc-impl.rs
> Rustup to rust-lang/rust#61812

- Cargo.toml
> Update git2 to 0.12

- clippy_lints/src/consts.rs
> use question mark operator

- tests/ui/author/blocks.rs
- tests/ui/author/blocks.stdout
- tests/ui/swap.fixed
- tests/ui/swap.rs
> Rustup to rust-lang/rust#69506

- CONTRIBUTING.md
Multiple people seem to have missed this based on questions asked in the Discord channel. Might as well mention it up front.
> Mention the setup instructions in CONTRIBUTING

- clippy_lints/Cargo.toml
> deps: bump itertools 0.8 -> 0.9

- clippy_lints/src/misc_early.rs
> check_pat: delay creation of the "normal" vec until we reach the branch where it is actually needed

- clippy_lints/src/implicit_return.rs
- clippy_lints/src/missing_const_for_fn.rs
- clippy_lints/src/redundant_clone.rs
- clippy_lints/src/utils/mod.rs
- tests/ui/crashes/trivial_bounds.rs
https://github.com/rust-lang/rust/issues/69874#issuecomment-596890446
changelog: Fix ICE with trivial_bounds feature
> Fix ICE with trivial_bounds feature

- clippy_lints/src/len_zero.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/needless_pass_by_value.rs
- clippy_lints/src/utils/mod.rs
> Rustup to rust-lang/rust#69076

- tests/integration.rs
> Don't convert Path to lossy str

- clippy_lints/src/dbg_macro.rs
- clippy_lints/src/non_expressive_names.rs
- clippy_lints/src/utils/sugg.rs
- clippy_lints/src/write.rs
> rustup https://github.com/rust-lang/rust/pull/69589/

- clippy_dev/src/new_lint.rs
> new_lint.rs: encourage authors to write more detailed code samples in lint descriptions (linted as well as fixed code)

- clippy_lints/src/functions.rs
- clippy_lints/src/inherent_impl.rs
- clippy_lints/src/loops.rs
- clippy_lints/src/missing_doc.rs
- clippy_lints/src/new_without_default.rs
- clippy_lints/src/swap.rs
- clippy_lints/src/utils/mod.rs
- clippy_lints/src/utils/usage.rs
- clippy_lints/src/wildcard_imports.rs
> Rustup to rust-lang/rust#66131

- clippy_lints/src/write.rs
> rustup https://github.com/rust-lang/rust/pull/69838

- clippy_lints/src/doc.rs
> rustup https://github.com/rust-lang/rust/pull/69968/

- README.md
> readme: explain how to run only a single lint on a codebase

- clippy_lints/src/lib.rs
- clippy_lints/src/redundant_pub_crate.rs
- src/lintlist/mod.rs
- tests/ui/wildcard_imports.fixed
- tests/ui/wildcard_imports.rs
> move redundant_pub_crate to nursery

- clippy_dev/Cargo.toml
> Bump itertools

- clippy_lints/src/redundant_clone.rs
cc https://github.com/rust-lang/rust/pull/70449
> Rustup to https://github.com/rust-lang/rust/pull/70449

- clippy_lints/src/methods/mod.rs
- clippy_lints/src/types.rs
> Rustup to https://github.com/rust-lang/rust/pull/70913

- Cargo.toml
> deps: bump compiletest-rs from 0.4 to 0.5

- .github/workflows/clippy_bors.yml
> Reenable rustfmt integration test

- README.md
> readme: update to cargo clippy --fix command

- Cargo.toml
cc https://github.com/rust-lang/crates.io/issues/2436
> Remove badge FIXME from Cargo.toml

- util/fetch_prs_between.sh
This can then be easily copy/pasted into the changelog :blue_heart:
> util/fetch_prs_between.sh: Add Markdown formatted link

- doc/release.md
> Add a note to the beta sections of release.md

- clippy_lints/src/redundant_pub_crate.rs
> rustup to https://github.com/rust-lang/rust/pull/70043

- clippy_lints/src/needless_pass_by_value.rs
- clippy_lints/src/utils/mod.rs
cc https://github.com/rust-lang/rust/issues/71608
> rustup: rust-lang/rust#71628

- tests/ui/implicit_saturating_sub.fixed
- tests/ui/implicit_saturating_sub.rs
> Rustup to rust-lang/rust#71518

- Cargo.toml
> deps: remove unused regex dependency from root crate

- clippy_lints/src/utils/mod.rs
> Make use of slice pattern

- doc/release.md
r? @phansch 
[Rendered](https://github.com/flip1995/rust-clippy/blob/release_doc/doc/release.md)
> Reorder sections of release documentation

- clippy_lints/src/loops.rs
> Improve end of expression check in for loop lints

- clippy_lints/src/deprecated_lints.rs
- clippy_lints/src/dereference.rs
- clippy_lints/src/inherent_impl.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/missing_const_for_fn.rs
- clippy_lints/src/modulo_arithmetic.rs
- clippy_lints/src/option_if_let_else.rs
- clippy_lints/src/utils/numeric_literal.rs
- tests/ui/manual_async_fn.fixed
- tests/ui/manual_async_fn.rs
- tests/ui/manual_async_fn.stderr
- tests/ui/never_loop.rs
- tests/ui/precedence.fixed
- tests/ui/precedence.rs
- tests/ui/vec_resize_to_zero.rs
> fix typos (found by codespell)

- clippy_lints/src/utils/mod.rs
> trait_sel: only test predicates w/ no substs

- clippy_lints/src/useless_conversion.rs
- tests/ui/useless_conversion.fixed
- tests/ui/useless_conversion.rs
- tests/ui/useless_conversion.stderr
> Fix FP `useless_conversion`

- CONTRIBUTING.md
- doc/adding_lints.md
- doc/basics.md
While answering a few questions to @AB1908, I realized, that our documentation could use some love. Especially the "Getting Started" part for new contributors. So I wrote together some instruction on how to get the toolchain and how to build and test Clippy.
[Rendered](https://github.com/flip1995/rust-clippy/blob/basics/doc/basics.md)
r? @phansch 
> Basic instruction for new contributors

- clippy_lints/src/methods/mod.rs
The known problems looks to be obsolete since NLL is stable.
> Remove obsolete known problems unnecessary_fold

- clippy_lints/src/methods/mod.rs
- clippy_lints/src/utils/mod.rs
- tests/ui/new_ret_no_self.rs
- tests/ui/new_ret_no_self.stderr
Lint in trait def instead of impl block.
Fixes: #5435 
> Fix FP in `new_ret_no_self`: trigger in trait def instead of impl block

- clippy_lints/src/default_trait_access.rs
Remove repeated matching on the same QPath.
> Simplify `clippy::default_trait_access`

- clippy_lints/src/types.rs
> fix some use of `snippet` in `types.rs`

- triagebot.toml
> Add S-* label modifier to triagebot

- doc/backport.md
> Update backport documentation to the subtree workflow

- clippy_lints/src/types.rs
- tests/ui/crashes/ice-6139.rs
Fixes #6139
Kind of hacky, but this should be fine. 
> Fixes ICE 6139

- .github/PULL_REQUEST_TEMPLATE.md
- doc/adding_lints.md
r? @ghost since this is blocking CI
> Fix remark linting on checkboxes

- clippy_lints/src/transmute.rs
> Add a known problem for transmute_ptr_to_ref lint

- Cargo.toml
- clippy_lints/Cargo.toml
> Update semver 0.10 -> 0.11

- Cargo.toml
- clippy_lints/Cargo.toml
> bump cargo_metadata version

- .github/driver.sh
this changs the add/delete indication from
>
>
<
to
+
+
-
(same as git diff)
> use diff -u in driver.sh test

- clippy_dev/src/ra_setup.rs
> cargo dev ra-setup: don't inject deps multiple times if we have already done so

- tests/ui/crashes/ice-6250.rs
- tests/ui/crashes/ice-6250.stderr
- tests/ui/crashes/ice-6251.rs
- tests/ui/crashes/ice-6251.stderr
- tests/ui/crashes/ice-6252.rs
- tests/ui/crashes/ice-6252.stderr
- tests/ui/crashes/ice-6254.rs
- tests/ui/crashes/ice-6254.stderr
- tests/ui/crashes/ice-6255.rs
- tests/ui/crashes/ice-6255.stderr
- tests/ui/crashes/ice-6256.rs
- tests/ui/crashes/ice-6256.stderr
Fixes #6250
Fixes #6251
Fixes #6252
Fixes #6255
Fixes #6256
> add a couple of ICE testcases

- tests/ui/manual_ok_or.fixed
- tests/ui/manual_ok_or.rs
> revisiting a typo

- clippy_lints/src/panic_unimplemented.rs
- tests/ui/panicking_macros.stderr
> issue_6357 update unreachable macro usage

- clippy_lints/src/size_of_in_element_count.rs
- tests/ui/size_of_in_element_count.stderr
> Fix a style of texts in `size_of_in_element_count`

- clippy_lints/src/utils/conf.rs
> add more lints to msrv docs

- clippy_lints/src/manual_async_fn.rs
- clippy_lints/src/unused_unit.rs
- clippy_lints/src/utils/mod.rs
> remove clone in manual_async_fn lint

- clippy_dev/src/bless.rs
> Add ui-internal to cargo dev bless

- clippy_lints/src/needless_question_mark.rs
> Small fixes of doc in `needless_question_mark`

- clippy_lints/src/manual_ok_or.rs
> Remove duplication in the manual_ok_or lint example

- CONTRIBUTING.md
Refer to https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/New.20prioritization.20labels.
> Add notes of prioritization labels to doc

- triagebot.toml
> Rename "good first issue" back to "good-first-issue"

- clippy_lints/src/functions.rs
- tests/ui/result_unit_error.rs
- tests/ui/result_unit_error.stderr
> Fix FP of result_unit_err when using type aliases

- clippy_dev/src/lintcheck.rs
- clippy_dev/test_sources.toml
- lintcheck-logs/lintcheck_crates_logs.txt
This is the rest of https://github.com/rust-lang/rust-clippy/pull/6829 but without adding anything to ci
> lintcheck: add test (but don't run on ci)

- doc/adding_lints.md
> Add msrv to contents in adding lints md

- clippy_lints/src/methods/bind_instead_of_map.rs
> Remove paths from bind_instead_of_map

- clippy_utils/src/lib.rs
- clippy_utils/src/paths.rs
> Remove some dead utils

- clippy_lints/src/pass_by_ref_or_value.rs
Hello,
I thought it would be better to have a note and warning about this issue considering it introduced an UB in the past even with the "Search on Github" feature.
---
changelog: Add a note on the issue #5953 to the known problems section.
> Add a note on the issue #5953

- clippy_lints/src/utils/conf.rs
- tests/ui/min_rust_version_attr.rs
- tests/ui/min_rust_version_attr.stderr
> Finish MSRV for cloned_instead_of_copied

- CONTRIBUTING.md
This is a section for `IntelliJ Rust`, not `rust-analyzer`.
> Small fix in CONTRIBUTING.md

- clippy_lints/src/manual_unwrap_or.rs
- tests/ui/manual_unwrap_or.fixed
- tests/ui/manual_unwrap_or.rs
changelog: none (since this just piggybacks on #7233)
Fixes #6960
> Fix another manual_unwrap_or deref FP

- doc/basics.md
Adding this command should better help new contributors.
> Add the command to add upstream remote

- COPYRIGHT
- LICENSE-APACHE
- LICENSE-MIT
- README.md
This PR just updates years in copyrights, nothing more.
> Updated years in copyrigths

- clippy_lints/src/lib.rs
> Add macro_use clippy_utils

- doc/release.md
Inspired by https://stackoverflow.com/a/5195913
> Document to only push the created tag and not everything

- clippy_lints/src/redundant_clone.rs
> redundant_clone: fix comment

- clippy_lints/src/bytecount.rs
- clippy_lints/src/collapsible_match.rs
- clippy_lints/src/manual_map.rs
- clippy_utils/src/lib.rs
- clippy_utils/src/ptr.rs
...because checking vars by name is bad, because of shadowing.
> Factor out match_var and get_pat_name utils

- clippy_dev/src/fmt.rs
> Remove rustfmt bug workaround

- tests/compile-test.rs
> Add to test third party crates list

- clippy_lints/src/derivable_impls.rs
- tests/ui/derivable_impls.rs
fix #7654
fix #7655 
changelog: none (not released)
> Fix derivable impl false positives

- tests/compile-test.rs
> Improve depinfo error

- clippy_utils/src/diagnostics.rs
> lower_case in  span_lint_and_help document

- clippy_lints/src/lib.rs
r? @Manishearth since you added this in #540 :smile: 
> Remove rustfmt::skip attribute from register_plugins function

- lintcheck/src/main.rs
This PR updates changes lintcheck's output to use text tables and adds a markdown option to use Markdown links in the reports table. At first, I tried to keep the original output format, but the loading of old stats broke with the markdown option. The old format is therefore sadly incompatible with the new one. I can if requested make it in a way that the markdown output is only and optional additional output, but that would require more work for little benefit IMO.
For now, lintcheck has two output types. Here are the examples (best viewed on desktop):
<details>
<summary>`cargo lintcheck --only anyhow`</summary>
```txt
clippy 0.1.59 (460bef22a 2021-12-08)
target/lintcheck/sources/anyhow-1.0.38/build.rs:1:null clippy::cargo_common_metadata "package `anyhow` is missing `package.keywords` …
```
> Update lintcheck output to use tables and add markdown support

- .github/workflows/clippy.yml
- .github/workflows/clippy_bors.yml
- clippy_utils/src/lib.rs
- clippy_utils/src/str_utils.rs
r? @xFrednet Since you did the last refactor of the `str_utils` functions in #7873
changelog: Make sure tests in `clippy_utils` are passing by testing it in CI
> Test clippy_utils in CI

- CONTRIBUTING.md
- README.md
> Fixed some typos in README and CONTRIBUTING

- .cargo/config.toml
- .github/workflows/clippy.yml
- .github/workflows/clippy_bors.yml
- Cargo.toml
- clippy_dev/src/update_lints.rs
- clippy_lints/Cargo.toml
- clippy_lints/src/lib.register_lints.rs
- clippy_lints/src/lib.rs
- clippy_lints/src/utils/conf.rs
- clippy_lints/src/utils/internal_lints.rs
- clippy_lints/src/utils/internal_lints/metadata_collector.rs
- clippy_lints/src/utils/mod.rs
- clippy_utils/Cargo.toml
- clippy_utils/src/diagnostics.rs
- clippy_utils/src/paths.rs
- tests/compile-test.rs
- tests/dogfood.rs
This is just simpler and I don't see any downsides.
> Combine internal cargo features

- COPYRIGHT
- LICENSE-APACHE
- LICENSE-MIT
- README.md
- rustc_tools_util/README.md
At this point, I'm just searching for small things to do instead of sleeping or working on my bachelor thesis. :sweat_smile:  Taking one day off will be fine :upside_down_face: 
> Update copyright year for Clippy (2022 edition)

- clippy_lints/src/ptr.rs
- tests/ui/crashes/ice-8386.rs
> Fix ICE in `ptr_arg`

- clippy_lints/src/redundant_clone.rs
> Optimize `redundant_clone`

- clippy_lints/src/methods/unnecessary_to_owned.rs
- tests/ui/unnecessary_to_owned.fixed
- tests/ui/unnecessary_to_owned.rs
- tests/ui/unnecessary_to_owned.stderr
> Fix `unncessary_to_owned` false positive

- clippy_lints/src/lib.register_all.rs
- clippy_lints/src/lib.register_restriction.rs
- clippy_lints/src/lib.register_style.rs
- clippy_lints/src/try_err.rs
Fixes #5757 
changelog: Moved try_err lint to rescrition for #5757
> Moved ``[try_err]`` to restriction

- .github/ISSUE_TEMPLATE/bug_report.yml
> Fix typo in bug report

- Cargo.toml
> specify serde version compatible with codebase

- clippy_lints/src/matches/needless_match.rs
> Fix typo in comment

- CHANGELOG.md
roses are red,
this changelog,
is no longer a todo!
---
> Changelog for Rust 1.61 :octopus:

- clippy_dev/src/main.rs
- clippy_dev/src/new_lint.rs
- clippy_lints/src/assign_ops.rs
- clippy_lints/src/casts/cast_slice_different_sizes.rs
- clippy_lints/src/casts/mod.rs
- clippy_lints/src/default_union_representation.rs
- clippy_lints/src/derive.rs
- clippy_lints/src/main_recursion.rs
- clippy_lints/src/methods/mod.rs
- clippy_lints/src/mutable_debug_assertion.rs
- clippy_lints/src/needless_bitwise_bool.rs
- clippy_lints/src/pass_by_ref_or_value.rs
- clippy_lints/src/redundant_clone.rs
- clippy_lints/src/transmute/mod.rs
- doc/adding_lints.md
- tests/ui/blacklisted_name.rs
Hello! Thank you for this awesome project!
This PR has implemented improved representation.
- Use "lib" instead of "lifb"
- Use "triggered" instead of "triggere"
- Use "blacklisted_name" instead of "blackisted_name"
- Use "stabilization" instead of "stabilisation"
- Use "behavior" instead of "behaviour"
- Use "target" instead of "tartet"
- Use "checked_add" instead of "chcked_add"
- Use "anti-pattern" instead of "antipattern" 
- Use "suggestion" instead of "suggesttion" 
- Use "example" instead of "exampel"
- Use "Cheat Sheet" instead of "Cheatsheet"
---
> Tweak some words improved representation

- clippy_lints/src/methods/filter_map.rs
- tests/ui/manual_filter_map.fixed
- tests/ui/manual_filter_map.rs
- tests/ui/manual_filter_map.stderr
- tests/ui/manual_find_map.fixed
- tests/ui/manual_find_map.rs
- tests/ui/manual_find_map.stderr
close #8920 
Added conditional branching when the clone method is used.
---
changelog: check `clone()` and other variant preserving methods in [`manual_find_map`] and [`manual_filter_map`]
> fix(manual_find_map and manual_filter_map): check clone method

- util/gh-pages/index.html
> Add description meta tag for lint list

- clippy_lints/src/strings.rs
STRING_ADD example, how it should be
> STRING_ADD example

- clippy_lints/src/self_assignment.rs
changelog: Fix example in `SELF_ASSIGNMENT` docs
> Fix example `SELF_ASSIGNMENT`

- book/src/development/basics.md
> Add `dev deprecate` to the development basics

- CHANGELOG.md
- book/src/development/basics.md
- clippy_utils/src/ty.rs
> Fix some links

- util/etc/vscode-tasks.json
> Fix broken link

- tests/ui/cast_size_32bit.stderr
changelog: fix stderr for cast_size_32bit
> Fix stderr for cast_size_32bit

- clippy_lints/src/octal_escapes.rs
> Fix example header

- lintcheck/Cargo.toml
- lintcheck/README.md
- lintcheck/src/main.rs
> Fix small mistakes

- book/src/continuous_integration/github_actions.md
> Rephrased text to remove passive voice for a more active one.

- clippy_lints/src/matches/mod.rs
> Remove extra newlines in [`significant_drop_in_scrutinee`] docs

- book/src/development/infrastructure/book.md
> Fix src link

- tests/ui-cargo/multiple_config_files/warn/src/main.rs
Verified that it actully works on windows
> Enable test multiple_config_files on windows

- clippy_dev/src/fmt.rs
> Tell the user how to revert `dev setup intellij`

- clippy_lints/src/methods/clone_on_copy.rs
- tests/ui/clone_on_copy.fixed
- tests/ui/clone_on_copy.rs
- tests/ui/clone_on_copy.stderr
> add paren before '?' when suggesting deref for clone_on_copy

- clippy_lints/src/casts/cast_abs_to_unsigned.rs
- tests/ui/cast_abs_to_unsigned.fixed
- tests/ui/cast_abs_to_unsigned.rs
- tests/ui/cast_abs_to_unsigned.stderr
> Fix cast_abs_to_unsigned with code in parens

- clippy_lints/src/borrow_deref_ref.rs
- clippy_lints/src/doc_link_with_quotes.rs
- clippy_lints/src/duplicate_mod.rs
- clippy_lints/src/methods/mod.rs
- clippy_lints/src/mismatching_type_param_order.rs
- clippy_lints/src/rc_clone_in_vec_init.rs
- clippy_lints/src/unused_rounding.rs
> Update lint versions for 1.63 release

- clippy_lints/src/casts/unnecessary_cast.rs
- tests/ui/unnecessary_cast.fixed
- tests/ui/unnecessary_cast.rs
- tests/ui/unnecessary_cast.stderr
> remove parenthesis from `unnecessary_cast` suggestion

- clippy_utils/src/macros.rs
- tests/ui/explicit_write.fixed
- tests/ui/explicit_write.rs
- tests/ui/explicit_write.stderr
Woops, forgot visitors don't walk themselves
Fixes #9468
r? @giraffate
> Fix FormatArgsExpn parsing of FormatSpec positions

- clippy_lints/src/operators/arithmetic_side_effects.rs
- tests/ui/arithmetic_side_effects.rs
- tests/ui/arithmetic_side_effects.stderr
* Adding or Subtracting 0
* Division and Module of anything other than 0
* Multiplying 1 or 0
changelog: [arithmetic-side-effects] More non-overflowing operations
> [arithmetic-side-effects] More non-overflowing ops

- clippy_lints/src/utils/author.rs
- tests/ui/author.stdout
- tests/ui/author/blocks.stdout
- tests/ui/author/call.stdout
- tests/ui/author/if.stdout
- tests/ui/author/issue_3849.stdout
- tests/ui/author/loop.stdout
- tests/ui/author/matches.stdout
- tests/ui/author/repeat.stdout
- tests/ui/author/struct.stdout
Should help nudge new contributors towards let chains
> Replace if_chain with let chains in `clippy::author` output

- CONTRIBUTING.md
> add missing comma

- tests/ui/crate_level_checks/no_std_main_recursion.rs
Verified that test actually works on windows
> Enable test no_std_main_recursion

- clippy_lints/src/matches/significant_drop_in_scrutinee.rs
- clippy_utils/src/ty.rs
- tests/ui/manual_flatten.rs
- tests/ui/mut_range_bound.rs
- tests/ui/mut_range_bound.stderr
> Fix dupe word typos

- clippy_lints/src/methods/unnecessary_join.rs
- tests/ui/unnecessary_join.stderr
changelog: [`unnecessary_join`] fix turbofish in suggest message
> fix turbofish in suggest message

- clippy_lints/src/methods/mod.rs
> Fixed Typo

- CHANGELOG.md
- clippy_lints/src/box_default.rs
- clippy_lints/src/casts/mod.rs
- clippy_lints/src/disallowed_macros.rs
- clippy_lints/src/format_args.rs
- clippy_lints/src/implicit_saturating_add.rs
- clippy_lints/src/methods/mod.rs
It's really nice to see a changelog with so many suggestion fixes and improvements. Not much else to say. This should be merged with the coming release on 2022-12-15. For the reviewer, please review it and approve it if it looks good. The merge should wait until the release :) 
---
> Changelog 1.66

- tests/ui/wildcard_imports.rs
- tests/ui/wildcard_imports_2021.edition2018.fixed
- tests/ui/wildcard_imports_2021.edition2018.stderr
- tests/ui/wildcard_imports_2021.edition2021.fixed
- tests/ui/wildcard_imports_2021.edition2021.stderr
- tests/ui/wildcard_imports_2021.rs
- tests/ui/wildcard_imports_2021.stderr
> Add 2018/2021 edition tests for wildcard_imports

- clippy_lints/src/types/mod.rs
changelog: [`linkedlist`]: Update description
> Correct Gankra's name in the linkedlist lint

- clippy_lints/src/methods/filter_map.rs
This is a really small fix. 
If someone could take a look at it, I would appreciate it:pray:
---
> chore: fix identation of `if_chain` in `filter_map`

- book/src/installation.md
> Fix typo in installation instructions

- tests/ui/arithmetic_side_effects.rs
- tests/ui/arithmetic_side_effects.stderr
Add tests to ensure that custom types are triggered with any type of arithmetic operation as well as combinations with or without references.
---
> [arithmetic_side_effects] Add more tests related to custom types

- book/src/development/infrastructure/backport.md
- book/src/development/infrastructure/sync.md
> book: move warning to the right place

- book/src/development/proposals/syntax-tree-patterns.md
- clippy_lints/src/functions/impl_trait_in_params.rs
- clippy_lints/src/functions/misnamed_getters.rs
- clippy_lints/src/matches/mod.rs
- clippy_utils/src/lib.rs
- tests/ui/impl_trait_in_params.stderr
- tests/ui/implicit_clone.fixed
- tests/ui/implicit_clone.rs
- tests/ui/new_ret_no_self.rs
> Fixing typos

- tests/dogfood.rs
Run dogfood on all packages before failing the test. Failing early is painful on lints which trigger on multiple crates.
> Run dogfood to completion

- CHANGELOG.md
- clippy_lints/src/almost_complete_range.rs
- clippy_lints/src/fn_null_check.rs
- clippy_lints/src/permissions_set_readonly_false.rs
- clippy_lints/src/size_of_ref.rs
- clippy_lints/src/transmute/mod.rs
Roses are red,
I'm running out of rhymes,
changelogs are crimes????
---
> Update version attribute for 1.68 lints

- book/src/development/adding_lints.md
I don't know how this would be done on Windows or MacOS, feedback appreciated.
I did find this snippet for MacOS but it seems a little sketchy.
https://github.com/rust-lang/rust-clippy/blob/1d1e72308e5bcdf5abe95c1d29dfe82524940061/.github/workflows/clippy_bors.yml#L98-L102
> Add explanation on how to run `cargo-clippy` and `clippy-driver`

- clippy_lints/src/significant_drop_tightening.rs
> Fix typo in significant_drop_tightening

- tests/ui/crashes/ice-10645.rs
- tests/ui/crashes/ice-10645.stderr
- tests/ui/crashes/ice-5207.rs
> split test into 2

- CHANGELOG.md
Roses are red,
Fixing commas,
Is the completed todo.
(It's always impressive, that the poems are getting worse)
---
Follow-up from: https://github.com/rust-lang/rust-clippy/pull/10668
> Catching, stray, commas, (I'll, never, learn, to, use, them, correctly)  :sweat_smile:

- clippy_utils/src/macros.rs
> Update macros.rs (typo)

- clippy_dev/src/dogfood.rs
- clippy_dev/src/lib.rs
- clippy_dev/src/lint.rs
Prints progress as it happens and in colour, and will also show anything printed to stderr
> Inherit stdout/stderr for `cargo dev dogfood`

- README.md
> Bump README copyright

- CHANGELOG.md
- clippy_lints/src/allow_attributes.rs
- clippy_lints/src/collection_is_never_read.rs
- clippy_lints/src/large_futures.rs
- clippy_lints/src/let_with_type_underscore.rs
- clippy_lints/src/methods/mod.rs
- clippy_lints/src/missing_assert_message.rs
- clippy_lints/src/redundant_async_block.rs
Roses are red,
damn I have an exam to cram,
and this rhyme is a scam
---
This poem is... certainly something... Anyways, hope whoever is reading this, has a lovely day full of sunshine without the need to study :D
---
> Changelog for Rust 1.70 :hammer:

- tests/compile-test.rs
Fixes https://github.com/rust-lang/rust-clippy/issues/11036
> Fix compile-test under cargo nextest

- clippy_lints/src/methods/mod.rs
just order the arms in the match block
> Alphabetically order arms in `methods/mod.rs` match

- clippy_lints/src/methods/mod.rs
> Small code style adjustments

- clippy_lints/src/methods/or_fun_call.rs
- tests/ui/unwrap_or_else_default.fixed
- tests/ui/unwrap_or_else_default.rs
> Check that the suggested method exists in unwrap_or_default

- CHANGELOG.md
Roses are red,
new release,
tiny todo
---
---
> Update changelog stable note

- clippy_lints/src/methods/iter_overeager_cloned.rs
- clippy_lints/src/methods/mod.rs
- tests/ui/iter_overeager_cloned.fixed
- tests/ui/iter_overeager_cloned.rs
- tests/ui/iter_overeager_cloned.stderr
changelog: [`iter_overeager_cloned`]
r? @blyxyas
> [`iter_overeager_cloned`]: detect .cloned().all() and .cloned().any()

- clippy_dev/src/new_lint.rs
> Add msrv test template for `cargo dev new_lint --msrv`

- clippy_lints/src/raw_strings.rs
- tests/ui/needless_raw_string.fixed
- tests/ui/needless_raw_string.rs
- tests/ui/needless_raw_string.stderr
- tests/ui/needless_raw_string_hashes.stderr
- tests/ui/write_literal_2.rs
- tests/ui/write_literal_2.stderr
> Describe the type of string in raw_strings lints

- clippy_lints/src/iter_without_into_iter.rs
> Fix two typos in lint description

- CHANGELOG.md
- clippy_lints/src/attrs.rs
- clippy_lints/src/implied_bounds_in_impls.rs
- clippy_lints/src/missing_asserts_for_indexing.rs
- clippy_lints/src/needless_borrows_for_generic_args.rs
- clippy_lints/src/reserve_after_initialization.rs
- clippy_lints/src/unnecessary_map_on_constructor.rs
Roses are red,
Halloween is over,
Have you considered,
Buying a Mars rover?
---
<sub>The cat for the next release can be nominated in the comments</sub>
---
> Changelog for Rust 1.74 🎃

- triagebot.toml
Came back from surgery about 2 days ago, totally cool to review some more PRs.
changelog:none
r? ghost
> Remove me from `users_on_vacation`

- clippy_dev/src/new_lint.rs
> Fix typo in new_lint.rs

- Cargo.toml
> Upgrade anstream to 0.6.0

- triagebot.toml
My life is currently a bit chaotic, and it feels like I can't give reviews the attention they need. I'll finish the PRs I'm assigned to, write the changelogs, and am available when I get pinged etc.  
This is only intended as a temporary pause, as I still genuinely enjoy working with everyone in this repo and seeing Clippy grow day by day.
---
r? @ghost
> Pause PR assignments for xFrednet :)

- book/src/development/trait_checking.md
- book/src/development/type_checking.md
Changes:
Added documentation on how to create types via `Ty` and how to check specific trait implementations.
r? @blyxyas
> Add documentation on trait checking and type construction

- clippy_lints/src/methods/mod.rs
fixes #12457.
---
changelog: [`seek_from_current`]: readability improvements
> [`seek_from_current`]: readability improvements

- clippy_lints/src/functions/mod.rs
> chore: fix typo

- CHANGELOG.md
- clippy_lints/src/methods/mod.rs
- clippy_lints/src/thread_local_initializer_can_be_made_const.rs
- clippy_lints/src/transmute/mod.rs
- clippy_lints/src/unconditional_recursion.rs
Roses are violets,
Red is blue,
Let's create a world,
Perfect for me and you
---
The cat for the next release can be voted on: [here](https://forms.gle/57gbrNvXtCUmrHYh6)
The cat for the next next release can be nominated in the comments and will be voted in the next changelog PR (Submission deadline is 2024-03-30 23:59CET)
---
> Changelog for Clippy 1.77 :school: 

- triagebot.toml
You know what? Having a work-life balance is boring.
I truly enjoyed having a free few weeks, and learned that I need to take a break every once in a while, but not doing reviews feels weird. So, this is me coming back for more :D
---
r? @ghost
> Add xFrednet back to the reviewing rotation :tada: 

- clippy_lints/src/legacy_numeric_constants.rs
- clippy_lints/src/transmute/transmute_int_to_non_zero.rs
- clippy_utils/src/lib.rs
- tests/ui/unconditional_recursion.rs
> Fix various typos

- clippy_lints/src/implied_bounds_in_impls.rs
- clippy_lints/src/methods/unused_enumerate_index.rs
- clippy_lints/src/size_of_ref.rs
- tests/ui/mistyped_literal_suffix.fixed
- tests/ui/mistyped_literal_suffix.rs
- tests/ui/type_id_on_box_unfixable.rs
- util/gh-pages/script.js
> chore: fix some typos in comments

- triagebot.toml
> Add myself back to review rotation

- clippy_lints/src/assigning_clones.rs
- clippy_utils/src/lib.rs
- tests/ui/assigning_clones.fixed
- tests/ui/assigning_clones.rs
- tests/ui/assigning_clones.stderr
> Don't lint assigning_clones on nested late init locals

- tests/ui/double_neg.rs
- tests/ui/infinite_loops.rs
- tests/ui/iter_over_hash_type.rs
> chore: fix some comments

- clippy_lints/src/significant_drop_tightening.rs
fixes #10750
No test as I'm not sure exactly how the type alias caused a stack overflow here. Also removes an unnecessary `HashSet`.
> Normalize type aliases when checking significant drops.

- book/src/usage.md
> Fix minor typo

- triagebot.toml
Hey :wave:
Even though I might have less time than usual, $DAY_JOB soon and working on Cosmographic Software for fun, I think I want to get back in the swing of things here
> Add myself back to reviewer rotation

- clippy_lints/src/utils/internal_lints/invalid_paths.rs
- clippy_utils/src/paths.rs
> resolve `clippy::invalid_paths` on `bool::then`

- clippy_lints/src/operators/mod.rs
Minor fixes for doc for INEFFECTIVE_BIT_MASK and VERBOSE_BIT_MASK
changelog: [none]
> Fix doc for INEFFECTIVE_BIT_MASK and VERBOSE_BIT_MASK

- clippy_lints/src/almost_complete_range.rs
Does less work when the lint doesn't trigger.
> `almost_complete_range`: Delay suggestion creation.

- clippy_lints/src/matches/significant_drop_in_scrutinee.rs
- clippy_lints/src/returns.rs
- lintcheck/src/output.rs
- tests/ui/deref_addrof.fixed
- tests/ui/deref_addrof.rs
- tests/ui/missing_const_for_fn/could_be_const.fixed
- tests/ui/missing_const_for_fn/could_be_const.rs
- tests/ui/zero_repeat_side_effects.fixed
- tests/ui/zero_repeat_side_effects.rs
> Reduce typo count.

- Cargo.toml
- tests/compile-test.rs
r? @Alexendoo 
cc @GuillaumeGomez 
> Bump ui_test version -> 0.25

- clippy_lints/src/loops/explicit_counter_loop.rs
- clippy_lints/src/loops/mod.rs
- clippy_utils/src/higher.rs
- tests/ui/explicit_counter_loop.rs
- tests/ui/explicit_counter_loop.stderr
- tests/ui/for_kv_map.fixed
- tests/ui/for_kv_map.rs
- tests/ui/for_kv_map.stderr
changelog: [`explicit_counter_loop`]: fix label drop
changelog: [`for_kv_map`]: add label drop test
> Fix fix under loop may dropping loop label when applying fix.

- util/gh-pages/script.js
Just a small cleanup for the lints page JS source code.
r? @Alexendoo 
changelog: Clean up clippy lints page JS source code
> Clean up clippy lints page JS source code

- clippy_lints/src/implicit_hasher.rs
- tests/ui/crashes/ice-3717.stderr
- tests/ui/implicit_hasher.fixed
- tests/ui/implicit_hasher.rs
- tests/ui/implicit_hasher.stderr
The second commit individually shows the diagnostic change
----
> Use a single multipart suggestion for `implicit_hasher`

- triagebot.toml
> flip1995: 2 week vacation

- clippy_lints/src/matches/collapsible_match.rs
- tests/ui/collapsible_match.stderr
> Improve `collapsible_match` error message syntax

- clippy_config/src/msrvs.rs
- clippy_lints/src/loops/explicit_iter_loop.rs
- tests/ui/explicit_iter_loop.fixed
- tests/ui/explicit_iter_loop.rs
close #13184 
This PR fix false positive in explicit_iter_loop when msrv < 1.80
changelog: fix false positive in explicit_iter_loop when msrv < 1.80
> fix false positive in explicit_iter_loop with msrv

- clippy_lints/src/panic_unimplemented.rs
- clippy_utils/src/paths.rs
- tests/ui-toml/panic/panic.rs
- tests/ui-toml/panic/panic.stderr
close #13292 
This PR detects `std::panic::panic_any` in panic lint.
changelog: check std::panic::panic_any in panic lint
> check std::panic::panic_any in panic lint

- clippy_lints/src/attrs/allow_attributes_without_reason.rs
- clippy_utils/src/sugg.rs
> Minor code simplification

- triagebot.toml
> End my vacation

- triagebot.toml
This reverts commit 5ea7044d7297de1d663e374494905330df2ca863. I needed some time free from reviewing to focus on the Project Goal and myself.
Now I'm much better, and we can continue reviewing!
I hope that I can approve this myself :sweat_smile: 
> Back from burnout

- triagebot.toml
> Unvacation giraffate and remove gh-pages -> xFrednet assignment

- book/src/development/common_tools_writing_lints.md
- book/src/development/type_checking.md
> fix examples using `Ty.kind()` in the book

- clippy_lints/src/regex.rs
> Examples fixes for regex

- tests/ui/crashes/ice-11230.fixed
- tests/ui/crashes/ice-11230.stderr
Closes #11230
changelog:  none
> add more test coverage for #11230

- util/gh-pages/script.js
> fix version search in the website

- clippy_lints/src/methods/range_zip_with_len.rs
- tests/ui/range.fixed
- tests/ui/range.stderr
changelog: [`range_zip_with_len`]: add autofix
> autofix for `range_zip_with_len`

- book/src/development/basics.md
> fix broken link of UI test in the book

- clippy_lints/src/macro_use.rs
> Clarify example for macro_use

- clippy_lints/src/casts/mod.rs
> add a preferred fix for `cast_possible_wrap` description

- clippy_lints/src/doc/lazy_continuation.rs
> Remove obsolete TODO

- clippy_lints/src/entry.rs
- tests/ui/entry.fixed
- tests/ui/entry.rs
Closes #11976 
changelog: [`map_entry`]: fix FP inside closure
> fix: `map_entry` FP inside closure

- clippy_lints/src/useless_conversion.rs
The `has_eligible_receiver()` function had been adapted *a minima* when the `sym::ControlFlow` diagnostic item has been added to rustc. This refactors the function content to make its meaning clearer.
> Refactor function after adding a new diagnostic item

- COPYRIGHT
- LICENSE-APACHE
- LICENSE-MIT
- README.md
- clippy_utils/README.md
- rustc_tools_util/README.md
> Update copyright year

- book/src/development/macro_expansions.md
This comes up every now and then in PRs, so I think it would be good if we had an explanation in a central place that we can link to.
> Explain `is_from_proc_macro` and `proc_macros` auxiliary crate in the book

- book/src/development/the_team.md
Cleaning up the last few loose ends. To everyone reading this: I hope you have a beautiful day!
r? @ghost
> Remove `@xFrednet` from docs :wave:

- triagebot.toml
I love this project but I (again) don't have the time nor energy at the moment. Will go through my current assignments over time and still review occasionally.
PS: sorry about the branch on upstream!
> Leave assignments for now

- triagebot.toml
> Add myself to reviewer rotation

- clippy_lints/src/casts/mod.rs
> Fix type error in lint description

- clippy_lints/src/derive.rs
> Fix a typo in derive.rs comment

- CHANGELOG.md
Violets are red,
Roses are blue,
We miss our penguin,
This is hard to do.
---
Penguin of the release 
This is not a cat. But nominations are open in the comments for the next release! :heart_eyes_cat: 
---
> Changelog for Clippy 1.86 :penguin: 

- triagebot.toml
> samueltardieu: vacation for ~3 weeks

- triagebot.toml
> Remove myself from users on vacation

- tests/dogfood.rs
Where you would previously see
```
error: some lint
--> src/lib.rs:1:2
```
it will now print
```
error: some lint
--> clippy_lints/src/lib.rs:1:2
```
Ensuring you can click the link in the terminal
A workaround for us not being in a workspace
> Fix diagnostic paths printed by dogfood test

- clippy_lints/src/cognitive_complexity.rs
- clippy_lints/src/copies.rs
- clippy_lints/src/extra_unused_type_parameters.rs
- clippy_lints/src/functions/must_use.rs
- clippy_lints/src/functions/result.rs
- clippy_lints/src/implicit_hasher.rs
- clippy_lints/src/inherent_to_string.rs
- clippy_lints/src/lifetimes.rs
- clippy_lints/src/methods/manual_inspect.rs
- clippy_lints/src/missing_const_for_fn.rs
- clippy_lints/src/mut_key.rs
- clippy_lints/src/operators/assign_op_pattern.rs
- clippy_lints/src/suspicious_trait_impl.rs
- clippy_utils/src/lib.rs
- clippy_utils/src/source.rs
- tests/ui-toml/collapsible_if/collapsible_if.fixed
- tests/ui-toml/collapsible_if/collapsible_if.stderr
- tests/ui/manual_inspect.fixed
- tests/ui/manual_inspect.stderr
This mainly fixes `with_leading_whitespace` not always adding the whitespace it can.
> Misc changes

- clippy_lints/src/mut_reference.rs
One downside to this is that, since the patterns matched against (on the left) are quite long, it's a bit difficult to see what's even getting matched. Using `matches!()` could help with that
> refactor(mut_reference): replace `match` with `if-let` to reduce nesting 

- triagebot.toml
https://rust-lang.zulipchat.com/#narrow/channel/257328-clippy/topic/Outside.20rotation.20until.20June.2030/with/520912074
> Mark myself as on vacation until June 30

- clippy_utils/src/lib.rs
> Remove unneeded lifetime

- .github/workflows/feature_freeze.yml
> Activate feature freeze automated notice

- book/src/development/infrastructure/backport.md
- book/src/development/infrastructure/changelog_update.md
Polishing changelog update doc
r? @flip1995
> Polishing changelog update doc

- Cargo.toml
Bump termize to remove one more dep with winapi (https://github.com/JohnTitor/termize/releases/tag/v0.2.0)
> bump termize

- clippy_lints/src/ineffective_open_options.rs
This is needed to split the lint crate.
> `ineffective_open_options`: remove `method_call` use

- clippy_lints/src/doc/broken_link.rs
We were calling an expensive functions lots of times resulting in 12 million instructions for `broken_links`, the doc lint optimization is not over yet...
Now the instruction count for `broken_links` is at a healthy 27 thousand. This improvement is a difference of 1.5% in the total analysis time for `tokio`.
changelog:[`broken_links`]: Optimize by 99.77%
> Optimize broken_links by 99.77%

- clippy_utils/src/source.rs
> clean-up `SourceFileRange::as_str`

- clippy_lints/src/methods/expect_fun_call.rs
> `expect_fun_call`: move helper functions out of the main one

- .github/workflows/feature_freeze.yml
remove redundant word in comment
> chore: remove redundant word in comment

- clippy_lints/src/casts/mod.rs
- clippy_lints/src/casts/ptr_as_ptr.rs
> `ptr_as_ptr`: move to `if`

- triagebot.toml
Forgot to do this at the start of the week. Will be back on the 15th. (That's also the reason why I forgot about the meeting. Sorry for that!)
r? @ghost
> Set flip1995 to on-vacation

- clippy_lints/src/replace_box.rs
> `replace_box`: clean-up a bit
