clippy_lints/src/loops.rs
clippy_lints/src/main_recursion.rs
clippy_lints/src/utils/mod.rs
tests/ui/issue-3746.rs

closes #3746.
changelog: move no_std detection to utils, don't fire empty_loop in no_std crates

don't fire `empty_loop` in `no_std` crates

---

clippy_lints/src/empty_enum.rs
tests/ui/empty_enum.stderr

closes #4905
changelog: improve `empty_enum` help message and documentation.

improve `empty_enum` documentation

---

tests/ui/match_same_arms.rs
tests/ui/match_same_arms.stderr
tests/ui/match_same_arms2.rs
tests/ui/match_same_arms2.stderr

Split up `match_same_arms` ui test

---

clippy_lints/src/formatting.rs
tests/ui/formatting.rs
tests/ui/formatting.stderr

Closes #4399 
changelog: dont fire `possible_missing_comma` if intendation is present
I suspect there is already a utils function for indentation (but searching indent didn't yield a function for that), and my solution is certainly not universal, but it's probably the best we can do.

dont fire `possible_missing_comma` if intendation is present

---

clippy_lints/src/utils/mod.rs

This is the same change as the first commit in rust-lang/rust#68407, but applied to clippy.
The new code should work both before and after the changes in rust-lang/rust#68407.

Don't use ExpnKind::descr to get the name of a bang macro.

---

tests/ui/missing_const_for_fn/could_be_const.rs
tests/ui/missing_const_for_fn/could_be_const.stderr

`const_string_new` is stable since Rust 1.39

Resolve FIXME: String::new is now a const fn

---

clippy_lints/src/methods/mod.rs
tests/ui/expect.stderr
tests/ui/filter_methods.stderr
tests/ui/find_map.stderr
tests/ui/iter_nth.stderr
tests/ui/iter_skip_next.stderr
tests/ui/ok_expect.stderr
tests/ui/unwrap.stderr

Uses `span_help_and_lint` instead of `span_lint` and `span_lint_and_sugg` instead of `span_lint_and_then`.

Clean up `span_lint` in `methods/mod.rs`

---

CHANGELOG.md
README.md
clippy_lints/src/lib.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/single_component_path_imports.rs
clippy_lints/src/types.rs
src/lintlist/mod.rs
tests/ui/single_component_path_imports.fixed
tests/ui/single_component_path_imports.rs
tests/ui/single_component_path_imports.stderr

fixes #4903.
Check list:
[lint_naming]: https://rust-lang.github.io/rfcs/0344-conventions-galore.html#lints
---
changelog: implement lint that warn about single component path imports(`use ident;`).

Closes Issue4903

---

tests/ui/enum_clike_unportable_variant.rs
tests/ui/enum_clike_unportable_variant.stderr

Revive one test since mentioned ICE has been resolved.

Revive test in `enum_clike_unportable_variant`

---

clippy_lints/src/methods/mod.rs

The documentation for RESULT_EXPECT_USED includes this code:
let res: Result<usize, ()> = Ok(1);
res?;
Because the code fence didn't start with `rust`, the code wasn't highlighted and the line starting with `#` was displayed on the website. This is now fixed.
EDIT: I noticed that highlighting for some other lints is broken as well. It only works if the code fence looks like this:
````markdown
```rust
// ..
```
````
However, many code blocks were ignored. I un-ignored most code blocks and made them compile by adding hidden code with `#`. While doing so, I found two mistakes:
```rust
opt.map_or(None, |a| a + 1)
// instead of
opt.map_or(None, |a| Some(a + 1))
```
and
```rust
fn as_str(self) -> &str
// instead of
fn as_str(self) -> &'static str
```

Fix syntax highlighting of code fences

---

tests/ui/borrow_box.stderr
tests/ui/bytecount.stderr
tests/ui/checked_unwrap/complex_conditionals.stderr
tests/ui/checked_unwrap/simple_conditionals.stderr
tests/ui/cstring.stderr
tests/ui/default_lint.stderr
tests/ui/fallible_impl_from.stderr
tests/ui/get_unwrap.stderr
tests/ui/identity_conversion.stderr
tests/ui/inefficient_to_string.stderr
tests/ui/infinite_iter.stderr
tests/ui/inherent_to_string.stderr
tests/ui/issue_2356.stderr
tests/ui/lint_without_lint_pass.stderr
tests/ui/mem_discriminant.stderr
tests/ui/mem_discriminant_unfixable.stderr
tests/ui/option_and_then_some.stderr
tests/ui/outer_expn_data.stderr
tests/ui/replace_consts.stderr
tests/ui/try_err.stderr
tests/ui/type_repetition_in_bounds.stderr
tests/ui/unnecessary_ref.stderr
tests/ui/unneeded_wildcard_pattern.stderr
tests/ui/unused_unit.stderr
tests/ui/useless_asref.stderr
tests/ui/wildcard_enum_match_arm.stderr

update test stderr

---

clippy_lints/src/multiple_crate_versions.rs

This example isn't reproducible now since `ctrlc` upgrades `winapi` to `0.3.x` in `3.1.1`. We should pin their versions to trigger lint correctly.

Tweak documentation in `multiple_crate_versions`

---

clippy_lints/src/methods/mod.rs

closes #5115
changelog: Improve the documentation of `iter_nth_zero`

improve 'iter_nth_zero' documentation

---

clippy_lints/src/misc_early.rs

(Fixes) #4681 (possibly)
The issue likely occurs due to `lit_snip.len() < suffix.len() + 1`. You can see similar backtrace to change it to `lit_snip.len() - suffix.len() - 1000` or something then run `cargo test --release`.
But I couldn't come up with the test so I'd leave the issue open if we want.
changelog: Fix potential ICE in `misc_early`

Use `checked_sub` to avoid index out of bounds

---

clippy_dev/src/stderr_length_check.rs
tests/ui/indexing_slicing_index.rs
tests/ui/indexing_slicing_index.stderr
tests/ui/indexing_slicing_slice.rs
tests/ui/indexing_slicing_slice.stderr

Closes #2038
Now all the stderrs are less than 200 lines :tada: 

Split up `indexing_slicing` ui test

---

clippy_lints/src/lib.rs
clippy_lints/src/utils/conf.rs

* Fix a few typos
* Handle Option<&Path> early
* Use `env::var_os` when possible

Few improvement to `utils::conf` module

---

setup-toolchain.sh

If `rustup-toolchain-install-master` fails to install master
toolchain (in case `rustup update` executes at the same time 
it would remove the tmp directory), `cargo search` (which use 
master toolchain after `rustup override` command) will fail. 
This leads to `setup-toolchain` fails too.

Prevent failing to restart setup-toolchain

---

tests/cargo/mod.rs
tests/compile-test.rs
tests/dogfood.rs

* Hopefully this finally resolves the "multiple matching crates" error, e.g. #4015
* This handle some convenient CARGO env like CARGO_TARGET_DIR and CARGO_BUILD_TARGET

Improve compile_test and dogfood tests

---

clippy_lints/src/unwrap.rs
tests/ui/checked_unwrap/simple_conditionals.rs
tests/ui/checked_unwrap/simple_conditionals.stderr

Fixes #5131
I think we shouldn't lint `{panicking, unnecessary}_unwrap` in macros, not just `assert!`.
changelog: Fix false positive in `unnecessary_unwrap`

Do not lint `unnecessary_unwrap` in external macros

---

clippy_lints/src/misc_early.rs
clippy_lints/src/non_expressive_names.rs
clippy_lints/src/returns.rs
clippy_lints/src/utils/internal_lints.rs
tests/ui/custom_ice_message.stderr

Rustup to rust-lang/rust#68788

---

tests/ui/assertions_on_constants.stderr
tests/ui/checked_unwrap/simple_conditionals.stderr
tests/ui/crashes/ice-2636.stderr
tests/ui/declare_interior_mutable_const.stderr
tests/ui/default_lint.stderr
tests/ui/derive_hash_xor_eq.stderr
tests/ui/doc_unsafe.stderr
tests/ui/fallible_impl_from.stderr
tests/ui/implicit_hasher.stderr
tests/ui/lint_without_lint_pass.stderr
tests/ui/match_same_arms2.stderr
tests/ui/mem_discriminant.stderr
tests/ui/mem_replace_macro.stderr
tests/ui/mut_mut.stderr
tests/ui/unit_cmp.stderr
tests/ui/unseparated_prefix_literals.stderr
tests/ui/update-all-references.sh
tests/ui/use_self.stderr

cc https://github.com/rust-lang/rust/pull/67359

Rustup https://github.com/rust-lang/rust/pull/67359

---

tests/cargo/mod.rs
tests/compile-test.rs
tests/dogfood.rs

Sadly, this mostly reverts  #5121. Now I use HashMap to only store one rlib
per crate. But that would not work when non-compatible version of the same crate show up.

Fix error E0460 when compiled on Rustc repo

---

CHANGELOG.md
README.md
clippy_lints/src/lib.rs
clippy_lints/src/option_env_unwrap.rs
src/lintlist/mod.rs
tests/ui/auxiliary/macro_rules.rs
tests/ui/option_env_unwrap.rs
tests/ui/option_env_unwrap.stderr

changelog: Add `option-env-unwrap` lint
Fixes #5147

Add `option-env-unwrap` lint

---

tests/cargo/mod.rs

r? @lzutao 
I got 
```
thread '[ui] ui/crashes/ice-1969.rs' panicked at 'failed to exec `"target/debug/test_build_base/crashes/ice-1969.stage-id"`: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/pkrones/.cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.4.0/src/runtest.rs:1350:25
```
on tests with `// run-pass` locally. The reason for this is, that I haven't set `CARGO_TARGET_DIR` and then `"target"` was used as the `CARGO_TARGET_DIR`. It seems, that `compiletest-rs` cannot deal with relative paths for `// run-pass` tests.

Fix run-pass tests when CARGO_TARGET_DIR is not set

---

CONTRIBUTING.md
clippy_dev/src/new_lint.rs
doc/adding_lints.md
tests/ui/default_lint.rs
tests/ui/default_lint.stderr
tests/ui/lint_without_lint_pass.rs

Remove unnecessary `Lint{Array|Pass}` imports

---

clippy_lints/src/utils/diagnostics.rs

Preparation for rust-lang/rust#68725

Rustup to rust-lang/rust#68725

---

src/driver.rs

cc https://github.com/rust-lang/rust/pull/69059#discussion_r377643560

Impl DefaultCallbacks on our side

---

.github/workflows/clippy.yml
.github/workflows/clippy_bors.yml
.github/workflows/clippy_dev.yml
.github/workflows/deploy.yml
.github/workflows/remark.yml

Fix GHA after the merge

---

README.md

For some reason GHA classifies the bors merges on the master branch as a
push to the auto branch, even though the workflow got triggered by a
push to the master branch. I guess this has something to do with the
same commit hash on master+auto directly after the merge?

Change badge branch from master to auto

---

clippy_lints/src/misc_early.rs
tests/ui/literals.rs
tests/ui/literals.stderr

Fixes #5169
changelog: Fix false positive in `zero_prefixed_literal`

Fix false positive in `zero_prefixed_literal`

---

clippy_lints/Cargo.toml

deps: update pulldown-cmark from 0.6 to 0.7

---

.github/deploy.sh
util/gh-pages/versions.html
util/versions.py

**This should be merged shortly after** #5172
This extracts the python code that generated the `versions.json` file and now sorts the versions. in addition to that it improves the order on the website, respecting the new `rust-*` directories.
The new appearance of the documentation site can be previewed here: https://flip1995.github.io/rust-clippy/
changelog: Add documentation for Clippy stable releases at https://rust-lang.github.io/rust-clippy/

Improve deployment and documentation

---

clippy_dev/src/lib.rs
clippy_dev/src/main.rs
clippy_lints/src/lib.rs
doc/adding_lints.md

Let update_lints also generate the internal lints

---

clippy_lints/src/literal_representation.rs

Octal numbers can't have 8 in them ;)

Typo in literal_representation.rs

---

clippy_lints/src/methods/mod.rs
clippy_lints/src/needless_pass_by_value.rs

These regions will all be `ReErased` soon. (rust-lang/rust#69189)

Avoid using regions from `TypeckTables`

---

clippy_lints/src/escape.rs
clippy_lints/src/len_zero.rs
clippy_lints/src/lib.rs
clippy_lints/src/loops.rs
clippy_lints/src/needless_pass_by_value.rs
clippy_lints/src/utils/mod.rs
clippy_lints/src/utils/usage.rs

Rustup to rust-lang/rust#67953

---

clippy_lints/src/single_component_path_imports.rs
tests/ui/single_component_path_imports.fixed
tests/ui/single_component_path_imports.rs

Fixes #5154
changelog: Fix false positive in `single_component_path_imports`

Don't lint `single_component_path_imports` in macros

---

clippy_lints/Cargo.toml

Should reduce `pulldown-cmark` size.
ref. https://github.com/raphlinus/pulldown-cmark#build-options

Reduce `pulldown-cmark` size

---

clippy_lints/src/functions.rs
clippy_lints/src/lifetimes.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/ptr.rs
clippy_lints/src/returns.rs
clippy_lints/src/types.rs
clippy_lints/src/use_self.rs
clippy_lints/src/utils/hir_utils.rs

Rustup to rust-lang/rust#69179

Rename `FunctionRetTy` to `FnRetTy`

---

clippy_lints/src/doc.rs
clippy_lints/src/utils/paths.rs
tests/ui/doc_errors.rs
tests/ui/doc_errors.stderr

This adds the `missing_errors_doc` lint to async functions.
changelog: Make [`missing_errors_doc`] lint also trigger on `async` functions

Expand `missing_errors_doc` to also work on async functions

---

clippy_lints/src/approx_const.rs
tests/ui/approx_const.rs
tests/ui/approx_const.stderr

changelog: Add constants `LOG2_10` and `LOG10_2` to `approx_const` lint

Add `LOG2_10` and `LOG10_2` to `approx_const` lint

---

clippy_lints/src/consts.rs
clippy_lints/src/enum_clike.rs

Rustup to rust-lang/rust#69181

---

clippy_lints/src/redundant_clone.rs

Migration to [the new dataflow framework](https://github.com/rust-lang/rust/pull/65672) is ongoing in rustc. This PR updates the dataflow impl in `redundant_clone` lint.
---

redundant_clone: Migrate to new dataflow framework

---

tests/ui/indexing_slicing_index.stderr

rustup https://github.com/rust-lang/rust/pull/69325, update test stderr

---

clippy_lints/src/doc.rs
tests/ui/crashes/ice-5207.rs

Fixes #5207
changelog: Fix ICE in `missing_errors_doc`

Use generator own DefId

---

clippy_lints/src/missing_const_for_fn.rs
tests/ui/missing_const_for_fn/cant_be_const.rs
tests/ui/missing_const_for_fn/could_be_const.rs
tests/ui/missing_const_for_fn/could_be_const.stderr

`const` functions cannot have const generic parameters so prevent the
`missing_const_for_fn` lint from firing in that case.
changelog: Fix false positive in `missing_const_for_fn`
Fixes #5192

Prevent `missing_const_for_fn` on functions with const generic params

---

clippy_lints/src/excessive_bools.rs
clippy_lints/src/non_expressive_names.rs
clippy_lints/src/redundant_static_lifetimes.rs

Rustup to rust-lang/rust#69366

---

.github/workflows/deploy.yml

Usually, we don't have to run deploy action on other repos, let's ignore there.

Do not run deploy action on other repos

---

clippy_lints/src/non_copy_const.rs

Rustup to rust-lang/rust#69469

---

tests/ui/crashes/ice-5238.rs

add test for #5238

---

clippy_lints/src/attrs.rs
tests/ui/useless_attribute.fixed
tests/ui/useless_attribute.rs
tests/ui/useless_attribute.stderr

This PR whitelists the `unused` attribute with `use` items and adds a corresponding test case.
Fixes: #5229

Whitelist unused attribute for use items.

---

clippy_lints/src/lib.rs
clippy_lints/src/write.rs
tests/ui/print.stderr

Fixes #5039
changelog: Don't trigger [`use_debug`] lint in Debug impl

Don't trigger use_debug lint in Debug impl

---

clippy_lints/src/consts.rs
clippy_lints/src/indexing_slicing.rs
clippy_lints/src/methods/mod.rs
tests/ui/crashes/ice-5223.rs

Fixes #5223
changelog: Fix ICE in evaluating usizes

Use `try_eval_usize` over `eval_usize`

---

.github/workflows/clippy_bors.yml

RLS updated their dependencies in rust-lang/rls#1646 so we can revive the integration test. I confirm it passed on my local.

Revive rls integration test

---

clippy_lints/src/floating_point_arithmetic.rs
tests/ui/floating_point_abs.fixed
tests/ui/floating_point_abs.rs
tests/ui/floating_point_abs.stderr

Closes #5224  
changelog: Enhance [`suboptimal_flops`] lint to detect manual implementations of the `abs` method

Detect usage of custom floating-point abs implementation 

---

clippy_lints/src/question_mark.rs
clippy_lints/src/types.rs
tests/ui/question_mark.fixed
tests/ui/question_mark.rs
tests/ui/question_mark.stderr

Fixes #5260
changelog: lint `if let Some` and early return in `question_mark` lint

Lint `if let Some` and early return in question_mark lint

---

.github/deploy.sh

By hand updating the documentation for the `rust-1.41.1` release, I found, that the deploy script was buggy for tag deploys. Luckily we weren't affected yet (will only run if the commit of the tag already has the workflow config, so probably ~`rust-1.43.0`)
The bug:
When a tag was deployed, until now it also updated the master documentation to the state of the tag. This was because the `git add .` not only updated the files created or modified by the tag commit, but also the master lints.json file.

Fix deploy script for tag deploys

---

CHANGELOG.md
clippy_lints/src/lib.rs
clippy_lints/src/macro_use.rs
src/lintlist/mod.rs
tests/ui/macro_use_imports.rs
tests/ui/macro_use_imports.stderr

I missed this during review of #5230. We can just do this, without deprecating the old name, since this lint didn't hit nightly rustc yet.

Rename macro_use_import -> macro_use_imports

---

clippy_lints/src/map_unit_fn.rs
tests/ui/option_map_unit_fn_fixable.stderr
tests/ui/result_map_unit_fn_fixable.stderr

Instead of saying "unit function", use the phrase the description uses: "function that returns the unit type".
Fixes #5180.
changelog: Improve error messages for {option,result}_map_unit_fn

Improve error messages for {option,result}_map_unit_fn

---

clippy_lints/src/matches.rs
tests/ui/match_single_binding.fixed
tests/ui/match_single_binding.rs
tests/ui/match_single_binding.stderr

Fix bad suggestion when `match_single_binding` lints when inside a local (let) statement.
Fixes #5267

Fix match single binding when in a let stmt

---

clippy_lints/src/misc_early.rs
tests/ui/patterns.fixed
tests/ui/patterns.rs
tests/ui/patterns.stderr

fixes #5271
changelog: redundant_pattern: take binding (ref, ref mut) into account in suggestion (#5271)

redundant_pattern: take binding (ref, ref mut) into account in suggestion

---

clippy_lints/src/map_unit_fn.rs
tests/ui/option_map_unit_fn_fixable.fixed
tests/ui/option_map_unit_fn_fixable.rs
tests/ui/option_map_unit_fn_fixable.stderr

Instead of using `_` as a default placeholder use `a`.
fixes #5180 
changelog: Improve default placeholder in map_unit_fn

Improve placeholder in map_unit_fn

---

doc/adding_lints.md

The rustc-guide is being renamed to the rustc-dev-guide. The discussion is in rust-lang/rustc-guide#470.
This PR revises rustc-guide to rustc-dev-guide in the Readme Markdown file.
Transition tracker: rust-lang/rustc-guide#602

Update rustc-guide to rustc-dev-guide

---

clippy_lints/README.md

clippy_lints: readme: don't mention crates.io since it is no longer used to publish clippy

---

clippy_lints/src/doc.rs
tests/ui/needless_doc_main.rs
tests/ui/needless_doc_main.stderr

This fixes #5280 by checking the language attribute on code blocks.
---

needless_doc_main: only check rust code

---

CONTRIBUTING.md
tests/ui/doc_errors.rs
tests/ui/issue_4266.rs
tests/ui/macro_use_imports.rs
tests/ui/methods.rs
tests/ui/single_component_path_imports.fixed
tests/ui/single_component_path_imports.rs
tests/ui/use_self.fixed
tests/ui/use_self.rs

Now we recommend using `// edition:2018`, so let's use it more widely.
Also replace a too old example with new one in the docs.

Use `edition:2018` flag more widely

---

CHANGELOG.md
README.md
clippy_lints/src/lib.rs
clippy_lints/src/utils/paths.rs
clippy_lints/src/verbose_file_reads.rs
src/lintlist/mod.rs
tests/ui/verbose_file_reads.rs
tests/ui/verbose_file_reads.stderr

Adds lint `verbose_file_reads` which checks for use of File::read_to_end and File::read_to_string. 
Closes https://github.com/rust-lang/rust-clippy/issues/4916
changelog: add lint on File::{read_to_end, read_to_string}

add lint on File::read_to_string and File::read_to_end

---

clippy_lints/src/attrs.rs
clippy_lints/src/doc.rs
clippy_lints/src/functions.rs
clippy_lints/src/inline_fn_without_body.rs
clippy_lints/src/lifetimes.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/missing_doc.rs
clippy_lints/src/missing_inline.rs
clippy_lints/src/mut_key.rs
clippy_lints/src/ptr.rs
clippy_lints/src/trivially_copy_pass_by_ref.rs
clippy_lints/src/types.rs

Rustup to rust-lang/rust#69674

---

clippy_lints/src/redundant_clone.rs
tests/ui/format.fixed
tests/ui/format.rs
tests/ui/redundant_clone.fixed
tests/ui/redundant_clone.rs
tests/ui/redundant_clone.stderr

Fixes #5303.
---
changelog: Extend `redundant_clone` to the case that cloned value is not consumed

Extend `redundant_clone` to the case that cloned value is not consumed

---

Cargo.toml
tests/integration.rs

This removes the `git2` dependency (used in the integration test).  Updating git2 is awkward because both cargo and clippy have to be updated in sync, so this removes that requirement. It didn't look like it was using the git2 library for any particular reason, so this just launches the `git` executable, which should be available more or less everywhere.
This unblocks updating Cargo.

Remove git2 dependency.

---

clippy_lints/src/wildcard_imports.rs

changelog: Improve [`wildcard_imports`] documentation

Document that wildcard_imports doesn't warn about `use ...::prelude::*;`

---

clippy_lints/src/assign_ops.rs
clippy_lints/src/block_in_if_condition.rs
clippy_lints/src/booleans.rs
clippy_lints/src/cognitive_complexity.rs
clippy_lints/src/doc.rs
clippy_lints/src/entry.rs
clippy_lints/src/escape.rs
clippy_lints/src/eval_order_dependence.rs
clippy_lints/src/fallible_impl_from.rs
clippy_lints/src/functions.rs
clippy_lints/src/let_if_seq.rs
clippy_lints/src/lifetimes.rs
clippy_lints/src/loops.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/option_map_unwrap_or.rs
clippy_lints/src/methods/unnecessary_filter_map.rs
clippy_lints/src/missing_doc.rs
clippy_lints/src/mut_mut.rs
clippy_lints/src/mutable_debug_assertion.rs
clippy_lints/src/slow_vector_initialization.rs
clippy_lints/src/suspicious_trait_impl.rs
clippy_lints/src/types.rs
clippy_lints/src/unused_self.rs
clippy_lints/src/unwrap.rs
clippy_lints/src/use_self.rs
clippy_lints/src/utils/author.rs
clippy_lints/src/utils/internal_lints.rs
clippy_lints/src/utils/mod.rs
clippy_lints/src/utils/ptr.rs
clippy_lints/src/utils/usage.rs

rustup https://github.com/rust-lang/rust/pull/68944

---

clippy_lints/src/consts.rs
clippy_lints/src/eval_order_dependence.rs
clippy_lints/src/lib.rs
clippy_lints/src/lifetimes.rs
clippy_lints/src/loops.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/no_effect.rs
clippy_lints/src/non_copy_const.rs
clippy_lints/src/utils/mod.rs

Make use of `or_patterns` feature

---

clippy_lints/src/attrs.rs
clippy_lints/src/doc.rs
clippy_lints/src/fallible_impl_from.rs
clippy_lints/src/functions.rs
clippy_lints/src/inherent_to_string.rs
clippy_lints/src/inline_fn_without_body.rs
clippy_lints/src/lifetimes.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/missing_doc.rs
clippy_lints/src/missing_inline.rs
clippy_lints/src/mut_key.rs
clippy_lints/src/new_without_default.rs
clippy_lints/src/ptr.rs
clippy_lints/src/types.rs
clippy_lints/src/unused_self.rs
clippy_lints/src/use_self.rs
clippy_lints/src/utils/inspector.rs
clippy_lints/src/utils/mod.rs

rustup https://github.com/rust-lang/rust/pull/69738

---

clippy_lints/src/approx_const.rs
clippy_lints/src/assertions_on_constants.rs
clippy_lints/src/block_in_if_condition.rs
clippy_lints/src/needless_bool.rs
clippy_lints/src/swap.rs
clippy_lints/src/types.rs

clean up a few lint docs

---

CHANGELOG.md

In the beta changelog update, I accidentally used the commit of the 1.43.0 beta, instead of the 1.42.0 beta. I fixed this in this PR.
r? @Manishearth 

Update changelog to 1.43.0 beta

---

tests/ui/inefficient_to_string.stderr
tests/ui/transmute.stderr
tests/ui/transmute_ptr_to_ptr.stderr
tests/ui/transmute_ptr_to_ref.stderr

rustups https://github.com/rust-lang/rust/pull/69189 which is part of https://github.com/rust-lang/rust/pull/70085
(at least I think this is the only pr that changes clippy test stdout)

rustup https://github.com/rust-lang/rust/pull/69189

---

clippy_lints/src/lifetimes.rs
tests/ui/issue_4266.stderr
tests/ui/needless_lifetimes.stderr

Changes the span on which the lint is reported to point to only the
function return type instead of the entire function body.
Fixes #5284 

Improvement: Don't show function body in needless_lifetimes

---

util/lintlib.py

In #5135, the configuration macro changed, but the documentation generation script wasn't updated. This PR catches up on this.
[Preview](https://flip1995.github.io/rust-clippy/master/index.html)
r? @Manishearth 
changelog: Document configuration options of lints again.

Fix documentation generation for configurable lints

---

clippy_lints/src/matches.rs
tests/ui/match_single_binding.fixed
tests/ui/match_single_binding.rs
tests/ui/match_single_binding.stderr

Fix the `match_single_binding` lint when triggered inside a closure.
Fixes: #5347 
changelog: Improve suggestion for [`match_single_binding`]

Fix single binding closure

---

CHANGELOG.md
README.md
clippy_lints/src/lib.rs
clippy_lints/src/redundant_pub_crate.rs
clippy_lints/src/utils/conf.rs
clippy_lints/src/utils/numeric_literal.rs
src/lintlist/mod.rs
tests/ui/redundant_pub_crate.fixed
tests/ui/redundant_pub_crate.rs
tests/ui/redundant_pub_crate.stderr
tests/ui/wildcard_imports.fixed
tests/ui/wildcard_imports.rs
tests/ui/wildcard_imports.stderr

changelog: Add `redundant_pub_crate` lint
Closes #5274.

Lint for `pub(crate)` items that are not crate visible due to the visibility of the module that contains them

---

clippy_lints/src/lib.rs
clippy_lints/src/transmute.rs
src/lintlist/mod.rs
tests/ui/transmute_ptr_to_ptr.stderr

cc #5343 
@rust-lang/clippy anyone against moving this to nursery?
changelog: Move [`useless_transmute`] to nursery

Move useless_transmute to nursery

---

clippy_lints/Cargo.toml
clippy_lints/src/block_in_if_condition.rs
clippy_lints/src/eta_reduction.rs
clippy_lints/src/items_after_statements.rs
clippy_lints/src/lifetimes.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/misc.rs
clippy_lints/src/missing_const_for_fn.rs
clippy_lints/src/mutable_debug_assertion.rs
clippy_lints/src/needless_pass_by_value.rs
clippy_lints/src/redundant_clone.rs
clippy_lints/src/swap.rs
clippy_lints/src/trivially_copy_pass_by_ref.rs
clippy_lints/src/utils/mod.rs
clippy_lints/src/utils/sugg.rs

The std equivalent works exactly the same.

Remove dependency on `matches` crate

---

clippy_lints/src/lib.rs
clippy_lints/src/verbose_file_reads.rs
src/lintlist/mod.rs

cc #5368 
Using `File::read` instead of  `fs::read_to_end` does make sense in multiple cases, so this lint is rather restriction, than complexity
changelog: Move [`verbose_file_reads`] to restriction

Move verbose_file_reads to restriction

---

README.md

readme: move "how to run single lint" instructions to "Allowing/denying lints" section.

---

.gitattributes

This change simply moves the `rust` macro definition directly into the
attributes for `*.rs` files.
git commands that recurse from the rust toplevel tree into submodules
produce errors in clippy due to the fact that:
"Custom macro attributes can be defined only in top-level
gitattributes files"
For example, from the toplevel `rust` directory in a rustc development
build, try:
$ git grep "search string" --recurse-submodules
Embedded within the actual results is the error message:
[attr]rust text eol=lf whitespace=tab-in-indent,trailing-space,tabwidth=4
not allowed: src/tools/clippy/.gitattributes:1
Thank you for making Clippy better!
We're collecting our changelog from pull request descriptions.
If your PR only updates to the latest nightly, you can leave the
`changelog` entry as `none`. …

git attribute macros not allowed in submodules

---

clippy_lints/src/unused_self.rs
tests/ui/unused_self.rs

fixes #5351
Remove the for loop in `unused_self` so that lint enabled for one method doesn't trigger on another method.
changelog: Fix false positive in `unused_self` around lint gates on impl items

`unused_self` false positive

---

.github/deploy.sh
.github/workflows/deploy.yml
doc/backport.md
doc/release.md
util/gh-pages/versions.html
util/versions.py

This PR adds documentation on how to create Clippy releases and backports.
This PR also introduces a new backport/release process for Clippy:
- A beta branch is introduced: https://github.com/rust-lang/rust-clippy/tree/beta
- Backports are now done by PRs to the `beta` branch
- also commits to the beta branch will be deployed, so that the documentation page has a tab for the Clippy beta release.
This has two advantages:
1. The Clippy release process is closer to the Rust release process: stable releases are tagged, the beta release has its own branch
2. Backports to beta are easier, since they don't need as much coordination as before. No new branch has to be created for a backport. Just a PR to the beta branch, like in the Rust repo.¹
I tested the deployment here: …

Document how to create releases and backports

---

clippy_lints/src/needless_bool.rs
tests/ui/bool_comparison.fixed
tests/ui/bool_comparison.rs
tests/ui/bool_comparison.stderr

changelog: Check for bool inequality comparison that might be written more concisely
Fixes #4983

Issue4983 bool updates

---

CHANGELOG.md
README.md
clippy_lints/src/lib.rs
clippy_lints/src/unnamed_address.rs
clippy_lints/src/utils/paths.rs
src/lintlist/mod.rs
tests/ui/fn_address_comparisons.rs
tests/ui/fn_address_comparisons.stderr
tests/ui/vtable_address_comparisons.rs
tests/ui/vtable_address_comparisons.stderr

Functions and vtables have an insignificant address. Attempts to compare such addresses will lead to very surprising behaviour. For example: addresses of different functions could compare equal; two trait object pointers representing the same object and the same type could be unequal.
Lint against unnamed address comparisons to avoid issues like those in rust-lang/rust#69757 and rust-lang/rust#54685.
changelog: New lints: [`fn_address_comparisons`] [#5294](https://github.com/rust-lang/rust-clippy/pull/5294), [`vtable_address_comparisons`] [#5294](https://github.com/rust-lang/rust-clippy/pull/5294)

Lint unnamed address comparisons

---

clippy_lints/src/lifetimes.rs

Fixes #5283
changelog: Don't emit lifetime lint warnings for code inside macros.

don't emit lifetime lint warnings for code inside macros.

---

clippy_lints/src/matches.rs
tests/ui/single_match.rs
tests/ui/single_match_else.rs

Avoid single_match lint in macro rules

---

clippy_lints/src/let_underscore.rs
tests/ui/let_underscore_must_use.rs

Allow let_underscore_must_use to be ignored

---

CHANGELOG.md
clippy_lints/src/lib.rs
clippy_lints/src/types.rs
clippy_lints/src/utils/paths.rs
src/lintlist/mod.rs
tests/ui/must_use_candidates.fixed
tests/ui/must_use_candidates.rs
tests/ui/redundant_allocation.fixed
tests/ui/redundant_allocation.rs
tests/ui/redundant_allocation.stderr

refers to  #2394
changelog: Add lints for Rc<Rc<T>> and Rc<Box<T>> and Rc<&T>, Box<&T>
this is based on top of another change #5310 so probably should go after that one.

useless Rc<Rc<T>>, Rc<Box<T>>, Rc<&T>, Box<&T>

---

clippy_lints/src/types.rs

Hint about using tri-state enums to replace legitimate uses of `Option<Option<_>>`
changelog: The docs for `option_option` now suggest using a tri-state enum

Improve docs for option_option

---

clippy_lints/src/escape.rs
clippy_lints/src/large_enum_variant.rs
clippy_lints/src/types.rs
clippy_lints/src/utils/mod.rs

Rustup to rust-lang/rust#70634

---

clippy_lints/src/let_underscore.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/use_self.rs
setup-toolchain.sh

The first commit fixes a portability bug in `setup-toolchain.sh`, while the second rewrites the handling of "trait impl methods" in `use_self` - even if `Ty::walk` could've still been used, it was IMO a misuse.
This could also serve as a PSA: *please* use `hir_ty_to_ty` instead of trying to compare `hir::Ty`s between themselves or against semantic `Ty`s. Its "quasi-deprecation" is 3 years old and doesn't really mean anything, just that it's currently uncached and that we should eventually querify it (either for a single HIR node, or for all of the nodes in an entire definition).
---

rustup: update for the new Ty::walk interface.

---

clippy_lints/src/checked_conversions.rs
clippy_lints/src/float_literal.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/misc.rs
clippy_lints/src/neg_cmp_op_on_partial_ord.rs
clippy_lints/src/types.rs
clippy_lints/src/utils/diagnostics.rs
clippy_lints/src/zero_div_zero.rs
src/lintlist/mod.rs
tests/ui/absurd-extreme-comparisons.rs
tests/ui/absurd-extreme-comparisons.stderr
tests/ui/cmp_nan.rs
tests/ui/cmp_nan.stderr
tests/ui/crashes/mut_mut_macro.rs
tests/ui/enum_clike_unportable_variant.rs
tests/ui/enum_clike_unportable_variant.stderr
tests/ui/float_cmp.rs
tests/ui/float_cmp.stderr
tests/ui/float_cmp_const.rs
tests/ui/float_cmp_const.stderr
tests/ui/if_same_then_else.rs
tests/ui/if_same_then_else2.rs
tests/ui/if_same_then_else2.stderr
tests/ui/zero_div_zero.stderr

changelog: Recommend primitive type associated constants instead of module level constants
In Rust 1.43 integer and float primitive types will have a number of new associated constants. For example `MAX`, `MIN` and a number of constants related to the machine representation of floats. https://github.com/rust-lang/rust/pull/68952
These new constants are preferred over the module level constants in `{core,std}::{f*, u*, i*}`. I have in the last few days made sure that the documentation in the main rust repository uses the new constants in every place I could find (https://github.com/rust-lang/rust/pull/69860, https://github.com/rust-lang/rust/pull/70782). So the next step is naturally to make the linter recommend the new constants as well.
This PR only changes two lints. There are more. But …

Use assoc int and float consts instead of module level ones

---

clippy_lints/src/loops.rs
clippy_lints/src/methods/mod.rs
tests/ui/option_as_ref_deref.fixed
tests/ui/option_as_ref_deref.rs
tests/ui/option_as_ref_deref.stderr

Lint on opt.as_ref().map(|x| &**x). Fixes #5367.
changelog: lint on opt.as_ref().map(|x| &**x)

Ehance opt_as_ref_deref lint.

---

clippy_lints/src/suspicious_trait_impl.rs
tests/ui/suspicious_arithmetic_impl.rs
tests/ui/suspicious_arithmetic_impl.stderr

fixes #5255 
changelog: In suspicious_op_assign_impl ignore all operators in expression if it's part of AssignOp

Incorrect suspicious_op_assign_impl

---

CONTRIBUTING.md

CONTRIBUTING.md: fix broken triage link

---

CONTRIBUTING.md
doc/adding_lints.md

Update doc links and mentioned names in docs

---

clippy_lints/src/assign_ops.rs
clippy_lints/src/cognitive_complexity.rs
clippy_lints/src/lib.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/mutable_debug_assertion.rs
clippy_lints/src/types.rs
src/lintlist/mod.rs
tests/ui/collapsible_else_if.fixed
tests/ui/collapsible_else_if.rs
tests/ui/collapsible_if.fixed
tests/ui/collapsible_if.rs
tests/ui/debug_assert_with_mut_call.rs
tests/ui/for_loop_fixable.fixed
tests/ui/for_loop_fixable.rs
tests/ui/for_loop_fixable.stderr
tests/ui/for_loop_unfixable.rs
tests/ui/for_loop_unfixable.stderr
tests/ui/if_same_then_else2.rs
tests/ui/if_same_then_else2.stderr
tests/ui/rename.fixed
tests/ui/rename.rs
tests/ui/rename.stderr
tests/ui/while_let_on_iterator.rs

As discussed in https://github.com/rust-lang/rust-clippy/issues/5418#issuecomment-610054361; Clippy's current understanding of cognitive complexity is not good enough yet at analyzing code for understandability to have this lint be enabled by default.
changelog: Remove cognitive_complexity from default set of enabled lints

Move cognitive_complexity to nursery

---

clippy_lints/src/methods/mod.rs
tests/ui/methods.rs
tests/ui/methods.stderr

When checking for functions that are potential candidates for trait
implementations check the function header to make sure modifiers like
asyncness, constness and safety match before triggering the lint.
Fixes #5413, #4290
changelog: check fn header along with decl for should_implement_trait

Check fn header along with decl when suggesting to implement trait

---

clippy_lints/src/large_enum_variant.rs
tests/ui/large_enum_variant.stderr

This should make the lint less noisy for now. See [my comment](https://github.com/rust-lang/rust-clippy/issues/5418#issuecomment-610440898) to issue #5418.
---

compare with the second largest instead of the smallest variant

---

clippy_lints/src/methods/mod.rs
tests/ui/unnecessary_clone.rs
tests/ui/unnecessary_clone.stderr

Earlier if arguments to method calls matched the above pattern they were
not reported. This patch ensures such arguments are checked as well.
Fixes #5436
changelog: apply clone_on_copy lint to func args as well

Check for clone-on-copy in argument positions

---

clippy_lints/src/doc.rs
clippy_lints/src/enum_clike.rs
clippy_lints/src/implicit_return.rs
clippy_lints/src/needless_pass_by_value.rs
clippy_lints/src/redundant_clone.rs
clippy_lints/src/utils/mod.rs

rustup https://github.com/rust-lang/rust/pull/69745

---

clippy_lints/src/literal_representation.rs
tests/ui/inconsistent_digit_grouping.fixed
tests/ui/inconsistent_digit_grouping.rs

This change adds a check to the `inconsistent_digit_grouping` to add a check for
NumericLiterals that follow the UUID format of 8-4-4-4-12.
If the NumericLiteral matches the UUID format, no further inconsistent grouping checks
will be performed.
Closes #5431
changelog: Allow UUID style formatting for `inconsistent_digit_grouping` lint

Allow UUID style formatting for `inconsistent_digit_grouping` lint

---

clippy_lints/src/bit_mask.rs

changelog: fixes verbose_bit_mask docs

verbose_bit_mask: fix bit mask used in docs

---

.github/workflows/clippy_bors.yml
tests/integration.rs

Running rustfmt from master is currently broken and [fails our bors build](https://github.com/rust-lang/rust-clippy/runs/582066368#step:10:19):
https://github.com/rust-lang/rust/issues/71077

Temporarily disable rustfmt integration test

---

clippy_lints/src/methods/mod.rs
src/lintlist/mod.rs

changelog: Update documentation for lint new_ret_no_self to reflect that the return type must only contain `Self`, not be `Self`
The lint was changed to be more lenient than the documentation implies in PR #3338 (Related issue #3313)

Update documentation for new_ret_no_self

---

clippy_lints/src/utils/attrs.rs

It's doing exactly the same: https://doc.rust-lang.org/nightly/nightly-rustc/src/rustc_ast/expand/mod.rs.html#8-12

Cleanup: Use rustc's is_proc_macro_attr

---

clippy_lints/src/redundant_clone.rs
tests/ui/redundant_clone.fixed
tests/ui/redundant_clone.rs
tests/ui/redundant_clone.stderr

Check whether slice elements implement Copy before suggesting to drop
the clone method
changelog: add a check for slice indexing on redundant_clone lint

Fixes #5405: redundant clone false positive with arrays

---

clippy_lints/src/len_zero.rs
clippy_lints/src/new_without_default.rs
clippy_lints/src/unused_self.rs
clippy_lints/src/use_self.rs

rustup https://github.com/rust-lang/rust/pull/70643

---

clippy_lints/src/get_last_with_len.rs
clippy_lints/src/loops.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/needless_pass_by_value.rs
clippy_lints/src/ptr.rs
clippy_lints/src/swap.rs
clippy_lints/src/types.rs

It's much shorter than Symbol::intern and the effect should still be clear
---

Cleanup: Use our `sym!` macro more

---

tests/ui/result_map_unit_fn_unfixable.rs
tests/ui/result_map_unit_fn_unfixable.stderr

`x` and the `HasResult` struct were missing in this file.

result_map_unit_fn: Fix incorrect UI tests

---

clippy_lints/src/booleans.rs
clippy_lints/src/cognitive_complexity.rs
clippy_lints/src/doc.rs
clippy_lints/src/fallible_impl_from.rs
clippy_lints/src/if_let_some_result.rs
clippy_lints/src/loops.rs
clippy_lints/src/map_clone.rs
clippy_lints/src/map_unit_fn.rs
clippy_lints/src/matches.rs
clippy_lints/src/mem_replace.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/option_map_unwrap_or.rs
clippy_lints/src/question_mark.rs
clippy_lints/src/types.rs
clippy_lints/src/unwrap.rs
clippy_lints/src/utils/paths.rs

This makes use of some (not all) already existing diagnostic items. Specifically:
* 79982a2: `core::mem::uninitialized`, `core::mem::zeroed`, `alloc::sync::Arc`, `alloc::sync::Rc`
* 83874d0: `Option` and `Result`
cc #5393

Make use of more diagnostic items

---

clippy_lints/src/utils/mod.rs

This replaces our match_def_path implementation with the rustc one.
Note that we can't just use it in all call sites because of the
`&[&str]` / `&[Symbol]` difference in Clippy/rustc.

Refactor: Use rustc's `match_def_path`

---

clippy_lints/src/consts.rs
clippy_lints/src/misc.rs
tests/ui/float_cmp.rs
tests/ui/float_cmp.stderr
tests/ui/float_cmp_const.rs
tests/ui/float_cmp_const.stderr

Fixes #4277 
changelog: 
- Added new handler for expression of index kind (e.g. `arr[i]`). It returns a constant when both array and index are constant, or when the array is constant and all values are equal.
- Trigger float_cmp and float_cmp_const lint when comparing arrays. Allow for comparison when one of the arrays contains only zeros or infinities. 
- Added appropriate tests for such cases.

Add lint for float in array comparison

---

clippy_lints/src/utils/author.rs

rustup https://github.com/rust-lang/rust/pull/71116

---

clippy_lints/src/non_expressive_names.rs
clippy_lints/src/utils/conf.rs
tests/ui-toml/zero_single_char_names/clippy.toml
tests/ui-toml/zero_single_char_names/zero_single_char_names.rs

Fixes: #4086 
changelog:
- Make the inequality strict

Zero single char names

---

clippy_lints/src/large_enum_variant.rs
tests/ui/large_enum_variant.stderr

This reports the sizes of the largest and second-largest variants.
Closes #5459 
changelog: `large_enum_variant`: Report the sizes of the largest and second-largest variants.

large_enum_variant: Report sizes of variants

---

clippy_lints/src/arithmetic.rs
src/lintlist/mod.rs
tests/ui/integer_arithmetic.rs
tests/ui/integer_arithmetic.stderr

Make the `integer_arithmetic` lint detect all the operations that are defined as being capable of overflow in the [Rust Reference](https://doc.rust-lang.org/reference/expressions/operator-expr.html#overflow), by also linting for bit-shifting operations (`<<`, `>>`).
changelog: Disallow bit-shifting in `integer_arithmetic`

Disallow bit-shifting in integer_arithmetic

---

CHANGELOG.md
clippy_lints/src/large_const_arrays.rs
clippy_lints/src/lib.rs
clippy_lints/src/utils/conf.rs
src/lintlist/mod.rs
tests/ui/large_const_arrays.fixed
tests/ui/large_const_arrays.rs
tests/ui/large_const_arrays.stderr
util/lintlib.py

This PR adds the new lint `non_scalar_const` that aims to warn against `const` declaration of large arrays. For performance, because of inlining, large arrays should be preferably declared as `static`.
Note: i made this one to warn on all const arrays, whether they are in a body function or not. I don't know if this is really necessary, i could just reduce this lint to variables out of function scope.
Fixes: #400
changelog: add new lint for large non-scalar types declared as const

Add lint on large non scalar const

---

.github/workflows/clippy_bors.yml

Perhaps doing a system upgrade magically solves the problem?

 perform system upgrade fixes ci issue

---

clippy_lints/src/methods/mod.rs
tests/ui/map_flatten.fixed
tests/ui/map_flatten.rs
tests/ui/map_flatten.stderr

Fixes #5175 
changelog: 
- Trigger the map_flatten lint when map is called on an option
- Add test for such case

Map flatten for option

---

.github/workflows/clippy_dev.yml

changelog: minor: fixes file name in Github Actions workflow `clippy_dev.yml`
I was looking for something else and ended up on that typo, just thought I would fix it.

[fix] Minor typo in GH Actions 'clippy_dev'

---

clippy_lints/src/matches.rs
tests/ui/infallible_destructuring_match.fixed
tests/ui/infallible_destructuring_match.rs
tests/ui/infallible_destructuring_match.stderr
tests/ui/match_single_binding.fixed
tests/ui/match_single_binding.rs
tests/ui/match_single_binding.stderr
tests/ui/rest_pat_in_fully_bound_structs.rs
tests/ui/rest_pat_in_fully_bound_structs.stderr

Don't lint in macros for match lints, more precisely in `check_pat` and `check_local` where it was not the case.
fixes: #5362

Do not lint in macros for match lints

---

clippy_lints/src/types.rs

This lint suggests replacing any code returining `()`-type with `()` literal, which can change the behavior. e.g. `Ok(do_something())` -> `OK(())`.
---

unit_arg suggestion is not really machine-applicable

---

clippy_lints/src/question_mark.rs
tests/ui/question_mark.fixed
tests/ui/question_mark.rs
tests/ui/question_mark.stderr

If a call returns a `!Copy` value, it does so regardless of whether `as_ref()` is added. For example, `foo.into_option().as_ref()?` can be simplified to `foo.into_option()?`.
---
changelog: Improved `question_mark` lint suggestion so that it doesn't add redundant `as_ref()`

question_mark: don't add `as_ref()` for a call expression

---

clippy_lints/src/precedence.rs
tests/ui/precedence.fixed
tests/ui/precedence.rs

First contribution here 😊 ! Do not hesitate to correct me. 
This PR is related to issue #4892 . 
```rust
-literal.method_call(args)
```
The main idea is to not trigger `clippy::precedence` when the method call is an odd function.
```rust
// should trigger lint 
let _ = -1.0_f64.abs() //precedence of method call abs() and neg ('-') is ambiguous
// should not trigger lint
let _ = -1.0_f64.sin() // sin is an odd function => -sin(x) = sin(-x) 
```
Rust allows following literals: 
- char
- string
- integers
- floats
- byte
- bool
Only integers/floats implements the relevant `std::ops::Neg`.
Following odd functions are implemented on i[8-128] and/or f[32-64]: 
- `asin`
- `asinh`
- `atan`
- `atanh`
- `cbrt`
- `fract`
- `round`
- `signum`
- `sin`
- `sinh`
- `tan`
- `tanh `
- `to_degrees`
- …

Fixes issue #4892.

---

CHANGELOG.md
clippy_lints/src/future_not_send.rs
clippy_lints/src/lib.rs
src/lintlist/mod.rs
tests/ui/future_not_send.rs
tests/ui/future_not_send.stderr

changelog: add lint futures_not_send
fixes #5379 
~Remark: one thing that can (should?) still be improved is to directly include the error message from the `Send` check so that the programmer stays in the flow. Currently, getting the actual error message requires a restructuring of the code to make the `Send` constraint explicit.~
It now shows all unmet constraints for allowing the Future to be Send.

add lint futures_not_send

---

clippy_lints/src/redundant_pattern_matching.rs
tests/ui/redundant_pattern_matching.fixed
tests/ui/redundant_pattern_matching.rs
tests/ui/redundant_pattern_matching.stderr

- now it handles `while let` case  (related to #5462)
- better suggestions in `if let` case
changelog: Fix suggestion in `redundant_pattern_matching` and also apply this lint to the `while let` case

fix redundant_pattern_matching lint

---

CHANGELOG.md
clippy_lints/src/implicit_saturating_sub.rs
clippy_lints/src/lib.rs
src/lintlist/mod.rs
tests/ui/implicit_saturating_sub.fixed
tests/ui/implicit_saturating_sub.rs
tests/ui/implicit_saturating_sub.stderr

Fixes: #5399 
I've made a basic skeleton of the lint, would love more feedback on how to make it better.
changelog: Add lint [`implicit_saturating_sub`]

Add lint named implicit_saturating_sub

---

clippy_lints/src/misc.rs
tests/ui/toplevel_ref_arg.fixed
tests/ui/toplevel_ref_arg.rs

The lint suggests turning `for ref x in 0..10 {` into `for ref x in let x = &0..10; {`.
---

Don't trigger toplevel_ref_arg for `for` loops

---

clippy_lints/src/future_not_send.rs

Cleanup: future_not_send: use `utils::return_ty` function

---

clippy_lints/src/derive.rs
clippy_lints/src/loops.rs
clippy_lints/src/missing_inline.rs

This removes some more `node_id` terminology from Clippy and replaces one occurrence of `as_local_node_id` with `as_local_hir_id`, which should be doing the same for that particular case. 

Cleanup: `node_id` -> `hir_id`

---

clippy_lints/src/types.rs
tests/ui/borrow_box.rs
tests/ui/borrow_box.stderr

Update the "borrow box" lint to avoid recommending the following
conversion:
```
// Old
pub fn f(&mut Box<T>) {...}
// New
pub fn f(&mut T) {...}
```
Given a mutable reference to a box, functions may want to change
"which" object the Box is pointing at.
This change avoids recommending removing the "Box" parameter
for mutable references.
changelog: Don't trigger [`borrow_box`] lint on `&mut Box` references

Fix issue #2907.

---

doc/changelog_update.md

I just started working on updating the changelog. Hopefully the docs are a bit clearer now?
r? @flip1995 

Update the changelog update documentation

---

clippy_lints/src/consts.rs
tests/ui/crashes/ice-5497.rs

Fixes #5497
changelog: fix crash on rustc test issue-69020-assoc-const-arith-overflow.rs

fix crash on issue-69020-assoc-const-arith-overflow.rs

---

clippy_lints/src/redundant_clone.rs

cc https://github.com/rust-lang/rust/pull/71044

Rustup "Remove `BodyAndCache`"

---

CHANGELOG.md

[Rendered](https://github.com/phansch/rust-clippy/blob/update_changelog/CHANGELOG.md)

Update CHANGELOG.md for Rust 1.43 and 1.44

---

README.md
clippy_dev/src/lib.rs

fix clippy_dev exit status and make regex match again

---

clippy_lints/src/cognitive_complexity.rs
clippy_lints/src/derive.rs
clippy_lints/src/doc.rs
clippy_lints/src/escape.rs
clippy_lints/src/exit.rs
clippy_lints/src/len_zero.rs
clippy_lints/src/loops.rs
clippy_lints/src/missing_const_for_fn.rs
clippy_lints/src/missing_inline.rs
clippy_lints/src/needless_pass_by_value.rs
clippy_lints/src/new_without_default.rs
clippy_lints/src/utils/inspector.rs
tests/ui/issue_2356.stderr
tests/ui/while_let_on_iterator.fixed
tests/ui/while_let_on_iterator.stderr

There's currently an crash in `ui/new_without_default.rs` that I need to figure out how to avoid.

rustup https://github.com/rust-lang/rust/pull/71215/

---

tests/ui/new_ret_no_self.rs

cc https://github.com/rust-lang/rust-clippy/issues/734#issuecomment-619344352

Add lifetime test case for `new_ret_no_self`

---

.github/workflows/clippy_bors.yml
.github/workflows/deploy.yml

Since not only commits to the master branch, but also tags and the beta branch are deployed, we have to be cautious which version of the deploy script is used. GHA always runs the workflow that is commited on the `ref`, that gets tested. For tagged commits. this is 6 weeks outdated workflows/scripts. To prevent this, this workflow first checks out the deploy.sh script, the website templates and all python scripts generating files for the website.

Deploy time travel

---

clippy_lints/src/cargo_common_metadata.rs
clippy_lints/src/lib.rs
clippy_lints/src/multiple_crate_versions.rs
clippy_lints/src/utils/internal_lints.rs
clippy_lints/src/utils/mod.rs
clippy_lints/src/wildcard_dependencies.rs

Avoid running cargo+internal lints when not enabled

---

clippy_lints/src/map_clone.rs
tests/ui/map_clone.fixed
tests/ui/map_clone.rs
tests/ui/map_clone.stderr

changelog: map_clone: avoid suggesting `copied()` for &mut 
Fixes #5524

map_clone: avoid suggesting `copied()` for &mut

---

clippy_lints/src/loops.rs
tests/ui/while_let_on_iterator.fixed
tests/ui/while_let_on_iterator.rs
tests/ui/while_let_on_iterator.stderr

r? @phansch 
Fixes #1654
changelog: Fix false positive in [`while_let_on_iterator`]

 Don't trigger while_let_on_iterator when the iterator is recreated every iteration

---

util/dev

`cargo dev` has been the replacement for a while, so I think we can
remove it now.
cc #5394

Remove util/dev script

---

clippy_lints/src/misc.rs
tests/ui/used_underscore_binding.rs
tests/ui/used_underscore_binding.stderr

changelog: used_underscore_binding: do not lint on `await` desugaring
Fixes #5360

used_underscore_binding: do not lint on `await` desugaring

---

clippy_lints/src/escape.rs
clippy_lints/src/functions.rs
clippy_lints/src/loops.rs
clippy_lints/src/needless_pass_by_value.rs
clippy_lints/src/utils/mod.rs
clippy_lints/src/utils/usage.rs
clippy_lints/src/wildcard_imports.rs

cc https://github.com/rust-lang/rust/issues/71608
---

rustup https://github.com/rust-lang/rust/pull/71292/

---

clippy_lints/src/methods/mod.rs
tests/ui/unnecessary_clone.rs
tests/ui/unnecessary_clone.stderr

- Added `<_>` to suggestion
- Changed help message
- Added new tests
Closes #5494 
changelog: Improve suggestion of [`clone_double_ref`]

Fixed incorrect suggestion of `clone_double_ref` lint

---

clippy_lints/src/attrs.rs

mismatched_target_os: link to respective section in rust reference

---

clippy_lints/src/loops.rs
tests/ui/manual_memcpy.rs
tests/ui/manual_memcpy.stderr

While I’m working on the long procrastinated work to expand `manual_memcpy`(#1670), I found a few minor bugs and probably unidiomatic or old coding style. There is a brief explanation of changes to the behaviour this PR will make below. And, I have a questoin: do I need to add tests for the first and second fixed bugs? I thought it might be too rare cases to include the tests for those. I added for the last one though.
* Bug fix
* It negates resulted offsets (`src/dst_offset`) when `offset` is subtraction by 0. This PR will remove any subtraction by 0 as a part of minification.
```rust
for i in 0..5 {
dst[i - 0] = src[i];
}
```
```diff
warning: it looks like you're manually copying between slices
--> src/main.rs:2:14
|
LL  |     for i in 0..5 {
-   |              ^^^^ help: try replacing …
```

Fix the bugs of `manual_memcpy`, simplify the suggestion and refactor it

---

CHANGELOG.md
clippy_lints/src/lib.rs
clippy_lints/src/manual_non_exhaustive.rs
src/lintlist/mod.rs
tests/ui/manual_non_exhaustive.rs
tests/ui/manual_non_exhaustive.stderr

Some implementation notes:
* Not providing automatic fixups because additional changes may be needed in other parts of the code, e.g. when constructing a struct.
* Even though the attribute is valid on enum variants, it's not possible to use the manual implementation of the pattern because the visibility is always public, so the lint ignores enum variants.
* Unit structs are also ignored, it's not possible to implement the pattern manually without fields.
* The attribute is not accepted in unions, so those are ignored too.
* Even though the original issue did not mention it, tuple structs are also linted because it's possible to apply the pattern manually.
changelog: Added the manual non-exhaustive implementation lint
Closes #2017

Implement the manual_non_exhaustive lint

---

clippy_lints/src/utils/mod.rs
tests/ui/while_let_on_iterator.fixed
tests/ui/while_let_on_iterator.rs
tests/ui/while_let_on_iterator.stderr

- fix `is_refutable` for slice patterns
- fix `is_refutable` for bindings
- add some TODO-s for cases, which can not be fixed easily
fixes #3780
changelog: fix FP on while-let-on-iterator for arrays and bindings

Fix FP on while-let-on-iterator

---

clippy_lints/src/unwrap.rs
tests/ui/checked_unwrap/simple_conditionals.rs
tests/ui/checked_unwrap/simple_conditionals.stderr

Fixes a false positive in `unnecessary_unwrap` lint when checks are done in macro parameters.
FIxes #5174 
changelog: Fixes a false positive in `unnecessary_unwrap` lint when checks are done in macro parameters.

Fix `unnecessary_unwrap` lint when checks are done in parameters

---

clippy_lints/src/redundant_clone.rs
tests/ui/builtin-type-shadow.stderr

So, turns out `git subtree push` dies in various interesting ways, but the source cause is that the rustc repo looks like
```
--- A --- B --- C ---
\--- D ---/
```
where `B` is the commit where I added clippy to rustc and `D` is an arbitrary other PR and `C` is the master branch (or an earlier commit in it). When we now do `git subtree push`, it doesn't stop looking for things to merge at `B` as it needs to look at `D`, too, but then the bad thing happens, and it doesn't stop at `A` either, and just goes on looking at the entire history of rustc in a recursive bash script. That recursion then quickly runs into a stack overflow. While we can increase the stack size via `ulimit -s 60000`, that just means I was waiting for 30 minutes looking at `git subtree push` counting up …

Update to rustc changes

---

clippy_lints/src/misc_early.rs

Current example is incorrect (or pseudo-code) because a struct name is omitted. I have used the code from the tests instead. Perhaps this example can be made less verbose, but I think it is more convenient to see a "real" code as an example.
---
changelog: extend example for the `unneeded_field_pattern` lint

Extend example for the `unneeded_field_pattern` lint

---

clippy_lints/src/utils/mod.rs

This should hopefully fix https://github.com/rust-lang/rust/pull/72054#issuecomment-626418591-- I have not yet had a chance to run tests locally though (I believe this should fix the remaining problem though).
I guess in the future we'll fix this upstream but this beta cycle we can't do that unfortunately :/

Add hint for collect type

---

clippy_lints/src/unwrap.rs
tests/ui/checked_unwrap/simple_conditionals.rs
tests/ui/crashes/ice-5579.rs

changelog: Fix ICE in unwrap module with unexpected number of parameters for method of Option/Result
Fixes #5579

Fix ICE caused in unwrap module

---

clippy_lints/src/returns.rs
tests/ui/unused_unit.fixed
tests/ui/unused_unit.rs
tests/ui/unused_unit.stderr

changelog: unused_unit now also lints in type parameters and where clauses
Fixes #5585

unused_unit: lint also in type parameters and where clauses

---

clippy_lints/src/identity_op.rs
tests/ui/identity_op.rs
tests/ui/identity_op.stderr

I went for accepting `1 << 0` verbatim instead of something more general as it seems to be what everyone in the issue thread needed.
changelog: identity_op: allow `1 << 0` as it's a common pattern in bit manipulation code.
Fixes #3430

identity_op: allow `1 << 0`

---

clippy_lints/src/comparison_chain.rs
tests/ui/comparison_chain.rs

changelog: comparison_chain: fix false positives when the binary operation is the same.
Fixes #5212

Fix comparison_chain false positive

---

CHANGELOG.md
clippy_lints/src/eq_op.rs
clippy_lints/src/lib.rs
clippy_lints/src/loops.rs
clippy_lints/src/matches.rs
clippy_lints/src/methods/bind_instead_of_map.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/needless_pass_by_value.rs
clippy_lints/src/types.rs
clippy_lints/src/utils/diagnostics.rs
src/lintlist/mod.rs
tests/ui/bind_instead_of_map.fixed
tests/ui/bind_instead_of_map.rs
tests/ui/bind_instead_of_map.stderr
tests/ui/bind_instead_of_map_multipart.rs
tests/ui/bind_instead_of_map_multipart.stderr
tests/ui/blocks_in_if_conditions.fixed
tests/ui/blocks_in_if_conditions.rs
tests/ui/option_map_or_none.fixed
tests/ui/option_map_or_none.rs

fixed #5492 
changelog: Improve and generalize `option_and_then_some` and rename it to `bind_instead_of_map`.

Improve `option_and_then_some` lint

---

CHANGELOG.md
clippy_lints/src/lib.rs
clippy_lints/src/useless_conversion.rs
src/lintlist/mod.rs
tests/ui/useless_conversion.fixed
tests/ui/useless_conversion.rs
tests/ui/useless_conversion.stderr

Lint name `identity_conversion` was misleading, so this PR renames it to `useless_conversion`.
As decision has not really came up in the issue comments, this PR will probably need discussion.
fixes #3106
changelog: Rename lint `identity_conversion` to `useless_conversion`

Rename lint `identity_conversion` to `useless_conversion`

---

clippy_dev/src/new_lint.rs
clippy_lints/src/cargo_common_metadata.rs
clippy_lints/src/multiple_crate_versions.rs
doc/adding_lints.md
tests/compile-test.rs
tests/ui-cargo/cargo_common_metadata/fail/Cargo.toml
tests/ui-cargo/cargo_common_metadata/fail/src/main.rs
tests/ui-cargo/cargo_common_metadata/fail/src/main.stderr
tests/ui-cargo/cargo_common_metadata/pass/Cargo.toml
tests/ui-cargo/cargo_common_metadata/pass/src/main.rs
tests/ui-cargo/multiple_crate_versions/fail/Cargo.toml
tests/ui-cargo/multiple_crate_versions/fail/src/main.rs
tests/ui-cargo/multiple_crate_versions/fail/src/main.stderr
tests/ui-cargo/multiple_crate_versions/pass/Cargo.toml
tests/ui-cargo/multiple_crate_versions/pass/src/main.rs
tests/ui-cargo/update-all-references.sh
tests/ui-cargo/update-references.sh
tests/ui-cargo/wildcard_dependencies/fail/Cargo.toml
tests/ui-cargo/wildcard_dependencies/fail/src/main.rs
tests/ui-cargo/wildcard_dependencies/fail/src/main.stderr
tests/ui-cargo/wildcard_dependencies/pass/Cargo.toml
tests/ui-cargo/wildcard_dependencies/pass/src/main.rs

changelog: Add infrastructure to test cargo lints
Closes #5603

Test cargo lints

---

clippy_lints/src/mut_reference.rs

fixes #5433 by replacing "giving" with "passing"
changelog: Clarifies documentation for `unnecessary_mut_passed`

Clarify the documentation of the `unnecessary_mut_passed` lint

---

clippy_lints/src/new_without_default.rs
tests/ui/new_without_default.rs
tests/ui/new_without_default.stderr

---
changelog: do not suggest deriving `Default` in `new_without_default`
This commit changes the behavior of the `new_without_default` lint to not suggest deriving `Default`. This suggestion is misleading if the `new` implementation does something different than what a derived `Default` implementation would do, because then the two methods would not be equivalent. 
Instead, the `can_derive_default` check is removed, and we always suggest implementing `Default` in terms of `new()`.

new_without_default: do not suggest deriving

---

tests/ui/option_option.rs
tests/ui/option_option.stderr

Adds regression test case for #4298.
The bug seems still present although rust Playground said otherwise.

option_option test case #4298

---

doc/adding_lints.md
doc/common_tools_writing_lints.md

This PR starts adding some documentation about linting tools.
`Retrieving all methods of a type` is not covered at this time.
fixes partially: #3843

Add common lint tools doc

---

clippy_lints/src/methods/mod.rs
tests/ui/or_fun_call.fixed
tests/ui/or_fun_call.rs

Resolves #1653
changelog: Update `or_fun_call`: Allow calls to `len` for Slice, Array & Vec.

Update 'or_fun_call' to ignore calls to len

---

clippy_lints/src/ptr.rs
clippy_lints/src/utils/sugg.rs
tests/ui/ptr_arg.rs

The `intravisit::Visitor` impl for `LateContextAndPass` only takes into account the attributes of a function parameter inside the `check_param` method. `ptr_arg` starts its heuristics at `check_item` / `check_impl_item` / `check_trait_item`, so the `allow` is not taken into account automatically.
changelog: ptr_arg: honor `allow` attribute on arguments 
Fixes #5644

ptr_arg: honor `allow` attribute on arguments

---

clippy_dev/src/new_lint.rs
clippy_lints/src/multiple_crate_versions.rs
tests/ui-cargo/cargo_common_metadata/fail/src/main.rs
tests/ui-cargo/cargo_common_metadata/pass/src/main.rs
tests/ui-cargo/multiple_crate_versions/5041_allow_dev_build/Cargo.toml
tests/ui-cargo/multiple_crate_versions/5041_allow_dev_build/src/main.rs
tests/ui-cargo/multiple_crate_versions/fail/src/main.rs
tests/ui-cargo/multiple_crate_versions/pass/src/main.rs
tests/ui-cargo/wildcard_dependencies/fail/src/main.rs
tests/ui-cargo/wildcard_dependencies/pass/src/main.rs

changelog: multiple_crate_versions: skip dev and build deps
Closes #5041

multiple_crate_versions: skip dev and build deps

---

CONTRIBUTING.md

[Rendered](https://github.com/flip1995/rust-clippy/blob/clippyup_up/CONTRIBUTING.md#fixing-build-failures-caused-by-rust)
r? @oli-obk Did I get the sync process right?

Update contributing section about syncing Clippy

---

clippy_lints/src/ranges.rs
tests/ui/reversed_empty_ranges_fixable.fixed
tests/ui/reversed_empty_ranges_fixable.rs
tests/ui/reversed_empty_ranges_fixable.stderr
tests/ui/reversed_empty_ranges_unfixable.rs
tests/ui/reversed_empty_ranges_unfixable.stderr

As discussed in the issue thread, the user accepted this solution. Let me know if this is what we want, or if changing the way we lint the N..N case is prefered.
changelog: reversed_empty_ranges: add suggestion for &slice[N..N]
Closes #5628

reversed_empty_ranges: add suggestion for &slice[N..N]

---

clippy_lints/Cargo.toml
clippy_lints/src/attrs.rs
tests/compile-test.rs
tests/ui/auxiliary/proc_macro_attr.rs
tests/ui/empty_line_after_outer_attribute.rs
tests/ui/empty_line_after_outer_attribute.stderr

Fixes #5567
Unfortunately I couldn't find a way to reproduce the issue without syn/quote. Considering that most real-world macros use syn and/or quote, I think it's okay to pull them in anyway.
changelog: Fix false positive in [`empty_line_after_outer_attr`]

Make empty_line_after_outer_attr an early lint

---

rustc_tools_util/LICENSE-APACHE
rustc_tools_util/LICENSE-MIT

To make it easier for Linux distributions to ship the licenses text within the rustc_tools_util crate directory.

Add license symlink

---

.github/workflows/clippy.yml
.github/workflows/clippy_bors.yml

We just released v2. That includes a lot of improvements.
https://github.com/actions/cache/releases/tag/v2.0.0

Bump actions/cache from v1 to v2

---

clippy_lints/src/lib.rs
clippy_lints/src/new_without_default.rs
clippy_lints/src/non_expressive_names.rs
clippy_lints/src/redundant_field_names.rs
src/driver.rs

Similar names was moved to a pre-expansion pass to solve #2927, so I'm avoiding linting on code from expansion, which makes the dogfood (mostly, see below) pass.
I had to change new_without_default though, and although I understand why it was not triggering before, TBH I don't see why the binding inside the nested `if_chain` is being linted now. Any ideas? (it seems legit though as the code can be changed by the user)
changelog: Register redundant_field_names and non_expressive_names as early passes
Fixes #5356
Fixes #5521

Register redundant_field_names and non_expressive_names as early passes

---

tests/ui/cognitive_complexity.rs
tests/ui/cognitive_complexity_attr_used.rs

rustup https://github.com/rust-lang/rust/pull/72342, allow unused_crate_dependencies

---

clippy_lints/src/useless_conversion.rs
clippy_lints/src/utils/paths.rs
src/lintlist/mod.rs
tests/ui/useless_conversion.stderr
tests/ui/useless_conversion_try.rs
tests/ui/useless_conversion_try.stderr

This PR extends `useless_conversion` lint with `TryFrom` and `TryInto`
fixes: #5344 
changelog: Extend `useless_conversion` with `TryFrom` and `TryInto`

Extend useless conversion

---

.github/workflows/clippy_bors.yml

Bors stopped failed if the changelog was missing. Instead it waited 2h (?) and then timed out.

Fail bors on missing changelog

---

clippy_dev/src/lib.rs
clippy_dev/src/main.rs
clippy_dev/src/ra_setup.rs

It takes an absolute path to a rustc repo and adds path-dependencies
that point towards the respective rustc subcrates into the Cargo.tomls of
the clippy and clippy_lints crate.
This allows rustc-analyzer to show proper type annotations etc on rustc-internals inside the clippy repo.
Usage: cargo dev ra-setup /absolute/path/to/rust/
cc https://github.com/rust-analyzer/rust-analyzer/issues/3517
cc https://github.com/rust-lang/rust-clippy/issues/5514

cargo_dev: add ra-setup

---

tests/ui/crashes/ice-3969.rs
tests/ui/crashes/ice-3969.stderr

add testcase that no longer ICEs

---

clippy_lints/src/len_zero.rs
tests/ui/len_zero.fixed
tests/ui/len_zero.rs
tests/ui/len_zero_ranges.fixed
tests/ui/len_zero_ranges.rs
tests/ui/len_zero_ranges.stderr

If the feature is not enabled, calling `is_empty()` on a range is ambiguous. Moreover, the two possible resolutions are unstable methods, one inherent to the range and the other being part of the `ExactSizeIterator` trait.
Since `len_zero` only checks for existing `is_empty()` inherent methods, we only take into account the `range_is_empty` feature.
Related: https://github.com/rust-lang/rust/issues/48111#issuecomment-445132965
changelog: len_zero: avoid linting ranges without #![feature(range_is_empty)]
Fixes: #3807

len_zero: skip ranges if feature `range_is_empty` is not enabled

---

CHANGELOG.md
clippy_lints/src/lib.rs
clippy_lints/src/utils/paths.rs
clippy_lints/src/vec_resize_to_zero.rs
src/lintlist/mod.rs
tests/ui/vec_resize_to_zero.rs
tests/ui/vec_resize_to_zero.stderr

implements #5444
changelog: new lint vec_resize_to_zero

new lint: vec_resize_to_zero

---

Cargo.toml
clippy_lints/Cargo.toml

`clippy_lints` makes use of `dep_kinds` on `NodeDep` but this was only
added in versoin 0.9.1. Compiling with 0.9.0 will fail because of this.

Increase cargo_metadata version to 0.9.1

---

tests/compile-test.rs

I forgot that I had fixed this in a PR I closed some days ago (#5643).
Before this change, cargo UI tests could fail when switching between branches if the previous branch had a test that the current branch does not have. The directory is not removed when switching because an ignored `Cargo.lock` file exists, and the code was trying to reach `$DIR/src` unconditionally.
This change will just skip a directory that has no `src` subdirectory. 

cargo-ui tests: check that <dir>/src exists before processing test

---

CONTRIBUTING.md

Fixes #5514
Technically this should be merged after https://github.com/rust-lang/rust-clippy/pull/5655 but it's not very important.
---

CONTRIBUTING: explain how to use cargo dev ra-setup

---

clippy_lints/Cargo.toml
tests/ui/crashes/regressions.rs

Closes #4917
This was fixed in pulldown_cmark 0.7.1, specifically raphlinus/pulldown-cmark#438

Add regression test for endless loop / update `pulldown_cmark`

---

tests/ui/string_lit_as_bytes.fixed
tests/ui/string_lit_as_bytes.rs
tests/ui/string_lit_as_bytes.stderr

Closes #5619
Before the fix in https://github.com/rust-lang/rust/pull/72637, `string_lit_as_bytes` was incorrectly triggering on the `env!` macro. With the fix merged, this test makes sure that the lint is not triggering anymore.

Add regression test for `string_lit_as_bytes` issue

---

clippy_lints/src/checked_conversions.rs
tests/ui/checked_conversions.fixed
tests/ui/checked_conversions.rs
tests/ui/checked_conversions.stderr

 Fix false negative of `checked_conversion` lint 

---

clippy_lints/src/matches.rs

See https://rust-lang.github.io/rust-clippy/master/index.html#match_wildcard_for_single_variants

match_wildcard_for_single_variants: remove empty line at start of lint example.

---

CHANGELOG.md
doc/changelog_update.md

[Rendered](https://github.com/ebroto/rust-clippy/blob/changelog_144_145/CHANGELOG.md)

Update changelog for stable:1.44 beta:1.45

---

doc/changelog_update.md
doc/release.md

r? @phansch 
I should have included this in #5686, but forgot about it, so here we go again.

Replace all remaining occurrences of submodule with subtree

---

clippy_dev/src/new_lint.rs
clippy_lints/src/cargo_common_metadata.rs
clippy_lints/src/multiple_crate_versions.rs
clippy_lints/src/utils/mod.rs
clippy_lints/src/wildcard_dependencies.rs
tests/compile-test.rs
tests/ui-cargo/cargo_common_metadata/fail/Cargo.toml
tests/ui-cargo/cargo_common_metadata/pass/Cargo.toml
tests/ui-cargo/multiple_crate_versions/5041_allow_dev_build/Cargo.toml
tests/ui-cargo/multiple_crate_versions/fail/Cargo.toml
tests/ui-cargo/multiple_crate_versions/pass/Cargo.toml
tests/ui-cargo/wildcard_dependencies/fail/Cargo.toml
tests/ui-cargo/wildcard_dependencies/pass/Cargo.toml

It seems we hit https://github.com/rust-lang/cargo/issues/5418, so I've applied the suggested solution. Also added some more info when cargo-metadata fails to execute.
(there was no open issue for this)

Fix cargo tests when running inside the rustlang/rust repo

---

clippy_lints/src/copies.rs
clippy_lints/src/loops.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/new_without_default.rs
clippy_lints/src/types.rs
clippy_lints/src/useless_conversion.rs
clippy_lints/src/utils/mod.rs

This delegates our `same_tys` to [ty::TyS::same_type][same_type] to
remove some duplication.
Our `same_tys` was introduced 4 years ago in #730. Before, it was
building an inference context to be able to call
`can_eq` to compare the types. The `rustc-dev-guide` has some more details
about `can_eq` in [Type Inference -> Trying equality][try_eq].
Now, using the rustc function, we are essentially comparing the `DefId`s
of the given types, which also makes more sense, IMO.
I also confirmed that the FIXME is resolved via a bit of `dbg!`, however
no UI tests seem to have been affected.
[same_type]: https://github.com/rust-lang/rust/blob/659951c4a0d7450e43f61c61c0e87d0ceae17087/src/librustc_middle/ty/util.rs#L777
[try_eq]: https://rustc-dev-guide.rust-lang.org/type-inference.html#trying-equality …

Cleanup: Use rustc's `same_type` for our `same_tys`

---

doc/common_tools_writing_lints.md

This PR adds documentation on how:
- check if a type defines a specific method
- check an expr is calling a specific method
closes: #3843 

Add doc for checking if type defines specific method

---

clippy_lints/src/ranges.rs
tests/ui/reversed_empty_ranges_fixable.fixed
tests/ui/reversed_empty_ranges_fixable.rs
tests/ui/reversed_empty_ranges_fixable.stderr
tests/ui/reversed_empty_ranges_unfixable.rs
tests/ui/reversed_empty_ranges_unfixable.stderr

changelog: [`reversed_empty_ranges`]: avoid linting N..N except in for loop arguments
r? @yaahc 
Fixes #5689

reversed_empty_ranges: avoid linting N..N except in for loop arguments

---

clippy_lints/src/utils/hir_utils.rs
tests/ui/if_same_then_else.rs

changelog: Don't assume multiplication is always commutative in [`if_same_then_else`]
Fixes #5698

if_same_then_else: don't assume multiplication is always commutative

---

clippy_lints/src/mem_replace.rs
tests/ui/repl_uninit.rs
tests/ui/repl_uninit.stderr

resolves: #5575 
changelog: improvements to `MEM_REPLACE_WITH_UNINIT`:
- add a new test case in `tests/ui/repl_uninit.rs` to cover the case of replacing with `mem::MaybeUninit::uninit().assume_init()`.
- modify the existing `MEM_REPLACE_WITH_UNINIT` when replacing with `mem::uninitialized` to suggest using `ptr::read` instead.
- lint with `MEM_REPLACE_WITH_UNINIT` when replacing with `mem::MaybeUninit::uninit().assume_init()`

New lint: suggest `ptr::read` instead of `mem::replace(..., uninitialized())`

---

clippy_lints/src/redundant_pattern_matching.rs
tests/ui/redundant_pattern_matching.fixed
tests/ui/redundant_pattern_matching.rs
tests/ui/redundant_pattern_matching.stderr
tests/ui/redundant_pattern_matching_const_result.fixed
tests/ui/redundant_pattern_matching_const_result.rs
tests/ui/redundant_pattern_matching_const_result.stderr

changelog: Avoid suggesting non-`const fn` calls in const contexts in [`redundant_pattern_matching`]
Fixes #5697

redundant_pattern_matching: avoid non-`const fn` calls in const contexts

---

clippy_lints/src/wildcard_imports.rs

Fix typo in wildcard_imports

---

clippy_lints/src/lib.rs
clippy_lints/src/loops.rs
clippy_lints/src/suspicious_trait_impl.rs
clippy_lints/src/trivially_copy_pass_by_ref.rs
clippy_lints/src/utils/sugg.rs
src/driver.rs
src/main.rs

cc https://github.com/rust-lang/rust/pull/73297#discussion_r439747061

Use lints in Clippy that are enabled in rustc bootstrap

---

clippy_lints/src/utils/conf.rs
tests/ui/blacklisted_name.rs
tests/ui/blacklisted_name.stderr

changelog: Remove `bar` from blacklisted names
fixes #5225

Remove `bar` from blacklisted names

---

clippy_lints/src/consts.rs
tests/ui/crashes/ice-5389.rs

changelog: Fix ICE in `consts::binop`
Fixes #5389

Fix ICE in consts::binop

---

.github/driver.sh
src/driver.rs

changelog: clippy-driver: pass all args to rustc if --rustc is present

clippy-driver: pass all args to rustc if --rustc is present

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/blank_issue.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/ice.md
.github/ISSUE_TEMPLATE/new_lint.md
.github/PULL_REQUEST_TEMPLATE.md

changelog: Make it easier to create feature request and bug reports with issue templates.

Add more specific GitHub issue templates

---

clippy_lints/src/lib.rs
src/driver.rs

Remove unused allowed unused attributes

---

CHANGELOG.md
clippy_lints/src/lib.rs
clippy_lints/src/map_identity.rs
src/lintlist/mod.rs
tests/ui/map_flatten.fixed
tests/ui/map_flatten.rs
tests/ui/map_flatten.stderr
tests/ui/map_identity.fixed
tests/ui/map_identity.rs
tests/ui/map_identity.stderr

changelog: adds a new lint for iterator.map(|x| x) (see https://github.com/rust-lang/rust-clippy/issues/5626)
The code also lints for result.map(|x| x) and option.map(|x| x). Also, I'm not sure if I'm checking for type adjustments correctly and I can't think of an example where .map(|x| x) would apply type adjustments.

#5626: lint iterator.map(|x| x)

---

clippy_lints/src/methods/mod.rs
tests/ui/clone_on_copy.fixed
tests/ui/clone_on_copy.rs
tests/ui/clone_on_copy.stderr
tests/ui/unnecessary_clone.rs
tests/ui/unnecessary_clone.stderr

Fix #4826. 
Change the applicability of the lint clone_on_copy. Split a test file and run rustfix on the clone_on_copy part. 
changelog: clone_on_copy - add machine applicability

clone_on_copy - add machine applicability

---

clippy_lints/src/await_holding_lock.rs

changelog: Fixed some grammar in the documentation for `await_holding_lock`.
Just a tiny little thing I found while using clippy <3

Change a noun to a verb to make the sentence complete

---

CHANGELOG.md
clippy_lints/src/attrs.rs
clippy_lints/src/lib.rs
src/lintlist/mod.rs
tests/ui/attrs.rs
tests/ui/attrs.stderr

I've added it to the `correctness` category, but I may be missing some valid use cases. In that case it could be changed to `pedantic`.
changelog: Add [`blanket_clippy_restriction_lints`] to check against enabling the whole restriction group.

Lint enabling the whole restriction group

---

clippy_lints/src/unnested_or_patterns.rs
tests/ui/unnested_or_patterns3.rs

changelog: Require `#![feature(or_patterns)]` to trigger [`unnested_or_patterns`]
Fixes #5704

Require `or_patterns` to suggest nesting them

---

clippy_lints/src/deprecated_lints.rs
clippy_lints/src/lib.rs
clippy_lints/src/regex.rs
clippy_lints/src/utils/paths.rs
src/lintlist/mod.rs
tests/ui/deprecated.rs
tests/ui/deprecated.stderr
tests/ui/regex.rs

Closes #2586 
changelog: Deprecate regex_macro lint

Deprecate regex_macro lint

---

CHANGELOG.md
clippy_lints/src/lib.rs
clippy_lints/src/pattern_type_mismatch.rs
src/lintlist/mod.rs
tests/ui/pattern_type_mismatch/mutability.rs
tests/ui/pattern_type_mismatch/mutability.stderr
tests/ui/pattern_type_mismatch/pattern_alternatives.rs
tests/ui/pattern_type_mismatch/pattern_alternatives.stderr
tests/ui/pattern_type_mismatch/pattern_structs.rs
tests/ui/pattern_type_mismatch/pattern_structs.stderr
tests/ui/pattern_type_mismatch/pattern_tuples.rs
tests/ui/pattern_type_mismatch/pattern_tuples.stderr
tests/ui/pattern_type_mismatch/syntax.rs
tests/ui/pattern_type_mismatch/syntax.stderr

changelog: Added a new restriction lint `pattern-type-mismatch`. This lint is especially helpful for beginners learning about the magic behind pattern matching. (This explanation might be worth to include in the next changelog.)

Added restriction lint: pattern-type-mismatch

---

clippy_lints/src/matches.rs
tests/ui/single_match_else.rs
tests/ui/single_match_else.stderr

One approach to fix #3489. 
See discussion in the issue.
changelog: single_match_else - single expr/stmt else block corner case fix

single_match_else - single expr/stmt else block corner case

---

CONTRIBUTING.md

Fix a broken link in CONTRIBUTING.md

---

.github/ISSUE_TEMPLATE/new_lint.md

fix phrase in new_lint issue template

---

clippy_lints/src/unnested_or_patterns.rs

Fixes #5780
changelog: fix out of bounds access in unnested_or_patterns lint.
Edit: I did not bother reducing a testcase from `librustc_typeck` crate but I can confirm that with the change the crash no longer occurs.

Fix out of bounds access by checking length equality BEFORE accessing by index.

---

clippy_lints/src/let_and_return.rs
clippy_lints/src/unnecessary_sort_by.rs
clippy_lints/src/utils/mod.rs
tests/ui/unnecessary_sort_by.fixed
tests/ui/unnecessary_sort_by.rs

changelog: Avoid linting if key borrows in [`unnecessary_sort_by`]
Fixes #5754 
Closes #2313

unnecessary_sort_by: avoid linting if key borrows

---

clippy_lints/src/floating_point_arithmetic.rs
tests/ui/floating_point_hypot.fixed
tests/ui/floating_point_hypot.rs
tests/ui/floating_point_hypot.stderr
tests/ui/floating_point_log.fixed
tests/ui/floating_point_log.rs
tests/ui/floating_point_log.stderr
tests/ui/floating_point_logbase.fixed
tests/ui/floating_point_logbase.rs
tests/ui/floating_point_logbase.stderr
tests/ui/floating_point_mul_add.fixed
tests/ui/floating_point_mul_add.rs
tests/ui/floating_point_mul_add.stderr
tests/ui/floating_point_powf.fixed
tests/ui/floating_point_powf.rs
tests/ui/floating_point_powf.stderr
tests/ui/floating_point_powi.fixed
tests/ui/floating_point_powi.rs
tests/ui/floating_point_powi.stderr
tests/ui/floating_point_rad.fixed
tests/ui/floating_point_rad.rs
tests/ui/floating_point_rad.stderr

This will add some lints for accuracy on floating point operations suggested by @clarfon in #2040 (fixes #2040).
These are the remaining lints:
changelog: Included some accuracy lints for floating point operations

Some accuracy lints for floating point operations

---

CHANGELOG.md
clippy_lints/src/lib.rs
clippy_lints/src/repeat_once.rs
src/lintlist/mod.rs
tests/ui/repeat_once.fixed
tests/ui/repeat_once.rs
tests/ui/repeat_once.stderr

changelog: New lint `repeat_once`
fix #3028.

Add a lint for `.repeat(1)`

---

clippy_lints/src/collapsible_if.rs
tests/ui/collapsible_else_if.stderr
tests/ui/collapsible_if.stderr

The name "try" is confusing when shown as quick fix by rust-analyzer
changelog: Rename `collapsable_if` fix suggestion to "collapse nested if block"

Rename collapsable_if fix suggestion to "collapse nested if block"

---

CHANGELOG.md
clippy_lints/src/lib.rs
clippy_lints/src/unit_return_expecting_ord.rs
src/lintlist/mod.rs
tests/ui/unit_return_expecting_ord.rs
tests/ui/unit_return_expecting_ord.stderr

This lint catches cases where the last statement of a closure expecting
an instance of Ord has a trailing semi-colon. It compiles since the
closure ends up return () which also implements Ord but causes
unexpected results in cases such as sort_by_key.
Fixes #5080
Reprise of #5348 where I addressed all the comments there
changelog: add lint [`unit_return_expecting_ord`]

Reprise: new lint: Unintentional return of unit from closures expecting Ord

---

clippy_lints/src/methods/mod.rs
tests/ui/iter_nth_zero.stderr

fixes #5783
changelog:  For iter_nth_zero, the "use .next()" replacement advice is on the last line of the code snippet, where it is vulnerable to truncation. Display that advice at the beginning instead.

improve advice in iter_nth_zero

---

tests/ui/needless_range_loop2.rs

Closes #2277
This was fixed when we fixed #2542.

Add test for `needless_range_loop` issue

---

clippy_lints/src/shadow.rs
tests/ui/shadow.stderr

Fixes #5703
I am not sure if I reinvented the wheel here, but I could not really find a snippet function that did this truncation, so I created the function. Please tell me if there was a more obvious way to do this, I am new here. :smile:
changelog: Truncates multi-line RHS in shadow_unrelated message if it has more than 5 lines.

Removing RHS snippet from SHADOW_UNRELATED message.

---

.github/deploy.sh

Since the `beta/` directory already exists, we can't copy the complete `master` dir

Fix deploy script for beta deployment

---

clippy_lints/src/panic_unimplemented.rs
tests/ui/panicking_macros.rs
tests/ui/panicking_macros.stderr

changelog: Fixes bug with `panic` lint reported in #5767. I also did the same changes to the lints for `todo`, `unimplemented` and `unreachable`, so those lints should now also detect calls to those macros with a message.

Panic multiple args

---

clippy_lints/src/matches.rs
tests/ui/redundant_pattern_matching.fixed
tests/ui/redundant_pattern_matching.rs
tests/ui/redundant_pattern_matching.stderr

changelog: Fixes the bug reported #5766

Redundant pattern bugfix

---

clippy_lints/src/redundant_clone.rs
clippy_lints/src/utils/paths.rs
tests/ui/redundant_clone.fixed
tests/ui/redundant_clone.rs
tests/ui/redundant_clone.stderr

"Redundant" clones of `ManuallyDrop` are sometimes used for the side effect of
invoking the clone, without running the drop implementation of the inner type.
In other words, they aren't really redundant. For example, futures-rs crate:
```rust
#[allow(clippy::redundant_clone)] // The clone here isn't actually redundant.
unsafe fn increase_refcount<T: ArcWake>(data: *const ()) {
// Retain Arc, but don't touch refcount by wrapping in ManuallyDrop
let arc = mem::ManuallyDrop::new(Arc::<T>::from_raw(data as *const T));
// Now increase refcount, but don't drop new refcount either
let _arc_clone: mem::ManuallyDrop<_> = arc.clone();
}
```
changelog: Ignore redundant clone lint for ManuallyDrop.

Ignore not really redundant clones of ManuallyDrop

---

README.md

Update Usage section of README.md

---

clippy_lints/src/misc.rs

`float_cmp(_const)` suggests using `{f32|f64}::EPSILON` and it'd be great if the docs mentioned it.

Use `(std::)f64::EPSILON` in the examples as suggested in the lints

---

clippy_lints/src/methods/mod.rs
tests/ui/iter_skip_next.fixed
tests/ui/iter_skip_next.stderr

changelog: Add suggestion for [`iter_skip_next`](https://rust-lang.github.io/rust-clippy/master/index.html#iter_skip_next) lint

Add suggestion for `iter_skip_next` lint

---

tests/compile-test.rs

r? @ebroto 
The `ui-toml` tests set the `CARGO_MANIFEST_DIR` var, but never reset it, so the `ui-cargo` tests used it also and then found a faulty `clippy.toml` file

Fix ui-cargo tests in CI

---

clippy_lints/src/attrs.rs
clippy_lints/src/lib.rs
clippy_lints/src/lifetimes.rs
clippy_lints/src/loops.rs
clippy_lints/src/shadow.rs
clippy_lints/src/utils/mod.rs

I couldn't really tell what it was meant to improve. It seems more clear
without the renaming to `Name`?

Remove old Symbol reexport

---

clippy_lints/src/methods/mod.rs
tests/ui/map_flatten.fixed
tests/ui/map_flatten.rs
tests/ui/map_flatten.stderr

Fixes #4496
The existing [`map_flatten`](https://rust-lang.github.io/rust-clippy/master/index.html#map_flatten) lint suggests changing `expr.map(...).flatten()` to `expr.flat_map(...)` when `expr` is `Iterator`. This PR changes suggestion to `filter_map` instead of `flat_map` when mapping to `Option`, because it is more natural
Also here are some questions:
* If expression has type which implements `Iterator` trait (`match_trait_method(cx, expr, &paths::ITERATOR) == true`), how can I get type of iterator elements? Currently I use return type of closure inside `map`, but probably it is not good way
* I would like to change suggestion range to cover only `.map(...).flatten()`, that is from:
```
let _: Vec<_> = vec![5_i8; 6].into_iter().map(|x| 0..x).flatten().collect(); …
```

Handle mapping to Option in `map_flatten` lint

---

clippy_lints/src/manual_async_fn.rs
tests/ui/await_holding_lock.rs
tests/ui/await_holding_lock.stderr
tests/ui/manual_async_fn.fixed
tests/ui/manual_async_fn.rs
tests/ui/manual_async_fn.stderr

The anonymous future returned from an `async fn` captures all input
lifetimes. This was not being taken into account.
See https://github.com/rust-lang/rfcs/blob/master/text/2394-async_await.md#lifetime-capture-in-the-anonymous-future
changelog: Take input lifetimes into account in [`manual_async_fn`].
Fixes #5765

manual_async_fn: take input lifetimes into account

---

CHANGELOG.md
clippy_lints/src/lib.rs
clippy_lints/src/stable_sort_primitive.rs
clippy_lints/src/utils/mod.rs
src/lintlist/mod.rs
tests/ui/stable_sort_primitive.fixed
tests/ui/stable_sort_primitive.rs
tests/ui/stable_sort_primitive.stderr
tests/ui/unnecessary_sort_by.fixed
tests/ui/unnecessary_sort_by.rs
tests/ui/unnecessary_sort_by.stderr

Stable sort primitive

---

clippy_lints/src/loops.rs
tests/ui/crashes/ice-5872.rs
tests/ui/crashes/ice-5872.stderr
tests/ui/needless_collect.fixed
tests/ui/needless_collect.rs
tests/ui/needless_collect.stderr

changelog: Fix ICE related to `needless_collect` when a call to `iter()` was not present.
I went for restoring the old suggestion of `next().is_some()` over `get(0).is_some()` given that `iter()` is not necessarily present (could be e.g. `into_iter()` or `iter_mut()`)  and that the old suggestion could change semantics, e.g. a call to `filter()` could be present between `iter()` and the collect part.
Fixes #5872

Fix ICE in `loops` module

---

clippy_dev/src/ra_setup.rs

Currently after running `cargo dev ra-setup` the following lines are added to `Cargo.toml`:
```toml
[target]
rustc_data_structures = { path = ".../rust/src/librustc_data_structures" }
rustc_driver = { path = ".../rust/src/librustc_driver" }
rustc_errors = { path = ".../rust/src/librustc_errors" }
rustc_interface = { path = ".../rust/src/librustc_interface" }
rustc_middle = { path = ".../rust/src/librustc_middle" }
```
This pull request adds dependencies for `rustc` crates under `cfg(NOT_A_PLATFORM)`, thus preventing them from compiling together with clippy:
```toml
[target.'cfg(NOT_A_PLATFORM)'.dependencies]
rustc_data_structures = { path = ".../rust/src/librustc_data_structures" }
rustc_driver = { path = ".../rust/src/librustc_driver" }
rustc_errors = { path = …
```

Prevent compile parts of rustc when using `cargo dev ra-setup`

---

CONTRIBUTING.md
doc/basics.md

It confused me before, so I made it extra obvious that you need to run
a script to set up your toolchain before you can build Clippy.
I also added a note so that new contributors aren't confused when
Clippy doesn't build as a result of a change in rustc's internals.
changelog: make `CONTRIBUTING.md` clearer for new contributors

Make the docs clearer for new contributors

---

clippy_lints/src/minmax.rs
tests/ui/min_max.rs
tests/ui/min_max.stderr

Fixes  #5854
changelog: Also lint `ord.min(a).max(b)`, where `a < b` in [`min_max`] lint

Lint .min(x).max(y) with x < y

---

clippy_lints/src/derive.rs
tests/ui/unsafe_derive_deserialize.rs

Before this change this lint could not be allowed as the code we are checking is automatically generated.
changelog: Enable using the `allow` attribute on top of an ADT linted by [`unsafe_derive_deserialize`].
Fixes: #5789

enable #[allow(clippy::unsafe_derive_deserialize)]

---

CHANGELOG.md

Two most recent links linked to the wrong range

Fix CHANGELOG's commit range links

---

clippy_lints/src/utils/mod.rs
tests/ui/or_fun_call.fixed
tests/ui/or_fun_call.rs

Based on #5682 by @lzutao 
This avoids a subset of false positives, specifically those related to `const fn`s that take no arguments. 
For the rest, a much more involved fix would be needed, see https://github.com/rust-lang/rust-clippy/pull/5682#issuecomment-638681210. 
So this does *not* solve #5658 
changelog: Avoid triggering [`or_fun_call`] with `const fn`s that take no arguments. 
Fixes #5886

Avoid or_fun_call for const_fn with no args

---

clippy_lints/src/mut_reference.rs
tests/ui/mut_reference.stderr

changelog: refine "unnecessary-mut-passed" lint message

unnecessary-mut-passed: make lint message say if fn is a function or a method

---

clippy_lints/src/ptr.rs

Addresses #214
changelog: Add example of false positive to `ptr_arg` docs.

Add example of false positive to PTR_ARG docs.

---

clippy_lints/src/duration_subsec.rs
clippy_lints/src/enum_clike.rs
clippy_lints/src/enum_variants.rs
clippy_lints/src/if_let_some_result.rs
clippy_lints/src/if_not_else.rs
clippy_lints/src/implicit_saturating_sub.rs
clippy_lints/src/inherent_impl.rs
clippy_lints/src/int_plus_one.rs
clippy_lints/src/map_clone.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/mutex_atomic.rs
clippy_lints/src/stable_sort_primitive.rs
clippy_lints/src/use_self.rs
src/lintlist/mod.rs
tests/ui/duration_subsec.stderr
tests/ui/enum_clike_unportable_variant.stderr
tests/ui/enum_variants.stderr
tests/ui/if_let_some_result.stderr
tests/ui/if_not_else.stderr
tests/ui/impl.stderr
tests/ui/implicit_saturating_sub.stderr
tests/ui/int_plus_one.stderr
tests/ui/iter_next_slice.stderr
tests/ui/map_clone.stderr
tests/ui/mutex_atomic.stderr
tests/ui/stable_sort_primitive.stderr

r? @yaahc 
changelog:  make remaining lint messages adhere to rustc dev guide lint message convention.

fix remaining lint messages

---

clippy_lints/src/suspicious_trait_impl.rs
tests/ui/suspicious_arithmetic_impl.rs
tests/ui/suspicious_arithmetic_impl.stderr

In #2268 I idly mused that the other user-overloadable operations could be added to this lint. Knowing that the lint was arguably incomplete was gnawing at the back of my mind, so I figured that I might as well make this PR, particularly given the change needed was so small.
changelog: Start warning on suspicious implementations of the `BitAnd`, `BitOr`, `BitXor`, `Rem`, `Shl`, and `Shr` traits.

Add the other overloadable operations to suspicious_arithmetic_impl

---

clippy_lints/src/write.rs

write.rs: don't clone TokenStream

---

clippy_lints/src/useless_conversion.rs
tests/ui/useless_conversion.fixed
tests/ui/useless_conversion.rs
tests/ui/useless_conversion.stderr

Note: this lint was previously named `identity_conversion`.
fixes: #4750
changelog: fix parenthesis for `useless_conversion` lint suggestion

Fix: keep parenthesis for suggestion in `useless_conversion` lint

---

clippy_lints/src/types.rs
tests/ui/redundant_allocation.fixed
tests/ui/redundant_allocation.stderr

Fixes #5722
changelog: Suggest `Rc<Box<T>>` -> `Rc<T>` in [`redundant_allocation`] lint

Change Rc<Box<T>> recommendation to be Rc<T> instead of Box<T>

---

doc/adding_lints.md

I think it would be better to add lint message convention to documentation. I referred to https://github.com/rust-lang/rust-clippy/pull/5888 and https://github.com/rust-lang/rust-clippy/pull/5893.

Add reference to rustc-dev-guide about lint message

---

clippy_lints/src/methods/mod.rs

docs: typo in `temporary_cstring_as_ptr`: s/point/&s

---

clippy_lints/src/doc.rs
tests/ui/needless_doc_main.rs
tests/ui/needless_doc_main.stderr

This switches from text-based search to running the parser to avoid false positives. Inspired by how [rustdoc](https://github.com/rust-lang/rust/blob/3f3250500fe152b5759c21453ba9a9129808d0d8/src/librustdoc/test.rs#L366) handles this and by #4729.
cc @llogiq 
changelog: Fix multiple false positives in [`needless_doctest_main`].
Fixes #5879 
Fixes #4906 
Fixes #5103
Fixes #4698

Parse doctests in needless_doctest_main

---

CHANGELOG.md
clippy_lints/src/lib.rs
clippy_lints/src/to_string_in_display.rs
src/lintlist/mod.rs
tests/ui/to_string_in_display.rs
tests/ui/to_string_in_display.stderr

fixes #3876
this PR is derived from [Toxyxer's implementation](https://github.com/rust-lang/rust-clippy/pull/5574).
changelog: add [`to_string_in_display`] lint

Don't use `to_string` in impl Display

---

clippy_lints/src/lib.rs
clippy_lints/src/utils/conf.rs
clippy_lints/src/vec.rs
tests/ui/vec.fixed
tests/ui/vec.rs

Fixes: #5847 
changelog: Add `too_large_for_stack ` configuration option for `USELESS_VEC`

appreciative too_large_for_stack in useless `vec!`

---

clippy_lints/src/mut_reference.rs

changelog: Correct "immutable reference" to "mutable reference" in description of `unnecessary_mut_passed`

Fix typo in description of unnecessary_mut_passed

---

CHANGELOG.md
clippy_lints/src/assign_ops.rs
clippy_lints/src/booleans.rs
clippy_lints/src/copies.rs
clippy_lints/src/double_comparison.rs
clippy_lints/src/eq_op.rs
clippy_lints/src/floating_point_arithmetic.rs
clippy_lints/src/lib.rs
clippy_lints/src/question_mark.rs
clippy_lints/src/self_assignment.rs
clippy_lints/src/swap.rs
clippy_lints/src/utils/hir_utils.rs
clippy_lints/src/utils/internal_lints.rs
clippy_lints/src/utils/mod.rs
src/lintlist/mod.rs
tests/ui/self_assignment.rs
tests/ui/self_assignment.stderr

Warn about assignments where left-hand side place expression is the same
as right-hand side value expression. For example, warn about assignment in:
```rust
pub struct Event {
id: usize,
x: i32,
y: i32,
}
pub fn copy_position(a: &mut Event, b: &Event) {
a.x = b.x;
a.y = a.y;
}
```
changelog: New lint `self_assignment`, checks for explicit self-assignments.

Warn about explicit self-assignment

---

Cargo.toml
clippy_lints/Cargo.toml

cargo_metadata 0.9.1 -> 0.11.1
semver 0.9.0 -> 0.10.0

deps: bump cargo_metadata and semver

---

clippy_lints/src/loops.rs
tests/ui/same_item_push.rs

Fixes https://github.com/rust-lang/rust-clippy/issues/5902
changelog: Fix FP for `same_item_push` where the pushed variable is mutated.

Fix FP for `same_item_push`

---

clippy_lints/src/transmute.rs
tests/ui/transmute.rs
tests/ui/transmute.stderr
tests/ui/transmute_float_to_int.rs
tests/ui/transmute_float_to_int.stderr

changelog: Avoid suggesting from/to bits in const contexts in [`transmute_int_to_float`]
Fixes #5747

transmute: avoid suggesting from/to bits in const

---

clippy_lints/src/precedence.rs
tests/ui/precedence.fixed
tests/ui/precedence.rs
tests/ui/precedence.stderr

Extend the lint to handle chains of methods combined with unary negation.
Closes #5924
changelog: Fix false negative in `PRECEDENCE` lint

Fix false negative in `PRECEDENCE` lint

---

clippy_lints/src/stable_sort_primitive.rs
clippy_lints/src/utils/mod.rs
tests/ui/stable_sort_primitive.stderr

changelog: stable_sort_primitive: print the type that is being sorted in the lint message

stable_sort_primitive: print the type that is being sorted in the lint message

---

clippy_lints/src/redundant_closure_call.rs
tests/ui/redundant_closure_call_early.stderr
tests/ui/redundant_closure_call_fixable.stderr
tests/ui/redundant_closure_call_late.rs

Fix #5916
changelog: Fix FP for `redundant_closure_call` when called in function body

Fix FP for `redundant_closure_call`

---

CONTRIBUTING.md

[Rendered](https://github.com/ebroto/rust-clippy/blob/rustup_doc_improvements/CONTRIBUTING.md)
r? @flip1995 

Improve documentation related to the sync process

---

.cargo/config
tests/fmt.rs

Various fmt test improvements.

Various fmt test improvements

---

clippy_lints/src/len_zero.rs
tests/ui/len_zero.fixed
tests/ui/len_zero.rs
tests/ui/len_zero_ranges.fixed
tests/ui/len_zero_ranges.rs
tests/ui/len_zero_ranges.stderr

Fixes #5956
Completed stabilization PR: https://github.com/rust-lang/rust/pull/75132
changelog: len_zero: re-enable linting ranges now that range_is_empty is stable

Re-enable len_zero for ranges now that `is_empty` is stable on them

---

clippy_lints/src/methods/mod.rs
tests/ui/unnecessary_clone.rs
tests/ui/unnecessary_clone.stderr

In the lint `clone_on_ref_ptr`, if the `span` is in a macro, don't expand it for suggestion.
Fixes: #2076
r? @ebroto

Fix incorrect suggestion when `clone_on_ref_ptr` is triggered in macros

---

clippy_lints/src/non_copy_const.rs
tests/ui/borrow_interior_mutable_const.rs
tests/ui/borrow_interior_mutable_const.stderr

fixes #5796
changelog: fix false positive in `borrow_interior_mutable_const` when referencing a field behind a pointer.

Fix fp in `borrow_interior_mutable_const`

---

clippy_lints/src/returns.rs
tests/ui/let_and_return.rs
tests/ui/let_and_return.stderr

Add a cast to the suggestion when the return expression has adjustments.
These adjustments are lost when the suggestion is applied.
This is similar to the problem in issue #4437.
Closes #5729
changelog: Fix `let_and_return` bad suggestion

Fix `let_and_return` bad suggestion

---

clippy_lints/src/float_equality_without_abs.rs
tests/ui/float_equality_without_abs.stderr

Fixes an issue in the `float_equality_without_abs` lint. The lint suggestion was configured in a way that it lints the whole error and not just the subtraction part. In the current configuration the lint would suggest to change the expression in a wrong way, e.g.
```rust
let _ = (a - b) < f32::EPSILON; // before
let _ = (a - b).abs(); // after
```
This was dicovered by @flip1995. (See discussion of PR #5952).
Also the suggestion is now formatted via `utils::sugg`.

Corrects the float_equality_without_abs lint

---

clippy_lints/src/write.rs

For the context, please see https://github.com/rust-lang/rust-clippy/issues/5822#issuecomment-680749728 and https://github.com/rust-lang/rust-clippy/issues/5822#issuecomment-680783381.
---

Fix the wrong use of `snippet_with_applicability`

---

clippy_lints/src/to_string_in_display.rs
tests/ui/to_string_in_display.rs

Don't emit a lint when `.to_string()` on anything that is not `self`
Fix #5967 
changelog: Fix FP in `to_string_in_display` when calling `.to_string()` on anything that is not `self`

Fix FP in `to_string_in_display`

---

CHANGELOG.md

[Rendered](https://github.com/ebroto/rust-clippy/blob/changelog_beta_1_47/CHANGELOG.md)

Update changelog to beta 1.47

---

clippy_lints/src/len_zero.rs
tests/ui/len_zero.fixed
tests/ui/len_zero.rs
tests/ui/len_zero_ranges.fixed
tests/ui/len_zero_ranges.rs
tests/ui/len_zero_ranges.stderr

[beta] Backport: Re-enable len_zero for ranges now that `is_empty` is stable on them

---

clippy_lints/src/methods/mod.rs

It wasn't being syntax highlighted in the online lint index:
changelog: Add syntax highlighting to the documentation of [`single_char_push_str`]

Syntax-highlight `single_char_push_str` lint

---

clippy_lints/src/utils/mod.rs
tests/ui/or_fun_call.fixed
tests/ui/or_fun_call.rs
tests/ui/or_fun_call.stderr

The fix in #5889 was missing associated functions.
changelog: Ignore also `const fn` methods in [`or_fun_call`]
Fixes #5693

or_fn_call: ignore nullary associated const fns

---

CHANGELOG.md
clippy_lints/src/async_yields_async.rs
clippy_lints/src/lib.rs
src/lintlist/mod.rs
tests/ui/async_yields_async.fixed
tests/ui/async_yields_async.rs
tests/ui/async_yields_async.stderr

This catches bugs of the form
tokio::spawn(async move {
let f = some_async_thing();
f // Oh no I forgot to await f so that work will never complete.
});
See the two XXXkhuey comments and the unfixed `_l` structure for things that need more thought.

Add a lint for an async block/closure that yields a type that is itself awaitable.

---

clippy_lints/src/utils/sugg.rs
tests/ui/collapsible_if.fixed
tests/ui/collapsible_if.rs
tests/ui/collapsible_if.stderr

Fix #5962
changelog: Fix the wrong suggestion when using macro in `collapsible_if`

Fix the wrong suggestion when using macro in `collapsible_if`

---

clippy_lints/src/default_trait_access.rs
tests/ui/default_trait_access.fixed
tests/ui/default_trait_access.stderr

https://github.com/rust-lang/rust-clippy/issues/5975#issuecomment-683751131
> I think the underlying problem is clippy suggests code with complete parameters, not clippy triggers this lint even for complex types. AFAIK, If code compiles with `Default::default`, it doesn't need to specify any parameters, as type inference is working. (So, in this case, `default_trait_access` should suggest `RefCell::default`.)
Fixes #5975 Fixes #5990
changelog: `default_trait_access`: fixed wrong suggestion

default_trait_access: Fix wrong suggestion

---

clippy_lints/src/transmute.rs
tests/ui/transmute_ptr_to_ptr.rs

fixes #5959
changelog: Fix a false positive in `transmute_ptr_to_ptr` that the lint fires when `transmute` is used to cast a reference in const contexts although dereferencing raw pointers in consts is unstable.

Fix a fp in `transmute_ptr_to_ptr`

---

clippy_lints/src/utils/conf.rs
tests/ui/doc.rs
tests/ui/doc.stderr

changelog: Allow "GraphQL" in [`doc_markdown`] without backticks.

Allow GraphQL in docs without backticks

---

tests/ui/issue-3145.stderr

Related rust pull request: rust-lang/rust#76160

Update ui stderr with improved rustc output

---

clippy_lints/src/attrs.rs
tests/ui/useless_attribute.fixed
tests/ui/useless_attribute.rs
tests/ui/useless_attribute.stderr

Fixes #5918
changelog: `useless_attribute`: Permit `wildcard_imports` and `enum_glob_use` on `use` items

useless_attribute: Permit wildcard_imports and enum_glob_use

---

clippy_lints/src/functions.rs
tests/ui-toml/functions_maxlines/test.stderr
tests/ui/functions_maxlines.stderr

This PR adds the current amount of lines and the current maximum number of lines in the message for the `too_many_lines` lint, in a similar way as the `too_many_arguments` lint currently does.
changelog: show the line count and the maximum lines in the message for the `too_many_lines` lint.

Show line count and max lines in too_many_lines lint message

---

clippy_lints/src/loops.rs
tests/ui/same_item_push.rs

Don't emit a lint when the pushed item doesn't have Clone trait
Fix #5979
changelog: Fix FP in `same_item_push` not to emit a lint when the pushed item doesn't have Clone trait

Fix FP in `same_item_push`

---

clippy_lints/src/unnecessary_sort_by.rs
tests/ui/unnecessary_sort_by.fixed
tests/ui/unnecessary_sort_by.rs

`Vec::sort_by_key` closure parameter is `F: FnMut(&T) -> K`. The lint's suggestion destructures the `T` parameter; this was probably done to avoid different unnamed lifetimes when `K = Reverse<&T>`.
This change fixes two issues:
* Destructuring T when T is non-reference requires the type to be Copy, otherwise we would try to move from a shared reference. We make sure `T: Copy` holds. 
* Make sure `T` is actually non-reference. I didn't go for destructuring multiple levels of references, as we would have to compensate in the closure body by removing derefs and maybe adding parens, which would add more complexity.
changelog: Restrict [`unnecessary_sort_by`] to non-reference, Copy types
Fixes #6001

Restrict unnecessary_sort_by to non-reference, Copy types

---

clippy_lints/src/loops.rs
tests/ui/same_item_push.rs
tests/ui/same_item_push.stderr

It only emits a lint when the pushed item is a literal, a constant and an immutable binding that are initialized with those, as discussed in https://github.com/rust-lang/rust-clippy/pull/5997#pullrequestreview-483005186. 
Fix https://github.com/rust-lang/rust-clippy/issues/5985
changelog: Restrict `same_item_push` to literals, constants and immutable bindings that are initialized with those.
r? @ebroto

Restrict `same_item_push` to suppress false positives

---

clippy_lints/src/map_unit_fn.rs
tests/ui/option_map_unit_fn_fixable.stderr
tests/ui/result_map_unit_fn_fixable.stderr
tests/ui/result_map_unit_fn_unfixable.stderr

changelog: print the unit type `()` in related lint messages

print the unit type `()` in related lint messages.

---

clippy_lints/src/types.rs

changelog: link to the box docs in lint docs

link to the Box docs in related lint documentation.

---

clippy_dev/src/ra_setup.rs

update cargo dev ra-setup to changed rustc source paths

---

clippy_lints/src/methods/mod.rs
tests/ui/into_iter_on_ref.stderr

into_iter_on_ref: rephrase lint message: will not move the x -> will not consume the x

---

clippy_lints/src/bit_mask.rs
clippy_lints/src/lib.rs
src/lintlist/mod.rs
tests/ui/trailing_zeros.rs
tests/ui/trailing_zeros.stderr

Fix #5633.
changelog: Downgrade `verbose_bit_mask` to pedantic

Downgrade `verbose_bit_mask` to pedantic

---

clippy_lints/src/useless_conversion.rs
tests/ui/useless_conversion.stderr
tests/ui/useless_conversion_try.stderr

changelog: useless_conversion: show type in error message.

useless_conversion: show type in error message.

---

clippy_lints/src/lib.rs
clippy_lints/src/loops.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/option_if_let_else.rs
clippy_lints/src/utils/diagnostics.rs
clippy_lints/src/utils/internal_lints.rs
clippy_lints/src/utils/mod.rs
doc/common_tools_writing_lints.md
tests/ui/match_type_on_diag_item.rs
tests/ui/match_type_on_diag_item.stderr

Internal lint: suggest `is_type_diagnostic_item` over `match_type` where applicable

---

clippy_lints/src/shadow.rs

It seems to be an extra blank line in doc example.

Remove an extra blank line in `shadow_same`

---

clippy_lints/src/misc.rs
tests/ui/float_cmp.stderr
tests/ui/float_cmp_const.stderr

fixes #6040 
changelog: change wording of float comparison operator to make margin of error less ambiguous

clarify margin of error in wording of float comparison operator lint messages

---

clippy_lints/Cargo.toml

Bump pulldown-cmark v0.8

---

CONTRIBUTING.md
doc/adding_lints.md

Moving from Discord to Zulip was discussed at https://github.com/rust-lang/rust-clippy/issues/5943 and new stream in Zulip was created at https://github.com/rust-lang/rust-clippy/issues/5943#issuecomment-691984366.

Update documentation about moving from Discord to Zulip

---

clippy_lints/src/write.rs
tests/ui/print_with_newline.rs
tests/ui/print_with_newline.stderr
tests/ui/write_with_newline.rs
tests/ui/write_with_newline.stderr

changelog: do not suggest empty format strings in `print-with-newline` and `write-with-newline`

{print,write}-with-newline: do not suggest empty format string

---

clippy_lints/src/shadow.rs

Fix #5455.
This lint can be disabled at function level.

Add note to `shadow_unrelated`

---

clippy_lints/src/methods/bind_instead_of_map.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/unnecessary_lazy_eval.rs
clippy_lints/src/option_if_let_else.rs
clippy_lints/src/utils/eager_or_lazy.rs
clippy_lints/src/utils/mod.rs
clippy_lints/src/utils/sugg.rs
clippy_lints/src/utils/usage.rs
tests/ui/option_if_let_else.fixed
tests/ui/option_if_let_else.rs
tests/ui/option_if_let_else.stderr
tests/ui/unnecessary_lazy_eval.fixed
tests/ui/unnecessary_lazy_eval.rs
tests/ui/unnecessary_lazy_eval.stderr

Addresses partially #5821.
changelog: improve the lint `option_if_let_else`. Suggest `map_or` or `map_or_else` based on the else expression purity.

option_if_let_else - distinguish pure from impure else expressions

---

clippy_lints/src/bytecount.rs
clippy_lints/src/duration_subsec.rs
clippy_lints/src/entry.rs
clippy_lints/src/fallible_impl_from.rs
clippy_lints/src/format.rs
clippy_lints/src/indexing_slicing.rs
clippy_lints/src/inherent_to_string.rs
clippy_lints/src/len_zero.rs
clippy_lints/src/match_on_vec_items.rs
clippy_lints/src/matches.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/misc.rs
clippy_lints/src/mut_key.rs
clippy_lints/src/open_options.rs
clippy_lints/src/path_buf_push_overwrite.rs
clippy_lints/src/repeat_once.rs
clippy_lints/src/strings.rs
clippy_lints/src/swap.rs
clippy_lints/src/unwrap_in_result.rs
clippy_lints/src/utils/internal_lints.rs
clippy_lints/src/utils/mod.rs
tests/ui/indexing_slicing_index.rs
tests/ui/indexing_slicing_index.stderr
tests/ui/indexing_slicing_slice.stderr

Fixes #6021
...and remove `walk_ptrs_ty` in favour of `peel_refs`, which came in 2019.
---
changelog: Fix a false positive in `indexing_slicing` and `out_of_bounds_indexing` where references to arrays weren't treated as arrays.

Treat refs to arrays the same as owned arrays in `indexing_slicing` and `out_of_bounds_indexing`

---

clippy_lints/src/non_copy_const.rs
tests/ui/borrow_interior_mutable_const.rs
tests/ui/borrow_interior_mutable_const.stderr
tests/ui/declare_interior_mutable_const.rs
tests/ui/declare_interior_mutable_const.stderr

This implements my suggestion [here](https://github.com/rust-lang/rust-clippy/issues/5050#issuecomment-680310889), and so hopefully fixes #5050.
* stop linting associated types and generic type parameters
* start linting ones in trait impls
whose corresponding definitions in the traits are generic
* remove the `is_copy` check
as presumably the only purpose of it is to allow
generics with `Copy` bounds as `Freeze` is internal
and generics are no longer linted
* remove the term 'copy' from the tests
as being `Copy` no longer have meaning
---
changelog: Change the criteria of `declare_interior_mutable_const` and `borrow_interior_mutable_const` to narrow the lints to only lint things that defenitly is a interior mutable type, not potentially.

Change the criteria of `interior_mutable_const`

---

CHANGELOG.md
clippy_lints/src/consts.rs
clippy_lints/src/lib.rs
clippy_lints/src/types.rs
clippy_lints/src/utils/paths.rs
src/lintlist/mod.rs
tests/ui/rc_buffer.rs
tests/ui/rc_buffer.stderr
tests/ui/rc_buffer_arc.rs
tests/ui/rc_buffer_arc.stderr
tests/ui/rc_buffer_redefined_string.rs

Fixes #2623
This is a bit different from the original PR attempting to implement this type of lint.   Rather than linting against converting into the unwanted types, this PR lints against declaring the unwanted type in a struct or function definition.
I'm reasonably happy with what I have here, although I used the fully qualified type names for the Path and OsString suggestions, and I'm not sure if I should have just used the short versions instead, even if they might not have been declared via use.
Also, I don't know if "buffer type" is the best way to put it or not.  Alternatively I could call it a "growable type" or "growable buffer type", but I was thinking of PathBuf when I started making the lint.
changelog: Add `rc_buffer` lint

Add `rc_buffer` lint for checking Rc<String> and friends

---

clippy_lints/src/loops.rs
tests/ui/explicit_counter_loop.rs

Fixes #4677 and #6074
Fix a false positive in `explicit_counter_loop` where the loop counter is used after incremented, adjust the test so that counters are incremented at the end of the loop and add the test for this false positive.
---
changelog: Fix a false positive in `explicit_counter_loop` where the loop counter is used after incremented

Fix a FP in `explicit_counter_loop`

---

clippy_lints/src/utils/mod.rs
tests/ui/or_fun_call.fixed
tests/ui/or_fun_call.rs
tests/ui/or_fun_call.stderr

The changes in #5889 and #5984 were done under the incorrect assumption that a `const fn` with no args was guaranteed to be evaluated at compile time.  A `const fn` is only guaranteed to be evaluated at compile time if it's inside a const context (the initializer of a `const` or a `static`). 
See this [zulip conversation](https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/Common.20misconception.3A.20.60const.20fn.60.20and.20its.20effect.20on.20codegen/near/208059113) for more details on this common misconception.
Given that none of the linted methods by `or_fun_call` can be called in const contexts, the lint should make no exceptions.
changelog: [`or_fun_call`] lints again calls to `const fn` with no args

Revert: or_fun_call should lint calls to `const fn`s with no args

---

clippy_lints/src/write.rs
clippy_workspace_tests/build.rs
tests/ui/build.rs
tests/ui/print_stdout_build_script.rs

Fix #6041 
This lint shouldn't be emitted in `build.rs` as `println!` and `print!` are used for the build script.

Fix FP in `print_stdout`

---

clippy_lints/src/types.rs

This didn't display some types properly in the docs due the lack of code formatting.
Also, refs for the caveat:
https://github.com/rust-lang/rust-clippy/pull/6044#issuecomment-699559082
https://github.com/http-rs/surf/pull/242
Fwiw I can't get `cargo test` to run, even on nightly. I get: 
```
error[E0463]: can't find crate for `rustc_ast`
```
changelog: none, nightly

lints: clarify rc_buffer and add caveats

---

clippy_lints/src/needless_arbitrary_self_type.rs
tests/ui/auxiliary/proc_macro_attr.rs
tests/ui/needless_arbitrary_self_type_unfixable.rs
tests/ui/needless_arbitrary_self_type_unfixable.stderr

This fixes two cases related to macros:
* If the parameter comes from expansion, do not lint as the user has no possibility of changing it. This is not directly related to the fixed issue, but we should probably do that.
* If *only* the lifetime name comes from expansion, lint, but allow the user decide the name of the lifetime. In the related issue, the lifetime was unnamed and then renamed by `async_trait`, so just removing the name in the suggestion would work, but in the general case a macro can rename a lifetime that was named differently, and we can't reliably know that name anymore. 
As a hint for the reviewer, the expanded code for the test can be checked with this command (from the root dir of the repo):
```sh
rustc -L target/debug/test_build_base/needless_arbitrary_self_type_unfi …
```

needless arbitrary self: handle macros

---

CHANGELOG.md
clippy_lints/src/asm_syntax.rs
clippy_lints/src/lib.rs
src/lintlist/mod.rs
tests/ui/asm_syntax.rs
tests/ui/asm_syntax.stderr

changelog: Add lint for inline assembly syntax style preference

Add lint for inline assembly syntax style preference

---

clippy_lints/src/loops.rs
tests/ui/needless_range_loop2.rs

Fix #5945
Fix #1864
changelog: Don't emit a lint for the suggestion leading to errors in `needless_range_loop`

Don't emit a lint for the suggestion leading to errors in `needless_range_loop`

---

clippy_lints/src/utils/numeric_literal.rs
tests/ui/inconsistent_digit_grouping.fixed
tests/ui/inconsistent_digit_grouping.rs

Fixes #6096
changelog: Fixed bug in `clippy::inconsistent_digit_grouping` when floating point exponent is used

Allow exponent separator

---

clippy_lints/src/literal_representation.rs
tests/ui/mistyped_literal_suffix.fixed
tests/ui/mistyped_literal_suffix.rs
tests/ui/mistyped_literal_suffix.stderr

As suggested in https://github.com/rust-lang/rust-clippy/issues/4706#issuecomment-544797928, the fractional part is now ignored (the integer part is checked instead).
Fixes: #4706
changelog: `mistyped_literal_suffixes` no longer warns on the fractional part of a float (e.g. 713.23_64)

Do not lint float fractions in `mistyped_literal_suffixes`

---

clippy_lints/src/unnecessary_sort_by.rs
tests/ui/unnecessary_sort_by.fixed
tests/ui/unnecessary_sort_by.rs
tests/ui/unnecessary_sort_by.stderr

This change tries to simplify the solution for problematic cases but is less restrictive than  #6006.
* We can't dereference shared references to non-Copy types, so the new suggestion does not do that. Note that this implies that the suggested closure parameter will be a reference.
* We can't take a reference to the closure parameter in the returned key, so we don't lint in those cases. This can happen either because the key borrows from the parameter (e.g. `|a| a.borrows()`), or because we suggest `|a| Reverse(a)`. If we did we would hit this error:
```
error: lifetime may not live long enough
--> /home/ebroto/src/ebroto-clippy/tests/ui/unnecessary_sort_by.fixed:19:25
|
19 |     vec.sort_by_key(|b| Reverse(b));
|                      -- ^^^^^^^^^^ returning this value requires that `'1` …
```

unnecessary sort by: avoid dereferencing the suggested closure parameter

---

tests/ui/attrs.rs
tests/ui/attrs.stderr
tests/ui/blanket_clippy_restriction_lints.rs
tests/ui/blanket_clippy_restriction_lints.stderr

In [this commit](https://github.com/rust-lang/rust-clippy/pull/6126/commits/5747c15961da9d2d0b0dd775174d39f3b5961597) coming from rust-lang/rust (#6126) the test for `#![forbid(clippy::restriction)]` was removed because some restriction lints were being allowed after the forbid.
This change reinstates the test for `forbid` by using a separate file.
r? @flip1995

Reinstate test for forbid(clippy::restriction)

---

clippy_lints/src/methods/mod.rs

Use more concrete explanation for methods

---

clippy_dev/Cargo.toml
clippy_dev/src/lib.rs
clippy_lints/Cargo.toml
clippy_lints/src/lib.rs
clippy_lints/src/macro_use.rs
clippy_lints/src/utils/conf.rs
tests/cargo/mod.rs
tests/compile-test.rs
tests/dogfood.rs

This replaces some `lazy_static` usage with [`SyncLazy`](https://doc.rust-lang.org/nightly/std/lazy/struct.SyncLazy.html) of the unstable `once_cell` feature.

Replace some lazy_static usage with once_cell feature

---

clippy_lints/src/lib.rs
clippy_lints/src/types.rs
src/lintlist/mod.rs

I think Arc\<Vec\<T\>\> and Arc\<String\> and similar are a totally reasonable data structure, as observed by others in the comments on [#6044](https://github.com/rust-lang/rust-clippy/pull/6044#event-3799579830) as well. Doing `Arc::make_mut(&mut self.vec).push(...)` or `Arc::make_mut(&mut self.string).push_str("...")` is a terrific and well performing copy-on-write pattern. Linting this with an enabled-by-default <kbd>performance</kbd> lint strikes me as an unacceptable false positive balance.
As of #6090 the documentation of this lint now contains:
> **Known problems:** This pattern can be desirable ...
which should indicate that we shouldn't be linting against correct, reasonable, well-performing patterns with an enabled-by-default lint.
Mentioning #6044, #6090.
r? @yaahc, who …

Downgrade rc_buffer to restriction

---

clippy_lints/src/regex.rs
tests/ui/regex.rs

fixes #6005
The rationale for this is that since we wrote that lint, `bytes::Regex` was extended to be able to use unicode character classes.
---
changelog: [`invalid_regex`]: allow unicode character classes in bytes regex.

Fix unicode regexen with bytes::Regex

---

doc/basics.md

I think it would be better to add a note that we follow a rustc no merge-commit policy. For example, it was mentioned at https://github.com/rust-lang/rust-clippy/pull/5694#issuecomment-641871096.

Add note that we follow a rustc no merge-commit policy

---

clippy_lints/src/lib.rs
clippy_lints/src/strings.rs
src/lintlist/mod.rs

Between #1402 (regarding `to_owned`) and #4494 (regarding `impl Read`), as well as other confusion I've seen hit in my work codebase involving string_lit_as_bytes (`"...".as_bytes().into()`), I don't think this lint is at a quality to be enabled by default.
I would consider re-enabling this lint after it is updated to understand when the surrounding type information is sufficient to unsize `b"..."` to &\[u8\] without causing a type error.
As currently implemented, this lint is pushing people to write `&b"_"[..]` which is not an improvement over `"_".as_bytes()` as far as I am concerned.
---
changelog: Remove string_lit_as_bytes from default set of enabled lints

Downgrade string_lit_as_bytes to nursery

---

clippy_lints/src/escape.rs
tests/ui/escape_analysis.rs

changelog: [`boxed_local`]: don't lint in `extern fn` arguments
Fixes #5542.
When using C FFI, to handle pointers in parameters it is needed to
declare them as `Box` in its Rust-side signature. However, the current
linter warns against the usage of Box stating that "local variable
doesn't need to be boxed here".
This commit fixes it by ignoring functions whose Abi is C.

clippy_lints: Do not warn against Box parameter in C FFI

---

CHANGELOG.md

[Rendered](https://github.com/ebroto/rust-clippy/blob/changelog_1_48/CHANGELOG.md)
I've not added the PRs fixing `same_item_push` because those were backported, namely:
* [#5908](https://github.com/rust-lang/rust-clippy/pull/5908)
* [#5997](https://github.com/rust-lang/rust-clippy/pull/5997)
* [#6016](https://github.com/rust-lang/rust-clippy/pull/6016)
The following PR was reverted, so I've ignored it too:
* [#5984](https://github.com/rust-lang/rust-clippy/pull/5984)
~~Also, I took the liberty of adding a "Thanks" section, naming all the contributors to this release. I think they deserve visibility in the changelog. Please tell me if we want to add this or maybe it's redundant given we link to the PRs?~~
r? @flip1995

Add changelog for 1.48 beta

---

clippy_lints/src/option_if_let_else.rs

clippy_lint: Fix doc on 'option_if_let_else'

---

doc/common_tools_writing_lints.md

While working on #6130, I noticed that part of the documentation was updated to use `LateContext::typeck_results`, but the paragraph still referred to the old `tables` field of `LateContext`.
---

Rename tables to typecheck_result()

---

doc/release.md

When updating the beta branch, we want to reset, instead of rebase. Otherwise we might produce again new commits on the beta branch, that aren't on the master branch.

Update release documentation

---

.github/workflows/clippy.yml
.github/workflows/clippy_bors.yml
.github/workflows/clippy_dev.yml
.github/workflows/deploy.yml
.github/workflows/remark.yml

This updates all of our action dependencies and removes every usage of `set-env`. `set-env` and `add-path` has been deprecated: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Remove deprecated set-env from GHA

---

CHANGELOG.md
clippy_lints/src/lib.rs
clippy_lints/src/ptr_eq.rs
src/lintlist/mod.rs
tests/ui/ptr_eq.fixed
tests/ui/ptr_eq.rs
tests/ui/ptr_eq.stderr

This is based almost entirely on the code available in the previous PR #4596. I merely updated the code to make it compile.
Fixes #3661.
---

New lint: Recommend using `ptr::eq` when possible

---

clippy_lints/src/consts.rs
tests/ui/float_cmp.rs
tests/ui/float_cmp.stderr

This helps with #3804 (but won't completely fix it).
---

allow refs in our constant folder

---

clippy_lints/src/format.rs
tests/ui/format.fixed
tests/ui/format.stderr

fixes #6142 
clippy::useless_format will keep the source's string (after converting {{ and }} to { and }) when suggesting a change from format!() to .to_string() usage. Ie:
|     let s = format!(r#""hello {{}}""#);
|             ^^^^^^^^^^^^^^^^^^^^^ help: consider using `.to_string()`: `r#""hello {}""#.to_string()`
changelog: [`useless_format`]: preserve raw string literals when no arguments to `format!()` are provided.

Preserve raw strs for: format!(s) to s.to_string() lint

---

clippy_lints/src/loops.rs
clippy_lints/src/utils/mod.rs
clippy_lints/src/utils/sugg.rs
tests/ui/manual_memcpy.rs
tests/ui/manual_memcpy.stderr
tests/ui/manual_memcpy/with_loop_counters.rs
tests/ui/manual_memcpy/with_loop_counters.stderr
tests/ui/manual_memcpy/without_loop_counters.rs
tests/ui/manual_memcpy/without_loop_counters.stderr

Closes #1670
This PR expands `manual_memcpy` to lint ones with loop counters as described in https://github.com/rust-lang/rust-clippy/issues/1670#issuecomment-293280204
Although the current code is working, I have a couple of questions and concerns.
~~Firstly, I manually implemented `Clone` for `Sugg` because `AssocOp` lacks `Clone`. As `AssocOp` only holds an enum, which is `Copy`, as a value, it seems `AssocOp` can be `Clone`; but, I was not sure where to ask it. Should I make a PR to `rustc`?~~ The [PR]( https://github.com/rust-lang/rust/pull/73629) was made.
Secondly, manual copying with loop counters are likely to trigger `needless_range_loop` and `explicit_counter_loop` along with `manual_memcpy`; in fact, I explicitly allowed them in the tests. Is there any way to disable these two …

Expands `manual_memcpy` to lint ones with loop counters

---

clippy_lints/src/doc.rs

This PR does not fix #5834, but it records the problematic link text as a **known problem** inside `doc_markdown` lint.
r? @flip1995
---
changelog: Document problematic link text style as known problem for `doc_markdown`

Ref style link false positive

---

clippy_lints/src/mut_key.rs
clippy_lints/src/types.rs
tests/ui/crashes/ice-6153.rs

Fixes #6153 
Properly fixes #6139 
The test case in #6153 is kind of weird. Even removing one of the arguments of the `foo` function prevented the ICE. I think this test case is actually minimal.

Fix two ICEs caused by ty.is_{sized,freeze}

---

doc/adding_lints.md
tests/ui-cargo/update-references.sh
tests/ui-toml/update-references.sh
tests/ui/update-references.sh

An empty file may be generated by `update-references.sh` and committed as is when creating a patch like https://github.com/rust-lang/rust-clippy/pull/6101#issuecomment-702076508 and https://github.com/rust-lang/rust-clippy/pull/6079#pullrequestreview-496502721. So, I think it would be helpful to add documentation, and automatically remove the generated file if it's empty.

Remove the generated files by `update-references.sh` if they are empty

---

Cargo.toml
clippy_dev/src/update_lints.rs
src/driver.rs
src/lintlist/mod.rs

Follow-up to https://github.com/rust-lang/rust-clippy/pull/6120
This removes the last remaining `lazy_static` usages and replaces them with `SyncLazy` from the `once_cell` feature.
---

Remove lazy_static completely and use once_cell feature instead

---

clippy_lints/src/copies.rs
tests/ui/same_functions_in_if_condition.rs

Ignore expr that originate from a macro.
Fixes: #6168

Fix FP in `same_functions_in_if_condition` lint about condition as macro

---

README.md

it took me a while to figure out why `cargo clippy -- -Aclippy::pedantic -Wclippy::items-after-statements` still showed me *all* the lints. At first I thought it was due to the missing spaces in the current example and I debugged that until I stumbled across an issue noting that you have to touch a random file or run `cargo clean` when you're running clippy repeatedly on an unchanged codebase. This PR is an attempt to save the next person some time and also structure the "Allowing/denying lints" section a bit more while we're at it.
---

README: sort en/disabling section, fix typos, add note

---

doc/basics.md

setup-toolchain.sh uses "[[" which is a bash builtin, but the guide
suggests running it with sh.  On Ubuntu, /bin/sh points to dash and
running the script fails.
---

Suggest a compatible shell for setup-toolchain.sh

---

doc/adding_lints.md

Backstory: I somehow missed the fact that I needed to register a lint pass in order for it to run, and I spent some time confused until I figured it out. So I wanted to make it clear that a missing `register_(early|late)_pass` call is a likely cause of a lint not running.

Add more infomation about LintStore registration

---

CONTRIBUTING.md

These labels seems wrong.
- <https://github.com/rust-lang/rust-clippy/labels/L-crash%20%3Aboom%3A>
- <https://github.com/rust-lang/rust-clippy/labels/L-bug%20%3Abeetle%3A>

Fix links to labeled issues

---

clippy_lints/src/manual_unwrap_or.rs
src/lintlist/mod.rs
tests/ui/manual_unwrap_or.fixed
tests/ui/manual_unwrap_or.rs
tests/ui/manual_unwrap_or.stderr

Implements partially #5923.
changelog: support Result::unwrap_or in manual_unwrap_or

manual_unwrap_or / support Result::unwrap_or

---

CHANGELOG.md
clippy_lints/src/lib.rs
clippy_lints/src/undropped_manually_drops.rs
src/lintlist/mod.rs
tests/ui/undropped_manually_drops.rs
tests/ui/undropped_manually_drops.stderr

Adds a new lint for the following code:
```rust
struct S;
impl Drop for S {
fn drop(&mut self) {
println!("drip drop");
}
}
fn main() {
// This will not drop the `S`!!!
drop(std::mem::ManuallyDrop::new(S));
unsafe {
// This will.
std::mem::ManuallyDrop::drop(&mut std::mem::ManuallyDrop::new(S));
}
}
```
The inner value of a `ManuallyDrop` will not be dropped unless the proper, unsafe drop function is called on it. This lint makes sure that a user does not accidently use the wrong function and forget to drop a `ManuallyDrop` value. 
Fixes #5581.
---

Add new lint for undropped ManuallyDrop values

---

clippy_lints/src/lifetimes.rs
tests/ui/needless_lifetimes.rs

Closes #6159.
changelog: fix regression in needless-lifetimes

needless-lifetime / multiple where clause predicates regression

---

clippy_lints/src/needless_bool.rs
tests/ui/bool_comparison.fixed
tests/ui/bool_comparison.rs
tests/ui/bool_comparison.stderr

Don't lint if `cfg!` macro is one of the operand.
Fix suggestion when the span originated from a macro, using `hir_with_macro_callsite`.
Fixes: #3973 

No lint with `cfg!` and fix sugg for macro in `needless_bool` lint

---

clippy_lints/src/functions.rs
clippy_lints/src/loops.rs
clippy_lints/src/utils/mod.rs
clippy_lints/src/utils/usage.rs

The field `owner` of `HirId` is `LocalDefId` and `hir_id.owner.to_def_id().expect_local()` is redundant. I wonder they were introduced in some rustups.

Remove redundant `expect_local()` call

---

clippy_lints/src/blocks_in_if_conditions.rs
clippy_lints/src/escape.rs
clippy_lints/src/matches.rs
clippy_lints/src/misc_early.rs

It seems to be an extra blank line in doc example.

Remove an extra blank line in doc examples

---

clippy_lints/src/loops.rs
tests/ui/needless_collect_indirect.rs
tests/ui/needless_collect_indirect.stderr

A test, https://github.com/rust-lang/rust-clippy/blob/master/tests/ui/needless_collect_indirect.rs#L11-L12, suggests following codes, but the suggested codes don't work. An example is here: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6947d9f2806a83f41cc5eb8e39b09d0b.
```
error: avoid using `collect()` when not needed
--> $DIR/needless_collect_indirect.rs:11:5
|
LL | /     let indirect_contains = sample.iter().collect::<VecDeque<_>>();
LL | |     indirect_contains.contains(&&5);
| |____^
|
help: Check if the original Iterator contains an element instead of collecting then checking
|
LL |     
LL |     sample.iter().any(|x| x == &&5);
```

Fix an invalid suggestion in `needless_collect` test

---

clippy_lints/src/misc.rs
tests/ui/auxiliary/macro_rules.rs
tests/ui/toplevel_ref_arg.fixed
tests/ui/toplevel_ref_arg.rs
tests/ui/toplevel_ref_arg.stderr
tests/ui/toplevel_ref_arg_non_rustfix.rs
tests/ui/toplevel_ref_arg_non_rustfix.stderr

Do not lint when the span is from a macro.
Question: shouldn't we extend this for external macros also ?
Fixes: #5849 

No lint in macro for `toplevel_ref_arg`

---

clippy_lints/src/items_after_statements.rs
tests/ui/item_after_statement.rs
tests/ui/item_after_statement.stderr

The items_after_statements lint was skipping all expansions.  Instead
we should still lint local macros.
Fixes #578
---
changelog: The items_after_statements now applies to local macro expansions

Lint items after statements in local macro expansions

---

CONTRIBUTING.md

`E-easy` isn't used, so `good first issue` is more appropriate.

Replace `E-easy` with `good first issue` in `CONTRIBUTING.md`

---

clippy_lints/src/types.rs
tests/ui/borrow_box.rs
tests/ui/borrow_box.stderr

Fixes #3128 
Fix the suggestion of 'borrowed_box', which causes a syntax error because it misses necessary parentheses.
---
changelog: Fix the error-causing suggestion of 'borrowed_box'

fix the error-causing suggestion of 'borrowed_box'

---

clippy_lints/src/arithmetic.rs
tests/ui/integer_arithmetic.rs
tests/ui/integer_arithmetic.stderr

re: #6209 
Updates the lint to not the error message if RHS of binary operation `/` of `%` is a literal/constant that is not `0` or `-1`, as suggested [here](https://github.com/rust-lang/rust-clippy/issues/6209#issuecomment-715624354)
changelog: Expand [`integer_arithmetic`] to work with RHS literals and constants

Update the existing arithmetic lint

---

doc/adding_lints.md

Fix typo in adding_lints.md

---

CHANGELOG.md
clippy_lints/src/lib.rs
clippy_lints/src/manual_ok_or.rs
src/lintlist/mod.rs
tests/ui/manual_ok_or.fixed
tests/ui/manual_ok_or.rs
tests/ui/manual_ok_or.stderr

Implements partially #5923
changelog: add lint manual_ok_or

add manual_ok_or lint

---

README.md

Disable and enable when not specifically explained were not clear to me
as an English language speaker, but I was able to figure it out fairly
easily due to the examples having A/W, which I assumed meant `allow` and
`warn`.  I removed both words to be sure it was clear as well as
extending the note on what deny means.  It now includes a statement on
exactly what each word means.
Documentation only update.

Clarify allow/warn/deny documentation.  Remove enable/disable.

---

clippy_lints/src/unused_unit.rs
tests/ui/unused_unit.fixed
tests/ui/unused_unit.rs
tests/ui/unused_unit.stderr

Fix https://github.com/rust-lang/rust-clippy/issues/6230
changelog: Fix suggestion to add unneeded space in `unused_unit`

Fix suggestion to add unneeded space in `unused_unit`

---

clippy_lints/src/manual_async_fn.rs
clippy_lints/src/unused_unit.rs
clippy_lints/src/utils/mod.rs
tests/ui/manual_async_fn.fixed
tests/ui/manual_async_fn.rs
tests/ui/manual_async_fn.stderr

Fix a same case as https://github.com/rust-lang/rust-clippy/pull/6247
changelog: Fix suggestion to add unneeded space in `manual_async`

Fix suggestion to add unneeded space in `manual_async`

---

clippy_lints/src/methods/unnecessary_lazy_eval.rs
tests/ui/unnecessary_lazy_eval_unfixable.rs
tests/ui/unnecessary_lazy_eval_unfixable.stderr

changelog: Fix unnecessary_lazy_eval suggestion applicability when breaking type inference
Fixes #6240

Fix unnecessary_lazy_eval suggestion applicability

---

clippy_lints/src/non_copy_const.rs
tests/ui/borrow_interior_mutable_const/auxiliary/helper.rs
tests/ui/borrow_interior_mutable_const/enums.rs
tests/ui/borrow_interior_mutable_const/enums.stderr
tests/ui/borrow_interior_mutable_const/others.rs
tests/ui/borrow_interior_mutable_const/others.stderr
tests/ui/borrow_interior_mutable_const/traits.rs
tests/ui/borrow_interior_mutable_const/traits.stderr
tests/ui/declare_interior_mutable_const/enums.rs
tests/ui/declare_interior_mutable_const/enums.stderr
tests/ui/declare_interior_mutable_const/others.rs
tests/ui/declare_interior_mutable_const/others.stderr
tests/ui/declare_interior_mutable_const/traits.rs
tests/ui/declare_interior_mutable_const/traits.stderr

fixes #3962
fixes #3825
Hello,
It might not be a good idea to submit another relatively large PR while I have an opened PR; but, I've finished this anyway. This may be able to wait for months.
Note: the code uses the MIR interpreter, which the author of #3962 thought unlikely to be a solution. This might be over-engineering; but, I think it's important to be able to work with the 'http' crate (#3825). (And, I don't want to write a MIR visitor)
---
changelog: fix a false positive in two `interior_mutable_const` lints where a constant with enums gets linted
even if it uses a clearly unfrozen variant

"Respect" enums in `interior_mutable_const`

---

clippy_lints/src/await_holding_invalid.rs

- Remove redundant `()`
- Fix variable name

Fix `await_holding_refcell_ref` examples for clarify

---

clippy_lints/src/methods/mod.rs

Fixes #6302
changelog: fix unwrap of None when checking libcore with clippy

FROM_ITER_INSTEAD_OF_COLLECT: avoid unwrapping unconditionally

---

clippy_lints/src/map_clone.rs
tests/ui/map_clone.fixed
tests/ui/map_clone.rs

fixes #6299 
changelog: do not trigger map_clone in the case of &mut

do not trigger map_clone in the case of &mut

---

clippy_lints/src/loops.rs
clippy_lints/src/utils/mod.rs
tests/ui/crashes/ice-360.stderr
tests/ui/empty_loop.stderr
tests/ui/empty_loop_no_std.rs
tests/ui/empty_loop_no_std.stderr

Depends on #6162. Fixes #6161 
We skip the lint if the `loop {}` is in the `#[panic_handler]` as the
main recommendation we give is to panic, which obviously isn't
possible in a panic handler.
changelog: Enable empty_loop lint for no_std crates

Enable empty_loop lint for no_std crates

---

clippy_lints/src/types.rs
tests/ui/vec_box_sized.fixed
tests/ui/vec_box_sized.rs
tests/ui/vec_box_sized.stderr

changelog: Fix vec_box suggestion with wrong type scope
Fixes #6236

Fix vec_box scope error

---

clippy_lints/src/cargo_common_metadata.rs

The previous example used in `cargo_common_metadata`  included an authors field, even though the comment says it doesn't. And thus doesn't actually demonstrate an example of how the lint fails.
This removes that authors field from the _bad_ example and suggest to fix the _bad_ example by adding the authors field
changelog: Fix example used in `cargo_common_metadata`

Fix example used in cargo_common_metadata

---

.github/PULL_REQUEST_TEMPLATE.md

Require the `changelog:` entry in the PR body to be modified

---

clippy_lints/src/methods/mod.rs
clippy_lints/src/utils/eager_or_lazy.rs
tests/ui/or_fun_call.fixed
tests/ui/or_fun_call.rs
tests/ui/or_fun_call.stderr

changelog: Fix or_fun_call for index operator
Fixes #6266

Fix or_fun_call for index operator

---

clippy_lints/src/reference.rs
clippy_lints/src/try_err.rs
tests/ui/deref_addrof.fixed
tests/ui/deref_addrof.rs
tests/ui/deref_addrof.stderr
tests/ui/try_err.fixed
tests/ui/try_err.rs
tests/ui/try_err.stderr

Fix bad suggestions when in macro expansion for `deref_addrof` and `try_err` lints.
Fixes: #6234 
Fixes: #6242 
Fixes: #6237 
r? @llogiq

Fix bad suggestions for `deref_addrof` and `try_err` lints

---

tests/ui/option_option.rs
tests/ui/option_option.stderr

As it is not triggering locally anymore, I propose to remove `#[allow(clippy::option_option)]` from the test.
The goal is also to see what happens on CI.
closes: #4298 

Remove `allow` in `option_option` lint test

---

clippy_lints/src/map_clone.rs
tests/ui/map_clone.fixed
tests/ui/map_clone.rs

changelog: Fix map_clone false positive with deref coercion
Fixes #6239

Fix map_clone with deref and clone

---

clippy_lints/src/reference.rs
tests/ui/crashes/ice-6332.rs

Remove `expect()` calls to avoid ICEs in `deref_addrof` lint

---

clippy_lints/src/map_clone.rs

A follow up of https://github.com/rust-lang/rust-clippy/issues/6239#issuecomment-719100677.
`map_clone` works with not only `Iterator` but `Option` although not written in [doc](https://rust-lang.github.io/rust-clippy/master/#map_clone). Also, an example in the doc shows  a usage of dereferencing, but this isn't also written.
changelog: Improve doc about `map_clone`

Improve doc about `map_clone`

---

tests/ui/cast_ref_to_mut.rs
tests/ui/cast_ref_to_mut.stderr

This reverts commit 0e803417f997ba35c0045704dd347e64c2a1786c.
Fixed by rustfmt v1.4.27 available in the latest nightly (2020-11-18). Refer to https://github.com/rust-lang/rustfmt/issues/4528.

Revert "Add `rustfmt::skip` as a work around"

---

CHANGELOG.md
doc/changelog_update.md

This changelog is **big**. Hacktoberfest was pretty good for us, even though we had too few reviewers.

Changelog Rust 1.48

---

clippy_lints/src/await_holding_invalid.rs
clippy_lints/src/lib.rs
src/lintlist/mod.rs

We found a false positive in these lints (see https://github.com/rust-lang/rust-clippy/issues/6353 for more details). As a short-term mitigation, this downgrades the lints from correctness to limit the noise.
changelog: downgrade AWAIT_HOLDING_REFCELL_REF and AWAIT_HOLDING_LOCK to pedantic. From rustup earlier, where I forgot the changlog: deprecate [`panic_params`] (uplifted)

Downgrade the await holding lints from correctness

---

clippy_lints/src/len_zero.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/regex.rs
clippy_lints/src/unit_return_expecting_ord.rs
clippy_lints/src/useless_conversion.rs
src/lintlist/mod.rs

changelog: Made small grammar, punctuation, and code style improvements to docs
I recently found some places in rust-lang/rust that had lists without spaces after commas, which led me to look for more places, which led me over here to find:
- Some similar lists in code examples that could use spaces after commas to be idiomatic Rust style
- Some lists in documentation text that didn't have spaces after commas, needed an Oxford comma (fight me), or were otherwise misformatted
- Some other grammar improvements in the area of the other changes
These changes should only be in user-facing documentation or output.

Small grammar, punctuation, and code style improvements to docs

---

tests/ui/as_conversions.rs
tests/ui/as_conversions.stderr
tests/ui/auxiliary/macro_rules.rs

Added external macros to this PR https://github.com/rust-lang/rust-clippy/pull/4888.
r? @llogiq 

Add exteranal macros for as_conversions

---

clippy_lints/src/types.rs
tests/ui/unnecessary_cast.rs

changelog: Disable unnecessary_cast for cfg-dependant types
Fix  #6331

Disable unnecessary_cast for cfg-dependant types

---

clippy_lints/src/loops.rs
tests/ui/needless_collect_indirect.rs

Fix https://github.com/rust-lang/rust-clippy/issues/5991
Fix https://github.com/rust-lang/rust-clippy/issues/6297
changelog: Fix FP in indirect `needless_collect` when used multiple times

Fix FP in indirect `needless_collect` when used multiple times

---

clippy_lints/src/deprecated_lints.rs
clippy_lints/src/lib.rs
clippy_lints/src/strings.rs
src/lintlist/mod.rs
tests/ui/deprecated.rs
tests/ui/deprecated.stderr
tests/ui/deprecated_old.rs
tests/ui/deprecated_old.stderr
tests/ui/str_to_string.rs
tests/ui/str_to_string.stderr
tests/ui/string_to_string.rs
tests/ui/string_to_string.stderr

changelog: un-deprecate [`str_to_string`] and [`string_to_string`] and introduce them as `restriction` lints again.
Fixes #5610 
Added new lint:- str_to_string
r? @flip1995

Added lint str_to_string

---

README.md

changelog: add some documentation for the `msrv` feature (#6097)
related PR: https://github.com/rust-lang/rust-clippy/pull/6201

update readme for specifying msrv

---

clippy_lints/src/types.rs
tests/ui/unnecessary_cast_fixable.fixed
tests/ui/unnecessary_cast_fixable.rs
tests/ui/unnecessary_cast_fixable.stderr

changelog: Fix rust-lang/rust#79255 - Incorrect try suggestion for float literal cast ending in dot

Fix rust-lang/rust#79255 - Incorrect try suggestion for float cast

---

README.md

As @taiki-e explained in https://github.com/rust-lang/rust-clippy/pull/6379#discussion_r530743279, mentioning this might be problematic.

Remove mention of possibility to specify the MSRV with a tilde/caret

---

clippy_lints/src/misc.rs
tests/ui/modulo_one.rs
tests/ui/modulo_one.stderr

Fixes #6321.
changelog: trigger `modulo_one` lint also on `-1`

Trigger modulo_one lint also on -1.

---

CHANGELOG.md
clippy_lints/src/eq_op.rs
clippy_lints/src/lib.rs
clippy_lints/src/suspicious_operation_groupings.rs
clippy_lints/src/utils/ast_utils.rs
clippy_lints/src/utils/ast_utils/ident_iter.rs
tests/ui/eq_op.rs
tests/ui/eq_op.stderr
tests/ui/suspicious_operation_groupings.rs
tests/ui/suspicious_operation_groupings.stderr

This is my (<del> currently WIP </del>) attempt to close #6039.
changelog: Added `suspicious_operation_groupings` lint.

Add suspicious_operation_groupings lint

---

clippy_lints/src/comparison_chain.rs

changelog: Added documentation to comparison_chain that explains a possible performance penalty, according to issue #5354
This is my first PR, I hope everything has been done correctly.
Fixes #5354

Added known problem to comparison_chain docs

---

clippy_lints/src/matches.rs

fixed #6289 
changelog: do not trigger MATCH_LIKE_MATCHES_MACRO lint for arms with attrs

do not trigger MATCH_LIKE_MATCHES_MACRO lint with attrs

---

clippy_lints/src/methods/mod.rs
clippy_lints/src/unnecessary_wraps.rs
clippy_lints/src/utils/mod.rs
tests/ui/unnecessary_wraps.rs

Fix #6384 
changelog: Fix FP in `unnecessary_wraps` that happens when `Call` expr has `Return` expr inside

Fix a false positive in `unnecessary_wraps`

---

clippy_lints/Cargo.toml
clippy_lints/src/lib.rs
clippy_lints/src/manual_non_exhaustive.rs
clippy_lints/src/manual_strip.rs
clippy_lints/src/matches.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/utils/mod.rs
tests/ui/min_rust_version_attr.rs
tests/ui/min_rust_version_attr.stderr
tests/ui/min_rust_version_no_patch.rs

add `rustc-semver` to dependencies
switch `Version/VersionReq` usages to `RustcVersion`

switch Version/VersionReq usages to RustcVersion 

---

CONTRIBUTING.md

changelog: CONTRIBUTING: update homu links to bors.rust-lang.org

CONTRIBUTING: update bors queue url from buildbot2.rlo to bors.rlo

---

clippy_lints/src/unnecessary_wraps.rs

Fixes: #6417 
changelog: Turn [`unnecessary_wraps`] applicability to `MaybeIncorrect`

Turn unnecessary_wraps applicability to MaybeIncorrect

---

clippy_lints/src/doc.rs
clippy_lints/src/missing_const_for_fn.rs
clippy_lints/src/needless_pass_by_value.rs
clippy_lints/src/pass_by_ref_or_value.rs
clippy_lints/src/redundant_clone.rs
clippy_lints/src/types.rs
clippy_lints/src/unnecessary_wraps.rs
clippy_lints/src/utils/ast_utils.rs
clippy_lints/src/utils/mod.rs
clippy_lints/src/utils/usage.rs
tests/ui/unnecessary_lazy_eval_unfixable.rs

Fix https://github.com/rust-lang/rust-clippy/issues/6343
changelog: Fix FP in `unnecessary_lazy_evaluations`

Fix FP in `unnecessary_lazy_evaluations`

---

clippy_lints/src/panic_in_result_fn.rs
clippy_lints/src/utils/mod.rs
tests/ui/panic_in_result_fn.stderr
tests/ui/panic_in_result_fn_assertions.rs
tests/ui/panic_in_result_fn_assertions.stderr
tests/ui/panic_in_result_fn_debug_assertions.rs
tests/ui/panic_in_result_fn_debug_assertions.stderr

Add lint for assertions in functions returning Result

---

CHANGELOG.md
clippy_lints/src/functions.rs
clippy_lints/src/len_zero.rs
clippy_lints/src/lib.rs
clippy_lints/src/matches.rs
clippy_lints/src/methods/unnecessary_filter_map.rs
clippy_lints/src/non_expressive_names.rs
clippy_lints/src/redundant_else.rs
tests/ui/redundant_else.rs
tests/ui/redundant_else.stderr

changelog: Add redundant_else lint
It seemed appropriate for "pedantic".
Closes #112 \*blows off dust*

Add Redundant else lint

---

CHANGELOG.md
clippy_lints/src/lib.rs
clippy_lints/src/write.rs
tests/ui/eprint_with_newline.rs
tests/ui/eprint_with_newline.stderr
tests/ui/print_stderr.rs
tests/ui/print_stderr.stderr
tests/ui/println_empty_string.fixed
tests/ui/println_empty_string.rs
tests/ui/println_empty_string.stderr

Resolves #6348
Almost identical to print_stdout, this lint applies to the `eprintln!` and `eprint!` macros rather than `println!` and `print!`.
changelog: Add new lint [`print_stderr`]. [`println_empty_string`] and [`print_with_newline`] now apply to `eprint!()` and `eprintln!()` respectively.

Add lint print_stderr

---

README.md
clippy_workspace_tests/path_dep/Cargo.toml
clippy_workspace_tests/path_dep/src/lib.rs
clippy_workspace_tests/subcrate/Cargo.toml
src/driver.rs
src/main.rs
tests/dogfood.rs

Since rust-lang/cargo#8758 has hit nightly, this allows us to address the second bullet point and [the concern related to `--fix`](https://github.com/rust-lang/cargo/issues/8143#issuecomment-619289546) in the [RUSTC_WORKSPACE_WRAPPER tracking issue](https://github.com/rust-lang/cargo/issues/8143). 
As a reminder stabilizing that env var will solve #4612 (Clippy not running after `cargo check` in stable) and would allow to stabilize the `--fix` option in Clippy.
changelog: Add `--no-deps` option to avoid running on path dependencies in workspaces
Fixes #3025

Add --no-deps option to avoid running on path dependencies in workspaces

---

clippy_lints/src/checked_conversions.rs
clippy_lints/src/lib.rs
clippy_lints/src/mem_replace.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/missing_const_for_fn.rs
clippy_lints/src/ranges.rs
clippy_lints/src/redundant_field_names.rs
clippy_lints/src/redundant_static_lifetimes.rs
clippy_lints/src/use_self.rs
doc/adding_lints.md
tests/ui/min_rust_version_attr.rs
tests/ui/min_rust_version_attr.stderr

add MSRV to more lints specified in #6097
add instructions for adding msrv in other lints
update tests
changelog: Add MSRV config to more lints. ^This is now the complete list, AFAWK

Add MSRV to more lints specified in #6097

---

clippy_lints/src/ranges.rs
tests/ui/range_contains.fixed
tests/ui/range_contains.rs

Fix #6373.
changelog: Fix FP of `manual_range_contains` in `const fn`

Fix FP of `manual_range_contains` in `const fn`

---

clippy_lints/src/missing_doc.rs
tests/ui/missing-doc-crate-missing.stderr
tests/ui/missing-doc-impl.stderr

Moves closer to the current rustc missing_doc lint

Use article_and_description for missing docs

---

clippy_lints/src/methods/mod.rs
tests/ui/unnecessary_clone.stderr

changelog: clone_double_ref: print the type of the reference in lint message

clone_double_ref: print reference type in lint message

---

Cargo.toml
README.md
src/driver.rs
src/main.rs
tests/dogfood.rs

This removes a hack (\_\_CLIPPY_HACKERY\_\_) to add another one :)
It allows this workflow to work:
```terminal
cargo clippy                             # warning: empty `loop {}` wastes CPU cycles
cargo clippy -- -A clippy::empty_loop    # no warnings emitted
```
Before this change the new flag was not taken into consideration in cargo's fingerprint and the warning was emitted again. I guess that ideally we could add a specific env var for compiler wrapper arguments, but in the meantime this should do the job.
changelog: Pass clippy arguments through RUSTFLAGS so that changing them will trigger a rebuild
r? @flip1995
cc @ehuss (I think this may count as another step towards stabilizing `RUSTC_WORKSPACE_WRAPPER` :smile:)
Fixes #5214 and avoids frustration for users unfamiliar with the …

Pass Clippy args also trough RUSTFLAGS

---

clippy_lints/src/methods/mod.rs
tests/ui/clone_on_copy.stderr
tests/ui/unnecessary_clone.stderr

changelog: clone_on_copy: show the type in the lint message

clone_on_copy: show the type in the lint message

---

clippy_lints/src/needless_borrow.rs
tests/ui/eta.stderr
tests/ui/needless_borrow.stderr

changelog: needless_borrow: print type in lint message

needless_borrow: print the type in the lint message

---

CONTRIBUTING.md
clippy_dev/src/fmt.rs
clippy_dev/src/main.rs
clippy_dev/src/ra_setup.rs
doc/basics.md

It turns out that rustfmt sees a rustc repo that we pulled in as path dependency via `cargo dev ra-setup` as part of the tree and would try to format it :D
Of course we don't want this, so skip formatting if we see that we ran `ra-setup` previously. 

cargo dev fmt: don't format entire rustc repo if we ran ra_setup previously

---

clippy_lints/src/matches.rs
tests/ui/match_single_binding.fixed
tests/ui/match_single_binding.rs
tests/ui/match_single_binding.stderr

This is a fix for a false positive in the `match_single_binding` lint when using `#[cfg()]` on a branch. It is sadly a bit hacky but maybe the best solution as rust removes the other branch from the AST before we can even validate it. This fix looks at the code snippet itself and returns if it includes another thick arrow `=>` besides the one matching arm we found. This can again cause false negatives if someone has the following code:
```rust
match x {
// => <-- Causes a false negative
_ => 1,
}
```
I thought about making the code more complex and maybe validating against other things like the `#[cfg()]` macro but I believe that this is the best solution. This has basically switched the issue from a false positive to a false negative in a very specific case.
I'm happy to make some …

Fixing a false positive for the `match_single_binding` lint #5552

---

rust-toolchain

This should hopefully fix incremental compilation ICEs in rustc that I have encountered multiple times while working with the previously pinned nightly.

bump pinned nightly from nightly-2020-12-09 to nightly-2020-12-14

---

clippy_lints/src/create_dir.rs

Typo in create_dir doc comment

---

clippy_lints/src/doc.rs
clippy_lints/src/lib.rs
tests/ui/needless_doc_main.rs

Before this change, finding an error when parsing a doctest would make Clippy exit without emitting an error. Now we properly catch a fatal error and ignore it.
Also, if a doctest specifies an edition in the info line, it will be used when parsing it.
changelog: needless_doctest_main: handle correctly parse errors
Fixes #6022

needless_doctest_main: handle correctly parse errors

---

triagebot.toml

The `good first issue` label got renamed to `good-first-issue`. See [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Rename.20the.20.22good.20first.20issue.22.20label.20for.20bot.20usage/near/220428379) to enable the assignment with rustbot.
r? @flip1995

Renamed the good first issue label for rustbot

---

CONTRIBUTING.md

Follow up from #6468 
Grep found some more references to the old `good first issue`.
[CONTRIBUTING.md rendered](https://github.com/xFrednet/rust-clippy/blob/0000-rename-good-first-issue-in-docs/CONTRIBUTING.md)
<details>
<summary>grep output</summary>
```
$ grep -Ri "good first issue" rust-clippy/
rust-clippy/.git/COMMIT_EDITMSG:Renamed the good first issue label in CONTRIBUTING.md
rust-clippy/.git/logs/HEAD:896d82f7ff64644656bda7a4ed8bbd55ca3b7619 1f58c2bb8a638a63edc1f3503c8771937aa19157 xFrednet <xFrednet@gmail.com> 1608326295 +0000     commit: Renamed the good first issue label for rustbot
rust-clippy/.git/logs/HEAD:9be704584f05e5a6c3ba2708590f98c1f261d19a ced54f28671ddb9ccf9b44131d522f4fdeab7097 xFrednet <xFrednet@gmail.com> 1608329602 +0000     commit: Renamed the good first issue …
```

Renamed the good first issue label in CONTRIBUTING.md

---

clippy_lints/src/needless_update.rs
tests/ui/needless_update.rs
tests/ui/needless_update.stderr

changelog: make `needless_update` lint ignore `non_exhaustive` structs
fixes #6323

make needless_update ignore non_exhaustive structs

---

clippy_dev/src/bless.rs

Adding of new reference files wasn't handled correctly. It was trying to
read a file that didn't exist yet.
Instead of unwrapping, we now treat a missing reference file as empty
(`Vec::new`). This makes the following conditional work. We then also
have to re-read the reference file after it was being copied. This
second read is technically the same as in the old shell script, but
wasn't really obvious there. The shell script did a `-s` test which
reads the file as well.
changelog: internal: Fix `cargo dev bless` when new reference files are added

Fix blessing of new reference files

---

tests/ui/formatting.rs
tests/ui/formatting.stderr
tests/ui/suspicious_else_formatting.rs
tests/ui/suspicious_else_formatting.stderr

Was briefly looking into https://github.com/rust-lang/rust-clippy/issues/3864 when I saw that the tests could benefit from being in their own file.
---

UI Tests: Separate suspicious_else_formatting tests

---

clippy_lints/src/methods/mod.rs
tests/ui/use_self.fixed
tests/ui/use_self.rs
tests/ui/use_self.stderr
tests/ui/wrong_self_convention.rs
tests/ui/wrong_self_convention.stderr

Extends `wrong_self_convention` to lint also in trait definition.
By the way, I think the `wrong_pub_self_convention` [example](https://github.com/rust-lang/rust-clippy/blob/dd826b4626c00da53f76f00f02f03556803e9cdb/clippy_lints/src/methods/mod.rs#L197) is misleading.
On [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=32615ab3f6009e7e42cc3754be0ca17f), it fires `wrong_self_convention`, so the example (or the lint maybe?) needs to be reworked.
The difference with `wrong_self_convention` [example](https://github.com/rust-lang/rust-clippy/blob/dd826b4626c00da53f76f00f02f03556803e9cdb/clippy_lints/src/methods/mod.rs#L172) is mainly the `pub` keyword on the method `as_str`, but the lint doesn't use the function visibility as condition to choose which lint to …

Lint also in trait def for `wrong_self_convention`

---

util/gh-pages/index.html

* This adds the ability to search for ids with dashes and spaces in the name. 
* Example: `missing-errors-doc` and `missing errors doc` are now valid aliases for lint names
* It also improves the fuzzy search in the description. This search will now match any lint that where all searched words are inside the description.
* Example: `doc section` finds two lints in our selection
This was suggested/discussed on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Enable.20lint.20search.20with.20dashes/near/220469464)
These changes can be tested locally by:
1. Clone this branch
2. Download the current lint index from the [gh-pages branch](https://github.com/rust-lang/rust-clippy/blob/gh-pages/master/lints.json)
3. Put it next to the `util/gh-pages/index.html` and open …

Adapted the website search for better matching

---

README.md

Clippy should always be available on nightly because we are gating on it in rustcs CI.
changelog: remove outdated readme paragraph

readme: remove paragraph about installing clippy manually on ci, if it is missing on a nightly

---

clippy_lints/src/large_enum_variant.rs
tests/ui/auxiliary/macro_rules.rs
tests/ui/large_enum_variant.rs
tests/ui/large_enum_variant.stderr

Closes #1776 (the potential JSON output issue is not something we can fix in Clippy and I can't reproduce it anymore)
changelog: Don't trigger [`large_enum_variant`] in external macros

Don't trigger large_enum_variant in external macros

---

CHANGELOG.md
clippy_lints/src/from_over_into.rs
clippy_lints/src/lib.rs
tests/ui/from_over_into.rs
tests/ui/from_over_into.stderr
tests/ui/min_rust_version_attr.rs
tests/ui/min_rust_version_attr.stderr
tests/ui/unused_unit.fixed
tests/ui/unused_unit.rs
tests/ui/unused_unit.stderr

Closes #6456
Added a lint that searches for implementations of `Into<..>` and suggests to implement `From<..>` instead, as it comes with a default implementation of `Into`. Category: style.
changelog: added `from_over_into` lint

Added from_over_into lint

---

README.md

This most likely no longer works since we are pinning clippy on a specific nightly now.
"cargo run" would try to compile clippy with whatever version the project we want to check demands.
Also building clippy yourself to run it on a project is not really needed anymore since clippy is shipped with official rust releases.
Fixes #6489

readme: remove paragraph about executing clippy via "cargo run .."

---

Cargo.toml
README.md
src/driver.rs
src/main.rs
tests/dogfood.rs

Reverts rust-lang/rust-clippy#6441
r? @ebroto 
changelog: Revert "Pass Clippy args also trough RUSTFLAGS"

Revert "Pass Clippy args also trough RUSTFLAGS"

---

.github/workflows/clippy.yml

Make sure we catch cases like https://github.com/rust-lang/rust-clippy/issues/6487 in CI in the future.
---

ci: test cargo clippy --fix -Zunstable-options

---

util/gh-pages/index.html

This PR implements some improvements to the website:
1. Added a "Search on Github" link to the "Known problems" section (Closes #5386)
<details>
<summary>Another mock up I created with the GitHub logo</summary>
</details>
2. Only starting the search after three letters and improving the search performance in general. (Followup #6477)
These changes can be tested locally by:
1. Clone this branch
2. Download the current lint index from the [gh-pages branch](https://github.com/rust-lang/rust-clippy/blob/gh-pages/master/lints.json)
3. Put it next to the `util/gh-pages/index.html` and open the html file. Make sure that it can load the lint data. (Browsers can be a bit iffy when opening a local html page and loading data)
1. [A stackoverflow about angular filter …

Website issue tracker link and better search performance

---

.github/workflows/clippy.yml

Turned out the --fix test was run in the wrong directory.

fix ci on master branch; run the --fix test in the correct directory

---

clippy_lints/src/map_err_ignore.rs
tests/ui/map_err.stderr

Fix a style of texts in `map_err_ignore`

---

.github/ISSUE_TEMPLATE/false_negative.md
.github/ISSUE_TEMPLATE/false_positive.md

These will add the correct labels automatically so we don't have to do that ourselves :) 

ISSUE_TEMPLATE: add templates for false negative and false positive tickets.

---

clippy_lints/src/default.rs
tests/ui/field_reassign_with_default.rs
tests/ui/field_reassign_with_default.stderr

changelog: fix field_reassign_with_default false positive
* Fix #6344
* Fix assumption that `field: Default::default()` is the same as `..Default::default()`
* Cleanup some redundant logic

Reassign default private

---

clippy_dev/src/ra_setup.rs
clippy_lints/src/ptr.rs
tests/ui/ptr_arg.rs
tests/ui/ptr_arg.stderr

fixes #6502 
changelog: lint "`&PathBuf` instead of `&Path`" in `PTR_ARG`

Lint "&PathBuf instead of &Path" in PTR_ARG

---

clippy_lints/src/utils/ptr.rs
tests/ui/ptr_arg.rs
tests/ui/ptr_arg.stderr

don't ignore expression after first not matched method call in PtrCloneVisitor

---

Cargo.toml
clippy_lints/Cargo.toml
tests/versioncheck.rs

clippy 0.1.50 corresponds to rustc 1.50.x
This bumps the clippy version number from 0.0.212 to 0.1.50
Fixes #6499
Notes:
I used `cargo --version` because that way we can honour the version set in the `rust-toolchain` file.
When we bump the bootstrap compiler from 1.50 to 1.51, the version numbers will have to be changed to 1.51 or the test will fail.
---
changelog: make clippy version number correspond to rustc version number (rust 1.50.0 -> clippy 0.1.50)

make clippy version number correspond to rustc version number.

---

clippy_lints/src/macro_use.rs
clippy_lints/src/single_component_path_imports.rs

Clippy treated Rust 2021 as Rust 2015, because 2018 was checked with `==` instead of `>=`. This fixes that, such that 2018-specific things are also enabled for 2021.
changelog: Added support for Rust 2021.

Initial support for Rust 2021.

---

CHANGELOG.md

Update CHANGELOG for Rust 1.50

---

clippy_lints/src/default.rs
tests/ui/field_reassign_with_default.rs
tests/ui/field_reassign_with_default.stderr

fixes #6522
changelog: field_reassign_with_default: don't expand macros in lint suggestion (#6522)

field_reassign_with_default: don't expand macros in suggestion

---

clippy_lints/src/default.rs
tests/ui/field_reassign_with_default.rs
tests/ui/field_reassign_with_default.stderr

With the pinned nightly we can test backports to our beta branch now :tada: 
cc #6515
changelog: beta 1.50: Backport of private fields fix in [`field_reassign_with_default`] lints

[beta] Backport of #6375 - field_reassign_with_default fix

---

clippy_dev/src/bless.rs

The core issue was the usage of `reference_file_path.file_name()`, which
provided a non-existent path if the file to be updated was in a
subdirectory.
Instead we have to provide the whole path after 'tests/ui/' as the
'filename'. This part of the path is called `test_name` in the code now.

Fix blessing of test output in subdirectories

---

CHANGELOG.md
clippy_lints/src/lib.rs
clippy_lints/src/needless_question_mark.rs
tests/ui/needless_question_mark.fixed
tests/ui/needless_question_mark.rs
tests/ui/needless_question_mark.stderr
tests/ui/try_err.fixed
tests/ui/try_err.rs
tests/ui/unit_arg.rs
tests/ui/unit_arg.stderr

Fixes #6410, i.e the needless question mark lint
changelog: [`needless_question_mark`] New lint

Needless Question Mark Lint

---

CHANGELOG.md
clippy_lints/src/lib.rs
clippy_lints/src/vec_init_then_push.rs
tests/ui/clone_on_copy.fixed
tests/ui/clone_on_copy.rs
tests/ui/clone_on_copy.stderr
tests/ui/vec_init_then_push.rs
tests/ui/vec_init_then_push.stderr

fixes: #1483
This will trigger on `new`, `default`, and `with_capacity` when the given capacity is less than or equal to the number of push calls. Is there anything else this should trigger on?
changelog: Added lint: `vec_init_then_push`

New lint: vec_init_then_push

---

clippy_dev/src/bless.rs
clippy_dev/src/main.rs

changelog: internal
Change `cargo dev bless` to only include test output that was generated since the last build of clippy. This is especially useful when running tests with `TESTNAME=...`. The feature may be disabled by `cargo dev bless --ignore-timestamp`.

Curse outdated test output

---

CHANGELOG.md
clippy_lints/src/lib.rs
clippy_lints/src/types.rs
tests/ui/ptr_as_ptr.fixed
tests/ui/ptr_as_ptr.rs
tests/ui/ptr_as_ptr.stderr

This PR adds a new lint `ptr_as_ptr` which checks for `as` casts between raw pointers without changing its mutability and suggest replacing it with `pointer::cast`. Closes #5890.
Open question: should this lint be `pedantic` or `style`? I set it `pedantic` for now because the original post suggests using it, but I think the lint also fits well to `style`.
---
changelog: New lint `ptr_as_ptr`

Add a new lint `ptr_as_ptr`

---

clippy_lints/src/utils/mod.rs
clippy_lints/src/utils/sym_helper.rs

* Renames `sym.rs` to `sym_helper.rs` so that the `sym as rustc_sym` is no longer needed.
* Removes one needless `symbol` from a path

Tiny Symbol cleanup

---

clippy_lints/src/default.rs
clippy_lints/src/needless_borrow.rs
tests/ui/auxiliary/macro_rules.rs
tests/ui/auxiliary/proc_macro_derive.rs
tests/ui/field_reassign_with_default.rs
tests/ui/field_reassign_with_default.stderr

Closes #6545 
changelog: Fix derive and macro related false positives in [`field_reassign_with_default`]

Fix derive and macro related false positives in `field_reassign_with_default`

---

clippy_lints/src/pass_by_ref_or_value.rs

Fixed a typo in the explanation of https://rust-lang.github.io/rust-clippy/master/index.html#large_types_passed_by_value : `which which can be` -> `which can be`

Fix typo: `which which can be` -> `which can be`

---

clippy_lints/src/ref_option_ref.rs

Fix typo: `irrevelent` -> `irrelevant`

---

clippy_lints/src/from_over_into.rs
tests/ui/from_over_into.stderr

A follow up of https://github.com/rust-lang/rust-clippy/pull/6476#discussion_r546271382
> That item might be quite large. We may want to reduce the span to the `impl` header.

Reduce the span in `from_over_into` to impl header

---

clippy_lints/src/escape.rs
tests/ui/escape_analysis.rs
tests/ui/escape_analysis.stderr

Fix FP on default trait function implementation on `boxed_local` lint.
Maybe I checked too much when looking if `self` is carrying `Self` in its bound type.
I can't find a good test case for this, so it could be too much conservative.
Let me know if you think only detecting `self` parameter is enough.
Fixes: #4804 

Fix FP for `boxed_local` lint in default trait fn impl

---

doc/adding_lints.md
src/driver.rs
tests/compile-test.rs

This changes the variable used for testing Clippy in the internal test
suite:
```
CLIPPY_TESTS -> __CLIPPY_INTERNAL_TESTS
```
`CLIPPY_TESTS` is understandably used in environments of Clippy users,
so we shouldn't use it in our test suite.
changelog: Fix oversight which caused Clippy to lint deps in some environments.
Once again fixes https://github.com/rust-lang/rust-clippy/issues/3874

Change env var used for testing Clippy

---

clippy_lints/src/types.rs
clippy_lints/src/utils/mod.rs
tests/ui/cast_alignment.rs
tests/ui/cast_alignment.stderr

Fixes #4708
Although there were some discussion in the issue, this PR implements the original feature. I think `cast_ptr_alignment` should exist as it is, separated from `ptr_as_ptr`.
---
changelog: Extend `cast_ptr_alignment` lint for the `pointer::cast` method

Catch `pointer::cast` too in `cast_ptr_alignment`

---

doc/roadmap-2021.md

[Rendered](https://github.com/flip1995/rust-clippy/blob/roadmap/doc/roadmap-2021.md)
This is the first time Clippy gets its own roadmap. The reason for this roadmap is, that with the Rust language growing, also Clippy is growing. With this keeping track of and implementing bigger projects gets quite hard. This roadmap should help in exactly this regard.
After having the approval of this roadmap by the Clippy team, we want to know from the community:
- What do you think in general about this roadmap?
- Are there any pain points in Clippy, that should be included here?
- What of the points listed here has the highest priority for you?
We're looking forward to getting your feedback!
changelog: Add roadmap for Clippy 2021
r? @rust-lang/clippy

Roadmap for 2021

---

clippy_lints/src/comparison_chain.rs
clippy_lints/src/eta_reduction.rs
clippy_lints/src/loops.rs
clippy_lints/src/types.rs
clippy_lints/src/use_self.rs

I think it's incovenient that references in doc are just a text.

Make a reference a link in doc

---

clippy_lints/src/matches.rs
clippy_lints/src/utils/mod.rs
tests/ui/single_match.rs
tests/ui/single_match.stderr
tests/ui/single_match_else.stderr

fixes: #173
changelog: single_match: suggest `if` over `if let` when possible

single_match: suggest `if` over `if let` when possible

---

CHANGELOG.md
clippy_lints/Cargo.toml
clippy_lints/src/case_sensitive_file_extension_comparisons.rs
clippy_lints/src/lib.rs
tests/compile-test.rs
tests/ui/case_sensitive_file_extension_comparisons.rs
tests/ui/case_sensitive_file_extension_comparisons.stderr

Closes #6425
Looks for ends_with methods calls with case sensitive extension comparisons.
changelog: Add new lint that warns about case-sensitive file extension comparisons.

Case sensitive file extensions

---

clippy_lints/src/returns.rs
tests/ui/needless_return.fixed
tests/ui/needless_return.rs
tests/ui/needless_return.stderr

This fixes a false positive in `needless_return` lint, when triggered in a closure using `return` statement without value.
Fixes: #6501 

Fix FP with empty return for `needless_return` lint

---

clippy_lints/src/zero_sized_map_values.rs
tests/ui/crashes/ice-6539.rs

Fixes #6539
It happened because `zero_sized_map_values` used `layout_of` with types from type aliases, which is essentially the same as the ICE 4968.
---
changelog: Fix an ICE in `zero_sized_map_values`

Fix the ICE 6539

---

CHANGELOG.md
clippy_lints/src/lib.rs
clippy_lints/src/map_unit_fn.rs
clippy_lints/src/redundant_slicing.rs
tests/ui/redundant_slicing.rs
tests/ui/redundant_slicing.stderr

changelog: Added lint: `redundant_slicing`
fixes #6519
This will trigger on any type which implements `Index<RangeFull>` that returns the input type. This would be a false positive if the implementation does something other than return itself, but I'm not sure why you would ever want to do that.

New lint: redundant_slicing

---

clippy_lints/src/await_holding_invalid.rs

Adds documentation for known false positives for the `await_holding*` lints.
Issues:
https://github.com/rust-lang/rust-clippy/issues/6353
https://github.com/rust-lang/rust-clippy/issues/6446
changelog: document FPs for the ``await_holding_*`` lints

Explicitly document false positives

---

tests/ui/needless_return.fixed
tests/ui/needless_return.rs
tests/ui/needless_return.stderr

Just a follow up of #6549 that adds a test for this lint.

Add test for `needless_return` lint

---

clippy_lints/src/as_conversions.rs

I have seen a couple of examples where there are some misunderstandings of `as_conversions` ([1](https://github.com/rust-lang/rust-clippy/issues/5890#issuecomment-671852546), [2](https://github.com/rust-lang/rust-clippy/issues/6116#issuecomment-704251710) and [3](https://github.com/rust-lang/rust-clippy/issues/6428)). This PR adds the note that explains its purpose and relationship with other `as` related casts. Open question: should I list every related lints for discoverbility, or just suggest how to find these? I chose the former because there's no way to list only and all `as` related lints (e.g. on All the Clippt Lints, 'cast' includes some noises, but `cast_` excludes some) even though I cannot guarantee the list will be updated to include future changes.
---
changelog: Add a note …

Add a note to `as_conversions`

---

clippy_lints/src/size_of_in_element_count.rs
tests/ui/size_of_in_element_count/expressions.rs
tests/ui/size_of_in_element_count/expressions.stderr
tests/ui/size_of_in_element_count/functions.rs
tests/ui/size_of_in_element_count/functions.stderr

Fixes #6511
It is fairly common to divide some length in bytes by the byte-size of a single element before creating a `from_raw_parts` slice or similar operation. This lint would erroneously disallow such expressions.
Just in case, instead of simply disabling this lint in the RHS of a division, keep track of the inversion and enable it again on recursive division.
---
changelog: Do not trigger size_of_in_element_count when dividing by element size

size_of_in_element_count: Disable lint on division by byte-size

---

clippy_lints/src/utils/mod.rs
tests/ui-internal/invalid_paths.rs

I tried to add `Option::is_some` to the paths but got a false positive from the invalid paths lint. Turns out the `path_to_res` function does not find inherent impls for enums. I fixed this and took the liberty to do some additional cleanup in the method.

Fix path_to_res for enum inherent items

---

clippy_lints/src/stable_sort_primitive.rs
tests/ui/stable_sort_primitive.stderr

Now Clippy emits `stable_sort_primitive` warning as follows:
```
warning: used sort instead of sort_unstable to sort primitive type `usize`
--> src\asm.rs:41:13
|
41 |             self.successors.sort();
|             ^^^^^^^^^^^^^^^^^^^^^^ help: try: `self.successors.sort_unstable()`
|
= note: `#[warn(clippy::stable_sort_primitive)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#stable_sort_primitive
```
I think the position of `sort` and `sort_unstable` in the first line should be reversed.
changelog: Fix the reversed suggestion message of `stable_sort_primitive`.

Fix the reversed suggestion message of `stable_sort_primitive`.

---

clippy_lints/src/write.rs
tests/ui/crashes/ice-3891.stderr
tests/ui/print_literal.rs
tests/ui/print_literal.stderr
tests/ui/write_literal.rs
tests/ui/write_literal.stderr

changelog: No longer lint numeric literals in [`write_literal`] and [`print_literal`].
Fixes #6335

Fix false positive in write_literal and print_literal (numeric literals)

---

clippy_lints/src/matches.rs
tests/ui/match_expr_like_matches_macro.fixed
tests/ui/match_expr_like_matches_macro.rs
tests/ui/match_expr_like_matches_macro.stderr

fixes #6503
changelog: match_like_matches_macro: strip refs in suggestion (#6503)

match_like_matches_macro: strip refs in suggestion

---

clippy_lints/src/reference.rs
tests/ui/unnecessary_ref.fixed
tests/ui/unnecessary_ref.rs
tests/ui/unnecessary_ref.stderr

Fix #6358.
changelog: Fix a wrong suggestion of `ref_in_deref`

Fix a wrong suggestion of `ref_in_deref`

---

clippy_lints/src/reference.rs

Add a suggested code to the example in doc

Improve the example in `ref_in_deref`

---

clippy_lints/src/collapsible_match.rs
clippy_lints/src/main_recursion.rs
clippy_lints/src/ptr.rs
clippy_lints/src/utils/higher.rs
clippy_lints/src/utils/mod.rs
tests/ui/collapsible_match2.rs
tests/ui/collapsible_match2.stderr

changelog: Fix collapsible_match false negatives
Allow `&` and/or `*` on the binding and make sure the type still matches.

Improve collapsible_match

---

clippy_lints/src/non_expressive_names.rs
tests/ui/similar_names.rs

changelog: Ignore underscore-prefixed names for similar_names
IMO, this lint is not very helpful for underscore-prefixed variables. Usually they are unused or are just there to ignore part of a destructuring.

Similar names ignore underscore prefixed names

---

doc/adding_lints.md
doc/basics.md

This PR adds some commonly used abbreviations to the `basis.md` file and a guide on how to implement a configuration value for a lint. 
* [Rendered `/doc/basics.md` (Abbreviation list)](https://github.com/xFrednet/rust-clippy/blob/0000-configuration-documentation/doc/basics.md#common-abbreviations)
* [Rendered `/doc/adding_lints.md` (Configuration value guide)](https://github.com/xFrednet/rust-clippy/blob/0000-configuration-documentation/doc/adding_lints.md#adding-configuration-to-a-lint)
I'm not sure if the guide is written in the best way. Style suggestions are appreciated. :upside_down_face: 
---
Again a big **thank you** for everyone who helped to collect the abbreviation list over on [zulip]. I had a lot of fun, and it was also very informative. Keep up the good work …

Documentation for adding configuration to a lint and common abbreviations

---

util/export.py

Fix syntax highlighting on website when the docs contain ` ```rust,ignore`

Fix website syntax highlighting

---

clippy_lints/Cargo.toml
clippy_lints/src/case_sensitive_file_extension_comparisons.rs
clippy_lints/src/utils/diagnostics.rs

r? @llogiq 
#6500 
regex is unnecessary for this lint (https://github.com/rust-lang/rust-clippy/pull/6500#discussion_r558555071)
lazy_static is unnecessary. The std lazy feature should be  used instead.

No lazy static regex

---

clippy_dev/src/fmt.rs

This improves error reporting when running `rustfmt` fails for some reason, as seen [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Issue.20with.20rustfmt). It will now include the stderr output in the `CliError::CommandFailed` error.

clippy_dev: Pass stderr to CommandFailed

---

clippy_lints/src/matches.rs
tests/ui/match_overlapping_arm.rs
tests/ui/match_overlapping_arm.stderr

This fix has been developed following this [comment](https://github.com/rust-lang/rust-clippy/issues/5986#issuecomment-703313548).
So this will be linted:
```
|----------|
|-----------|
```
Now this won't be linted:
```
|---|
|--------------------|
```
and this will still lint:
```
|--------|
|--------------|
```
Fixes: #5986 
changelog: Fix FPs in match_overlapping_arm, when first arm is completely included in second arm

Do not lint when range is completely included into another one

---

clippy_lints/src/exhaustive_items.rs
tests/ui/exhaustive_items.fixed
tests/ui/exhaustive_items.rs
tests/ui/exhaustive_items.stderr

changelog: Restrict `exhaustive_structs` to structs with all-public
fields

exhaustive_structs: don't trigger for structs with private fields

---

clippy_lints/src/utils/mod.rs
tests/ui/let_and_return.rs
tests/ui/let_and_return.stderr

The issue:
See this Rust playground link: https://play.rust-lang.org/?edition=2018&gist=12cb5d1e7527f8c37743b87fc4a53748
Run the above with clippy to see the following warning:
```
warning: returning the result of a `let` binding from a block
--> src/main.rs:24:5
|
23 |     let value = Foo::new(&x).value();
|     --------------------------------- unnecessary `let` binding
24 |     value
|     ^^^^^
|
= note: `#[warn(clippy::let_and_return)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#let_and_return
help: return the expression directly
|
23 |
24 |     Foo::new(&x).value()
|
```
Implementing the suggested fix, removing the temporary let binding,
yields a compiler error:
```
error[E0597]: `x` does not live long enough
--> …
```

Fix let_and_return false positive

---

clippy_lints/src/utils/internal_lints.rs
clippy_lints/src/utils/mod.rs

Tiny cleanup for `path_to_res` to return `Res` instead of `Option<Res>`.

Remove Option from `path_to_res` return type

---

CONTRIBUTING.md
doc/adding_lints.md
doc/basics.md

I've implemented the two suggestions from #6630 that were added after the merge. This PR also changes the example code to use `register_*_pass` instead of `register_late_pass`. I'm not sure if this is better or worse, but it makes it clearer in my opinion. Let me know if I should change it back.
---
r? @flip1995

Updated some NITs in the documentation from #6630

---

clippy_dev/src/ra_setup.rs

This will convert the path to the Rust repo to an absolute path. This is
important for the clippy_lints/Cargo.toml file. Otherwise if a relative
path is passed, rst-analyzer won't find the Rust repo, because it starts
the relative path search from the clippy_lints dir, not the
rust-clippy dir where the ra_setup command was run from.

Use absolute path to Rust repo in ra_setup

---

tests/versioncheck.rs

Do not check if clippy version matches rustc version when runnning tests inside the rustc repo.
This makes sure that upstream rustc maintainers do not have to deal with our test failing/mismatching versions
when the rustc version bump is happening.
cc #6683
We already do the "don't run inside the rustc-repo" workaround for the dogfood test:
https://github.com/rust-lang/rust-clippy/blob/a507c27660d05f37307369d30bee9e82ce3a11e1/tests/dogfood.rs#L16

tests: ignore check_that_clippy_has_the_same_major_version_as_rustc()inside the rustc repo

---

clippy_dev/src/serve.rs
clippy_lints/src/let_underscore.rs
clippy_lints/src/macro_use.rs
src/main.rs
tests/ui/let_underscore_drop.rs

changelog: Fix let_underscore_drop false positives and negatives
Fixes #6633

Fix let_underscore_drop FP

---

triagebot.toml

Update triagebot.toml to new label names

---

clippy_lints/src/collapsible_match.rs
clippy_lints/src/eval_order_dependence.rs
clippy_lints/src/functions.rs
clippy_lints/src/let_if_seq.rs
clippy_lints/src/loops.rs
clippy_lints/src/manual_ok_or.rs
clippy_lints/src/manual_unwrap_or.rs
clippy_lints/src/matches.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/unnecessary_filter_map.rs
clippy_lints/src/to_string_in_display.rs
clippy_lints/src/utils/mod.rs
clippy_lints/src/utils/usage.rs
clippy_lints/src/utils/visitors.rs

It seemed like too much ceremony going on to check if an expression matches a variable. So I created two util functions `path_to_local(Expr) -> Option<HirId>` and `path_to_local_id(Expr, HirId) -> bool` to make this easier, and used them wherever applicable.
I changed logic in a few places to use `HirId` instead of `Symbol` where it was easy to do so. I believe this is more correct and may even fix some bugs.
I also removed some calls to `qpath_res`. This is not needed if you are only looking for a `Res::Local`.
As a note, I wanted to name the util functions in a way that encourages understanding of the HIR.

Cleanup path-to-local checks

---

clippy_lints/src/disallowed_method.rs
clippy_lints/src/utils/conf.rs
tests/ui-toml/toml_disallowed_method/clippy.toml
tests/ui-toml/toml_disallowed_method/conf_disallowed_method.rs
tests/ui-toml/toml_disallowed_method/conf_disallowed_method.stderr

Hey all! I have a particular use case where I'd like to ban certain functions in a code base I work on. For example, I want to ban `Instant::now()` (among others) as we have a time service for mocking time in deterministic simulation tests. Obviously, it doesn't make sense to include a lint like this for all clippy users. Imagine my excitement when I spotted the new `disallowed_methods` lint in clippy--perfect! Unfortunately, after playing around with it for a bit, I was frustrated to realize that it didn't support functions like `Instant::now()`, so I've added support for them in this PR.
It might also make sense to rename the lint from `disallowed_methods` -> `disallowed_functions`, though I've held off from including that rename in this change, since I'm unsure of clippy's breaking …

disallowed_methods: Support functions in addition to methods

---

clippy_dev/src/lintcheck.rs
clippy_dev/src/main.rs

Fixes #6691
changelog: lintcheck: add --crates-toml  cmdline option to override default crates.toml file.

lintcheck: add a cmdline option --crates-toml <TOML PATH> to override crate sources file to use.

---

rust-toolchain

We use latest nightly rustfmt in our tests anyway

Remove rustfmt from rust-toolchain file

---

clippy_lints/src/collapsible_match.rs
clippy_lints/src/let_if_seq.rs
clippy_lints/src/loops.rs
clippy_lints/src/matches.rs
clippy_lints/src/methods/filter_map_identity.rs
clippy_lints/src/unused_self.rs
clippy_lints/src/utils/visitors.rs
tests/ui/collapsible_match.rs

changelog: Fix some detections of variable usage in closures

More path-to-local fixes

---

src/main.rs

This fixes it so that `cargo clippy` doesn't share the same cache artifacts as `cargo check`. The Cargo side was stabilized a while ago (https://github.com/rust-lang/cargo/pull/8976), so this should be ready to go. I'm not aware of any blockers or concerns.
Closes #4612
---
changelog: `cargo clippy` no longer shares the same build cache as `cargo check`.

Stabilize workspace wrapper.

---

clippy_lints/src/methods/mod.rs
tests/ui/from_iter_instead_of_collect.fixed
tests/ui/from_iter_instead_of_collect.rs
tests/ui/from_iter_instead_of_collect.stderr

Fixes broken suggestions that need parens (i.e.: range)
Fixes: #6648 

Fix suggestions that need parens in `from_iter_instead_of_collect` lint

---

CHANGELOG.md

~~Don't merge yet. This is the last step of the release process.~~ Release process for 1.50 is done, this can now be merged.

Update changelog for 1.51

---

clippy_lints/src/use_self.rs
tests/ui/auxiliary/proc_macro_derive.rs
tests/ui/use_self.fixed
tests/ui/use_self.rs
tests/ui/use_self.stderr
tests/ui/use_self_trait.fixed
tests/ui/use_self_trait.rs
tests/ui/use_self_trait.stderr

This builds on top of #5531
I already reviewed and approved the commits by @montrivo. So only the review of my commits should be necessary. 
I would also appreciate your review @montrivo, since you are familiar with the challenges here.
Fixes #3410 and Fixes #4143 (same problem)
Fixes #2843
Fixes #3859 
Fixes #4734 and fixes #6221
Fixes #4305
Fixes #5078 (even at expression level now 🎉)
Fixes #3881 and Fixes #4887 (same problem)
Fixes #3909
Not yet: #4140 (test added)
All the credit for the fixes goes to @montrivo. I only refactored and copy and pasted his code.
changelog: rewrite [`use_self`] lint and fix multiple (8) FPs. One to go.

Rework use_self impl based on ty::Ty comparison #3410 | Take 2

---

clippy_lints/src/doc.rs
tests/ui/doc_panics.rs
tests/ui/doc_panics.stderr

Fixes #6699.
Are there any other test-cases I should cover?
changelog: [`missing_panics_doc`](https://rust-lang.github.io/rust-clippy/master/index.html#missing_panics_doc): No longer lints on [`unreachable!`](https://doc.rust-lang.org/std/macro.unreachable.html)

Fix missing_panics_doc warning on `unreachable!`.

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/false_negative.md
.github/ISSUE_TEMPLATE/false_positive.md
.github/ISSUE_TEMPLATE/ice.md
.github/ISSUE_TEMPLATE/new_lint.md

It seems like we forgot to update the GitHub templates when we decided to update the label names. This PR just adjusts the templates to use the new label names :)
Context: [Zulip discussion about renaming the labels](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Label.20cleanup/near/224083870)
---

Update labels in template files

---

clippy_dev/README.md
clippy_dev/src/lintcheck.rs

changelog: lintcheck: accept  LINTCHECK_TOML env var to set list of crates to be checked.

lintcheck: accept env var to set crates.toml file

---

tests/ui/crashes/ice-6179.rs

This PR is an auxiliary PR for #6179, just add a minimal reproducer for the ICE discussed in #6179.
See #6179 for more details.

Add a minimal reproducer for the ICE in #6179

---

clippy_lints/src/vec_init_then_push.rs
tests/ui/vec_init_then_push.rs
tests/ui/vec_init_then_push.stderr

changelog: Fix vec_init_then_push false positives
Fixes #6615

Fix vec_init_then_push false positives

---

clippy_lints/src/collapsible_if.rs
tests/ui/collapsible_else_if.fixed
tests/ui/collapsible_else_if.rs
tests/ui/collapsible_if.fixed
tests/ui/collapsible_if.rs

changelog: Fix collapsible_if FP with attributes
Fixes #6593

Fix collapsible_if with attributes

---

clippy_lints/src/blocks_in_if_conditions.rs
tests/ui/blocks_in_if_conditions_closure.rs

Fix FP when the closure is used in an iterator for `blocks_in_if_conditions` lint
FIxes: #1141 

Do not lint when the closure is called using an iterator

---

Cargo.toml
doc/adding_lints.md
tests/compile-test.rs

These updates allow us to specify multiple testnames for `TESTNAME` by
providing a comma separated list of testnames.
The new version of compiletest-rs also includes `bless` support, but is
not enabled with this PR.
cc #5394 

Upgrade compiletest-rs to 0.6 and tester to 0.9

---

clippy_dev/src/lintcheck.rs
lintcheck-logs/lintcheck_crates_logs.txt

* do some refactoring and renaming here and there
* add comments to functions
* fix bug where git repos would not get checked out to the proper commits (cmd was not actually run in repo directory :sweat_smile: )
* print warnings if we can't clone or check out a git repo
* filter out noise from cargo-metadata errors and lint messages that contained absolute file paths (these would change with every pinned-nightly bump, polluting the logs)
changelog: more lintcheck refactoring and fixes for git crates

more lintcheck updates

---

CHANGELOG.md
clippy_lints/src/default_numeric_fallback.rs
clippy_lints/src/lib.rs
tests/ui/default_numeric_fallback.rs
tests/ui/default_numeric_fallback.stderr

fixes #6064 
r? @flip1995 
As we discussed in [here](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Issue.20.236064/near/224647188) and [here](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Issue.20clippy.236064/near/224746333),   I start implementing this lint from the strictest version.
In this PR, I'll allow the below two cases to pass the lint to reduce FPs.
1. Appearances of unsuffixed numeric literals in `Local` if `Local` has a type annotation, for example:
```rust
// Good.
let x: i32 = 1;
// Also good.
let x: (i32, i32) = if cond {
(1, 2)
} else {
(2, 3)
};
```
2. Appearances of unsuffixed numeric literals in args of `Call` or `MethodCall`  if corresponding arguments of their signature have concrete types, for example:
```rust
fn foo_mono(x: …
```

New lint: default_numeric_fallback

---

Cargo.toml

This fixes the dogfood test to include clippy_lints (regression from #6687).
r? @flip1995

Add workspace to manifest

---

.github/workflows/clippy.yml
.github/workflows/clippy_bors.yml
Cargo.toml

Test workspace at once

---

clippy_dev/README.md
clippy_dev/src/lintcheck.rs

Make it possible to add command line options to the clippy invocation of the lintcheck-tool
I found that this will be really helpful if we use a separate repository and want to maintain a all-lints-passing list of crates. See my early experimentation here: https://github.com/flip1995/clippy-lintcheck 
```
git submodule update --init
cargo run -- --mode=all
```
Will run the lintcheck tool on all the specified crates in `config/` in that repository.

Lintcheck and an options for command line options

---

Cargo.toml

r? @matthiaskrgr  cc @camsteffen 
So `exclude` doesn't work with glob patterns, but it turns out that it works with `starts_with`.

Fix lintcheck by excluding checked crates from workspace

---

clippy_dev/Cargo.toml
clippy_dev/src/lintcheck.rs
clippy_dev/src/main.rs
lintcheck-logs/lintcheck_crates_logs.txt

By default we use a single thread and one target dir as before.
If `-j n` is passed, use `n` target dirs and run one clippy in each of them.
We need several target dirs because cargo would lock them for a single process otherwise which would prevent the parallelism.
`-j 0` makes rayon use  $thread_count/2 (which I assume is the number of physical cores of a machine) for the number of threads.
Other change:
Show output of clippy being compiled when building it for lintcheck (makes it easier to spot compiler errors etc)
Show some progress indication in the "Linting... foo 1.2.3"  message.
Sort crates before linting (previously crates would be split randomly between target dirs, with the sorting, we try to make sure that even crates land in target dir 0 and odd ones in target dir 1 etc..) …

lintcheck: parallelize

---

clippy_lints/src/collapsible_match.rs
tests/ui/collapsible_match.stderr
tests/ui/collapsible_match2.stderr

(see https://rustc-dev-guide.rust-lang.org/diagnostics.html for details)
---
changelog: collapsible_match: fix lint message capitalization

collapsible_match: fix lint message capitalization

---

clippy_lints/src/matches.rs
clippy_lints/src/utils/hir_utils.rs
tests/ui/collapsible_match.rs
tests/ui/if_same_then_else2.rs
tests/ui/if_same_then_else2.stderr

changelog: Fix collapsible_match false positive
Fixes #6740
This PR changes the way `SpanlessEq` determines whether two local variables are the same. Instead of checking that the names match, it checks that the `HirId`s match. If local bindings are declared within the expressions that are being compared, `SpanlessEq` will remember bindings that correspond to each other in a `FxHashMap<HirId, HirId>`. This makes `SpanlessEq` more flexible while also fixing false positives. 
Example: `{ let x = 1; x + 2 }` is equal to `{ let y = 1; y + 2 }`.
CC @xFrednet I think this will resolve some concerns in #6463

Teach SpanlessEq binding IDs

---

clippy_lints/src/utils/camel_case.rs
tests/ui/enum_variants.rs
tests/ui/enum_variants.stderr

Fix camel case postfix
Fixes: #4639 

Fix camel case postfix for `enum_variant_names` lint

---

clippy_lints/src/inherent_to_string.rs
tests/ui/inherent_to_string.rs
tests/ui/inherent_to_string.stderr

Minimal example of the false positive: 
````
struct G;
impl G {
fn to_string<const _N: usize>(&self) -> String {
"G.to_string()".to_string()
}
}
fn main() {
let g = G;
g.to_string::<1>();
}
````
Clippy emits an `inherent_to_string` warning, and suggests that we implement `Display` for `G` instead. However, this is not possible, since the generic parameter _N only exists in this function, not in `G` itself. This particular example uses const generics, which is where the issue is most likely to come up, but this PR skips the lint if the `to_string` function has any kind of generic parameters.
changelog: Fix FP in `inherent_to_string`

Fix FP in inherent_to_string when the function has generic parameters

---

CHANGELOG.md
clippy_lints/src/inconsistent_struct_constructor.rs
clippy_lints/src/lib.rs
clippy_lints/src/unnecessary_sort_by.rs
tests/ui/inconsistent_struct_constructor.fixed
tests/ui/inconsistent_struct_constructor.rs
tests/ui/inconsistent_struct_constructor.stderr

fixes: #6352
I added the lint that checks for the struct constructors where the order of the field init shorthands is inconsistent with that in the struct definition.
changelog: Add style lint: `inconsistent_struct_constructor`

Inconsistent struct constructor

---

clippy_dev/src/bless.rs

fixes #6757 
r? @phansch 
Trying to do a quick fix of `bless`, I'm not sure how much work it will need to do transition to `bless` built in `compiletest`, so please feel free to close this PR if it will not need so much.

Quick fix cargo dev bless

---

clippy_lints/src/write.rs

Remove unneeded blank lines like below.

Remove unneeded blank lines from doc

---

clippy_dev/src/lintcheck.rs
lintcheck-logs/lintcheck_crates_logs.txt

Automatically clean lintchecks shared target dir (will force clippy to recheck sources) if
the clippy binaries are older than the lintcheck logs.
Also updated lintcheck logs in the pr.
changelog: lintcheck: fully rerun lintcheck if clippy was rebuilt since last log update

lintcheck: fully rerun lintcheck if clippy was rebuilt since last log update

---

CHANGELOG.md
clippy_lints/src/lib.rs
clippy_lints/src/manual_map.rs
clippy_lints/src/utils/mod.rs
tests/ui/manual_map_option.fixed
tests/ui/manual_map_option.rs
tests/ui/manual_map_option.stderr

fixes: #6
changelog: Added lint: `match_map`

New lint: option_manual_map

---

README.md

This is useful for projects that do not use cargo.
changelog: README: Add subsection on running Clippy as a rustc wrapper

README: Add subsection on running Clippy as a rustc wrapper

---

clippy_lints/src/utils/conf.rs
tests/ui/doc.rs
tests/ui/doc.stderr

changelog: This commit adds `"OpenDNS"` to doc-valid-idents to avoid `doc_markdown` false positives.

Add OpenDNS to `doc-valid-idents`

---

clippy_lints/src/methods/mod.rs
tests/ui/or_fun_call.fixed
tests/ui/or_fun_call.rs
tests/ui/or_fun_call.stderr

fixes #6748 
changelog: or_fun_call: fix suggestion for `or_insert(vec![])` on `std::collections::hash_map::Entry` or `std::collections::btree_map::Entry`

or_fun_call: fix suggestion for `or_insert(vec![])`

---

clippy_dev/src/lintcheck.rs
lintcheck-logs/lintcheck_crates_logs.txt

The stats look like this:
````
Stats:
clippy::manual_map 0 => 10
clippy::missing_panics_doc 54 => 56
clippy::upper_case_acronyms 18 => 4
````
changelog: lintcheck: print stats about changing lint counts in the log

lintcheck: print stats how lint counts change

---

clippy_lints/src/default_numeric_fallback.rs
clippy_lints/src/inconsistent_struct_constructor.rs
tests/ui/crashes/ice-6792.rs
tests/ui/crashes/ice-6793.rs

fixes #6792, fixes #6793.
Fixes the ICEs by replacing `TyCtxt::type_of` with `TypeckResults::expr_ty`.

Fix ICEs 6792 and 6793

---

.github/workflows/clippy.yml
.github/workflows/clippy_bors.yml
Cargo.toml
tests/dogfood.rs
tests/versioncheck.rs

In response to https://github.com/rust-lang/rust-clippy/pull/6733#issuecomment-785792060

Remove workspace and fix dogfood (again)

---

clippy_lints/src/bytecount.rs
clippy_lints/src/lib.rs

As discussed on Zulip, current best practice is to avoid recommending
external crates. This lint is from before that was enforced. Move it
to the pedantic group to avoid enabling it by default.
https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/naive_bytecount.20suggesting.20extra.20dependency
changelog: move [`naive_bytecount`] to pedantic

Move naive_bytecount to pedantic

---

clippy_dev/src/lintcheck.rs

split out from https://github.com/rust-lang/rust-clippy/pull/6829

lintcheck: fix clippy warnings

---

clippy_lints/src/use_self.rs
tests/ui/use_self.fixed
tests/ui/use_self.rs

Fixes  #6818. 
changelog: Fix false positives for use_self in macros.

Fix false-positive in `use_self`

---

clippy_utils/src/hir_utils.rs
clippy_utils/src/lib.rs
tests/ui/match_same_arms2.rs
tests/ui/match_same_arms2.stderr

fixes: #1390
This only considers empty blocks for now, though we should also catch something like this:
```rust
match 0 {
0 => {
do_something();
trace!(0);
0
}
1 => {
do_something();
trace!(1);
1
}
x => x,
}
```
As far as I can tell there aren't any negative effects on other lints. These blocks only happen to be the same for a given compilation, not all compilations.
changelog: Fix `match_on_same_arms` and others. Only consider empty blocks equal if the tokens contained are the same.

Compare empty blocks for equality based on tokens

---

.github/workflows/clippy.yml
.github/workflows/clippy_bors.yml
clippy_dev/src/lib.rs
clippy_dev/src/lintcheck.rs
clippy_lints/src/transmute/transmute_int_to_char.rs
clippy_lints/src/transmute/transmute_ptr_to_ref.rs
clippy_lints/src/transmute/transmute_ref_to_ref.rs
clippy_lints/src/use_self.rs
src/main.rs
tests/dogfood.rs

The CI fix is practically #6829 rebased and squashed into one commit
Dogfood fix is a follow up of #6802
r? @matthiaskrgr for lintcheck changes
(best reviewed with whitespace changes hidden)

Dogfood and CI fixes

---

clippy_lints/src/async_yields_async.rs
clippy_lints/src/await_holding_invalid.rs
clippy_lints/src/doc.rs
clippy_lints/src/implicit_return.rs

We use MIR to get the return type of a closure/function in a couple places. But typeck seems like a better approach.
This is the easy part of #6080.
Also did a tiny cleanup with `typeck` -> `typeck_body`.

Remove a couple MIR usages

---

clippy_lints/src/format.rs

fixes #6844 
changelog: useless_format: fix examples in the description

useless_format: fix examples in the description

---

clippy_lints/src/len_zero.rs
clippy_utils/src/lib.rs
tests/ui/len_without_is_empty.rs
tests/ui/len_without_is_empty.stderr

fixes #1562
This also reverts #1559 as the `#[allow]` now works on the `len` method. A note has also been added to point out where the `empty` method is, if it exists.
changelog: `len_without_is_empty` will now consider multiple impl blocks
changelog: `len_without_is_empty` will now consider `#[allow]` on both the `len` method, and the type definition

`len_without_is_empty` will now consider multiple impl blocks

---

README.md
src/driver.rs
tests/dogfood.rs

This PR makes `clippy-driver` emit `CLIPPY_ARGS` in its `dep-info` output.
Just like #6441, this allows this workflow to work:
```shell
cargo clippy # warning: empty `loop {}` wastes CPU cycles
cargo clippy -- -A clippy::empty_loop # no warnings emitted
```
But without rebuilding all dependencies.
cc https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/CLIPPY_ARGS.20is.20not.20tracked.20by.20Cargo/near/228599088
changelog: Cargo now re-runs Clippy if arguments after `--` provided to `cargo clippy` are changed.

Let Cargo track CLIPPY_ARGS

---

clippy_lints/src/eta_reduction.rs
tests/ui/eta.fixed
tests/ui/eta.rs
tests/ui/eta.stderr

changelog: Fix redundant_closure FPs with macros
Fixes #6732
Fixes #6850
Fixes #4354 (addresses the error message confusion)

Fix redundant closure with macros

---

Cargo.toml
clippy_lints/Cargo.toml
clippy_utils/Cargo.toml

rust-analyzer/rust-analyzer#7891
This will also help priroda and any other package which depends on the `miri` library crate.

Opt-in to rustc_private for `rust-analyzer`

---

clippy_lints/src/derive.rs
clippy_lints/src/lifetimes.rs
clippy_lints/src/map_clone.rs
clippy_utils/src/lib.rs

~~Should fix lintcheck warnings caused by #6823~~
See below

Don't assume lang items will exist.

---

clippy_utils/src/lib.rs
tests/ui/crashes/ice-6840.rs

fixes #6840
make `is_normalizable` more strict, which should catch this ICE and related cases
changelog: Fix ICE in [`zero_sized_map_values`]

Fix ICE 6840 - make is_normalizable more strict

---

clippy_lints/src/methods/mod.rs

Fix https://github.com/rust-lang/rust-clippy/issues/6870. It's because this doc lacks the description that this lint is also used for `Option`.

Improve doc on `map_flatten`

---

Cargo.toml
clippy_dev/Cargo.toml
clippy_dummy/Cargo.toml
clippy_lints/Cargo.toml
mini-macro/Cargo.toml
rustc_tools_util/Cargo.toml

Clippy has grown enough, that putting specific people in the "authors"
field isn't warranted anymore.
As a heads-up: @Manishearth @llogiq @birkenfeld @mcarton @oli-obk @phansch @matthiaskrgr your names will be removed from one or more of the `Cargo.toml` files of Clippy. This of course does not mean that we value your previous work on Clippy any less :heart: 
As per our discussion in today's meeting: https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Meeting.202021-03-09/near/229502514

Set Clippy authors to "The Rust Clippy Developers"

---

clippy_lints/src/missing_inline.rs
tests/ui/missing_inline_executable.rs
tests/ui/missing_inline_proc_macro.rs

Fixes #6486.
changelog: Fix false positives on procedural macros of `missing_inline_in_public_items` lint.

Fix false positives on procedural macros of `missing_inline_in_public_items` lint

---

clippy_lints/src/blocks_in_if_conditions.rs
clippy_lints/src/copy_iterator.rs
clippy_lints/src/loops/iter_next_loop.rs
clippy_lints/src/loops/needless_collect.rs
clippy_lints/src/loops/utils.rs
clippy_lints/src/loops/while_let_on_iterator.rs
clippy_lints/src/map_clone.rs
clippy_lints/src/map_identity.rs
clippy_lints/src/matches.rs
clippy_lints/src/methods/filter_flat_map.rs
clippy_lints/src/methods/filter_map.rs
clippy_lints/src/methods/filter_map_flat_map.rs
clippy_lints/src/methods/filter_map_identity.rs
clippy_lints/src/methods/filter_map_map.rs
clippy_lints/src/methods/filter_map_next.rs
clippy_lints/src/methods/filter_next.rs
clippy_lints/src/methods/flat_map_identity.rs
clippy_lints/src/methods/from_iter_instead_of_collect.rs
clippy_lints/src/methods/inspect_for_each.rs
clippy_lints/src/methods/iter_nth_zero.rs
clippy_lints/src/methods/iter_skip_next.rs
clippy_lints/src/methods/iterator_step_by_zero.rs
clippy_lints/src/methods/map_collect_result_unit.rs
clippy_lints/src/methods/map_flatten.rs
clippy_lints/src/methods/search_is_some.rs
clippy_lints/src/methods/skip_while_next.rs
clippy_lints/src/methods/unnecessary_filter_map.rs
clippy_lints/src/methods/unnecessary_fold.rs
clippy_utils/src/lib.rs
clippy_utils/src/paths.rs

Since `sym::Iterator` was added to diagnostic_item, it's time to remove `paths::ITERATOR`.
ref: #5393
changelog: Add `is_trait_method` to `clippy_utils`
changelog: Remove `paths::ITERATOR`

Use sym::Iterator instead of paths::ITERATOR

---

clippy_lints/src/inconsistent_struct_constructor.rs
tests/ui/inconsistent_struct_constructor.stderr

changelog: inconsistent_struct_constructor: try to make message and lint description a bit clearer
r? @ghost

inconsistent_struct_constructor: try to make message and lint description a bit clearer

---

CHANGELOG.md
clippy_lints/src/if_then_some_else_none.rs
clippy_lints/src/lib.rs
tests/ui/if_then_some_else_none.rs
tests/ui/if_then_some_else_none.stderr

Resolves #6760
changelog: Added a new lint: `if_then_some_else_none`

Implement new lint: if_then_some_else_none

---

clippy_lints/src/casts/unnecessary_cast.rs
tests/ui/unnecessary_cast.stderr

fixes: #6874 
apologies if this may not be the most idiomatic way of doing it, any advice on changes (if any) would be greatly appreciated.

replace span_lint with span_lint_and_sugg along with error message

---

clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/suspicious_map.rs
clippy_utils/src/lib.rs
tests/ui/suspicious_map.rs
tests/ui/suspicious_map.stderr

changelog: Fix suspicious_map false positives
Fixes #5253
Replaces #5375

Fix suspicious_map false positives

---

clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/wrong_self_convention.rs
tests/ui/def_id_nocore.stderr
tests/ui/wrong_self_convention.stderr
tests/ui/wrong_self_conventions_mut.rs
tests/ui/wrong_self_conventions_mut.stderr

fixes #6758 
changelog: wrong_self_convention: fix lint in case of `to_*_mut` method. When a method starts with `to_` and ends with `_mut`, clippy expects a `&mut self` parameter, otherwise `&self`.
Any feedback is welcome. I was also thinking if shouldn't we treat `to_` the same way as `as_`. Namely to accept `self` taken:  `&self` or `&mut self`.

wrong_self_convention: fix lint in case of `to_*_mut` method

---

clippy_utils/src/diagnostics.rs

This small change ensures that if the diagnostic functions are called from outside of Clippy, a docs link is not displayed.
---
changelog: restrict docs links

Do not show docs link when lint doesn't start with "clippy::"

---

Cargo.toml
clippy_lints/Cargo.toml
clippy_utils/Cargo.toml
clippy_utils/src/lib.rs

Get rid of some unused dependecies

---

clippy_lints/src/manual_unwrap_or.rs
tests/ui/manual_unwrap_or.fixed
tests/ui/manual_unwrap_or.rs

Fixes #6898 
changelog:  Fix false-positive for manual_unwrap_or in const fn.

Fix false-positive `manual_unwrap_or` inside const fn

---

CONTRIBUTING.md
clippy_dev/src/fmt.rs
clippy_dev/src/ide_setup.rs
clippy_dev/src/lib.rs
clippy_dev/src/main.rs
doc/basics.md

Add documentation how to get rust-analyzer to like clippys `extern crate` rustc deps.
Fixes #6883
This initially removed `cargo-dev ra_setup` but it is still needed by folks who use intellij rust, so keeping that.

docs: update RA setup documentation

---

clippy_lints/src/write.rs
tests/ui/print.stderr
tests/ui/print_literal.stderr
tests/ui/write_literal.stderr
tests/ui/write_literal_2.rs
tests/ui/write_literal_2.stderr

fixes: #6768
changelog: Add suggestion to `write_literal` and `print_literal` lints
changelog: Change `use_debug` to point only at the format string

Write literal suggestion

---

clippy_lints/src/upper_case_acronyms.rs
tests/ui-toml/upper_case_acronyms_aggressive/upper_case_acronyms.rs
tests/ui/upper_case_acronyms.rs

Fixes #6803
changelog: upper_case_acronyms: ignore public items

upper_case_acronyms: don't warn on public items

---

clippy_lints/src/manual_map.rs
clippy_utils/src/lib.rs
tests/ui/manual_map_option.fixed
tests/ui/manual_map_option.rs
tests/ui/manual_map_option.stderr

fixes: #6847
changelog: Fix `manual_map` suggestion for `if let.. else ... if let.. else` chain

Fix `manual_map` suggestion for `if let.. else ... if let.. else` chain

---

clippy_lints/src/attrs.rs
clippy_lints/src/doc.rs
clippy_lints/src/eval_order_dependence.rs
clippy_lints/src/loops/never_loop.rs
clippy_lints/src/matches.rs
clippy_lints/src/redundant_clone.rs
clippy_lints/src/types/mod.rs
clippy_lints/src/unnecessary_wraps.rs
clippy_utils/src/lib.rs
tests/ui/match_wildcard_for_single_variants.fixed
tests/ui/match_wildcard_for_single_variants.rs
tests/ui/match_wildcard_for_single_variants.stderr
tests/ui/wildcard_enum_match_arm.fixed
tests/ui/wildcard_enum_match_arm.stderr

fixes: #6604
fixes: #5733
fixes: #6862
#5733 is only fixed in the normal case, if different paths are used for the variants then the same problem will occur. It's cause by `def_path_str` returning an utterly useless result. I haven't dug into why yet.
For #6604 there should be some discussion before accepting this. It's easy enough to change the message rather than disable the lint for `Option` and `Result`.
changelog: Attempt to find a common path prefix for `match_wildcard_for_single_variants` and `wildcard_enum_match_arm`
changelog: Don't lint op `Option` and `Result` for `match_wildcard_for_single_variants` and `wildcard_enum_match_arm`
changelog: Consider `or` patterns and `Self` prefix for `match_wildcard_for_single_variants` and `wildcard_enum_match_arm`

`match_wildcard` improvements

---

clippy_lints/src/methods/or_fun_call.rs
tests/ui/or_fun_call.fixed
tests/ui/or_fun_call.rs
tests/ui/or_fun_call.stderr

fixes #6675
changelog: or_fun_call: trigger on unsafe blocks

or_fun_call: trigger on unsafe blocks

---

clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/wrong_self_convention.rs
tests/ui/def_id_nocore.stderr
tests/ui/use_self.fixed
tests/ui/use_self.rs
tests/ui/use_self.stderr
tests/ui/wrong_self_convention.rs
tests/ui/wrong_self_convention.stderr
tests/ui/wrong_self_conventions_mut.stderr

fixes #6727 
changelog: wrong_self_convention: `to_` convention respects `Copy` types

wrong_self_convention: `to_` convention respects `Copy` types

---

clippy_lints/src/new_without_default.rs
tests/ui/new_without_default.rs
tests/ui/new_without_default.stderr

Fixes bad suggestion where a type parameter was missing for `new_without_default` lint.
Fixes #6933 

Fix bad suggestion for generics in `new_without_default` lint

---

clippy_lints/src/default.rs
tests/ui/field_reassign_with_default.rs
tests/ui/field_reassign_with_default.stderr

Fix bad suggestion where `::` is missing after type if generics are involved
Fixes #6944 

Fix suggestion with generics for `field_reassign_with_default` lint

---

clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/search_is_some.rs
tests/ui/search_is_some.rs
tests/ui/search_is_some.stderr
tests/ui/search_is_some_fixable.fixed
tests/ui/search_is_some_fixable.rs
tests/ui/search_is_some_fixable.stderr

fixes: #6815 
changelog: search_is_some: add checking for `is_none()`.
To be honest I don't know what is the process of renaming the lints. Appreciate any feedback if that needs to be handled differently. Thanks!

search_is_some: add checking for `is_none()`

---

clippy_lints/src/methods/or_fun_call.rs
tests/ui/or_fun_call.fixed
tests/ui/or_fun_call.rs
tests/ui/or_fun_call.stderr

changelog: Changed `or_fun_call` to ignore `str::len`, in the same way it ignores `slice::len` and `array::len`
Closes #6943

Ignore str::len() in or_fun_call lint.

---

clippy_lints/src/methods/mod.rs
clippy_utils/src/hir_utils.rs

Factor out `SpanlessEq::eq_ty_kind`

---

clippy_lints/src/loops/manual_flatten.rs
clippy_lints/src/methods/utils.rs
tests/ui/manual_flatten.rs
tests/ui/manual_flatten.stderr

This pull request fixes false positive in `manual_flatten` in case using a slice of references .
closes: #6893
changelog: fix false positive in `manual_flatten`

Fix false positive in `manual_flatten`

---

clippy_lints/src/methods/mod.rs
clippy_utils/src/ty.rs
tests/ui/new_ret_no_self.rs

fixes: #1724
changelog: Fix false positive with `new_ret_no_self` when returning `Self` with different generic arguments

Fix `new_ret_no_self` false positive

---

clippy_lints/src/strings.rs
tests/ui/string_lit_as_bytes.fixed
tests/ui/string_lit_as_bytes.rs
tests/ui/string_lit_as_bytes.stderr

fixes #6927 
changelog: Add a check for `into_bytes()` to string_lit_to_bytes lint

Check for `.to_string().into_bytes()` in string_lit_to_bytes

---

CHANGELOG.md

I've underestimated the work that goes into this a bit, but it just shows that a lot has happened again in Clippy in 1.52 :upside_down_face:.
[Rendered](https://github.com/xFrednet/rust-clippy/blob/changelog-1-52/CHANGELOG.md)
---

Update changelog for 1.52

---

clippy_lints/src/redundant_slicing.rs
tests/ui/redundant_slicing.rs
tests/ui/redundant_slicing.stderr

fixes: #6968
changelog: Fix `redundant_slicing` suggestion when a reborrow might be required or when the value is from a macro call

Improve `redundant_slicing`

---

clippy_lints/src/lib.rs
clippy_lints/src/unnested_or_patterns.rs
clippy_lints/src/utils/conf.rs
doc/adding_lints.md
tests/ui/min_rust_version_attr.rs
tests/ui/min_rust_version_attr.stderr

changelog: [`unnested_or_patterns`] can now be configured with the `msrv` config/attribute.
Fixes #6953

Add MSRV options to `unnested_or_patterns`

---

clippy_lints/src/len_zero.rs
tests/ui/len_without_is_empty.rs
tests/ui/len_without_is_empty.stderr

fixes: #6958
fixes: #6972
changelog: Check the return type of `len`. Only integral types, or an `Option` or `Result` wrapping one.
changelog: Ensure the return type of `is_empty` matches. e.g. `Option<usize>` -> `Option<bool>`

`len_without_is_empty` improvements

---

clippy_lints/src/utils/conf.rs

r? @giraffate 
changelog: Add missing lints to MSRV config doc

Add missing lints to MSRV config doc

---

clippy_lints/src/matches.rs
tests/ui/match_ref_pats.stderr

look inside refs and detect if let &None = ...
Fixes https://github.com/rust-lang/rust-clippy/issues/5396
changelog:  redundant_pattern_matching: look inside Refs to fix FNs with "if let &None = .. "

redundant_pattern_matching: look inside Refs

---

clippy_lints/src/derive.rs
tests/ui/derive.rs
tests/ui/derive.stderr

fixes: #1254
changelog: Check to see if the generic constraints are the same as if using derive for `expl_impl_clone_on_copy`

Improve `expl_impl_clone_on_copy`

---

doc/adding_lints.md

A follow-up of <https://github.com/rust-lang/rust-clippy/pull/6977/files#diff-dac623e7b9c58138761aa527bf5f026bf113cda5b22eea61e655b44dd113389e>

Use uppercase for MSRV

---

clippy_lints/src/functions/mod.rs
clippy_lints/src/functions/must_use.rs
clippy_lints/src/functions/not_unsafe_ptr_arg_deref.rs
clippy_lints/src/functions/result_unit_err.rs
clippy_lints/src/functions/too_many_arguments.rs
clippy_lints/src/functions/too_many_lines.rs
clippy_lints/src/lib.rs

Ref: #6680 
Rearrange lints in `functions`.

Organize functions into functions module

---

clippy_lints/src/manual_map.rs
clippy_utils/src/lib.rs
tests/ui/manual_map_option.fixed
tests/ui/manual_map_option.rs
tests/ui/manual_map_option.stderr

changelog: Fix `manual_map` suggestion at the end of an if chain

Fix `manual_map` at the end of an if chain

---

clippy_lints/src/functions/result_unit_err.rs
tests/ui/len_without_is_empty.stderr
tests/ui/result_unit_error.stderr

changelog: result_unit_err: fix typo in a diagnostic message
r? @giraffate 
fixes https://github.com/rust-lang/rust-clippy/pull/6990#discussion_r603292920.

result_unit_err: Fix typo

---

clippy_lints/src/upper_case_acronyms.rs
tests/ui-toml/upper_case_acronyms_aggressive/upper_case_acronyms.rs
tests/ui-toml/upper_case_acronyms_aggressive/upper_case_acronyms.stderr
tests/ui/upper_case_acronyms.rs
tests/ui/upper_case_acronyms.stderr

Fixes https://github.com/rust-lang/rust-clippy/issues/6803 (again... :sweat_smile:  )
My previous fix did not work for enums because enum variants were checked separately in the `check_variant` function but it looks like we can't use that because we can't tell if the enum the variants belong to is declared as public or not (it always said `Inherited` for me)
I went and special-cased enums and iterated over all the variants "manually", but only, if the enums is not public.
---
changelog: fix upper_case_acronyms still firing on public enums (#6803)

disable upper_case_acronyms for pub items - enum edition

---

clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/wrong_self_convention.rs
tests/ui/wrong_self_convention.rs
tests/ui/wrong_self_convention.stderr
tests/ui/wrong_self_convention2.rs
tests/ui/wrong_self_convention2.stderr

fixes #6983 
changelog: `wrong_self_convention`: fix FP inside trait impl for `to_*` method taking `&self`

wrong_self_convention: fix FP inside trait impl for `to_*` method taking `&self`

---

clippy_lints/src/redundant_clone.rs
tests/ui/redundant_clone.fixed
tests/ui/redundant_clone.rs
tests/ui/redundant_clone.stderr

fixes: #5973
fixes: #5595
fixes: #6998
changelog: Fix `redundant_clone` fp  where the cloned value is modified while the clone is in use.

Fix `redundant_clone` fp

---

clippy_utils/src/sugg.rs
tests/ui/floating_point_log.fixed
tests/ui/floating_point_log.stderr
tests/ui/from_str_radix_10.stderr
tests/ui/manual_memcpy/with_loop_counters.stderr

changelog: clippy_utils: fix needless parenthesis output from `sugg::Sugg::maybe_par`
fixes: #6767

clippy_utils: fix needless parenthesis output from sugg::Sugg::maybe_par

---

clippy_lints/src/lib.rs
clippy_lints/src/manual_non_exhaustive.rs
clippy_lints/src/matches.rs
clippy_lints/src/missing_doc.rs
clippy_utils/src/attrs.rs
tests/ui/match_wildcard_for_single_variants.fixed
tests/ui/match_wildcard_for_single_variants.rs

Fixes #6984
changelog: Fix hidden variant suggestion on `match_wildcard_for_single_variants`

Fix hidden variant suggestion on single variant

---

clippy_lints/src/loops/needless_collect.rs
clippy_utils/src/diagnostics.rs
tests/ui/needless_collect_indirect.stderr

changelog: Improve needless_collect output
Fixes #6908
Partially addresses #6164

Improve needless_collect output

---

util/gh-pages/index.html

This PR adds the MdBook color themes to the lint list of Clippy. Well at least an adaption of these themes.
<details>
<summary>Here are some beautiful screenshots:</summary>
**light theme**
**Rust theme**
**Coal theme**
**Navy theme**
**Ayu theme**
</details>
The theme is also stored in the browser to ensure that the next session applies the theme and doesn't burn your eyes out.
cc: @matthiaskrgr
---
Closes #6877
changelog: [Clippy's lint list](https://rust-lang.github.io/rust-clippy/master/index.html) now supports themes

Clippy going dark: Adding a dark theme to Clippy's lint list

---

clippy_lints/src/matches.rs
tests/ui/crashes/ice-7012.rs

Fix ICE #7012

---

util/gh-pages/index.html

This fixes a problem from #7030 that the service used to access css files was blocked by GitHub pages due to `SSL_ERROR_BAD_CERT_DOMAIN`. The css file loading worked fine during local development. The browser probably disabled some security options due to the local address.
This fix works locally and should also work online as it references the direct css files used by the [mdBook User Guide](https://rust-lang.github.io/mdBook/index.html) the disadvantage of this is that refactorings within the mdBook project can have effects on the theme loading of Clippy. This PR is therefor more meant as a quick fix until I find a better solution. 
I've tested these changes using the page editor in the browser and can now confirm that they work :)
r?  @llogiq

Quick fix for the updated website theaming to access the correct css files

---

clippy_lints/src/functions/must_use.rs
clippy_lints/src/functions/not_unsafe_ptr_arg_deref.rs
clippy_lints/src/inherent_impl.rs
clippy_lints/src/len_zero.rs
clippy_lints/src/loops/utils.rs
clippy_lints/src/loops/while_immutable_condition.rs
clippy_lints/src/matches.rs
clippy_lints/src/needless_pass_by_value.rs
clippy_utils/src/hir_utils.rs
clippy_utils/src/usage.rs

Use DefIdMap and similar aliases

---

clippy_lints/src/doc.rs
tests/ui/doc.rs

fixes: #7033
changelog: Fix ICE in `missing_panics_doc` while searching in a `const` block

Fix ICE in `missing_panics_doc`

---

clippy_lints/src/cargo_common_metadata.rs
tests/ui-cargo/cargo_common_metadata/fail/src/main.stderr
tests/ui-cargo/cargo_common_metadata/fail_publish/src/main.stderr
tests/ui-cargo/cargo_common_metadata/fail_publish_true/src/main.stderr
tests/ui-cargo/cargo_common_metadata/pass/Cargo.toml

This PR follows https://github.com/rust-lang/cargo/pull/9282, I'm not fully informed about all of this, it would be great if somebody knowledgeable about this topic agrees.
changelog: Changed `cargo_common_metadata` to stop linting on the optional author field.

Remove author requirement for `cargo_common_metadata`

---

clippy_lints/src/loops/same_item_push.rs
tests/ui/same_item_push.rs

fixes #6987
changelog: `same_item_push`: Don't trigger if the `vec` is used in the loop body

Don't trigger `same_item_push` if the vec is used in the loop body

---

clippy_lints/src/vec.rs
tests/ui/vec.fixed
tests/ui/vec.rs
tests/ui/vec.stderr

fixes #7035 
changelog: Now the suggested by `useless_vec` considers mutability to suggest either `&[]`, as before, or `&mut []` if the used reference is mutable.

consider mutability on useless_vec suggestions

---

clippy_utils/src/lib.rs

From zulip [disucssion](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/match_.5Bq.5Dpath.20is.20bad.3F).

Soft deprecate match_path and match_qpath

---

clippy_lints/src/attrs.rs
clippy_lints/src/excessive_bools.rs
clippy_lints/src/functions/must_use.rs
clippy_lints/src/macro_use.rs
clippy_lints/src/methods/or_fun_call.rs
clippy_lints/src/option_env_unwrap.rs
clippy_utils/src/lib.rs

Some symbol optimizations

---

clippy_lints/src/macro_use.rs
tests/ui/macro_use_imports.fixed
tests/ui/macro_use_imports.rs

fixes: #7015
changelog: Fix `macro_use_import` ICE

Fix `macro_use_import` ICE

---

CHANGELOG.md
clippy_lints/src/deprecated_lints.rs
clippy_lints/src/lib.rs
tests/ui/deprecated.stderr

This still applies the lint, and also adds a structured suggestion to
rename it.
changelog: Use `register_renamed` instead of `register_removed` for lints uplifted to rustc

Use `register_renamed` instead of `register_removed` for uplifted lints

---

clippy_lints/src/panic_unimplemented.rs
tests/ui/panicking_macros.rs

This fixes a false-positive in `clippy::panic` when `debug_assert` is used with a message.
Fixes https://github.com/rust-lang/rust-clippy/issues/7062.
changelog: Fix false-positive in `panic` when `debug_assert` is used with a message

Fix false-positive `debug_assert` in `panic`

---

clippy_lints/src/lib.rs
clippy_lints/src/single_component_path_imports.rs
tests/ui/single_component_path_imports.fixed
tests/ui/single_component_path_imports.rs
tests/ui/single_component_path_imports.stderr
tests/ui/single_component_path_imports_nested_first.rs
tests/ui/single_component_path_imports_nested_first.stderr
tests/ui/single_component_path_imports_self_after.rs
tests/ui/single_component_path_imports_self_before.rs

Fix FP in  `single_component_path_imports` lint when the import is reused with `self`, like in `use self::module`.
Fixes #5210 

Fix FP in `single_component_path_imports` lint

---

clippy_lints/src/collapsible_match.rs
clippy_lints/src/if_then_some_else_none.rs
clippy_lints/src/loops/manual_flatten.rs
clippy_lints/src/manual_map.rs
clippy_lints/src/manual_ok_or.rs
clippy_lints/src/manual_unwrap_or.rs
clippy_lints/src/matches.rs
clippy_lints/src/mem_replace.rs
clippy_lints/src/methods/option_map_or_none.rs
clippy_lints/src/methods/unnecessary_filter_map.rs
clippy_lints/src/needless_question_mark.rs
clippy_lints/src/option_if_let_else.rs
clippy_lints/src/question_mark.rs
clippy_lints/src/try_err.rs
clippy_lints/src/unnecessary_wraps.rs
clippy_lints/src/unused_io_amount.rs
clippy_utils/src/lib.rs

Replaces `is_some_ctor` and `is_ok_ctor`. Removes many path usages.

Introduce `is_lang_ctor`

---

clippy_lints/src/loops/explicit_into_iter_loop.rs
clippy_lints/src/loops/explicit_iter_loop.rs
clippy_lints/src/loops/mod.rs
tests/ui/for_loop_fixable.fixed
tests/ui/for_loop_fixable.rs

fixes: #6900 
changelog: Only lint when `into_iter` is an implementation of `IntoIterator`

Fix `explicit_into_iter_loop`

---

clippy_lints/src/methods/wrong_self_convention.rs
tests/ui/wrong_self_convention2.rs

Previously, this lint didn't check into impl block when it was implementing a trait.
Recent improvements (#6924) have moved this check and some impl blocks are now checked but they shouldn't, such as in #7032.
Fixes #7032 
changelog: Fix FP when not taking `self` in impl block for `wrong_self_convention` lint

Fix FP in `wrong_self_convention` lint

---

clippy_lints/src/returns.rs
tests/ui/needless_return.fixed
tests/ui/needless_return.rs
tests/ui/needless_return.stderr

closes #7042
changelog: fix a false negative on `needless return`

Fix a false negative on `needless return`

---

clippy_lints/src/mem_replace.rs
clippy_lints/src/methods/implicit_clone.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/misc.rs
clippy_lints/src/to_string_in_display.rs
clippy_utils/src/lib.rs

* Split `is_diagnostic_assoc_item` into `is_diag_item_method` and `is_diag_trait_item`
* `is_diag_item_method` is a bit more nuanced with the `tcx.type_of(impl_id).ty_adt_def()` step, so it seems better to keep that separate.
* No need to generalize over traits and Adt's since we know which one we want at compile time
* "item" vs. "method" because a trait may have associated items.
* Replaces the usage of the `sym::slice` diagnostic item with the `slice_alloc` lang item. The diagnostic item should be removed from rustc because it is on the `slice_alloc` impl, not slice itself (and it's not needed).

Split `is_diagnostic_assoc_item`

---

clippy_lints/src/missing_const_for_fn.rs
clippy_utils/src/lib.rs
clippy_utils/src/qualify_min_const_fn.rs
tests/ui/missing_const_for_fn/auxiliary/helper.rs
tests/ui/missing_const_for_fn/cant_be_const.rs
tests/ui/missing_const_for_fn/could_be_const.rs
tests/ui/missing_const_for_fn/could_be_const.stderr

where a function that calls a standard library function whose constness
is unstable is considered as being able to be a const function. Fixes #5995.
The core change is the move from `rustc_mir::const_eval::is_min_const_fn` to `rustc_mir::const_eval::is_const_fn`. I'm not clear about the difference in their purpose between them so I'm not sure if it's acceptable to call `qualify_min_const_fn::is_min_const_fn` this way now.
---
changelog: `missing_const_for_fn`: No longer lints when an unstably const function is called

Fix a FP in `missing_const_for_fn`
