clippy_lints/src/tabs_in_doc_comments.rs
tests/ui/crashes/ice-5835.rs
tests/ui/crashes/ice-5835.stderr

This is a quick-fix for an ICE in `tabs_in_doc_comments`. The problem
was that we we're indexing into possibly multi-byte characters, such as '位'.
More specifically `get_chunks_of_tabs` was returning indices into
multi-byte characters. Those were passed on to a `Span` creation that
then caused the ICE.
This fix makes sure that we don't return indices that point inside a
multi-byte character. *However*, we are still iterating over unicode
codepoints, not grapheme clusters. So a seemingly single character like y̆ ,
which actually consists of two codepoints, will probably still cause
incorrect spans in the output. But I don't think we handle those cases
anywhere in Clippy currently?
Fixes #5835
changelog: Fix ICE in `tabs_in_doc_comments`

tabs_in_doc_comments: Fix ICE due to char indexing

---

.github/workflows/clippy_bors.yml

Error messages are more helpful if you can see them.

Fix changelog check output

---

clippy_lints/src/lib.rs

Just had to turn away a PR for using pre-expansion. I don't think that was the first time. So hopefully this will inform people sooner.
r? flip1995

Add a note for pre-expansion passes

---

clippy_lints/src/manual_map.rs
tests/ui/manual_map_option.fixed
tests/ui/manual_map_option.rs

fixes: #7077
The other option here would be to add the return type to the closure. It would be fine for simple types, but longer types can be rather unwieldy. Could also implement the adjustment manually.
changelog: Don't lint `manual_map` when type adjustments are added. e.g. autoderef

Don't allow adjustments for `manual_map`

---

clippy_lints/src/matches.rs
tests/ui/single_match.rs
tests/ui/single_match.stderr

fixes: #7038
changelog: Don't suggest an equality check for types which don't implement `PartialEq` in `single_match`

Fix `single_match`

---

clippy_lints/src/matches.rs
tests/ui/redundant_pattern_matching_drop_order.fixed
tests/ui/redundant_pattern_matching_drop_order.rs
tests/ui/redundant_pattern_matching_drop_order.stderr
tests/ui/redundant_pattern_matching_option.fixed
tests/ui/redundant_pattern_matching_option.rs
tests/ui/redundant_pattern_matching_option.stderr
tests/ui/redundant_pattern_matching_poll.fixed
tests/ui/redundant_pattern_matching_poll.rs
tests/ui/redundant_pattern_matching_poll.stderr
tests/ui/redundant_pattern_matching_result.fixed
tests/ui/redundant_pattern_matching_result.rs
tests/ui/redundant_pattern_matching_result.stderr

Fixes #5746
A note about the change in drop order is added when the scrutinee (or any temporary in the expression) isn't known to be safe to drop in any order (i.e. doesn't implement the `Drop` trait, or contain such a type). There is a whitelist for some `std` types, but it's incomplete. Currently just `Vec<_>`, `Box<_>`, `Rc<_>` and `Arc<_>`, but only if the contained type is also safe to drop in any order.
Another lint for when the drop order changes could be added as allowed by default, but the drop order requirement is pretty subtle in this case. I think the note added to the lint should be enough to make someone think before applying the change.
changelog: Added a note to `redundant_pattern_matching` when the change in drop order might matter

Fix: redundant_pattern_matching drop order

---

clippy_lints/src/comparison_chain.rs
clippy_lints/src/copies.rs
clippy_lints/src/if_then_some_else_none.rs
clippy_lints/src/needless_bool.rs
clippy_utils/src/hir_utils.rs
clippy_utils/src/lib.rs
tests/ui/branches_sharing_code/shared_at_bottom.rs
tests/ui/branches_sharing_code/shared_at_top.rs
util/gh-pages/index.html

Fixes #7053
Fixes #7054 
And an additional CSS adjustment to support dark mode for every inline code. It currently only works in paragraphs, which was an oversight on my part :sweat_smile:. [Current Example](https://rust-lang.github.io/rust-clippy/master/index.html#blacklisted_name)
This also includes ~50 lines of doc comments and is therefor not as big as the changes would indicate. :penguin:
---
All of these bugs were introduced in this dev version and are therefor not worth a change log entry.
r? @phansch 
cc: @camsteffen since you have a pretty good overview of the `SpanlessEq` implementation :upside_down_face:

Fixing FPs for the `branches_sharing_code` lint

---

clippy_lints/src/formatting.rs
tests/ui/suspicious_else_formatting.rs
tests/ui/suspicious_else_formatting.stderr

fixes: #3864
Indentation checks could be added as well, but the lint already doesn't check for it.
changelog: Allow allman style braces in `suspicious_else_formatting`

Allow allman style braces in `suspicious_else_formatting`

---

clippy_lints/src/from_over_into.rs
tests/ui/from_over_into.stderr

fixes #7088
changelog: add type in help message of from_over_into

add type in help message of from_over_into

---

clippy_lints/src/try_err.rs
tests/ui/try_err.fixed
tests/ui/try_err.rs
tests/ui/try_err.stderr

This fixes #7103 by looking at the parent expression and omitting the "return " in the suggestion when its already a `return` expression.
---

un-double `return` on try_err

---

clippy_lints/src/format.rs
tests/ui/format.fixed
tests/ui/format.rs
tests/ui/format.stderr

fixes #7066 
changelog: [`useless_format`] wraps the content in the braces when it's needed.
r? @giraffate

useless use of format! should return function directly

---

clippy_lints/src/inconsistent_struct_constructor.rs
tests/ui/inconsistent_struct_constructor.fixed
tests/ui/inconsistent_struct_constructor.rs
tests/ui/inconsistent_struct_constructor.stderr

fixes #7069 
changelog: `inconsistent_struct_constructor`: Fix FP in macro expansion.

Fixed inconsistent_struct_constructor triggers in macro-generated code

---

tests/ui/asm_syntax.rs
tests/ui/asm_syntax.stderr

fixes #7091 - asm_syntax lint test will not compile on aarch64

Ignore aarch64 for this test as it's x86 assembly only.  Fixes #7091

---

CHANGELOG.md
clippy_lints/src/bool_assert_comparison.rs
clippy_lints/src/lib.rs
clippy_utils/src/ast_utils.rs
tests/ui/bool_assert_comparison.rs
tests/ui/bool_assert_comparison.stderr

This PR adds a lint to check if an assert macro is using a boolean as "comparison value". For example:
```rust
assert_eq!("a".is_empty(), false);
```
Could be rewritten as:
```rust
assert!(!"a".is_empty());
```
PS: The dev guidelines are amazing. Thanks a lot for writing them!
changelog: Add `bool_assert_comparison` lint

Add lint to check for boolean comparison in assert macro calls

---

CHANGELOG.md
clippy_lints/src/lib.rs
clippy_lints/src/modulo_arithmetic.rs
clippy_lints/src/unnecessary_self_imports.rs
tests/ui/unnecessary_self_imports.fixed
tests/ui/unnecessary_self_imports.rs
tests/ui/unnecessary_self_imports.stderr

fixes #6552 
changelog: add `unnecessary_self_imports` lint

add unnecessary_self_imports lint

---

clippy_lints/src/unused_io_amount.rs
tests/ui/unused_io_amount.rs
tests/ui/unused_io_amount.stderr

fixes #7096
changelog: unused_io_amount now detect expertion like `.read().ok()?`,  `.read().or_else(|err| ...)?` and similar expressions.

Unused io amount detects `.read().ok()?`

---

clippy_lints/src/single_component_path_imports.rs
tests/ui/single_component_path_imports_macro.fixed
tests/ui/single_component_path_imports_macro.rs
tests/ui/single_component_path_imports_macro.stderr

Fixes #7106
changelog: Ignore exporting a macro within a crate using `pub(crate) use some_macro;` for [`single_component_path_imports`]

`single_component_path_imports`: ignore `pub(crate) use some_macro;`

---

lintcheck/src/main.rs

Fix lintcheck on windows

---

clippy_lints/src/methods/cloned_instead_of_copied.rs
clippy_lints/src/methods/mod.rs

(since the lint is still new)
Fixes #7127

cloned_instead_of_copied MSRV

---

clippy_lints/src/loops/single_element_loop.rs
tests/ui/single_element_loop.fixed
tests/ui/single_element_loop.rs
tests/ui/single_element_loop.stderr

This extends `single_element_loop` to also match `[..].iter()` in the loop argument. Related to #7125, but not completely fixing it due to the lint only firing if the array expression contains a local variable.
---

extend `single_element_loop` to match `.iter()`

---

clippy_lints/src/manual_unwrap_or.rs
tests/ui/manual_unwrap_or.fixed
tests/ui/manual_unwrap_or.rs
tests/ui/manual_unwrap_or.stderr

fixes #6965 
changelog: fix invalid code suggestion in `manual_unwrap_or` lint, due to macro expansion

manual_unwrap_or: fix invalid code suggestion, due to macro expansion

---

clippy_lints/src/methods/utils.rs
tests/ui/iter_cloned_collect.fixed
tests/ui/iter_cloned_collect.rs
tests/ui/iter_cloned_collect.stderr

fixes #6808 
changelog: Fix FN in `iter_cloned_collect` with a large array
I spotted that [is_iterable_array](https://github.com/rust-lang/rust-clippy/blob/a362a4d1d0edb66aef186c1d27b28c60573078f4/clippy_lints/src/loops/explicit_iter_loop.rs#L67-L75) function that `explicit_iter_loop` lint is using only works for array sizes <= 32.
There is this comment:
> IntoIterator is currently only implemented for array sizes <= 32 in rustc
I'm a bit confused, because I read that [IntoIterator for arrays](https://doc.rust-lang.org/src/core/array/mod.rs.html#194-201) with const generic `N` is stable since = "1.0.0". Although Const Generics MVP were stabilized in Rust 1.51.
Should I set MSRV for the current change? I will try to test with older compilers soon.

Fix FN in `iter_cloned_collect` with a large array

---

clippy_utils/src/qualify_min_const_fn.rs
tests/ui/crashes/ice-7126.rs

fixes: #7126
changelog: Fix ICE in `missing_const_for_fn` when using a feature-gated `const fn`

Fix ICE checking for feature gated const fn

---

clippy_lints/src/matches.rs

```
thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 0', src/tools/clippy/clippy_lints/src/matches.rs:1595:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I don't have a minimised testcase because I don't have time to reduce libstd down to a few lines right now.
---
changelog: fix index out of bounds access when checking rustc libstd

fix ice when checking rustc libstd

---

clippy_lints/src/lib.rs
clippy_lints/src/utils/conf.rs
src/driver.rs

Removes dead code that used to support the following syntax:
```rust
#![plugin(clippy(conf_file="path/to/clippy's/configuration"))]
```
RLS (and others?) will need to remove the `&[]` from `clippy_lints::read_conf(&[], sess)`.
r? @flip1995

Remove leftover plugin conf_file code

---

clippy_lints/src/comparison_chain.rs
tests/ui/comparison_chain.rs

closes https://github.com/rust-lang/rust-clippy/issues/7082
changelog: fix a false-positive inside const fn in [`comparison_chain`]

Fix a false-positive inside const fn in `comparison_chain`

---

clippy_lints/src/default.rs
clippy_lints/src/lib.rs
clippy_lints/src/utils/conf.rs
tests/ui-toml/bad_toml_type/conf_bad_type.stderr
tests/ui-toml/conf_deprecated_key/conf_deprecated_key.stderr

changelog: Allow `default_trait_access` in macros 
Mainly this is a change to use serde as in [Manually implementing Deserialize for a struct](https://serde.rs/deserialize-struct.html), which opens the door for a cleaner implementation overall.
* Allow `default_trait_access` in macros (tangential, but used in this PR)
* Deserialize into `TryConf { conf, errors }` instead of using a global `ERRORS` variable.
* Improve the `define_Conf!` macro
* Remove the redundant string literal `(name, "name", ..)`
* Support deprecated configs with `#[conf_deprecated(message)]`. Message shows in error.
* Make the default value optional. Use `Default::default()` if omitted.
* Invalid config value error now shows the key (see test output)
* Cleaner `impl Default for Conf` (no `toml::from_str("")`)

`Conf` macro improvements

---

clippy_lints/src/utils/conf.rs
doc/adding_lints.md
tests/ui-toml/conf_deprecated_key/conf_deprecated_key.stderr
util/lintlib.py

Follow-up to #7150
I made the default value required again for `define_Conf!` so that it can be parsed by the magic Python. I guess it's just as well for readability.
r? @flip1995

`Conf` macro improvements part 2

---

clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/single_char_pattern.rs
tests/ui/single_char_pattern.fixed
tests/ui/single_char_pattern.rs
tests/ui/single_char_pattern.stderr

Title says it all. Adjusted ui tests.
I added the second commit in case you don't like that I moved that table into `single_char_pattern.rs` directly. I don't see any reason why it shouldn't be in that file. It isn't used anywhere else.
changelog: add strip_prefix and strip_suffix to single_char_pattern lint

[single_char_pattern] add strip_prefix and strip_suffix

---

clippy_utils/src/hir_utils.rs

SpanlessHash add Pat

---

clippy_lints/src/unused_unit.rs
tests/ui/unused_unit.fixed
tests/ui/unused_unit.rs

changelog: Fix [`unused_unit`] false positive with macros
Fixes #7055

Fix unused_unit macro false positive

---

clippy_lints/src/loops/needless_collect.rs
tests/ui/copy_iterator.rs
tests/ui/needless_collect_indirect.rs
tests/ui/needless_collect_indirect.stderr

fixes #7110
changelog: needless_collect: Lint cases with type annotations for indirect usage and recognize `BinaryHeap`.

needless_collect: Lint cases with type annotations for indirect usage and recognize `BinaryHeap`

---

clippy_lints/src/matches.rs
tests/ui/crashes/ice-7169.rs
tests/ui/crashes/ice-7169.stderr

Fixes #7169 
~~cc @Jarcho Since tomorrow is release day and we need to get this also fixed in beta, I'll just revert the PR instead of looking into the root issue. Your changes are good, so if you have an idea what could cause this stack overflow and know how to fix it, please open a PR that reverts this revert with a fix.~~
r? @llogiq 
changelog: none (fixes stack overflow, but this was introduced in this release cycle)

Fix stack overflow issue in `redundant_pattern_matching`

---

clippy_lints/src/eval_order_dependence.rs
tests/ui/eval_order_dependence.rs
tests/ui/eval_order_dependence.stderr

changelog: Fix [`eval_order_dependence`] false positive in async code
Fixes #6925

Fix eval_order_dependence async false positive

---

clippy_lints/src/methods/unnecessary_filter_map.rs
tests/ui/unnecessary_filter_map.rs

changelog: Fix an [`unnecessary_filter_map`] false positive
Fixes #6804

Fix unnecessary_filter_map false positive

---

clippy_lints/src/utils/conf.rs

A follow-up of https://github.com/rust-lang/rust-clippy/pull/6859.
changelog: Add a missing lint to MSRV config doc

Add a missing lint to MSRV config doc

---

CHANGELOG.md

The most recent changelog update 037ddf282bbf011babd4b7f9a851f6028fc6fd70 accompanying the 1.52 release added a second "Rust 1.52" section header, with the result that the Rust release announcement https://blog.rust-lang.org/2021/05/06/Rust-1.52.0.html is linking to the "current beta" changelog section for Clippy rather than the stable changelog. I don't know the release process but based on previous changes to this file, I assume the correct thing to do is to mark the topmost section as being for Rust 1.53, not 1.52.

Fix duplicated "Rust 1.52" version section header

---

clippy_lints/src/write.rs
tests/ui/write_with_newline.stderr

Make `write!(buf, "\n")` suggest `writeln!(buf)` by removing
the trailing comma from `writeln!(buf, )`.
changelog: [`write_with_newline`] suggestion on only "\n" improved

Handle write!(buf, "\n") case better

---

clippy_lints/src/matches.rs
tests/ui/crashes/ice-7169.rs
tests/ui/crashes/ice-7169.stderr

changelog: none (fixes stack overflow, but this was introduced in this release cycle)

Backport #7170 to beta

---

clippy_lints/src/matches.rs
tests/ui/crashes/ice-7169.rs
tests/ui/crashes/ice-7169.stderr

r? @ghost
changelog: none (fixes stack overflow, but this was introduced in this release cycle)
Now actually opened towards the `beta` branch.

Backport of #7170 to beta

---

clippy_lints/src/deprecated_lints.rs
clippy_lints/src/lib.rs
clippy_lints/src/utils/internal_lints/metadata_collector.rs

This adds the collection of deprecated lints to the metadata collection monster. The JSON output has the same structure with the *new* lint group "DEPRECATED". Here is one of fourteen examples it was able to dig up in Clippy's code:
```JSON
{
"id": "assign_op_pattern",
"id_span": {
"path": "src/assign_ops.rs",
"line": 34
},
"group": "clippy::style",
"docs": " **What it does:** Checks for `a = a op b` or `a = b commutative_op a` patterns.\n\n **Why is this bad?** These can be written as the shorter `a op= b`.\n\n **Known problems:** While forbidden by the spec, `OpAssign` traits may have\n implementations that differ from the regular `Op` impl.\n\n **Example:**\n ```rust\n let mut a = 5;\n let b = 0;\n // ...\n // Bad\n a = a + b;\n\n // Good\n a += b;\n ```\n",
"applicability": { …
```

Metadata collection monster eating deprecated lints

---

clippy_lints/src/doc.rs
clippy_lints/src/loops/while_let_on_iterator.rs
clippy_utils/src/lib.rs
clippy_utils/src/sugg.rs
clippy_utils/src/visitors.rs
tests/ui/while_let_on_iterator.fixed
tests/ui/while_let_on_iterator.rs
tests/ui/while_let_on_iterator.stderr

fixes: #6491
fixes: #6231
fixes: #5844
fixes: #1924
fixes: #1033
The check for whether a field can be borrowed should probably be moved to utils at some point, but it would require some cleanup work and knowing what parts can actually be shared.
changelog: Suggest `&mut iter` when the iterator is used after the loop.
changelog: Suggest `&mut iter` when the iterator is a field in a struct.
changelog: Don't lint when the iterator is a field in a struct, and the struct is used in the loop.
changelog: Lint when the loop is nested in another loop, but suggest `&mut iter` unless the iterator is from a local declared inside the loop.

`while_let_on_iterator` Improvements

---

clippy_lints/src/matches.rs
tests/ui/match_single_binding.fixed
tests/ui/match_single_binding.rs
tests/ui/match_single_binding.stderr
tests/ui/match_single_binding2.fixed
tests/ui/match_single_binding2.rs
tests/ui/match_single_binding2.stderr

fixes #7094
changelog: `match_single_binding`: Fix invalid suggestion when match scrutinee has side effects
---
`Expr::can_have_side_effects` is used to determine the scrutinee has side effects, while this method is a little bit conservative for our use case. But I'd like to use it to avoid reimplementation of the method and too much heuristics. If you think this is problematic, then I'll implement a custom visitor to address it.

match_single_binding: Fix invalid suggestion when match scrutinee has side effects

---

clippy_lints/src/methods/mod.rs
tests/ui/wrong_self_convention2.rs
tests/ui/wrong_self_convention2.stderr

Lint [`wrong_self_convention`] only if the impl or trait has `self` _per sé_.
Fixes: #7179 
changelog: trigger [`wrong_self_convention`] only if it has implicit self

Trigger [`wrong_self_convention`] only if it has implicit self

---

clippy_lints/src/loops/needless_collect.rs
tests/ui/needless_collect.fixed
tests/ui/needless_collect.rs
tests/ui/needless_collect.stderr

fixes #7164  
changelog: `needless_collect`: For `BTreeMap` and `HashMap` lint only `is_empty`, as `len` might produce different results than iter's `count`
changelog: `needless_collect`: Lint `LinkedList` and `BinaryHeap` in direct usage case as well

`needless_collect` enhancements

---

tests/ui/wrong_self_convention2.rs

This has been solved a few hours ago by #7215 😉 
Fixes: #7219 

Add sized trait for `wrong_self_convention` lint test

---

.cargo/config
tests/dogfood.rs

This PR adds a new alias to run the metadata collection monster on `clippy_lints`. I'm currently using it to create the `metadata_collection.json` file and I plan to use it in the `deply.sh` script. Having it as a new alias enables us to simply use:
```sh
cargo collect-metadata
```
It sometimes requires running `cargo clean` before collecting the metadata due to caching. I'm still debating if I should include a cargo clean as part of the `run_metadata_collection_lint` test or not. Input on this would be greatly appreciated :upside_down_face: 
That's it, just a small change that can be reviewed and merged in parallel to #7214. 
---
See: #7172 for the full metadata collection to-do list or to suggest a new feature in connection to it.
---
r? @flip1995 btw. feel free to pass …

Add `cargo collect-metadata` as an cargo alias for the metadata collection lint

---

clippy_lints/src/lib.rs
clippy_lints/src/utils/conf.rs
clippy_lints/src/utils/internal_lints/metadata_collector.rs

This PR teaches our lovely metadata collection monster which configurations are available inside Clippy. It then adds a new *Configuration* section to the lint documentation.
---
The implementation uses the `define_Conf!` macro to create a vector of metadata during compilation. This enables easy collection and parsing without the need of searching for the struct during a lint-pass (and it's quite elegant IMO). The information is then parsed into an intermediate struct called `ClippyConfiguration` which will be saved inside the `MetadataCollector` struct itself. It is currently only used to generate the *Configuration* section in the lint documentation, but I'm thinking about adding an overview of available configurations to the website. Saving them in this intermediate state without …

Metadata collection monster searching for Clippy's configuration options

---

clippy_lints/src/option_if_let_else.rs
tests/ui/option_if_let_else.fixed
tests/ui/option_if_let_else.stderr

For readability concerns, it is counterproductive to lint `else if let` pattern.
Unfortunately the suggested code is much less readable.
Fixes: #7006 
changelog: stop linting `else if let` pattern in [`option_if_let_else`] lint

Stop linting `else if let` pattern in [`option_if_let_else`] lint

---

clippy_lints/src/manual_unwrap_or.rs
tests/ui/manual_unwrap_or.fixed
tests/ui/manual_unwrap_or.rs

Fix https://github.com/rust-lang/rust-clippy/issues/7228.
changelog: Fix a [`manual_unwrap_or`] FP with deref coercion

Fix a `manual_unwrap_or` FP with deref coercion

---

clippy_lints/src/use_self.rs
clippy_lints/src/useless_conversion.rs
clippy_utils/src/ty.rs
tests/ui/use_self.fixed
tests/ui/use_self.rs
tests/ui/use_self.stderr
tests/ui/useless_conversion.fixed
tests/ui/useless_conversion.rs
tests/ui/useless_conversion.stderr

Fix 2 false positives in [`use_self`] and [`useless_conversion`] lints, by taking into account generic args and comparing them.
Fixes: #7205 
Fixes: #7206 
changelog: Fix FPs about generic args in [`use_self`] and [`useless_conversion`] lints

Fix FPs about generic args

---

CHANGELOG.md
clippy_lints/src/lib.rs
clippy_lints/src/needless_bitwise_bool.rs
tests/ui/needless_bitwise_bool.fixed
tests/ui/needless_bitwise_bool.rs
tests/ui/needless_bitwise_bool.stderr

fixes #6827
fixes #1594
changelog: Add ``[`needless_bitwise_bool`]`` lint
Creates a new `bitwise_bool` lint to convert `x & y` to `x && y` when both `x` and `y` are booleans. I also had to adjust thh `needless_bool` lint slightly, and fix a couple failing dogfood tests. I made it a correctness lint as per flip1995's comment [here](https://github.com/rust-lang/rust-clippy/pull/3385#issuecomment-434715723), from a previous WIP attempt at this lint.

Add `needless_bitwise_bool` lint

---

clippy_lints/src/option_if_let_else.rs

Remove dead code after #7216

---

clippy_lints/src/floating_point_arithmetic.rs
tests/ui/floating_point_powi.fixed
tests/ui/floating_point_powi.rs
tests/ui/floating_point_powi.stderr

powi(2) produces exactly the same native code as x * x
powi was part of the [`suboptimal_flops`] lint
fixes #7058
changelog: Remove powi [`suboptimal_flops`], "square can be computed more efficiently"

Remove powi, "square can be computed more efficiently"

---

.github/workflows/clippy_bors.yml

Ok, fine windows, if this is what you want, take it...
r? @ghost

CI: update rustup before installing the toolchain on windows

---

Cargo.toml
clippy_dev/src/lib.rs
clippy_dev/src/main.rs
clippy_lints/Cargo.toml
clippy_utils/Cargo.toml
clippy_utils/src/lib.rs
clippy_utils/src/ty.rs

Pointed out by @xFrednet in https://github.com/rust-lang/rust-clippy/pull/7229#issuecomment-842978909
This enables the same (rustc) lints in every main sub-crate:
- `clippy`
- `clippy_lints`
- `clippy_utils`
- `clippy_dev`
In addition it forwards the `deny-warnings` feature to those sub-crates, so we don't miss warnings that then become a problem during sync. (I wanted to fix that before, but forgot about it, so thanks for pointing it out @xFrednet!)

Deny warnings in every main sub-crate 

---

clippy_lints/src/implicit_return.rs
tests/ui/crashes/ice-7231.rs

fixes: #7231
changelog: Fix ICE in `implicit_return` for async functions

Fix ICE in `implicit_return`

---

clippy_lints/src/inherent_impl.rs
clippy_lints/src/lib.rs
tests/ui/impl.rs
tests/ui/impl.stderr

fixes: #5772
changelog: Treat different generic arguments as different types in `multiple_inherent_impl`

Don't lint `multiple_inherent_impl` with generic arguments

---

clippy_lints/src/utils/internal_lints/metadata_collector.rs

I noticed while working on the website adaption that the lint groups still had the `clippy::` prefix in the JSON output. This PR removes this prefix and adds a `level` field to each lint and with that simplifies the website display and saves performance.
The deprecated lints get are assigned to the level `none`. This is a bit different in comparison to the current lint list, but I believe that this will look better overall. Unless there is any argument against this :).
That's it just a small baby PR in comparison to the original monster ^^
---
See: #7172 for the full metadata collection to-do list or to suggest a new feature in connection to it.
---
r? @flip1995

Adding the default lint level to the metadata collection

---

clippy_lints/src/lib.rs

This speeds up the metadata collection by 2-2.5x on my machine. During
metadata collection other lint passes don't have to be registered, only
the lints themselves.
cc #7172 
r? @xFrednet 

Early return from LintPass registration when collecting metadata

---

CHANGELOG.md
clippy_lints/src/lib.rs
clippy_lints/src/needless_borrow.rs
clippy_utils/src/higher.rs
clippy_utils/src/lib.rs
clippy_utils/src/visitors.rs
tests/ui/needless_borrow.fixed
tests/ui/needless_borrow.rs
tests/ui/needless_borrow.stderr
tests/ui/needless_borrow_pat.rs
tests/ui/needless_borrow_pat.stderr
tests/ui/ref_binding_to_reference.rs
tests/ui/ref_binding_to_reference.stderr

fixes: #2610
While I'm working on this, should needless_borrow be split into two? One lint for expressions and another for patterns. In expression it only lints when the compiler inserts a dereference, but for patterns it's whenever a double reference is created. I think at least the case where a double reference is needed should be split into a new lint as it's not 'needless', it can just be done without a ref binding.
For illustration:
```rust
fn foo(x: &&str) {}
match Some("test") {
// ref binding is useless here
Some(ref x) => *x,
_ => (),
}
match Some("test") {
// ref binding is useless here
Some(ref x) => x.len(),
_ => (),
}
match Some("test") {
// double reference is needed, but could be `Some(x) => foo(&x)`
Some(ref x) => foo(x),
_ => (),
}
```
changelog: Improve the suggestion …

fix `needless_borrow` suggestion

---

clippy_lints/src/eta_reduction.rs
tests/ui/eta.fixed
tests/ui/eta.rs
tests/ui/eta.stderr

fixes: #7224
changelog: Fix `redundant_closure` for `vec![]` macro in a closure with arguments

Fix `redundant_closure` for `vec![]` macro in a closure with arguments

---

clippy_lints/src/methods/from_iter_instead_of_collect.rs
tests/ui/from_iter_instead_of_collect.fixed
tests/ui/from_iter_instead_of_collect.rs
tests/ui/from_iter_instead_of_collect.stderr

First attempt at contributing, hopefully this is a good start and can be improved. :)
fixes #7259 
changelog: [`from_iter_instead_of_collect`] fix invalid suggestion involving "as Trait"

Fix invalid syntax in `from_iter_instead_of_collect` suggestion

---

clippy_lints/src/non_expressive_names.rs
tests/ui/similar_names.rs
tests/ui/similar_names.stderr

`wparam` and `lparam` are often used as generic parameter names in win32 (for example [WindowProc](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/ms633573(v=vs.85))). This PR adds them to the similar_names exception list.
changelog: [`similar_names`] don't treat wparam and lparam as similar

Allow wparam and lparam in similar_names

---

clippy_lints/src/lib.rs
clippy_lints/src/suspicious_operation_groupings.rs

This addresses #6722.
changelog: Downgrade [`suspicious_lint_operations`] to Nursery

Downgrade suspicious_op..._groupings to Nursery

---

clippy_lints/src/trait_bounds.rs
clippy_utils/src/hir_utils.rs
clippy_utils/src/lib.rs

* Use `mem::discriminant().hash()` instead of `stable_hash` for simple enums and then use `FxHasher` instead of `StableHasher`. We don't use any StableHash features.
* Use `UnHashMap` for maps keyed by spanless hash values.

Some SpanlessHash improvements

---

Cargo.toml
tests/dogfood.rs

This adds the discussed hack to touch `clippy_lints/src/lib.rs` to invalidate cargos cache and force metadata collection. I've decided to use the [`filetime`](https://github.com/alexcrichton/filetime) crate instead of the touch command to make is cross-platform and just cleaner in general. Looking at the maintainers I would say that it's a save crate to use xD.
---
cc: #7172 I know this ID without looking it up now... This is not good
r? @flip1995

Adding the ability to invalidate caches to force metadata collection

---

clippy_lints/src/loops/needless_collect.rs
clippy_lints/src/misc.rs
clippy_lints/src/no_effect.rs
clippy_utils/src/diagnostics.rs
tests/ui/needless_collect_indirect.rs
tests/ui/no_effect.rs

changelog: Fix `#[allow(..)]` over statements for [`needless_collect`], [`short_circuit_statement`] and [`unnecessary_operation`]
Fixes #7171
Fixes #7202

Fix allow on some statement lints

---

clippy_lints/src/missing_doc.rs
tests/ui/missing-doc-impl.rs
tests/ui/missing-doc-impl.stderr

changelog: Fix [`missing_docs_in_private_items`] false negative when the item has any `#[name = "value"]` attribute
Closes #7247 (decided not to use the rustc method since it calls `Session::check_name`, which is for rustc only)

Fix missing_docs_in_private_items false negative

---

clippy_lints/src/functions/too_many_lines.rs
tests/ui/crashes/auxiliary/ice-7272-aux.rs
tests/ui/crashes/ice-7272.rs

fixes: #7272
fixes: #7286
#7272 looks like it's caused by a bug in rust-c. The span it's giving for the closure is:
```rust
$crate:: $lower($d arg) }
}
}
}
```
The correct span would be `$crate:: $lower($d arg)` without all the closing braces.
#7286 is definitely a clippy bug

Fix ICE in `too_many_lines`

---

clippy_lints/src/functions/not_unsafe_ptr_arg_deref.rs
tests/ui/functions.stderr

changelog: Improved message for the ['not_unsafe_ptr_arg_deref'] lint
Doesn't close any issue, but implements a suggestion from https://github.com/rust-lang/rust-clippy/issues/3045#issuecomment-791556803.

Improve message for `not_unsafe_ptr_arg_deref` lint

---

.github/workflows/clippy_bors.yml

This reverts commit 716d03f86bc9d72e56c2d803fd76ff44f29c9b3a.
This is no longer necessary, since rustup 1.24.2 is now the default
version on the windows runner.

Revert "CI: update rustup before installing the toolchain on windows"

---

clippy_utils/src/consts.rs
tests/ui/assertions_on_constants.rs

This makes clippy understand that `cfg!(..)` is not just a hardcoded `true` or `false` (even though it expands to one of those).
cc @khyperia
changelog: Don't treat `cfg!(..)` as a constant in [`assertions-on-constants`]

Don't warn about `cfg!(..)` as a constant in assertions

---

clippy_lints/src/loops/needless_collect.rs

changelog: Fix [`needless_collect`] weird output when a binding is shadowed
Fixes #7200

Fix needless_collect with binding shadowing

---

doc/release.md

r? @xFrednet 
[Rendered](https://github.com/flip1995/rust-clippy/blob/doc-release-stable-branch/doc/release.md)

Release doc: add explanation for updating the stable branch

---

clippy_lints/src/default_numeric_fallback.rs
tests/ui/auxiliary/macro_rules.rs
tests/ui/default_numeric_fallback.rs
tests/ui/default_numeric_fallback.stderr

fixes #7304 
changelog: Fix `default_numeric_fallback` FP with external macro expansion

Fix FP in `default_numeric_fallback` with external macro expansion

---

clippy_lints/src/loops/while_let_on_iterator.rs
clippy_utils/src/lib.rs
tests/ui/while_let_on_iterator.fixed
tests/ui/while_let_on_iterator.rs
tests/ui/while_let_on_iterator.stderr

fixes: #7249
A future improvement would be to check if the closure is being used as `FnOnce`, in which case the original suggestion would be correct.
changelog: Suggest `&mut iter` inside a closure for `while_let_on_iterator`

fix `while_let_on_iterator` suggestion in a closure

---

clippy_lints/src/semicolon_if_nothing_returned.rs
clippy_utils/src/lib.rs
tests/ui/semicolon_if_nothing_returned.rs
tests/ui/semicolon_if_nothing_returned.stderr

Currently the [`semicolon_if_nothing_returned`](https://rust-lang.github.io/rust-clippy/master/index.html#semicolon_if_nothing_returned) lint fires in unwanted situations where a block only spans one line. An example of this was given in #7324. This code:
```rust
use std::mem::MaybeUninit;
use std::ptr;
fn main() {
let mut s = MaybeUninit::<String>::uninit();
let _d = || unsafe { ptr::drop_in_place(s.as_mut_ptr()) };
}
```
yields the following clippy error:
```
error: consider adding a `;` to the last statement for consistent formatting
--> src/main.rs:6:26
|
6 |     let _d = || unsafe { ptr::drop_in_place(s.as_mut_ptr()) };
|                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: add a `;` here: `ptr::drop_in_place(s.as_mut_ptr());`
|
= note: `-D …
```

Fix false positive on `semicolon_if_nothing_returned`

---

clippy_lints/src/utils/conf.rs
tests/ui/doc.rs

For the doc-markdown lint.
changelog: Add FreeBSD as identifier not needing ticks for ``[`doc-markdown`]`` lint.

Add FreeBSD as identifier not needing ticks

---

clippy_lints/src/default.rs
tests/ui/field_reassign_with_default.rs
tests/ui/field_reassign_with_default.stderr

Fixes #7155
Producing a good suggestion for this lint is already hard when no macros
are involved. With macros the lint message and the suggestion are just
confusing. Since both, producing a good suggestion and figuring out if
this pattern can be re-written inside a macro is nearly impossible, just
bail out.
changelog: [`field_reassign_with_default`] No longer triggers in macros
---
No that our reviewing queue is under control, I want to start hacking on Clippy myself again. Starting with an easy issue to get back in :)

Don't trigger `field_reassign_with_default` in macros

---

clippy_lints/src/use_self.rs
tests/ui/use_self.fixed
tests/ui/use_self.rs
tests/ui/use_self.stderr

changelog: Fix [`use_self`] false positives on type parameters
Fixes #4140
Fixes #7139

Fix use_self FPs on type params

---

clippy_lints/src/disallowed_method.rs
clippy_lints/src/disallowed_type.rs
tests/ui-toml/toml_disallowed_method/clippy.toml
tests/ui-toml/toml_disallowed_type/clippy.toml
tests/ui-toml/toml_disallowed_type/conf_disallowed_type.stderr

changelog: Remove the need for fully qualified paths in disallowed_method and disallowed_type
After fixing this issue in [import_rename](https://github.com/rust-lang/rust-clippy/pull/7300#discussion_r650127720) I figured I'd fix it for these two.
If this does in fact fix the **Known problems:** section I was planning to remove them from both lints after confirmation.

Remove requirement of fully qualified path for disallowed_method/type

---

doc/common_tools_writing_lints.md

The [docs](https://github.com/rust-lang/rust-clippy/blob/master/doc/common_tools_writing_lints.md) had an incorrect link for "Checking if a type defines a specific method".

Fix link in docs

---

clippy_lints/src/utils/internal_lints/metadata_collector.rs

Fixes code fence block in the metadata collector to change ` ``` ` or ` ```ignore` or ` ```rust,ignore` to ` ```rust`. This makes syntax highlighting work more consistently on the website.

Fix metadata code block syntax highlighting

---

tests/compile-test.rs

Related to #7343 
When I first met this error I was pretty much confused, so I thought it may be a good idea to:
- Give a hint on what to do to users that don't want to dig into specifics and just want to quickly resolve the issue.
- Give a link for those who are interested in details.

Improve panic message on "Found multiple rlibs" error in compile-test

---

clippy_lints/src/deprecated_lints.rs
clippy_lints/src/lib.rs
tests/ui/deprecated.stderr

Problem:
for code like
````rust
#![warn(clippy::wrong_pub_self_convention)]
fn main() {
println!("Hello, world!");
}
````
clippy will issue a warning to use a clippy.toml option instead:
````
warning: lint `clippy::wrong_pub_self_convention` has been removed: set the `avoid_breaking_exported_api` config option to `false` to enable the `wrong_self_convention` lint for public items
--> src/main.rs:2:9
|
2 | #![warn(clippy::wrong_pub_self_convention)]
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(renamed_and_removed_lints)]` on by default
````
But using the lint name as seen in the warning message
`echo "avoid_breaking_exported_api = true\n" > clippy.toml`
Will cause an error:
````
error: error reading Clippy's configuration file `/tmp/clippytest/clippy.toml`: unknown field …
```

Fix wrong config option being suggested for deprecated wrong_pub_self_convention lint

---

clippy_lints/src/utils/conf.rs
util/lintlib.py

The deploy script on master currently runs into an error (See [log](https://github.com/rust-lang/rust-clippy/runs/2865828873)) due to the new configuration documentation added in #7299. The current documentation collection for the configuration macro sadly doesn't support multiline doc comments. This will be changes in the future with the new metadata collector tracked in #7172 For now we have to use `<br>` inside doc comments to add paragraphs.
This PR restricts `define_Conf!` macro to single lines and adds a comment explaining the reasoning behind it. It also adjusted the actual document parsing to fix a bug. (The parsing was automatically stopping on the first curly bracket, even if it was part of a doc comment).

Fixed broken deploy script due to multiline configuration docs

---

clippy_lints/src/methods/mod.rs
tests/ui/zero_offset.rs
tests/ui/zero_offset.stderr

The `zst_offset` lint was broken by a refactoring regression in 21083875d211c29fcfa4a21fcd66d4601d2b618b. In the invocation of the `zst_offset` check [here](https://github.com/rust-lang/rust-clippy/commit/21083875d211c29fcfa4a21fcd66d4601d2b618b#diff-7f73f6fe28c04b654223c09c42fe02937d2351fc58a91d21ab812aaf6f9b185dR1927), we shadow the already-destructured receiver `recv`, and accidentally pass the first argument of the method as if it were the receiver.
This was not caught because the UI test expectation was never correct (a bad cast obscured the actual test result).
This PR:
- Fixes the existing test expectation
- Tests both `const` and `mut` raw pointers
- Passes the actual receiver to the lint's implementation
Fixes #7395.
changelog: Fix [`zst_offset`] invocation and test

Fix invocation of `zst_offset` lint

---

clippy_lints/src/blacklisted_name.rs
clippy_lints/src/wildcard_imports.rs
clippy_utils/src/lib.rs
tests/ui/blacklisted_name.rs

---
fixed #7305 
changelog: `blacklisted_name` lint is not spawned in the test context anymore.

Do not spawn blacklisted_name lint in test context

---

clippy_dev/src/main.rs
clippy_dev/src/setup/git_hook.rs
clippy_dev/src/setup/mod.rs
clippy_dev/src/setup/vscode.rs
util/etc/vscode-tasks.json

This PR adds a setup command to `clippy dev` that installs tasks into the Clippy vscode workspace. These might be useful as they be used via shortcuts and are accessible over the GUI. The available tasks are:
* `cargo check` (standard Linux shortcut `[ctrl] + [shift] + b`)
* `cargo dev fmt`
* `cargo uitest` (with a comment how to add the `TESTNAME` environment value)
* `cargo test`
* `cargo dev bless`
---
only internal changes again. cc #5394
r? @flip1995 This should be pretty much the same as the other `cargo dev setup` commands. Would you mind reviewing this? :upside_down_face:

Added `cargo dev setup vscode-tasks` for simplicity

---

clippy_lints/src/use_self.rs

Mainly to remove an extra visit and simplify the "in body?" logic.

Simplify use_self impl

---

clippy_lints/src/matches.rs
tests/ui/match_same_arms.stderr
tests/ui/match_same_arms2.stderr

fixes #7331
Follow-up to #7377 
This PR improves the lint message for `match-same-arms` lint and adds `todo!(..)`  example to the lint docs.

Improve lint message for match-same-arms lint

---

tests/ui/auxiliary/non-exhaustive-enum.rs
tests/ui/wildcard_enum_match_arm.fixed
tests/ui/wildcard_enum_match_arm.rs
tests/ui/wildcard_enum_match_arm.stderr

Every time we add something to `std::io::ErrorKind`, this clippy test breaks. This is especially annoying because it usually only happens when bors is testing it (e.g. in a rollup), as clippy tests are normally not run for PRs with just library changes.
For example: https://github.com/rust-lang/rust/pull/85746#issuecomment-868886893
This changes the test to not rely on the definition from std.
---

Don't use exact definition of std's ErrorKind in test.

---

clippy_lints/src/doc.rs
tests/ui/doc/unbalanced_ticks.rs

fixes #7421 
changelog: don't lint unbalanced tick marks in code blocks

fix doc_markdown false positive

---

clippy_lints/src/use_self.rs
tests/ui/crashes/ice-7423.rs

changelog: Fix ICE #7423
r? @flip1995

Fix use_self ICE

---

clippy_lints/src/nonstandard_macro_braces.rs
tests/ui-toml/nonstandard_macro_braces/auxiliary/proc_macro_derive.rs
tests/ui-toml/nonstandard_macro_braces/conf_nonstandard_macro_braces.rs
tests/ui-toml/nonstandard_macro_braces/conf_nonstandard_macro_braces.stderr

fixes #7422
changelog: fixes false positives in [`nonstandard_macro_braces`]

Fix emitting in nested (proc_)macros for nonstandard_macro_braces lint

---

CHANGELOG.md
clippy_lints/src/lib.rs
clippy_lints/src/strlen_on_c_strings.rs
clippy_utils/src/paths.rs
clippy_utils/src/ty.rs
tests/ui/strlen_on_c_strings.rs
tests/ui/strlen_on_c_strings.stderr

~~This is WIP, linting in case of `CString` has been added, but for `CStr`, its diagnostic item needs to be available for clippy. 
[PR that adds diagnostic item for CStr on rust repo](https://github.com/rust-lang/rust/pull/85439).~~
Ready for the review. Please take a look. 
fixes #7145
changelog: Add new lint: `strlen_on_c_strings`, that lints on `libc::strlen(some_cstring.as_ptr())`

Add new lint: `strlen_on_c_strings`

---

clippy_lints/src/panic_unimplemented.rs
tests/ui/panicking_macros.rs

This PR fixes a false-positive in `clippy::panic` when using the `assert` macro with its optional message parameter.
Fixes: #7433 
changelog: `panic_unimplemented.rs`: added condition to exclude `assert` macro, similar to `debug_assert`
changelog: `panicking_macros.rs`: relevant tests to check for `assert` usage.

Fix false-positive `assert` in `panic`

---

clippy_lints/src/cargo_common_metadata.rs
clippy_lints/src/copies.rs
clippy_lints/src/multiple_crate_versions.rs
clippy_lints/src/utils/internal_lints.rs
clippy_lints/src/wildcard_dependencies.rs
clippy_utils/src/lib.rs

Just a quick rename of a utilities function. `run_lints` kinda suggested that the lints were run by this function. But the only thing this function does is to check if the lints are enabled in the context of the `hir_id`

Rename run_lints -> lints_enabled

---

clippy_lints/src/cargo_common_metadata.rs
clippy_lints/src/copies.rs
clippy_lints/src/dereference.rs
clippy_lints/src/derive.rs
clippy_lints/src/inherent_impl.rs
clippy_lints/src/len_zero.rs
clippy_lints/src/manual_map.rs
clippy_lints/src/matches.rs
clippy_lints/src/multiple_crate_versions.rs
clippy_lints/src/ptr.rs
clippy_lints/src/strings.rs
clippy_lints/src/unicode.rs
clippy_lints/src/utils/internal_lints.rs
clippy_lints/src/wildcard_dependencies.rs
clippy_utils/src/lib.rs

r? @camsteffen 
cc https://github.com/rust-lang/rust-clippy/pull/7448#issuecomment-876497862
I haven't added a variant with `last_node_with_lint_attrs` yet, since I didn't see a usecase for this. Also this field is not documented, so I'm wondering how it behaves with command line lints and so on.

Remove lints_enabled

---

clippy_lints/src/unused_unit.rs

(don't think this is worth a changelog mention)

Add fixed example to unused_unit documentation

---

clippy_lints/src/eta_reduction.rs
clippy_utils/src/usage.rs
tests/ui/eta.fixed
tests/ui/eta.rs
tests/ui/eta.stderr

fixes #6903
changelog: suggest `&mut` for redundant FnMut closures

suggest `&mut` for redundant FnMut closures

---

clippy_lints/src/copies.rs
tests/ui/branches_sharing_code/false_positives.rs

Closes rust-lang/rust-clippy#7369
Related rust-lang/rust-clippy#7452 I'm still thinking about the best way to fix this. I could simply add another visitor to ensure that the moved expressions don't modify values being used in the condition, but I'm not totally happy with this due to the complexity. I therefore only documented it for now 
changelog: [`branches_sharing_code`] fixed false positive where block expressions would sometimes be ignored.

FP fix and documentation for `branches_sharing_code` lint

---

doc/basics.md

We often get messages on Zulip asking how to install and run Clippy from source. This adds instructions to the readme. I also added a note explaining that `cargo install --path . --force` is bad, which I just decided after some investigating. I use macOS. It would be nice to get some tests on other platforms to see if this is correct.

Add instructions to run from source

---

clippy_utils/src/ty.rs
tests/ui/crashes/ice-7410.rs

Fixes #7410
changelog: Fix ICE in `redundant_pattern_matching` in `no_std` crates.

Fix ICE in redundant_pattern_matching

---

clippy_utils/src/lib.rs
tests/ui/crashes/ice-7340.rs

fixes: #7340
changelog: Fix ICE in `modulo_one` in const contexts

Fix ICE in `is_integer_const`

---

clippy_lints/src/assign_ops.rs
clippy_lints/src/eq_op.rs
clippy_lints/src/suspicious_trait_impl.rs
clippy_utils/src/higher.rs
clippy_utils/src/lib.rs
clippy_utils/src/sugg.rs
tests/ui/suspicious_arithmetic_impl.stderr

Use lang items for BinOp lints

---

CHANGELOG.md
clippy_lints/src/lib.rs
clippy_lints/src/self_named_constructor.rs
tests/ui/crashes/ice-6179.rs
tests/ui/issue_4266.rs
tests/ui/missing-doc-impl.rs
tests/ui/missing-doc-impl.stderr
tests/ui/missing_const_for_fn/cant_be_const.rs
tests/ui/missing_const_for_fn/could_be_const.stderr
tests/ui/needless_bool/fixable.fixed
tests/ui/needless_bool/fixable.rs
tests/ui/needless_bool/fixable.stderr
tests/ui/self_named_constructor.rs
tests/ui/self_named_constructor.stderr
tests/ui/unit_arg.rs
tests/ui/unit_arg.stderr
tests/ui/use_self.fixed
tests/ui/use_self.rs
tests/ui/use_self.stderr

Adds the `self_named_constructor` lint for detecting when an implemented method has the same name as the type it is implemented for.
changelog: [`self_named_constructor`]
closes: #7142

New lint: [`self_named_constructor`]

---

clippy_lints/src/zero_sized_map_values.rs
tests/ui/issue-7447.rs

Fixes: #7447
changelog: fix ICE in [`zero_sized_map_values`]

Add check if ty has_escaping_bound_vars in zero_sized_map_values lint

---

clippy_lints/src/non_expressive_names.rs
tests/ui/similar_names.stderr

changelog: [`similar_names`] lint no longer suggests to insert or add an underscore to "fix" too similar names

similar_names: No longer suggest inserting or appending an underscore

---

clippy_lints/src/repeat_once.rs

Documents the fact that the `repeat_once` lint evaluates constant expressions
---
closes: #7306 
(I don't think it's worth a change log entry, as nothing has really changed)
r? @giraffate as you've implemented the lint and were part of the discussion in the issue :upside_down_face:

Documented constant expression evaluation for `repeat_once`

---

clippy_lints/src/utils/author.rs
tests/ui/author/blocks.rs
tests/ui/author/blocks.stdout
tests/ui/author/for_loop.stdout
tests/ui/author/if.stdout
tests/ui/author/matches.stdout

* Use `Debug` instead of re-implementing it for some things
* Fix block trailing expression handing
* Don't double print on stmt/expr with `#[clippy::author]` attribute

Some `clippy::author` improvements

---

clippy_lints/src/needless_continue.rs
tests/ui/needless_continue.rs
tests/ui/needless_continue.stderr

Fixes #7417
changelog: Report [`needless_continue`] in `loop { continue; }` case

Enhance needless continue to detect loop {continue;}

---

clippy_lints/src/new_without_default.rs
tests/ui/new_without_default.rs
tests/ui/new_without_default.stderr

Fixes: rust-lang/rust-clippy#7220
changelog: [`new_without_default`]: The `Default` impl block type doesn't use the full type path qualification 
Have a nice day to everyone reading this :upside_down_face:

Prefer a code snipped over formatting the self type (`new_without_default`)

---

tests/compile-test.rs

Now you can do `rm <paste>` and 🐇💨 
```text
thread 'compile_test' panicked at '
----------------------------------------------------------------------
ERROR: Found multiple rlibs for crates: `clippy_lints`, `clippy_utils`
Try running `cargo clean` or remove the following files:
target/debug/deps/libclippy_lints-9117c875159004e0.rlib \
target/debug/deps/libclippy_lints-fe45157be7ff9444.rlib \
target/debug/deps/libclippy_utils-5eba1e07a9846ed0.rlib \
target/debug/deps/libclippy_utils-ccbc08fcf64de262.rlib
For details on this error see https://github.com/rust-lang/rust-clippy/issues/7343
----------------------------------------------------------------------
```

Improve conflicting rlibs error again

---

clippy_lints/src/from_over_into.rs
clippy_lints/src/implicit_hasher.rs
clippy_lints/src/infinite_iter.rs
clippy_lints/src/loops/explicit_into_iter_loop.rs
clippy_lints/src/loops/explicit_iter_loop.rs
clippy_lints/src/loops/for_kv_map.rs
clippy_lints/src/matches.rs
clippy_lints/src/methods/get_unwrap.rs
clippy_lints/src/methods/iter_count.rs
clippy_lints/src/methods/or_fun_call.rs
clippy_lints/src/mut_key.rs
clippy_lints/src/needless_pass_by_value.rs
clippy_lints/src/new_without_default.rs
clippy_lints/src/ptr.rs
clippy_lints/src/size_of_in_element_count.rs
clippy_lints/src/transmute/mod.rs
clippy_lints/src/transmute/unsound_collection_transmute.rs
clippy_lints/src/transmuting_null.rs
clippy_lints/src/types/linked_list.rs
clippy_lints/src/useless_conversion.rs
clippy_lints/src/zero_sized_map_values.rs
clippy_utils/src/lib.rs
clippy_utils/src/paths.rs
tests/ui-internal/match_type_on_diag_item.rs
tests/ui-internal/match_type_on_diag_item.stderr

Clippy still uses a bunch of paths in places that could easily use already defined diagnostic items. This PR updates all references to such paths and also removes a bunch of them that are no longer needed after this cleanup.
Some paths are also used to construct new paths and can therefore not be removed that easily. I've added a doc comment to those instances that recommends the use of the diagnostic item where possible.
And that's it, cleaning crew signing off :broom: :wastebasket: 
---
(only internal improvements)
cc: #5393

Use diagnostic items where possible

---

clippy_lints/src/disallowed_type.rs
clippy_utils/src/lib.rs
tests/ui-toml/toml_disallowed_type/clippy.toml
tests/ui-toml/toml_disallowed_type/conf_disallowed_type.rs
tests/ui-toml/toml_disallowed_type/conf_disallowed_type.stderr

Closes #6845
changelog: Enable the banning of primitive types in [`disallowed_type`]

Add primitive type support to disallowed_type lint

---

src/main.rs
tests/dogfood.rs

This commit closes #7389. As stated in the issue, `cargo clippy --help`
provides explanation for some flags and states that the rest are same
as in `cargo check --help`, even though some clippy specific flags
exist.
This commit extends the `cargo clippy --help` with two additional flags,
- `cargo clippy --fix`
- `cargo clippy --no-deps`
If there are more flags which are not present in `cargo check --help`
please bring these to my attention, I will include these aswell.
For now, I noticed only the two flags mentioned above.
changelog: `cargo clippy --help` now explains additional flags missing in `cargo check --help`.

Explain flags missing in cargo check in --help

---

clippy_lints/src/utils/internal_lints/metadata_collector.rs
util/gh-pages/index.html

This is close to the end of a long living project to rewrite the lint metadata collection for Clippy. Progress on this has been tracked in #7172. This PR adds one of the last missing puzzle pieces, the actual display of all the changes that have been done in the background. A preview can be seen here: [Clippy's lint list](https://xfrednet.github.io/rust-clippy/master/index.html)
The styling has been discussed on [zulip](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Styling.20feedback.20for.20Clippy's.20lint.20list/near/239601067) but is still open to suggestion.
Side note: It has been fun working on the website where we don't have unit tests and everything is just tested by playing around. However, it's good that this chaos is contained into this one part of Clippy. …

Adapting the lint list to Clippy's new metadata format

---

CHANGELOG.md

This has again been a bit of work, but I'm happy to notice that my English is still improving, and I'm getting faster at these things. That's a very nice side effect of contributing and getting feedback on reviews :blush:
Moving on, there were a few things that I was unsure about:
* The PR rust-lang/rust#86717 changes an old entry in the change log, is this worth mentioning? I've left it out for now.
* The stabilization of `cargo clippy --fix` is quite awesome and important IMO. It sadly gets a bit lost in the *Other* entry, as it's the last one. Do we maybe want to move it somewhere else or change the headline order for this release?
* I've listed the introduction of the new `suspicious` group under the *Moves and Deprecations* section. Is this alright, or should it be moved to the …

Updated changelog for 1.55

---

clippy_lints/src/unnested_or_patterns.rs

changelog: removed `or_patterns` feature gate in the code example for the [`unnested_or_patterns`] lint

Remove `or_patterns` feature gate in example

---

CHANGELOG.md

Hey, I've noticed that the change log for 1.54 references the avoid_breaking_exported_api configuration with its Rust name, not the name it actually has in the config file. This should fix it for everyone, as the blog post references our change log on the master branch. Just a very small PR xD
(This is the change log xD)
r? @flip1995

Updated config value name in change log for 1.54

---

clippy_lints/src/loops/while_let_on_iterator.rs
tests/ui/while_let_on_iterator.fixed
tests/ui/while_let_on_iterator.rs
tests/ui/while_let_on_iterator.stderr

fixes: #7510
changelog: Suggest re-borrowing mutable references in `while_let_on_iterator`

Fix `while_let_on_iterator` - #7510

---

clippy_lints/src/methods/map_flatten.rs
tests/ui/map_flatten.fixed
tests/ui/map_flatten.rs
tests/ui/map_flatten.stderr

Closes #7496 
changelog: `[map_flatten]` handles `Result` type

Cover `Result` on `map_flatten` lint

---

.github/workflows/clippy.yml
.github/workflows/clippy_bors.yml
clippy_lints/src/utils/conf.rs
clippy_lints/src/utils/internal_lints/metadata_collector.rs

Updated the `define_Conf!` macro to support multi-line doc comments for readability. This also enables configuration documentation to have multiple paragraphs.
I've also added the `metadata-collector-lint` feature to the CI build and testing tasks. (I would think that we want this, now that we officially switched over)  
---
Now a small informal explanation what this PR changes (just for fun): 
* *Once upon a time there was a monster. It was handsome, supportive and happy to dig through the best source code it has ever seen. Spanning over hundreds of lines and reading over complete crates, it was purely marvels!*
*However, there was one region in its territory that wasn't clean and well formatted like the rest. That was the mighty `define_Conf` macro. The monster would have cleaned it up …

Updated `define_Conf!` to support multi-line doc comments

---

.github/workflows/remark.yml
doc/basics.md

In https://github.com/rust-lang/rust-clippy/pull/7528#issuecomment-892281632, remark-cli version has been updated recently and it requires to use ESM module: https://github.com/remarkjs/remark/releases/tag/14.0.0. Node version in CI was v10.24.1, it seems to be old.

Use node v12.x in CI

---

clippy_lints/src/needless_borrow.rs

needless_borrow: try to make lint example a bit more illustrating

---

clippy_lints/src/methods/extend_with_drain.rs
tests/ui/extend_with_drain.fixed
tests/ui/extend_with_drain.rs
tests/ui/extend_with_drain.stderr

fixes: #7524 
This PR is related to issue #7524 
changelog:  [`extend_with_drain`] Improve code suggestion for mutable and immutable references

fix bug on mutable ref

---

clippy_lints/src/functions/mod.rs
clippy_lints/src/functions/too_many_lines.rs
tests/ui-toml/functions_maxlines/test.rs
tests/ui-toml/functions_maxlines/test.stderr

changelog: don't emit the [`too_many_lines`] lint inside closures to avoir duplicated diagnostics.
Fixes #7517.

Don't emit `too_many_lines` for closures

---

clippy_lints/src/types/mod.rs

Add missing backtick in docs for `redundant_allocation`

---

clippy_lints/src/as_conversions.rs
clippy_lints/src/else_if_without_else.rs
clippy_lints/src/if_not_else.rs
clippy_lints/src/items_after_statements.rs
clippy_lints/src/literal_representation.rs
clippy_lints/src/methods/from_iter_instead_of_collect.rs
clippy_lints/src/misc_early/mod.rs
clippy_lints/src/misc_early/unneeded_field_pattern.rs
clippy_lints/src/redundant_closure_call.rs
clippy_lints/src/reference.rs
clippy_lints/src/unused_unit.rs

- avoid using `SourceMap::span_to_snippet` directly and use `clippy_utils::source::snippet_opt` instead
- don't use `LintContext::sess()` on `EarlyContext`s which have a `sess` field directly available, saving the import of `LintContext`

Cleanup usage of `span_to_snippet` and `LintContext::sess`

---

clippy_lints/src/nonstandard_macro_braces.rs
tests/ui-toml/nonstandard_macro_braces/clippy.toml
tests/ui-toml/nonstandard_macro_braces/conf_nonstandard_macro_braces.rs
tests/ui-toml/nonstandard_macro_braces/conf_nonstandard_macro_braces.stderr

changelog: Fix FP in [`nonstandard_macro_braces`] lint

Fix nonstandard_macro_braces FP and docs of disallowed_types

---

clippy_lints/src/pass_by_ref_or_value.rs
tests/ui/trivially_copy_pass_by_ref.rs
tests/ui/trivially_copy_pass_by_ref.stderr

changelog: properly handle `Self` type for [`trivially_copy_pass_by_ref`].
Fixes #7518

Properly handle `Self` type for `trivially_copy_pass_by_ref`

---

clippy_lints/src/loops/never_loop.rs
tests/ui/never_loop.stderr

changelog: suggest using an `if let` statement instead of a `for` loop that [`never_loop`]s
Fixes #7537, r? @camsteffen.

`never_loop`: suggest using an `if let` instead of a `for` loop

---

clippy_lints/src/no_effect.rs
tests/ui/no_effect.stderr

I noticed during last PR that range expression is `ExprKind::Struct` while inclusive range is `ExprKind::Call` which was why it was not handled. This PR adds check for this case.
changelog: [`no_effect]` Report inclusive range in no_effect lint

No effect inclusive range

---

clippy_lints/src/non_expressive_names.rs
tests/ui/similar_names.rs
tests/ui/similar_names.stderr

changelog: [`similar_names`] no longer complains about `iter` and `item` being too similar

similar_names: allow "iter" and "item"

---

clippy_lints/src/lib.rs
clippy_lints/src/types/mod.rs
clippy_lints/src/types/rc_mutex.rs
clippy_lints/src/utils/conf.rs
tests/ui/box_vec.rs
tests/ui/box_vec.stderr
tests/ui/linkedlist.rs
tests/ui/linkedlist.stderr
tests/ui/rc_mutex.rs
tests/ui/rc_mutex.stderr

This PR empowers our lovely `avoid-breaking-exported-api` configuration value to also influence the emission of lints inside the `types` module. 
(That's pretty much it, not really a change worthy of writing a fairy tale about. Don't get me wrong, I would love to write a short one, but I sadly need to study now).
---
Closes: rust-lang/rust-clippy#7489
changelog: The `avoid-breaking-exported-api` configuration now also works for [`box_vec`], [`redundant_allocation`], [`rc_buffer`], [`vec_box`], [`option_option`], [`linkedlist`], [`rc_mutex`]
changelog: [`rc_mutex`]: update the lint message to comply with the normal format
---
r? @camsteffen, as you implemented the configuration value
cc: @flip1995, as we've discussed this change in rust-lang/rust-clippy#7308

Use `avoid-breaking-exported-api` configuration in types module

---

clippy_lints/src/methods/filter_next.rs
tests/ui/auxiliary/option_helpers.rs
tests/ui/methods.rs

fixes #7561
changelog: Fix false positive on [`filter_next`] when a method does not implement `Iterator`

Fix false positive on `filter_next`

---

lintcheck/Cargo.toml
lintcheck/src/main.rs

When lintcheck is run on local crates it copies the crate to `target/lintcheck/sources/crate_name` on the first run only.
Then in subsequent runs of lintcheck it reuses this same copy.
This caching behaviour makes sense when dealing with immutable crates.io releases and git commits.
However it is quite surprising that the changes to my local crate are not used when I run lintcheck.
To fix this I removed the copy, instead clippy runs directly off the provided crate folder.
I have tested this and have not observed any negative effects from doing this.
But maybe i'm missing something as im not familiar with clippy!
Alternatively we could make it copy the entire crate every run, but that seems problematic to me as multi-gigabyte target folders will take a long time to copy and …

lintcheck always copies in a fresh crate when provided with a crate path

---

clippy_lints/src/entry.rs
clippy_lints/src/manual_map.rs
clippy_utils/src/lib.rs
tests/ui/entry.fixed
tests/ui/entry.rs
tests/ui/entry.stderr
tests/ui/entry_btree.fixed
tests/ui/entry_btree.rs
tests/ui/entry_btree.stderr
tests/ui/manual_map_option_2.fixed
tests/ui/manual_map_option_2.rs
tests/ui/manual_map_option_2.stderr

fixes: #7413 
This only fixes the specific problem from #7413, not the general case. The full fix requires interacting with the borrow checker to determine the lifetime of all the borrows made in the function. I'll open an issue about it later.
changelog: Don't suggest using `map` when the option is borrowed in the match, and also consumed in the arm.
changelog: Locals declared within the would-be closure will not prevent the closure from being suggested in `manual_map` and `map_entry`

Manual map 7413

---

clippy_lints/src/loops/manual_flatten.rs
tests/ui/manual_flatten.rs

Fixes #6784
Fixes #7538 
`manual_flatten` should not trigger when `if let` match expression will be used.
changelog: [`manual_flatten`] checks for expr usage after `if let`

Check expr usage for  `manual_flatten`

---

clippy_lints/src/derive.rs

The known issue was fixed in #6993. I missed updating the docs then, so it's happening now.

Update docs for `expl_impl_clone_on_copy`

---

clippy_lints/src/utils/conf.rs
clippy_lints/src/utils/internal_lints/metadata_collector.rs
doc/adding_lints.md

Just small documentation updates after the merge of the new metadata collection. I'm also here to deliver on the promised fairy tale:
*Once upon a time, there was a world with many languages. One of the oldest was C a very versatile language that gave great power for the cost of great complexity and manual work. C was so powerful that it was able to create new languages. There is Java a versatile language often used by companies and in formal settings. Python that focused on readability and rapid prototyping capabilities. JavaScript which has some interesting edge cases but was still loved and widely used in the world. Together they build the foundation of our world and continue to shape the interactions between kingdoms worldwide.*
*C ruled as the king of Linux and other operating …

Small documentation update for the new metadata_collector

---

CHANGELOG.md
clippy_lints/src/feature_name.rs
clippy_lints/src/lib.rs
tests/ui-cargo/feature_name/fail/Cargo.toml
tests/ui-cargo/feature_name/fail/src/main.rs
tests/ui-cargo/feature_name/fail/src/main.stderr
tests/ui-cargo/feature_name/pass/Cargo.toml
tests/ui-cargo/feature_name/pass/src/main.rs

Add new lint [`negative_feature_names`] to detect feature names with prefixes `no-` or `not-` and new lint [`redundant_feature_names`] to detect feature names with prefixes `use-`, `with-` or suffix `-support`
changelog: Add new lint [`negative_feature_names`] and [`redundant_feature_names`]

Add new lint `negative_feature_names` and `redundant_feature_names`

---

clippy_lints/src/copies.rs
clippy_lints/src/lib.rs

changelog: Move [`branches_sharing_code`] to nursery
...since there are quite a few [open bugs](https://github.com/rust-lang/rust-clippy/issues?q=is%3Aissue+is%3Aopen+branches_sharing_code).

Move branches_sharing_code to nursery

---

clippy_lints/src/types/redundant_allocation.rs
tests/ui/redundant_allocation.rs
tests/ui/redundant_allocation.stderr

Fixes #7487
changelog: [`redundant_allocation`] - allow `Box<Box<dyn T>>` which replaces wide pointers with thin pointers

redundant_allocation: fix 7487

---

clippy_lints/src/no_effect.rs
tests/ui/unnecessary_operation.fixed
tests/ui/unnecessary_operation.stderr

Attempts to fix: #7412 
changelog: Don't report function calls used in indexing as unnecessary operation. [`unnecessary_operation`]

Don't report function calls as unnecessary operation if used in array index

---

CHANGELOG.md
clippy_lints/src/lib.rs
clippy_lints/src/module_style.rs
tests/ui-cargo/module_style/fail_mod/Cargo.toml
tests/ui-cargo/module_style/fail_mod/src/bad/inner.rs
tests/ui-cargo/module_style/fail_mod/src/bad/inner/stuff.rs
tests/ui-cargo/module_style/fail_mod/src/bad/inner/stuff/most.rs
tests/ui-cargo/module_style/fail_mod/src/bad/mod.rs
tests/ui-cargo/module_style/fail_mod/src/main.rs
tests/ui-cargo/module_style/fail_mod/src/main.stderr
tests/ui-cargo/module_style/fail_no_mod/Cargo.toml
tests/ui-cargo/module_style/fail_no_mod/src/bad/mod.rs
tests/ui-cargo/module_style/fail_no_mod/src/main.rs
tests/ui-cargo/module_style/fail_no_mod/src/main.stderr
tests/ui-cargo/module_style/pass_mod/Cargo.toml
tests/ui-cargo/module_style/pass_mod/src/bad/mod.rs
tests/ui-cargo/module_style/pass_mod/src/main.rs
tests/ui-cargo/module_style/pass_mod/src/more/foo.rs
tests/ui-cargo/module_style/pass_mod/src/more/inner/mod.rs
tests/ui-cargo/module_style/pass_mod/src/more/mod.rs
tests/ui-cargo/module_style/pass_no_mod/Cargo.toml
tests/ui-cargo/module_style/pass_no_mod/src/good.rs
tests/ui-cargo/module_style/pass_no_mod/src/main.rs

changelog: Add new [`module_style`] style lint
This is a configurable (no mod file/mod file) lint that determines if `mod.rs` is used consistently or if `mod.rs` is never used (using the new mod layout).

Add module_style lint to style

---

clippy_lints/src/option_if_let_else.rs
clippy_utils/src/lib.rs
tests/ui/option_if_let_else.fixed
tests/ui/option_if_let_else.rs
tests/ui/option_if_let_else.stderr

fixes: #5822
fixes: #6737
fixes: #7567
The inference from #6137 still exists so I'm not sure if this should be moved from the nursery. Before doing that though I'd almost want to see this split into two lints. One suggesting `map_or` and the other suggesting `map_or_else`.
`map_or_else` tends to have longer expressions for both branches so it doesn't end up much shorter than a match expression in practice. It also seems most people find it harder to read. `map_or` at least has the terseness benefit of being on one line most of the time, especially when the `None` branch is just a literal or path expression.
changelog: `break` and `continue` statments local to the would-be closure are allowed in `option_if_let_else`
changelog: don't lint in const contexts  in `option_if_let_else` …

Fix `option_if_let_else`

---

clippy_lints/src/bool_assert_comparison.rs
clippy_lints/src/lib.rs
tests/ui/bool_assert_comparison.rs
tests/ui/bool_assert_comparison.stderr

Close #7548 
changelog: [`bool_assert_comparison`] fixes should be emitted only in case they are comparing a value of a type that implements the `Not` trait with an output of type `bool` against a boolean literal.

Issue 7548 fix

---

doc/common_tools_writing_lints.md

The title says it all. The rustc dev guide now has some information about diagnostic items that are worthwhile linking to :upside_down_face: 
---

Reference new diagnostic item docs in our docs :)

---

clippy_lints/src/unwrap.rs
clippy_utils/src/usage.rs
tests/ui/checked_unwrap/complex_conditionals.stderr
tests/ui/checked_unwrap/complex_conditionals_nested.stderr
tests/ui/checked_unwrap/simple_conditionals.rs
tests/ui/checked_unwrap/simple_conditionals.stderr

changelog: Extend ``[`unnecessary_unwrap`]`` to also check for `Option::expect` and `Result::expect`. Also give code suggestions in some cases.
Fixes #7581

Extend unnecessary_unwrap to look for expect in addition to unwrap

---

CHANGELOG.md
clippy_lints/src/derivable_impls.rs
clippy_lints/src/lib.rs
clippy_lints/src/mem_replace.rs
clippy_utils/src/lib.rs
clippy_utils/src/ty.rs
tests/ui/derivable_impls.rs
tests/ui/derivable_impls.stderr
tests/ui/mem_replace.fixed
tests/ui/mem_replace.rs
tests/ui/mem_replace.stderr

Fix #7550 
changelog: Add new derivable_impls lint. mem_replace_with_default now covers non constructor cases.

Add the `derivable_impls` lint

---

.github/ISSUE_TEMPLATE/blank_issue.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/false_positive.md
doc/adding_lints.md

It turns out that our current issue template can sometimes trigger a rustbot error message, as can be seen in [#7626](https://github.com/rust-lang/rust-clippy/issues/7626). I originally tested this in #7599, but it's apparently a bit inconsistent. This PR adds backticks to the commands, as correctly suggested by @mikerite in the comments. (Thank you!)
`@rustbot label +S-blocked`
---
Now I also pushed a tiny link fix as well. :upside_down_face: 
---

Updating issue templates again for rustbot

---

clippy_lints/src/blocks_in_if_conditions.rs
clippy_lints/src/casts/cast_ptr_alignment.rs
clippy_lints/src/floating_point_arithmetic.rs
clippy_lints/src/if_let_mutex.rs
clippy_lints/src/if_let_some_result.rs
clippy_lints/src/loops/needless_range_loop.rs
clippy_lints/src/mem_forget.rs
clippy_lints/src/methods/or_fun_call.rs
clippy_lints/src/methods/utils.rs
clippy_lints/src/misc.rs
clippy_lints/src/mut_mutex_lock.rs
clippy_lints/src/open_options.rs
clippy_lints/src/ptr_offset_with_cast.rs
clippy_lints/src/strings.rs
clippy_lints/src/to_string_in_display.rs
clippy_lints/src/undropped_manually_drops.rs
clippy_lints/src/unused_io_amount.rs
clippy_lints/src/utils/internal_lints.rs

While working on #7569 I got about 23 lint reports where we can avoid slice indexing by destructing the slice early. This is a preparation PR to avoid fixing them in the lint PR. (The implementation already takes about 300 lines without tests :sweat_smile:). Either way, this should hopefully be easy to review :upside_down_face: 
---

Avoid slice indexing in Clippy (down with the ICEs)

---

CHANGELOG.md
clippy_lints/src/lib.rs
clippy_lints/src/loops/never_loop.rs
clippy_lints/src/needless_option_as_deref.rs
tests/ui/needless_option_as_deref.fixed
tests/ui/needless_option_as_deref.rs
tests/ui/needless_option_as_deref.stderr

changelog: [`option_needless_deref`]
fix #7571

New lint: option_needless_deref

---

clippy_lints/src/eval_order_dependence.rs

Fixes #7624.
changelog: fix documentation of eval_order_dependence

Fix documentation of eval_order_dependence

---

clippy_lints/src/approx_const.rs
clippy_utils/src/msrvs.rs
tests/ui/approx_const.rs
tests/ui/approx_const.stderr

changelog: [`approx_constant`]: Add `TAU`

Add `TAU` to `approx_constant`

---

clippy_lints/src/loops/mod.rs
clippy_lints/src/loops/mut_range_bound.rs
tests/ui/mut_range_bound.rs
tests/ui/mut_range_bound.stderr

closes #7532 
`mut_range_bound` ignores mutation on range bounds that is placed immediately before break. Still warns if the break is not always reachable.
changelog: [`mut_range_bound`] ignore range bound mutations before immediate break

`mut_range_bound` check for immediate break after mutation

---

.cargo/config
Cargo.toml
clippy_utils/Cargo.toml
tests/compile-test.rs
tests/dogfood.rs
tests/fmt.rs
tests/integration.rs
tests/lint_message_convention.rs
tests/missing-test-files.rs
tests/versioncheck.rs

Closes #7343
Closes #6809
Closes #3643
r? @flip1995 
cc @Jarcho

Use binary-dep-depinfo to resolve UI test dependencies

---

clippy_lints/src/disallowed_method.rs
clippy_lints/src/lib.rs
clippy_lints/src/utils/conf.rs
tests/ui-toml/toml_disallowed_method/clippy.toml
tests/ui-toml/toml_disallowed_method/conf_disallowed_method.stderr

Fixes #7609.
This permits writing the config for `disallowed-methods` as either a list of strings (like before) or a list of tables, where each table gives the path to the disallowed method and an optional reason for why the method is disallowed.
changelog: Allow giving reasons for [`disallowed_methods`]

Allow giving reasons for `disallowed_methods`

---

CHANGELOG.md
clippy_lints/src/iter_not_returning_iterator.rs
clippy_lints/src/lib.rs
tests/ui/iter_not_returning_iterator.rs
tests/ui/iter_not_returning_iterator.stderr

Add new lint [`iter_not_returning_iterator`] to detect method `iter()` or `iter_mut()` returning a type not implementing `Iterator`
changelog: Add new lint [`iter_not_returning_iterator`]

Add new lint `iter_not_returning_iterator`

---

clippy_lints/src/methods/manual_split_once.rs
tests/ui/manual_split_once.fixed
tests/ui/manual_split_once.rs
tests/ui/manual_split_once.stderr

fixes: #7656
changelog: Fix result order for `manual_split_once` when `rsplitn` is used

Fix result order for `manual_split_once` when `rsplitn` is used

---

clippy_lints/src/disallowed_type.rs
clippy_lints/src/eta_reduction.rs
clippy_lints/src/format.rs
clippy_lints/src/loops/while_let_loop.rs
clippy_lints/src/ptr.rs
clippy_utils/src/ast_utils.rs
clippy_utils/src/eager_or_lazy.rs
tests/ui/eta.fixed
tests/ui/eta.rs
tests/ui/eta.stderr
tests/ui/map_flatten.fixed
tests/ui/map_flatten.rs
tests/ui/map_flatten.stderr
tests/ui/semicolon_if_nothing_returned.rs
tests/ui/semicolon_if_nothing_returned.stderr

changelog: Fix various false negatives and false positives for [`redundant_closure`]
Closes #3071
Closes #4002
This lint is full of weird nuances and this is basically a re-write to tighten up the logic.

Fix various redundant_closure bugs

---

.cargo/config
clippy_dev/src/bless.rs
src/main.rs
tests/cargo/mod.rs
tests/compile-test.rs
tests/dogfood.rs

* .cargo/config now has `target-dir` specified so that it is inherited by child projects. The target directory needs to be shared with clippy_dev, but not necessarily at the project root. (cc #7625)
* Uses `std::env::current_exe` (and its parent directories) whenever possible
* `CLIPPY_DRIVER_PATH` and `TARGET_LIBS` are no longer required from rustc bootstrap (but `HOST_LIBS` still is). These can be removed from the rustc side after merging.
* `CLIPPY_DOGFOOD` and the separate target directory are removed. This was originally added to mitigate #7343.
r? @flip1995

Target directory cleanup

---

.github/ISSUE_TEMPLATE/blank_issue.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/false_positive.md

This adds a space between the `@` and the name *rustbot*. This should now surely fix it. If not, I'm giving up. 
@ rustbot label +C-bug
---
r? @camsteffen

Updating issue templates to avoid @rustbot triggers

---

clippy_lints/src/mut_key.rs
tests/ui/mut_key.rs
tests/ui/mut_key.stderr

Fixes #6745.
Whilst writing the tests for this, I noticed what I believe is a false negative (the code in @xFrednet's [comment](https://github.com/rust-lang/rust-clippy/issues/6745#issuecomment-909658267) doesn't trigger the lint).  Currently the tests contain a case for this (which is blatantly ignored), but I'm not at all sure how to implement this (since the lint currently behaves completely differently for ADTs).  I'm not sure what should be done - on the one hand the extra test cases are misleading, but on the other hand they don't cause much harm and would save effort for anyone fixing that false negative.
---
changelog: Improve accuracy of `clippy::mutable_key_type`.

Improve accuracy of `mut_key`

---

tests/ui/wrong_self_convention2.rs

fixes #3414
I found #3414 was fixed some time. So I add the tests.

add #3414 test

---

CHANGELOG.md
clippy_lints/src/lib.rs
clippy_lints/src/same_name_method.rs
tests/ui/same_name_method.rs
tests/ui/same_name_method.stderr

changelog: ``[`same_name_method`]``
fix: https://github.com/rust-lang/rust-clippy/issues/7632
It only compares a method in `impl` with another in `impl trait for`
It doesn't lint two methods in two traits.
I'm not sure my approach is the best way. I meet difficulty in other approaches.

New lint: `same_name_method`

---

clippy_lints/src/needless_borrow.rs
tests/ui/needless_borrow.fixed
tests/ui/needless_borrow.rs
tests/ui/needless_borrow.stderr

closes #7635
changelog: [`needless_borrow`] now checks for needless mutable borrow

`needless_borrow` checks for mutable borrow

---

clippy_lints/src/loops/while_let_on_iterator.rs
tests/ui/while_let_on_iterator.fixed
tests/ui/while_let_on_iterator.stderr

It came up in the discussion #7659 that suggesting `iter.by_ref()` is a clearer suggestion than `&mut iter`. I personally think they're equivalent, but if `by_ref()` is clearer to people then that should be the suggestion.
changelog: Change `while_let_on_iterator` suggestion when using `&mut` to use `by_ref()`

Change `while_let_on_iterator` suggestion to use `by_ref()`

---

lintcheck/src/main.rs

I'm currently on spotty wifi right now. It is shocking the number of things that break when you lose connection for a few seconds. Some 500 errors should probably also be retried, but this fixes my issue.

Retry on some download errors in lintcheck

---

clippy_lints/src/methods/mod.rs
tests/ui/wrong_self_convention2.rs

fixed #4546
I notice #4546 was fixed some time, I just add the tests.

add #4546 test

---

README.md

Okay this is getting a bit picky (you might even say pedantic). I think we need to be careful not use the pedantic category as cover-all for lints with any amount of false positives. Lints with a high degree of FPs should be nursery or restriction IMO. If the pedantic category were to yield, say hypothetically, over 50% FPs, it would just be too annoying to use at all (to be sure, "too picky for me" is not a FP).
CC @rust-lang/clippy

Tweak pedantic description for occasional FPs

---

clippy_lints/src/formatting.rs
tests/ui/auxiliary/proc_macro_suspicious_else_formatting.rs
tests/ui/suspicious_else_formatting.rs
tests/ui/suspicious_else_formatting.stderr

fixes: #7650
I'll add a test for this one soon.
changelog: Don't lint `suspicious_else_formatting` inside proc-macros

Don't lint `suspicious_else_formatting` inside proc-macros

---

clippy_lints/src/types/box_collection.rs

Fix issue left from previous PR
changelog: none.

Avoid needless heap allocation in box_collection

---

CHANGELOG.md
clippy_lints/src/if_then_panic.rs
clippy_lints/src/lib.rs
clippy_lints/src/utils/internal_lints.rs
clippy_utils/src/higher.rs
tests/compile-test.rs
tests/integration.rs
tests/ui/fallible_impl_from.rs
tests/ui/fallible_impl_from.stderr
tests/ui/if_then_panic.fixed
tests/ui/if_then_panic.rs
tests/ui/if_then_panic.stderr
tests/ui/ptr_arg.rs
tests/ui/ptr_arg.stderr

changelog: add the new lint [`if_then_panic`]
fix #7645

New lint `if_then_panic`

---

CHANGELOG.md

As expected a pretty short changelog, because of the missed sync last release cycle.

Update changelog to 1.56

---

clippy_lints/src/doc.rs
tests/ui/def_id_nocore.rs
tests/ui/def_id_nocore.stderr
tests/ui/doc_unsafe.rs
tests/ui/doc_unsafe.stderr

Fixes #7732
changelog: Make [`doc_unsafe`] warn on unsafe traits as well

Make `doc_unsafe` warn on unsafe traits as well

---

clippy_lints/src/await_holding_invalid.rs

changelog: Fixed small typo in [`await_holding_lock`]'s documentation - "asynx" was corrected to "async"

Fix typo ("asynx" corrected to "async")

---

clippy_utils/src/lib.rs
tests/ui/derivable_impls.rs
tests/ui/derivable_impls.stderr

Fixes #7683.
For Repeat  [x; y] (x is the type and y is the times to repeat) . When y > 32, the compiler will report an error:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7148558162685e91056e0550797ea74c
Because https://github.com/rust-lang/rust/blob/6cdd42f9f8dd4e5e5ba0aa816bc4c99ab8b102f9/library/std/src/primitive_docs.rs#L538
/// Arrays of sizes from 0 to 32 (inclusive) implement [`Default`] trait
/// if the element type allows it. As a stopgap, trait implementations are
/// statically generated up to size 32.
So here to detect this situation.
changelog: [`derivable_impls`]: No longer lints when arrays bigger than 32 elements are involved

fix for issue #7683

---

clippy_lints/src/large_enum_variant.rs
tests/ui/large_enum_variant.rs
tests/ui/large_enum_variant.stderr

Fix the discussion problem in the issue of https://github.com/rust-lang/rust-clippy/issues/7666#issuecomment-919654291
About the false positive problem of case:
```rust
enum LargeEnum6 {
A,
B([u8;255]),
C([u8;200]),
}
```
changelog: Fix largest_enum_variant wrongly identifying the second largest variant.

fix bug for large_enum_variants

---

clippy_lints/src/lib.register_pedantic.rs
clippy_lints/src/lib.register_restriction.rs
clippy_lints/src/lib.rs
clippy_lints/src/shadow.rs
clippy_utils/src/lib.rs
tests/ui/approx_const.rs
tests/ui/for_loop_fixable.fixed
tests/ui/for_loop_fixable.rs
tests/ui/for_loop_fixable.stderr
tests/ui/for_loop_unfixable.rs
tests/ui/for_loop_unfixable.stderr
tests/ui/integer_arithmetic.rs
tests/ui/integer_arithmetic.stderr
tests/ui/map_clone.fixed
tests/ui/map_clone.rs
tests/ui/modulo_arithmetic_float.rs
tests/ui/modulo_arithmetic_float.stderr
tests/ui/modulo_arithmetic_integral.rs
tests/ui/modulo_arithmetic_integral.stderr
tests/ui/modulo_arithmetic_integral_const.rs
tests/ui/modulo_arithmetic_integral_const.stderr
tests/ui/shadow.rs
tests/ui/shadow.stderr

changelog: Move shadow_unrelated to restriction
changelog: The shadow lints find a lot more shadows and are not limited to certain patterns
Drastically simplifies the implementation. Catches a lot more cases.
I removed the "initialization happens here" note. It is not helpful IMO.
Closes #318
Fixes #2890
Fixes #6563
Fixes #7588
Fixes #7620

Re-write shadow lints

---

clippy_lints/src/if_then_panic.rs
tests/ui/if_then_panic.fixed
tests/ui/if_then_panic.rs
tests/ui/if_then_panic.stderr

fixes #7731
Make if_then_panic handle situation of cond.kind = ExprKind::DropTemps(ExprKind::Binary(BinOpKind::And || BinOpKind::Or, left, right), ..) =
changelog: [`if_then_panic`] Fix suggestion for more complex conditions

Make if_then_panic handle situation of BinOpKind::And || BinOpKind::Or

---

clippy_lints/src/derivable_impls.rs
tests/ui/derivable_impls.rs

fix #7753 
changelog: Exclude enum from ``[`derivable_impls`]``

exclude enum from derivable impls

---

clippy_lints/src/implicit_hasher.rs
tests/ui/implicit_hasher.rs
tests/ui/implicit_hasher.stderr

close #7712
changelog: Fix ICE in [`implicit_hasher`]

Fix ICE in `implicit_hasher`

---

clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/suspicious_map.rs
tests/ui/suspicious_map.stderr

`suspicious_map`'s help message assumes that the literal behavior is never the intended one, although it's sometimes.  This PR adds a mention of `inspect`, offering a idiomatic alternative.
fixes #7767
---
changelog: Improved help message of [`suspicious_map`].

improved help message for `suspicious_map`

---

clippy_lints/src/doc.rs
tests/ui/doc/doc.rs
tests/ui/doc/doc.stderr

Fixes #7758
changelog: Handle intra-doc links in [`doc_markdown`]

Handle intra-doc links in doc_markdown

---

clippy_lints/src/ptr.rs
tests/ui/ptr_arg.rs

Works using the fact that the hir path will point to a TyAlias, rather than being resolved to the underlying type
Fixes #7699
changelog: [`ptr_arg`] No longer lints references to type aliases

Ignore references to type aliases in ptr_arg

---

clippy_lints/src/if_not_else.rs
clippy_lints/src/lib.rs
tests/ui/if_not_else.rs
tests/ui/if_not_else.stderr

Fixes #7892
1. Convert `['if_not_else']` to `LateLintPass` and use `clippy_utils::is_else_clause` for checking.
2. Update tests.
changelog: [`if_not_else`] now ignores else if statements.

Disable "if_not_else" lints from firing on else-ifs

---

clippy_utils/src/consts.rs

Refactoring `FullInt`

---

clippy_lints/src/option_if_let_else.rs
clippy_lints/src/unwrap_in_result.rs

Small fixes for missing backticks in doc

---

clippy_lints/src/casts/cast_possible_truncation.rs
tests/ui/cast.rs
tests/ui/cast.stderr

---
changelog: avoid linting `possible_truncation` on bit-reducing operations

avoid linting `possible_truncation` on bit-reducing operations

---

clippy_lints/src/lifetimes.rs
tests/ui/needless_lifetimes.rs
tests/ui/needless_lifetimes.stderr

Scan `OpaqueDef` bounds for lifetimes as well. Those `OpaqueDef` instances are generated while desugaring an `async` function definition.
This fixes #7893
changelog: Prevent [`clippy::needless_lifetimes`] false positive in `async` function definition

Prevent clippy::needless_lifetimes false positive in async function definition

---

clippy_lints/src/lib.register_pedantic.rs
clippy_lints/src/lib.register_restriction.rs
clippy_lints/src/unicode.rs

It feels like the more apt category, since cases where you'd want it enabled would be pretty specific
changelog: Move [`non_ascii_literal`] to `restriction`

Move non_ascii_literal to restriction

---

clippy_lints/src/doc.rs
tests/ui/doc/doc.rs
tests/ui/doc/doc.stderr

Fixes #7914.
changelog: Keep an initial `::` when [`doc_markdown`] suggests to use ticks

Advise to put a :: prefix inside the ticks

---

clippy_utils/src/source.rs
clippy_utils/src/ty.rs
doc/adding_lints.md
doc/common_tools_writing_lints.md

The `clippy_utils` crate is now part of the nightly-rustc documentation. See [**very beautiful documentation**](https://doc.rust-lang.org/nightly/nightly-rustc/clippy_utils/). This PR references them in our documentation and updates some other documentation. 

Reference `clippy_utils` docs on nightly-rustc and some other documentation updates

---

clippy_lints/src/matches.rs
tests/ui/match_overlapping_arm.rs
tests/ui/match_overlapping_arm.stderr

changelog: Fix false negative in [`match_overlapping_arms`]

Fix false negative in [`match_overlapping_arms`]

---

clippy_dev/src/lib.rs
clippy_dev/src/lint.rs
clippy_dev/src/main.rs
doc/adding_lints.md

I found the manual run command really useful, this makes it a bit easier to type
Not sure if this belongs in the changelog or not
changelog: Add `cargo dev lint` to manually run clippy on a file

Add `cargo dev lint` to manually run clippy on a file

---

clippy_lints/src/undocumented_unsafe_blocks.rs
tests/ui/crashes/auxiliary/ice-7934-aux.rs
tests/ui/crashes/ice-7934.rs

changelog: Fix ICE in [`undocumented_unsafe_blocks`]
closes: #7934

Fix ICE in undocumented_unsafe_blocks

---

clippy_lints/src/eta_reduction.rs
clippy_lints/src/format_args.rs
clippy_lints/src/implicit_return.rs
clippy_lints/src/matches.rs
clippy_utils/src/lib.rs
clippy_utils/src/ptr.rs
clippy_utils/src/usage.rs
clippy_utils/src/visitors.rs

A couple utils that satisfy a *lot* of visitor use cases. Factoring in every possible usage would be really big so I just focused on cleaning clippy_utils.

Introduce `expr_visitor` and `expr_visitor_no_bodies`

---

clippy_lints/src/matches.rs
tests/ui/redundant_pattern_matching_option.fixed
tests/ui/redundant_pattern_matching_option.rs
tests/ui/redundant_pattern_matching_option.stderr
tests/ui/redundant_pattern_matching_result.fixed
tests/ui/redundant_pattern_matching_result.stderr

changelog: Fix suggestion for deref expressions in [`redundant_pattern_matching`]
closes: #7921

Fix suggestion for deref expressions in redundant_pattern_matching

---

clippy_lints/src/loops/explicit_counter_loop.rs
clippy_lints/src/loops/manual_memcpy.rs
clippy_lints/src/loops/utils.rs
tests/ui/explicit_counter_loop.rs
tests/ui/explicit_counter_loop.stderr

changelog: Add a new suggestion for non-usize types in [`explicit_counter_loop`]
closes: #7920

Fix `explicit_counter_loop` suggestion for non-usize types

---

clippy_lints/src/matches.rs

The main purpose of this pull request is to remove the unneeded and scary `unimplented!()` in the `match_arm_overlapping` code.
The rest is gratuitous refactoring.

`match_overlapping_arm` refactoring

---

clippy_lints/src/semicolon_if_nothing_returned.rs
tests/ui/semicolon_if_nothing_returned.rs
tests/ui/semicolon_if_nothing_returned.stderr

closes #7912
`semicolon_if_nothing_returned` now additionally checks if the statements ends in `;` , this will also prevent `let-else` statements to be linted.
changelog: fix [`semicolon_if_nothing_returned`] FP  firing on `let-else`

Fix `semicolon_if_nothing_returned` FP on `let-else` stmts

---

clippy_lints/src/lib.rs
clippy_lints/src/swap.rs
clippy_utils/src/lib.rs
tests/ui/crate_level_checks/no_std_swap.rs
tests/ui/crate_level_checks/no_std_swap.stderr

Closes #7858 
changelog: [`swap`] lints now check if there is `no_std` or `no_core` attribute

[`swap`] lints now check if there is `no_std` or `no_core` attribute

---

clippy_dev/src/fmt.rs

Use rustfmt version from `rust-toolchain`

---

.github/workflows/clippy_dev.yml
clippy_dev/src/fmt.rs
rust-toolchain

This gives `cargo dev fmt` a nice speed boost, down from 90s (because old) on my laptop and 120s (because windows) on my desktop to ~5s on both
250 at a time was to give windows a good amount of headroom (failed at ~800, https://github.com/rust-lang/rust/issues/40384)
Also adds rustfmt to the toolchain file and has the clippy_dev workflow test using the pinned version as a follow up to #7963

Run rustfmt on batches of multiple files

---

clippy_lints/src/option_if_let_else.rs
tests/ui/option_if_let_else.fixed
tests/ui/option_if_let_else.rs
tests/ui/option_if_let_else.stderr

Fixes #7973
changelog: don't expand macros in suggestion of clippy::option_if_let_else

option_if_let_else: don't expand macros in suggestion

---

clippy_lints/src/functions/too_many_lines.rs
clippy_lints/src/methods/from_iter_instead_of_collect.rs
clippy_lints/src/methods/or_fun_call.rs
clippy_lints/src/methods/unnecessary_lazy_eval.rs
clippy_lints/src/option_if_let_else.rs
clippy_utils/src/eager_or_lazy.rs
clippy_utils/src/paths.rs
clippy_utils/src/ty.rs
clippy_utils/src/visitors.rs
tests/ui/needless_return.fixed
tests/ui/needless_return.rs
tests/ui/needless_return.stderr
tests/ui/option_if_let_else.fixed
tests/ui/option_if_let_else.stderr
tests/ui/or_fun_call.fixed
tests/ui/or_fun_call.rs
tests/ui/or_fun_call.stderr

Still to be done:
* a more complete list of cheap functions
* a way to limit the complexity of cheap expressions
changelog: Improve heuristics for `or_fun_call` and `unnecessary_lazy_evaluations`

Improve heuristic for eagerness suggestion

---

clippy_lints/src/loops/needless_collect.rs
tests/ui/needless_collect_indirect.rs

Fixes error specified in #7975.
changelog: [`needless_collect`] no longer suggests removal of `collect` when removal would create code requiring mutably borrowing a value multiple times.

Fix `needless_collect`'s tendency to suggest code requiring multiple mutable borrows of the same value.

---

CHANGELOG.md
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_complexity.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/str_splitn.rs
tests/ui/manual_split_once.fixed
tests/ui/manual_split_once.rs
tests/ui/manual_split_once.stderr
tests/ui/needless_splitn.fixed
tests/ui/needless_splitn.rs
tests/ui/needless_splitn.stderr
tests/ui/suspicious_splitn.rs
tests/ui/suspicious_splitn.stderr

fixes: #7889
1. Fix the problem of manual_split_once changing the original behavior.
2. Add a new lint needless_splitn.
changelog: Fix the problem of manual_split_once changing the original behavior and add a new lint needless_splitn.

Fix for #7889 and add new lint needless_splitn

---

clippy_lints/src/no_effect.rs
tests/ui/no_effect.rs
tests/ui/no_effect.stderr

Fixes #7792 
changelog: Don't show [`no_effect`] or [`unecessary_operation`] warning for unit struct implementing FnOnce

Don't show no_effect warning on unit structs implementing fn_once

---

clippy_lints/src/undocumented_unsafe_blocks.rs
tests/ui/undocumented_unsafe_blocks.rs
tests/ui/undocumented_unsafe_blocks.stderr

fix https://github.com/rust-lang/rust-clippy/issues/7979
changelog: Fix ICE on `undocumented_unsafe_blocks`

Fix ICE on `undocumented_unsafe_blocks`

---

clippy_lints/src/methods/option_map_or_none.rs
tests/ui/option_map_or_none.fixed
tests/ui/option_map_or_none.rs
tests/ui/option_map_or_none.stderr

fix: #7960 
changelog: change suggestion in the lint rule `option_map_or_none`

fix suggestion in option_map_or_none

---

clippy_lints/src/manual_map.rs
tests/ui/manual_map_option_2.fixed
tests/ui/manual_map_option_2.rs
tests/ui/manual_map_option_2.stderr

fixes: #7820
changelog: Fix `manual_map` suggestion when used with unsafe functions and unsafe blocks

Fix `manual_map` with unsafe functions

---

tests/ui/option_map_or_none.fixed
tests/ui/option_map_or_none.rs
tests/ui/option_map_or_none.stderr

just added test case for RESULT_MAP_OR_INTO_OPTION.

Add test case for RESULT_MAP_OR_INTO_OPTION

---

tests/fmt.rs

Don't check for a nightly toolchain in fmt test

---

clippy_lints/src/doc.rs
tests/ui/doc/doc-fixable.stderr
tests/ui/doc/unbalanced_ticks.stderr

The easiest route here was to ensure that the suggestion is always shown on
its own line, where no additional backticks are added by the diagnostic formatter.
Fixes #8002 
---
changelog: Avoid inline hints with double backticks for `doc-markdown`

Avoid inline hints with double backticks for `doc-markdown`

---

clippy_lints/src/shadow.rs
tests/ui/shadow.rs
tests/ui/shadow.stderr

Fix shadow_same's false positive for async function's params(Fixes #7915):
Example Code:
```rust
#![deny(clippy::shadow_same)]
pub async fn foo(_a: i32) {
}
```
Output:
```
error: `_a` is shadowed by itself in `_a
```
Hir:
```rust
pub async fn foo(_a: i32)
->
/*impl Trait*/ #[lang = "from_generator"](move |mut _task_context|
{
let _a = _a;
{ let _t = { }; _t }
})
```
Skip checking async function's params.
changelog: Fix shadow_same's false positive for async function's params

Fixes shadow_same's false positive for #7915

---

clippy_lints/src/floating_point_arithmetic.rs
tests/ui/floating_point_abs.fixed
tests/ui/floating_point_abs.rs
tests/ui/floating_point_abs.stderr
tests/ui/floating_point_mul_add.fixed
tests/ui/floating_point_mul_add.rs
tests/ui/floating_point_mul_add.stderr
tests/ui/floating_point_rad.fixed
tests/ui/floating_point_rad.rs
tests/ui/floating_point_rad.stderr

This PR allows `clippy::suboptimal_flops` in constant functions. The check also effects the `clippy::imprecise_flops` lint logic. However, this doesn't have any effects as all functions checked for are not const and can therefore not be found in such functions. 
---
changelog: [`suboptimal_flops`]: No longer triggers in constant functions
Closes: rust-lang/rust-clippy#8004

Allow `suboptimal_flops` in const functions

---

rust-toolchain

Somehow these basic components are missing from the toolchain file...

Add missing components to rust-toolchain file

---

CHANGELOG.md
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_suspicious.rs
clippy_lints/src/lib.rs
clippy_lints/src/octal_escapes.rs
tests/ui/octal_escapes.rs
tests/ui/octal_escapes.stderr

This checks for sequences in strings that would be octal character
escapes in C, but are not supported in Rust.  It suggests either
to use the `\x00` escape, or an equivalent hex escape if the octal
was intended.
Fixes #7981
---
changelog: Add new lint [`octal_escapes`], which checks for literals like `"\033[0m"`.

Add new lint `octal_escapes`

---

clippy_lints/src/if_then_some_else_none.rs
tests/ui/if_then_some_else_none.rs

closes #7870 
changelog: [`if_then_some_else_none`] now does not fire when there is early return

Fix FP on `if_then_some_else_none` when there is early return

---

clippy_lints/src/needless_question_mark.rs
tests/ui/needless_question_mark.stderr

closes #8016
changelog: [`needless_question_mark`] help suggestion now explains what should be changed

Add more descriptive help info for `needless_question_mark`

---

clippy_lints/src/unicode.rs
tests/ui/unicode.rs
tests/ui/unicode.stderr

fix: #8013 
changelog: `non_ascii_literal` warn against non-ASCII within `char`, not just `strings`

Non ascii in sigle literal

---

CHANGELOG.md
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_style.rs
clippy_lints/src/lib.rs
clippy_lints/src/needless_late_init.rs
clippy_lints/src/no_effect.rs
tests/ui/let_if_seq.rs
tests/ui/let_if_seq.stderr
tests/ui/min_max.rs
tests/ui/min_max.stderr
tests/ui/needless_late_init.rs
tests/ui/needless_late_init.stderr
tests/ui/needless_late_init_fixable.fixed
tests/ui/needless_late_init_fixable.rs
tests/ui/needless_late_init_fixable.stderr
tests/ui/redundant_closure_call_late.rs
tests/ui/redundant_closure_call_late.stderr
tests/ui/redundant_else.rs

examples:
```rust
let a;
a = 1;
// to
let a = 1;
```
```rust
let b;
match 3 {
0 => b = "zero",
1 => b = "one",
_ => b = "many",
}
// to
let b = match 3 {
0 => "zero",
1 => "one",
_ => "many",
};
```
```rust
let c;
if true {
c = 1;
} else {
c = -1;
}
// to
let c = if true {
1
} else {
-1
};
```
changelog: Add [`needless_late_init`]

Add `needless_late_init` lint

---

clippy_lints/src/methods/iter_cloned_collect.rs
clippy_lints/src/methods/mod.rs
tests/ui/iter_cloned_collect.fixed
tests/ui/iter_cloned_collect.rs
tests/ui/iter_cloned_collect.stderr

fix: #6703
changelog: apply `iter_cloned_collect` to `collect()` using`copied()`

apply iter_cloned_collect to collect() using copied()

---

clippy_lints/src/strlen_on_c_strings.rs
clippy_utils/src/lib.rs
clippy_utils/src/paths.rs
clippy_utils/src/visitors.rs
tests/ui/strlen_on_c_strings.fixed
tests/ui/strlen_on_c_strings.rs
tests/ui/strlen_on_c_strings.stderr

fixes: #7436
changelog: lint `strlen_on_c_string` when used without a fully-qualified path
changelog: suggest removing the surrounding unsafe block for `strlen_on_c_string` when possible

Improve `strlen_on_c_string`

---

tests/ui/crate_level_checks/no_std_swap.rs
tests/ui/crate_level_checks/no_std_swap.stderr

`no_std_swap`: Fix typo in TODO

---

tests/ui/pattern_type_mismatch/mutability.rs

This issue has been fixed by [commit](https://github.com/rust-lang/rust-clippy/commit/8c1c763c2d5897c66f52bd5e7c16f48ae66c894c)
This PR is used for close #7946(Fixes #7946).
changelog: Add test for pattern_type_mismatch.

Add test for pattern_type_mismatch.

---

clippy_lints/src/methods/utils.rs
tests/ui/single_char_pattern.fixed
tests/ui/single_char_pattern.rs
tests/ui/single_char_pattern.stderr

Escape backslash in single_char_pattern.
Previously, the proposed clippy fix for a single backslash in raw strings ```r"\"``` or ```r#"\"#``` was also only an unescaped, *single* ```'\'```:
```shell
warning: single-character string constant used as pattern
2 |     let s = r#"abc\xyz/"#.find(r"\");
|                                ^^^^ help: try using a `char` instead: `'\'`
|
= note: `#[warn(clippy::single_char_pattern)]` on by default
```
This PR corrects this to a properly escaped *double* backslash ```'\\'```.
I haven't come up with any other problematic cases, a single quote was already handled.
Closes: #8060 
changelog:  Escape backslash in ``[`single_char_pattern`]``

Escape backslash in single_char_pattern.rs

---

clippy_lints/src/same_name_method.rs
tests/ui/same_name_method.stderr

Noticed some odd phrasing, while checking out the new release.

Fixed same_name_method description

---

clippy_lints/src/dbg_macro.rs
clippy_lints/src/write.rs
util/gh-pages/index.html

Our last three pre-macro expansion lints aren't affected by lint level attributes. This adds a comment to the know problems section of them. I've also updated some CSS to add some spacing after lists on Clippy's lint list:
Before:
After:
---
changelog: [`print_stdout`], [`print_stderr`], [`dbg_macro`]: Document how the lint level can be changed and reference rust-lang/rust-clippy#6610
cc: rust-lang/rust-clippy#6610

Updated known problems section for pre-expansion lints about level attributes

---

clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_complexity.rs
clippy_lints/src/lib.register_pedantic.rs
clippy_lints/src/methods/mod.rs
tests/ui/option_env_unwrap.rs
tests/ui/option_env_unwrap.stderr
tests/ui/option_filter_map.fixed
tests/ui/option_filter_map.rs
tests/ui/option_filter_map.stderr

changelog: upgrade [`map_flatten`] to complexity
Resolves #7999

Upgrade map_flatten to complexity

---

clippy_lints/src/non_send_fields_in_send_ty.rs
clippy_utils/src/paths.rs
tests/ui/non_send_fields_in_send_ty.rs
tests/ui/non_send_fields_in_send_ty.stderr

PR 1/2 for issue #8045. Add `NonNull` as a pointer class to suppress false positives like `UnsafeCell<NonNull<()>>`. However, this change is not sufficient to handle the cases shared in gtk-rs and Rug in the issue.
r? @xFrednet

Consider NonNull as a pointer type

---

triagebot.toml

This enables shortcuts for `@rustbot`. Just a quality of life feature for contributors.
|Shortcut| Full comment |
|---|---|
| `@rustbot ready` | `@rustbot label -S-waiting-on-author +S-waiting-on-review` |
| `@rustbot author` | `@rustbot label +S-waiting-on-author -S-waiting-on-review` |
See: https://github.com/rust-lang/triagebot/wiki/Shortcuts
The documentation also states that the author/assignee will be pinged. However, this doesn't seem to be the case, it at least hasn't done so for me and in this [PR](https://github.com/rust-lang/rust/pull/90642#issuecomment-962465404)
---

Enable rustbot shortcuts for rust-clippy

---

clippy_lints/src/map_unit_fn.rs
clippy_lints/src/methods/single_char_pattern.rs
clippy_lints/src/nonstandard_macro_braces.rs
clippy_lints/src/self_named_constructors.rs
clippy_lints/src/unicode.rs
clippy_lints/src/write.rs
tests/ui/single_char_pattern.fixed
tests/ui/single_char_pattern.rs
tests/ui/single_char_pattern.stderr

changelog: Fix some false negatives for [`single_char_pattern`]
I noticed that clippy wasn't complaining about my usage of `split_once("x")` in a personal project so I updated the list of functions.
I had to update the test case for an unrelated issue because replace is now included in the list of functions to be linted.

Fix some false negatives for [`single_char_pattern`]

---

clippy_lints/src/assertions_on_constants.rs
clippy_lints/src/bytecount.rs
clippy_lints/src/collapsible_match.rs
clippy_lints/src/derivable_impls.rs
clippy_lints/src/floating_point_arithmetic.rs
clippy_lints/src/if_then_some_else_none.rs
clippy_lints/src/implicit_saturating_sub.rs
clippy_lints/src/loops/manual_flatten.rs
clippy_lints/src/loops/never_loop.rs
clippy_lints/src/manual_map.rs
clippy_lints/src/map_clone.rs
clippy_lints/src/matches.rs
clippy_lints/src/methods/bind_instead_of_map.rs
clippy_lints/src/methods/filter_map.rs
clippy_lints/src/methods/option_as_ref_deref.rs
clippy_lints/src/methods/unnecessary_fold.rs
clippy_lints/src/needless_bool.rs
clippy_lints/src/no_effect.rs
clippy_lints/src/option_if_let_else.rs
clippy_lints/src/question_mark.rs
clippy_lints/src/strings.rs
clippy_lints/src/utils/internal_lints.rs
clippy_lints/src/utils/internal_lints/metadata_collector.rs
clippy_utils/src/lib.rs

* Rename `remove_blocks` to `peel_blocks`
* Add `peel_blocks_and_stmts`
* Various refactors to use the above utils
* The utils also now check `block.rules`

Peel blocks and statements utils

---

clippy_lints/src/question_mark.rs
tests/ui/question_mark.fixed
tests/ui/question_mark.rs

Closes #8019 
changelog: [`question_mark`] Fix FP when returned object is not local

Fix FP on `question_mark` if returned object is not local

---

clippy_lints/src/lifetimes.rs

fixes #8084
[needless_lifetimes]

`needless_lifetimes` Known problems typo

---

clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_nursery.rs
clippy_lints/src/lib.register_suspicious.rs
clippy_lints/src/non_send_fields_in_send_ty.rs
tests/ui-toml/strict_non_send_fields_in_send_ty/test.stderr
tests/ui/non_send_fields_in_send_ty.stderr

PR 2/2 for issue #8045. Tried to tone down the warning message and clarify the intention of the lint. Specifically, I added a description that this lint tries to detect "types that are not safe to be sent to another thread".
r? @xFrednet

Clarify the purpose of the non_send lint

---

clippy_lints/src/option_if_let_else.rs
tests/ui/option_if_let_else.fixed
tests/ui/option_if_let_else.rs
tests/ui/option_if_let_else.stderr

closes #7991 
Prefer not warning any complex subpat in `option_if_let_else` rather than suggesting obscure suggestions.
changelog: [`option_if_let_else`] does not warn when complex subpat is present

Fix bad suggestion on `option_if_let_else` when there is complex subpat

---

CHANGELOG.md
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_suspicious.rs
clippy_lints/src/lib.rs
clippy_lints/src/return_self_not_must_use.rs
clippy_utils/src/hir_utils.rs
clippy_utils/src/lib.rs
clippy_utils/src/sugg.rs
tests/ui/auxiliary/option_helpers.rs
tests/ui/deref_addrof.fixed
tests/ui/deref_addrof.rs
tests/ui/deref_addrof.stderr
tests/ui/return_self_not_must_use.rs
tests/ui/return_self_not_must_use.stderr
tests/ui/should_impl_trait/corner_cases.rs
tests/ui/should_impl_trait/method_list_1.rs
tests/ui/should_impl_trait/method_list_1.stderr
tests/ui/should_impl_trait/method_list_2.rs
tests/ui/should_impl_trait/method_list_2.stderr

This lint is somewhat similar to https://rust-lang.github.io/rust-clippy/master/index.html#must_use_candidate but also different: it emits a warning by default and only targets methods (so not functions nor associated functions).
Someone suggested it to me after this tweet: https://twitter.com/m_ou_se/status/1466439813230477312
I think it would reduce the number of cases of API misuses quite a lot.
What do you think?
---
changelog: Added new [`return_self_not_must_use`] lint

Add new lint to warn when #[must_use] attribute should be used on a method

---

clippy_lints/src/blocks_in_if_conditions.rs
tests/ui/blocks_in_if_conditions_closure.rs

Fix #8099 
changelog: Fix [`blocks_in_if_conditions`] false positive with an empty closure

Fix `blocks_in_if_conditions` false positive

---

clippy_lints/src/return_self_not_must_use.rs
tests/ui/return_self_not_must_use.rs

Fixes https://github.com/rust-lang/rust-clippy/issues/8140.
---
Edit:
(The lint is not in beta yet, this should therefore not be included inside the changelog :) )

Ensure that RETURN_SELF_NOT_MUST_USE is not emitted if the method already has `#[must_use]`

---

clippy_lints/src/return_self_not_must_use.rs
tests/ui/return_self_not_must_use.rs

New bug discovered with this lint. Hopefully, this is the last one.
---

Don't emit RETURN_SELF_NOT_MUST_USE lint if `Self` already is marked as `#[must_use]`

---

clippy_lints/src/undocumented_unsafe_blocks.rs
tests/ui/crashes/ice-7868.stderr
tests/ui/undocumented_unsafe_blocks.rs
tests/ui/undocumented_unsafe_blocks.stderr

This changes the lint introduced in #7748 to suggest adding a `SAFETY` comment instead of a `Safety` comment.
Searching for `// Safety:` in rust-lang/rust yields 67 results while `// SAFETY:` yields 1072.
I think it's safe to say that this comment tag is written in upper case, just like `TODO`, `FIXME` and so on are. As such I would expect this lint to follow the official convention as well.
Note that I intentionally introduced some casing diversity in `tests/ui/undocumented_unsafe_blocks.rs` to test more cases than just `Safety:`.
changelog: Capitalize `SAFETY` comment in [`undocumented_unsafe_blocks`]

Fix `SAFETY` comment tag casing in undocumented_unsafe_blocks

---

clippy_lints/src/neg_multiply.rs
tests/ui/neg_multiply.fixed
tests/ui/neg_multiply.rs
tests/ui/neg_multiply.stderr

This fixes #8115 by adding a suggestion for [neg_multiply].
My first issue on Github, any feedback or input is welcome 😃 
changelog: create a suggestion for `neg_multiply`

Add suggestion for neg_multiply lint

---

clippy_lints/src/methods/unwrap_or_else_default.rs
clippy_utils/src/lib.rs
tests/ui/unwrap_or_else_default.fixed
tests/ui/unwrap_or_else_default.rs
tests/ui/unwrap_or_else_default.stderr

changelog:  change `unwrap_or_else_default` to work with std constructors like `Vec::new`, `HashSet::new`, `HashMap::new`.
Notes:
- Code to handle detecting those constructors is already there. I moved it out to `is_default_equivalent_call`

Improve `unwrap_or_else_default` when handling `unwrap_or_else(XXX::new)`

---

clippy_lints/src/shadow.rs
tests/ui/shadow.rs
tests/ui/shadow.stderr

fixes #8087 
changelog: trigger [`shadow_reuse`] instead of [`shadow_unrelated`] on shadowed `if let` bindings

fix [`shadow_reuse`] false negative for if let bindings

---

clippy_lints/src/casts/unnecessary_cast.rs

This very likely fixes #8166 though I wasn't able to meaningfully reduce a test case. This line is the only call to `unwrap` within that function, which was the one in the stack trace that triggered the ICE, so I think we'll be OK.
@hackmad can you pull and build this branch and check if it indeed fixes your problem?
---
changelog: Fixed ICE in [`unnecessary_cast`]

fix an ICE on unwrapping a None

---

CHANGELOG.md
clippy_lints/src/init_numbered_fields.rs
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_style.rs
clippy_lints/src/lib.rs
clippy_lints/src/macro_use.rs
clippy_utils/src/lib.rs
tests/ui/numbered_fields.fixed
tests/ui/numbered_fields.rs
tests/ui/numbered_fields.stderr

This fixes #7985.
r? @xFrednet 
---
changelog: new lint: [`init_numbered_fields`]

new lint: `init-numbered-fields`

---

clippy_utils/src/lib.rs

This avoids quadratic behavior (collecting all test item names for each `eq_op` instance within the module). However, it invests a good deal of memory to buy this speedup. If that becomes a problem, I may need to change the cache to only store the chain of last visited modules.
This hopefully fixes #8171.
---

cache test item names

---

clippy_lints/src/enum_variants.rs
clippy_utils/src/str_utils.rs
tests/ui/enum_variants.rs
tests/ui/enum_variants.stderr

closes #8090 
Fix FP on `enum_variants` when prefixes are only a substring of a camel-case word. Also adds some util helpers on `str_utils` to help parsing camel-case strings.
This changes how the lint behaves:
1. previously if the Prefix is only a length of 1, it's going to get ignored, i.e. these were previously ignored and now is warned
```rust
enum Foo {
cFoo,
cBar,
cBaz,
}
enum Something {
CCall,
CCreate,
CCryogenize,
}
```
2. non-ascii characters that doesn't have casing will not be split, 
```rust
enum NonCaps {
PrefixXXX,
PrefixTea,
PrefixCake,
}
```
will be considered as `PrefixXXX`, `Prefix`, `Prefix`, so this won't lint as opposed to fired previously.
changelog: [`enum_variant_names`] Fix FP when first prefix are only a substring of a camel-case word. 
---
(Edited by @xFrednet …

Fix `enum_variants` FP on prefixes that are not camel-case

---

clippy_lints/src/floating_point_arithmetic.rs
tests/ui/floating_point_rad.fixed
tests/ui/floating_point_rad.rs
tests/ui/floating_point_rad.stderr

fixes #7651 
I fixed the original problem as described in the issue, but the bug remains for complex expressions (the commented out TC I added is an example). I would also love some feedback on how to cleanup my code and reduce duplication. I hope it's not a problem that the issue has been claimed by someone else - that was over two months ago.
changelog: ``[`suboptimal_flops`]`` no longer proposes broken code with `to_radians` and `to_degrees`

Fixed issues with to_radians and to_degrees lints

---

clippy_lints/src/identity_op.rs
clippy_utils/src/consts.rs
tests/ui/identity_op.rs
tests/ui/identity_op.stderr

changelog: limit ``[`identity_op`]`` to integral operands
In the ``[`identity_op`]`` lint, if the operands are non-integers, then the lint is likely
wrong.

Limit the ``[`identity_op`]`` lint to integral operands.

---

clippy_lints/src/floating_point_arithmetic.rs
clippy_lints/src/loops/manual_memcpy.rs
clippy_lints/src/needless_bool.rs
clippy_lints/src/ranges.rs
clippy_utils/src/sugg.rs
tests/ui/manual_memcpy/with_loop_counters.stderr
tests/ui/needless_bool/fixable.fixed
tests/ui/needless_bool/fixable.rs
tests/ui/needless_bool/fixable.stderr
tests/ui/short_circuit_statement.fixed
tests/ui/short_circuit_statement.stderr

fixes #7320 
changelog: ```needless_bool```: Changed to make a smart suggestion.

update: ```Sugg::not()``` replacing the comparison operator. #7320

---

Cargo.toml
clippy_lints/src/unused_io_amount.rs
clippy_utils/src/paths.rs
tests/compile-test.rs
tests/ui/unused_io_amount.rs
tests/ui/unused_io_amount.stderr

Clippy helpfully warns about code like this, telling you that you
probably meant "write_all":
fn say_hi<W:Write>(w: &mut W) {
w.write(b"hello").unwrap();
}
This patch attempts to extend the lint so it also covers this
case:
async fn say_hi<W:AsyncWrite>(w: &mut W) {
w.write(b"hello").await.unwrap();
}
(I've run into this second case several times in my own programming,
and so have my coworkers, so unless we're especially accident-prone
in this area, it's probably worth addressing?)
Since this is my first attempt at a clippy patch, I've probably
made all kinds of mistakes: please help me fix them?  I'd like
to learn more here.
Open questions I have:
* Should this be a separate lint from unused_io_amount?  Maybe
unused_async_io_amount?  If so, how should I structure their
shared code?
* …

Extend unused_io_amount to cover async io.

---

clippy_lints/src/eta_reduction.rs
tests/ui/eta.fixed
tests/ui/eta.rs

fixes #8073 
changelog: don't trigger [`redundant_closure`] on `Arc<F>` or `Rc<F>`

fix [`redundant_closure`] fp with `Rc<F>`/`Arc<F>`

---

clippy_lints/src/methods/mod.rs
clippy_lints/src/redundant_clone.rs
tests/ui/issue_4266.stderr
tests/ui/wrong_self_convention.rs
tests/ui/wrong_self_convention.stderr

The `wrong_self_convention` lint uses a `SelfKind` type to decide
whether a method has the right kind of "self" for its name, or whether
the kind of "self" it has makes its name confusable for a method in
a common trait.  One possibility is `SelfKind::No`, which is supposed
to mean "No `self`".
Previously, SelfKind::No matched everything _except_ Self, including
references to Self.  This patch changes it to match Self, &Self, &mut
Self, Box<Self>, and so on.
For example, this kind of method was allowed before:
```
impl S {
// Should trigger the lint, because
// "methods called `is_*` usually take `self` by reference or no `self`"
fn is_foo(&mut self) -> bool { todo!() }
}
```
But since SelfKind::No matched "&mut self", no lint was triggered
(see #8142).
With this patch, the code above now …

wrong_self_convention: Match `SelfKind::No` more restrictively

---

clippy_lints/src/erasing_op.rs
tests/ui/erasing_op.rs
tests/ui/erasing_op.stderr
tests/ui/identity_op.rs
tests/ui/identity_op.stderr

fixes #7210
changelog: [`erasing_op`] lint ignored when operation `Output` type is different from the type of constant `0`

[`erasing_op`] lint ignored when operation `Output` type is different from the type of constant `0`

---

src/main.rs

`ClippyCmd` warnings gets generated due to addition of `clippy::use-self`. This PR fixes that.
```
warning: unnecessary structure name repetition
--> src/main.rs:99:9
|
99 |         ClippyCmd {
|         ^^^^^^^^^ help: use the applicable keyword: `Self`
|
= note: `-W clippy::use-self` implied by `-W clippy::nursery`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#use_self
```
---

Fix `clippy::use-self`` warning in ` src/main.rs`

---

clippy_utils/src/lib.rs
tests/ui/swap.fixed
tests/ui/swap.rs
tests/ui/swap.stderr

fixes #8154
changelog: Don't lint `manual_swap` when a field access involves auto-deref

Consider auto-deref when linting `manual_swap`

---

clippy_lints/src/init_numbered_fields.rs
clippy_lints/src/macro_use.rs
clippy_utils/src/lib.rs

Previously done in #7897 but reverted in #8170. I'd like to keep `in_macro` out of utils because if a span is from expansion in any way (desugaring or macro), we should not proceed without understanding the nature of the expansion IMO.
r? @llogiq

Remove in_macro from clippy_utils

---

clippy_lints/src/trait_bounds.rs
clippy_utils/src/hir_utils.rs
tests/ui/type_repetition_in_bounds.rs

fixes #7360
fixes #8162
fixes #8056
changelog: Check for full equality in `type_repetition_in_bounds` rather than just equal hashes

Fix `type_repetition_in_bounds`

---

clippy_lints/src/loops/while_let_on_iterator.rs
tests/ui/while_let_on_iterator.fixed
tests/ui/while_let_on_iterator.rs
tests/ui/while_let_on_iterator.stderr

fixes #8113 
changelog: Better detect when a field can be moved from in `while_let_on_iterator`

Better detect when a field can be moved from in `while_let_on_iterator`

---

lintcheck/src/main.rs

I have Clippy checked out in `rust/clippy` rather than `rust/rust-clippy`, this allows lintcheck to still run in that case

Allow running lintcheck with a renamed rust-clippy dir

---

clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/unnecessary_iter_cloned.rs
clippy_lints/src/methods/unnecessary_to_owned.rs

I am having a hard time finding a good solution for #8148, so I am wondering if is enough to just change the suggestion's applicability to `MaybeIncorrect`?
I apologize, as I realize this is a bit of a cop out.

Change `unnecessary_to_owned` `into_iter` suggestions to `MaybeIncorrect`

---

.cargo/config.toml

Fixes #8248
According to https://doc.rust-lang.org/cargo/reference/unstable this
seems to be the right place to set it, and it does fix the build for me.
I haven't removed the other `rustflags` because perhaps it's needed on
different cargo/rust versions?
---

Set binary-dep-depinfo in .cargo/config.toml

---

clippy_lints/src/trait_bounds.rs
tests/ui/trait_duplication_in_bounds.rs
tests/ui/trait_duplication_in_bounds.stderr

closes #8229 
changelog: [`trait_duplication_in_bounds`] covers trait functions with `Self` bounds

cover trait for `trait_duplication_in_bounds`

---

clippy_lints/src/iter_not_returning_iterator.rs
tests/ui/iter_not_returning_iterator.rs
tests/ui/iter_not_returning_iterator.stderr

fixes #8225 
changelog: Handle type projections in `iter_not_returning_iterator`
changelog: Don't lint `iter_not_returning_iterator` in trait implementations
changelog: Lint `iter_not_returning_iterator` in trait definitions

fix `iter_not_returning_iterator`

---

clippy_lints/src/disallowed_methods.rs
clippy_lints/src/disallowed_types.rs
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_nursery.rs
clippy_lints/src/lib.register_style.rs

Closes #7841
changelog: Moved [`disallowed_methods`] and [`disallowed_types`] to `style`

Warn disallowed_methods and disallowed_types by default

---

clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_nursery.rs
clippy_lints/src/lib.register_perf.rs
clippy_lints/src/mutex_atomic.rs
tests/ui/mutex_atomic.rs
tests/ui/mutex_atomic.stderr

See #1516 and #4295.
There are suggestions about removing this lint from the default warned lints in both issues.
Also, [`mutex_integer`](https://rust-lang.github.io/rust-clippy/master/index.html#mutex_integer) lint that has the same problems as this lint is in `nursery` group.
changelog: Moved [`mutex_atomic`] to `nursery`

Downgrade mutex_atomic to nursery

---

clippy_lints/src/types/mod.rs

fixes #8161 
Updates documentation to elaborate more on how removing Box from a function parameter can generalize the function.

Improve documentation for `borrowed-box` lint

---

clippy_lints/src/reference.rs
tests/ui/deref_addrof.fixed
tests/ui/deref_addrof.rs
tests/ui/deref_addrof.stderr

fixes #8247
This would supersede #8259
changelog: Don't lint `deref_addrof` when the dereference and the borrow occur in different contexts

Fix `deref_addrof`

---

clippy_lints/src/methods/mod.rs

This is possible now that `SymbolStr` is removed from rustc.

Remove method_call! macro

---

README.md

Currently, Clippy does not guarantee the same codegen will be produced.
Therefore, it should not be used as an universal replacement for `rustc`.
See https://github.com/rust-lang/rust-clippy/issues/8035.
Signed-off-by: Miguel Ojeda <ojeda@kernel.org>
fixes #8035
changelog: document that Clippy may change codegen

`README`: document that Clippy may change codegen

---

CHANGELOG.md
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_style.rs
clippy_lints/src/lib.rs
clippy_lints/src/manual_bits.rs
clippy_utils/src/msrvs.rs
tests/ui/manual_bits.fixed
tests/ui/manual_bits.rs
tests/ui/manual_bits.stderr

Closes #6670 
---
changelog: new lint: [`manual_bits`]

Add `manual_bits` lint

---

clippy_lints/src/disallowed_methods.rs
clippy_lints/src/utils/conf.rs
clippy_utils/src/lib.rs
tests/ui-toml/toml_disallowed_methods/clippy.toml
tests/ui-toml/toml_disallowed_methods/conf_disallowed_methods.rs
tests/ui-toml/toml_disallowed_methods/conf_disallowed_methods.stderr

Fixes #8079
changelog: `disallowed_methods`: Now can disallow methods of primitive types

Allow primitive types in disallowed_methods

---

clippy_dev/src/fmt.rs

Call `rustup which rustfmt` and use the output. This shaves off  ~0.7 seconds for `cargo dev fmt` for me.

Cache rustfmt path

---

clippy_lints/src/loops/manual_memcpy.rs
tests/ui/manual_memcpy/with_loop_counters.stderr
tests/ui/manual_memcpy/without_loop_counters.rs
tests/ui/manual_memcpy/without_loop_counters.stderr

fixes #8160 
Ideally this would work with `VecDeque`, but the current interface is unsuitable for it. At a minimum something like `range_as_slices` would be needed.
changelog: Don't lint `manual_memcpy` on `VecDeque`
changelog: Suggest `copy_from_slice` for `manual_memcpy` when applicable

`manual_memcpy` fix

---

clippy_lints/src/functions/not_unsafe_ptr_arg_deref.rs
tests/ui/functions.rs
tests/ui/functions.stderr

changelog: Apply [`not_unsafe_ptr_arg_deref`] to type aliases

Apply `not_unsafe_ptr_arg_deref` to type aliases

---

clippy_lints/src/methods/implicit_clone.rs
clippy_lints/src/methods/mod.rs
tests/ui/implicit_clone.rs
tests/ui/implicit_clone.stderr

fixes #8227
changelog: Don't lint `implicit_clone` on `&&T`

Fix `implicit_clone` for `&&T`

---

clippy_lints/src/iter_not_returning_iterator.rs
tests/ui/iter_not_returning_iterator.rs

Erase late bound regions in `iter_not_returning_iterator`

---

clippy_lints/src/bit_mask.rs
util/gh-pages/index.html

Fixes improperly-escaped pipes in Markdown tables for the [documentation of bad_bit_mask](https://rust-lang.github.io/rust-clippy/master/index.html#bad_bit_mask) and [ineffective_bit_mask](https://rust-lang.github.io/rust-clippy/master/index.html#ineffective_bit_mask). A column pipe takes precedence over inline code markers, so some back ticks are displayed literally and the pipes need to be escaped. I found no other occurrences of the same problem when searching rust-clippy by ```\|.*`.*\|```.

Update markdown-it version

---

clippy_lints/src/format.rs
tests/ui/format.fixed
tests/ui/format.rs
tests/ui/format.stderr

fixes #8290
Ideally this would fix the macro parsing code to handle this, but this is a smaller change and easier to back port.
changelog: Handle implicit named arguments in `useless_format`

Handle implicit named arguments in `useless_format`

---

CHANGELOG.md
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_perf.rs
clippy_lints/src/methods/iter_overeager_cloned.rs
clippy_lints/src/methods/mod.rs
tests/ui/iter_overeager_cloned.fixed
tests/ui/iter_overeager_cloned.rs
tests/ui/iter_overeager_cloned.stderr

Closes #8202 
changelog: New lint: [`iter_overeager_cloned`]

New lint: `iter_overeager_cloned`

---

clippy_lints/src/copies.rs
tests/ui/if_same_then_else2.rs

fixes #7579 
changelog: Don't lint `if_same_then_else` with `if let` conditions

Don't lint `if_same_then_else` with `if let` conditions

---

clippy_lints/src/misc.rs
tests/ui/cmp_owned/comparison_flip.fixed
tests/ui/cmp_owned/comparison_flip.rs
tests/ui/cmp_owned/comparison_flip.stderr

changelog: ``[`cmp_owned`]`` fixes #8214 so that the suggestion does not flip the comparison

#8214 cmp_owned suggestion flips the comparison

---

clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_pedantic.rs
clippy_lints/src/lib.register_suspicious.rs
clippy_lints/src/return_self_not_must_use.rs
tests/ui/return_self_not_must_use.rs
tests/ui/return_self_not_must_use.stderr

Move `return_self_not_must_use` to `pedantic`

---

clippy_lints/src/eq_op.rs
tests/ui/op_ref.rs
tests/ui/op_ref.stderr

fixes #7572 
changelog: `op_ref` don't lint for unnecessary reference in BinOp impl if removing the reference will lead to unconditional recursion

fix op_ref false positive

---

clippy_lints/src/matches.rs

This should (slightly) improve performance and enhance code quality.

Remove unnecessary `Symbol` stringification

---

clippy_dev/src/lint.rs
src/driver.rs
tests/compile-test.rs

It doesn't have any effect AFAICT.

Remove __CLIPPY_INTERNAL_TESTS env var

---

clippy_lints/src/enum_variants.rs
tests/ui/enum_variants.rs

changelog: false positive fix: [`enum_variant_names`]: No longer suggests an empty variant name
Fixes #8324

Don't suggest an empty variant name in `enum_variant_names`

---

clippy_dev/src/bless.rs

Don't bless outdated files on windows

---

clippy_lints/src/lifetimes.rs
tests/ui/needless_lifetimes.rs
tests/ui/needless_lifetimes.stderr

changelog: false positive fix: [`needless_lifetimes`] no longer lints lifetimes in explicit self types
They're not currently elidable (https://github.com/rust-lang/rust/issues/69064)
Fixes #7296

`needless_lifetimes`: ignore lifetimes in explicit self types

---

clippy_lints/src/needless_question_mark.rs
tests/ui/needless_question_mark.fixed
tests/ui/needless_question_mark.rs
tests/ui/needless_question_mark.stderr

closes #8277 
changelog: [`needless_question_mark`] Fix FN on async functions

fix `needless_question_mark` not considering async fn

---

clippy_lints/src/trait_bounds.rs
tests/ui/trait_duplication_in_bounds.rs
tests/ui/trait_duplication_in_bounds.stderr

closes #8306 
changelog: [`trait_duplication_in_bounds`] Fix FP when path segments exists for trait items

`trait_duplication_in_bounds` checks path segments for trait items

---

util/gh-pages/index.html

changelog: autofocus filter input on Clippy Lints page

Autofocus search input

---

clippy_lints/src/casts/unnecessary_cast.rs
clippy_utils/src/numeric_literal.rs
tests/ui/unnecessary_cast.rs
tests/ui/unnecessary_cast.stderr

closes #8331 
changelog: [`numeric_literal`]  fix suggestion not showing sign

fix bad suggestion on `numeric_literal`

---

clippy_lints/src/methods/mod.rs

closes #8345
changelog: [`map_flatten`] Add docs info for `Option` case

Update docs for `map_flatten` on `Option` case

---

clippy_lints/src/methods/str_splitn.rs
tests/ui/crashes/ice-8250.rs
tests/ui/crashes/ice-8250.stderr

Hi, a friend found clippy started crashing on a suspiciously large allocation of `u64::MAX` memory on their code.
The mostly minimized repro is:
```rust
fn _f01(title: &str) -> Option<()> {
let _ = title[1..].splitn(2, '[').next()?;
Some(())
}
```
The underflow happens in this case on line 57 of the patch but I've changed the other substraction to saturating as well since it could potentially cause the same issue.
I'm not sure where to put a regression test, or if it's even worth for such a thing.
Aside, has it been considered before to build clippy with overflow checks enabled?
changelog: fix ICE of underflow in `manual_split_once` lint

Fix underflow in `manual_split_once` lint

---

CHANGELOG.md
clippy_lints/src/default_union_representation.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_restriction.rs
clippy_lints/src/lib.rs
tests/ui/default_union_representation.rs
tests/ui/default_union_representation.stderr

Closes #8235
changelog: Added a new lint  [`default_union_representation`]

Add `default_union_representation` lint

---

clippy_lints/src/ptr.rs
tests/ui/ptr_arg.rs

fixes #8366
changelog: Don't lint `ptr_arg` for `&mut _` types in trait items

Don't lint `ptr_arg` for `&mut _` types in trait items

---

clippy_utils/src/consts.rs
clippy_utils/src/higher.rs
clippy_utils/src/lib.rs
clippy_utils/src/macros.rs

Not realizing it was [already obsolete](https://github.com/rust-lang/rust-clippy/pull/8360), I built a [tool to format inside `if_chain` invocations](https://crates.io/crates/rustfmt_if_chain).
This PR applies the tool to clippy_utils. (If you apply it to clippy_lints, the changes are extensive.)
Anyway, I'm making it known here in case anyone wants to use it while `if-let` chain support is developed for `rustfmt`. (There could be a few Clippy PRs between now and then, and IMHO, the code looks better with the `if_chain` invocations formatted.)
Cheers.
---

Format `if_chain` invocations in clippy_utils

---

clippy_lints/src/loops/utils.rs
tests/ui/explicit_counter_loop.stderr
tests/ui/manual_flatten.rs
tests/ui/manual_flatten.stderr

I have modified `fn make_iterator_snippet` in clippy_lints/src/loops/utils.rs ,so this change has some little influence on another lint [manual_flatten] .
fixes #8155 
---
changelog: Fix that [`explicit_counter_loop`] suggests `into_iter()` despite that triggering [`into_iter_on_ref`] in some cases

[explicit_counter_loop] suggests `.into_iter()`, despite that triggering [into_iter_on_ref] in some cases

---

clippy_lints/src/methods/chars_cmp_with_unwrap.rs
tests/ui/starts_ends_with.fixed
tests/ui/starts_ends_with.rs
tests/ui/starts_ends_with.stderr

closes #8373 
changelog: [`chars_next_cmp`] Fix unescaped suggestion

[`chars_next_cmp`] Fix unescaped suggestion

---

clippy_lints/src/methods/mod.rs
tests/ui/get_unwrap.fixed
tests/ui/get_unwrap.rs
tests/ui/get_unwrap.stderr

fixes #8124 
changelog: make the [unwrap_used] lint trigger for code of the form such as `.get(i).unwrap()` and `.get_mut(i).unwrap()`

make unwrap_used also trigger on .get().unwrap()

---

CHANGELOG.md
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_correctness.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.rs
clippy_lints/src/transmute/mod.rs
clippy_lints/src/transmute/transmute_float_to_int.rs
clippy_lints/src/transmute/transmute_int_to_bool.rs
clippy_lints/src/transmute/transmute_int_to_char.rs
clippy_lints/src/transmute/transmute_int_to_float.rs
clippy_lints/src/transmute/transmute_num_to_bytes.rs
clippy_lints/src/transmute/transmute_ptr_to_ptr.rs
clippy_lints/src/transmute/transmute_ptr_to_ref.rs
clippy_lints/src/transmute/transmute_ref_to_ref.rs
clippy_lints/src/transmute/transmute_undefined_repr.rs
clippy_lints/src/transmute/transmutes_expressible_as_ptr_casts.rs
clippy_lints/src/transmute/useless_transmute.rs
tests/ui/crashes/ice-4968.rs
tests/ui/transmute_undefined_repr.rs
tests/ui/transmute_undefined_repr.stderr

Partially implements #3999 and #546
This doesn't consider `enum`s at all right now as those are going to be a pain to deal with. This also allows `#[repr(Rust)]` structs with only one non-zero sized fields. I think those are technically undefined when transmuted.
changelog: Add lint `transmute_undefined_repr`

Add lint `transmute_undefined_repr`

---

clippy_lints/src/utils/conf.rs
tests/ui-cargo/multiple_config_files/no_warn/Cargo.toml
tests/ui-cargo/multiple_config_files/no_warn/clippy.toml
tests/ui-cargo/multiple_config_files/no_warn/src/main.rs
tests/ui-cargo/multiple_config_files/warn/.clippy.toml
tests/ui-cargo/multiple_config_files/warn/Cargo.toml
tests/ui-cargo/multiple_config_files/warn/clippy.toml
tests/ui-cargo/multiple_config_files/warn/src/main.rs
tests/ui-cargo/multiple_config_files/warn/src/main.stderr

Fixes #8323
---
changelog: warn if we find multiple clippy configs

warn if we find multiple clippy configs

---

clippy_lints/src/blocks_in_if_conditions.rs
clippy_lints/src/disallowed_methods.rs
clippy_lints/src/disallowed_types.rs
clippy_lints/src/formatting.rs
clippy_lints/src/implicit_hasher.rs
clippy_lints/src/infinite_iter.rs
clippy_lints/src/loops/single_element_loop.rs
clippy_lints/src/matches.rs
clippy_lints/src/methods/chars_cmp.rs
clippy_lints/src/methods/manual_saturating_arithmetic.rs
clippy_lints/src/methods/option_map_or_none.rs
clippy_lints/src/methods/option_map_unwrap_or.rs
clippy_lints/src/misc.rs
clippy_lints/src/missing_enforced_import_rename.rs
clippy_lints/src/ptr.rs
clippy_lints/src/ranges.rs
clippy_lints/src/swap.rs
clippy_lints/src/transmute/unsound_collection_transmute.rs
clippy_lints/src/types/box_collection.rs
clippy_lints/src/types/option_option.rs
clippy_lints/src/types/rc_buffer.rs
clippy_lints/src/types/rc_mutex.rs
clippy_lints/src/types/redundant_allocation.rs
clippy_lints/src/unwrap.rs
clippy_lints/src/utils/internal_lints.rs
clippy_utils/src/hir_utils.rs
clippy_utils/src/lib.rs
clippy_utils/src/ty.rs
doc/common_tools_writing_lints.md

This is generally an effort to reduce the total number of utils. `path_def_id` is added which I believe is more "cross-cutting" and also complements `path_to_local`. Best reviewed one commit at a time.
Added:
* `path_def_id`
* `path_res`
Removed:
* `is_qpath_def_path`
* `match_any_diagnostic_items`
* `expr_path_res`
* `single_segment_path`
* `differing_macro_contexts`
* `is_ty_param_lang_item`
* `is_ty_param_diagnostic_item`
* `get_qpath_generics`
Renamed:
* `path_to_res` to `def_path_res`
* `get_qpath_generic_tys` to `qpath_generic_tys`
CC @Jarcho since this relates to some of your work and you may have input.

Factor out several utils, add `path_def_id`

---

clippy_dev/src/bless.rs
tests/compile-test.rs

changelog: internal: Support `cargo dev bless` for tests with revisions
Previously bless wouldn't pick up the saved stderr from `target/debug/tests/manual_assert.stage-id.edition2021.stderr` or `target/debug/tests/manual_assert.stage-id.edition2018.stderr` due to there being multiple revisions of the test output
This tweaks compile-test so the built files end up in e.g. `target/debug/tests/ui`, `target/debug/tests/ui-cargo` rather than share the `tests` dir. `cargo dev bless` then uses that to update all the `.stdout/stdout/fixed` files it can find
Also removes an empty file I found, and the logic to remove empty outputs as compiletest doesn't produce empty `.stdout/stderr` files

Support `cargo dev bless` for tests with revisions

---

clippy_lints/src/dbg_macro.rs
clippy_lints/src/lib.rs
tests/ui/dbg_macro.rs
tests/ui/dbg_macro.stderr

changelog: Make `dbg_macro` work with crate level attributes and inside macro calls
One down for #6610, fixes #7275
Also fixes #7274, and adds parenthesis around the suggestion for `dbg!(1, 2, 3)` as it expands to a tuple

Migrate `dbg_macro` to late pass

---

clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_correctness.rs
clippy_lints/src/lib.register_nursery.rs
clippy_lints/src/transmute/mod.rs

Reason: #8417. I am skeptical of this lint but maybe there is a narrower subset of types on which it is useful, so keeping it for now but moving to nursery for further development.
---
changelog: Remove [`transmute_undefined_repr`] from default set of enabled lints

Downgrade transmute_undefined_repr to nursery

---

clippy_lints/src/derive.rs
clippy_lints/src/duration_subsec.rs
clippy_lints/src/infinite_iter.rs
clippy_lints/src/minmax.rs
clippy_lints/src/types/borrowed_box.rs
clippy_utils/src/paths.rs

A fairly small change towards #5393

Replace a few paths with diagnostic items

---

clippy_lints/src/new_without_default.rs
tests/ui/new_without_default.rs
tests/ui/new_without_default.stderr

fixes #8415
Also adds some UI tests that ensure that `pub` is required on both the struct _and_ the field. The only thing I'm not sure about is that the lint actually [checks](https://github.com/rust-lang/rust-clippy/blob/master/clippy_lints/src/new_without_default.rs#L102) if `new` is _reachable_, not _public_. To the best of my understanding, both the struct and the method need to be public for the method to be reachable for external crates (I certainly didn't manage to craft a counterexample).
changelog: Document `pub` requirement for ``[`new_without_default`]`` lint.

Document `pub` requirement for `new_without_default` lint

---

clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_correctness.rs
clippy_lints/src/lib.register_nursery.rs
clippy_lints/src/transmute/mod.rs
clippy_lints/src/transmute/transmute_undefined_repr.rs
tests/ui/transmute_undefined_repr.rs

Fixes: #8417
The description has also been made more precise.
changelog: Fix `transmute_undefined_repr` with single field `#[repr(C)]` structs
changelog: Move `transmute_undefined_repr` back to `correctness`

Fix `transmute_undefined_repr` with single field `#[repr(C)]` structs

---

clippy_lints/src/default.rs
tests/ui/default_trait_access.fixed
tests/ui/default_trait_access.rs

changelog: Don't lint `Default::default` it is part of the update syntax
Current clippy warns about this:
```
warning: calling `Foo::default()` is more clear than this expression
--> src/main.rs:12:11
|
12 |         ..Default::default()
|           ^^^^^^^^^^^^^^^^^^ help: try: `Foo::default()`
|
```
With these changes, it will not lint that particular expression anymore.

Don't lint Default::default if it is the udpate syntax base

---

clippy_lints/src/dereference.rs
tests/ui/needless_borrow.fixed
tests/ui/needless_borrow.rs
tests/ui/needless_borrow.stderr

fixes #8408 
fixes #8407 
fixes #8391
fixes #8367
fixes #8380
This is a temporary fix for `needless_borrow`. The proper fix is included in #8355.
This should probably be merged into rustc before beta branches on Friday. This issue has been reported six or seven times in the past couple of weeks.
changelog: Fix various issues with `needless_borrow` n´. Note to changelog writer: those issues might have been introduced in this release cycle, so this might not matter in the changelog.

Don't lint `needless_borrow` in method receiver positions

---

CHANGELOG.md
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_restriction.rs
clippy_lints/src/redundant_slicing.rs
tests/ui/deref_by_slicing.fixed
tests/ui/deref_by_slicing.rs
tests/ui/deref_by_slicing.stderr
tests/ui/redundant_slicing.fixed
tests/ui/redundant_slicing.rs
tests/ui/redundant_slicing.stderr

fixes #7972
fixes #7257
This can supersede #7976
changelog: Fix suggestion for `redundant_slicing` when re-borrowing for a method call
changelog: New lint `deref_as_slicing`

Improve `redundant_slicing` lint

---

clippy_lints/src/casts/mod.rs
tests/ui/auxiliary/macro_rules.rs
tests/ui/ptr_as_ptr.fixed
tests/ui/ptr_as_ptr.rs
tests/ui/ptr_as_ptr.stderr

This PR makes `ptr_as_ptr` trigger inside macros
Fixes issue #8120
changelog: ``[`ptr_as_ptr`]`` is now triggered inside macros
r? @llogiq

trigger  `ptr_as_ptr` inside macros 

---

CHANGELOG.md
clippy_lints/src/casts/cast_possible_truncation.rs
clippy_lints/src/casts/mod.rs
clippy_lints/src/casts/utils.rs
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_suspicious.rs
clippy_lints/src/lib.rs
clippy_utils/src/ty.rs
tests/ui/cast.rs
tests/ui/cast.stderr

fixes: #542
~~This will not lint casting a specific variant to an integer. That really should be a new lint as it's definitely a truncation (other than `isize`/`usize` values).~~
changelog: Lint enum-to-int casts with `cast_possible_truncation`
changelog: New lint `cast_enum_truncation`

Lint enum-to-int casts with `cast_possible_truncation`

---

clippy_lints/src/casts/cast_ptr_alignment.rs
clippy_lints/src/transmute/transmute_undefined_repr.rs
clippy_utils/src/lib.rs
clippy_utils/src/ty.rs
tests/ui/transmute_undefined_repr.rs
tests/ui/transmute_undefined_repr.stderr

changelog: Fix transmuting a struct containing a pointer into a pointer in `transmute_undefined_repr`
changelog: Allow various forms of type erasure in `transmute_undefined_repr`

Some more fixes for `transmute_undefined_repr`

---

clippy_lints/src/matches/match_like_matches.rs
clippy_lints/src/matches/match_same_arms.rs
clippy_lints/src/matches/match_single_binding.rs
clippy_lints/src/matches/mod.rs
clippy_lints/src/matches/redundant_pattern_match.rs
tests/ui/match_as_ref.fixed
tests/ui/match_as_ref.rs
tests/ui/match_bool.rs
tests/ui/match_expr_like_matches_macro.fixed
tests/ui/match_expr_like_matches_macro.rs
tests/ui/match_same_arms2.rs
tests/ui/match_single_binding.fixed
tests/ui/match_single_binding.rs
tests/ui/match_single_binding.stderr
tests/ui/single_match.rs

Somehow there are no open issues related to this for any of the affected lints. At least none that I could fine from a quick search.
changelog: Don't lint `match` expressions with `cfg`ed arms in many cases

Don't lint `match` expressions with `cfg`ed arms

---

Cargo.toml
tests/compile-test.rs

Benchmarks (tested on i5-7200U, 2 cores, 4 threads)
```
master branch:
cargo test // prime caches
cargo --color=always test  70,39s user 21,91s system 180% cpu 51,035 total
cargo --color=always test  70,77s user 22,13s system 180% cpu 51,579 total
cargo --color=always test  70,97s user 22,12s system 180% cpu 51,673 total
cargo --color=always nextest run  78,74s user 22,27s system 220% cpu 45,829 total
cargo --color=always nextest run  78,46s user 21,92s system 224% cpu 44,674 total
cargo --color=always nextest run  78,31s user 22,21s system 228% cpu 43,909 total
Patched (ui_speedup branch):
cargo test // prime cache
cargo --color=always test  97,51s user 32,02s system 288% cpu 44,905 total
cargo --color=always test  99,19s user 31,91s system 276% cpu 47,436 total
cargo --color=always test …
```

tests: default to more threads for ui-tests

---

clippy_lints/src/eta_reduction.rs
tests/ui/eta.fixed
tests/ui/eta.rs

fixes #8460 
Fixed [redundant_closure] so that closures of which params bound as `ref` or `ref mut ` doesn't trigger the lint.
(e.g. `|ref x| some_expr` doesn't trigger the lint.)

False positive redundant_closure when using ref pattern in closure params

---

clippy_lints/src/drop_forget_ref.rs
clippy_lints/src/manual_bits.rs
clippy_lints/src/mem_forget.rs
clippy_lints/src/mem_replace.rs
clippy_lints/src/methods/uninit_assumed_init.rs
clippy_lints/src/redundant_clone.rs
clippy_lints/src/size_of_in_element_count.rs
clippy_lints/src/undropped_manually_drops.rs
clippy_utils/src/macros.rs
clippy_utils/src/paths.rs

cc #5393
Replaces the macro & mem paths, and catches a couple others that were unused

Replace some more paths with diagnostic items

---

clippy_lints/src/large_enum_variant.rs
tests/ui/large_enum_variant.rs
tests/ui/large_enum_variant.stderr

fixes: #8321 
The size of enums containing generic type was calculated to be 0. 
I changed [large_enum_variant] so that such enums are not linted.

fix false positives of large_enum_variant

---

clippy_lints/src/ptr.rs
tests/ui/ptr_arg.rs

fixes: #8463
changelog: Fix `ptr_arg` when multiple arguments are being checked in one function

Fix `ptr_arg`

---

rustfmt.toml

I noticed that our `rustfmt.toml` still has the edition 2018 listed. This updates the configuration to use 2021.
This luckily doesn't introduce any formatting changes :upside_down_face: 

Update edition in rustfmt.toml

---

clippy_lints/src/methods/unnecessary_filter_map.rs
clippy_lints/src/methods/unnecessary_iter_cloned.rs
clippy_lints/src/methods/utils.rs
tests/ui/unnecessary_filter_map.rs
tests/ui/unnecessary_filter_map.stderr

This is a proposed fix for #4433.
It moves `clone_or_copy_needed` out of `unnecessary_iter_cloned.rs` and into `methods::utils`. It then adds a check of this function to `unnecessary_filter_map::check`.
Fixes #4433

Fix some `unnecessary_filter_map` false positives

---

.github/workflows/clippy.yml
.github/workflows/clippy_bors.yml
.github/workflows/clippy_dev.yml

This should be placed there. No need to run this in PR CI, if clippy_dev
isn't touched. (It will be run by bors anyway)

Move testing of cargo dev new_lint to cargo dev workflow

---

Cargo.toml
tests/compile-test.rs

removes the dependency added in https://github.com/rust-lang/rust-clippy/pull/8451
---
changelog: tests: use std::thread::available_parallelism() instead of num_cpus to get thread count

tests: use std::thread::available_parallelism() instead of num_cpus to get thread count

---

clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_correctness.rs
clippy_lints/src/lib.register_nursery.rs
clippy_lints/src/transmute/mod.rs

This PR reinstates #8418, which was reverted in #8425 (incorrectly I think).
I don't want to start a revert war over this but I feel very strongly that this lint is not in a state that would be a net benefit to users of clippy. In its current form, making this an enabled-by-default `correctness` lint with authoritative-sounding proclamations of undefined behavior does more harm than the benefit of the true positive cases.
I can file a bunch more examples of false positives but I don't want to give the author of this lint the impression that it is ready to graduate from `nursery` as soon as I've exhausted the amount of time I am willing to spend revising this lint.
Instead I would recommend that the author of the lint try running it on some reputable codebases containing transmutes. …

Transmute_undefined_repr to nursery again

---

CHANGELOG.md
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_perf.rs
clippy_lints/src/loops/missing_spin_loop.rs
clippy_lints/src/loops/mod.rs
tests/ui/missing_spin_loop.fixed
tests/ui/missing_spin_loop.rs
tests/ui/missing_spin_loop.stderr
tests/ui/missing_spin_loop_no_std.fixed
tests/ui/missing_spin_loop_no_std.rs
tests/ui/missing_spin_loop_no_std.stderr

This fixes #7809. I went with the shorter name because the function is called `std::hint::spin_loop`. It doesn't yet detect `while let` loops. I left that for a follow-up PR.
---
changelog: new lint: [`missing_spin_loop`]

new lint: `missing-spin-loop`

---

clippy_lints/src/use_self.rs
tests/ui/use_self.fixed
tests/ui/use_self.rs
tests/ui/use_self.stderr

fixes #6955
changelog: check `use_self` in `pat`

check `use_self` in `pat`

---

CHANGELOG.md
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_complexity.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/unnecessary_filter_map.rs
tests/ui/unnecessary_find_map.rs
tests/ui/unnecessary_find_map.stderr

This PR adds an `unnecessary_find_map` lint. It is essentially just a minor enhancement of `unnecessary_filter_map`.
Closes #8467
changelog: New lint `unnecessary_find_map`

Add `unnecessary_find_map` lint

---

clippy_lints/src/transmute/mod.rs

See discussion in https://github.com/rust-lang/rust-clippy/pull/8432

comment about transmute_undefined_repr in nursery

---

CHANGELOG.md
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_perf.rs
clippy_lints/src/methods/iter_with_drain.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/suspicious_operation_groupings.rs
clippy_lints/src/utils/internal_lints/metadata_collector.rs
clippy_utils/src/hir_utils.rs
tests/ui/extend_with_drain.fixed
tests/ui/extend_with_drain.rs
tests/ui/iter_with_drain.fixed
tests/ui/iter_with_drain.rs
tests/ui/iter_with_drain.stderr
tests/ui/range_plus_minus_one.fixed
tests/ui/range_plus_minus_one.rs

Replacing `.drain(..)` with `.into_iter()` makes my project's binary size smaller.
Fixes #1908
Applicability of this suggestion is `MaybeIncorrect` rather than `MachineApplicable` due to the complexity of "checking otherwise usage" X-|
changelog: Add new lint [`iter_with_drain`]

Use `.into_iter()` rather than `.drain(..)`

---

clippy_lints/src/dbg_macro.rs
tests/ui/dbg_macro.rs
tests/ui/dbg_macro.stderr

Omit dbg_macro in test code

---

util/gh-pages/index.html

Partially solves #7958 
Updated styles for filtering options. It now uses dropdown menus.

Improve styles of filtering options for Clippy's lint list

---

CHANGELOG.md
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_complexity.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.rs
clippy_lints/src/methods/option_map_or_none.rs
clippy_lints/src/only_used_in_recursion.rs
clippy_lints/src/question_mark.rs
clippy_lints/src/unnecessary_sort_by.rs
tests/ui/crate_level_checks/no_std_main_recursion.rs
tests/ui/only_used_in_recursion.rs
tests/ui/only_used_in_recursion.stderr

changed:
- added `only_used_in_recursion`.
- fixed code that variables are only used in recursion.
- this would not lint when `unused_variable`
This fixes: #8390 
-----
changelog: add lint [`only_used_in_recursion`]

new lint: `only_used_in_recursion`

---

clippy_utils/src/sugg.rs

My biggest PR to date, about 0.3 Lines have been changed!
Closes https://github.com/rust-lang/rust-clippy/issues/8062
The suggestion seems to work well, as we've received no error reports since the implementation in December. This PR therefore promotes the suggestion to `MachineApplicable`. The tests already include `.fixed` files :)
changelog: [`search_is_some`]: Make more suggestions `MachineApplicable`

Make `search_is_some`s suggestion `MachineApplicable`

---

clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_nursery.rs
clippy_lints/src/lib.register_perf.rs
clippy_lints/src/methods/mod.rs

cc #8538 #8539
r? @giraffate 
changelog: Move [`iter_with_drain`] to nursery

Move iter_with_drain to nursery

---

clippy_lints/src/collapsible_if.rs

changelog: [`collapsible_if`] fix typo in code-block kind specifier

[`collapsible_if`] fix typo in code-block kind specifier

---

clippy_lints/src/transmute/mod.rs
clippy_lints/src/transmute/transmute_undefined_repr.rs
tests/ui/transmute_undefined_repr.rs
tests/ui/transmutes_expressible_as_ptr_casts.stderr

fixes: #8498
fixes: #8501
fixes: #8503
changelog: Allow `transumte_undefined_repr` between fat pointers and `(usize, usize)`
changelog: Allow `transumte_undefined_repr` when one side is a union
changelog: Fix `transumte_undefined_repr` on tuples with one non-zero-sized type.

More `transmute_undefined_repr` fixes

---

clippy_lints/src/transmute/transmute_undefined_repr.rs
tests/ui/transmute_undefined_repr.rs
tests/ui/transmute_undefined_repr.stderr

Partially fixes #8499
changelog: Don't lint `transmute_undefined_repr` when changing the type of generic params

Don't lint `transmute_undefined_repr` when changing the type of generic params

---

clippy_lints/src/ptr.rs
tests/ui/ptr_arg.rs

fixes: #8495
changelog: Don't lint `ptr_arg` on `&mut Cow<_>`

Don't lint `ptr_arg` on `&mut Cow<_>`

---

clippy_lints/src/methods/unnecessary_lazy_eval.rs
tests/ui/unnecessary_lazy_eval.fixed
tests/ui/unnecessary_lazy_eval.rs
tests/ui/unnecessary_lazy_eval.stderr
tests/ui/unnecessary_lazy_eval_unfixable.stderr

Closes #8393 
changelog: [`unnecessary_lazy_eval`] now shows suggestions for long-line lints

`unnecessary_lazy_eval` show suggestions on multiline lint

---

CHANGELOG.md
clippy_lints/src/casts/cast_enum_constructor.rs
clippy_lints/src/casts/mod.rs
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_suspicious.rs
tests/ui/cast_enum_constructor.rs
tests/ui/cast_enum_constructor.stderr

fixes: #1116
changelog: Add lint `cast_enum_constructor`

Add lint `cast_enum_constructor`

---

clippy_lints/src/doc.rs
clippy_lints/src/lib.rs
clippy_lints/src/matches/match_same_arms.rs
clippy_lints/src/write.rs
tests/ui/match_same_arms.stderr
tests/ui/match_same_arms2.rs
tests/ui/match_same_arms2.stderr

fixes #860
fixes #1140
changelog: Don't lint `match_same_arms` when an interposing arm's pattern would overlap

`match_same_arms` fix

---

CHANGELOG.md
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_pedantic.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/unnecessary_join.rs
tests/ui/unnecessary_join.fixed
tests/ui/unnecessary_join.rs
tests/ui/unnecessary_join.stderr

Adds a lint called `unnecessary_join` that detects cases of `.collect::<Vec<String>>.join("")` or `.collect::<Vec<_>>.join("")` on an iterator, suggesting `.collect::<String>()` instead
Fixes: https://github.com/rust-lang/rust-clippy/issues/8570
This is a reopen of https://github.com/rust-lang/rust-clippy/pull/8573
changelog: add lint [`unnecessary_join`]

`unnecessary_join` lint

---

CHANGELOG.md

As always, I'm impressed by how much stuff happened in just one release. Seriously, kudos to everyone who contributed.

Changelog for Rust 1.60.0 :crab: (Kudos to everyone who contributed!)

---

clippy_lints/src/identity_op.rs
tests/ui/identity_op.rs
tests/ui/identity_op.stderr
tests/ui/modulo_arithmetic_integral_const.rs
tests/ui/modulo_arithmetic_integral_const.stderr

Fixes #8508 
changelog: [`identity_op`] now checks for modulos, e.g. `1 % 3`

Check if lhs < rhs in modulos in `identity_op`

---

clippy_lints/src/methods/map_identity.rs
clippy_lints/src/methods/mod.rs
tests/ui/map_identity.fixed
tests/ui/map_identity.rs
tests/ui/map_identity.stderr

Closes #8478
changelog: [`map_identity`] checks for needless `map_err`

[`map_identity`] checks for needless `map_err`

---

clippy_lints/src/map_unit_fn.rs
tests/ui/option_map_unit_fn_fixable.fixed
tests/ui/option_map_unit_fn_fixable.rs
tests/ui/option_map_unit_fn_fixable.stderr
tests/ui/result_map_unit_fn_fixable.fixed
tests/ui/result_map_unit_fn_fixable.rs
tests/ui/result_map_unit_fn_fixable.stderr

Fixes #8569
changelog: Fix incorrect suggestion for `option_map_unit_fn` , `result_map_unit_fn`

Provide suggestion context in map_unit_fn

---

clippy_lints/src/methods/iter_overeager_cloned.rs
tests/ui/iter_overeager_cloned.fixed
tests/ui/iter_overeager_cloned.rs
tests/ui/iter_overeager_cloned.stderr

Fix https://github.com/rust-lang/rust-clippy/issues/8527
changelog: Fix ICE for [`iter_overeager_cloned`]

Fix ICE for `iter_overeager_cloned`

---

clippy_lints/src/transmute/mod.rs
clippy_lints/src/transmute/transmute_int_to_char.rs
tests/ui/transmute.rs
tests/ui/transmute.stderr

changelog: Don't warn ``[`transmute_int_to_char`]`` in const contexts
fixes: #8379

Don't warn int-to-char transmutes in const contexts

---

clippy_lints/src/loops/single_element_loop.rs
tests/ui/single_element_loop.fixed
tests/ui/single_element_loop.rs
tests/ui/single_element_loop.stderr

changelog: [`single_element_loop`] handle arrays in Edition 2021, handle `.iter_mut()` and `.into_iter()`, and wrap in parens if necessary

single_element_loop: handle arrays for Edition2021

---

clippy_lints/src/module_style.rs
tests/ui-cargo/module_style/fail_mod/src/main.stderr
tests/ui-cargo/module_style/fail_no_mod/src/main.stderr

The problem being that when clippy is run in the project's directory `lp` would be a relative path, this wasn't caught by the tests as there `lp` is an absolute path. Being a relative path it did not start with `trim_src_path` and so was ignored
Also allowed the removal of some `.to_os_string`/`.to_owned`s
changelog: Fixes [`self_named_module_files`] and [`mod_module_files`] not linting
Fixes #8123, cc @DevinR528

Handle relative paths in module_files lints

---

clippy_lints/src/lib.rs
clippy_lints/src/undocumented_unsafe_blocks.rs
tests/ui/auxiliary/proc_macro_unsafe.rs
tests/ui/crashes/ice-7868.stderr
tests/ui/undocumented_unsafe_blocks.rs
tests/ui/undocumented_unsafe_blocks.stderr

fixes: #8264
fixes: #8449
One thing came up while working on this. Currently comments on the same line are supported like so:
```rust
/* SAFETY: reason */ unsafe {}
```
Is this worth supporting at all? Anything other than a couple of words doesn't really fit well.
edit: [zulip topic](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/.60undocumented_unsafe_blocks.60.20same.20line.20comment)
changelog: Don't lint `undocumented_unsafe_blocks` when the unsafe block comes from a proc-macro.
changelog: Don't lint `undocumented_unsafe_blocks` when the preceding line has a safety comment and the unsafe block is a sub-expression.

Rework `undocumented_unsafe_blocks`

---

clippy_lints/src/module_style.rs

As the title says nothing special, still a fun fix :)
Closes: #8627

Escape `mod.rs` file mentions to avoid links in our documentation

---

clippy_dev/Cargo.toml
clippy_dev/src/bless.rs
clippy_dev/src/lib.rs
clippy_dev/src/lint.rs
clippy_dev/src/main.rs

Allows you run the local clippy in a specified directory, e.g. allowing
```sh
cargo dev lint tests/ui-cargo/wildcard_dependencies/fail
cargo dev lint ~/my-project
```
The `target` directory is set to a tempdir which isn't ideal for medium/large projects as it would be compiled from scratch. This is to avoid cached clippy messages where you `cargo dev lint dir`, change something in clippy, and run `cargo dev lint dir` again
changelog: Dev: `cargo dev lint` can now be run on a package directory

Allow running `cargo dev lint` on a package directory

---

clippy_lints/src/methods/bytes_nth.rs
tests/ui/bytes_nth.stderr

changelog: fix misspelling in diagnostic message in ``[`bytes_nth`]``

fix misspelling in diagnostic message of `bytes_nth`

---

doc/release.md

This ensures that the link to the Clippy version in the Rust release
blog post works correctly. The additional `(beta)` behind the previous
beta version breaks that link otherwise.
[Rendered](https://github.com/flip1995/rust-clippy/blob/release_changelog_quick_update/doc/release.md)

Add documentation on how to do a minimal changelog update

---

clippy_lints/src/indexing_slicing.rs
tests/ui/indexing_slicing_index.rs
tests/ui/indexing_slicing_index.stderr

fix #8348
changelog: [`indexing_slicing`] fewer false positives in `const` contexts and with `const` indices

`indexing_slicing` should not fire if a valid array index comes from a constant function that is evaluated at compile-time

---

clippy_lints/src/casts/unnecessary_cast.rs
tests/ui/unnecessary_cast.rs
tests/ui/unnecessary_cast_fixable.fixed
tests/ui/unnecessary_cast_fixable.rs

Fix #6923. The [`unnecessary_cast`] lint now will skip casting to non-primitive type.
changelog: fix lint [`unnecessary_cast `]

Fix unnecessary_cast suggestion for type aliasses

---

clippy_lints/src/transmute/transmute_ref_to_ref.rs
tests/ui/transmute.rs
tests/ui/transmute.stderr

Unfortunately I couldn't figure out how to check whether a given expression is in an `unsafe` context or not, so I just unconditionally emit the wrapping `unsafe {}` block in the suggestion. If there is an easy way to get it to work better then I would love to hear it.
changelog: Suggest `from_utf8_unchecked` instead of `from_utf8` in const contexts for ``[`transmute_bytes_to_str`]``
refs: #8379

Suggest from_utf8_unchecked in const contexts

---

clippy_lints/src/methods/mod.rs

Updates the description of `unnecessary_join` in accordance with https://github.com/rust-lang/rust-clippy/pull/8579#issuecomment-1089969859. I've also added a line regarding differences in assembly output, please let me know if it should also make it in.

update unnecessary_join documentation

---

CHANGELOG.md
clippy_dev/src/update_lints.rs
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_style.rs

update_lints now understands raw strings in declare_clippy_lint descriptions.
Supersedes  #8655
cc @Alexendoo thanks for addressing this so quickly. I build a little bit simpler version of your patch. I don't think it really matters what `Literal` we're trying to tokenize, since we assume later, that it is some sort of `str`.

Allow raw lint descriptions

---

clippy_lints/src/unnested_or_patterns.rs
tests/ui/unnested_or_patterns.fixed
tests/ui/unnested_or_patterns.rs
tests/ui/unnested_or_patterns.stderr

replacing it with `&(x | y)` is actually more characters
Fixes #6973
changelog: [`unnested_or_patterns`] ignore `&x | &y`, nesting would result in more characters

ignore `&x | &y` in unnested_or_patterns

---

clippy_lints/src/transmute/utils.rs
tests/ui/transmute_collection.rs

fixes #7706
changelog: Better check size and alignment requirements in `unsound_collection_transmute`

Fix `unsound_collection_transmute`

---

tests/ui/manual_split_once.fixed
tests/ui/manual_split_once.rs

This PR fixed comments in test.
`split_once` was stabilized in 1.52, so I think the comments maybe be wrong.
ref:
https://doc.rust-lang.org/std/string/struct.String.html#method.split_once
thank you in advance.

fix comments in test for split_once

---

clippy_dev/src/main.rs

Allows passing `--remove` to `cargo dev setup <SUBCOMMAND>` as an alternative to `cargo dev remove ...`
Fixes https://github.com/rust-lang/rust-clippy/issues/8663

Allow passing `--remove` to `cargo dev setup <SUBCOMMAND>`

---

clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/str_splitn.rs
tests/ui/crashes/ice-8250.stderr
tests/ui/manual_split_once.fixed
tests/ui/manual_split_once.rs
tests/ui/manual_split_once.stderr
tests/ui/needless_splitn.fixed
tests/ui/needless_splitn.rs
tests/ui/needless_splitn.stderr

changelog: Remove overlap between [`manual_split_once`] and [`needless_splitn`]. Fixes some incorrect `rsplitn` suggestions for [`manual_split_once`] 
Things that can trigger `needless_splitn` no longer trigger `manual_split_once`, e.g.
```rust
s.[r]splitn(2, '=').next();
s.[r]splitn(2, '=').nth(0);
s.[r]splitn(3, '=').next_tuple();
```
Fixes some suggestions:
```rust
let s = "should not match";
s.rsplitn(2, '.').nth(1);
// old -> Some("should not match")
Some(s.rsplit_once('.').map_or(s, |x| x.0));
// new -> None
s.rsplit_once('.').map(|x| x.0);
s.rsplitn(2, '.').nth(1)?;
// old -> "should not match"
s.rsplit_once('.').map_or(s, |x| x.0);
// new -> early returns
s.rsplit_once('.')?.0;
```

Remove overlap between `manual_split_once` and `needless_splitn`

---

clippy_lints/src/methods/iter_with_drain.rs
tests/ui/iter_with_drain.fixed
tests/ui/iter_with_drain.rs

fixes #8538
changelog: Don't lint `iter_with_drain` on references

Don't lint `iter_with_drain` on references

---

clippy_utils/src/hir_utils.rs
tests/ui/same_functions_in_if_condition.rs
tests/ui/same_functions_in_if_condition.stderr

fixes #8139
changelog: Don't consider `Foo<{ SomeConstant }>` and `Foo<{ SomeOtherConstant }>` to be the same, even if the constants have the same value.

Fix `same_functions_in_if_condition` FP

---

clippy_lints/src/matches/mod.rs
clippy_utils/src/source.rs
tests/ui/auxiliary/proc_macro_with_span.rs
tests/ui/single_match_else.rs
tests/ui/single_match_else.stderr

fixes #4952
As always for proc-macro output this is a hack-job of a fix. It would be really nice if more proc-macro authors would set spans correctly.
changelog: Don't lint various lints on proc-macro output.

Don't lint various match lints when expanded by a proc-macro

---

clippy_lints/src/casts/cast_possible_truncation.rs
tests/ui/cast.rs
tests/ui/cast.stderr

changelog: Fix false negative due to subtraction overflow in `cast_possible_truncation`
I *think* a false negative is the worst that can happen from this

Fix subtraction overflow in `cast_possible_truncation`

---

CHANGELOG.md
clippy_lints/src/case_sensitive_file_extension_comparisons.rs
clippy_lints/src/doc.rs
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_style.rs
clippy_lints/src/methods/is_digit_ascii_radix.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/misc_early/mod.rs
clippy_lints/src/non_expressive_names.rs
clippy_utils/src/msrvs.rs
clippy_utils/src/numeric_literal.rs
tests/ui/is_digit_ascii_radix.fixed
tests/ui/is_digit_ascii_radix.rs
tests/ui/is_digit_ascii_radix.stderr
tests/ui/to_digit_is_some.fixed
tests/ui/to_digit_is_some.rs
tests/ui/to_digit_is_some.stderr

Closes #6399 
changelog: Added [`is_digit_ascii_radix`]: recommend `is_ascii_digit()` or `is_ascii_hexdigit()` in place of `is_digit(10)` and `is_digit(16)`

New lint `is_digit_ascii_radix`

---

clippy_lints/src/undocumented_unsafe_blocks.rs
tests/ui/crashes/auxiliary/ice-8681-aux.rs
tests/ui/crashes/ice-8681.rs

fixes #8681
changelog: Fix ICE in `undocumented_unsafe_blocks`

Fix ICE in `undocumented_unsafe_blocks`

---

clippy_lints/src/only_used_in_recursion.rs

This simplifies the visitor code a bit and prevents checking expressions
multiple times. I still think this lint should be removed for now,
because its code isn't really tested.
Fixes #8689 
**NOTE:** Before merging this, we should talk about removing and revisiting this lint. See my comment in #8689 
changelog: prevent infinite recursion in [`only_used_in_recursion`]

Prevent infinite (exponential) recursion in only_used_in_recursion

---

clippy_lints/src/lib.rs
clippy_lints/src/manual_non_exhaustive.rs
tests/ui/manual_non_exhaustive_enum.rs
tests/ui/manual_non_exhaustive_enum.stderr
tests/ui/manual_non_exhaustive_struct.rs
tests/ui/manual_non_exhaustive_struct.stderr

fixes #5714
changelog: Don't lint `manual_non_exhaustive` when the enum variant is used

Don't lint `manual_non_exhaustive` when the enum variant is used

---

clippy_lints/src/ptr.rs
clippy_utils/src/visitors.rs
tests/ui/mut_from_ref.rs
tests/ui/mut_from_ref.stderr

fixes #6326
changelog: Only lint `mut_from_ref` when unsafe code is used.

Only lint `mut_from_ref` when unsafe code is used

---

clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/unnecessary_to_owned.rs
tests/ui/unnecessary_to_owned.fixed
tests/ui/unnecessary_to_owned.rs
tests/ui/unnecessary_to_owned.stderr

This PR fixes ``[`unnecessary_owned`]``.
```rust
fn _msrv_1_35() {
#![clippy::msrv = "1.35"]
let _ = &["x"][..].to_vec().into_iter();
}
fn _msrv_1_36() {
#![clippy::msrv = "1.36"]
let _ = &["x"][..].to_vec().into_iter();
}
```
If we will check this code using clippy, ``[`unnecessary_owned`]`` will modify the code as follows.
```rust
error: unnecessary use of `to_vec`
--> $DIR/unnecessary_to_owned.rs:219:14
|
LL |     let _ = &["x"][..].to_vec().into_iter();
|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use: `["x"][..].iter().copied()`
error: unnecessary use of `to_vec`
--> $DIR/unnecessary_to_owned.rs:224:14
|
LL |     let _ = &["x"][..].to_vec().into_iter();
|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use: `["x"][..].iter().copied()`
```
This is incorrect. Because …

fix unnecessary_to_owned about msrv

---

CHANGELOG.md
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_restriction.rs
clippy_lints/src/lib.rs
clippy_lints/src/pub_use.rs
tests/ui/pub_use.rs
tests/ui/pub_use.stderr

[`pub_use`]
Fixes https://github.com/rust-lang/rust-clippy/issues/8545
[lint_naming]: https://rust-lang.github.io/rfcs/0344-conventions-galore.html#lints
changelog: Adds a lint called `pub_use` that restricts the usage of `pub use ...`

`pub_use` restriction

---

clippy_lints/src/eta_reduction.rs
clippy_utils/src/usage.rs
tests/ui/eta.fixed
tests/ui/eta.rs
tests/ui/eta.stderr
tests/ui/needless_option_as_deref.fixed
tests/ui/needless_option_as_deref.rs

Follow up to #8646, catches when a local is used multiple times because it's in a loop or a closure

Check for loops/closures in `local_used_after_expr`

---

clippy_lints/src/manual_bits.rs
tests/ui/manual_bits.fixed
tests/ui/manual_bits.rs
tests/ui/manual_bits.stderr

A fix for the suggestion from https://github.com/rust-lang/rust-clippy/pull/8213
changelog: [`manual_bits`]: The suggestion now includes a cast for proper type conversion

Add `usize` cast to `clippy::manual_bits` suggestion

---

CHANGELOG.md
clippy_dev/src/new_lint.rs
clippy_dev/src/update_lints.rs
clippy_lints/src/format_push_string.rs
clippy_lints/src/inconsistent_struct_constructor.rs
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_perf.rs
clippy_lints/src/lib.rs
clippy_lints/src/trait_bounds.rs
clippy_utils/src/sugg.rs
lintcheck/src/main.rs
tests/ui/format_push_string.rs
tests/ui/format_push_string.stderr
tests/ui/identity_op.rs
tests/ui/identity_op.stderr

Closes #6261 
changelog: Added [`format_add_string`]: recommend using `write!` instead of appending the result of  `format!`

New lint `format_add_strings`

---

clippy_utils/src/consts.rs
tests/ui/assertions_on_constants.rs

Fixes #7597
changelog: [`assertions_on_constants`] ignore constants indirectly based on `cfg!`

assertions_on_constants: ignore indirect `cfg!`

---

clippy_lints/src/casts/mod.rs

The "use instead" section of the example was not being formatted as Rust code, and the "configuration" documentation was being formatted as Rust code.
changelog: `[cast_abs_to_unsigned]` Fix example/configuration formatting

Fix formatting of `cast_abs_to_unsigned` docs

---

lintcheck/src/main.rs

looks like --allow-no-vcs does no longer exist(?)

lintcheck: fix --fix

---

CHANGELOG.md
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_complexity.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_suspicious.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/needless_option_take.rs
tests/ui/needless_option_take.fixed
tests/ui/needless_option_take.rs
tests/ui/needless_option_take.stderr
tests/ui/option_take_on_temporary.fixed

Fixes #8618 
changelog: Introduce [`needless_option_take`] lint

Introduce needless_option_take lint

---

CHANGELOG.md
clippy_lints/src/bytes_count_to_len.rs
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_complexity.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.rs
clippy_utils/src/paths.rs
tests/ui/bytes_count_to_len.fixed
tests/ui/bytes_count_to_len.rs
tests/ui/bytes_count_to_len.stderr

take over #8375 
close #8083 
This PR adds new lint about  considering replacing `.bytes().count()` with `.len()`.
---
r! @Manishearth 
changelog: adds new lint [`bytes_count_to_len`] to consider replacing `.bytes().count()` with `.len()`

Take over: New lint bytes count to len

---

clippy_lints/src/matches/needless_match.rs
tests/ui/needless_match.fixed
tests/ui/needless_match.rs
tests/ui/needless_match.stderr

fix #8695
changelog: Fixed ``[`needless_match`]`` false positive when else block expression differs.

Fix needless_match false positive for if-let when the else block doesn't match to given expr

---

clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_pedantic.rs
clippy_lints/src/lib.register_perf.rs
clippy_lints/src/stable_sort_primitive.rs
tests/ui/stable_sort_primitive.stderr

fixes #8241 
Hey all - first contribution here so I'm deciding to start with something small.
Updated the linked message to be less authoritative as well as moved the lint grouping from `perf` to `pedantic` as suggested by @camsteffen under the issue.
changelog: [`stable_sort_primitive`]: emit less authoritative message and move to `pedantic`

Less authoritative stable_sort_primitive message

---

CHANGELOG.md
clippy_lints/src/empty_drop.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_restriction.rs
clippy_lints/src/lib.rs
tests/ui/empty_drop.fixed
tests/ui/empty_drop.rs
tests/ui/empty_drop.stderr

Closes #8352 
changelog: New lint [`empty_drop`]

add `empty_drop`

---

clippy_lints/src/collapsible_if.rs
tests/ui/collapsible_else_if.fixed
tests/ui/collapsible_else_if.rs
tests/ui/collapsible_else_if.stderr

changelog: Fix missing whitespace in [`collapsible_else_if`] suggestion
closes #7318

Fix missing whitespace in `collapsible_else_if` suggestion

---

clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/str_splitn.rs
tests/ui/manual_split_once.fixed
tests/ui/manual_split_once.rs
tests/ui/manual_split_once.stderr

changelog: `manual_split_once`: lint manual iteration of `SplitN`
Now lints:
```rust
let mut iter = "a.b.c".splitn(2, '.');
let first = iter.next().unwrap();
let second = iter.next().unwrap();
let mut iter = "a.b.c".splitn(2, '.');
let first = iter.next()?;
let second = iter.next()?;
let mut iter = "a.b.c".rsplitn(2, '.');
let first = iter.next().unwrap();
let second = iter.next().unwrap();
let mut iter = "a.b.c".rsplitn(2, '.');
let first = iter.next()?;
let second = iter.next()?;
```
It suggests (minus leftover whitespace):
```rust
let (first, second) = "a.b.c".split_once('.').unwrap();
let (first, second) = "a.b.c".split_once('.')?;
let (second, first) = "a.b.c".rsplit_once('.').unwrap();
let (second, first) = "a.b.c".rsplit_once('.')?;
```
Currently only lints if the statements are …

`manual_split_once`: lint manual iteration of `SplitN`

---

tests/dogfood.rs

https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/unknown.20lint.20in.20test.20dogfood_clippy
It's only a warning so this wasn't causing the test to fail, but if you had another error somewhere or used `--nocapture` the extra warnings would be shown

dogfood: allow unknown lints when not running with `internal` feature

---

clippy_lints/src/redundant_pub_crate.rs
tests/ui/redundant_pub_crate.fixed
tests/ui/redundant_pub_crate.rs

changelog: Add macro export exemption to `redundant_pub_crate`
closes #8732

Add macro export exemption to `redundant_pub_crate`

---

clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/wrong_self_convention.rs
tests/ui/wrong_self_convention.rs
tests/ui/wrong_self_convention.stderr
tests/ui/wrong_self_convention2.rs

fix #8480 and #8513
Allowing `is_*` to take `&self` or none is too restrictive.
changelog: FPs: [`wrong_self_convention`] now allows `&mut self` and no self as arguments for `is_*` methods

wrong_self_convention allows `is_*` to take `&mut self`

---

clippy_lints/src/literal_representation.rs
tests/ui/mistyped_literal_suffix.fixed
tests/ui/mistyped_literal_suffix.rs
tests/ui/mistyped_literal_suffix.stderr

This PR fixes 2 things:
- The known problem that integer types are always suggested as signed, by suggesting an unsigned suffix for literals that wouldnt fit in the signed type, and ignores any literals too big for the corresponding unsigned type too.
- The lint would only look at the integer part of any floating point literals without an exponent, this causing #6129. This just ignores those literals.
Examples:
```rust
let _ = 2_32; // still 2_i32
let _ = 234_8; // would now suggest 234_u8
// these are now ignored
let _ = 500_8;
let _ = 123_32.123;
```
changelog: suggest correct integer types in [`mistyped_literal_suffix`], ignore float literals without an exponent
fixes #6129

mistyped_literal_suffix: improve integer suggestions, avoid wrong float suggestions

---

clippy_lints/src/lifetimes.rs
tests/ui/crashes/ice-2865.rs
tests/ui/crashes/ice-3151.rs
tests/ui/extra_unused_lifetimes.rs
tests/ui/extra_unused_lifetimes.stderr
tests/ui/impl.rs
tests/ui/new_without_default.rs

Fixes #6437 (cc: @carols10cents)
changelog: fix #6437

Extend `extra_unused_lifetimes` to handle impl lifetimes

---

clippy_lints/src/matches/redundant_pattern_match.rs
clippy_lints/src/needless_late_init.rs
clippy_utils/src/ty.rs
tests/ui/needless_late_init.rs
tests/ui/needless_late_init.stderr
tests/ui/needless_late_init_fixable.fixed
tests/ui/needless_late_init_fixable.rs
tests/ui/needless_late_init_fixable.stderr

No longer lints `if let`, personal taste on this one is pretty split, so it probably shouldn't be warning by default. Fixes #8613
```rust
let x = if let Some(n) = y {
n
} else {
1
}
```
No longer lints `let mut`, things like the following are not uncommon and look fine as they are
https://github.com/shepmaster/twox-hash/blob/b169c16d86eb8ea4a296b0acb9d00ca7e3c3005f/src/sixty_four.rs#L88-L93
Avoids changing the drop order in an observable way, where the type of `x` has a drop with side effects and something between `x` and the first use also does, e.g.
https://github.com/denoland/rusty_v8/blob/48cc6cb791cac57d22fab1a2feaa92da8ddc9a68/tests/test_api.rs#L159-L167
The implementation of `type_needs_ordered_drop_inner` was changed a bit, it now uses `Ty::has_significant_drop` and reordered the …

`needless_late_init`: ignore `if let`, `let mut` and significant drops

---

clippy_lints/src/attrs.rs
tests/ui/useless_attribute.fixed
tests/ui/useless_attribute.rs
tests/ui/useless_attribute.stderr

changelog: [`useless_attribute`] no longer lints [`redundant_pub_crate`]
As mentioned in https://github.com/rust-lang/rust-clippy/issues/8732#issuecomment-1106489634
> And it turns out I can't even explicitly allow it at the usage site, because then `clippy::useless_attribute` fires (which would also be a FP?), which is deny-by-default.
> 
> Though it does work if I then allow `clippy::useless_attribute`. 😂
> 
> ```rust
> #[allow(clippy::useless_attribute)]
> #[allow(clippy::redundant_pub_crate)]
> pub(crate) use bit;
> ```
> 
> The originally-reported warning now no longer occurs.

ignore `redundant_pub_crate` in `useless_attribute`

---

clippy_lints/src/eta_reduction.rs
tests/ui/eta.fixed
tests/ui/eta.rs
tests/ui/eta.stderr

Closes https://github.com/rust-lang/rust-clippy/issues/8416,
Closes https://github.com/rust-lang/rust-clippy/issues/7812
Closes https://github.com/rust-lang/rust-clippy/issues/8091
~~Seems like this is fixed in #817 and regressed.~~
Ignore coerced closure false positives, but this will lead to some false negatives on resolvable generics. IMO, this is still an overall improvement
changelog: [`redundant_closure`] ignores coerced closure

`redundant_closure` fix FP on coerced closure

---

.github/workflows/clippy.yml
.github/workflows/clippy_bors.yml
.github/workflows/clippy_dev.yml
.github/workflows/deploy.yml
.github/workflows/remark.yml

The v2 implementation uses Node 12, which is end-of-life on April 30, 2022. See https://nodejs.org/en/about/releases/. Update to v3, which is based on Node 16 whose support lasts until April 30, 2024.
---

Update GitHub Actions actions/checkout@v2 to v3

---

clippy_lints/src/casts/cast_slice_different_sizes.rs
tests/ui/cast_slice_different_sizes.rs
tests/ui/cast_slice_different_sizes.stderr

fixes #8708 
changelog: fixes an ICE introduced in #8445

fix ICE in `cast_slice_different_sizes`

---

clippy_lints/src/large_include_file.rs

Roses are red,
this fix,
was simple to do
Closes: https://github.com/rust-lang/rust-clippy/issues/8765

Add missing quite in `large_include_file` example

---

clippy_lints/src/identity_op.rs
tests/ui/identity_op.rs
tests/ui/identity_op.stderr

fix #8724 
changelog: FP: [`identity_op`]: is now allowed in front of if statements, blocks and other expressions where the suggestion would be invalid.
Resolved simular problems with blocks, mathces, and loops.
identity_op always does NOT suggest reducing `0 + if b { 1 } else { 2 } + 3` into  `if b { 1 } else { 2 } + 3` even in the case that the expression is in `f(expr)` or `let x = expr;` for now.

[FP] identity_op in front of if

---

clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_complexity.rs
clippy_lints/src/lib.register_nursery.rs
clippy_lints/src/only_used_in_recursion.rs

r? @llogiq 
I still think this is the right thing to do for this lint. See: #8782
I want to get this merged before the sync on Thursday, because I want to backport this and the last fix #8691 to beta.
changelog: Move [`only_used_in_recursion`] to nursery

Move only_used_in_recursion to nursery

---

clippy_lints/src/needless_late_init.rs
tests/ui/needless_late_init.stderr
tests/ui/needless_late_init_fixable.stderr

Closes #8530 
Updated the lint to use a `MultiSpan`, showing where the `let` statement was first used and where the initialisation statement was done, as in the format described, for easier readability.
Was wondering why, when pushing the span label for the initialisation statement, that sometimes the prior statement above the initialisation statement gets pulled into the output as well - any insight is appreciated!
---
changelog: [`needless_late_init`]: Now shows the `let` statement where it was first initialized

Easier readability for `needless_late_init` message

---

clippy_lints/src/init_numbered_fields.rs
tests/ui/numbered_fields.fixed
tests/ui/numbered_fields.rs

changelog: Ignore type aliases in [`init_numbered_fields`]
Fixes #8638

Ignore type aliases in `init_numbered_fields`

---

CHANGELOG.md
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_style.rs
clippy_lints/src/lib.rs
clippy_lints/src/strings.rs
tests/ui/trim_split_whitespace.fixed
tests/ui/trim_split_whitespace.rs
tests/ui/trim_split_whitespace.stderr

Closes #8521
changelog: [`trim_split_whitespace`]

add `trim_split_whitespace`

---

clippy_lints/src/casts/mod.rs

Adds the missing line to ``[`cast-slice-different-sizes`]`` lint documentation
fixes #8781 

Added missing `### What it does`

---

clippy_lints/src/attrs.rs

Reverts the change from 034c81b76145a0514916f34713671b16f26988df as it's no longer needed. The test is left just in case. Original issue is #2475. 
changelog: Lint `empty_lint_after_outer_attr` on argumentless macros again

Lint `empty_lint_after_outer_attr` on argumentless macros

---

clippy_lints/src/casts/cast_lossless.rs
tests/ui/cast_size_32bit.stderr

Previously, the `cast_lossless` lint would issue a warning on code that
converted a `usize` value to `f64`, on 32-bit targets.
`usize` to `f64` is a lossless cast on 32-bit targets, however there is
no corresponding `f64::from` that takes a `usize`, so `cast_lossless`'s
suggested replacement does not compile.
This PR disables the lint in the case of casting from `usize` or `isize`.
Fixes #3689.
changelog: [`cast_lossless`] no longer gives wrong suggestion on usize,isize->f64

Fix `cast_lossless` to avoid warning on `usize` to `f64` conversion.

---

clippy_dev/src/lint.rs
clippy_dev/src/main.rs

changelog: Pass through extra args in `cargo dev lint`
Lets you pass some useful flags through, like `-A/W/etc`, `--fix`, `--force-warn`

Pass through extra args in `cargo dev lint`

---

clippy_lints/src/methods/unnecessary_to_owned.rs
tests/ui/recursive_format_impl.stderr
tests/ui/unnecessary_to_owned.fixed
tests/ui/unnecessary_to_owned.rs
tests/ui/unnecessary_to_owned.stderr

My proposed fix for #8759 is to revise the conditions that delineate `redundant_clone` and `unnecessary_to_owned`:
```rust
// Only flag cases satisfying at least one of the following three conditions:
// * the referent and receiver types are distinct
// * the referent/receiver type is a copyable array
// * the method is `Cow::into_owned`
// This restriction is to ensure there is no overlap between `redundant_clone` and this
// lint. It also avoids the following false positive:
//  https://github.com/rust-lang/rust-clippy/issues/8759
//   Arrays are a bit of a corner case. Non-copyable arrays are handled by
// `redundant_clone`, but copyable arrays are not.
```
This change causes a few cases that were previously flagged by `unnecessary_to_owned` to no longer be flagged. But one could argue …

Address `unnecessary_to_owned` false positive

---

CONTRIBUTING.md
clippy_lints/src/bit_mask.rs
doc/adding_lints.md
doc/common_tools_writing_lints.md

Switches over bit_mask.rs to let chains in order to create a nice example
While the rustfmt thing isn't resolved yet, my rust-analyzer isn't a fan of large `if_chains!`s, it stops giving me hover info and such after some number of if statements

Recommend let chains over if_chain in docs

---

tests/dogfood.rs

r? @xFrednet 
When metadata collection is enabled the regular early/late pass registrations are skipped, which the `#[expect()]`s were no fan of: https://github.com/rust-lang/rust-clippy/runs/6356675328?check_suite_focus=true

Ignore unfulfilled_lint_expectations in metadata collection

---

CHANGELOG.md
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_suspicious.rs
clippy_lints/src/lib.rs
clippy_lints/src/rc_clone_in_vec_init.rs
tests/ui/rc_clone_in_vec_init/arc.rs
tests/ui/rc_clone_in_vec_init/arc.stderr
tests/ui/rc_clone_in_vec_init/rc.rs
tests/ui/rc_clone_in_vec_init/rc.stderr

Closes #8719
changelog: Introduce [`rc_clone_in_vec_init`] lint

introduce rc_clone_in_vec_init lint

---

lintcheck/Cargo.toml
lintcheck/lintcheck_crates.toml
lintcheck/src/config.rs
lintcheck/src/main.rs

A grab bag of smaller changes:
Panics if a crate source isn't valid, and fixes the `ryu` crate entry so it's picked up. Took me a while to realise why I couldn't do `cargo lintcheck --only ryu` 😅
Parses messages with `cargo_metadata`, this catches a few more lints that were ignored because the message had an [expansion field](https://docs.rs/cargo_metadata/latest/cargo_metadata/diagnostic/struct.DiagnosticSpanMacroExpansion.html) that contained a path pointing into `.../.toolchains/...`. It also no longer emits some log lines with `null` as the column
It also merges the `run_clippy_lint` invocations and splits `LintcheckConfig` out into its own file

Some lintcheck cleanup

---

clippy_lints/src/vec_init_then_push.rs
clippy_utils/src/higher.rs
clippy_utils/src/visitors.rs
tests/ui/vec_init_then_push.rs
tests/ui/vec_init_then_push.stderr

fixes #7071
This will still lint when a larger number of pushes are done (four currently). The exact number could be debated, but this is more readable then a sequence of pushes so it shouldn't be too large. 
changelog: Don't lint `vec_init_then_push` when further extended.
changelog: Remove `mut` binding from `vec_init_then_push` when possible.

Don't lint `vec_init_then_push` when further extended

---

clippy_lints/src/undocumented_unsafe_blocks.rs
tests/ui/undocumented_unsafe_blocks.rs
tests/ui/undocumented_unsafe_blocks.stderr

Closes #8505 
changelog: This lint checks unsafe impls NOT from macro expansions and checks ones in macro declarations.
~~`unsafe impl`s from macro invocations don't trigger the lint for now.~~
~~This lint checks unsafe impls from/not from macro expansions~~

`undocumented_unsafe_blocks` does not trigger on unsafe trait impls

---

clippy_lints/src/unit_types/let_unit_value.rs
tests/ui/crashes/ice-8821.rs
tests/ui/crashes/ice-8821.stderr

fixes #8821
changelog: Fix ICE in `let_unit_value` when calling a static or const callable type

Fix ICE in `let_unit_value` when calling a static or const callable type

---

clippy_lints/src/rc_clone_in_vec_init.rs
tests/ui/rc_clone_in_vec_init/arc.rs
tests/ui/rc_clone_in_vec_init/arc.stderr
tests/ui/rc_clone_in_vec_init/rc.rs
tests/ui/rc_clone_in_vec_init/rc.stderr

A followup to https://github.com/rust-lang/rust-clippy/pull/8769
I also switch the order of the 2 suggestions, since the loop initialization one is probably the common case.
@xFrednet I'm not letting you guys rest for a minute 😅 
changelog: add suggestions to [`rc_clone_in_vec_init`]

add suggestions to rc_clone_in_vec_init

---

clippy_lints/src/misc.rs
tests/ui/cmp_owned/without_suggestion.rs
tests/ui/cmp_owned/without_suggestion.stderr

fixes #8803
fixes #7365
changelog: Don't lint `cmp_owned` on `From::from` for copy types

Fix `cmp_owned` on copy types

---

Cargo.toml
clippy_lints/src/lib.rs
clippy_lints/src/utils/conf.rs
src/main.rs
tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr

Fixes #8806
Sample output:
```
error: error reading Clippy's configuration file `/home/smoelius/github/smoelius/rust-clippy/clippy.toml`: unknown field `foobar`, expected one of
allow-expect-in-tests              enable-raw-pointer-heuristic-for-send    standard-macro-braces
allow-unwrap-in-tests              enforced-import-renames                  third-party
allowed-scripts                    enum-variant-name-threshold              too-large-for-stack
array-size-threshold               enum-variant-size-threshold              too-many-arguments-threshold
avoid-breaking-exported-api        literal-representation-threshold         too-many-lines-threshold
await-holding-invalid-types        max-fn-params-bools                      trivial-copy-size-limit
blacklisted-names …
```

Improve "unknown field" error messages

---

util/gh-pages/index.html
util/gh-pages/script.js

changelog: Documentation: Add a *copy lint name*-button to Clippy's lint list
closes #7959

Add copy lint name button

---

clippy_lints/src/dbg_macro.rs
clippy_utils/src/lib.rs
tests/ui/dbg_macro.rs

fix: #8758 
changelog: [dbg_macro] tolerates use of `dbg!` in items with `#[cfg(test)]` attribute

[dbg_macro] tolerates use of `dbg!` in items which have `#[cfg(test)]` attribute

---

CHANGELOG.md

I'll do the full release and sync tomorrow, as I sadly don't have the time today. This is a quick update to ensure that Rust's changelog will link to the correct section in our changelog.  The change is according to [our docs](https://github.com/rust-lang/rust-clippy/blob/8751e47bae68f6bf7ec833dbd42bde51a74f1a65/book/src/development/infrastructure/release.md#update-changelogmd)

Mini changelog update for Rust 1.61.0

---

clippy_lints/src/deprecated_lints.rs

Just noticed this empty code block that no other lint has :smile:.
r? @xFrednet

Remove code block from `pub_enum_variant_names`

---

util/gh-pages/script.js

This just sets the theme to coal by default if the user prefers dark color schemes.
r? @xFrednet

Auto-detect preferred colorscheme

---

util/gh-pages/script.js

Strip `clippy::` prefix from search strings

---

doc/common_tools_writing_lints.md

The import of `clippy_utils::is_type_diagnostic_item` would cause this error:
```
error[E0432]: unresolved import `clippy_utils::is_type_diagnostic_item
```

Fix imports for "Checking if a type defines a specific method"

---

tests/ui/map_flatten_fixable.fixed
tests/ui/map_flatten_fixable.rs
tests/ui/map_flatten_fixable.stderr

This adds a testcase for a bugfix that has been fixed by https://github.com/rust-lang/rustfix/tree/v0.6.1
`rustfix` is pulled in by `compiletest_rs`. So to test that the correct rustfix version is used, I added one (and a half) testcase.
I tried to add a testcase for #8734 as well, but interesting enough the rustfix is wrong:
```diff
fn issue8734() {
let _ = [0u8, 1, 2, 3]
.into_iter()
-        .and_then(|n| match n {
+        .flat_map(|n| match n {
+            1 => [n
+                .saturating_add(1)
1 => [n
.saturating_add(1)
.saturating_add(1)
.saturating_add(1)
.saturating_add(1)
.saturating_add(1)
.saturating_add(1)
.saturating_add(1)
.saturating_add(1)],
n => [n],
});
}
```
this needs some investigation and then this testcase needs to be enabled by commenting it …

Add some testcases for recent rustfix update

---

CHANGELOG.md
clippy_lints/src/get_first.rs
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_style.rs
clippy_lints/src/lib.rs
clippy_lints/src/methods/iter_next_slice.rs
clippy_utils/src/paths.rs
tests/ui-toml/unwrap_used/unwrap_used.rs
tests/ui/debug_assert_with_mut_call.rs
tests/ui/get_first.fixed
tests/ui/get_first.rs
tests/ui/get_first.stderr
tests/ui/get_unwrap.fixed
tests/ui/get_unwrap.rs
tests/ui/iter_next_slice.fixed
tests/ui/iter_next_slice.rs
tests/ui/iter_next_slice.stderr
tests/ui/needless_lifetimes.rs
tests/ui/needless_lifetimes.stderr

close #8851 
This PR adds new lint about considering replacing .get(0) with .first().
changelog: adds new lint [`get_first`] to consider replacing .get(0) with .first()

feat(lint): impl lint about use first() instead of get(0)

---

clippy_lints/src/match_str_case_mismatch.rs

Remove newlines in [`match_str_case_mismatch`] example

---

CHANGELOG.md
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_nursery.rs
clippy_lints/src/lib.rs
clippy_lints/src/unused_rounding.rs
tests/ui/unused_rounding.fixed
tests/ui/unused_rounding.rs
tests/ui/unused_rounding.stderr

fixes #39 
changelog: added a ``[`unused_rounding`]`` lint to check for the rounding of whole-number literals

Add new lint `[unused_rounding]`

---

clippy_utils/src/lib.rs
tests/ui/crashes/ice-8850.rs
tests/ui/crashes/ice-8850.stderr

Fixes #8850
in `returns.rs` `tcx.fn_sig` is called on the result of `fn_def_id`, which panics if the def is a `const`/`static`/etc rather than a functions definition
https://github.com/rust-lang/rust-clippy/blob/bc4d39e5fea64970dded1e6d2132d41435c0ef24/clippy_lints/src/returns.rs#L294-L303
changelog: Fix ICE due to callable `static`/`const`s

Only return `DefId`s to `Fn`-like definitions in `clippy_utils::fn_def_id`

---

clippy_lints/src/rc_clone_in_vec_init.rs
tests/ui/rc_clone_in_vec_init/arc.stderr
tests/ui/rc_clone_in_vec_init/rc.stderr
tests/ui/rc_clone_in_vec_init/weak.rs
tests/ui/rc_clone_in_vec_init/weak.stderr

changelog: Support `Weak` in [`rc_clone_in_vec_init`]

Support `Weak` in [`rc_clone_in_vec_init`]

---

clippy_lints/src/dbg_macro.rs
clippy_lints/src/lib.rs
clippy_lints/src/utils/conf.rs
tests/ui-toml/dbg_macro/clippy.toml
tests/ui-toml/dbg_macro/dbg_macro.rs
tests/ui-toml/dbg_macro/dbg_macro.stderr
tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr

related to: Issue #8758,  PR https://github.com/rust-lang/rust-clippy/pull/8838
changelog: Introduced `allow-dbg-in-tests` config value. [dbg_macro] does not allow `dbg!` in test code by default.

Introduce `allow-dbg-in-tests` config value

---

Cargo.toml
clippy_lints/src/attrs.rs
tests/compile-test.rs
tests/ui/empty_line_after_outer_attribute.rs
tests/ui/empty_line_after_outer_attribute.stderr

This PR fixes a false positive in `empty_line_after_outer_attribute`.
Here is a minimal example that trigger the FP:
```rust
#[derive(clap::Parser)]
#[clap(after_help = "This ia a help message.
You're welcome.
")]
pub struct Args;
```
changelog: PF: [`empty_line_after_outer_attribute`]: No longer lints empty lines in inner string values.

Fix `empty_line_after_outer_attribute` false positive

---

clippy_lints/src/use_self.rs
tests/ui/use_self.fixed
tests/ui/use_self.rs
tests/ui/use_self.stderr

fixes #8845 
changelog: Triggered the warning for ``[`use_self`]`` on `TupleStruct` and `Struct` patterns, whereas currently it's only triggered for `Path` patterns

Fix `[use_self]` false negative with on struct and tuple struct patterns

---

clippy_lints/src/needless_late_init.rs
tests/ui/needless_late_init.fixed
tests/ui/needless_late_init.rs
tests/ui/needless_late_init.stderr

Fixes #8911
When the assignment is done in a match guard or the if condition and all of the branches return the never type `assignment_suggestions` would return an empty `Vec` which caused the ICE. It now returns `None` in that scenario
Also moves some tests to the top of the file
changelog: ICE Fixes: [`needless_late_init`] #8911

needless_late_init: fix ICE when all branches return the never type

---

clippy_lints/src/casts/cast_abs_to_unsigned.rs
tests/ui/cast_abs_to_unsigned.fixed
tests/ui/cast_abs_to_unsigned.rs
tests/ui/cast_abs_to_unsigned.stderr

Fixes #8873
If `iX` is not cast to `uX` then keep the cast rather than removing it
changelog: [`cast_abs_to_unsigned`]: do not remove cast if it's required

`cast_abs_to_unsigned`: do not remove cast if it's required

---

clippy_lints/src/derive.rs
clippy_utils/src/ty.rs
tests/ui/derive_partial_eq_without_eq.fixed
tests/ui/derive_partial_eq_without_eq.rs

fixes #8867
changelog: Handle differing predicates applied by `#[derive(PartialEq)]` and `#[derive(Eq)]` in `derive_partial_eq_without_eq`

Set correct `ParamEnv` for `derive_partial_eq_without_eq`

---

clippy_lints/src/large_enum_variant.rs
tests/ui/large_enum_variant.rs
tests/ui/large_enum_variant.stderr

Replaces the (erroneous) suggestion on `large_enum_variant` for `Copy` types by a note. This fixes #8894.
---

remove `large_enum_variant` suggestion for `Copy` types

---

clippy_lints/src/significant_drop_in_scrutinee.rs
clippy_utils/src/lib.rs
tests/ui/significant_drop_in_scrutinee.rs
tests/ui/significant_drop_in_scrutinee.stderr

When trying to set the current suggestion, if the type of the expression
is not a reference and it is not trivially pure clone copy, we should still
trigger and emit a lint message. Since this fix may require cloning an
expensive-to-clone type, do not attempt to offer a suggested fix.
This change means that matches generated from TryDesugar and AwaitDesugar
would normally trigger a lint, but they are out of scope for this lint,
so we will explicitly ignore matches with sources of TryDesugar or
AwaitDesugar.
changelog: Update for ``[`significant_drop_in_scrutinee`]`` to correctly
emit lint messages for cases where the type is not a reference *and*
not trivially pure clone copy.
changelog: [`significant_drop_in_scrutinee`]: No longer lint on Try `?` 
and `await` desugared expressions.

When setting suggestion for significant_drop_in_scrutinee, add suggestion for MoveAndClone for non-ref

---

clippy_lints/src/methods/option_map_or_none.rs
clippy_lints/src/returns.rs
tests/ui/needless_return.fixed
tests/ui/needless_return.rs
tests/ui/needless_return.stderr

closes #8879
Macro expressions in returns were not checked by `needless_return`. The test added in [this commit](https://github.com/rust-lang/rust-clippy/commit/6396a7a425293745b1810566851c17cf08d36985#diff-a869168cfafb7e6e5010feb76a16389d6c96d59e98113dee5c2b304a5160e43aR51-R55) seems to have regressed.
changelog: [`needless_return`] checks for macro exprs in return statements

`needless_return` checks for macro expr in return stmts

---

CHANGELOG.md
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_pedantic.rs
clippy_lints/src/lib.rs
clippy_lints/src/mismatching_type_param_order.rs
tests/ui/mismatching_type_param_order.rs
tests/ui/mismatching_type_param_order.stderr

changelog: Add new lint [`mismatching_type_param_order`] for checking if type parameters are consistent between type definitions and impl blocks.
fixes #7147

Add new lint `mismatching_type_param_order`

---

CHANGELOG.md
clippy_lints/src/as_underscore.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_restriction.rs
clippy_lints/src/lib.rs
tests/ui/as_underscore.fixed
tests/ui/as_underscore.rs
tests/ui/as_underscore.stderr

closes #8847
detect usage of `as _` and enforce the usage of explicit type like 
```rust
fn foo(n: usize) {}
let n: u16 = 256;
foo(n as _);
```
will suggest to change to
```rust
fn foo(n: usize) {}
let n: u16 = 256;
foo(n as usize);
```
changelog: add [`as_underscore`] lint

add [`as_underscore`] lint

---

clippy_lints/src/utils/internal_lints/metadata_collector.rs

changelog: Display past names of renamed lints on Clippy's lint list
cc #7172
r? @xFrednet

Collect renamed lints

---

clippy_lints/src/loops/for_loops_over_fallibles.rs
clippy_lints/src/loops/mod.rs
tests/ui/for_loops_over_fallibles.rs
tests/ui/for_loops_over_fallibles.stderr
tests/ui/manual_map_option.fixed
tests/ui/manual_map_option.rs
tests/ui/manual_map_option.stderr

fix #6762
detects code like 
```rust
for _ in option.iter() {
//..
}
```
changelog: Improve [`for_loops_over_fallibles`] to detect `for _ in option.iter() {}` or using `iter_mut()` or `into_iterator()`.

improve [`for_loops_over_fallibles`] to detect the usage of iter, iter_mut and into_iterator

---

clippy_lints/src/needless_late_init.rs

Some refactoring in `needless_late_init`

---

clippy_lints/src/utils/conf.rs
tests/ui-toml/blacklisted_names_append/blacklisted_names.rs
tests/ui-toml/blacklisted_names_append/blacklisted_names.stderr
tests/ui-toml/blacklisted_names_append/clippy.toml
tests/ui-toml/blacklisted_names_replace/blacklisted_names.rs
tests/ui-toml/blacklisted_names_replace/blacklisted_names.stderr
tests/ui-toml/blacklisted_names_replace/clippy.toml
tests/ui-toml/doc_valid_idents_append/clippy.toml
tests/ui-toml/doc_valid_idents_append/doc_markdown.rs
tests/ui-toml/doc_valid_idents_append/doc_markdown.stderr
tests/ui-toml/doc_valid_idents_replace/clippy.toml
tests/ui-toml/doc_valid_idents_replace/doc_markdown.rs
tests/ui-toml/doc_valid_idents_replace/doc_markdown.stderr

I've seen some `clippy.toml` files, that have a few additions to the default list of a configuration and then a copy of our default. The list will therefore not be updated, when we add new names. This change should make it simple for new users to append values instead of replacing them.
I'm uncertain if the documentation of the `".."` is apparent. Any suggestions are welcome. I've also check that the lint list displays the examples correctly.
<details>
<summary>Lint list screenshots</summary>
</details> 
---
changelog: enhancement: [`doc_markdown`]: Users can now indicate, that the `doc-valid-idents` should extend the default and not replace it
changelog: enhancement: [`blacklisted-name`]: Users can now indicate, that the `blacklisted-names` should extend the default and not replace it …

List configuration values can now be extended instead of replaced

---

clippy_lints/src/methods/iter_overeager_cloned.rs
clippy_lints/src/methods/mod.rs
clippy_utils/src/ty.rs
tests/ui/iter_overeager_cloned.fixed
tests/ui/iter_overeager_cloned.rs
tests/ui/iter_overeager_cloned.stderr

fixes: #8494
changelog: Don't lint `iter_overeager_cloned` on `.cloned().flatten()` when `T::Item` doesn't implement `IntoIterator`

Changes to `iter_overeager_cloned`

---

clippy_lints/src/derive.rs
tests/ui/derive_partial_eq_without_eq.fixed
tests/ui/derive_partial_eq_without_eq.rs
tests/ui/derive_partial_eq_without_eq.stderr

fixes  #8875 
changelog: Don't lint `derive_partial_eq_without_eq` on non-public types
changelog: Better handle generics in `derive_partial_eq_without_eq`

Fixes for `derive_partial_eq_without_eq`

---

clippy_lints/src/checked_conversions.rs
tests/ui/checked_conversions.fixed
tests/ui/checked_conversions.rs

close: https://github.com/rust-lang/rust-clippy/issues/8898
This PR fixes a bug in checked_conversions.
changelog: check const context in checked_conversions.

fix(lint): check const context

---

clippy_lints/src/casts/mod.rs
clippy_lints/src/doc.rs
clippy_lints/src/index_refutable_slice.rs
clippy_lints/src/loops/mod.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/needless_late_init.rs
clippy_lints/src/octal_escapes.rs
clippy_lints/src/only_used_in_recursion.rs
clippy_lints/src/redundant_slicing.rs
clippy_lints/src/single_char_lifetime_names.rs

Correct some `#[clippy::version]`s

---

clippy_lints/src/async_yields_async.rs
clippy_lints/src/default_numeric_fallback.rs
clippy_lints/src/dereference.rs
clippy_lints/src/same_name_method.rs
tests/ui/async_yields_async.fixed
tests/ui/async_yields_async.rs
tests/ui/default_numeric_fallback_i32.fixed
tests/ui/default_numeric_fallback_i32.rs
tests/ui/default_numeric_fallback_i32.stderr
tests/ui/needless_borrow.fixed
tests/ui/needless_borrow.rs
tests/ui/needless_borrow.stderr
tests/ui/ref_binding_to_reference.rs
tests/ui/ref_binding_to_reference.stderr
tests/ui/same_name_method.rs
tests/ui/same_name_method.stderr

Fixing the first few lints that aren't caught by `#[expect]`. The root cause of these examples was, that the lint was emitted at the wrong location.
---
r? @Jarcho 
cc: rust-lang/rust#97660

Fix some `#[expect]` lint interaction

---

tests/ui/eta.fixed
tests/ui/eta.rs

Add tests for some fixed `redundant_closure` issues

---

.github/workflows/clippy_bors.yml

This PR adds a new check to bors CI workflows, which ensures that the metadata collection success, when it's run as part of the `deploy` script. I've only added it to bors workflows, as the runtime will be high while it'll also succeed most of the time. This is a preparation for rust-lang/rust-clippy#8947.
---
r? @ghost

Test metadata collection in Bors CI workflow

---

clippy_dev/src/lint.rs
clippy_dev/src/main.rs
clippy_dev/src/new_lint.rs
clippy_dev/src/serve.rs
lintcheck/src/config.rs

Clap `3.2.0` deprecated a few functions used by lintcheck.

Fix `clap` deprecation warnings

---

clippy_lints/src/copies.rs
clippy_utils/src/hir_utils.rs
clippy_utils/src/lib.rs
tests/ui/branches_sharing_code/false_positives.rs
tests/ui/branches_sharing_code/shared_at_bottom.stderr
tests/ui/branches_sharing_code/shared_at_top.stderr
tests/ui/branches_sharing_code/shared_at_top_and_bottom.stderr

fixes #7378
This changes the lint from checking pairs of blocks, to checking all the blocks at the same time. As such there's almost none of the original code left.
changelog: Don't lint `branches_sharing_code` when using different binding names

Rework `branches_sharing_code`

---

clippy_lints/src/lib.rs
tests/ui-toml/bad_toml/conf_bad_toml.rs
tests/ui-toml/bad_toml_type/conf_bad_type.rs
tests/ui-toml/conf_deprecated_key/conf_deprecated_key.rs
tests/ui-toml/good_toml_no_false_negatives/conf_no_false_negatives.rs
tests/ui-toml/toml_unknown_key/conf_unknown_key.rs

The `clippy_lints` one [is unused](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/.60error-pattern.60), the others in `ui-toml` also appear not to have an effect

Remove error-pattern comments

---

CHANGELOG.md
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_correctness.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.rs
clippy_lints/src/read_zero_byte_vec.rs
tests/ui/read_zero_byte_vec.rs
tests/ui/read_zero_byte_vec.stderr

Warn about read into zero-length `Vec`

---

CHANGELOG.md
clippy_lints/src/default_instead_of_iter_empty.rs
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_style.rs
clippy_lints/src/lib.rs
clippy_utils/src/paths.rs
tests/ui/default_instead_of_iter_empty.fixed
tests/ui/default_instead_of_iter_empty.rs
tests/ui/default_instead_of_iter_empty.stderr

close #8915 
This PR adds `default_iter_empty` lint.
This lint checks `std::iter::Empty::default()` and replace with `std::iter::empty()`.
---
changelog: add `default_instead_of_iter_empty` lint.

feat(lint): add default_iter_empty

---

tests/ui/needless_return.fixed
tests/ui/needless_return.rs
tests/ui/needless_return.stderr

The stdio locks no longer fail to compile if the `return` is removed due to them now being `'static` (#9008)

Use `RefCell` in `needless_return` tests

---

clippy_lints/src/unused_async.rs
tests/ui/methods.rs
tests/ui/methods.stderr
tests/ui/should_impl_trait/corner_cases.rs
tests/ui/unused_async.rs
tests/ui/unused_async.stderr

Now lints:
```rust
impl Foo {
async fn method(&self) -> &'static str {
"no await here"
}
}
```
changelog: [`unused_async`]: lint async methods
Fixes #9024

unused_async: lint async methods

---

clippy_lints/src/copies.rs
clippy_utils/src/hir_utils.rs
tests/ui/if_same_then_else.rs
tests/ui/if_same_then_else.stderr

close: #8836
take over:  #8853 
This PR adds  check `todo!` and `unimplemented!` in if_same_then_else. 
( I thought `unimplemented` should not be checked as well as todo!.)
changelog: ignore todo! and unimplemented! in if_same_then_else
r? @Jarcho

feat(fix): ignore `todo!` and `unimplemented!` in `if_same_then_else`

---

clippy_lints/src/loops/mod.rs

example for `WHILE_LET_ON_ITERATOR`, using `for` instead of `while let`

Example for `WHILE_LET_ON_ITERATOR`

---

clippy_lints/src/neg_multiply.rs
tests/ui/neg_multiply.fixed
tests/ui/neg_multiply.rs
tests/ui/neg_multiply.stderr

changelog: [`neg_multiply`]: put parentheses around suggestion if needed

put parentheses around neg_multiply suggestion if needed

---

clippy_lints/src/utils/internal_lints.rs
tests/ui-internal/collapsible_span_lint_calls.fixed
tests/ui-internal/collapsible_span_lint_calls.rs

close #8798 
This PR fixes false positive when using chain in `collapsible_span_lint_calls`.

confirm  using chain in collapsible_span_lint_calls

---

clippy_lints/src/vec_resize_to_zero.rs

Example for VEC_RESIZE_TO_ZERO - what we should use instead

Example for VEC_RESIZE_TO_ZERO

---

clippy_lints/src/slow_vector_initialization.rs
tests/ui/slow_vector_initialization.rs
tests/ui/slow_vector_initialization.stderr

fix #8800
for example 
```rust
let mut vec1 = Vec::with_capacity(len);
vec1.resize(vec1.capacity(), 0);
let mut vec2 = Vec::with_capacity(len);
vec2.extend(repeat(0).take(vec2.capacity()));
```
will trigger the lint
---
changelog: add `vec.capacity()` to [`slow_vec_initialization`] detection

add vec.capacity() to [`slow_vec_initialization`] detection

---

src/driver.rs

Just a thing I've noticed while tinkering on the driver. Currently, the driver only checks for `--cap-lints=allow` to determine if Clippy should run on the code, but ignores possible `--force-warn` arguments
---
changelog: Others: Allowing all lints and only `--force-warn`ing some will now work with Clippy's driver

Check for `--force-warn` in Clippy's driver run condition

---

clippy_lints/src/non_copy_const.rs
tests/ui/declare_interior_mutable_const/others.rs

close #8493 
This PR ignores `thread_local` macro in `declare_interior_mutable_const`.
changelog: ignore `thread_local!` macro in `declare_interior_mutable_const`

ignore item in `thread_local!` macro

---

clippy_lints/src/matches/single_match.rs
tests/ui/single_match.stderr
tests/ui/single_match_else.rs
tests/ui/single_match_else.stderr

fixes #8928 
changelog: did some cleanup of the logic for ``[`single_match`]`` and ``[`single_match_else`]`` which fixes the bug where `Option` matches were not linted unless a wildcard was used for one of the arms.

Lint `[single_match]` on `Option` matches

---

.github/workflows/remark.yml

Optional chain (`?.`) is available in `node v14`, but node version in CI is `node v12`, so CI is failed now.
ref:
https://github.com/rust-lang/rust-clippy/runs/7059529735?check_suite_focus=true
optional chain:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#browser_compatibility
Corresponding PR (maybe)
https://github.com/remarkjs/remark/pull/1007

update node.js version in `remark.yml`

---

clippy_lints/src/enum_variants.rs
tests/ui/enum_variants.rs
tests/ui/enum_variants.stderr

close #9018 
When Enum prefix is only an underscore, we should not issue warnings.
changelog: fix false positive in enum_variant_names

enum_variant_names should ignore when all prefixes are _

---

clippy_lints/src/lib.rs
clippy_lints/src/transmute/mod.rs
clippy_lints/src/transmute/transmute_ptr_to_ref.rs
clippy_lints/src/transmute/utils.rs
tests/ui/transmute_ptr_to_ref.fixed
tests/ui/transmute_ptr_to_ref.stderr

fixes #8924
changelog: Suggest casting the pointer for any type containing lifetimes in `transmute_ptr_to_ref`.
changelog: Suggest `pointer::cast` when possible in `transmute_ptr_to_ref`.

Suggest `pointer::cast` when possible in `transmute_ptr_to_ref`

---

CHANGELOG.md
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_complexity.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/loops/manual_find.rs
clippy_lints/src/loops/mod.rs
clippy_lints/src/non_expressive_names.rs
tests/ui/manual_find.rs
tests/ui/manual_find.stderr
tests/ui/manual_find_fixable.fixed
tests/ui/manual_find_fixable.rs
tests/ui/manual_find_fixable.stderr
tests/ui/while_let_on_iterator.fixed
tests/ui/while_let_on_iterator.rs
tests/ui/while_let_on_iterator.stderr

part of the implementation discussed in #7143 
changelog: add [`manual_find`] lint for function return case

add [`manual_find`] lint for function return case

---

clippy_lints/src/lib.rs
clippy_lints/src/pass_by_ref_or_value.rs
clippy_utils/src/ty.rs
tests/ui/trivially_copy_pass_by_ref.rs
tests/ui/trivially_copy_pass_by_ref.stderr

fixes #5953
fixes #2961
The fix for #5953 is overly aggressive, but the suggestion is so bad that it's worth the false negatives. Basically three things together:
* It's not obviously wrong
* It compiles
* It may actually work when tested
changelog: Don't lint `trivially_copy_pass_by_ref` when unsafe pointers are used.
changelog: Better track lifetimes when linting `trivially_copy_pass_by_ref`.

`trivially_copy_pass_by_ref` fixes

---

clippy_lints/src/matches/mod.rs
clippy_lints/src/matches/significant_drop_in_scrutinee.rs
tests/ui/significant_drop_in_scrutinee.rs
tests/ui/significant_drop_in_scrutinee.stderr

Adds more details about how a significant drop in a match scrutinee can cause a deadlock and include link to documentation.
changelog: Add more details to significant drop lint to explicitly show how temporaries in match scrutinees can cause deadlocks.

Add details about how significant drop in match scrutinees can cause deadlocks

---

tests/ui/auxiliary/proc_macro_derive.rs
tests/ui/extra_unused_lifetimes.rs
tests/ui/extra_unused_lifetimes.stderr

Add test to cover for #9014 which is fixed in #9037.
changelog: [`extra_unused_lifetimes`] Add FP test case emitting from derived attributes.
---
Seeing the FP from the test:
```sh
$ git revert -m 1 1d1ae10876d3eaa5c982dd3daa083b7c2fc363b9
$ TESTNAME=extra_unused_lifetime cargo uitest
```

`extra_unused_lifetimes` add FP test case emitting from derived attributes.

---

clippy_lints/src/loops/while_let_loop.rs
clippy_lints/src/matches/redundant_pattern_match.rs
clippy_utils/src/visitors.rs
tests/ui/while_let_loop.rs

fixes #7226
fixes #7913
fixes #5717
For #5717 it may not stay fully fixed. This is only completely fixed right now due to all the allowed drop impls have `#[may_dangle]` on their drop impls. This may get changed in the future based on how significant drops are determined, but the example listed with `RefCell` shouldn't break.
changelog: Don't lint `while_let_loop` when the order of significant drops would change

Don't lint `while_let_loop` when significant drop order would change

---

clippy_lints/src/large_const_arrays.rs
clippy_lints/src/matches/mod.rs

https://rust-lang.github.io/rust-clippy/master/#significant_drop_in_scrutinee

fix typo in Clippy Lints page

---

.github/workflows/clippy_bors.yml

r? @xFrednet 
Currently bors runs the `metadata_collection` but merges before the run is finished, because the bors success dummy step didn't depend on it. This also makes sure that the `metadata_collection` test is run at the same time as the other base runs to not produce overhead.

Make sure bors success depends on metadata_collection

---

tests/ui/map_flatten_fixable.fixed
tests/ui/map_flatten_fixable.rs
tests/ui/map_flatten_fixable.stderr

I believe the issue was an interaction between rustfix and `span_lint_and_sugg_for_edges`, so this would've been fixed by https://github.com/rust-lang/rust/pull/98261 (Thanks, @WaffleLapkin!)
Closes #8734

Uncomment test for #8734

---

clippy_lints/src/equatable_if_let.rs
tests/ui/auxiliary/macro_rules.rs
tests/ui/equatable_if_let.fixed
tests/ui/equatable_if_let.rs
tests/ui/equatable_if_let.stderr

Was linting in external macros. I guess now that I know about https://github.com/rust-lang/rust-clippy/pull/8694 it seems all kinda pointless until we resolve that.
Nevertheless, it's an improvement.
Fixes #9066.
changelog:`equatable_if_let` No longer lint on macros

Fix false-positive in `equatable_if_let`

---

CHANGELOG.md

This special artifact was just discovered. The artifact details changes to something called Clippy. Presently and from the context, we were unable to determine what this is supposed to be. All we know, is that it seems to have an active community around it which supports it. The members sometimes use paper clips as a secret symbol for Clippy.
I want to donate this artifact to the rust-lang organization, to have it displayed to the public.
---

Changelog for Rust 1.62 :t-rex:

---

clippy_lints/src/methods/mod.rs

The hyperlinks in [`is_digit_ascii_radix`](https://rust-lang.github.io/rust-clippy/master/index.html#is_digit_ascii_radix)'s docs are broken. This PR fixes those.

Fix broken hyperlink in documentation

---

book/src/development/basics.md
clippy_dev/src/dogfood.rs
clippy_dev/src/lib.rs
clippy_dev/src/main.rs
tests/dogfood.rs

changelog: Add `cargo dev dogfood`
Part of #5394

Add `cargo dev dogfood`

---

clippy_lints/src/unit_types/let_unit_value.rs
clippy_lints/src/unit_types/mod.rs
tests/ui/let_unit.fixed
tests/ui/let_unit.rs
tests/ui/let_unit.stderr

Fixes part of #9080
Not sure why it doesn't work when the lint is emitted at the statement, but switching it to the local works fine
changelog: Fix direct `#[allow]` attributes in [`let_unit_value`]

Fix direct `#[allow]` attributes in `let_unit_value`

---

book/README.md

This change corrects the book link on the Clippy Book README.md.

corrected README.md book link

---

book/src/development/infrastructure/changelog_update.md
clippy_lints/src/await_holding_invalid.rs
clippy_lints/src/casts/mod.rs
clippy_lints/src/crate_in_macro_def.rs
clippy_lints/src/drop_forget_ref.rs
clippy_lints/src/empty_drop.rs
clippy_lints/src/methods/mod.rs

closes: https://github.com/rust-lang/rust-clippy/issues/9088
---
It feels weird to have such a short PR description. So, what should I add to this one... Yes, art:
```txt
,-----.,--.,--.                       
'  .--./|  |`--' ,---.  ,---.,--. ,--. 
|  |    |  |,--.| .-. || .-. |\  '  /  
'  '--'\|  ||  || '-' '| '-' ' \   '   
`-----'`--'`--'|  |-' |  |-'.-'  /    
`--'   `--'  `---'     
```
```txt
,-----.,--.   ,--.,------. ,------.,--.   ,--. 
'  .--./|  |   |  ||  .--. '|  .--. '\  `.'  /  
|  |    |  |   |  ||  '--' ||  '--' | '.    /   
'  '--'\|  '--.|  ||  | --' |  | --'    |  |    
`-----'`-----'`--'`--'     `--'        `--'    
```
```txt
_____ _      _____ _____  _______     __
/ ____| |    |_   _|  __ \|  __ \ \   / /
| |    | |      | | | |__) | |__) \ \_/ / …
```

Correct `[clippy::version]` for 1.62 lints and add note to docs

---

util/etc/vscode-tasks.json

Closes #9108 
changelog: remove trailing spaces,  which are not allowed by the JSON standard.

Remove trailing spaces

---

CHANGELOG.md
clippy_lints/src/invalid_utf8_in_unchecked.rs
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_correctness.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.rs
clippy_utils/src/paths.rs
tests/ui/invalid_utf8_in_unchecked.rs
tests/ui/invalid_utf8_in_unchecked.stderr

changelog: Add [`invalid_utf8_in_unchecked`]
closes: #629
Don't know how useful of a lint this is, just saw this was a really old issue :smile:.

Add `invalid_utf8_in_unchecked`

---

clippy_lints/src/dereference.rs
tests/ui/explicit_auto_deref.fixed
tests/ui/explicit_auto_deref.rs
tests/ui/explicit_auto_deref.stderr

fixes #9089
changelog: Fix ICE when dereferencing or borrowing on explicit returns from closures

Fix ICE in `dereference.rs`

---

clippy_lints/src/new_without_default.rs
tests/ui/new_without_default.rs

Fixes #9113
No longer lints if `fn new` has any params
changelog: [`new_without_default`]: no longer lints const generics and lifetime params on `fn new`

`new_without_default`: ignore const generics/lifetime params on `fn new`

---

clippy_lints/src/undocumented_unsafe_blocks.rs
tests/ui/undocumented_unsafe_blocks.rs
tests/ui/undocumented_unsafe_blocks.stderr

fixes #9114
changelog: Fix `undocumented_unsafe_blocks` not checking for comments before the start of a closure

Fix `undocumented_unsafe_blocks` in closures

---

clippy_lints/src/dereference.rs
tests/ui/needless_borrow.fixed
tests/ui/needless_borrow.rs

fixes #9095
changelog: Don't lint `needless_borrow` on method receivers when it would change which trait impl is called

Fix `needless_borrow` 9095

---

clippy_lints/src/methods/filter_map.rs
tests/ui/manual_filter_map.fixed
tests/ui/manual_filter_map.rs
tests/ui/manual_filter_map.stderr
tests/ui/manual_find_map.fixed
tests/ui/manual_find_map.rs
tests/ui/manual_find_map.stderr

changelog: Lint simple expressions in [`manual_filter_map`], [`manual_find_map`]
The current comparison rules out `.find(|a| a.is_some()).map(|b| b.unwrap())` because `a` being a reference can effect more complicated expressions, this adds a simple check for that case and adds the necessary derefs
There's some overlap with `option_filter_map` so `lint_filter_some_map_unwrap` now returns a `bool` to indicate it linted

Lint simple expressions in `manual_filter_map`, `manual_find_map`

---

clippy_lints/src/matches/significant_drop_in_scrutinee.rs
tests/ui/significant_drop_in_scrutinee.rs

fixes #9135
changelog: Ignore the `IntoIterator::into_iter` call from for loops in `significant_drop_in_scrutinee`

Ignore `into_iter` in `significant_drop_in_scrutinee`

---

clippy_lints/src/unit_types/let_unit_value.rs
clippy_lints/src/unit_types/mod.rs
clippy_utils/src/visitors.rs
tests/ui/let_unit.fixed
tests/ui/let_unit.rs
tests/ui/let_unit.stderr

fixes #8998
changelog: Lint `let_unit_value` less aggressively when the type is specified

Allow `let_unit_value` in more cases

---

clippy_lints/src/methods/or_fun_call.rs
tests/ui/or_fun_call.fixed
tests/ui/or_fun_call.stderr

Closes #9033
changelog: [`or_fun_call`]: span points to the `unwrap_or` only instead of through the entire method chain expression

Fix span for or_fun_call

---

CONTRIBUTING.md

Remove broken link in CONTRIBUTING.md

---

clippy_lints/src/copies.rs
clippy_utils/src/lib.rs
clippy_utils/src/visitors.rs
tests/ui/branches_sharing_code/false_positives.rs

fixes #7198
fixes #7452
fixes #7555
fixes #7589
changelog: Don't suggest moving modifications to locals used in any of the condition expressions in `branches_sharing_code`
changelog: Don't suggest moving anything after a local with a significant drop in `branches_sharing_code`

Fixes for `branches_sharing_code`

---

clippy_lints/src/loops/explicit_counter_loop.rs

close #9013 
This PR changes  applicability type to `MaybeIncorrect`,  because the suggestion is not `MachineApplicable`.
changelog: change applicability type to MaybeIncorrect in `explicit_counter_loop`

change applicability type to MaybeIncorrect in `explicit_counter_loop`

---

clippy_lints/src/trait_bounds.rs
tests/compile-test.rs
tests/ui/trait_duplication_in_bounds.rs
tests/ui/trait_duplication_in_bounds.stderr

I thought I would try and scratch my own itch for #8674.
1. Is comparing the `Res` the correct way for ensuring we have the same trait?
2. Is there a way to get the spans for the bounds and clauses for suggestions?
I tried to use `GenericParam::bounds_span_for_suggestions` but it only gave me an empty span at the end of the spans.
I tried `WhereClause::span_for_predicates_or_empty_place` and it included the comma.
3. Is there a simpler way to get the trait names? I have used the spans of the traits because I didn't see a way to get it off the `Res` or `Def`.
changelog: Add ``[`repeated_where_clause_or_trait_bound`]`` lint.

Add `repeated_where_clause_or_trait_bound` lint

---

clippy_lints/src/loops/manual_flatten.rs
tests/lint_message_convention.rs
tests/ui/manual_flatten.rs
tests/ui/manual_flatten.stderr

fixes  #8948 
Whenever suggestion for this lint does not fit in one line,
legacy solution has some unexpected/unhandled behavior:
lint will then generate two help messages which seem to be shown in the wrong order.
The second help message in that case will contain the suggestion.
The first help message always refers to a suggestion message,
and **it should adapt** depending on the location of the suggestion:
- inline suggestion within the error/warning message
- suggestion separated into a second help text
This is my first contribution here, so I hope I didn't miss anything for creating this PR.
changelog: fix [`manual_flatten`] help texts order

fix [`manual_flatten`] help texts order

---

tests/lint_message_convention.rs

They were being recompiled for `Message::new` call, for me this shaves 7s off the time it takes to run the test. Also removes a redundant exception from the list and joins the various `message...` exceptions into one

Use `LazyLock` for `lint_message_convention` regexes

---

clippy_lints/src/loops/while_let_on_iterator.rs
clippy_utils/src/lib.rs
clippy_utils/src/ty.rs
tests/ui/while_let_on_iterator.fixed
tests/ui/while_let_on_iterator.rs
tests/ui/while_let_on_iterator.stderr

changelog: Improve `while_let_on_iterator` suggestion inside an `FnOnce` closure

Improve `while_let_on_iterator` suggestion inside an `FnOnce` closure

---

clippy_lints/src/format_push_string.rs
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_pedantic.rs
clippy_lints/src/lib.register_perf.rs
clippy_lints/src/lib.register_restriction.rs

Fixes #9077 (kinda) by moving the lint to the restriction group. As I noted in that issue, I think the suggested change is too much and as the OP of the issue points out, the ramifications of the change are not necessarily easily understood. As such I don't think the lint should be enabled by default.
changelog: [`format_push_string`]: moved to restriction (see #9077).

Move format_push_string to restriction

---

clippy_lints/src/types/box_collection.rs
tests/ui/box_collection.rs
tests/ui/box_collection.stderr

So far, only [`Vec`, `String`, `HashMap`] were considered.
Extend collection checklist for this lint with:
- `HashSet`
- `VecDeque`
- `LinkedList`
- `BTreeMap`
- `BTreeSet`
- `BinaryHeap`
changelog: [`box_collection`]: raise warn for all std collections

[`box_collection`]: raise warn for all std collections

---

CONTRIBUTING.md

According to [rust-analyzer docs](https://rust-analyzer.github.io/manual.html#toolchain:~:text=rust%2Danalyzer.rustc.source), rustcSource has been renamed to rustc.source.

Rename rustcSource in contributing documentation

---

clippy_lints/src/methods/mod.rs

changelog: More info on `NEEDLESS_OPTION_TAKE`

`NEEDLESS_OPTION_TAKE` doc improvements

---

clippy_lints/src/regex.rs

Close #9194 
changelog: previous example doesn't trigger lint

Fix example for `clippy::invalid_regex`

---

clippy_lints/src/mismatching_type_param_order.rs
tests/ui/mismatching_type_param_order.rs

changelog: Don't lint `mismatching_type_param_order` on complicated generic params
fixes #8962

Fix `mismatching_type_param_order` false positive

---

CHANGELOG.md
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_style.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/obfuscated_if_else.rs
tests/ui/obfuscated_if_else.fixed
tests/ui/obfuscated_if_else.rs
tests/ui/obfuscated_if_else.stderr

part of #9100, additional commits could make it work with `then` and `unwrap_or_else` as well
changelog: Add new lint `obfuscated_if_else`

Add new lint `obfuscated_if_else`

---

clippy_lints/src/std_instead_of_core.rs

The description previously claimed it ensures items are imported from alloc, to ensure a crate won't require alloc, which can't be true.
I'm not sure know how to better phrase the changelog entry below.
changelog: [`alloc_instead_of_core`]: fixed typo in description

Fix typo in alloc_instead_of_core

---

clippy_lints/src/dereference.rs
tests/ui/needless_borrow.fixed
tests/ui/needless_borrow.rs
tests/ui/needless_borrow.stderr

Fixes #9160 
changelog: [`needless_borrow`]: Fix suggestion removing parens from calling a field

Fix suggestion causing error for [`needless_borrow`] function in field

---

Cargo.toml
tests/compile-test.rs
tests/ui-cargo/cargo_common_metadata/fail/Cargo.toml
tests/ui-cargo/cargo_common_metadata/fail/src/main.stderr
tests/ui-cargo/cargo_common_metadata/fail_publish/Cargo.toml
tests/ui-cargo/cargo_common_metadata/fail_publish/src/main.stderr
tests/ui-cargo/cargo_common_metadata/fail_publish_true/Cargo.toml
tests/ui-cargo/cargo_common_metadata/fail_publish_true/src/main.stderr
tests/ui-cargo/cargo_common_metadata/pass/Cargo.toml
tests/ui-cargo/cargo_common_metadata/pass_publish_empty/Cargo.toml
tests/ui-cargo/cargo_common_metadata/pass_publish_false/Cargo.toml
tests/ui-cargo/cargo_rust_version/fail_both_diff/Cargo.toml
tests/ui-cargo/cargo_rust_version/fail_both_same/Cargo.toml
tests/ui-cargo/cargo_rust_version/fail_cargo/Cargo.toml
tests/ui-cargo/cargo_rust_version/fail_clippy/Cargo.toml
tests/ui-cargo/cargo_rust_version/fail_file_attr/Cargo.toml
tests/ui-cargo/cargo_rust_version/pass_both_same/Cargo.toml
tests/ui-cargo/cargo_rust_version/pass_cargo/Cargo.toml
tests/ui-cargo/cargo_rust_version/pass_clippy/Cargo.toml
tests/ui-cargo/cargo_rust_version/pass_file_attr/Cargo.toml
tests/ui-cargo/cargo_rust_version/warn_both_diff/Cargo.toml
tests/ui-cargo/module_style/fail_mod/Cargo.toml
tests/ui-cargo/module_style/fail_no_mod/Cargo.toml
tests/ui-cargo/module_style/pass_mod/Cargo.toml
tests/ui-cargo/module_style/pass_no_mod/Cargo.toml
tests/ui-cargo/multiple_config_files/no_warn/Cargo.toml
tests/ui-cargo/multiple_config_files/warn/Cargo.toml
tests/ui-cargo/multiple_crate_versions/pass/Cargo.toml

This PR adds a test to check the metadata of packages in the `ui_cargo` directory.
A recent change to Cargo causes it to warn when it finds multiple packages with the same name in a git dependency (the issue is described [here](https://github.com/rust-lang/cargo/issues/10752)).
Many (if  not all) Dylint libraries depend upon `clippy_utils`. As a result of the change, one now sees the following when building a Dylint library:
```
warning: skipping duplicate package `fail` found at `/home/smoelius/.cargo/git/checkouts/rust-clippy-4b72815e96774b3d/0cb0f76/tests/ui-cargo/module_style/pass_mod`
warning: skipping duplicate package `fail` found at `/home/smoelius/.cargo/git/checkouts/rust-clippy-4b72815e96774b3d/0cb0f76/tests/ui-cargo/module_style/fail_no_mod`
warning: skipping duplicate package …
```

Add `ui_cargo_toml_metadata` test

---

tests/ui/crate_level_checks/entrypoint_recursion.rs
tests/ui/crate_level_checks/entrypoint_recursion.stderr

Verified that this test actually works on windows

Enable test for entrypoint_recursion for windows

---

clippy_lints/src/operators/assign_op_pattern.rs
tests/ui/assign_ops.fixed
tests/ui/assign_ops.rs
tests/ui/assign_ops.stderr

fixes #9180
changelog: [`assign_op_pattern`](https://rust-lang.github.io/rust-clippy/master/#assign_op_pattern): Don't lint when the suggestion would cause borrowck errors.

Check `assign_op_pattern` for conflicting borrows

---

clippy_lints/src/case_sensitive_file_extension_comparisons.rs

Closing #9220
changelog: [`case_sensitive_file_extension_comparisons`]: update example

Update case_sensitive_file_extension_comparisons example

---

clippy_lints/src/as_conversions.rs

changelog: fix outdated lint names in "as_conversions" documentation

fix outdated lint names in docs

---

clippy_lints/src/format.rs
tests/ui/format.fixed
tests/ui/format.rs
tests/ui/format.stderr

Fixes #9234
changelog: [`useless_format`]: Fix spans for `format!("{foo}")`
https://github.com/rust-lang/rust/pull/94030 made our workaround unneeded, but by coincidence our test still passed [because `Span::new()` swaps `hi` & `lo` if needed](https://github.com/rust-lang/rust/blob/c32dcbba187d1ee0dbe92dc152cb9c2f3f42900c/compiler/rustc_span/src/span_encoding.rs#L86-L88). So with a single character variable like `format!("{x}")` it still worked

Fix `useless_format` spans for `format!("{foo}")`

---

clippy_lints/src/question_mark.rs
tests/ui/crashes/ice-9242.rs

fixes #9242
changelog: [`question_mark`](https://rust-lang.github.io/rust-clippy/master/#question_mark): Fix ICE on zero field tuple structs

Fix ICE in `question_mark`

---

Cargo.toml
clippy_lints/src/non_copy_const.rs
tests/ui/declare_interior_mutable_const/others.rs
tests/ui/declare_interior_mutable_const/others.stderr

close #8493 
close #9224 
This PR fixes false positives in `[non_copy_const]`.
changelog: fix false positives in`[non_copy_const]`
---
r? @Jarcho

check macro statements in `[non_copy_const]`

---

CHANGELOG.md
clippy_lints/src/assertions_on_result_states.rs
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_style.rs
clippy_lints/src/lib.rs
tests/ui/assertions_on_result_states.fixed
tests/ui/assertions_on_result_states.rs
tests/ui/assertions_on_result_states.stderr

Close #9162 
changelog: add `[assertions_on_result_states]` lint
Signed-off-by: tabokie <xy.tao@outlook.com>

add `[assertions_on_result_states]` lint

---

clippy_lints/src/lib.rs
clippy_lints/src/std_instead_of_core.rs
tests/ui/std_instead_of_core.rs
tests/ui/std_instead_of_core.stderr

fixes #9239
This also reorders the execution of the lint to do as little as possible in the case where the path doesn't start with `std` or `alloc`.
changelog: [`std_instead_of_core`](https://rust-lang.github.io/rust-clippy/master/#std_instead_of_core): Don't lint on `use std::env`
changelog: [`std_instead_of_alloc`](https://rust-lang.github.io/rust-clippy/master/#std_instead_of_alloc): Don't lint `use std::vec` twice

Don't lint `std_instead_of_core` on `std::env`

---

CHANGELOG.md
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_restriction.rs
clippy_lints/src/lib.rs
clippy_lints/src/operators/arithmetic.rs
clippy_lints/src/operators/mod.rs
clippy_lints/src/utils/conf.rs
tests/ui-toml/arithmetic_allowed/arithmetic_allowed.rs
tests/ui-toml/arithmetic_allowed/clippy.toml
tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
tests/ui/arithmetic.fixed
tests/ui/arithmetic.rs

Fixes https://github.com/rust-lang/rust-clippy/issues/8903
r? @llogiq 
changelog: Add `Arithmetic` lint

Add `Arithmetic` lint

---

clippy_utils/src/consts.rs
clippy_utils/src/lib.rs
tests/ui/crashes/ice-9238.rs

fixes #9238
changelog: Fix ICE when using `#![feature(generic_const_exprs)]` in various lints

Fix ICE in `miri_to_const`

---

book/src/continuous_integration/github_actions.md

As this type of document is often copied/pasted, using a newer version of `actions/checkout` would be better.
Signed-off-by: Yuki Okushi <jtitor@2k36.org>

Use `action/checkout@v3` in the book

---

book/src/development/adding_lints.md
clippy_dev/src/main.rs
clippy_dev/src/new_lint.rs
clippy_dev/src/update_lints.rs
clippy_lints/src/cargo/mod.rs
clippy_lints/src/matches/mod.rs
clippy_lints/src/operators/mod.rs

This only works with directories, `--type={copies, doc, ...}` won't work. Should they be counted?

Add `--type` flag to `dev new_lint`

---

clippy_lints/src/methods/expect_used.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/unwrap_used.rs
tests/ui-toml/expect_used/expect_used.stderr
tests/ui/expect.stderr
tests/ui/unwrap_expect_used.rs
tests/ui/unwrap_expect_used.stderr

Fixes #9222 
```
changelog: [`unwrap_used`]: Don't recommend using `expect` when the `expect_used` lint is not allowed
```

unwrap_used: Don't recommend using `expect` when the `expect_used` lint is not allowed

---

CONTRIBUTING.md

Make it easier to find the developer guide

---

clippy_lints/src/assertions_on_result_states.rs
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_restriction.rs
clippy_lints/src/lib.register_style.rs
tests/ui/assertions_on_result_states.fixed
tests/ui/assertions_on_result_states.rs
tests/ui/assertions_on_result_states.stderr

Close #9263
This lint causes regression on readability of code and log output. And printing runtime values is not particularly useful for majority of tests which should be reproducible.
changelog: Move [`assertions_on_result_states`] to restriction and don't lint it for unit type
Signed-off-by: tabokie <xy.tao@outlook.com>

Move [`assertions_on_result_states`] to restriction

---

tests/ui/empty_loop_no_std.rs
tests/ui/empty_loop_no_std.stderr

Verified that it actully works on windows

Enable test empty_loop_no_std on windows

---

clippy_lints/src/checked_conversions.rs
clippy_lints/src/create_dir.rs
clippy_lints/src/from_str_radix_10.rs
clippy_lints/src/loops/manual_memcpy.rs
clippy_lints/src/loops/needless_range_loop.rs
clippy_lints/src/manual_ok_or.rs
clippy_lints/src/map_err_ignore.rs
clippy_lints/src/map_unit_fn.rs
clippy_lints/src/matches/match_as_ref.rs
clippy_lints/src/matches/try_err.rs
clippy_lints/src/mem_replace.rs
clippy_lints/src/path_buf_push_overwrite.rs
clippy_lints/src/question_mark.rs
clippy_lints/src/ranges.rs
clippy_lints/src/regex.rs
clippy_lints/src/slow_vector_initialization.rs
clippy_lints/src/stable_sort_primitive.rs
clippy_lints/src/useless_conversion.rs
clippy_lints/src/verbose_file_reads.rs

Some improvements:
- Simplify implementation of `is_unit_type`
- Use slice matching to destruct `Call` or `MethodCall` whenever possible
r? @flip1995

chore: a few small improvements to code quality

---

CHANGELOG.md
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_pedantic.rs
clippy_lints/src/lib.rs
clippy_lints/src/manual_instant_elapsed.rs
clippy_utils/src/paths.rs
tests/ui/manual_instant_elapsed.fixed
tests/ui/manual_instant_elapsed.rs
tests/ui/manual_instant_elapsed.stderr

Closes #8603
---
changelog: [`elapsed_instant`]: Add lint

Add `elapsed_instant` lint

---

clippy_lints/src/redundant_closure_call.rs
clippy_utils/src/sugg.rs
tests/ui/redundant_closure_call_fixable.fixed
tests/ui/redundant_closure_call_fixable.rs
tests/ui/redundant_closure_call_fixable.stderr

Fixes #9052
changelog: Fix suggestions given by [`redundant_closure_call`] for async closures

Fix suggestions for `async` closures in redundant_closure_call

---

tests/ui/redundant_allocation.rs
tests/ui/redundant_allocation.stderr

fix typo in tests/ui/redundant_allocation.rs

---

tests/ui/def_id_nocore.rs
tests/ui/def_id_nocore.stderr

Verified that it actully works on windows

Enable test for def_id_nocore for windows

---

clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_nursery.rs
clippy_lints/src/lib.register_suspicious.rs
clippy_lints/src/matches/mod.rs

The current suggestion of extending the lifetime of every sub-expression is not great and doesn't fix the error given in the lint's example, though it does make the potential deadlock easier to see, but it can also cause it's own issues by delaying the drop of the lock guard.
e.g.
```rust
match x.lock().foo {
..
}
// some stuff
let y = x.lock();
```
The suggestion would create a deadlock at the second `x.lock()` call.
This also lints even when a significant drop type isn't created as a temporary. (#9072)
I agree @kpreid (https://github.com/rust-lang/rust-clippy/issues/8987#issuecomment-1207464440) that this should be back-ported before the lint hits stable.
changelog: Move `significant_drop_in_scrutinee` into `nursey`

Move `significant_drop_in_scrutinee` into `nursey`

---

clippy_utils/src/numeric_literal.rs
tests/ui/mistyped_literal_suffix.fixed
tests/ui/mistyped_literal_suffix.rs
tests/ui/mistyped_literal_suffix.stderr

fixes #9297
changelog: Fix ICE when reading literals with weird proc-macro spans

Fix ICE when reading literals with weird proc-macro spans

---

clippy_lints/src/dereference.rs
clippy_utils/src/ty.rs
tests/ui/explicit_auto_deref.fixed
tests/ui/explicit_auto_deref.rs
tests/ui/explicit_auto_deref.stderr

fixes #9123
fixes #9109
fixes #9143
fixes #9101
This avoid suggesting code which hits a rustc bug. Basically `&{x}` won't use auto-deref if the target type is `Sized`. 
changelog: Don't suggest using auto deref for block expressions when the target type is `Sized`
changelog: Include the borrow in the suggestion for `explicit_auto_deref`
changelog: Don't lint `explicit_auto_deref` on `dyn Trait` return
changelog: Don't lint `explicit_auto_deref` when other adjustments are required
changelog: Lint `explicit_auto_deref` in implicit return positions for closures

`explicit_auto_deref` changes

---

CHANGELOG.md
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_style.rs
clippy_lints/src/lib.rs
clippy_lints/src/partialeq_to_none.rs
tests/ui/ifs_same_cond.rs
tests/ui/manual_assert.edition2018.fixed
tests/ui/manual_assert.edition2021.fixed
tests/ui/manual_assert.fixed
tests/ui/manual_assert.rs
tests/ui/partialeq_to_none.fixed
tests/ui/partialeq_to_none.rs
tests/ui/partialeq_to_none.stderr
tests/ui/same_functions_in_if_condition.rs
tests/ui/same_functions_in_if_condition.stderr

Initial implementation of #9275, adding lint `partialeq_to_none`. This is my first time working on `clippy`, so please review carefully.
I'm unsure especially about the `Sugg`, as it covers the entire `BinOp`, instead of just covering one of the sides and the operator (see the multi-line example). I was unsure if pinpointing the suggestion wouldn't be brittle...
changelog: [`PARTIALEQ_TO_NONE`]: Initial commit

Add partialeq_to_none lint

---

clippy_lints/src/missing_const_for_fn.rs
clippy_utils/src/check_proc_macro.rs
tests/ui/missing_const_for_fn/cant_be_const.rs

This uses @Jarcho's #8694 implementation to fix `missing_const_for_fn` linting in proc-macros.
I'm not 100% sure what I'm doing here, any feedback is appreciated.
Previously: https://github.com/Jarcho/rust-clippy/pull/1.
Fixes #8854.
changelog: [`missing_const_for_fn`]: No longer lints in proc-macros

Use `check_proc_macro` for `missing_const_for_fn`

---

clippy_lints/src/if_then_some_else_none.rs
tests/ui/if_then_some_else_none.stderr

Closes #9094.
changelog: Extend `if_then_some_else_none` to also suggest `bool::then_some`

Extend `if_then_some_else_none` to also suggest `bool::then_some`

---

CHANGELOG.md

1.63 Changelog

---

clippy_lints/src/trait_bounds.rs
tests/compile-test.rs
tests/ui/trait_duplication_in_bounds.fixed
tests/ui/trait_duplication_in_bounds.stderr
tests/ui/trait_duplication_in_bounds_unfixable.rs
tests/ui/trait_duplication_in_bounds_unfixable.stderr

Fixes #9076 #9151 #8757.
Partially fixes #8771.
changelog: [`trait_duplication_in_bounds`]: Reduce number of false positives.

Fixes [`trait_duplication_in_bounds`] false positives

---

clippy_lints/src/methods/unnecessary_to_owned.rs
tests/ui/unnecessary_to_owned.fixed
tests/ui/unnecessary_to_owned.rs

Fixes #9317
changelog: [`unnecessary_to_owned`]: none

Skip `unnecessary_to_owned` when `t != t.to_string()`

---

clippy_lints/src/if_let_mutex.rs
tests/ui/if_let_mutex.rs
tests/ui/if_let_mutex.stderr

Fixes #9193
We can always peel references because we are looking for a method-call, for which autoderef applies.
---
changelog: [`if_let_mutex`]: detect calls to `Mutex::lock()` if mutex is behind a ref
changelog: [`if_let_mutex`]: Add labels to the two instances of the same Mutex that will deadlock

Fix if_let_mutex not checking Mutexes behind refs

---

clippy_lints/src/borrow_deref_ref.rs

I don't think such minor change should be mentioned in the changelog.

Remove extra dereference from the borrow_deref_ref lint example

---

clippy_lints/src/escape.rs

The example didn't show the actual problem [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9d0e0727ca5bbd854767f50da693ca0f)

Fix example

---

clippy_lints/src/unicode.rs
tests/ui/unicode.fixed
tests/ui/unicode.rs
tests/ui/unicode.stderr

changelog: Don't lint [`non_ascii_literal`] when using non-ascii comments in tests
changelog: Don't lint [`non_ascii_literal`] when `allow`ed on tests
closes: #7739
closes: #8263

Fix [`non_ascii_literal`] in tests

---

tests/compile-test.rs

I have a global `CARGO_TARGET_DIR` set, but forgot to delete the old target dir. `compile-test` was getting tripped up on an outdated `rustfix_missing_coverage.txt` I had in there, keeping me from running tests :smile:.

Use `CARGO_TARGET_DIR` in compile-test

---

clippy_lints/src/case_sensitive_file_extension_comparisons.rs

changelog: [`case_sensitive_file_extension_comparisons `]: updated suggestion in the example to use `map_or`
Currently, case_sensitive_file_extension_comparisons suggests using `map(..).unwrap_or(..)` which trips up the `map_unwrap_or` lint.  This updates the suggestion to use `map_or`.

suggest map_or in case_sensitive_file_extension_comparisons

---

tests/compile-test.rs

Handle `CARGO_TARGET_DIR` not being set in compile-test

---

clippy_lints/src/as_underscore.rs

Fix typo in as_undescore docs

---

clippy_lints/src/transmute/transmute_undefined_repr.rs
tests/ui/transmute_undefined_repr.rs
tests/ui/transmute_undefined_repr.stderr

changelog: Don't lint `transmute_undefined_repr` when the the first field of a `repr(C)` type is compatible with the other type

`transmute_undefined_repr` fix

---

clippy_lints/src/methods/expect_used.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/unwrap_used.rs
tests/ui/expect.rs
tests/ui/expect.stderr
tests/ui/unwrap.rs
tests/ui/unwrap.stderr
tests/ui/unwrap_expect_used.rs
tests/ui/unwrap_expect_used.stderr

changelog: [`unwrap_used`]: lint uses of `unwrap_err`
changelog: [`expect_used`]: lint uses of `expect_err`
fixes #9331

unwrap_used and expect_used: trigger on uses of their _err variants

---

clippy_dev/src/bless.rs
clippy_dev/src/fmt.rs
clippy_dev/src/update_lints.rs
clippy_lints/src/dereference.rs
clippy_lints/src/lib.rs
clippy_lints/src/methods/unnecessary_to_owned.rs
clippy_utils/src/msrvs.rs
rustc_tools_util/src/lib.rs
tests/check-fmt.rs
tests/dogfood.rs
tests/integration.rs
tests/lint_message_convention.rs
tests/ui/needless_borrow.fixed
tests/ui/needless_borrow.rs
tests/ui/needless_borrow.stderr
tests/ui/regex.rs
tests/ui/same_item_push.rs
tests/ui/verbose_file_reads.rs
tests/workspace.rs

The proposed enhancement causes `needless_borrow` to suggest removing `&` from `&e` when `&e` is an argument position requiring trait implementations, and `e` implements the required traits. Example:
```
error: the borrowed expression implements the required traits
--> $DIR/needless_borrow.rs:131:51
|
LL |     let _ = std::process::Command::new("ls").args(&["-a", "-l"]).status().unwrap();
|                                                   ^^^^^^^^^^^^^ help: change this to: `["-a", "-l"]`
```
r? @Jarcho
changelog: Enhance `needless_borrow` to consider trait implementations

Enhance `needless_borrow` to consider trait implementations

---

clippy_lints/src/question_mark.rs
tests/ui/question_mark.fixed
tests/ui/question_mark.rs

Fixes #9347
Technically it is possible to have a blank match-pattern that does nothing, and we fail to lint. But it's easier to be safe than sorry here.
changelog: [`question_mark`]: don't lint `if let`s with subpatterns

Don't lint on match pattern-binding in ´question_mark`

---

clippy_lints/src/format.rs
clippy_lints/src/format_args.rs
clippy_lints/src/format_impl.rs
clippy_lints/src/methods/uninit_assumed_init.rs
clippy_lints/src/transmute/transmuting_null.rs
clippy_utils/Cargo.toml
clippy_utils/src/lib.rs
clippy_utils/src/macros.rs
clippy_utils/src/paths.rs
tests/ui/format_args.fixed
tests/ui/format_args.rs
tests/ui/format_args.stderr

It now for each format argument `{..}` has:
- The `Expr` it points to, and how it does so (named/named inline/numbered/implicit)
- The parsed `FormatSpec` (format trait/fill/align/etc., the precision/width and any value they point to)
- Many spans
The caller no longer needs to pair up arguments to their value, or separately interpret the `specs` `Expr`s when it isn't `None`
The gist is that it combines the result of [`rustc_parse_format::Parser`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_parse_format/struct.Parser.html) with the macro expansion itself
This unfortunately makes the code a bit longer, however we need to use both as neither have all the information we're after. `rustc_parse_format` doesn't have the information to resolve named arguments to their values. The macro …

Refactor `FormatArgsExpn`

---

clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_complexity.rs
clippy_lints/src/lib.register_nursery.rs
clippy_lints/src/lib.rs
clippy_lints/src/only_used_in_recursion.rs
clippy_lints/src/redundant_static_lifetimes.rs
tests/ui/only_used_in_recursion.rs
tests/ui/only_used_in_recursion.stderr
tests/ui/only_used_in_recursion2.rs
tests/ui/only_used_in_recursion2.stderr

fixes #8782
fixes #8629
fixes #8560
fixes #8556
This is a complete rewrite of the lint. This loses some capabilities of the old implementation. Namely the ability to track through tuple and slice patterns, as well as the ability to trace through assignments.
The two reported bugs are fixed with this. One was caused by using the name of the method rather than resolving to the `DefId` of the called method. The second was cause by using the existence of a cycle in the dependency graph to determine whether the parameter was used in recursion even though there were other ways to create a cycle in the graph.
Implementation wise this switches from using a visitor to walking up the tree from every use of each parameter until it has been determined the parameter is used for something other than …

Rework `only_used_in_recursion`

---

CHANGELOG.md
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_suspicious.rs
clippy_lints/src/lib.rs
clippy_lints/src/unused_peekable.rs
clippy_utils/src/paths.rs
clippy_utils/src/ty.rs
tests/ui/unused_peekable.rs
tests/ui/unused_peekable.stderr

changelog: Add [`unused_peekable`] lint
closes: #854

Add [`unused_peekable`] lint

---

CHANGELOG.md
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_perf.rs
clippy_lints/src/methods/collapsible_str_replace.rs
clippy_lints/src/methods/mod.rs
tests/ui/collapsible_str_replace.fixed
tests/ui/collapsible_str_replace.rs
tests/ui/collapsible_str_replace.stderr

fixes #6651
```
changelog: [`collapsible_str_replace`]: create new lint `collapsible_str_replace`
```
- \[ ] Executed `cargo dev update_lints`

Lint `collapsible_str_replace`

---

tests/ui/format_args.fixed
tests/ui/format_args.rs
tests/ui/format_args.stderr

Fix #8855
Here is what I think is going on.
First, the expression `format!("{:>6} {:>6}", a, b.to_string())` expands to:
```rust
{
let res =
::alloc::fmt::format(::core::fmt::Arguments::new_v1_formatted(&["",
" "],
&[::core::fmt::ArgumentV1::new_display(&a),
::core::fmt::ArgumentV1::new_display(&b.to_string())],
&[::core::fmt::rt::v1::Argument {
position: 0usize,
format: ::core::fmt::rt::v1::FormatSpec {
fill: ' ',
align: ::core::fmt::rt::v1::Alignment::Right,
flags: 0u32,
precision: ::core::fmt::rt::v1::Count::Implied,
width: ::core::fmt::rt::v1::Count::Is(6usize),
},
},
::core::fmt::rt::v1::Argument {
position: 1usize,
format: ::core::fmt::rt::v1::FormatSpec {
fill: ' ',
align: ::core::fmt::rt::v1::Alignment::Right,
flags: 0u32,
precision: ::core::fmt::rt::v1::Count::Implied,
width: …
```

Add test for #8855

---

clippy_lints/src/option_if_let_else.rs
tests/ui/option_if_let_else.fixed
tests/ui/option_if_let_else.rs
tests/ui/option_if_let_else.stderr

fixes: #8492 
---
changelog: make [`option_if_let_else`] to check for match expression with both Option and Result; **TODO: Change lint name? Add new lint with similar functionality?**

check for if-some-or-ok-else-none-or-err

---

clippy_lints/src/loops/needless_collect.rs
tests/compile-test.rs
tests/ui/needless_collect_indirect.rs
tests/ui/needless_collect_indirect.stderr

close #8753 
we consider the following code.
```rust
fn main() {
let vec = vec![1];
let w: Vec<usize> = vec.iter().map(|i| i * i).collect();  // <- once.
for i in 0..2 {
let _ = w.contains(&i);
}
}
```
and the clippy will issue the following warning.
```rust
warning: avoid using `collect()` when not needed
--> src/main.rs:3:51
|
3 |     let w: Vec<usize> = vec.iter().map(|i| i * i).collect();
|                                                   ^^^^^^^
...
6 |         let _ = w.contains(&i);
|                 -------------- the iterator could be used here instead
|
= note: `#[warn(clippy::needless_collect)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_collect
help: check if the original Iterator contains an element …
```

feat(fix): Do not lint if the target code is inside a loop

---

clippy_lints/src/matches/needless_match.rs
tests/ui/needless_match.fixed
tests/ui/needless_match.rs
tests/ui/needless_match.stderr

closes: #9084 
made needless_match take into account arm in the form of `_ if => ...`

Fix false positives of needless_match

---

clippy_lints/src/format_args.rs
tests/ui/format_args.fixed
tests/ui/format_args.rs
tests/ui/format_args.stderr

Fix `to_string_in_format_args` false positive

---

clippy_lints/src/dereference.rs
clippy_lints/src/escape.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/unnecessary_to_owned.rs
clippy_lints/src/self_named_constructors.rs
clippy_utils/src/ty.rs

This removes some code we don't need and the method syntax is
also more readable IMO.

Replace `contains_ty(..)` with `Ty::contains(..)`

---

clippy_lints/src/uninit_vec.rs

Quick documentation fix: `Vec::spare_capacity_mut` no longer needs nightly.

uninit_vec: Vec::spare_capacity_mut is stable

---

clippy_lints/src/returns.rs
tests/ui/needless_return.fixed
tests/ui/needless_return.rs

Fixes #9361
The lint used to have a mechanic to allow `cfg`-attrs on naked `return`-statements. This was well-intentioned, yet we can have any kind of attribute, e.g. `allow`, `expect` or even custom `derive`. So the mechanic was simply removed. We now never lint on a naked `return`-statement that has attributes on it.
Turns out that the ui-test had a Catch22 in it: In `check_expect()` the `#[expect(clippy::needless_return)]` is an attribute on the `return` statement that can and will be rustfixed away without side effects. But any other attribute would also have been removed, which is what #9361 is about. The test proved the wrong thing. Removed the test, the body is tested elsewhere as well.
changelog: Ignore [`needless_return`] on `return`s with attrs

Don't lint `needless_return` if `return` has attrs

---

CHANGELOG.md
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_suspicious.rs
clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/suspicious_to_owned.rs
tests/compile-test.rs
tests/ui/suspicious_to_owned.rs
tests/ui/suspicious_to_owned.stderr

changelog: Add lint ``[`suspicious_to_owned`]``
-----------------
Hi,
posting this unsolicited PR as I've been burned by this issue :)
Being unsolicited, feel free to reject it or reassign a different lint level etc.
This lint checks whether `to_owned` is called on `Cow<'_, _>`. This is done because `to_owned` is very similarly named to `into_owned`, but the effect of calling those two methods is completely different (one makes the `Cow::Borrowed` into a `Cow::Owned`, the other just clones the `Cow`). If the cow is then passed to code for which the type is not checked (e.g. generics, closures, etc.) it might slip through and if the cow data is coming from an unsafe context there is the potential for accidentally cause undefined behavior.
Even if not falling into this painful case, there's …

Implemented `suspicious_to_owned` lint to check if `to_owned` is called on a `Cow`

---

clippy_lints/src/matches/match_like_matches.rs
clippy_utils/src/lib.rs
tests/ui/match_expr_like_matches_macro.fixed
tests/ui/match_expr_like_matches_macro.rs

Closes #9164
changelog: [`match_like_matches_macro`] is ignored when there is some comment inside the match block.
Also add `span_contains_comment` util to check if given span contains comments.

Ignore `match_like_matches_macro` when there is comment

---

clippy_lints/src/partialeq_to_none.rs
tests/ui/partialeq_to_none.fixed
tests/ui/partialeq_to_none.rs
tests/ui/partialeq_to_none.stderr

This addresses https://github.com/rust-lang/rust-clippy/pull/9288#issuecomment-1229398524: If the literal `None` is from expansion, we never lint. This is correct because e.g. replacing the call to `option_env!` with whatever that macro expanded to at the time of linting is certainly wrong.
changelog: Don't lint [`partialeq_to_none`] for macro-expansions

Don't lint literal `None` from expansion

---

CHANGELOG.md
clippy_lints/src/casts/cast_slice_from_raw_parts.rs
clippy_lints/src/casts/mod.rs
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_suspicious.rs
tests/ui/cast_raw_slice_pointer_cast.fixed
tests/ui/cast_raw_slice_pointer_cast.rs
tests/ui/cast_raw_slice_pointer_cast.stderr

Adds a lint to check for a raw slice being created and cast back to a pointer, suggesting `ptr::slice_from_raw_parts`, to identify UB such as https://github.com/SimonSapin/rust-typed-arena/pull/54.
```
changelog: [`cast_slice_from_raw_parts`]: Add lint to check for `slice::from_raw_parts(.., ..) as *const _`
```

New lint: Raw slice pointer cast

---

tests/ui/suspicious_to_owned.rs

Fix `suspicious_to_owned` test when `c_char` is `u8`

---

clippy_lints/src/floating_point_arithmetic.rs
tests/ui/floating_point_exp.fixed
tests/ui/floating_point_exp.rs
tests/ui/floating_point_exp.stderr
tests/ui/floating_point_log.fixed
tests/ui/floating_point_log.rs
tests/ui/floating_point_log.stderr
tests/ui/floating_point_logbase.fixed
tests/ui/floating_point_logbase.rs
tests/ui/floating_point_logbase.stderr
tests/ui/floating_point_powf.fixed
tests/ui/floating_point_powf.rs
tests/ui/floating_point_powf.stderr
tests/ui/floating_point_powi.fixed
tests/ui/floating_point_powi.rs
tests/ui/floating_point_powi.stderr
tests/ui/floating_point_rad.fixed
tests/ui/floating_point_rad.rs
tests/ui/floating_point_rad.stderr

Fixes #9391. The problem is simple enough, I didn't check if the same problem occurs elsewhere, though.
changelog: fix missing parenthesis in `suboptimal_flops` suggestion

Fix missing parens in `suboptimal_flops` suggestion

---

clippy_lints/src/trait_bounds.rs
tests/ui/trait_duplication_in_bounds.fixed
tests/ui/trait_duplication_in_bounds.stderr
tests/ui/trait_duplication_in_bounds_unfixable.stderr

Makes the lint emit in source order rather than whatever order the hash map happens to be in. This is currently blocking the sync into rustc.

Fix the emission order of `trait_duplication_in_bounds`

---

clippy_lints/src/matches/match_wild_err_arm.rs
tests/ui/match_wild_err_arm.edition2018.stderr
tests/ui/match_wild_err_arm.edition2021.stderr

changelog: [`match_wild_err_arm`]: fix typo in note text

match_wild_err_arm: Fix typo in note text

---

clippy_dev/src/update_lints.rs
clippy_lints/src/write.rs
clippy_utils/src/macros.rs
tests/ui/crashes/ice-9405.rs
tests/ui/crashes/ice-9405.stderr

fixes #9405
changelog: Fix ICE when format literals raise compiler warnings

Correctly handle unescape warnings

---

clippy_lints/src/floating_point_arithmetic.rs
tests/ui/floating_point_powf.fixed
tests/ui/floating_point_powf.rs
tests/ui/floating_point_powf.stderr

There used to be an early return if the receiver was an effective const but the method was not linted, not taking into account later cases where the receiver and the arguments are both effective consts for different methods. Removed the early return.
Fixes #9402
Fixes #9201
changelog: Fix `suboptimal_flops`, `imprecise_flops` not linting on `{const}.powf({const})` et al

Fix `suboptimal_float` not linting on `{const}.powf({const})`

---

CHANGELOG.md
clippy_lints/src/bool_to_int_with_if.rs
clippy_lints/src/lib.register_all.rs
clippy_lints/src/lib.register_lints.rs
clippy_lints/src/lib.register_style.rs
clippy_lints/src/lib.rs
clippy_lints/src/matches/single_match.rs
clippy_lints/src/only_used_in_recursion.rs
tests/ui/author/struct.rs
tests/ui/bool_to_int_with_if.fixed
tests/ui/bool_to_int_with_if.rs
tests/ui/bool_to_int_with_if.stderr

This is a rebased version of https://github.com/rust-lang/rust-clippy/pull/9086 I could sadly not push directly push to the PR branch as it's protected.
The lint implementation comes from @jst-r. Thank you for the work you put into this :)
---
Closes: https://github.com/rust-lang/rust-clippy/issues/8131
Closes: https://github.com/rust-lang/rust-clippy/pull/9086 
changelog: Add lint [`bool_to_int_with_if`]
r? @ghost

New lint `bool_to_int_with_if`

---

clippy_lints/src/functions/result.rs
tests/ui/crashes/ice-9414.rs

fixes #9414
This occurs starting with 2022-09-01. I checked that this does fix the ICE on rust-lang/rust@9353538. Not sure which pr caused the late-bound region to leak through `hir_ty_to_ty`.

Don't use `hir_ty_to_ty` in `result_large_err`

---

clippy_lints/src/methods/mut_mutex_lock.rs
tests/ui/mut_mutex_lock.fixed
tests/ui/mut_mutex_lock.rs

I *think* the problem here is the `if let ty::Ref(_, _, Mutability::Mut) = cx.typeck_results().expr_ty(recv).kind()` line tries to check if the `Mutex` can be mutably borrowed (there already is a test for `Arc<Mutex<_>>`), but gets bamboozled by the `&mut Arc` indirection. And I *think* checking the deref-adjustment to filter immutable-adjust (the deref through the `Arc`, starting from `&mut Arc`) is the correct fix.
Fixes #9415
changelog: Fix `mut_mutex_lock` when Mutex is behind immutable deref

Fix `mut_mutex_lock` when Mutex is behind immutable deref

---

clippy_lints/src/large_enum_variant.rs
src/docs/large_enum_variant.txt
tests/ui/large_enum_variant.rs
tests/ui/large_enum_variant.stderr
tests/ui/result_large_err.rs
tests/ui/result_large_err.stderr

This builds upon #9373 to use the approximate size of each variant for `large_enum_variant`. This allows us to lint in situations where an `enum` contains generics but is still guaranteed to have a large variant on an at-least basis, e.g. with `(T, [u8; 512])`.
* I've changed the wording from "is ... bytes" to "contains at least" because
* the size is now an approximate lower bound (e.g. `512` in the example above). The actual size is larger due to `T`, including due to `T`'s memory layout.
* the discriminant is not taken into account in the message. This comes up with variants like `A(T)`, which are "is at least 0 bytes" otherwise, which may be misleading.
* If the second-largest variant has no fields, there is a special case "carries no data" instead of "is at least 0 bytes".
* A …

Use `approx_ty_size` for `large_enum_variant`

---

clippy_lints/src/methods/unnecessary_to_owned.rs
tests/ui/unnecessary_to_owned.fixed
tests/ui/unnecessary_to_owned.rs
tests/ui/unnecessary_to_owned.stderr

Fixes #9351.
Note that this commit reworks that fix for #9317. The change
is to check that the type implements `AsRef<str>` before regarding
`to_string` as an equivalent of `to_owned`. This was suggested
by Jarcho in the #9317 issue comments.
The benefit of this is that it moves some complexity out of
`check_other_call_arg` and simplifies the module as a whole.
changelog: FP: [`unnecessary_to_owned`]: No longer lints, if type change would cause errors in the caller function

Fix `unnecessary_to_owned` false positive

---

clippy_lints/src/derivable_impls.rs
src/docs/derivable_impls.txt

While looking at the explanation as to why this lint was not automatically applicable, found the explanation a bit clunky grammatically.
Feel free to close if you consider the wording was correct in the first place.

fix wording for `derivable_impls`

---

clippy_lints/src/methods/mod.rs
clippy_lints/src/methods/or_fun_call.rs
src/docs/or_fun_call.txt
tests/ui/or_fun_call.fixed
tests/ui/or_fun_call.stderr

Unlike past similar work done in #6228, expand the existing `or_fun_call`
lint to detect `or_insert` calls with a `T::new()` or `T::default()`
argument, much like currently done for `unwrap_or` calls. In that case,
suggest the use of `or_default`, which is more idiomatic.
Note that even with this change, `or_insert_with(T::default)` calls
aren't detected as candidates for `or_default()`, in the same manner
that currently `unwrap_or_else(T::default)` calls aren't detected as
candidates for `unwrap_or_default()`.
Also, as a nearby cleanup, change `KNOW_TYPES` from `static` to `const`,
since as far as I understand it's preferred (should Clippy have a lint
for that?).
Addresses #3812.
changelog: …

Suggest `Entry::or_default` for `Entry::or_insert(Default::default())`

---

clippy_lints/src/methods/unwrap_or_else_default.rs
tests/ui/unwrap_or_else_default.fixed
tests/ui/unwrap_or_else_default.rs
tests/ui/unwrap_or_else_default.stderr

Closes https://github.com/rust-lang/rust-clippy/issues/9420
changelog: [`unwrap_or_else_default`]: suggest `unwrap_or_default()` instead of `unwrap_or_else` with a closure that returns an empty `to_string`.

Suggest `unwrap_or_default` when closure returns `"".to_string`
