clippy_lints/src/vec_init_then_push.rs, tests/ui/vec_init_then_push.rs, tests/ui/vec_init_then_push.stderr
fixes #9433
changelog: Fix infinite loop in `vec_init_then_push`
=> Fix hang in `vec_init_then_push`

CHANGELOG.md, clippy_lints/src/lib.register_lints.rs, clippy_lints/src/lib.register_restriction.rs, clippy_lints/src/lib.rs, clippy_lints/src/operators/arithmetic_side_effects.rs, clippy_lints/src/operators/mod.rs, clippy_lints/src/utils/conf.rs, src/docs.rs, src/docs/arithmetic_side_effects.txt, tests/ui-toml/arithmetic_allowed/clippy.toml, tests/ui-toml/arithmetic_side_effects_allowed/arithmetic_side_effects_allowed.rs, tests/ui-toml/arithmetic_side_effects_allowed/clippy.toml, tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr, tests/ui/arithmetic_side_effects.rs, tests/ui/arithmetic_side_effects.stderr
changelog: Rename the `arithmetic` lint
=> Rename the arithmetic lint

clippy_lints/src/ranges.rs, tests/ui/range_plus_minus_one.fixed, tests/ui/range_plus_minus_one.rs, tests/ui/range_plus_minus_one.stderr
Fixes #9431.
The current `range_plus_one` and `range_minus_one` suggestions are completely incorrect when macros are involved.
This commit resolves this by disabling the lints for any range expression that is expanded from a macro. The reasons for this are that it is very difficult to create a correct suggestion in this case and that false negatives are less important for pedantic lints.
changelog: Fix `range_{plus,minus}_one` bad suggestions
=> Fix `range_{plus,minus}_one` bad suggestions

tests/ui/large_enum_variant.rs, tests/ui/large_enum_variant.stderr
A u128 has [an 8 byte alignment on x86](https://github.com/rust-lang/rust/issues/54341), but a 16 byte alignment on aarch64 which changes the size of the enums due to extra padding. This means the test fails on aarch64
=> Replace u128 with u64 in large_enum_variant uitest

clippy_lints/src/assertions_on_result_states.rs, clippy_lints/src/methods/err_expect.rs, clippy_lints/src/methods/ok_expect.rs, clippy_utils/src/ty.rs, tests/ui/assertions_on_result_states.fixed, tests/ui/assertions_on_result_states.rs, tests/ui/assertions_on_result_states.stderr
fix https://github.com/rust-lang/rust-clippy/issues/9450
changelog: [`assertions_on_result_states`]: Fix suggestion when `assert!` is not in a statement.
=> [`assertions_on_result_states`]: Fix suggestion when `assert!` is not in a statement.

clippy_lints/src/booleans.rs, tests/ui/nonminimal_bool.rs, tests/ui/nonminimal_bool.stderr
fix https://github.com/rust-lang/rust-clippy/issues/9428
changelog: Do not expand macros in [`nonminimal_bool`] suggestions
=> Do not expand macro in `nonminimal_bool` suggestions

clippy_utils/src/sugg.rs, tests/ui/collapsible_if.fixed, tests/ui/collapsible_if.rs, tests/ui/collapsible_if.stderr
Closes #9375 
changelog: Improvement: [`collapsible_if`]: Suggestions now work with macros, by taking the call site into account.
=> Use macro callsite when creating `Sugg` helper

clippy_utils/src/macros.rs
A small change to make it a little simpler
=> Use `visit_expr_field` for `ParamPosition`

clippy_lints/src/large_stack_arrays.rs, tests/ui/large_stack_arrays.rs, tests/ui/large_stack_arrays.stderr
We now check if the linted `Expr` is inside an `ItemKind::Static`, which can't take the suggested `Box<[...]`. I _think_ this is the correct fix for #9460
I removed `if_chain` while I was at it.
changelog: Don't lint `large_stack_array` inside static items
=> Don't lint `large_stack_array` inside static items

book/src/development/common_tools_writing_lints.md
fix `implements_trait` and `in_external_macro` import path
Remove example using `match_trait_method` since its deprecated.
=> Fix dev book

clippy_lints/src/use_self.rs, tests/ui/use_self.fixed, tests/ui/use_self.rs
fix https://github.com/rust-lang/rust-clippy/issues/9440
fix https://github.com/rust-lang/rust-clippy/issues/8910
fix https://github.com/rust-lang/rust-clippy/issues/6902
changelog: [`use_self`]: Do not lint in proc macro expansion
=> Do not lint `use_self` in proc macro expansion

clippy_lints/src/derivable_impls.rs, tests/ui/derivable_impls.fixed, tests/ui/derivable_impls.stderr
changelog: [`derivable_impls`]: Now machine applicable
=> Make `derivable_impls` machine applicable

clippy_lints/src/almost_complete_letter_range.rs, tests/ui/almost_complete_letter_range.fixed, tests/ui/almost_complete_letter_range.rs, tests/ui/almost_complete_letter_range.stderr, tests/ui/auxiliary/macro_rules.rs
changelog: Fix [`almost_complete_letter_range`] false positive in an external macro
=> Fix `almost_complete_letter_range` false positive.

clippy_lints/src/bool_to_int_with_if.rs, clippy_lints/src/dereference.rs, clippy_lints/src/methods/unnecessary_to_owned.rs, clippy_utils/src/sugg.rs, tests/ui/bool_to_int_with_if.fixed, tests/ui/bool_to_int_with_if.rs, tests/ui/bool_to_int_with_if.stderr, tests/ui/len_without_is_empty.rs
Enhances `bool_to_int_with_if` such that it can also catch an inverse bool int conversion scenario, and makes the right suggestion for converting to int with a prefixed negation operator.
changelog: [`bool_to_int_with_if`]: Now correctly detects the inverse case, `if bool { 0 } else { 1 }`
=> `bool_to_int_with_if` inverse case patch

CONTRIBUTING.md
r-a uses the `rustc-dev` component from the rustup installed toolchain clippy specifies so it doesn't need to be manually installed. Also remove references to nightly r-a as the feature is long stable
I discovered `rust-analyzer.linkedProjects` recently and it has made working on the crates not referenced by the `clippy` crate so much nicer
=> Update rust-analyzer documentation, mention linkedProjects

book/src/development/common_tools_writing_lints.md
Markdowns are not displayed correctly.
https://github.com/rust-lang/rust-clippy/blob/master/book/src/development/common_tools_writing_lints.md#dealing-with-macros-and-expansions
=> Fix indents

CHANGELOG.md, clippy_lints/src/lib.register_all.rs, clippy_lints/src/lib.register_complexity.rs, clippy_lints/src/lib.register_lints.rs, clippy_lints/src/methods/iter_kv_map.rs, clippy_lints/src/methods/mod.rs, src/docs.rs, src/docs/iter_kv_map.txt, tests/ui/iter_kv_map.fixed, tests/ui/iter_kv_map.rs, tests/ui/iter_kv_map.stderr
fixes #9376
| before | after |
| -------------- | ------------------------- |
| `hmap.iter().map(\|(key, _)\| key)` | `hmap.keys()` |
| `hmap.iter().map(\|(_, v)\| v + 2)` | `hmap.values().map(\|v\| v + 2)` |
| `hmap.into_iter().map(\|(key, _)\| key)` | `hmap.into_keys()` |
Is `MachineApplicable`
changelog: [`iter_kv_map`]: added lint
=> Add `iter_kv_map` lint

book/src/development/adding_lints.md, clippy_dev/src/new_lint.rs
`rustfix` tests don't automatically apply `-Aunused` which leads to some tests having `_workarounds`, add it to new test files automatically so people don't have to worry about it
=> Add `#[allow(unused)]` to test in `cargo dev new_lint`

clippy_lints/src/operators/arithmetic_side_effects.rs, tests/ui/arithmetic_side_effects.rs, tests/ui/arithmetic_side_effects.stderr
Extends https://github.com/rust-lang/rust-clippy/pull/9474 to also take into consideration "raw" binary operations. For example, `let a = b / 2` and `let a = 1 * b` won't trigger the lint.
changelog: [arithmetic-side-effects] Finish non-overflowing ops
=> [arithmetic-side-effects] Finish non-overflowing ops

tests/ui/arithmetic_side_effects.rs, tests/ui/arithmetic_side_effects.stderr
Taken from the `integer-arithmetic` lint.
changelog: [arithmetic-side-effects] Add more tests
=> [arithmetic-side-effects] Add more tests

clippy_lints/src/methods/unnecessary_to_owned.rs, tests/ui/unnecessary_to_owned.fixed, tests/ui/unnecessary_to_owned.rs
Fixes #9504
Compiler generated call `into_future` nodes return empty substs which we need when checking it's predicates. Handle this by simply exitting when we encounter one. This change introduces false negatives in place of the ICEs.
changelog: [`unnecessary_to_owned`]: fix ICE
=> Fix ICE in `unnecessary_to_owned`

clippy_lints/src/nonstandard_macro_braces.rs, tests/ui-toml/nonstandard_macro_braces/conf_nonstandard_macro_braces.rs, tests/ui-toml/nonstandard_macro_braces/conf_nonstandard_macro_braces.stderr
changelog: Enhancement: [`nonstandard_macro_braces`]: Now includes `matches!()` in the default lint config
[#9471](https://github.com/rust-lang/rust-clippy/pull/9471)
=> Add matches! checking to nonstandard_macro_braces

CHANGELOG.md, clippy_lints/src/default_instead_of_iter_empty.rs, clippy_lints/src/dereference.rs, clippy_lints/src/loops/mod.rs, clippy_lints/src/manual_rem_euclid.rs, clippy_lints/src/manual_retain.rs
The normal release preparation dance. I've written the changelog like the version has already been released. The PR can be approved and then merged by anyone after the release of Rust 1.64 :upside_down_face: 
---
=> Changelog for Rust 1.64 :apple:

clippy_lints/src/nonstandard_macro_braces.rs, tests/ui-toml/nonstandard_macro_braces/conf_nonstandard_macro_braces.fixed, tests/ui-toml/nonstandard_macro_braces/conf_nonstandard_macro_braces.stderr
fix #9498
based on top of https://github.com/rust-lang/rust-clippy/pull/9471
Also simplify the lint by not caring about code format which should be `rustfmt` job, and turn the lint into machine Applicable
changelog: Suggestion: [`nonstandard_macro_braces`]: The suggestion is now machine applicable and will no longer replace brackets inside the macro argument.
[#9499](https://github.com/rust-lang/rust-clippy/pull/9499)
=> [`nonstandard_macro_braces`] Do not modify macro arguments

clippy_lints/src/uninit_vec.rs, tests/ui/uninit_vec.rs
`set_len(0)` does not create uninitialized elements. Fixes a false positive with the following pattern:
```rust
fn copy_slice_into_vec(dst: &mut Vec<u8>, src: &[u8]) {
dst.reserve(src.len().saturating_sub(dst.len()));
unsafe {
dst.set_len(0);
std::ptr::copy_nonoverlapping(src.as_ptr(), dst.as_mut_ptr(), src.len());
dst.set_len(src.len());
}
}
```
zulip thread: https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/uninit_vec.20and.20set_len.280.29
changelog: FP: [`uninit_vec`]: No longer lints `Vec::set_len(0)`
=> uninit_vec: fix false positive with set_len(0)

Cargo.toml
From `0.8` to `0.9`.
The new version includes a [fix](https://github.com/Manishearth/compiletest-rs/pull/259) for what I suspect was one cause of the recent rustup failure: https://github.com/rust-lang/rust-clippy/actions/runs/3106438892/jobs/5033324694#step:11:911
=> Upgrade `compiletest-rs` dependency

clippy_lints/src/loops/never_loop.rs, tests/ui/never_loop.rs, tests/ui/never_loop.stderr
Fixes #9356 
This has been bugging me for a while, so I thought I'd take a stab at it! I'm completely uncertain about the quality of my code, but I think it's an alright start, so opening this PR to get some feedback from more experienced clippy people :)
changelog: [`never_loop`]: Fix FP with let..else statements
=> [`never_loop`]: Fix FP with let..else statements.

clippy_dev/src/fmt.rs, clippy_dev/src/new_lint.rs, clippy_dev/src/serve.rs, clippy_dev/src/setup/git_hook.rs, clippy_dev/src/setup/intellij.rs, clippy_dev/src/setup/vscode.rs, clippy_dev/src/update_lints.rs, clippy_lints/src/utils/internal_lints.rs, clippy_lints/src/utils/internal_lints/metadata_collector.rs
Continuing #9525 -- a few more inlining, but this time with some code changes to simplify format strings:
* Inline format args where possible
* simplify a few complex macros into format str
* use formatdoc!() instead format!(indoc!(...))
cc: @llogiq
=> fallout2: rework clippy_dev & _lints fmt inlining

clippy_lints/src/needless_pass_by_value.rs, tests/ui/crashes/ice-9459.rs
fixes #9459
Not really sure why a query for a type implementing `FnOnce` even works since the trait if `FnOnce<T>`, but it seems to. I would have expected it to crash like it does when passing `dyn FnOnce()` as the type.
changelog: [`needless_pass_by_value`](https://rust-lang.github.io/rust-clippy/master/#needless_pass_by_value) Fix ICE in with unsized `dyn Fn` argument
=> Fix ICE in `needless_pass_by_value` with unsized `dyn Fn`

clippy_lints/src/derive.rs, clippy_lints/src/lib.register_all.rs, clippy_lints/src/lib.register_nursery.rs, clippy_lints/src/lib.register_style.rs
changelog: Moves: Move `derive_partial_eq_without_eq` to `nursery` (now allow-by-default)
[#9536](https://github.com/rust-lang/rust-clippy/pull/9536)
Closes: https://github.com/rust-lang/rust-clippy/issues/9530
=> Moved derive_partial_eq_without_eq to nursery

tests/integration.rs
=> Fix panic when displaying the backtrace of failing integration tests

clippy_lints/src/question_mark.rs, tests/ui/question_mark.fixed, tests/ui/question_mark.rs
fix https://github.com/rust-lang/rust-clippy/issues/9175
When `const_try` is stabilised can be turned into a MSRV
changelog: Silence [`question_mark`] in const context
=> Silence [`question_mark`] in const context

clippy_lints/src/non_copy_const.rs, tests/ui/crashes/ice-9445.rs
fixes #9445
cc rust-lang/rust#101113
This started ICE'ing sometime last month due to stricter UB checks. I'm not sure how we could check the value of a union as MIRI doesn't seem to store which field is currently active.
changelog: Don't ICE on const unions containing a `!Freeze` type.
=> Don't lint `*_interior_mutable_const` on unions due to potential ICE.

clippy_lints/src/operators/arithmetic_side_effects.rs, tests/ui/arithmetic_side_effects.rs, tests/ui/arithmetic_side_effects.stderr
Takes into consideration integer references like `&i32::MAX` because currently things like `let _ = &1 + 0` trigger the lint.
changelog: FP: [`arithmetic_side_effects`]: Now ignores references
[9507](https://github.com/rust-lang/rust-clippy/pull/9507)
=> [arithmetic-side-effects] Consider references

clippy_lints/src/returns.rs, tests/ui/needless_return.fixed, tests/ui/needless_return.rs, tests/ui/needless_return.stderr
fix #8336,
fix #8156,
fix https://github.com/rust-lang/rust-clippy/issues/7358,
fix #9192,
fix https://github.com/rust-lang/rust-clippy/issues/9503
changelog: [`needless_return`] Recursively remove unneeded semicolons
For now the suggestion about removing the semicolons are hidden because they would be very noisy and should be obvious if the user wants to apply the lint manually instead of using `--fix`. This could be an issue for beginner, but haven't found better way to display it.
=> [`needless_return`] Recursively remove unneeded semicolons

CHANGELOG.md, clippy_lints/src/box_default.rs, clippy_lints/src/lib.register_all.rs, clippy_lints/src/lib.register_lints.rs, clippy_lints/src/lib.register_perf.rs, clippy_lints/src/lib.rs, src/docs.rs, src/docs/box_default.txt, tests/ui/box_collection.rs, tests/ui/box_default.rs, tests/ui/box_default.stderr
This adds a `box-default` lint to suggest using `Box::default()` instead of `Box::new(Default::default())`, which offers less moving parts and potentially better performance according to [the perf book](https://nnethercote.github.io/perf-book/standard-library-types.html#box).
---
changelog: add [`box_default`] lint
=> add `box-default` lint

clippy_lints/src/drop_forget_ref.rs, tests/ui/drop_forget_copy.rs, tests/ui/drop_forget_copy.stderr
close https://github.com/rust-lang/rust-clippy/issues/9482
changelog: [`drop_copy`]: Do not lint idiomatic in match arm
=> [`drop_copy`]: Do not lint idiomatic in match arm

clippy_lints/src/std_instead_of_core.rs, tests/ui/std_instead_of_core.rs, tests/ui/std_instead_of_core.stderr
Fixes #9515
changelog: [`std_instead_of_core`]: No longer suggests unstable modules such as `core::error`
=> Don't lint unstable moves in `std_instead_of_core`

clippy_lints/src/dereference.rs, tests/ui/needless_borrow.fixed, tests/ui/needless_borrow.rs
fix https://github.com/rust-lang/rust-clippy/issues/9383
changelog: fix [`needless_borrow`] false positive on unions
changelog: fix [`explicit_auto_deref`] false positive on unions
Left a couple debug derived impls on purpose I needed to debug as I don't think it's noise
=> fix [`needless_borrow`], [`explicit_auto_deref`] FPs on unions

clippy_utils/src/eager_or_lazy.rs, tests/ui/unnecessary_lazy_eval.fixed, tests/ui/unnecessary_lazy_eval.rs, tests/ui/unnecessary_lazy_eval.stderr
fix #9427
changelog: [`unnecessary_lazy_evaluations`] Do not suggest switching to early evaluation when type has custom `Drop`
=> [`unnecessary_lazy_evaluations`] Do not suggest switching to early evaluation when type has custom `Drop`

clippy_lints/src/methods/unnecessary_lazy_eval.rs, tests/ui/unnecessary_lazy_eval.fixed, tests/ui/unnecessary_lazy_eval.rs, tests/ui/unnecessary_lazy_eval.stderr
fix https://github.com/rust-lang/rust-clippy/issues/9485, fix https://github.com/rust-lang/rust-clippy/issues/9439
I didn't find a way to add a test since fps occur due to an external crate.
changelog: [`unnecessary_lazy_eval`] Do not lint in external macros
=> [`unnecessary_lazy_eval`] Do not lint in external macros

clippy_lints/src/eta_reduction.rs, tests/ui/eta.fixed, tests/ui/eta.rs, tests/ui/eta.stderr
Fixes #9369 
changelog: [`redundant_closure`] Fix suggestion causes error with `impl FnMut` types
=> [`redundant_closure`] Fix suggestion causes error for `impl FnMut`

lintcheck/Cargo.toml, lintcheck/README.md, lintcheck/lintcheck_crates.toml, lintcheck/src/config.rs, lintcheck/src/driver.rs, lintcheck/src/main.rs, lintcheck/src/recursive.rs
r? @matthiaskrgr
This just adds the mode without changing how a regular run works
Takes a fair bit longer to run than a `-j4` or regular run 
```
cargo lintcheck -j4  468.33s user 43.78s system 290% cpu 2:56.42 total
cargo lintcheck  428.81s user 41.85s system 199% cpu 3:55.37 total
cargo lintcheck --recursive  679.83s user 45.01s system 210% cpu 5:43.72 total
```
But finds more results:
<details>
<summary>Stats</summary>
<pre><code>clippy::explicit_counter_loop 0 =&gt; 1
clippy::needless_question_mark 0 =&gt; 3
clippy::unnecessary_cast 0 =&gt; 2
clippy::to_string_in_format_args 0 =&gt; 4
clippy::deprecated_cfg_attr 0 =&gt; 23
clippy::redundant_closure 0 =&gt; 9
clippy::drop_copy 0 =&gt; 4
clippy::double_must_use 0 =&gt; 1
clippy::transmute_num_to_bytes 0 =&gt; 9 …
=> Add `cargo lintcheck --recursive` to check dependencies of crates

Cargo.toml, rustc_tools_util/Cargo.toml, rustc_tools_util/README.md, rustc_tools_util/src/lib.rs
cc https://github.com/rust-lang/rust-clippy/issues/9553
After this is merged, I will publish the 0.2.1 version to crates.io, and make another PR that switches clippy to use the dependency from crates.io.
The source can still be kept in the clippy repo though imo.
This will allow miri and clippy to "share" the crate in the rustc repo once they both depend on it.
reopen of #9561
changelog: release `rustc_tools_util` on `Crates.io`.
=> rustc_tool_utils: bump version in anticipation of a new release

Cargo.toml
=> use rustc_tools_util dependency from crates.io instead of this repo.

clippy_dev/src/update_lints.rs
The old code cloned and sorted `usable_lints` into `sorted_usable_lints`, but then failed to do anything with `sorted_usable_lints`.
This was discovered by my new `collection_is_never_read` lint (#9267) that I'm working on!
Fix: I renamed the sorted vector to `usable_lints`.  Therefore it now gets used where the unsorted one was used previously.
=> Fix sorting in ` cargo dev update_lints` script

clippy_lints/src/manual_clamp.rs, clippy_lints/src/map_unit_fn.rs, clippy_lints/src/methods/manual_ok_or.rs, clippy_lints/src/needless_borrowed_ref.rs, src/docs/needless_borrowed_reference.txt, tests/ui/needless_borrowed_ref.fixed, tests/ui/needless_borrowed_ref.rs, tests/ui/needless_borrowed_ref.stderr
Now lints in positions other than top level, e.g. `Some(&ref a)`. Or patterns are excluded as that can cause issues
Slice patterns of `ref`s are now linted, e.g. `&[ref a, ref b]`. An easy one to walk into as you might expect that to match against a slice you should use `&[]`,  then to get around a `cannot move out of type [T]` error you apply a `ref`
changelog: [`needless_borrowed_reference`]: lint nested patterns and slice patterns
=> lint nested patterns and slice patterns in `needless_borrowed_reference`

clippy_lints/src/bool_to_int_with_if.rs, clippy_lints/src/checked_conversions.rs, clippy_lints/src/from_str_radix_10.rs, clippy_lints/src/implicit_saturating_sub.rs, clippy_lints/src/methods/get_last_with_len.rs, clippy_lints/src/misc.rs, clippy_lints/src/operators/arithmetic_side_effects.rs, clippy_lints/src/operators/numeric_arithmetic.rs, clippy_lints/src/slow_vector_initialization.rs, clippy_lints/src/transmute/transmuting_null.rs, clippy_lints/src/uninit_vec.rs
I noticed that we have the `is_integer_literal` function in our `clippy_utils`, yet almost everywhere people still match int literal expressions manually. So I searched for instances to replace and shorten the code a bit.
---
=> use `is_integer_literal` more

clippy_lints/src/casts/unnecessary_cast.rs, tests/ui/unnecessary_cast.fixed, tests/ui/unnecessary_cast.rs, tests/ui/unnecessary_cast.stderr
fix #9563
The issue was probably introduced by 90fe3bea52dd6ebd0cb02785ba523f182ff761e6
changelog: [`unnecessary_cast`] add parenthesis when negative number uses a method
r? llogiq
=> [`unnecessary_cast`] add parenthesis when negative number uses a method

clippy_lints/src/manual_assert.rs, clippy_utils/src/lib.rs, tests/ui/manual_assert.edition2018.fixed, tests/ui/manual_assert.edition2018.stderr, tests/ui/manual_assert.edition2021.fixed, tests/ui/manual_assert.edition2021.stderr, tests/ui/manual_assert.rs
close https://github.com/rust-lang/rust-clippy/issues/7730
changelog: [`manual_assert`]: Preserve comments in the suggestion
=> [`manual_assert`]: Preserve comments in the suggestion

clippy_lints/src/casts/unnecessary_cast.rs, tests/ui/floating_point_exp.fixed, tests/ui/floating_point_exp.rs, tests/ui/floating_point_exp.stderr, tests/ui/floating_point_log.fixed, tests/ui/floating_point_log.rs, tests/ui/floating_point_logbase.fixed, tests/ui/floating_point_logbase.rs, tests/ui/floating_point_logbase.stderr, tests/ui/floating_point_powf.fixed, tests/ui/floating_point_powf.rs, tests/ui/floating_point_powf.stderr, tests/ui/floating_point_powi.fixed, tests/ui/floating_point_powi.rs, tests/ui/floating_point_powi.stderr, tests/ui/manual_bits.fixed, tests/ui/manual_bits.rs, tests/ui/manual_bits.stderr, tests/ui/ptr_offset_with_cast.fixed, tests/ui/ptr_offset_with_cast.rs, tests/ui/ptr_offset_with_cast.stderr, tests/ui/unnecessary_cast.fixed, tests/ui/unnecessary_cast.rs, tests/ui/unnecessary_cast.stderr
Signed-off-by: TennyZhuang <zty0826@gmail.com>
---
changelog: [`unnecessary_cast`]: fix for trivial non_literal expressions
Fixes #9562
=> let unnecessary_cast work for trivial non_literal expressions

clippy_lints/src/blocks_in_if_conditions.rs, clippy_lints/src/cognitive_complexity.rs, clippy_lints/src/functions/must_use.rs, clippy_lints/src/functions/not_unsafe_ptr_arg_deref.rs, clippy_lints/src/implicit_return.rs, clippy_lints/src/methods/str_splitn.rs, clippy_lints/src/methods/unnecessary_filter_map.rs, clippy_lints/src/needless_late_init.rs, clippy_lints/src/operators/assign_op_pattern.rs, clippy_lints/src/panic_in_result_fn.rs, clippy_lints/src/read_zero_byte_vec.rs, clippy_lints/src/returns.rs, clippy_lints/src/suspicious_trait_impl.rs, clippy_lints/src/unwrap_in_result.rs, clippy_utils/src/lib.rs, clippy_utils/src/macros.rs, clippy_utils/src/ptr.rs, clippy_utils/src/usage.rs, clippy_utils/src/visitors.rs
This is a minor change which uses `ControlFlow` rather than a boolean. This also runs the visitor rather than returning the visitor, which results in a small readability win as well.
=> Replace `expr_visitor` with  `for_each_expr`

clippy_lints/src/upper_case_acronyms.rs, tests/ui/upper_case_acronyms.rs, tests/ui/upper_case_acronyms.stderr
Signed-off-by: TennyZhuang <zty0826@gmail.com>
Fix #9579
changelog: [`upper_case_acronyms`]: check the enum name
=> let `upper_case_acronyms` check the enum name

CHANGELOG.md, clippy_lints/src/implicit_saturating_add.rs, clippy_lints/src/lib.register_all.rs, clippy_lints/src/lib.register_lints.rs, clippy_lints/src/lib.register_style.rs, clippy_lints/src/lib.rs, src/docs.rs, src/docs/implicit_saturating_add.txt, tests/ui/implicit_saturating_add.fixed, tests/ui/implicit_saturating_add.rs, tests/ui/implicit_saturating_add.stderr
This fixes #9393 
---
changelog: add [`manual_saturating_add`] lint
=> new `implicit_saturating_add` lint

clippy_lints/src/operators/arithmetic_side_effects.rs, tests/ui/arithmetic_side_effects.rs, tests/ui/arithmetic_side_effects.stderr
To my utter surprise, `rustc` does does not warn stuff like `let n: u8 = &255 + &1` or `let n: u8 = 255 + &1`.
changelog: [arithmetic-side-effects] Do not ignore literal references
=> [arithmetic-side-effects] Do not ignore literal references

CHANGELOG.md, clippy_lints/src/await_holding_invalid.rs, clippy_lints/src/disallowed_macros.rs, clippy_lints/src/disallowed_methods.rs, clippy_lints/src/disallowed_types.rs, clippy_lints/src/lib.register_all.rs, clippy_lints/src/lib.register_lints.rs, clippy_lints/src/lib.register_style.rs, clippy_lints/src/lib.rs, clippy_lints/src/missing_enforced_import_rename.rs, clippy_lints/src/utils/conf.rs, clippy_lints/src/utils/internal_lints.rs, clippy_utils/src/lib.rs, src/docs.rs, src/docs/disallowed_macros.txt, tests/ui-toml/disallowed_macros/auxiliary/macros.rs, tests/ui-toml/disallowed_macros/clippy.toml, tests/ui-toml/disallowed_macros/disallowed_macros.rs, tests/ui-toml/disallowed_macros/disallowed_macros.stderr, tests/ui-toml/toml_disallowed_methods/clippy.toml, tests/ui-toml/toml_disallowed_methods/conf_disallowed_methods.rs, tests/ui-toml/toml_disallowed_methods/conf_disallowed_methods.stderr, tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
Closes #7790
Fixes #9558
`clippy_utils::def_path_res` already resolved macro definitions which is nice, it just needed a tweak to be able to disambiguate e.g. `std::vec` the module & `std::vec` the macro, and `serde::Serialize` the trait & `serde::Serialize` the derive macro
changelog: new lint: [`disallowed_macros`]
changelog: [`disallowed_methods`], [`disallowed_types`]: Fix false negative when a type/fn/macro share the same path
=> Add `disallowed_macros` lint

clippy_lints/src/format_args.rs, clippy_lints/src/write.rs, clippy_utils/src/macros.rs, tests/ui/expect_fun_call.fixed, tests/ui/expect_fun_call.rs, tests/ui/expect_fun_call.stderr, tests/ui/uninlined_format_args.fixed, tests/ui/uninlined_format_args.rs, tests/ui/uninlined_format_args.stderr
Fixes the following cases:
A missing `, 1` from the `expect_fun_call` suggestion:
```rust
Some(()).expect(&format!("{x} {}", 1));
```
```
warning: use of `expect` followed by a function call
--> t.rs:7:14
|
7 |     Some(()).expect(&format!("{x} {}", 1));
|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `unwrap_or_else(|| panic!("{x} {}"))`
```
The suggestion removing from the comma in the comment rather than the one after the format string:
```rust
println!(
"{}",
// a comment, with a comma in it
x
);
```
```
warning: variables can be used directly in the `format!` string
--> t.rs:9:5
|
9  | /     println!(
10 | |         "{}",
11 | |         // a comment, with a comma in it
12 | |         x
13 | |     );
| |_____^
|
help: change this to
|
10 ~         "{x}",
11 ~         // a …
```
=> FormatArgsExpn: Find comma spans and ignore weird proc macro spans

clippy_lints/src/format_args.rs, tests/ui/uninlined_format_args.fixed, tests/ui/uninlined_format_args.stderr
per suggestion in
https://github.com/rust-lang/rust/pull/102729#discussion_r988990080
workaround for an internal crash when handling multi-line format argument inlining.
(no point for changelog because it is still a new lint being introduced)
=> Add a temporary workaround for  multiline formart arg inlining

clippy_lints/src/matches/match_single_binding.rs, tests/ui/match_single_binding.fixed, tests/ui/match_single_binding.rs, tests/ui/match_single_binding.stderr
Fixes #9575 
changelog: [`match_single_binding`]: Add curlies for scrutinees with side effects for more cases
=> [`match_single_binding`] Add curlies for more cases to fix suggestion causes error

clippy_lints/src/box_default.rs, clippy_utils/src/lib.rs, src/docs/box_default.txt, tests/ui/box_default.fixed, tests/ui/box_default.rs, tests/ui/box_default.stderr
This extends the recently added `box-default` lint to also cover `Box::new(vec![])`, `Box::new(String::from(""))` and `Box::new(Vec::from([]))`. Also the lint now suggests a suitable replacement. I did not find a simple way to check whether the type is fully determined by the outside, so I at least checked for some variations to remove the turbofish in those cases.
---
=> extend `box-default` lint, add suggestion

CHANGELOG.md, clippy_lints/src/casts/as_ptr_cast_mut.rs, clippy_lints/src/casts/mod.rs, clippy_lints/src/lib.register_lints.rs, clippy_lints/src/lib.register_nursery.rs, src/docs.rs, src/docs/as_ptr_cast_mut.txt, tests/ui/as_ptr_cast_mut.rs, tests/ui/as_ptr_cast_mut.stderr
This lint detects calls to a `&self`-taking `as_ptr` method, where the result is then immediately cast to a `*mut T`. Code like this is probably invalid, as that pointer will not have write permissions, and `*mut T` is usually used to write through.
Examples of broken code with this pattern:
https://miri.saethlin.dev/ub?crate=lol_alloc&version=0.1.3
https://miri.saethlin.dev/ub?crate=sophon-wasm&version=0.19.0
https://miri.saethlin.dev/ub?crate=polars-core&version=0.24.2
https://miri.saethlin.dev/ub?crate=ach-cell&version=0.1.17
changelog: Add [`as_ptr_cast_mut`]
=> Add `as_ptr_cast_mut` lint

util/gh-pages/index.html, util/gh-pages/script.js
- related to #7958
This PR adds a default (reset) button to Clippy Lints Lint groups. (change for website)
[The page](https://rust-lang.github.io/rust-clippy/master/index.html) sets only `Deprecated` to false by default.
Certainly it is easy to set only `deprecated` to false, but it may be a bit lazy for beginners.
https://user-images.githubusercontent.com/38400669/194831117-3ade7e0d-c4de-4189-9daf-3be8ea3cdd18.mov
=> Add Default to Clippy Lints Lint groups

clippy_lints/src/format_args.rs, tests/ui/uninlined_format_args.fixed, tests/ui/uninlined_format_args.rs, tests/ui/uninlined_format_args.stderr, tests/ui/uninlined_format_args_2018.fixed, tests/ui/uninlined_format_args_2018.rs, tests/ui/uninlined_format_args_2018.stderr, tests/ui/uninlined_format_args_2021.fixed, tests/ui/uninlined_format_args_2021.rs, tests/ui/uninlined_format_args_2021.stderr
Before 2021 edition, `panic!("...")` was not treated as a format string.
Clippy autofix of `panic!("{}", foo)` into `panic!("{foo}")` is incorrect.
changelog: [`uninlined_format_args`]: Do not inline panic! macros before 2021 edition
=> fix: uninlined_format_args shouldn't inline panic! before 2021ed

clippy_lints/src/types/rc_buffer.rs
`Unspecified`
This changes `rc_buffer` from MachineApplicable to Unspecified
```
changelog: change [`rc_buffer`] to Unspecified. 
```
fixes #6241
---
changelog: change [`rc_buffer`] to Unspecified.
=> update Applicability of `rc_buffer` lint from `MachineApplicable` to `Unspecified`

CHANGELOG.md, clippy_lints/src/casts/cast_nan_to_int.rs, clippy_lints/src/casts/mod.rs, clippy_lints/src/lib.register_all.rs, clippy_lints/src/lib.register_lints.rs, clippy_lints/src/lib.register_suspicious.rs, src/docs.rs, src/docs/cast_nan_to_int.txt, tests/ui/cast_nan_to_int.rs, tests/ui/cast_nan_to_int.stderr
This fixes #371.
r? @Alexendoo
---
changelog: add [`cast-nan-to-int`] lint
=> add `cast-nan-to-int` lint

clippy_lints/src/format_args.rs, tests/ui/format_args.fixed, tests/ui/format_args.rs, tests/ui/format_args.stderr
Fix suggestions like
```
print!("error: something failed at {}", (Location::caller().to_string()));
```
where the parenthesis enclose some portion of the value.
Fixes #9540
changelog: [`to_string_in_format_args`]: fix incorrect fix when value is enclosed in parenthesis
=> Fix to_string_in_format_args in parens

clippy_lints/src/format_args.rs, clippy_lints/src/lib.register_all.rs, clippy_lints/src/lib.register_pedantic.rs, clippy_lints/src/lib.register_style.rs
As [previously discussed](https://github.com/rust-lang/rust-clippy/pull/9233#issuecomment-1256361205), the `uninlined_format_args` should probably be a part of the default style because `println!("{}", foo)` is not as concise or easy to understand as `println!("{foo}")`
changelog: [`uninlined_format_args`]: change to be the default `style`
=> Change uninlined_format_args into a style lint

clippy_lints/src/implicit_saturating_sub.rs, clippy_lints/src/lib.register_all.rs, clippy_lints/src/lib.register_pedantic.rs, clippy_lints/src/lib.register_style.rs, tests/ui/implicit_saturating_sub.fixed, tests/ui/implicit_saturating_sub.rs, tests/ui/implicit_saturating_sub.stderr
This adds more tests to the `implicit_saturating_sub` lint to rule out certain false positives that have appeared in the past.
Now with those false positives out of the equation, we can move the lint to `style`.
---
changelog: promote [`implicit-saturating-sub`] to the `style` category
=> add tests in `implicit_saturating_sub` lint

book/src/development/basics.md
---
Very minor
For the link accessibility change, `here` and related don't provide context for screen readers who are reading a list of links.
(Random supporting google links)
https://www.w3.org/QA/Tips/noClickHere
https://usability.yale.edu/web-accessibility/articles/links
=> Book: Small grammar + link a11y change

clippy_lints/src/ptr.rs, tests/ui/ptr_arg.rs, tests/ui/ptr_arg.stderr
fixes #9542
changelog: [`ptr_arg`](https://rust-lang.github.io/rust-clippy/master/#ptr_arg): Don't lint when used as an incompatible trait object
=> Don't lint `ptr_arg` when used as an incompatible trait object

clippy_lints/src/from_over_into.rs, tests/ui/from_over_into.fixed, tests/ui/from_over_into.rs, tests/ui/from_over_into.stderr, tests/ui/from_over_into_unfixable.rs, tests/ui/from_over_into_unfixable.stderr
Adds a machine applicable suggestion to convert the `Into` impl into a `From` one to `from_over_into`
Also adds a note explaining that `impl From<Local> for Foreign` is fine if the `Into` type is foreign
Closes #7444
Addresses half of #9638
changelog: [`from_over_into`] Add a suggestion and a note about orphan rules
=> Add a suggestion and a note about orphan rules for `from_over_into`

clippy_lints/src/box_default.rs, tests/ui/box_default_no_std.rs
This fixes #9653 by doing the check against the `Box` type correctly even if `Box` isn't there, as in `no_std` code. Thanks to @lukas-code for opening the issue and supplying a reproducer!
---
=> fix `box-default` linting `no_std` non-boxes

clippy_lints/src/default_numeric_fallback.rs, tests/ui/default_numeric_fallback_f64.fixed, tests/ui/default_numeric_fallback_f64.rs, tests/ui/default_numeric_fallback_f64.stderr, tests/ui/default_numeric_fallback_i32.fixed, tests/ui/default_numeric_fallback_i32.rs, tests/ui/default_numeric_fallback_i32.stderr
fix https://github.com/rust-lang/rust-clippy/issues/9632
changelog:[`default_numeric_fallback`] do not lint on constants
=> [`default_numeric_fallback`] do not lint on constants

CHANGELOG.md, clippy_lints/src/lib.register_lints.rs, clippy_lints/src/lib.register_restriction.rs, clippy_lints/src/lib.rs, clippy_lints/src/partial_pub_fields.rs, src/docs.rs, src/docs/partial_pub_fields.txt, tests/ui/partial_pub_fields.rs, tests/ui/partial_pub_fields.stderr
Signed-off-by: TennyZhuang <zty0826@gmail.com>
changelog: `partial_pub_fields`: new lint to disallow partial fields of a struct be pub
Resolve #9604
=> Add new lint `partial_pub_fields`

clippy_lints/src/misc_early/zero_prefixed_literal.rs, tests/ui/literals.rs, tests/ui/literals.stderr
fix https://github.com/rust-lang/rust-clippy/issues/9651
changelog: [`zero_prefixed_literal`] Do not advise to use octal form if not possible
=> [`zero_prefixed_literal`] Do not advise to use octal form if not possible

clippy_lints/src/casts/unnecessary_cast.rs, clippy_utils/src/numeric_literal.rs, tests/ui/unnecessary_cast.fixed, tests/ui/unnecessary_cast.rs
fix https://github.com/rust-lang/rust-clippy/issues/9603
changelog: [`unnecessary_cast`] Do not lint negative hexadecimal literals when cast as floats
=> [`unnecessary_cast`] Do not lint negative hexadecimal literals when cast as floats

CHANGELOG.md, clippy_lints/src/format_args.rs, clippy_lints/src/lib.register_all.rs, clippy_lints/src/lib.register_complexity.rs, clippy_lints/src/lib.register_lints.rs, clippy_utils/src/macros.rs, src/docs.rs, src/docs/unused_format_specs.txt, tests/ui/unused_format_specs.fixed, tests/ui/unused_format_specs.rs, tests/ui/unused_format_specs.stderr, tests/ui/unused_format_specs_unfixable.rs, tests/ui/unused_format_specs_unfixable.stderr
Currently catches two cases:
An empty precision specifier:
```rust
// the same as {}
println!("{:.}", x);
```
And using formatting specs on `format_args!()`:
```rust
// prints `x.`, not `x    .`
println("{:5}.", format_args!("x"));
```
changelog: new lint: [`unused_format_specs`]
=> Add `unused_format_specs` lint

clippy_lints/src/types/redundant_allocation.rs
This changes `redundant_allocation` lint from MachineApplicable to MaybeIncorrect
```
changelog: [`redundant_allocation]: Change Applicability from MachineApplicable to MaybeIncorrect
```
fixes #6243
---
changelog: [`redundant_allocation`]: Change Applicability from MachineApplicable to MaybeIncorrect
=> Update Applicability of `redundant_allocation` lint from `MachineApplicable` to `MaybeIncorrect`

CHANGELOG.md, clippy_lints/src/lib.register_lints.rs, clippy_lints/src/lib.register_restriction.rs, clippy_lints/src/lib.rs, clippy_lints/src/missing_trait_methods.rs, src/docs.rs, src/docs/missing_trait_methods.txt, tests/ui/missing_trait_methods.rs, tests/ui/missing_trait_methods.stderr
Closes #9661
changelog: new lint: [`missing_trait_methods`]
=> Add `missing_trait_methods` lint

clippy_lints/src/matches/collapsible_match.rs, tests/ui/collapsible_match.rs, tests/ui/collapsible_match.stderr
changelog: [`collapsible_match`] specify field name when destructuring structs
fix https://github.com/rust-lang/rust-clippy/issues/9647
I wasn't the sure about the best way to convey the message in the lint message since it does not use suggestion. Because I liked the former output highlighting both spans, I've left it as before, only modifying the span label.
=> [`collapsible_match`] specify field name when destructuring structs

lintcheck/src/config.rs, lintcheck/src/driver.rs, lintcheck/src/main.rs, lintcheck/src/recursive.rs, tests/dogfood.rs
Currently, `lintcheck` is not checked by the `dogfood` test. I assume that is not intentional. If it is intentional, then this PR can be ignored.
changelog: Add `lintcheck` to packages linted by `dogfood` test
=> Add `lintcheck` to packages linted by `dogfood` test

clippy_lints/src/box_default.rs, tests/ui/box_default.fixed, tests/ui/box_default.rs, tests/ui/box_default.stderr
This avoids removing the turbofish when the `Box` type is a `dyn` or `impl _`.
This fixes #9621.
---
=> fix `box-default` ignoring trait objects' types

clippy_lints/src/methods/expect_used.rs, clippy_lints/src/methods/unwrap_used.rs, clippy_lints/src/utils/conf.rs, tests/ui-toml/expect_used/expect_used.rs, tests/ui-toml/unwrap_used/unwrap_used.rs, tests/ui-toml/unwrap_used/unwrap_used.stderr
changelog: [`unwrap_used`], [`expect_used`] do not lint in `test` cfg
fix https://github.com/rust-lang/rust-clippy/issues/9612
I've updated the doc and used `cfg` acronym, not sure if `conditional compiler flag` would have been better
=> [`unwrap_used`], [`expect_used`] do not lint in `test` cfg

clippy_lints/src/methods/or_fun_call.rs, tests/ui/manual_ok_or.fixed, tests/ui/manual_ok_or.rs, tests/ui/manual_ok_or.stderr, tests/ui/or_fun_call.fixed, tests/ui/or_fun_call.rs, tests/ui/or_fun_call.stderr
fixes https://github.com/rust-lang/rust-clippy/issues/8993
The methods defined in `KNOW_TYPES`, except for `map_or`, accepts only one argument, so the matching `if let [arg] = args` works only for these methods.
This PR adds `rest_arg` argument to `check_general_case` method and handling of cases with two arguments to support `map_or`.
changelog: `or_fun_call` support `map_or`
* add `rest_arg` to pass second argument from `map_or(U, F)`
* extract some procedures into closure
=> fix: support `map_or` for `or_fun_call` lint

clippy_lints/src/attrs.rs
Previously the `clippy::allow_attributes_without_reason` lint would apply to external crate macros. Many macros in the Rust ecosystem include these `allow` attributes without adding a reason, making this lint pretty much unusable in any sizable Rust project.
This commit fixes that by adding a check to the lint if the attribute is from an external crate macro and returning early.
```
changelog: [`allow_attributes_without_reason`]: allow_attributes_without_reason no longer applies to external crate macros
```
=> Fix allow_attributes_without_reason applying to external crate macros

clippy_lints/src/equatable_if_let.rs, tests/ui/equatable_if_let.fixed, tests/ui/equatable_if_let.rs, tests/ui/equatable_if_let.stderr
fixes #9221 
This PR makes sure that enums or structs not implementing `PartialEq` trait but still using the `if let` patterns can be linted to be rewritten with `matches!`.
- \[ ] Followed [lint naming conventions][lint_naming]
- \[ ] Executed `cargo dev update_lints`
- \[ ] Added lint documentation
---
changelog: Improve [`equatable_if_let`] with additional `matches!` suggestions.
=> Improvement for  `equatable_if_let`

CHANGELOG.md, clippy_lints/src/from_raw_with_void_ptr.rs, clippy_lints/src/lib.register_all.rs, clippy_lints/src/lib.register_lints.rs, clippy_lints/src/lib.register_suspicious.rs, clippy_lints/src/lib.rs, src/docs.rs, src/docs/from_raw_with_void_ptr.txt, tests/ui/from_raw_with_void_ptr.rs, tests/ui/from_raw_with_void_ptr.stderr
This PR `fixes #9679` 
---
changelog:  [`from_raw_with_void_ptr`]: added new lint
=> add `from_raw_with_void_ptr` lint

clippy_lints/src/use_self.rs, tests/ui/use_self_trait.fixed, tests/ui/use_self_trait.rs
changelog: [`use_self`] fix FP when trait impl defined in macro
=> [`use_self`] fix FP when trait impl defined in macro

clippy_lints/src/from_raw_with_void_ptr.rs, tests/ui/from_raw_with_void_ptr.rs, tests/ui/from_raw_with_void_ptr.stderr
This PR updates the `from_raw_with_void_ptr` lint, which covered
`Box::from_raw`, to also cover the `from_raw` static method of the
`Rc`, `Arc`, `alloc::rc::Weak` and `alloc::sync::Weak` types.
It also improves the description and error messages of this lint.
---
changelog: [`from_raw_with_void_ptr`]: Now works with the `Rc`, `Arc`, `alloc::rc::Weak` and `alloc::sync::Weak` types.
=> Update `from_raw_with_void_ptr` to support types other than `Box`

clippy_lints/src/lib.rs, clippy_lints/src/mut_key.rs, clippy_lints/src/utils/conf.rs, clippy_utils/src/lib.rs, tests/ui-toml/mut_key/clippy.toml, tests/ui-toml/mut_key/mut_key.rs, tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
We had some false positives where people would create their own types that had interior mutability unrelated to hash/eq. This addition lets you configure this as e.g. `arc-like-types=["bytes::Bytes"]`
This fixes #5325 by allowing users to specify the types whose innards like `Arc` should be ignored (the generic types are still checked) for the sake of detecting inner mutability.
r? @Alexendoo
---
changelog: Allow configuring types to ignore internal mutability in `mutable-key`
=> make ignored internally mutable types for `mutable-key` configurable

clippy_dev/Cargo.toml, clippy_dev/src/lint.rs, clippy_lints/src/lib.rs, clippy_lints/src/utils/conf.rs, lintcheck/src/main.rs, src/driver.rs
Causes cargo to re-run clippy when those paths are modified
Also tracks the path to `clippy-driver` in debug mode to remove the workarounds in `cargo dev lint` and `lintcheck` (cc @matthiaskrgr)
changelog: Automatically re-run Clippy if `Cargo.toml` or `clippy.toml` are modified
Fixes #2130
Fixes #8512
r? @flip1995
=> Track `clippy.toml` and `Cargo.toml` in `file_depinfo`

clippy_dev/src/update_lints.rs
Follow up to #9709 / #9541
There's a good number of PRs with some leftover `src/docs` files for example, and as a reviewer it's something we're used to ignoring so it can easily slip through
r? @flip1995 
=> Remove `lib.register_*` and `src/docs*` in `cargo dev update_lints`

README.md
=> Remove note mentioning configuration changes need cargo clean

clippy_lints/src/dereference.rs, tests/ui/needless_borrow.fixed, tests/ui/needless_borrow.rs
The PR fixes the false positive exposed by @BusyJay's example in: https://github.com/rust-lang/rust-clippy/issues/9111#issuecomment-1277114280
The current approach is described in https://github.com/rust-lang/rust-clippy/pull/9674#issuecomment-1289294201 and https://github.com/rust-lang/rust-clippy/pull/9674#issuecomment-1292225232.
The original approach appears below.
---
The proposed fix is to flag only "simple" trait implementations involving references, a concept
that I introduce next.
Intuitively, a trait implementation is "simple" if all it does is dereference and apply the trait
implementation of a type named by a type parameter. `AsRef` provides a good example of a simple
implementation: https://doc.rust-lang.org/std/convert/trait.AsRef.html#impl-AsRef%3CU%3E-for-%26T
We can make …
=> Fix `needless_borrow` false positive

clippy_lints/src/format_args.rs
As discussed in zulip, we are moving this lint to pedantic to be backported
changelog: [`UNINLINED_FORMAT_ARGS`]: move to pedantic
=> move `UNINLINED_FORMAT_ARGS` to pedantic

clippy_lints/src/question_mark.rs, tests/ui/question_mark.fixed, tests/ui/question_mark.rs, tests/ui/question_mark.stderr
cc #9518
AFAICT the only time this would be a valid suggestion is the rather esoteric
```rust
let _ = if let Err(e) = x {
return Err(e);
} else {
// no side effects
x.unwrap()
}
```
which doesn't seem worth checking to me. Please correct me if I'm missing something.
changelog: [`question_mark`] don't lint on `if let Err` with `else`
=> `question_mark` don't lint on `if let Err` with `else`

clippy_lints/src/use_self.rs, tests/ui-cargo/cargo_rust_version/fail_both_diff/src/main.stderr, tests/ui-cargo/cargo_rust_version/fail_both_same/src/main.stderr, tests/ui-cargo/cargo_rust_version/fail_cargo/src/main.stderr, tests/ui-cargo/cargo_rust_version/fail_clippy/src/main.stderr, tests/ui-cargo/cargo_rust_version/fail_file_attr/src/main.stderr, tests/ui/use_self_trait.fixed, tests/ui/use_self_trait.rs, tests/ui/use_self_trait.stderr
Previously the following wrong suggestion was given
```rust
impl Error for std::fmt::Error {
fn custom<T: std::fmt::Display>(_msg: T) -> Self {
-        std::fmt::Error // Should lint
+        Self::Error // Should lint
}
}
```
Also remove known problem line related to #4140 since it's been closed, and refactor the lint
changelog: [`use_self`] fix suggestion when full path to struct was given
=> [`use_self`] fix suggestion when full path to struct was given

clippy_lints/src/methods/mod.rs, clippy_utils/src/ty.rs, tests/ui/new_ret_no_self.rs, tests/ui/new_ret_no_self.stderr
Fix #7344: ensure new_ret_no_self is not fired if `impl Trait<Self>` is returned.
changelog: [`new_ret_no_self`]: No longer lints when `impl Trait<Self>` is returned
=> Ensure new_ret_no_self is not fired if impl Trait<Self> is returned.

clippy_lints/src/methods/string_extend_chars.rs, tests/ui/string_extend.fixed, tests/ui/string_extend.rs, tests/ui/string_extend.stderr
This adds the missing `&` to the suggestion if the target is a `str` slice (e.g. extending with `"foo"[..].chars()`).
This closes #9735.
---
changelog: fix the `string-extend-chars` suggestion for `str` slices
=> fix the `string-extend-chars` suggestion on slice

clippy_lints/src/dereference.rs, tests/ui/needless_borrow.fixed, tests/ui/needless_borrow.rs
Fixes #9710
changelog: fix `needless_borrow` false positive #9710
=> Fix `needless_borrow` false positive #9710

clippy_lints/src/undocumented_unsafe_blocks.rs, tests/ui/undocumented_unsafe_blocks.rs, tests/ui/undocumented_unsafe_blocks.stderr
This fixes #9142 by iterating over the parent nodes as long as within a block, expression, statement, local, const or static.
---
=> fix `undocumented-unsafe-blocks` false positive

clippy_lints/src/bool_to_int_with_if.rs, tests/ui/bool_to_int_with_if.fixed, tests/ui/bool_to_int_with_if.rs, tests/ui/bool_to_int_with_if.stderr
changelog: [`bool_to_int_with_if`] do not lint in const context
fix https://github.com/rust-lang/rust-clippy/issues/9737
=> [`bool_to_int_with_if`] do not lint in const context

clippy_lints/src/bool_to_int_with_if.rs, tests/ui/bool_to_int_with_if.fixed, tests/ui/bool_to_int_with_if.rs, tests/ui/bool_to_int_with_if.stderr
Fixes #9706
changelog: FP: [`bool_to_int_with_if`]: Now ignores `if let` statements
=> Fix `bool_to_int_with_if` false positive with `if let`

clippy_lints/src/attrs.rs, tests/ui/blanket_clippy_restriction_lints.rs, tests/ui/blanket_clippy_restriction_lints.stderr
Currently it catches `#![warn(clippy::restriction)]`, it'll now catch `-W clippy::restriction` from the CLI. Also tweaks the message slightly
changelog: [`blanket_clippy_restriction_lints`]: Warn when `clippy::restriction` is enabled via the command line
=> Warn when `clippy::restriction` is enabled via the command line

clippy_lints/src/option_if_let_else.rs, tests/ui/option_if_let_else.fixed, tests/ui/option_if_let_else.rs
fix https://github.com/rust-lang/rust-clippy/issues/9742
changelog: [`option_if_let_else`] do not lint if any arm has guard
=> [`option_if_let_else`] do not lint if any arm has guard

README.md
Clippy test badge always shows "no status" message. Fix it for showing real status
=> Fix Clippy Test badge

clippy_lints/src/doc.rs, tests/ui/doc_errors.stderr, tests/ui/doc_unsafe.stderr, tests/ui/missing_panics_doc.stderr
Shrink the spans of `clippy::missing_*_doc` to match `missing_docs` and don't cover the entire item anymore. This helps readability in IDEs by not coloring the entire screen yellow, similar to https://github.com/rust-lang/rust/pull/103749 and https://github.com/rust-lang/rust/pull/90761.
before:
after:
changelog: [`missing_safety_doc`], [`missing_error_doc`], [`missing_panics_doc`]: These lints no longer span the entire item.
=> Shrink `missing_{safety,errors,panics}_doc` spans

clippy_lints/src/types/redundant_allocation.rs, tests/ui/crashes/ice-9746.rs
changelog: Fix ICE in `redundant_allocation`
Closes #9746, the original issue was fixed already, this gets the one in https://github.com/rust-lang/rust-clippy/issues/9746#issuecomment-1297132880
=> Fix ICE in `redundant_allocation`

CHANGELOG.md, clippy_lints/src/casts/mod.rs, clippy_lints/src/functions/mod.rs, clippy_lints/src/manual_instant_elapsed.rs, clippy_lints/src/methods/mod.rs, clippy_lints/src/partialeq_to_none.rs, clippy_lints/src/unused_peekable.rs
Roses are red,
another 6 weeks,
another changelog, yahoo!
This did not rhyme,
luckily, not a crime.
I want to say something smart,
but I am out of time.
---
Note for the reviewer. This PR is written, as if Rust was already released on 2022-11-03. Please review the changes and approve if you agree, but only merge it after the release. :)
---
=> Changelog for Rust 1.65

CONTRIBUTING.md
@xFrednet I cribbed some text of yours from https://github.com/rust-lang/rust-clippy/pull/9743#issuecomment-1295892442 and did some light editing in the hope that others might find it.
r? @xFrednet
changelog: Update CONTRIBUTING.md with changelog guidance
=> Update CONTRIBUTING.md with changelog guidance

clippy_lints/src/methods/mod.rs
changelog: [`suspicious_to_owned`]: Use explicit type annotation on lint description instead of `matches!`
=> Update lint `suspicious_to_owned`

clippy_lints/src/lib.rs, clippy_lints/src/utils/conf.rs, clippy_lints/src/write.rs, tests/ui-toml/print_macro/clippy.toml, tests/ui-toml/print_macro/print_macro.rs, tests/ui-toml/print_macro/print_macro.stderr, tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
Add a config, allow-print-in-tests, that can be set in clippy.toml which allows the usage of `[e]print[ln]!` macros in tests.
Closes #9795
---
changelog: Enhancement: [print_stdout], [print_stderr]: Can now be enabled in test with the `allow-print-in-tests` config value
=> Add allow-print-in-tests config

clippy_lints/src/loops/mod.rs, tests/ui/needless_collect_indirect.rs, tests/ui/needless_collect_indirect.stderr
changelog: [`needless_collect`]: Move `needless_collect` to nursery (Now allow-by-default)
After chatting with a few folks, it seems like `needless_collect` is giving false positives pretty regularly (https://github.com/rust-lang/rust-clippy/issues?q=is%3Aissue+is%3Aopen+needless_collect). We're big supporters of clippy in Nushell, and it's one of the passes we require for CI, but we've had to disable this particular lint. Perhaps it should be moved to the nursery until it's improved?
(apologies if this isn't the right approach to disabling a lint by default. I tried to follow the idea I saw other PRs doing in the past)
=> Move needless_collect to nursery

clippy_lints/src/dereference.rs, tests/ui/needless_borrow.fixed, tests/ui/needless_borrow.rs, tests/ui/needless_borrow.stderr
This PR fixes #9739 in the manner I suggested in https://github.com/rust-lang/rust-clippy/issues/9739#issuecomment-1296802376.
This PR also fixes the compilation failures in #9782 (but doesn't address @e00E's other objections).
Fixes #9739
r? @Jarcho
changelog: Fix two `needless_borrow` false positives, one involving borrows in `if`-`else`s, the other involving qualified function calls
=> Address issues 9739 and 9782

clippy_lints/src/methods/mod.rs
To fix this warning:
```
warning: the borrowed expression implements the required traits
--> src/fixes/quote_character.rs:16:43
|
16 |         let hello = "hesuo worpd".replace(&['s', 'u', 'p'], "l");
|                                           ^^^^^^^^^^^^^^^^ help: change this to: `['s', 'u', 'p']`
|
= note: `#[warn(clippy::needless_borrow)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
```
=> Update lint example for `collapsible_str_replace`

clippy_lints/src/dereference.rs, tests/ui/explicit_auto_deref.fixed, tests/ui/explicit_auto_deref.rs
fixes #9763
fixes #9811
changelog: `explicit_auto_deref`: Don't lint when the target type is a projection with generic arguments
=> Fix `explicit_auto_deref` fp

clippy_lints/src/cognitive_complexity.rs, tests/ui/cognitive_complexity.rs, tests/ui/cognitive_complexity.stderr
fix https://github.com/rust-lang/rust-clippy/issues/9300
changelog: [`cognitive_complexity`] support async fn
=> fix: cognitive_complexity for async fn

clippy_lints/src/bool_to_int_with_if.rs
In all the cases I've observed, it did not make the code clearer. Using bools as integer is frowned upon in some languages, in others it's simply not possible.
You can find comments on the original pull request #8131 that agree with this point of view.
changelog: [`bool_to_int_with_if`]: Change the categorization to pedantic
=> Make `bool_to_int_with_if` a pedantic lint

clippy_lints/src/functions/result.rs, clippy_lints/src/large_enum_variant.rs, clippy_utils/src/ty.rs, tests/ui/result_large_err.rs, tests/ui/result_large_err.stderr
fixes #9538 
changelog: Sugg: [`result_large_err`]: Now show largest enum variants in error message
=> `result_large_err` show largest variants in err msg

clippy_lints/src/manual_is_ascii_check.rs
refactor `manual_is_ascii_check` lint.
* remove unnecessary mutability
* fix typo
r? @xFrednet
=> refac: remove unnecessary mutability

clippy_utils/src/lib.rs, tests/ui/cognitive_complexity.rs, tests/ui/cognitive_complexity.stderr
This is a follow-up PR of https://github.com/rust-lang/rust-clippy/pull/9828 to support also async methods.
changelog: [`cognitive_complexity`] support async method
r? @Alexendoo
=> Fix is_async_fn to check FnKind::Method

clippy_lints/src/mut_mut.rs, tests/ui/mut_mut.rs
fix https://github.com/rust-lang/rust-clippy/issues/9035
changelog: [`mut_mut`] avoid suggesting to reborrow unsized mutable reference
=> Avoid linting unsized mutable reference

clippy_lints/src/excessive_bools.rs, clippy_lints/src/lib.rs, clippy_lints/src/methods/mod.rs, clippy_lints/src/trailing_empty_array.rs, clippy_utils/src/hir_utils.rs, clippy_utils/src/lib.rs, tests/ui/fn_params_excessive_bools.rs, tests/ui/fn_params_excessive_bools.stderr
changelog: FP: [`fn_params_excessive_bools`]: `#[allow]` now works on methods
fix https://github.com/rust-lang/rust-clippy/issues/9687
Tested without committing but `#[allow]`ing now works. Also rewrote the lint to be a late lint while at it :)
r? @xFrednet
=>  [`fn_params_excessive_bools`] Make it possible to allow the lint at the method level

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/doc.rs, tests/ui/auxiliary/doc_unsafe_macros.rs, tests/ui/doc_unnecessary_unsafe.rs, tests/ui/doc_unnecessary_unsafe.stderr
changelog: [`unnecessary_safety_doc`]: Add `unnecessary_safety_doc` lint
fixes https://github.com/rust-lang/rust-clippy/issues/6880
This lint does not trigger for private functions, just like `missing_safety_docs`. Reason for that was implementation simplicity and because I figured asking first would make more sense, so if it should trigger for private functions as well let me know and I'll fix that up as well.
=> Add `unnecessary_safety_doc` lint

clippy_lints/src/methods/mod.rs, tests/ui/unwrap_or.rs
Also move it to nursery so that the false-positives can be dealt with.
CC #8574
changelog: [`or_fun_call`]: Mention false-positives, move to nursery.
=> Make it clear that `or_fun_call` can be a false-positive

clippy_lints/src/loops/never_loop.rs, tests/ui/never_loop.rs
fixes #9831
changelog: [`never_loop`]: fixed false positive on unconditional break in internal labeled block
=> fix never_loop false positive

clippy_lints/src/unused_unit.rs, tests/ui/unused_unit.fixed, tests/ui/unused_unit.rs, tests/ui/unused_unit.stderr
fix https://github.com/rust-lang/rust-clippy/issues/9748
changelog: Fix [`unused_unit`] Allow return types for closures with lifetime binder
=> Allow return types for closures with lifetime binder

clippy_lints/src/loops/never_loop.rs, tests/ui/never_loop.rs, tests/ui/never_loop.stderr
ref: https://github.com/rust-lang/rust-clippy/pull/9837#issuecomment-1312788194
The previous fix (#9837) was too simple and ignored all break commands inside a labelled block, regardless of whether their destination was a labelled block or a loop. This fix tracks all the labelled blocks in scope to ensure that only breaks targeting loops are considered.
changelog: [`never_loop`]: prevent false negatives from `breaks` nested in labelled blocks
=> `never_loop`: don't emit AlwaysBreaks if it targets a block

clippy_lints/src/matches/infallible_destructuring_match.rs, tests/ui/infallible_destructuring_match.fixed, tests/ui/infallible_destructuring_match.rs, tests/ui/infallible_destructuring_match.stderr
Fixes https://github.com/rust-lang/rust-clippy/issues/7499
changelog: [`infallible_destructuring_match`]: Preserve `ref` on suggestion
=> Preserve `ref` on `infallible_destructuring_match` suggestion

clippy_lints/src/methods/expect_used.rs, clippy_lints/src/methods/unwrap_used.rs, tests/ui-toml/expect_used/expect_used.stderr, tests/ui-toml/unwrap_used/unwrap_used.stderr, tests/ui/expect.stderr, tests/ui/get_unwrap.stderr, tests/ui/unwrap.stderr, tests/ui/unwrap_expect_used.stderr
"\`an Option\`" -> "an \`Option\`" and "\`a Result\`" -> "a \`Result\`".
changelog: fix typo in `expect_used` and `unwrap_used` warning messages
=> Fix typo in `expect_used` and `unwrap_used` warning messages

clippy_lints/src/enum_variants.rs, clippy_lints/src/int_plus_one.rs, clippy_lints/src/len_zero.rs, clippy_lints/src/needless_borrowed_ref.rs, clippy_lints/src/unsafe_removed_from_name.rs, clippy_utils/src/consts.rs, clippy_utils/src/hir_utils.rs, tests/ui/match_expr_like_matches_macro.fixed, tests/ui/match_expr_like_matches_macro.rs, tests/ui/match_expr_like_matches_macro.stderr, tests/ui/needless_borrowed_ref.fixed, tests/ui/needless_borrowed_ref.rs, tests/ui/needless_borrowed_ref.stderr
changelog: [`needless_borrowed_reference`]: Lint struct and tuple patterns, and patterns containing `_`
Now lints patterns like
```rust
&(ref a, ref b)
&Tuple(ref a, ref b)
&Struct { ref a, ref b }
&(ref a, _)
```
=> Extend `needless_borrowed_reference` to structs and tuples, ignore _

clippy_lints/src/swap.rs, tests/ui/swap.fixed, tests/ui/swap.rs
Fix https://github.com/rust-lang/rust-clippy/issues/9864
changelog: Fix [`manual_swap`]: No longer lints in constant code
=> Allow manual swap in const fn

clippy_lints/src/await_holding_invalid.rs, clippy_lints/src/disallowed_macros.rs, clippy_lints/src/disallowed_methods.rs, clippy_lints/src/disallowed_types.rs, clippy_lints/src/missing_enforced_import_rename.rs, clippy_lints/src/mut_key.rs, clippy_lints/src/utils/conf.rs, clippy_lints/src/utils/internal_lints/interning_defined_symbol.rs, clippy_lints/src/utils/internal_lints/invalid_paths.rs, clippy_lints/src/utils/internal_lints/unnecessary_def_path.rs, clippy_utils/src/lib.rs, tests/ui-toml/await_holding_invalid_type/await_holding_invalid_type.stderr, tests/ui-toml/toml_disallowed_methods/clippy.toml, tests/ui-toml/toml_disallowed_methods/conf_disallowed_methods.rs, tests/ui-toml/toml_disallowed_methods/conf_disallowed_methods.stderr
Changes `def_path_res` to return all the resolutions matching the path rather than the first one (with a namespace hint that covered some cases).  This would fix any issues that come up with multiple versions of the same crate being present as they all have the same crate name
It also adds resolution of `impl _ {}` items for local items, and removes struct field resolution as it didn't seem to be used anywhere
I tested it on a local crate and it worked for the multiple crate issue, but I couldn't come up with a test that worked well with `// aux-build`, maybe `// aux-crate` after https://github.com/rust-lang/rust/pull/103266 could work but I'm not sure on that either
changelog: [`disallowed_methods`], [`disallowed_types`], [`disallowed_macros`]: fix path resolution with multiple versions …
=> Return multiple resolutions from `def_path_res`

clippy_lints/src/attrs.rs, clippy_lints/src/lib.rs, clippy_lints/src/single_component_path_imports.rs, tests/ui/single_component_path_imports.stderr, tests/ui/single_component_path_imports_nested_first.stderr, tests/ui/useless_attribute.fixed, tests/ui/useless_attribute.rs, tests/ui/useless_attribute.stderr
Fixes #7511
Fixes #8768
Fixes #9401
`single_component_path_imports` needed some changes to the lint itself, it now buffers the found single component paths to emit in the equivalent `check_item`
changelog: Fix `#[allow(clippy::module_name_repetitions)]` and `#[allow(clippy::single_component_path_imports)]`
=> Fix `#[allow]` for `module_name_repetitions` & `single_component_path_imports`

clippy_lints/src/unused_rounding.rs, tests/ui/unused_rounding.fixed, tests/ui/unused_rounding.rs, tests/ui/unused_rounding.stderr
While I did some investigation of https://github.com/rust-lang/rust-clippy/issues/9866 (I couldn't reproduce it though) I found that `unused_rounding` formats as follows:
```rust
3.0_f64.round() // => 3.0f64
```
This PR makes them preserve as the original notation.
```rust
3.0_f64.round() // => 3.0_f64
```
changelog: Suggestion Enhancement: [`unused_rounding`]: The suggestion now preserves the original float literal notation
=> Keep original literal notation in suggestion

clippy_lints/src/operators/arithmetic_side_effects.rs, tests/ui-toml/arithmetic_side_effects_allowed/arithmetic_side_effects_allowed.rs, tests/ui/arithmetic_side_effects.rs, tests/ui/arithmetic_side_effects.stderr
Triggers the negation of maximum unsigned integers using associated constants. Rustc already handles `-128i8` but doesn't handle `-i8::MAX`.
At the same time, allows stuff like `-1234`.
changelog: FP: [arithmetic-side-effects] Detect overflowing associated constants of integers
=> [arithmetic-side-effects] Detect overflowing associated constants of integers

clippy_utils/src/lib.rs, clippy_utils/src/source.rs
`line_span` is a non-public function used only in source.rs. It seems like it ought to go in source.rs.
=> Move `line_span` to source.rs

clippy_lints/src/eta_reduction.rs, tests/ui/eta.fixed, tests/ui/eta.rs, tests/ui/eta.stderr
Fixes #7746. The issue turns out to be more general than raw pointers. The `redundant_closure_for_method_calls` lint produces incorrect suggestions when the method is associated with a type that must be enclosed in angle brackets or must be written with generic arguments substituted. For example:
```rust
fn main() {
// Clippy's suggestion: [T; N]::as_slice
// Correct suggestion:  <[u8; 3]>::as_slice
let array_opt: Option<&[u8; 3]> = Some(&[4, 8, 7]);
array_opt.map(|a| a.as_slice());
// Clippy's suggestion: [T]::len
// Correct suggestion:  <[u8]>::len
let slice_opt: Option<&[u8]> = Some(b"slice");
slice_opt.map(|s| s.len());
// Clippy's suggestion: *const T::is_null
// Correct suggestion:  <*const usize>::is_null
let ptr_opt: Option<*const usize> = Some(&487);
ptr_opt.map(|p| p.is_null()); …
```
=> Fix `redundant_closure_for_method_calls` suggestion

clippy_lints/src/lifetimes.rs
This is a tiny followup to to #9743, now that https://github.com/rust-lang/rust/pull/103692 has landed.
r? @Alexendoo
=> Use `walk_generic_arg`

rfcs/0001-syntax-tree-patterns.md
This PR adds an RFC for implementing lints using *syntax tree patterns*.
[Rendered RFC](https://github.com/fkohlgrueber/rust-clippy-pattern/blob/syntax-tree-patterns/rfcs/0001-syntax-tree-patterns.md) (outdated)
**Update: A more thorough description of the current concept is given in my [thesis](https://fkohlgrueber.github.io/thesis.pdf).**
cc @oli-obk
=> RFC: syntax tree patterns

rfcs/0001-syntax-tree-patterns.md
https://github.com/rust-lang/rust-clippy/actions/runs/3542472739/jobs/5948006255#step:6:37
Removes the unused definitions, for the line length I disabled the lint for now as I gather it's going to be moved into the book in the future
=> Fix remark for `rfcs/0001-syntax-tree-patterns.md`

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/undocumented_unsafe_blocks.rs, clippy_utils/src/visitors.rs, tests/ui/undocumented_unsafe_blocks.rs, tests/ui/undocumented_unsafe_blocks.stderr, tests/ui/unnecessary_safety_comment.rs, tests/ui/unnecessary_safety_comment.stderr
changelog: [`unnecessary_safety_comment`]: Add unnecessary safety comment lint
Addresses https://github.com/rust-lang/rust-clippy/issues/7954
This does not necessarily catch all occurences, as doing so would require checking all expressions in the entire source which seems rather expensive. Instead what the lint does is it checks items, statements and the tail expression of blocks for safety comments, then checks if those comments are necessary or not, then linting for the unnecessary ones.
I kept the tests in one file to check that the lints do not clash with each other.
=> Lint unnecessary safety comments 

clippy_lints/src/format_args.rs, clippy_utils/src/ty.rs, lintcheck/src/main.rs, tests/ui/uninlined_format_args.fixed, tests/ui/uninlined_format_args.stderr
fix https://github.com/rust-lang/rust-clippy/issues/9719
There was an issue with the code suggestion which can be sometimes completely broken (fortunately when applied it's valid), so we do not show it.
changelog: [`uninlined_format_args`] re-enable for multiline format expression, but do not show the literal code suggestion in those cases
=> Re-enable `uninlined_format_args` on multiline `format!`

clippy_lints/src/exit.rs
Super simple change, hopefully fast and fun to review. Have a great start to the weekend!
=> Improve `EXIT` lint docs

README.md, book/src/configuration.md
=> Link to a list of configurable lints in documentation

clippy_lints/src/returns.rs, tests/ui/needless_return.fixed, tests/ui/needless_return.rs, tests/ui/needless_return.stderr
fix https://github.com/rust-lang/rust-clippy/issues/9416
changelog: [`needless_return`] improve result format
r? @llogiq
=> Remove blank lines when needless_return returns no value

clippy_lints/src/casts/unnecessary_cast.rs, tests/ui/unnecessary_cast.fixed, tests/ui/unnecessary_cast.rs, tests/ui/unnecessary_cast.stderr
fixes #9960
Time to start making a dent in this onslaught.
changelog: `unnecessary_cast`: Don't lint when the identifiers context differs from its binding's context for locals
=> Don't lint `unnecessary_cast` in mixed macro context

clippy_lints/src/no_effect.rs, tests/ui/unnecessary_operation.fixed, tests/ui/unnecessary_operation.rs
fixes #9954 
changelog: `unnecessary_operation`: Don't lint in mixed macro contexts.
=> Don't lint `unnecessary_operation` in mixed macro contexts

clippy_lints/src/index_refutable_slice.rs
During the creation, I out this lint into the nursery group to let it run in the wild before moving it to a commonly used group. This move never happened until now, though. It should be safe, as Clippy and I have been using it for months and there are no open issues for is :)
---
changelog: Move `index_refutable_slice` to `pedantic` (Now warn-by-default)
[#9975](https://github.com/rust-lang/rust-clippy/pull/9975)
=> Move `index_refutable_slice` to `pedantic`

triagebot.toml
This adds the S-waiting-on-review autolabel feature for new PRs.  This was previously handled by highfive, but I neglected to include it in #9963.
=> Add S-waiting-on-review autolabel.

clippy_lints/src/doc.rs, tests/ui/unnecessary_unsafety_doc.rs, tests/ui/unnecessary_unsafety_doc.stderr
This lint was added in #9822. I like the idea, but also agree with #9986 as well. I think it should at least not be warn-by-default. This is one of these cases, where I'd like a group between pedantic and restriction. But I believe that users using `#![warn(clippy::pedantic)]` will know how to enable the lint if they disagree with it.
---
Since the lint is new:
r? @flip1995 since I'd suggest back porting this, the original PR was merged 16 days ago.
Closes: #9986 (While it doesn't address everything, I believe that this is the best compromise)
=> Move `unnecessary_unsafety_doc` to `pedantic`

clippy_lints/src/collapsible_if.rs, clippy_lints/src/redundant_closure_call.rs, clippy_utils/src/source.rs, clippy_utils/src/sugg.rs, tests/ui/redundant_closure_call_fixable.fixed, tests/ui/redundant_closure_call_fixable.rs, tests/ui/redundant_closure_call_fixable.stderr
fixes #9957 
changelog: `redundant_closure_call`: Don't cross macro contexts while building the suggestion
=> Don't cross contexts while building the suggestion for `redundant_closure_call`

clippy_lints/src/dereference.rs, tests/ui/explicit_auto_deref.fixed, tests/ui/explicit_auto_deref.rs
fixes #9901
fixes #9777
changelog: `explicit_auto_deref`: Don't lint when the initial value is neither a reference, nor a receiver
=> Don't lint `explicit_auto_deref` when the initial type is neither a reference, nor a receiver

clippy_lints/src/casts/unnecessary_cast.rs, tests/ui/unnecessary_cast.fixed, tests/ui/unnecessary_cast.rs, tests/ui/unnecessary_cast.stderr
fixes #9906
changelog: `unnecessary_cast`: Fix suggestion when taking a reference
=> Fix `unnecessary_cast` suggestion when taking a reference

clippy_lints/src/unused_rounding.rs, tests/ui/unused_rounding.fixed, tests/ui/unused_rounding.rs, tests/ui/unused_rounding.stderr
fixes #9866
changelog: `unused_rounding`: Fix ICE when using the `_` separator
=> Fix ICE in `unused_rounding`

clippy_lints/src/manual_let_else.rs, tests/ui/manual_let_else.rs, tests/ui/manual_let_else.stderr
Closes #9940
changelog: [`manual_let_else`]: Do not expand macro calls on suggestions
=> manual_let_else: keep macro call on suggestion blocks

clippy_lints/src/functions/result.rs, tests/ui/result_large_err.rs
fixes #10005
changelog: `result_large_err`: Fix ICE with uninhabited enums
=> Fix ICE in `result_large_err` with uninhabited enums

clippy_lints/src/strings.rs, tests/ui/string_lit_as_bytes.fixed, tests/ui/string_lit_as_bytes.rs
fixes #9885
changelog: `string_lit_as_bytes`: Don't lint in match scrutinees
=> Don't lint `string_lit_as_bytes` in match scrutinees

clippy_lints/src/manual_let_else.rs, tests/ui/manual_let_else_match.rs, tests/ui/manual_let_else_match.stderr
Fix #9938
changelog: Sugg: [`manual_let_else`]: Suggestions for or-patterns now include required brackets.
[#9966](https://github.com/rust-lang/rust-clippy/pull/9966)
=> Fix manual_let_else produces a wrong suggestion with or-patterns

clippy_lints/src/redundant_static_lifetimes.rs, tests/ui/redundant_static_lifetimes.fixed, tests/ui/redundant_static_lifetimes.rs, tests/ui/redundant_static_lifetimes.stderr
fixes #9890
changelog: `redundant_static_lifetimes`: Don't suggest removing `mut` from references
=> Don't suggest removing `mut` from references in `redundant_static_lifetimes`

clippy_utils/src/lib.rs, tests/ui/cast_lossless_integer.fixed, tests/ui/cast_lossless_integer.rs
fixes #9882
changelog: All lints: Don't lint in enum discriminant values when the suggestion won't work in a const context
=> Treat custom enum discriminant values as constants

clippy_lints/src/manual_assert.rs, tests/ui/manual_assert.edition2018.fixed, tests/ui/manual_assert.edition2021.fixed, tests/ui/manual_assert.edition2021.stderr, tests/ui/manual_assert.rs
fixes #9886
changelog: `manual_assert`: Don't lint in `else if`
=> Don't lint `manual_assert` in `else if`

clippy_lints/src/from_over_into.rs, tests/ui/from_over_into.fixed, tests/ui/from_over_into.rs, tests/ui/from_over_into.stderr
fixes #9935
This is stalled until the next sync. The impl in question can't be written on the pinned nightly.
changelog: Don't lint `from_over_into` for opaque types
=> Don't lint `from_over_into` for opaque types

clippy_lints/src/len_zero.rs, tests/ui/len_zero.fixed, tests/ui/len_zero.rs, tests/ui/len_zero.stderr
This PR fixes #9958. In order to fix the issue, the lint will now peel reference operators and enclose the expression with parentheses when necessary.
changelog: [`comparison_to_empty`]: Peel deref operators in suggestions when necessary
=> `comparison_to_empty`: peel derefs in suggestions

clippy_lints/src/methods/implicit_clone.rs, tests/ui/implicit_clone.fixed, tests/ui/implicit_clone.rs
fixes #10019
changelog: `implicit_clone`: Don't lint when the type doesn't implement clone
=> Don't lint `implicit_clone` when the type doesn't implement clone

clippy_utils/src/ty.rs
=> Add missing slash to produce function documentation

clippy_lints/src/lib.rs, clippy_lints/src/misc.rs, tests/ui/zero_ptr_no_std.fixed, tests/ui/zero_ptr_no_std.rs, tests/ui/zero_ptr_no_std.stderr
fixes #10017
---
changelog: Sugg: [`zero_ptr`]: Now suggests `core::` paths for `no_std` crates
[#10023](https://github.com/rust-lang/rust-clippy/pull/10023)
=> Fix `zero_ptr` suggestion for `no_std` crates

triagebot.toml
Also non-maintainers should be able to label PRs with `beta-nominated`.
=> Add beta-nominated label to triagebot

clippy_lints/src/lib.rs, clippy_lints/src/operators/arithmetic_side_effects.rs, clippy_lints/src/operators/mod.rs, clippy_lints/src/utils/conf.rs, tests/ui-toml/arithmetic_side_effects_allowed/arithmetic_side_effects_allowed.rs, tests/ui-toml/arithmetic_side_effects_allowed/arithmetic_side_effects_allowed.stderr, tests/ui-toml/arithmetic_side_effects_allowed/clippy.toml, tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr, tests/ui/arithmetic_side_effects.stderr
Depends on https://github.com/rust-lang/rust-clippy/pull/9592.
Because of https://github.com/rust-lang/rust-clippy/pull/9559#discussion_r985293523, r? @Alexendoo 
```
changelog: [`arithmetic-side-effects`]: Consider user-provided pairs
```
=> [`arithmetic-side-effects`]: Consider user-provided pairs

clippy_lints/src/operators/identity_op.rs, tests/ui/identity_op.fixed, tests/ui/identity_op.rs, tests/ui/identity_op.stderr
fixes #9904
changelog: `identity_op`: Don't suggest keeping borrows
=> Don't suggest keeping borrows in `identity_op`

clippy_lints/src/format_args.rs, clippy_utils/src/macros.rs, tests/ui/uninlined_format_args_panic.edition2018.fixed, tests/ui/uninlined_format_args_panic.edition2021.fixed, tests/ui/uninlined_format_args_panic.edition2021.stderr, tests/ui/uninlined_format_args_panic.rs
Similar to https://github.com/rust-lang/rust-clippy/pull/9605, but for `assert!` and `debug_assert!` macros. ([non_fmt_panics lint triggers them](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=18b20c408ec62a67f1503cd5d284424b))
changelog: [`uninlined_format_args`]: Do not inline `assert!` and `debug_assert!` macros before 2021 edition
r? @llogiq
=> uninlined_format_args: Ignore assert! and debug_assert! before 2021 edition

clippy_lints/src/manual_is_ascii_check.rs, tests/ui/manual_is_ascii_check.fixed, tests/ui/manual_is_ascii_check.rs, tests/ui/manual_is_ascii_check.stderr
Sorry, not familiar the api, i can only check the method name of expression `<expr-1>.contains(<expr-2>)` after read clippy book and hints from #9933 . i dont know how to check
1.  if <expr-1> is a specific range
2. <expr-2> is a character
r? @xFrednet could you please provide some more hints? 😝️
---
changelog: Enhancement: [`manual_is_ascii_check`]: Now detects ranges with `.contains()` calls
[#10053](https://github.com/rust-lang/rust-clippy/pull/10053)
=> improve `manual_is_ascii_check ` check

Cargo.toml, build.rs, rustc_tools_util/CHANGELOG.md, rustc_tools_util/Cargo.toml, rustc_tools_util/README.md, rustc_tools_util/src/lib.rs, src/driver.rs, src/main.rs, tests/versioncheck.rs
If possible, I'd like to have a new release for this, maybe `v0.3.0` to use the changes in another project. Then we can also remove the `path = "./rustc_tools_util"` from `Cargo.toml`. I'd be happy to help with the release on crates.io if you'd like the help :)
r? @matthiaskrgr
=> Cleanup `rustc_tool_util` and add a convenient macro for `build.rs`

clippy_utils/src/ty.rs, tests/ui/new_ret_no_self.rs, tests/ui/new_ret_no_self.stderr
Fix #10041
This uses a hash set, as described in https://github.com/rust-lang/rust-clippy/pull/10068#issuecomment-1352528391
changelog: [`new_return_no_self`]: fix stack overflow when the return type is `impl Trait` and contains recursive bounds
=> Fix new_return_no_self with recursive bounds

clippy_lints/src/loops/utils.rs, tests/ui/explicit_counter_loop.rs
There used to be a logical bug where IncrementVisitor would completely stop checking an expression/block after seeing a continue statement.
I am a little unsure of whether my fix to `IncrementVisitor` is logically sound (I hope it makes sense). Let me know what you think, and thanks in advance for the review!
fixes #10058
---
changelog: FP: [`explicit_counter_loop`]: No longer ignores counter changes after `continue` expressions
[#10094](https://github.com/rust-lang/rust-clippy/pull/10094)
=> fix logic in IncrementVisitor

clippy_lints/src/methods/seek_to_start_instead_of_rewind.rs, tests/ui/seek_to_start_instead_of_rewind.fixed, tests/ui/seek_to_start_instead_of_rewind.rs, tests/ui/seek_to_start_instead_of_rewind.stderr
changelog: [`seek_to_start_instead_of_rewind`]: No longer lints, if the return of `seek` is used.
[#10096](https://github.com/rust-lang/rust-clippy/pull/10096)
Fixes #10065
=> fix: not suggest seek_to_start_instead_of_rewind when expr is used

clippy_lints/src/useless_conversion.rs, tests/ui/useless_conversion.fixed, tests/ui/useless_conversion.rs, tests/ui/useless_conversion.stderr
changelog: Sugg: [`useless_conversion`]: Now suggests removing calls to `into_iter()` on an expression implementing `Iterator`
[#10020](https://github.com/rust-lang/rust-clippy/pull/10020)
=> Identify more cases of useless `into_iter()` calls

clippy_lints/src/manual_clamp.rs
As discussed in https://github.com/rust-lang/rust-clippy/pull/9484#issuecomment-1278922613 and decided in the [Zulip meeting](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Meeting.202022-12-13/near/315626226)
changelog: Moved [`manual_clamp`] to `nursery` (Now allow-by-default)
[#10101](https://github.com/rust-lang/rust-clippy/pull/10101)
=> Move manual_clamp to nursery

clippy_lints/src/large_const_arrays.rs, clippy_lints/src/large_stack_arrays.rs, clippy_lints/src/utils/conf.rs, tests/ui/crashes/ice-10044.rs, tests/ui/crashes/ice-10044.stderr
Change `maximum_allowed_size` config variable type from `u64` to `u128`, and converting total array sizes to `u128` to avoid overflow during multiplication.
Fixes #10044
changelog: Fix: [`large_const_arrays`] and [`large_stack_arrays`]: avoid integer overflow when calculating total array size
#10103
=> Fix overflow ICE in large_stack/const_arrays

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/lib.rs, clippy_lints/src/permissions_set_readonly_false.rs, tests/ui/permissions_set_readonly_false.rs, tests/ui/permissions_set_readonly_false.stderr
Add slight modification on [this PR](https://github.com/rust-lang/rust-clippy/pull/9744).
---
changelog: New lint [`permissions_set_readonly_false`]
[#10063](https://github.com/rust-lang/rust-clippy/pull/10063)
=> add [`permissions_set_readonly_false`] #9702

clippy_lints/src/matches/manual_filter.rs, tests/ui/manual_filter.fixed, tests/ui/manual_filter.rs
fixes #10088 
fixes #9766
changelog: FP: [`manual_filter`]: Now ignores if expressions where the else branch has side effects or doesn't return `None`
[#10091](https://github.com/rust-lang/rust-clippy/pull/10091)
=> fix manual_filter false positive

clippy_lints/src/returns.rs, tests/ui/needless_return.fixed, tests/ui/needless_return.rs, tests/ui/needless_return.stderr
Fixes #9947
changelog: Fix: [`needless_return`]: don't lint when using `do yeet`
#10109
=> Fix FP in needless_return when using yeet

clippy_lints/src/matches/match_wild_enum.rs, clippy_utils/src/sugg.rs, tests/ui/match_wildcard_for_single_variants.fixed, tests/ui/match_wildcard_for_single_variants.rs, tests/ui/match_wildcard_for_single_variants.stderr
fix #9993
changelog: FP: [`match_wildcard_for_single_variants`]: No longer lints on wildcards with a guard
[#10056](https://github.com/rust-lang/rust-clippy/pull/10056)
r? @Jarcho
=> Avoid `match_wildcard_for_single_variants` on guarded wild matches

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/lib.rs, clippy_lints/src/size_of_ref.rs, tests/ui/size_of_ref.rs, tests/ui/size_of_ref.stderr
This addresses #9995, which is likely raising a valid point about `std::mem::size_of_val()`: It's [very easy to use double-references as the argument](https://github.com/apache/arrow-datafusion/pull/4371#discussion_r1032385224), which the function will happily accept and give back the size of _the reference_, not the size of the value _behind_ the reference. In the worst case, if the value matches the programmer's expectation, this seems to work, while in fact, everything will go horribly wrong e.g. on a different platform.
The size of a `&T` is independent of what `T` is, and people might want to use `std::mem::size_of_val()` to actually get the size of _any_ reference (e.g. via `&&()`). I would rather suggest that this is always bad behavior, though …
=> Add size_of_ref lint

clippy_lints/src/functions/mod.rs
changelog: [`not_unsafe_ptr_arg_deref`]: strengthened documentation wording, fixes #7714
=> `not_unsafe_ptr_arg_deref` update documentation

clippy_lints/src/floating_point_arithmetic.rs, tests/ui/floating_point_powi.fixed, tests/ui/floating_point_powi.rs, tests/ui/floating_point_powi.stderr
fixes #10003
There was an error when trying to negate an expression like `x - 1.0`. We used to format it as `-x - 1.0` whereas a proper negation would be `-(x - 1.0)`.
Therefore, we add parentheses around the expression when it is `ExprKind::Binary`.
We also add parentheses around multiply and divide expressions, even though this is not strictly necessary.
changelog: [`suboptimal_flops`]: fix incorrect suggestion caused by an incorrect negation of floating point expressions.
=> fix incorrect suggestion in `suboptimal_flops`

clippy_lints/src/utils/internal_lints/metadata_collector.rs
While I've looked into https://github.com/rust-lang/rust-clippy/issues/9990, I found broken code blocks in the document.
This patch not only improves visibility, but also fixes a potential bug. When a lint description ends with code block, the string will have three backquotes at the end.
Since the current implementation prints the default value immediately after that, the markdown renderer is unable to properly close the code block.
e.g. `arithmetic_side_effects`, we can see code block is not rendered properly, and (I think) it's bit hard to understand what ``"defaults to `[]`"`` is meant.
In this PR, it will be rendered as:
r? @xFrednet
=> fix codeblocks in the document

clippy_lints/src/matches/match_single_binding.rs, tests/ui/match_single_binding.fixed, tests/ui/match_single_binding.rs, tests/ui/match_single_binding.stderr
Fix #9725
---
changelog: [`match_single_binding`]: suggestion no longer introduces unneeded semicolons
[#10060](https://github.com/rust-lang/rust-clippy/pull/10060)
=>  Fix [match_single_binding] suggestion introduced an extra semicolon

clippy_lints/src/mutex_atomic.rs
By #4295, the general consensus seems to be that `mutex_atomic` is not a useful lint in most cases. If anything, it could be useful as a restriction on code that for whatever reason can't use atomics. Keeping it in `clippy::nursery` is harmful to people attempting to use clippy for soundness.
---
changelog: Moved [`mutex_atomic`] to `restriction`
[#10115](https://github.com/rust-lang/rust-clippy/pull/10115)
=> Move `mutex_atomic` to `restriction`

clippy_lints/src/returns.rs, tests/ui/needless_return.fixed, tests/ui/needless_return.rs, tests/ui/needless_return.stderr
Fixes #10051
changelog: Enhancement: [`needless_return`]: Now detects more cases for returns of owned values
[#10110](https://github.com/rust-lang/rust-clippy/pull/10110)
=> Fix FN in `needless_return`

clippy_lints/src/unused_self.rs, tests/ui/unused_self.stderr
changelog: Msg: [`unused_self`]: The message now correctly uses *an*
[#10138](https://github.com/rust-lang/rust-clippy/pull/10138)
=> Fix typo in `unused_self` diagnostic message

clippy_lints/src/copies.rs, clippy_lints/src/default.rs, clippy_lints/src/loops/needless_range_loop.rs, clippy_utils/src/lib.rs, tests/ui/field_reassign_with_default.rs
fixes #10136 
This change makes the ContainsName struct visit all interior expressions, which means that ContainsName will return true even if `name` is used in a closure within `expr`.
---
changelog: FP: [`field_reassign_with_default`]: No longer lints cases, where values are initializes from closures capturing struct values
[#10143](https://github.com/rust-lang/rust-clippy/pull/10143)
=> don't lint field_reassign when field in closure

clippy_lints/src/empty_structs_with_brackets.rs
fixes #9887
I refer to [my comment](https://github.com/rust-lang/rust-clippy/issues/9887#issuecomment-1368495395) to explain this PR.
---
changelog: Sugg: [`empty_structs_with_brackets`]: The suggestion is no longer machine applicable, to avoid errors when accessing struct fields
[#10141](https://github.com/rust-lang/rust-clippy/pull/10141)
=> fix empty_structs_with_brackets suggestion errors

clippy_lints/src/methods/case_sensitive_file_extension_comparisons.rs, tests/ui/case_sensitive_file_extension_comparisons.fixed, tests/ui/case_sensitive_file_extension_comparisons.rs, tests/ui/case_sensitive_file_extension_comparisons.stderr
fixes #10042 
changelog: Sugg: [`case_sensitive_file_extension_comparisons`]: Now displays a suggestion with `Path`
[#10107](https://github.com/rust-lang/rust-clippy/pull/10107)
=> Suggest using Path for comparing extensions

clippy_utils/src/lib.rs
I was reading the code of `clippy_utils/src/lib.rs` and thought that adding comment on `get_closing_block` would be helpful to first time visitor.
---
=> chore: add simple comment for `get_enclosing_block`

clippy_lints/src/methods/iter_kv_map.rs, tests/ui/iter_kv_map.fixed, tests/ui/iter_kv_map.rs, tests/ui/iter_kv_map.stderr
For the degenerate (`map(|(k, _)| k)`/`map(|(_, v)| v)`) cases a mut annotation is superfluous and a ref annotation won't compile, so no additional handling is required. For cases where the `map` call must be preserved ref/mut annotations should also be presereved so that the map body continues to work as expected.
changelog: [`iter_kv_map`]: handle ref/mut annotations
=> Make the iter_kv_map lint handle ref/mut annotations.

clippy_lints/src/derivable_impls.rs, tests/ui/derivable_impls.fixed, tests/ui/derivable_impls.rs, tests/ui/derivable_impls.stderr
changelog: [`derivable_impls`]: suggest deriving Default for enums with a default unit variant
=> Expand derivable-impls to cover enums with a default unit variant.

clippy_lints/src/drop_forget_ref.rs, tests/ui/drop_ref.rs, tests/ui/drop_ref.stderr
fixes #10122
As established in issue #9482, it is idiomatic to use a single `drop()` expression in a match arm to achieve a side-effect of a function while discarding its output. This should also apply to cases where the function returns a reference.
The change to the lint's code was less than 1 line, because all the heavy lifting was done in PR #9491.
---
changelog: FP: [`drop_ref`]: No longer lints idiomatic expression in `match` arms
[#10142](https://github.com/rust-lang/rust-clippy/pull/10142)
=> [`drop_ref`]: don't lint idiomatic in match arm

clippy_lints/src/dbg_macro.rs, tests/ui-toml/dbg_macro/dbg_macro.stderr, tests/ui/dbg_macro.stderr
---
This change rewords the `dbg_macro` lint labels to be clearer.
=> reword dbg_macro labels

clippy_lints/src/default.rs, clippy_lints/src/methods/clone_on_copy.rs, tests/ui/clone_on_copy.stderr, tests/ui/default_trait_access.fixed, tests/ui/default_trait_access.stderr, tests/ui/unnecessary_clone.stderr
This should help making the suggestions more palatable. Similar to #10153.
---
changelog: trim paths in [`default_trait_access`]/[`clone_on_copy`] suggestions
=> trim paths in `default_trait_access`/`clone_on_copy` suggestions

clippy_lints/src/box_default.rs, tests/ui/box_default.fixed, tests/ui/box_default.stderr
This might help with #10089, though I have not tested that yet. In any event, it keeps the suggestion short and to the point.
---
changelog: Trim paths in [`box_default`] suggestion
=> trim paths in `box_default`

clippy_lints/src/operators/arithmetic_side_effects.rs, clippy_utils/src/lib.rs, tests/ui-toml/arithmetic_side_effects_allowed/arithmetic_side_effects_allowed.rs, tests/ui/arithmetic_side_effects.rs, tests/ui/arithmetic_side_effects.stderr
Same as #9867.
Opening again because it is not possible to randomly choose a reviewer in an ongoing PR like in the rust repo.
---
changelog: PF: [`arithmetic_side_effects`]: No longer lints on corner cases with negative number literals
[#9867](https://github.com/rust-lang/rust-clippy/pull/9867)
=> [arithmetic-side-effects] Consider negative numbers and add more tests

clippy_lints/src/ranges.rs
Reading the documentation for the lint, one could expect that the lint works in all cases that `X == Y`. This is false.
While the lint was updated, the documentation wasn't.
More information about the `N..N` problem in #5689 and #5628
---
Fixes #10167 
changelog: [`reversed_empty_ranges`]: Update and clarify documentation
=> [#10167] Clarify that the lint only works if x eq. y in a `for` loop.

clippy_lints/src/derivable_impls.rs, clippy_lints/src/lib.rs, clippy_utils/src/msrvs.rs
See https://blog.rust-lang.org/2022/06/30/Rust-1.62.0.html#default-enum-variants
---
=> Restrict suggestion of deriving Default for enums to MSRV 1.62.

clippy_lints/src/loops/single_element_loop.rs, clippy_utils/src/visitors.rs, tests/ui/single_element_loop.fixed, tests/ui/single_element_loop.rs, tests/ui/single_element_loop.stderr
closes #10018
---
changelog: [`single_element_loop`]: No longer lints, if the loop contains a `break` or `continue`
[#10162](https://github.com/rust-lang/rust-clippy/pull/10162)
=> Fix FP of single-element-loop

clippy_utils/src/paths.rs
`&paths:ITER_COUNT` is not being called from anywhere, so removing it doesn't seem to be a problem.
---
=> hotfix: remove `ITER_COUNT` since it is not called

tests/ui/box_default.fixed, tests/ui/box_default.rs, tests/ui/box_default.stderr
This was just an oversight while doing the box default path trimming PR, so I'm adding it rather late than never.
---
=> add a test against #10089

clippy_lints/src/unused_self.rs, tests/ui/unused_self.rs
If the author is using todo!(), presumably they intend to use self at some point later, so we don't have a good basis to recommend factoring out to an associated function.
Fixes #10117.
---
changelog: Enhancement: [`unused_self`]: No longer lints, if the method body contains a `todo!()` call
[#10166](https://github.com/rust-lang/rust-clippy/pull/10166)
=> unused_self: Don't trigger if the method body contains todo!()

clippy_lints/src/derive.rs, tests/ui/derive.rs
changelog: [`expl_impl_clone_on_copy`]: Ignore `#[repr(packed)]` structs with type or const paramaters
Fixes #10188
A more involved solution that checks if any bound on the trait impl aren't present on the struct definition would be ideal, but I couldn't see a nice way to go about that
=> expl_impl_clone_on_copy: ignore packed structs with type/const params

clippy_lints/src/methods/suspicious_to_owned.rs, tests/ui/suspicious_to_owned.stderr
This continues my path trimming spree. I'm not going to add yet another changelog entry, we should have one "trim paths in some applicable lints" entry instead.
---
=> trim paths in `suspicious_to_owned`

.github/driver.sh, src/driver.rs, tests/integration.rs
This is useful for rust-lang/rust to allow setting a sysroot that's *only* for build scripts, different from the regular sysroot passed in RUSTFLAGS (since cargo doesn't apply RUSTFLAGS to build scripts or proc-macros).
That said, the exact motivation is not particularly important: this fixes a regression from
https://github.com/rust-lang/rust-clippy/pull/9881/commits/5907e9155ed7f1312d108aa2110853472da3b029#r1060215684.
Note that only RUSTFLAGS is tested in the new integration test; passing --sysroot through `clippy-driver` never worked as far as I can tell, and no one is using it, so I didn't fix it here.
Helps with https://github.com/rust-lang/rust/pull/106394.
---
changelog: other: `SYSROOT` and `--sysroot` can now be set at the same time …
=> Don't pass `--sysroot` twice if SYSROOT is set

clippy_lints/src/dereference.rs, clippy_lints/src/redundant_clone.rs, clippy_utils/src/mir/possible_borrower.rs, tests/ui/needless_borrow.fixed, tests/ui/needless_borrow.rs, tests/ui/needless_borrow.stderr, tests/ui/redundant_clone.fixed, tests/ui/redundant_clone.rs, tests/ui/redundant_clone.stderr
This partially reverts #9701 due to #10134
r? @flip1995 
=> Partially revert #9701

clippy_lints/src/instant_subtraction.rs
changelog: [`unchecked_duration_subtraction`]: Move to pedantic
Based on https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Meeting.202023-01-10/near/320488860
=> Move `unchecked_duration_subtraction` to pedantic

book/src/development/adding_lints.md
changelog: Add missing arguments to `new_lint` code example.
From the surrounding text, it seems like this code example is missing the arguments to create a new `cargo` lint.
=> Add missing arguments to `new_lint` example of `cargo` lints

clippy_lints/src/casts/cast_possible_truncation.rs, clippy_lints/src/casts/mod.rs, tests/ui/cast.rs, tests/ui/cast.stderr, tests/ui/cast_size.stderr
This fixes the last issues from https://github.com/rust-lang/rust-clippy/pull/9664 as the author seems to be inactive. The PR author was sadly kept during the rebase, due to the conflict resolution.
IDK if it's worth it do to a full review, I only added the last commit, everything else remained the same, besides a rebase.
---
changelog: Sugg: [`cast_possible_truncation`]: Now suggests using `try_from` or allowing the lint
[#10038](https://github.com/rust-lang/rust-clippy/pull/10038)
closes: https://github.com/rust-lang/rust-clippy/issues/9231
=> `cast_possible_truncation` Suggest TryFrom when truncation possible

clippy_lints/src/returns.rs, clippy_utils/src/lib.rs, tests/ui/needless_return.fixed, tests/ui/needless_return.rs, tests/ui/needless_return.stderr
Closes #10182 
Multiple semicolons currently breaks autofix for `needless_return` suggestions. Any semicolons left after removing return means that the return type will always be `()`, and thus fail to compile.
This PR allows `needless_return` to remove multiple semicolons.
The change won't cover the case where there is multiple line yet.
i.e. 
```rust
fn needless_return() -> bool {
return true;
;;
}
```
---
changelog: Sugg: [`needless_return`]: Now removes all semicolons on the same line
[#10187](https://github.com/rust-lang/rust-clippy/pull/10187)
=> [needless_return]: Remove all semicolons on suggestion 

book/src/development/infrastructure/changelog_update.md
- Make the clippy::version attribute instructions more prominent.
- Mention the beta-accepted label.
[Rendered](https://github.com/flip1995/rust-clippy/blob/changelog-doc/book/src/development/infrastructure/changelog_update.md)
r? @xFrednet 
=> Improve the changelog update documentation

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/lib.rs, clippy_lints/src/multiple_unsafe_ops_per_block.rs, tests/ui/multiple_unsafe_ops_per_block.rs, tests/ui/multiple_unsafe_ops_per_block.stderr
Adds a lint, which restricts an `unsafe` block to only one unsafe operation.
Closes #10064
---
changelog: New lint: [`multiple_unsafe_ops_per_block`]
[#10206](https://github.com/rust-lang/rust-clippy/pull/10206)
=> Add `multiple_unsafe_ops_per_block` lint

CHANGELOG.md, clippy_lints/src/doc.rs, clippy_lints/src/from_raw_with_void_ptr.rs, clippy_lints/src/instant_subtraction.rs, clippy_lints/src/let_underscore.rs, clippy_lints/src/manual_is_ascii_check.rs, clippy_lints/src/methods/mod.rs, clippy_lints/src/suspicious_xor_used_as_pow.rs
Roses are red,
if changelogs could talk,
what would we do?
---
The usual disclaimer: This PR is written, as if the version was already released. It should be merged with the coming release on 2023-01-26. So, please provide feedback and approve it, if everything looks good, but let's wait with the r+ until the release :)
---
=> Changelog for Rust 1.67 :lady_beetle:

clippy_lints/src/bool_assert_comparison.rs, tests/ui/bool_assert_comparison.fixed, tests/ui/bool_assert_comparison.stderr
Fixes #7598
Also closes #8118, it had already been fixed by an earlier change but I've added a test for it
changelog: [`bool_assert_comparison`] The suggestion is now machine applicable
=> Add machine applicable suggestion for `bool_assert_comparison`

src/main.rs
changelog: Fix typo in help message
=> Tiny typo: `eg.` -> `e.g.`

clippy_lints/src/undocumented_unsafe_blocks.rs, tests/ui/unnecessary_safety_comment.rs
Fix https://github.com/rust-lang/rust-clippy/issues/10084
changelog: FP: [`unnecessary_safety_comment`]: No longer lints code inside macros
[#10106](https://github.com/rust-lang/rust-clippy/pull/10106)
=> Fix FP in `unnecessary_safety_comment`

clippy_lints/src/enum_variants.rs, tests/ui/module_name_repetitions.stderr
changelog: [`module_name_repetitions`]: Narrowed span to the identifier
=> Improve span for module_name_repetitions

CHANGELOG.md
Roses are red,
not much to say,
not much to do
---
changelog: none.
=> Mark Rust 1.67 as released in the changelog

clippy_lints/src/suspicious_xor_used_as_pow.rs
There was a tab after the three leading slashes which caused the contents of the "Why is this bad?" section to be rendered as a code block.
**Before:**
**After:**
The file still contains a lot of tabs but they don't affect the documentation.
---
changelog: [`suspicious_xor_used_as_pow`]: Fix styling in documentation
=> Fix styling in documentation for `suspicious_xor_used_as_pow` lint

clippy_lints/src/regex.rs, tests/ui/regex.rs, tests/ui/regex.stderr
changelog: [`invalid_regex`]: Show full error when parsing non-literals or regular strings containing escape sequences
Fixes #4170, the escape sequence there causes the span to be incorrect which will have caused most of the confusion
=> `invalid_regex`: Show full error when string value doesn't match source

clippy_lints/src/loops/mod.rs, clippy_lints/src/loops/needless_range_loop.rs, tests/ui/needless_range_loop.stderr
fixes #6929
changelog: [`needless_range_loop`]: improve documentation
=> needless_range_loop: improve documentation

clippy_lints/src/multiple_unsafe_ops_per_block.rs, tests/ui/auxiliary/macro_rules.rs, tests/ui/multiple_unsafe_ops_per_block.rs, tests/ui/multiple_unsafe_ops_per_block.stderr
Fixes #10259
changelog: FP: [`multiple_unsafe_ops_per_block`]: No longer lints in external macros
[#10260](https://github.com/rust-lang/rust-clippy/pull/10260)
=> `multiple_unsafe_ops_per_block`: Don't lint in external macros

clippy_lints/src/lifetimes.rs, tests/ui/auxiliary/macro_rules.rs, tests/ui/needless_lifetimes.rs, tests/ui/needless_lifetimes.stderr
fixes #5283
changelog: [`needless_lifetimes`]: lint local macros
=> needless_lifetimes: lint local macros

clippy_lints/src/unused_io_amount.rs, tests/ui/unused_io_amount.rs, tests/ui/unused_io_amount.stderr
Fixes #10132
changelog: Apply [`unused_io_amount`] lint to `is_ok` and `is_err` without checking read/write amount
=> [`unused_io_amount`]: Lint with `is_ok` and `is_err`

clippy_lints/src/lifetimes.rs, tests/ui/crashes/ice-2774.stderr, tests/ui/crashes/needless_lifetimes_impl_trait.stderr, tests/ui/needless_lifetimes.fixed, tests/ui/needless_lifetimes.stderr
changelog: [`needless_lifetimes`]: Add machine applicable suggestion
Fixes #9360
It doesn't make suggestions for async functions as the input lifetime spans are funky there
The examples in #5787 and #7271 no longer seem to FP this PR aside, I added tests for them rather than disabling the lint entirely for async functions, I don't know if there are further FPs there though
Closes #5787
Closes #7271
=> Add machine applicable suggestion for `needless_lifetimes`

clippy_lints/src/format_args.rs
Fixes https://github.com/rust-lang/rust-clippy/issues/10087
We should restore this when rust-analyzer support gets better. Worth filing an issue to track.
changelog: Mark [`uninlined_format_args`] as `pedantic`
=> Mark uninlined_format_args as pedantic

Cargo.toml, clippy_dev/Cargo.toml, clippy_dev/src/main.rs, clippy_lints/Cargo.toml, lintcheck/Cargo.toml
Allows removing some duplicate dependencies in rust-lang/rust's `Cargo.lock`.
=> Update dependencies `cargo_metadata` and `clap`

clippy_lints/src/matches/match_wild_enum.rs, tests/ui/match_wildcard_for_single_variants.fixed, tests/ui/match_wildcard_for_single_variants.stderr, tests/ui/wildcard_enum_match_arm.fixed, tests/ui/wildcard_enum_match_arm.stderr
fixes #7419 
---
changelog: Enhancement: [`wildcard_enum_match_arm`]: Now lints missing private variants, for local enums
[#10250](https://github.com/rust-lang/rust-clippy/pull/10250)
=> wildcard_enum_match_arm lint takes the enum origin into account

clippy_lints/src/manual_assert.rs, tests/ui/manual_assert.edition2018.fixed, tests/ui/manual_assert.edition2018.stderr
Part of https://github.com/rust-lang/rust-clippy/issues/10233
=> Don't depend on FormatArgsExpn in ManualAssert.

CHANGELOG.md, README.md, book/src/README.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/extra_unused_type_parameters.rs, clippy_lints/src/lib.rs, tests/ui/extra_unused_type_parameters.rs, tests/ui/extra_unused_type_parameters.stderr, tests/ui/needless_lifetimes.fixed, tests/ui/needless_lifetimes.rs, tests/ui/needless_lifetimes.stderr, tests/ui/new_without_default.rs, tests/ui/new_without_default.stderr, tests/ui/redundant_field_names.fixed, tests/ui/redundant_field_names.rs, tests/ui/seek_to_start_instead_of_rewind.fixed, tests/ui/seek_to_start_instead_of_rewind.rs, tests/ui/type_repetition_in_bounds.rs, tests/ui/type_repetition_in_bounds.stderr
Closes #9240. ~~Keeping this as draft for now, because of a bug that I don't know how to fix.~~ It seems that opaque return types are not walked properly, for some unknown reason. As in, the following:
```rust
fn used_ret_opaque<A>() -> impl Iterator<Item = A> {
std::iter::empty()
}
```
This triggers the lint even though it shouldn't. Discussion on Zulip didn't illuminate any possible reasons why, so PR-ing this now to increase visibility.
---
changelog: new lint: [`extra_unused_type_parameters`]
[#10028](https://github.com/rust-lang/rust-clippy/pull/10028)
=> Add `extra_unused_type_parameters` lint

clippy_lints/src/methods/suspicious_to_owned.rs, tests/ui/suspicious_to_owned.stderr
fixes #10294
changelog: [`suspicious_to_owned`]: suggestions now produce valid Rust code
=> fix(suspicious_to_owned): use span_suggestions to suggest both intents

clippy_lints/src/bool_assert_comparison.rs, tests/ui/bool_assert_comparison.fixed, tests/ui/bool_assert_comparison.rs, tests/ui/bool_assert_comparison.stderr
changelog: none assuming this gets into the same release as #10218
Fixes #10291
r? @dswij
Thanks to @black-puppydog for spotting it early
=> Negate suggestions when needed in `bool_assert_comparison`

clippy_lints/src/utils/dump_hir.rs
Roses are red,
trait items are rare,
`[clippy::dump]` is too
---
Let's just ignore the horrible poem... anyways. While working on Marker I noticed, that `[clippy::dump]` doesn't work on trait item (See [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e2d9791ffa2872e7c09a9dfbd470350c)). This simply adds support for that. `[clippy::dump]` doesn't have UI tests, to make it more resistant to changes in the AST. I tested it locally and the dump works after these changes.
---
=> Make `[clippy::dump]` support trait items

clippy_dev/src/main.rs
Clap was updated in rust-lang/rust-clippy#10270, which broke the command line of clippy_dev. This swaps out contains_id, which now returns always true in the places it was used with get_flag.
r? @xFrednet 
This should also fix https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/.60cargo.20dev.20setup.20intellij.60.20is.20degraded/near/325770850
=> Fix CLI of clippy_dev

clippy_lints/src/casts/cast_possible_truncation.rs, tests/ui/cast.stderr, tests/ui/cast_size.stderr
Fixes #10325 
---
changelog: Sugg: [`cast_possible_truncation`]: Corrected the lint name in help message
[#10330](https://github.com/rust-lang/rust-clippy/pull/10330)
=> cast_possible_truncation: issue proper help message

lintcheck/src/config.rs
clap 4.1.4 panics if `-` is used at the start of an argument:
```
$ cargo lintcheck
[…]
thread 'main' panicked at 'Argument recursive: long "--recursive" must not start with a `-`, that will be handled by the parser', /home/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.1.4/src/builder/debug_asserts.rs:82:13
```
=> lintcheck: fix clap panic

clippy_lints/src/operators/arithmetic_side_effects.rs, tests/ui/arithmetic_side_effects.rs, tests/ui/arithmetic_side_effects.stderr
Fix #10209
---
changelog: Enhancement: [`arithmetic_side_effects`]: No longer lints, if safe constant values are used.
[#10310](https://github.com/rust-lang/rust-clippy/pull/10310)
=> [arithmetic_side_effects] Fix #10209

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/methods/mod.rs, clippy_lints/src/methods/suspicious_command_arg_space.rs, clippy_utils/src/paths.rs, tests/ui/suspicious_command_arg_space.rs, tests/ui/suspicious_command_arg_space.stderr
Fixes #10316
---
changelog: New lint: [`suspicious_command_arg_space`]
[#10317](https://github.com/rust-lang/rust-clippy/pull/10317)
=> Add `suspicious_command_arg_space` lint

clippy_lints/src/loops/never_loop.rs, tests/ui/never_loop.rs, tests/ui/never_loop.stderr
It is not sufficient to ignore break from a block inside the loop. Instructions after the break must be ignored, as they are unreachable. This is also true for all instructions in outer blocks and loops until the right block is reached.
Fixes #10304
---
changelog: FP: [`never_loop`]: No longer lints, for statements following break statements for outer blocks.
[#10311](https://github.com/rust-lang/rust-clippy/pull/10311)
=> [never_loop] Fix #10304

clippy_lints/src/entry.rs, tests/ui/entry.fixed, tests/ui/entry.rs
Fixes #10331
changelog: [`map_entry`]: do not base suggestion on code expanded by the compiler
=> Do not base map_entry lint suggestion on expanded code

clippy_lints/src/manual_let_else.rs, tests/ui/manual_let_else.rs
The divergent `else` block of a `let`/`else` statement does not make the `let/else` statement itself divergent.
Fixes #10296 
changelog: [`manual_let_else`]: do not consider `let`/`else` to be divergent by default
=> manual_let_else: let/else is not divergent by default

clippy_lints/src/returns.rs, tests/ui/needless_return.fixed, tests/ui/needless_return.rs, tests/ui/needless_return.stderr
fixes: #10049 
---
changelog: [`needless_return`]: fix incorrect suggestion  on if sequence
=> fix [`needless_return`] incorrect suggestion when returning if sequence

clippy_lints/src/format_args.rs, tests/ui/uninlined_format_args.fixed, tests/ui/uninlined_format_args.rs
Fix #10339
---
changelog: FP: [`uninlined_format_args`]: No longer lints for arguments with generic parameters
[#10343](https://github.com/rust-lang/rust-clippy/pull/10343)
=> uninlined_format_args: do not inline argument with generic parameters

clippy_lints/src/extra_unused_type_parameters.rs, tests/ui/extra_unused_type_parameters.rs, tests/ui/extra_unused_type_parameters.stderr, tests/ui/type_repetition_in_bounds.rs, tests/ui/type_repetition_in_bounds.stderr
Don't lint external macros. Also, if the function body is empty, any type parameters with bounds on them are not linted. Note that only the body needs be empty - this rule still applies if the function takes any arguments.
fixes #10318
fixes #10319 
=> Fix false positives for `extra_unused_type_parameters`

clippy_lints/src/extra_unused_type_parameters.rs, tests/ui/extra_unused_type_parameters.rs, tests/ui/extra_unused_type_parameters.stderr
There was a minor bug around calculating spans when forming the help message. An example:
```rust
fn unused_opaque<A, B>(dummy: impl Default) {}
//               ^^ ^
```
In this case, the entire list of generics should be highlighted, instead of each individual parameter. The culprit is the `impl Default`, which registers as a type parameter but doesn't live within the `<...>`. Because synthetic parameters can't ever be manually created, we just ignore them for this lint.
r? @flip1995 
=> Ignore synthetic type parameters for `extra_unused_type_parameters`

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/lib.rs, clippy_lints/src/significant_drop_tightening.rs, tests/ui/significant_drop_tightening.fixed, tests/ui/significant_drop_tightening.rs, tests/ui/significant_drop_tightening.stderr
cc #9399
Creates the lint with minimum functionalities, which is a good start IMO.
---
changelog: new lint: [`significant_drop_tightening`]
[#10163](https://github.com/rust-lang/rust-clippy/pull/10163)
=> [significant_drop_tightening] Add MVP

CHANGELOG.md, clippy_dev/src/new_lint.rs, clippy_dev/src/update_lints.rs, clippy_lints/src/declared_lints.rs, clippy_lints/src/entry.rs, clippy_lints/src/inconsistent_struct_constructor.rs, clippy_lints/src/let_underscore.rs, clippy_lints/src/literal_representation.rs, clippy_lints/src/module_style.rs, clippy_utils/src/numeric_literal.rs, clippy_utils/src/sugg.rs, lintcheck/src/main.rs, tests/ui/let_underscore_untyped.rs, tests/ui/let_underscore_untyped.stderr, tests/ui/map_flatten_fixable.fixed, tests/ui/map_flatten_fixable.rs, tests/ui/map_flatten_fixable.stderr, tests/ui/methods.rs, tests/ui/methods.stderr
Fixes #6842
This adds a new pedantic `let_underscore_untyped` lint which checks for `let _ = <expr>`, and suggests to either provide a type annotation, or to remove the `let` keyword. That way the author is forced to specify the type they intended to ignore, and thus get forced to re-visit the decision should the type of `<expr>` change. Alternatively, they can drop the `let` keyword to truly just ignore the value no matter what.
r? @llogiq
changelog: New lint: [let_underscore_untyped]
=> Add `let_underscore_untyped`

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/lib.rs, clippy_lints/src/question_mark_used.rs, tests/ui/question_mark_used.rs, tests/ui/question_mark_used.stderr
This lint complains when the question mark operator (try operator) is used.  This is a restriction lint that can be useful on local scopes where a custom error handling macro is supposed to be used to augment the error based on local scope data before returning.
Fixes #10340
---
changelog: New lint [`question_mark_used`]
[#10342](https://github.com/rust-lang/rust-clippy/pull/10342)
=> Add question-mark-used lint

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/transmute/mod.rs, clippy_lints/src/transmute/transmute_int_to_non_zero.rs, tests/ui/transmute_int_to_non_zero.rs, tests/ui/transmute_int_to_non_zero.stderr
Fixes #10288
This adds a new complexity lint `transmute_int_to_non_zero` which checks for transmutes to any of the `NonZero*` types, and suggests their `new_unchecked` method instead.
r? @llogiq
changelog: New lint: [`transmute_int_to_non_zero`]
=> Add the `transmute_int_to_non_zero` lint

clippy_lints/src/doc.rs, tests/ui/doc/doc-fixable.fixed, tests/ui/doc/doc-fixable.rs, tests/ui/doc/doc-fixable.stderr
Fixes #10302
This lint currently checks that any link should be enclosed with `backticks` if the title looks like a lang item. This PR changes the lint to only run on internal links. External links, indicated by `http` or `https`, are skipped. 
This PR also reorganises `pulldown_cmark` imports to bypass the clippy lint enforcing 100 line functions.
---
changelog: Stop doc_markdown requiring backticks on links to external websites
=> Stop doc_markdown requiring backticks on links to external websites

clippy_lints/src/methods/bytes_nth.rs, tests/ui/bytes_nth.fixed, tests/ui/bytes_nth.rs, tests/ui/bytes_nth.stderr
Fixes #10151
As discussed in the issue, this PR changes the lint in 2 ways
1. Replace `bytes().nth(n).unwrap()` with `as_bytes()[n]`
2. Replace other `bytes().nth(n)` with `as_bytes().get(n).copied()`
---
changelog: Stop bytes_nth from suggesting code that does not compile in some cases
=> Stop bytes_nth from suggesting code that does not compile

clippy_lints/src/manual_let_else.rs, tests/ui/manual_let_else_match.rs, tests/ui/manual_let_else_match.stderr
The problem is that this lint does not consider the possibility that the divergent branch can come first and that the patterns may overlap. This led to incorrect suggestions, previously registered as correct in the tests themselves:
```rust
let v = match build_enum() {
_ => continue,
Variant::Bar(v) | Variant::Baz(v) => v,
};
```
had a `let Variant::Bar(v) | Variant::Baz(v) = v else { continue; }` suggestion, which is obviously wrong as the original code `continue`s in any case. Issue #10241 gives another example.
The code now checks that the divergent branch comes second. It could be extended later (I've added a TODO) to check for non-overlapping patterns.
Fixes #10241.
changelog: [`manual_let_else`] do not suggest non equivalent replacements in `match`
=> manual_let_else: do not suggest semantically different replacements

clippy_lints/src/significant_drop_tightening.rs, tests/ui/significant_drop_tightening.fixed, tests/ui/significant_drop_tightening.rs, tests/ui/significant_drop_tightening.stderr
Not all statements that follow the last use of a lock guard are expensive and can therefore be ignored by the lint. 
```rust
pub fn foo() -> i32 {
let mutex = Mutex::new(1);
let lock = mutex.lock().unwrap();
let rslt = *lock;
let another = rslt;
another
}
```
---
changelog: [`significant_drop_tightening`]: No longer lints for inexpensive statements after the lock guard
[#10363](https://github.com/rust-lang/rust-clippy/pull/10363)
=> [significant_drop_tightening] Ignore inexpensive statements

clippy_lints/src/significant_drop_tightening.rs, tests/ui/significant_drop_tightening.fixed, tests/ui/significant_drop_tightening.rs, tests/ui/significant_drop_tightening.stderr
For whatever reason, the return expression of a block is not contained inside the slice of statements and because of that the lint wasn't evaluating things that could potentially block the release of a lock.
```rust
pub fn example() -> i32 {
let mutex = Mutex::new(1);
let lock = mutex.lock().unwrap();
let _ = *lock;
let _ = *lock;
do_heavy_computation_that_takes_time_and_returns_i32()
}
```
---
=> [significant_drop_tightening] Evaluate the return expression of a block

clippy_lints/src/box_default.rs, tests/ui/box_default.fixed, tests/ui/box_default.rs, tests/ui/box_default.stderr
Within a larger expression, when the type of `Box::new(T::default())` is `Box<dyn Trait>`, the concrete type `T` cannot be omitted in the proposed replacement `Box::<T>::default()`.
Fixes #10381
changelog: [`box_default`]: in case of a trait object do not omit the concrete type name
=> Box::default(): do not omit the type of the removed trait object

book/src/lint_configuration.md, clippy_lints/src/lib.rs, clippy_lints/src/missing_doc.rs, clippy_lints/src/utils/conf.rs, tests/ui-toml/pub_crate_missing_docs/clippy.toml, tests/ui-toml/pub_crate_missing_docs/pub_crate_missing_doc.rs, tests/ui-toml/pub_crate_missing_docs/pub_crate_missing_doc.stderr, tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
Fixes this: https://github.com/rust-lang/rust-clippy/issues/5736#issuecomment-1412442404
TODO:
@flip1995 I'd like to get some input from you :) 
---
changelog: Enhancement: [`missing_docs_in_private_items`]: Added new configuration `missing-docs-in-crate-items` to lint on items visible within the current crate. For example, `pub(crate)` items.
[#10303](https://github.com/rust-lang/rust-clippy/pull/10303)
=> Add configuration to lint missing docs of `pub(crate)` items

clippy_lints/src/lifetimes.rs, tests/ui/needless_lifetimes.fixed, tests/ui/needless_lifetimes.rs
Fixes #10379
changelog: [`needless_lifetimes`]: Don't lint signatures in macros if the lifetime is a metavariable
=> Ignore lifetimes from differing contexts in `needless_lifetimes`

clippy_lints/src/dereference.rs, clippy_utils/src/ty.rs, tests/ui/explicit_auto_deref.fixed, tests/ui/explicit_auto_deref.rs
fixes #10384
changelog: [`explicit_auto_deref`]: Better consider projection types when checking if auto deref is applicable
=> Normalize projections types when checking `explicit_auto_deref`

README.md
Adds some stronger wording about not enabling `restriction` lints. I've seen it come up a few times where people are confused about what the `restriction` category is for and end up casually enabling lints from it (or the whole category).
=> Update readme description of `restriction` lints to dissuade casual use.

clippy_lints/src/extra_unused_type_parameters.rs, clippy_lints/src/lib.rs, tests/ui/extra_unused_type_parameters.rs, tests/ui/extra_unused_type_parameters.stderr, tests/ui/new_without_default.rs, tests/ui/new_without_default.stderr, tests/ui/redundant_field_names.fixed, tests/ui/redundant_field_names.rs
Builds on #10321. All empty functions are no longer linted, instead of just those that have trait bounds on them. Also, if a trait bound contains a non-public trait (un-exported, but still potentially reachable), then the corresponding type parameter isn't linted.
Finally, added support for the `avoid_breaking_exported_api` config option.
r? @flip1995
=> Fix more false positives for `extra_unused_type_parameters`

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/lib.rs, clippy_lints/src/no_mangle_with_rust_abi.rs, tests/ui/must_use_candidates.fixed, tests/ui/must_use_candidates.rs, tests/ui/no_mangle_with_rust_abi.fixed, tests/ui/no_mangle_with_rust_abi.rs, tests/ui/no_mangle_with_rust_abi.stderr
Fixes issue #10347
This PR adds a new lint `no_mangle_with_rust_abi` that suggests converting a function to the C ABI to if the function has the `#[no_mangle]` attribute and `Abi == Abi::Rust`. It will not run for any of the other variants defined in [rustc_target::spec::abi::Abi](https://doc.rust-lang.org/beta/nightly-rustc/rustc_target/spec/abi/enum.Abi.html), nor suggest any conversion other than conversion to the C ABI.
Functions that explicitly opt into the Rust ABI with `extern "Rust"` are ignored by this lint.
---
changelog: [`no_mangle_with_rust_abi`]: add lint that converts Rust ABI functions with the `#[no_mangle]` attribute to C ABI
=> Add new lint no_mangle_with_rust_abi

book/src/lint_configuration.md, clippy_lints/src/methods/expect_used.rs, clippy_lints/src/methods/unwrap_used.rs, clippy_lints/src/utils/conf.rs, tests/ui-toml/expect_used/expect_used.rs, tests/ui-toml/unwrap_used/unwrap_used.rs, tests/ui-toml/unwrap_used/unwrap_used.stderr
After #9686 , `unwrap` and `expect` in integration tests and raw test functions won't be allowed.
fixes #10011
fixes #10238
fixes #10264
---
changelog: Fix: [`expect_used`], [`unwrap_used`], [`dbg_macro`], [`print_stdout`], [`print_stderr`]: No longer lint in test functions, if the related configuration is set
[#10391](https://github.com/rust-lang/rust-clippy/pull/10391)
=> Fix test function checker in `unwrap_used`, `expect_used`

clippy_utils/src/macros.rs, tests/ui/format.fixed, tests/ui/format.rs, tests/ui/format.stderr
Fixes #10148. This will trigger only when generating format strings while accepting weird things in a procedural macro and setting the span to something which is not a string.
=> Do not panic when analyzing the malformed origin of a format string

clippy_lints/src/use_self.rs, tests/ui/use_self.fixed, tests/ui/use_self.rs
Fixes #10371 
changelog: FP: [`use_self`]: do not suggest using `Self` in const generic parameters
=> Do not suggest using Self in const generic parameters

tests/ui/trailing_empty_array.rs
---
The associated rustfmt bug that originally necessitated these skips was resolved a while back, so these are no longer necessary
=> chore: remove unneeded rustfmt skip

clippy_lints/src/exit.rs
=> exit lint: potentualy -> potentially

clippy_lints/src/multiple_unsafe_ops_per_block.rs, tests/ui/multiple_unsafe_ops_per_block.rs, tests/ui/multiple_unsafe_ops_per_block.stderr
fixes #10367
changelog: [`multiple_unsafe_ops_per_block`]: Fix ICE when calling a function-like object in an unsafe block
=> Fix ICE in `multiple_unsafe_ops_per_block`

clippy_lints/src/missing_doc.rs, tests/ui/missing_doc.stderr, tests/ui/missing_doc_impl.stderr
`missing_docs_in_private_items` currently detects missing docs for public items as well as private. Since `missing_docs`already covers public items, this PR updates `missing_docs_in_private_items` to only cover private items.
Fixes #1895 
changelog: [`missing_docs_in_private_items`]: Apply lint only to private items (used to be public and private)
=> Scope `missing_docs_in_private_items` to only private items

clippy_lints/src/functions/mod.rs, clippy_lints/src/methods/mod.rs
The `wrong_self_convention` changes are for grammar and accuracy.
The `must_use_candidate` change is because that lint flags only exported functions: https://github.com/rust-lang/rust-clippy/blob/8b65632b6ef737979d42f83664271d6baa8c0270/clippy_lints/src/functions/must_use.rs#L27-L31
changelog: `wrong_self_convention` and `must_use_candidate` documentation improvements
=> Two small documentation improvements

clippy_lints/src/utils/internal_lints/metadata_collector.rs
I am interested in having a programmatic way to process [`RENAMED_LINTS`](https://github.com/rust-lang/rust-clippy/blob/113c704d225c63c1a0eec29cfa9478b7537e7d73/clippy_lints/src/renamed_lints.rs#L4) for https://github.com/dtolnay/noisy-clippy/issues/15.
<details>
<summary>lints.json diff</summary>
```diff
60c60,63
<     }
---
>     },
>     "former_ids": [
>       "almost_complete_letter_range"
>     ]
300c303,306
<     }
---
>     },
>     "former_ids": [
>       "option_and_then_some"
>     ]
330c336,340
<     }
---
>     },
>     "former_ids": [
>       "block_in_if_condition_expr",
>       "block_in_if_condition_stmt"
>     ]
450c460,463
<     }
---
>     },
>     "former_ids": [
>       "box_vec"
>     ]
945c958,961
<     }
---
>     },
>     "former_ids": [
> …
```
=> Include former name of renamed lints in lints.json

clippy_lints/src/let_underscore.rs
From reading #6842 I am not convinced of the cost/benefit of this lint even as a pedantic lint.
It sounds like the primary motivation was to catch cases of `fn() -> Result` being changed to `async fn() -> Result`. If the original Result was ignored by a `let _`, then the compiler wouldn't guide you to add `.await`. **However, this situation is caught in a more specific way by [let_underscore_future](https://rust-lang.github.io/rust-clippy/master/index.html#let_underscore_future) which was introduced _after_ the original suggestion (#9760).**
In #10410 it was mentioned twice that a <kbd>restriction</kbd> lint might be more appropriate for let_underscore_untyped.
changelog: Moved [`let_underscore_untyped`] to restriction
=> Downgrade let_underscore_untyped to restriction

clippy_lints/src/unit_types/let_unit_value.rs, tests/ui/let_unit.fixed, tests/ui/let_unit.rs
Fix https://github.com/rust-lang/rust-clippy/issues/10433
changelog: Fix FP for `let_unit_value` when `await` used
=> Fix FP for `let_unit_value` when `await` used

lintcheck/Cargo.toml, lintcheck/src/config.rs
Make `cargo lintcheck -j 0` use all threads instead of panicking, and cleanup (and shorten) lintcheck's parsing code.
=> Lintcheck maintenance

clippy_lints/src/dereference.rs, tests/ui/crashes/ice-rust-107877.rs
Fix #10009
Fix #10387
Fix https://github.com/rust-lang/rust/issues/107877
The fix is to verify that the associated item's trait is implemented before trying to project the item's type.
r? @Jarcho
---
changelog: ICE: [`needless_borrow`]: No longer panics on ambiguous projections
[#10403](https://github.com/rust-lang/rust-clippy/pull/10403)
=> Fix rust-lang/rust#107877, etc.

clippy_lints/src/casts/cast_slice_from_raw_parts.rs, clippy_lints/src/default_instead_of_iter_empty.rs, clippy_lints/src/format.rs, clippy_lints/src/implicit_saturating_add.rs, clippy_lints/src/instant_subtraction.rs, clippy_lints/src/len_zero.rs, clippy_lints/src/manual_bits.rs, clippy_lints/src/manual_is_ascii_check.rs, clippy_lints/src/manual_rem_euclid.rs, clippy_lints/src/match_result_ok.rs, clippy_lints/src/neg_multiply.rs, clippy_lints/src/non_octal_unix_permissions.rs, clippy_lints/src/swap.rs, tests/ui/match_result_ok.fixed, tests/ui/match_result_ok.stderr, tests/ui/swap.fixed, tests/ui/swap.stderr
No tests at the moment. Need to find a way to write macro tests without writing a pile of macros.
=> Use `snippet_with_context` more

src/driver.rs, src/main.rs
=> help: refer to `cargo check --help`

CHANGELOG.md, clippy_lints/src/collection_is_never_read.rs, clippy_lints/src/declared_lints.rs, clippy_lints/src/lib.rs, tests/ui/collection_is_never_read.rs, tests/ui/collection_is_never_read.stderr
Fixes #9267
@flip1995 and @llogiq, I talked with you about this one at Rust Nation in London last week. :-)
This is my first contribution to Clippy, so lots of feedback would be greatly appreciated.
- \[ ] Followed [lint naming conventions][lint_naming]
`dogfood` found one true positive (see #9509) and no false positives.
`lintcheck` found no (true or false) positives, even when running on an extended set of crates.
---
changelog: new lint [`collection_is_never_read`]
[#10415](https://github.com/rust-lang/rust-clippy/pull/10415)
=> Add `collection_is_never_read`

lintcheck/Cargo.toml, lintcheck/README.md, lintcheck/src/popular-crates.rs
This program downloads crates info from <https://crates.io/> and builds a TOML file that can be fed to `lintcheck`.
I have been asked, on various pull requests, what the result of `lintcheck` was. However, the default configuration file for lintcheck is limited. This `popular-crates` program allows building a recent list of the recently most downloaded crates from <https://crates.io> and feed it to `lintcheck`. Using it, it was easy to test two new lints against the 500 recently most downloaded crates to ensure that there was no regression.
=> Add the `popular-crates` binary

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/lib.rs, clippy_lints/src/redundant_async_block.rs, tests/ui/async_yields_async.fixed, tests/ui/async_yields_async.rs, tests/ui/async_yields_async.stderr, tests/ui/redundant_async_block.fixed, tests/ui/redundant_async_block.rs, tests/ui/redundant_async_block.stderr, tests/ui/redundant_closure_call_fixable.fixed, tests/ui/redundant_closure_call_fixable.rs, tests/ui/redundant_closure_call_fixable.stderr
Fixes #10444 
changelog: [`redundant_async_block`]: new lint to detect `async { future.await }`
=> Add new `redundant_async_block` lint

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/let_with_type_underscore.rs, clippy_lints/src/lib.rs, tests/ui/crashes/ice-6179.rs, tests/ui/default_numeric_fallback_f64.fixed, tests/ui/default_numeric_fallback_f64.rs, tests/ui/default_numeric_fallback_f64.stderr, tests/ui/default_numeric_fallback_i32.fixed, tests/ui/default_numeric_fallback_i32.rs, tests/ui/default_numeric_fallback_i32.stderr, tests/ui/let_with_type_underscore.rs, tests/ui/let_with_type_underscore.stderr, tests/ui/manual_rem_euclid.fixed, tests/ui/manual_rem_euclid.rs, tests/ui/manual_rem_euclid.stderr
Fixes #10463 
changelog: [`let_with_type_underscore`]: Add the lint.
=> Add `let_with_type_underscore` lint

lintcheck/src/config.rs
Use multithreading unless there is a reason not to.
=> lintcheck: use multithreading unless --fix or --recursive is used

clippy_lints/src/len_zero.rs, tests/ui/len_without_is_empty.rs, tests/ui/len_without_is_empty.stderr
fixes #7232
Changes done to the functionality:
Allowing different error types for the functions was disallowed. So the following was linted before but is not after this change
```
impl Foo {
pub len(&self) -> Result<usize, Error1> { todo!(); }
pub is_empty(&self) -> Result<bool, Error2> { todo!(); }
}
```
---
changelog: Enhancement: [`len_without_is_empty`]: Now also detects `async` functions
[#10359](https://github.com/rust-lang/rust-clippy/pull/10359)
=> Include async functions in the len_without_is_empty

CHANGELOG.md
Roses are red,
this poem is dead,
my creativity is lost,
outside there is frost?
Maybe I should really stop including a "roses are red" with every changelog PR. These are getting worse every time...
---
=> Mark Rust 1.68.0 as release in the changelog

CHANGELOG.md
Roses are red 
Violets are blue
r? @xFrednet is better at this
I can't rhyme. 
https://github.com/rust-lang/rust-clippy/pull/10423
https://github.com/rust-lang/rust-clippy/pull/10265
=> Update changelog for beta-accepted labels

clippy_lints/src/manual_clamp.rs, tests/ui/manual_clamp.rs
fixes #10474
Probably worth including in the sync.
r? @flip1995 
changelog: [`manual_clamp`]: Don't lint in const contexts.
=> Don't lint `manual_clamp` in const contexts.

clippy_lints/src/default.rs, clippy_lints/src/if_then_some_else_none.rs, clippy_lints/src/loops/same_item_push.rs, clippy_lints/src/matches/manual_unwrap_or.rs, clippy_lints/src/matches/match_bool.rs, clippy_lints/src/matches/match_ref_pats.rs, clippy_lints/src/matches/match_single_binding.rs, clippy_lints/src/matches/redundant_pattern_match.rs, clippy_lints/src/matches/single_match.rs, clippy_lints/src/methods/bind_instead_of_map.rs, clippy_lints/src/methods/clone_on_ref_ptr.rs, clippy_lints/src/methods/or_fun_call.rs, clippy_lints/src/misc.rs, clippy_lints/src/needless_bool.rs, clippy_lints/src/option_if_let_else.rs, clippy_lints/src/semicolon_if_nothing_returned.rs, clippy_lints/src/unit_types/let_unit_value.rs, clippy_lints/src/useless_conversion.rs, clippy_utils/src/source.rs, clippy_utils/src/sugg.rs, tests/ui/redundant_pattern_matching_result.fixed, tests/ui/redundant_pattern_matching_result.stderr
`snippet_with_context` is used instead to support nested macro calls.
=> Remove `snippet_with_macro_callsite`

clippy_lints/src/matches/match_single_binding.rs, tests/ui/match_single_binding.fixed, tests/ui/match_single_binding.rs, tests/ui/match_single_binding.stderr, tests/ui/match_single_binding2.fixed, tests/ui/match_single_binding2.stderr
changelog: [`match_single_binding`]: Fix missing semicolon after the suggestion
Fixes #10447
Also fixes an edge case for unit returning macros in expression contexts:
```rust
f(match 1 {
_ => println!("foo"),
});
```
would suggest
```rust
f(println!("foo"););
```
=> Fix semicolon insertion in `match_single_binding`

clippy_lints/src/derive.rs
changelog: fix documentation for `derived_hash_with_manual_eq`
The documentation retained "vice versa" from the previous incarnation of the lint but the lint itself no longer lints against manual `Hash` implementations with a derived `PartialEq`.
I also adjusted the documentation for `PartialOrd`-`Ord` lint as "vice versa" seemed a little confusing to me there (as to what it was refering to exactly.)
=> Fix documentation for `derived_hash_with_manual_eq`

clippy_lints/src/swap.rs, tests/ui/swap.fixed, tests/ui/swap.rs
Fixes `2` in #10421 
changelog: [`almost_swapped`]: Fix false positive when a variable is changed to itself. (`a = a`)
=> Fix `almost_swapped` false positive (`let mut a = b; a = a`)

clippy_lints/src/swap.rs, tests/ui/auxiliary/macro_rules.rs, tests/ui/swap.fixed, tests/ui/swap.rs, tests/ui/swap.stderr
Fixes #10421 ; Related to #10499 (Fixing points *1* and *3* from #10421)
changelog: [`almost_swapped`]: Add a check to ignore external macros
=> fix `almost_swapped`: Ignore external macros

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/lib.rs, clippy_lints/src/manual_main_separator_str.rs, clippy_utils/src/msrvs.rs, clippy_utils/src/paths.rs, tests/ui/manual_main_separator_str.fixed, tests/ui/manual_main_separator_str.rs, tests/ui/manual_main_separator_str.stderr
Fixes #10480 
changelog: [`manual_main_separator_str`] new lint
=> New lint to detect `&std::path::MAIN_SEPARATOR.to_string()`

clippy_lints/src/manual_async_fn.rs, tests/ui/manual_async_fn.fixed, tests/ui/manual_async_fn.rs, tests/ui/manual_async_fn.stderr
Fixes #10450 
changelog: [`manual_async_fn`] output function modifiers in correct order
=> Issue function modifiers in the right order in manual_async_fn lint

CONTRIBUTING.md, triagebot.toml
This corrects the link, where to find which members are currently active and can be pinged. It also adds me as the code owner of `gh-pages`. In most cases, I'm asked to review those PRs anyways :)
Otherwise, not much more to day, have a great day!
---
Closes: #10521
=> Correct active members link in `CONTRIBUTING.md`

clippy_utils/src/ty.rs, tests/ui/uninit.rs, tests/ui/uninit.stderr, tests/ui/uninit_vec.rs, tests/ui/uninit_vec.stderr
rustc has proper heuristics for actually checking whether a type allows being left uninitialized (by asking CTFE). We can now use this for our helper instead of rolling our own bad version with false positives.
I added this in rustc in rust-lang/rust#108669
Fix #10407
changelog: [`uninit_vec`]: fix false positives
changelog: [`uninit_assumed_init`]: fix false positives
=> Use uninit checking from rustc

clippy_lints/src/let_with_type_underscore.rs, clippy_lints/src/manual_async_fn.rs, clippy_lints/src/manual_main_separator_str.rs, clippy_lints/src/redundant_async_block.rs, clippy_lints/src/swap.rs, clippy_lints/src/wildcard_imports.rs, tests/dogfood.rs
The dogfood success condition was inverted in `tests/dogfood.rs`:
```rust
assert!(!failed_packages.is_empty(), …);
```
while instead the `failed_packages` collection must be empty:
```rust
assert!(failed_packages.is_empty(), …);
```
And indeed, several clippy lint source files were not clean and had to be fixed in the process.
=> Really dogfood clippy

clippy_lints/src/redundant_async_block.rs, tests/ui/redundant_async_block.fixed, tests/ui/redundant_async_block.rs, tests/ui/redundant_async_block.stderr
Fixes #10482 
changelog: FP [`redundant_async_block`] Do not propose to remove `async move` if variables are captured by ref
=> Do not propose to remove `async move` if variables are captured by ref

clippy_lints/src/booleans.rs, tests/ui/nonminimal_bool.rs
Fixes #10523 
changelog: FP [`nonminimal_bool`]: do not propose to change code coming from a macro
=> Do not propose to simplify a not expression coming from a macro

clippy_lints/src/significant_drop_tightening.rs
The lint is very slow as it doesn't cache the deeply nested check for the attribute. If we cache it, we can reduce the time spent on checking `rustc_borrowck` from 28s to 9s, which is a nice improvement. In the profile, the time inside `has_sig_drop_attr` goes from 66% to 0.2%, which is a lot more reasonable.
<details>
<summary>Flame graphs</summary>
Before (all the tall `clippy` towers are `has_sig_drop_attr`):
After:
</details>
Fixes #10532
changelog: [`significant_drop_tightening`]: significantly optimized
=> Significantly optimize `significant_drop_tightening`

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/lib.rs, clippy_lints/src/unnecessary_struct_initialization.rs, tests/ui/needless_update.rs, tests/ui/no_effect.rs, tests/ui/no_effect.stderr, tests/ui/unnecessary_operation.fixed, tests/ui/unnecessary_operation.rs, tests/ui/unnecessary_operation.stderr, tests/ui/unnecessary_struct_initialization.fixed, tests/ui/unnecessary_struct_initialization.rs, tests/ui/unnecessary_struct_initialization.stderr
Fixes #10476.
Running this lint on the top 500 crates produced one hit (in `rust-lang/rust-bindgen`) and [a PR has been submitted there](https://github.com/rust-lang/rust-bindgen/pull/2440).
changelog: [`unnecessary_struct_initialization`]: new lint
=> New lint: detect unnecessary struct building

.cargo/config.toml, .github/workflows/clippy_bors.yml
On Windows this has no effect as it's unsupported. On macOS the default set by cargo is already unpacked so no effect there either
For Linux it shaves a bit off the rebuild time, for me in the case of a simple `touch` + `cargo build` it goes from 12s to 10s
It saves a good amount of disk space too, on `aarch64-unknown-linux-gnu` it saves 1.2GB for a plain `cargo build`, 3GB when also running `cargo dev` and `cargo test --no-run -F internal`
r? @flip1995
=> Use `split-debuginfo = "unpacked"` for debug builds

clippy_lints/src/disallowed_script_idents.rs
changelog: [`DISALLOWED_SCRIPT_IDENTS`]: Replace the nonexistent `allowed-locales` in the docs with `allowed-scripts`.
=> docs fix: unknown field `allowed-locales`

clippy_lints/src/transmute/transmutes_expressible_as_ptr_casts.rs, tests/ui/transmutes_expressible_as_ptr_casts.fixed, tests/ui/transmutes_expressible_as_ptr_casts.rs, tests/ui/transmutes_expressible_as_ptr_casts.stderr
changelog: [`transmutes_expressible_as_ptr_casts`]: Fix suggestion missing wrapping parentheses
Fixes #10449
r? @Jarcho
Is this the best way to go about this? `unused_parens` will catch the unnecessary ones but emitting them in the first place isn't ideal
=> Wrap `transmutes_expressible_as_ptr_casts` suggestions in parentheses

clippy_lints/src/casts/cast_possible_truncation.rs, tests/ui/cast.rs, tests/ui/cast.stderr
fixes: #10366 
---
changelog: [`cast_possible_truncation`] Fix incorrect suggestions when casting from float types or to `_`
=> fix [`cast_possible_truncation`] offering wrong suggestion for casting float to integer

clippy_lints/src/unnecessary_struct_initialization.rs
changelog: none, assuming it makes into the same release as #10489
Mostly because of #10547 but there is also #10548
=> Move unnecessary_struct_initialization to nursery

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/methods/clear_with_drain.rs, clippy_lints/src/methods/iter_with_drain.rs, clippy_lints/src/methods/mod.rs, clippy_utils/src/lib.rs, tests/ui/clear_with_drain.fixed, tests/ui/clear_with_drain.rs, tests/ui/clear_with_drain.stderr
changelog: [`clear_with_drain`]: Add new lint
Fixes #9339
=> Clear with drain

clippy_lints/src/items_after_statements.rs, clippy_lints/src/lib.rs, tests/ui/items_after_statement.rs, tests/ui/items_after_statement.stderr
Fixes #10540
changelog: [`items_after_statements`]: Fixes `#[allow(clippy::items_after_statements)]` when applied to an item, and ignores items after statements from different macro contexts
=> Fix allow attribute, items from macros in `items_after_statements`

clippy_lints/src/explicit_write.rs, clippy_lints/src/format.rs, clippy_lints/src/format_impl.rs, clippy_lints/src/methods/expect_fun_call.rs, clippy_utils/src/lib.rs, clippy_utils/src/macros.rs
Closes #10233
Removes `FormatArgsExpn` & friends now that they're unused
=> Replace remaining usage of `FormatArgsExpn`

clippy_utils/src/ty.rs, tests/ui/uninit.rs, tests/ui/uninit.stderr, tests/ui/uninit_vec.rs
After #10520, we always assumed that polymorphic types do not allow to be left uninitialized. But we can do better, by peeking into polymorphic types and adding a few special cases for going through tuples, arrays (because the length may be polymorphic) and blanket allowing all unions (like MaybeUninit).
fixes #10551
changelog: [uninit_vec]: fix false positive for polymorphic types
changelog: [uninit_assumed_init]: fix false positive for polymorphic types
=> In uninit checking, add fallback for polymorphic types

README.md, book/src/README.md, book/src/configuration.md, book/src/development/README.md, book/src/development/adding_lints.md, book/src/development/basics.md, book/src/development/common_tools_writing_lints.md, book/src/development/infrastructure/book.md, book/src/development/infrastructure/changelog_update.md, book/src/development/infrastructure/release.md, book/src/development/infrastructure/sync.md, book/src/development/proposals/README.md, book/src/development/proposals/roadmap-2021.md, book/src/development/proposals/syntax-tree-patterns.md, book/src/installation.md, book/src/lint_configuration.md, book/src/lints.md, book/src/usage.md, clippy_lints/src/utils/conf.rs, etc/relicense/RELICENSE_DOCUMENTATION.md, lintcheck/README.md
A few minor cleanups in various markdown files, mostly focusing on spelling and ignoring non-compilable codeblocks. Also a few markdown tables, etc.
P.S. I'm no grammar expert, do take with a grain of salt.
=> Gramar, and spelin kleanup

clippy_lints/src/extra_unused_type_parameters.rs, tests/ui-toml/extra_unused_type_parameters/clippy.toml, tests/ui-toml/extra_unused_type_parameters/extra_unused_type_parameters.rs, tests/ui/extra_unused_type_parameters.fixed, tests/ui/extra_unused_type_parameters.stderr, tests/ui/extra_unused_type_parameters_unfixable.rs, tests/ui/extra_unused_type_parameters_unfixable.stderr
Change the `extra_unused_type_parameters` lint to provide machine applicable suggestions rather than just help messages. Exception to this are cases when any unused type parameters appear bounded in where clauses - for now I've deemed these cases unfixable and separated them out. Future work might be able to provide suggestions in these cases.
Also, added a test case for the `avoid_breaking_exported_api` config option.
r? @flip1995 
changelog: [`extra_unused_type_parameters`]: Now provides fixable suggestions.
=> Add suggestions to `extra_unused_type_parameters`

clippy_lints/src/operators/arithmetic_side_effects.rs, tests/ui/arithmetic_side_effects.rs, tests/ui/arithmetic_side_effects.stderr
Fixes #10583
```
changelog: [`arithmetic_side_effects`]: Correctly handle division and module when the right-hand-side is unknown
```
=> [arithmetic_side_effects] Fix #10583 

clippy_dev/src/new_lint.rs, clippy_dev/src/update_lints.rs, tests/ui/format_args_unfixable.rs, tests/ui/format_args_unfixable.stderr, tests/ui/uninlined_format_args.fixed, tests/ui/uninlined_format_args.rs
This contains some prep work for #9948 to keep that change to the minimum, and make it easier to review it.
This should be a noop, but it has some tests from that PR discussion, and should help in the future with the corner case format handling.
cc: @Alexendoo @llogiq @xFrednet  as the 3 people who reviewed the parent PR
----
=> Partial no-op refactoring of #9948

clippy_lints/src/booleans.rs, tests/ui/nonminimal_bool.rs
Closes #10435 
changelog: [`nonminimal_bool`]: Fix false-positive where the lint ignore `#[allow]` attributes.
r? @llogiq
=> Fix `nonminimal_bool` `#[allow]` attributes.

book/src/development/infrastructure/sync.md
Companion PR to https://github.com/rust-lang/rustc-dev-guide/pull/1653. That still keeps a `contributing.html` with an "External Contributions" section, so hopefully it won't be too disruptive.
=> Update subtree sync docs for changes in rustc-dev-guide

book/src/configuration.md
It is possible to use conditional compilation to prevent Clippy from evaluating certain code at all. Unfortunately, it was no longer documented anywhere. This adds a brief explanation of how to use the feature with conditional compilation, and mentions a few downsides.
Fixes #10220 — Ability to skip files or blocks entirely
=> Document `cargo-clippy` feature

clippy_lints/src/lib.rs, clippy_lints/src/utils/conf.rs, src/driver.rs, tests/ui-cargo/multiple_config_files/warn/src/main.stderr
Use `sess.warn` to display the multiple clippy.toml warning instead of `eprintln!`.
=> Show multiple clippy.toml warnings with `sess.warn` instead of `eprintln!`

clippy_lints/src/utils/conf.rs
Currently `lookup_conf_file` doesn't canonicalize the configuration directory before using [`PathBuf::pop`](https://doc.rust-lang.org/std/path/struct.PathBuf.html#method.pop) to get the parent directory. This isn't usually an issue when clippy is invoked via `cargo clippy` as `CARGO_MANIFEST_DIR` is already canonicalized. However, this currently causes `clippy-driver` to ignore any `clippy.toml` in any parent directories when  `CARGO_MANIFEST_DIR` and `CLIPPY_CONF_DIR` are not set.
changelog: Fix a bug that would cause parent directories not to be searched for `clippy.toml` when using `clippy-driver` directly.
=> Fix bug with getting parent directories in `lookup_conf_file`

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/lib.rs, clippy_lints/src/tests_outside_test_module.rs, tests/ui/tests_outside_test_module.rs, tests/ui/tests_outside_test_module.stderr
Adds `tests_outside_test_module` from #10506. This PR **doesn't** close the issue, just resolves task 1.
changelog: [`tests_outside_test_module`]: The lint has been added
=> Add `tests_outside_test_module` lint

clippy_lints/src/lib.rs, clippy_lints/src/redundant_async_block.rs, tests/ui/redundant_async_block.fixed, tests/ui/redundant_async_block.rs, tests/ui/redundant_async_block.stderr
This lets us detect more complex situations: `async { x.await }` is simplified into `x` if:
- `x` is an expression without side-effect
- or `x` is an `async` block itself
In both cases, no part of the `async` expression can be part of a macro expansion.
Fixes #10509.
Fixes #10525. 
changelog: [`redundant_async_block`] Do not lint expressions with side effects.
=> Make redundant_async_block a more complete late pass

clippy_lints/src/mem_replace.rs, tests/ui/mem_replace.fixed, tests/ui/mem_replace.rs, tests/ui/mem_replace.stderr
fixes: #9824 
---
changelog: fix [`mem_replace_option_with_none`] not considering field variables
=> fix [`mem_replace_option_with_none`] not considering field variables

clippy_lints/src/single_component_path_imports.rs, tests/ui/single_component_path_imports.fixed, tests/ui/single_component_path_imports.rs, tests/ui/single_component_path_imports.stderr
fixes #10549
I noticed that a couple functions in the file I was working on took `cx` as a parameter but didn't use them, so I removed that. Can revert if desired because it isn't related to my changes.
changelog: [`single_component_path_imports`] don't suggest removing import when it is used as `self::<import>::..`
=> fix `single_component_path_imports` FP on `self::<import>::..`

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/lib.rs, clippy_lints/src/manual_slice_size_calculation.rs, tests/ui/manual_slice_size_calculation.rs, tests/ui/manual_slice_size_calculation.stderr
Fixes: #10518
---
changelog: new lint [`manual_slice_size_calculation`]
=> Add [`manual_slice_size_calculation`]

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/lib.rs, clippy_lints/src/suspicious_doc_comments.rs, tests/ui/suspicious_doc_comments.fixed, tests/ui/suspicious_doc_comments.rs, tests/ui/suspicious_doc_comments.stderr, tests/ui/suspicious_doc_comments_unfixable.rs, tests/ui/suspicious_doc_comments_unfixable.stderr
Fixes #10485.
This PR adds a new lint (`suspicious_doc_comments`) that triggers when the user writes `///!` or `/**!`.
This is almost certainly a mistake and the user probably meant to write an inner doc comment (`//!`, `/*!`) to document the module or crate that this comment is contained in.
changelog: [`suspicious_doc_comments`]: new lint
=> new lint: suspicious_doc_comments

book/src/development/adding_lints.md, book/src/usage.md
rust-lang/rust#110003's CI is [currently broken](https://github.com/rust-lang/rust/actions/runs/4628510374/jobs/8187672234?pr=110003) because of broken links. This PR fixes that.
It was tested against `lintcheck` and found another broken link in `usage.md` (apart from CI's broken links)
changelog:Fix broken links in the book
Sorry for putting more work on you, but you're the one doing the Rust PR
r? @flip1995
=> (Small) Fix broken links for Rust merge

book/src/SUMMARY.md, book/src/development/type_checking.md
This PR adds a new chapter to the book: "Type Checking", it hasn't changed a lot from the source mainly because there wasn't many reviews on it and I haven't see a lot of things that needed a change.
- I have some doubts about the whole "`is_*` Usage" section, what do you think about it.
- For discussion about  the whole project, please use the tracking issue for the project #10597 (It also contains a timeline, discussions, and more information)
changelog: Add a new "Type Checking" chapter to the book
r? @flip1995
=> Clippy Book Chapter Updates Reborn: Type Checking

.editorconfig
Add `max_line_length` to `.editorconfig` to match the `max_width` in `rustfmt.toml`.
=> Add `max_line_length` to `.editorconfig`, matching `rustfmt.toml`

clippy_lints/src/missing_const_for_fn.rs
changelog: [`missing_const_for_fn`] note about removing const may break compatibility
fix #7121
=> [missing_const_for_fn] fix #7121

clippy_lints/src/lib.rs
The unstable feature does not appear to be used and its presence blocks work in https://github.com/rust-lang/rust/pull/104455
=> remove unusued `#![feature(drain_filter)]`

clippy_lints/src/returns.rs, tests/ui/needless_return.fixed, tests/ui/needless_return.rs, tests/ui/needless_return.stderr
If we see a case where match returns something other than `()`, we just skip `needless_return` lint in that case
Should fix #10546
Relevant Zulip Discussion: https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Issue.20.2310546
---
changelog: FP: [`needless_return`]: No longer lints match statements with incompatible branches
[#10593](https://github.com/rust-lang/rust-clippy/pull/10593)
=> fix(needless_return): do not trigger on ambiguous match arms return

clippy_lints/src/collection_is_never_read.rs, tests/ui/collection_is_never_read.rs, tests/ui/collection_is_never_read.stderr
changelog: [`collection_is_never_read`]: Fix false negative
fixes: #10488
=> `collection_is_never_read`: Handle unit type

Cargo.toml, declare_clippy_lint/Cargo.toml, declare_clippy_lint/src/lib.rs, tests/ui/auxiliary/proc_macro_attr.rs, tests/ui/needless_arbitrary_self_type_unfixable.stderr
=> bump syn to 2.0

clippy_lints/src/allow_attributes.rs, clippy_lints/src/casts/mod.rs, clippy_lints/src/crate_in_macro_def.rs, clippy_lints/src/entry.rs, clippy_lints/src/format_impl.rs, clippy_lints/src/formatting.rs, clippy_lints/src/lines_filter_map_ok.rs, clippy_lints/src/manual_bits.rs, clippy_lints/src/matches/mod.rs, clippy_lints/src/methods/mod.rs, clippy_lints/src/mutex_atomic.rs, clippy_lints/src/non_copy_const.rs, clippy_lints/src/operators/mod.rs, clippy_lints/src/types/mod.rs, clippy_lints/src/utils/internal_lints/unnecessary_def_path.rs, clippy_lints/src/write.rs
Fixes #10631 
changelog: Standardize a very frequent lint formulation which had variations
=> Standardize lint formulation

clippy_lints/src/casts/mod.rs
Fixes #10628
There's no `String::as_mut_ptr` surprisingly, so the example is actually calling `str::as_mut_ptr` on an empty `str`
=> Fix UB in `as_ptr_cast_mut` documentation

clippy_lints/src/octal_escapes.rs, tests/ui/octal_escapes.rs, tests/ui/octal_escapes.stderr
The code consumed characters to inspect them when it should have been peeking. This led to both false negatives (which even had a test case, sigh), and false positives for which I added a test.
I also deferred suggestion generation to not run if the lint is disabled, and disabled it altogether for strings longer than 400 bytes (we have some generated 5MB bytes strings that make clippy take 5 hours to generate the suggestions).
changelog: fix false positives and false negatives in `octal_escapes`
=> Fix false positives and false negatives in `octal_escapes`

book/src/SUMMARY.md, book/src/development/README.md, book/src/development/lint_passes.md, book/src/development/type_checking.md
- Adds the lint passes chapter to the index.
- Moves additional reading material for beginners to the front page of the development section.
- Clarify some details in `hir::Ty` vs `ty::Ty`.
@blyxyas I started reviewing the chapters that were already merged. Great work. I liked the additional reading chapter so much, that I moved it front and center. Other than that I only had some minor corrections to make. Please review.
r? @llogiq 
=> Book: Improve type checking and lint passes chapters

book/src/SUMMARY.md, book/src/development/macro_expansions.md
This PR adds a new chapter to the book: "Macro Expansions". There weren't big changes apart from grammar, re-phrasing and stylistic choices.
- **Does not require any other chapter** to be merged before this
- To talk about the whole project, please use the tracking issue for the project #10597 (It also contains a timeline, discussions and more information)
changelog: Add a new "Macro Expansions" chapter to the book
r? @flip1995
=> Clippy Book Chapter Updates Reborn: Macro Expansions

clippy_lints/src/manual_slice_size_calculation.rs, tests/ui/manual_slice_size_calculation.fixed, tests/ui/manual_slice_size_calculation.stderr
Continuation of https://github.com/rust-lang/rust-clippy/pull/10659#issuecomment-1511688869.
This adds applicable suggestions to the `manual_slice_size_calculation` lint:
```
error: manual slice size calculation
--> $DIR/manual_slice_size_calculation.rs:11:13
|
LL |     let _ = s_i32.len() * size_of::<i32>(); // WARNING
|             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `std::mem::size_of_val(s_i32)`
|
= note: `-D clippy::manual-slice-size-calculation` implied by `-D warnings`
```
changelog: [`manual_slice_size_calculation`]: add machine applicable suggestion
=> Add `manual_slice_size_calculation` applicable suggestion

clippy_lints/src/manual_slice_size_calculation.rs, tests/ui/manual_slice_size_calculation.fixed, tests/ui/manual_slice_size_calculation.rs, tests/ui/manual_slice_size_calculation.stderr
changelog: none, assuming same release as #10659
=> Ignore `manual_slice_size_calculation` in code from macro expansions

CHANGELOG.md, clippy_lints/src/functions/mod.rs, clippy_lints/src/methods/mod.rs, clippy_lints/src/multiple_unsafe_ops_per_block.rs, clippy_lints/src/question_mark_used.rs, clippy_lints/src/significant_drop_tightening.rs
Roses are blue,
Violets are red,
Something is wrong,
We still commit!
---
=> Changelog for Rust 1.69 :cherry_blossom:

clippy_lints/src/operators/arithmetic_side_effects.rs, tests/ui/arithmetic_side_effects.rs, tests/ui/arithmetic_side_effects.stderr
Fix #10590 
changelog: [`arithmetic_side_effects`]: Detect integer methods that can introduce side effects
=> [arithmetic_side_effects] Fix #10590 

clippy_lints/src/operators/arithmetic_side_effects.rs
An internal-only modification to speed up the processing of symbols because "intern" isn't very cheap, even more when you are doing the same thing for every method expression.
=> [arithmetic_side_effects] Cache symbols

clippy_lints/src/enum_variants.rs, tests/ui/enum_variants.rs
changelog: [`enum_variant_names`]: Fix `#[allow]` attributes applied directly to the enum variant
Fixes #10695
=> Fix `#[allow(clippy::enum_variant_names)]` directly on variants

clippy_lints/src/len_zero.rs, tests/ui/len_zero.fixed, tests/ui/len_zero.rs, tests/ui/len_zero.stderr
sorry it should be a quick fix but I was caught up by other stuffs last couple weeks :man_facepalming: 
---
fixes: #10529 
changelog: make [`len_zero`] lint not spanning over parenthesis
=> make [`len_zero`] lint not spanning over parenthesis

Cargo.toml
Drop unused `semver` crate dependency.
=> clippy: drop unused semver crate

clippy_lints/src/let_underscore.rs, tests/ui/let_underscore_untyped.rs, tests/ui/let_underscore_untyped.stderr
Fixes #10411
changelog:[`let_underscore_untyped`]: Ignore `impl Trait`(s) that caused false positives.
=> Bugfix: Ignore `impl Trait`(s) @ `let_underscore_untyped`

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/items_after_test_module.rs, clippy_lints/src/lib.rs, tests/ui/items_after_test_module.rs, tests/ui/items_after_test_module.stderr
Resolves task *3* of #10506, alongside *1* resolved at #10543 in an effort to help standarize a little bit more testing modules.
---
changelog:[`items_after_test_module`]: Added the lint.
=> Add `items_after_test_module` lint

clippy_lints/src/floating_point_arithmetic.rs, tests/ui/floating_point_arithmetic_nostd.rs
Fixes #10634
changelog: Enhancement: [`suboptimal_flops`]: Do not suggest `{f32,f64}::abs()` or `{f32,f64}::mul_add()` in a `no_std`-environment.
=> Don't suggest `suboptimal_flops` unavailable in nostd

clippy_utils/src/lib.rs, tests/ui/bool_to_int_with_if.fixed, tests/ui/bool_to_int_with_if.rs, tests/ui/bool_to_int_with_if.stderr
Fixes #10452.
This PR improves the `in_constant` util function to detect more cases of const contexts. Previously this function would not detect cases like expressions in array length position or expression in an inline const block `const { .. }`.
changelog: [`bool_to_int_with_if`]: recognize array length operand as being in a const context and don't suggest `usize::from` there
=> use `is_inside_const_context` for `in_constant` util fn

clippy_dev/src/update_lints.rs
The transition period has well passed
=> Remove check for `lib.register_*` and `src/docs*` in `cargo dev update_lints`

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/needless_bool.rs, tests/ui/needless_bool_assign.fixed, tests/ui/needless_bool_assign.rs, tests/ui/needless_bool_assign.stderr
Closes #10430
changelog: [`needless_bool_assign`] new lint to detect simple boolean assignment to the same target in `if` branches
=> New lint: detect `if` expressions with simple boolean assignments to the same target

clippy_lints/src/shadow.rs, tests/ui/shadow.rs, tests/ui/shadow.stderr
This PR fixes https://github.com/rust-lang/rust-clippy/issues/9757
I am in doubt if just looking for `pat.span.from_expansion()` would be sufficient instead of looking for both `pat.span.desugaring_kind().is_some()` or `pat.span.from_expansion()`. The tests (including the new one) passes if I leave the only `if pat.span.from_expansion()`. Any feedbacks?
Also, this is my first PR here, sorry for anything and thanks for the patience!
changelog: [`shadow_same`, `shadow_reuse`, `shadow_unrelated`]: avoiding warns in macro-generated code
=> Ignore `shadow` warns in code from macro expansions

clippy_lints/src/allow_attributes.rs, tests/ui/allow_attributes_false_positive.rs
This would emit a warning if used in a proc-macro with the feature `lint_reasons` enabled. This is now fixed.
changelog: [`allow_attributes`]: Don't lint if in external macro
=> Fix false positive in `allow_attributes`

clippy_lints/src/indexing_slicing.rs, clippy_lints/src/matches/redundant_pattern_match.rs, tests/ui/redundant_pattern_matching_option.fixed, tests/ui/redundant_pattern_matching_option.rs, tests/ui/redundant_pattern_matching_option.stderr
The `redundant_pattern_matching` lint currently checks for `if let Some(_) = ...`, but not for `if let Some(..) = ...`.
This PR makes sure to also check for the `..` pattern in tuple structs.
It also found one such instance in clippy itself so that shows it's worth checking for this pattern as well 😅
changelog: [`redundant_pattern_matching`]: check for `..` pattern in tuple structs
=> check for `..` pattern in `redundant_pattern_matching`

clippy_lints/src/let_underscore.rs, tests/ui/let_underscore_untyped.stderr
This would close #10410, because it applies the general consensus achieved in that issue (that replacing `let _ = ...` to `_ = ...` doesn't present any benefits).
I also added a little help message span.
changelog:[`let_underscore_untyped`]: Fix the help message confusion + add a help message span.
=> Improve the help message + add a help span

clippy_lints/src/strings.rs, tests/ui/auxiliary/macro_rules.rs, tests/ui/string_lit_as_bytes.fixed, tests/ui/string_lit_as_bytes.rs, tests/ui/string_lit_as_bytes.stderr
The following code will emit a warning on both w! and h!, despite there being nothing the user (or library author) could do about it:
```rust
#![warn(clippy::string_lit_as_bytes)]
use windows::w;
use windows::h;
fn main() {
let _w = w!("example");
let _h = h!("example");
}
```
This is because windows-rs will create a binding `const INPUT: &[u8] = $s.as_bytes()`, and changing this to b"$s" is, well, suboptimal. I don't know enough about Rust to know if this is something that can be detected though if it can be I'm happy with closing this in favor of implementing that.
I'm not sure whether this is how it should be done though, as this simply tells clippy to not invoke this even if it's applicable (this also affects the other string lints, but didn't cause any tests to fail).
changelog: …
=> Don't apply `string_lit_as_bytes` if in macro expansion

README.md, book/src/usage.md, lintcheck/README.md, src/main.rs
In [`cargo fix`'s documentation](https://doc.rust-lang.org/cargo/commands/cargo-fix.html) they indicate that `fix` implies `--all-targets` if no target is supplied. As Clippy uses Cargo under the hood, this also applies to Clippy, but we didn't document that behaviour.
This PR changes that
Fixes #10690 
changelog: Add to documentation that `--fix` implies `--all-targets`
=> Document that `cargo clippy --fix` implies `--all-targets`

.github/workflows/remark.yml, book/src/development/lint_passes.md
fixes #10711
changelog: Run [linkcheck.sh](https://github.com/rust-lang/rust/blob/master/src/tools/linkchecker/linkcheck.sh) from rustc repo in Remark.yml to check Clippy book.
=> run linkcheck in clippy ci

clippy_lints/src/floating_point_arithmetic.rs
Really small fix.
Fixes #10728
changelog: [`imprecise_flops`]: Fix false positives with `#[no_std]`
=> `imprecise_flops`: Globally ignore `#[no_std]` crates

clippy_lints/src/default_constructed_unit_structs.rs, tests/ui/default_constructed_unit_structs.fixed, tests/ui/default_constructed_unit_structs.rs, tests/ui/default_constructed_unit_structs.stderr
changelog: none, should be the same release as the lint itself
=> Ignore expressions from macros in `default_constructed_unit_structs`

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/lib.rs, clippy_lints/src/misc.rs, clippy_lints/src/ref_patterns.rs, tests/ui/ref_patterns.rs, tests/ui/ref_patterns.stderr
This implements a new lint that discourages the use of the `ref` keyword as outlined in #9010. I think there are still some things to improve about this lint, but I need some feedback before I can implement those.
Any help with these would be greatly appreciated.
fixes #9010 
changelog: [`ref_patterns`]: newly added lint
=> initial clippy::ref_patterns implementation

clippy_lints/src/borrow_deref_ref.rs, tests/ui/borrow_deref_ref.fixed, tests/ui/borrow_deref_ref.rs, tests/ui/borrow_deref_ref.stderr
Don't linting `borrow_deref_ref` if code was generated by procedural macro.
This PR fixes https://github.com/rust-lang/rust-clippy/issues/8971
changelog: [`borrow_deref_ref`] avoiding warnings in macro-generated code
=> Ignore `borrow_deref_ref` warnings in code from procedural macros.

clippy_lints/src/trait_bounds.rs, tests/ui/trait_duplication_in_bounds.fixed, tests/ui/trait_duplication_in_bounds.rs, tests/ui/trait_duplication_in_bounds.stderr
This PR extends `trait_duplication_in_bounds` to cover trait objects.
Currently,
```rs
fn foo(_a: &(dyn Any + Send + Send)) {}
```
generates no warnings. With this PR, it will complain about a duplicate trait and can remove it
Moved from rust-lang/rust#110991
changelog: [`trait_duplication_in_bounds`]: warn on duplicate trait object constraints
=> Extend `trait_duplication_in_bounds` to cover trait objects

clippy_lints/src/lib.rs, clippy_lints/src/utils/conf.rs, clippy_lints/src/utils/internal_lints/metadata_collector.rs, clippy_lints/src/utils/mod.rs
This PR rearranges some modules, taking `metadata_collector` out of `internal_lints` and making public just the necessary functions for `explain()` to use.
The output looks something like this:
```sh
$ cargo run --bin cargo-clippy --manifest-path ../rust-clippy/Cargo.toml -- --explain cognitive_complexity
Checks for methods with high cognitive complexity.
Methods of high cognitive complexity tend to be hard to
both read and maintain. Also LLVM will tend to optimize small methods better.
Sometimes it's hard to find a way to reduce the
complexity.
You'll see it when you get the warning.
========================================
Configuration for clippy::cognitive_complexity:
- cognitive-complexity-threshold: The maximum cognitive complexity a function can have (default: 25)
```
Fixes #9990 …
=> Add configuration options to `--explain`

clippy_lints/src/needless_bool.rs, tests/ui/needless_bool/fixable.fixed, tests/ui/needless_bool/fixable.rs, tests/ui/needless_bool/fixable.stderr
Fix #10710
changelog: [`needless_bool`]: do not simplify code if it loses comments
=> needless_bool: do not simplify code if it loses comments

CHANGELOG.md, clippy_lints/src/attrs.rs, clippy_lints/src/declared_lints.rs, tests/ui/empty_line_after_doc_comments.rs, tests/ui/empty_line_after_doc_comments.stderr
changelog: [`empty_line_after_doc_comments`]: add lint for checking empty lines after rustdoc comments.
Fixes: #10395
=> fix: warn on empty line outer AttrKind::DocComment

clippy_lints/src/useless_conversion.rs, clippy_utils/src/lib.rs, tests/ui/useless_conversion.fixed, tests/ui/useless_conversion.rs, tests/ui/useless_conversion.stderr
Fixes #10773
changelog: Enhancement: [`useless_conversion`]: Don't lint on type aliases
=> Don't emit clippy::useless_conversion on type aliases

triagebot.toml
A step I was trying to avoid for way too long, but sadly necessary now. I hope I can come back stronger in a few months.
More explanation on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Stepping.20back.20from.20review.20rotation/near/358384096)
=> flip1995: Stepping down from the reviewer rotation

clippy_lints/src/manual_let_else.rs, tests/ui/manual_let_else.rs, tests/ui/manual_let_else.stderr, tests/ui/manual_let_else_match.stderr
Fix https://github.com/rust-lang/rust-clippy/issues/10171
---
changelog: Sugg: [`manual_let_else`]: Now suggest the correct variable name
[#10175](https://github.com/rust-lang/rust-clippy/pull/10175)
=> Use original variable name in the suggestion

clippy_lints/src/option_if_let_else.rs, tests/ui/option_if_let_else.fixed, tests/ui/option_if_let_else.rs, tests/ui/option_if_let_else.stderr
This addresses a bug in Clippy where the fix suggestend by the `option_if_let_else` lint would not compile for `Result`s which have an impure expression in the `else` branch.
---
changelog: [`option_if_let_else`]: Fixed incorrect suggestion for `Result`s
[#10337](https://github.com/rust-lang/rust-clippy/pull/10337)
Fixes #10335.
=> Fix: Some suggestions generated by the option_if_let_else lint did not compile

clippy_lints/Cargo.toml, clippy_lints/src/regex.rs, tests/ui/regex.rs, tests/ui/regex.stderr
fixes: #10680 
---
changelog: fix [`invalid_regex`] not recognizing new syntax introduced after regex-1.8.0
bump up `regex-syntax` dependency version to 0.7.0
=> fix [`invalid_regex`] not recognizing new syntax introduced after regex-1.8.0

clippy_lints/src/let_underscore.rs, tests/ui/let_underscore_untyped.rs, tests/ui/let_underscore_untyped.stderr
Don't linting let_underscore_untyped if code was generated by procedural macro.
This PR fixes https://github.com/rust-lang/rust-clippy/issues/10723
---
closes: https://github.com/rust-lang/rust-clippy/issues/10723
changelog: Fix: [`let_underscore_untyped`]: No longer lints inside proc macros
[#10775](https://github.com/rust-lang/rust-clippy/pull/10775)
=> Ignoring `let_underscore_untyped` warnings in code from proc macros

clippy_lints/src/methods/mod.rs
The example for [clippy::needless_collect](https://rust-lang.github.io/rust-clippy/master/#needless_collect) is written as follows:
```rust
let len = iterator.clone().collect::<Vec<_>>().len();
// should be
let len = iterator.count();
```
With this change, the unnecessary `clone()` is removed and the the standard
```rust
// original
```
Use instead:
```rust
// improved
```
structure is followed.
Discussion: https://github.com/rust-lang/rust-clippy/discussions/10784#discussion-5198885
changelog: [`needless_collect`]: Cleaned up the example in the lint documentation.
=> Remove unnecessary `clone` from `needless_collect` example

clippy_lints/src/strings.rs
=> fix example heading in `string_slice`

clippy_lints/src/dbg_macro.rs, tests/ui/dbg_macro.rs, tests/ui/dbg_macro.stderr
Fixes #9914
The `dbg_macro` lint replaces empty `dbg!` invocations with the empty string in its suggestion, which is not always valid code in certain contexts (e.g. `let _ = dbg!();` becomes `let _ = ;`). This PR changes it to `()`, which should always be valid where `dbg!()` is valid (`dbg!()` with no arguments evaluates to `()`).
It also special-cases "standalone" `dbg!();` expression statements, where it will suggest removing the whole statement entirely like it did before.
changelog: [`dbg_macro`]: don't remove `dbg!()` in arbitrary expressions as it sometimes results in syntax errors
=> don't remove `dbg!` in arbitrary expressions

clippy_lints/src/matches/match_like_matches.rs, clippy_lints/src/matches/redundant_pattern_match.rs, tests/ui/match_expr_like_matches_macro.fixed, tests/ui/match_expr_like_matches_macro.stderr, tests/ui/redundant_pattern_matching_option.fixed, tests/ui/redundant_pattern_matching_option.rs, tests/ui/redundant_pattern_matching_option.stderr, tests/ui/redundant_pattern_matching_result.fixed, tests/ui/redundant_pattern_matching_result.rs, tests/ui/redundant_pattern_matching_result.stderr
This PR try to solve this issue https://github.com/rust-lang/rust-clippy/pull/10726, 
but it enter in conflict with another test.
Try to test this:
```
let _w = match x {
Some(_) => true,
_ => false,
};
```
this happen:
```
error: match expression looks like `matches!` macro
--> $DIR/match_expr_like_matches_macro.rs:21:14
|
LL |       let _w = match x {
|  ______________^
LL | |         Some(_) => true,
LL | |         _ => false,
LL | |     };
| |_____^ help: try this: `matches!(x, Some(_))`
+error: redundant pattern matching, consider using `is_some()`
+  --> $DIR/match_expr_like_matches_macro.rs:21:14
+   |
+LL |       let _w = match x {
+   |  ______________^
+LL | |         Some(_) => true,
+LL | |         _ => false,
+LL | |     };
+   | |_____^ help: try this: …
```
=> redundant_pattern_matching

clippy_lints/src/box_default.rs, clippy_lints/src/let_underscore.rs, tests/ui/box_default.fixed, tests/ui/box_default.rs, tests/ui/box_default.stderr, tests/ui/let_underscore_untyped.rs
changelog: [`box_default`], [`let_underscore_untyped`]: Don't suggest unnameable types
=> Don't suggest unnameable types in `box_default`, `let_underscore_untyped`

clippy_lints/src/methods/needless_collect.rs, tests/ui/needless_collect.fixed, tests/ui/needless_collect.rs, tests/ui/needless_collect.stderr
Updates `needless_collect` to also lint `collect` calls in method/function arguments that take an `IntoIterator` (for example `Extend::extend`). Every `Iterator` trivially implements `IntoIterator` and collecting it only causes an unnecessary allocation.
---
changelog: Enhancement: [`needless_collect`]: Now also detects function arguments, taking a generic `IntoIterator` 
[#10777](https://github.com/rust-lang/rust-clippy/pull/10777)
fixes #10762
=> Enhance `needless_collect`: lint in method/function arguments that take an `IntoIterator`

CHANGELOG.md, clippy_lints/src/attrs.rs, clippy_lints/src/declared_lints.rs, tests/ui/non_minimal_cfg.fixed, tests/ui/non_minimal_cfg.rs, tests/ui/non_minimal_cfg.stderr, tests/ui/non_minimal_cfg2.rs, tests/ui/non_minimal_cfg2.stderr
I encountered a few cases where some code had:
```rust
#[cfg(any(unix))]
```
In this case, the `any` is useless. This lint checks this and also for the `all` condition.
```
changelog: [`non_minimal_cfg`]: Add new `non_minimal_cfg` lint
```
=> Add `MINIMAL_CFG_CONDITION` lint

book/src/development/type_checking.md
Updated links to `Adt`, `pat_ty` and `Tykind` in the "Type Checking" chapter of the book. 
- For discussion about the whole project, please use the tracking issue for the project #10597  (It also contains a timeline, discussions, and more information).
changelog: Fix broken links in "Type Checking" chapter of the book
=> Update URLs in Type Checking chapter

clippy_lints/src/matches/match_wild_err_arm.rs, tests/ui/match_wild_err_arm.rs, tests/ui/match_wild_err_arm.stderr
Fixes #10635.
changelog: [`match_wild_err_arm`]: do not lint in const contexts as `Result::{unwrap, expect}` is not const-stable
=> [`match_wild_err_arm`]: do not lint in const contexts

clippy_utils/src/source.rs, tests/ui/single_match.fixed, tests/ui/single_match.rs, tests/ui/single_match.stderr, tests/ui/single_match_else.fixed, tests/ui/single_match_else.rs, tests/ui/single_match_else.stderr
If a block is declared as unsafe, it needs an extra layer of curly braces around it.
Fixes #10808
This code adds handling for `UnsafeSource::UserProvided` block, i.e. `unsafe { ... }`. Note that we do not handle the `UnsafeSource::CompilerGenerated` as it seems to not be possible to generate that with the user code (?), or at least doesn't seem to be needed to be handled explicitly.
There is an issue with this code: it does not add an extra indentation for the unsafe blocks. I think this is a relatively minor concern for such an edge case, and should probably be done by a separate PR (fixing compile bug is more important than getting styling perfect especially when `rustfmt` will fix it anyway)
```rust
// original code
unsafe {
...
}
// code that is now generated by this PR
{ unsafe {
... …
```
=> Fix missing block for unsafe code

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/lib.rs, clippy_lints/src/needless_else.rs, tests/ui-toml/ifs_same_cond/ifs_same_cond.rs, tests/ui/branches_sharing_code/valid_if_blocks.rs, tests/ui/branches_sharing_code/valid_if_blocks.stderr, tests/ui/crashes/ice-7410.rs, tests/ui/ifs_same_cond.rs, tests/ui/needless_else.fixed, tests/ui/needless_else.rs, tests/ui/needless_else.stderr, tests/ui/needless_return.fixed, tests/ui/needless_return.rs, tests/ui/needless_return.stderr, tests/ui/redundant_pattern_matching_drop_order.fixed, tests/ui/redundant_pattern_matching_drop_order.rs, tests/ui/suspicious_else_formatting.rs
Empty `else` clauses are useless. They happen in the wild and are not linted yet: https://github.com/uutils/coreutils/pull/4880/files
`else` clauses containing or preceded by comments are not linted as the comments might be important.
changelog: [`needless_else`]: new lint
=> needless_else: new lint to check for empty `else` clauses

CHANGELOG.md, clippy_lints/src/casts/mod.rs, clippy_lints/src/casts/ptr_cast_constness.rs, clippy_lints/src/declared_lints.rs, clippy_utils/src/msrvs.rs, tests/ui/ptr_cast_constness.fixed, tests/ui/ptr_cast_constness.rs, tests/ui/ptr_cast_constness.stderr
This adds a new lint which functions as the opposite side of the coin to `ptr_as_ptr`. Rather than linting only as casts that don't change constness, this lints only constness; suggesting to use `pointer::cast_const` or `pointer::cast_mut` instead.
changelog: new lint [`ptr_cast_constness`]
=> Add new lint `ptr_cast_constness`

clippy_lints/src/returns.rs, tests/ui/needless_return.stderr
Fixes #10816
Makes it a multipart suggestion so it can be displayed in a single frame which also fixes https://github.com/rust-lang/rust-clippy/issues/10816#issuecomment-1559784868
changelog: [`needless_return`]: Display the suggested change
=> Display the `needless_return` suggestion

clippy_dev/src/main.rs
This PR adds a little bit of validation to `cargo dev new_lint`. I've had it happen a few times where I wanted to add a new lint, but forgot that lint names cannot contain `-`. If you try to do it anyway, `clippy_dev` will generate illegal syntax (like adding `mod test-lint;` to clippy_lints/src/lib.rs for the module declaration). Maybe having it error out early would be helpful to others too.
=> validate lint name in `clippy_dev`

clippy_lints/src/unused_async.rs, tests/ui/unused_async.rs, tests/ui/unused_async.stderr
Fixes #10800.
This PR makes sure that `await` expressions inside of inner `async` blocks don't prevent the lint from triggering.
For example
```rs
async fn foo() {
async {
std::future::ready(()).await;
}
}
```
Even though there *is* a `.await` expression in this function, it's contained in an async block, which means that the enclosing function doesn't need to be `async` too.
changelog: [`unused_async`]: do not consider `await` in nested `async` blocks as used
=> [`unused_async`]: do not consider `await` in nested `async` blocks as used

clippy_lints/src/matches/mod.rs, clippy_lints/src/matches/redundant_pattern_match.rs, tests/ui/redundant_pattern_matching_option.fixed, tests/ui/redundant_pattern_matching_option.rs, tests/ui/redundant_pattern_matching_option.stderr, tests/ui/redundant_pattern_matching_result.fixed, tests/ui/redundant_pattern_matching_result.rs, tests/ui/redundant_pattern_matching_result.stderr
This PR solve this issue https://github.com/rust-lang/rust-clippy/issues/10803
r? @flip1995 
=> Fix redundant_pattern_match on matches! macro

clippy_lints/src/needless_else.rs, tests/ui/needless_else.fixed, tests/ui/needless_else.rs, tests/ui/needless_else.stderr
changelog: none (same release as #10810)
`#[cfg]` making things fun once more
This lead me to think about macro calls that expand to nothing as well, but apparently they produce an empty stmt in the AST so are already handled, added a test for that
r? @llogiq
=> Ignore `#[cfg]`'d out code in `needless_else`

clippy_lints/src/manual_let_else.rs, tests/ui/manual_let_else.rs, tests/ui/manual_let_else.stderr, tests/ui/manual_let_else_match.rs, tests/ui/manual_let_else_match.stderr
* Address a formatting issue pointed out in https://github.com/rust-lang/rust-clippy/pull/10175/files#r1137091002
* Replace variables inside | patterns in the if let: `let v = if let V::A(v) | V::B(v) = v { v } else ...`
* Support nested patterns: `let v = if let Ok(Ok(Ok(v))) = v { v } else ...`
* Support tuple structs with more than one arg: `let v = V::W(v, _) = v { v } else ...`; note that more than one *capture* is still not supported, so it bails for `let (v, w) = if let E::F(vi, wi) = x { (vi, wi)}`
* Correctly handle .. in tuple struct patterns: `let v = V::X(v, ..) = v { v } else ...`
- \[ ] Followed [lint naming conventions][lint_naming]
- \[ ] Executed `cargo dev update_lints` …
=> Improve pattern printing for manual_let_else

clippy_lints/src/regex.rs, tests/ui/regex.rs, tests/ui/regex.stderr
Fixing false positive and false negative when dealing with regex that could match invalid UTF8.
This PR fixes https://github.com/rust-lang/rust-clippy/issues/10825
changelog: [`invalid_regex`]: Fixing false positive and false negative when dealing with regex that could match invalid UTF8
=> Fixing `invalid_regex` with invalid UTF8. Also, adding more test cases

Cargo.toml, clippy_lints/Cargo.toml
Cargo now have it's own workspace and rustc dropped [`rustc-workspace-hack`](https://github.com/rust-lang/rust/pull/109133), so no need to unify features here; drop rustc-workspace-hack.
=> deps: drop serde feature from url, drop rustc-workspace-hack

clippy_lints/src/wildcard_imports.rs, tests/ui/auxiliary/wildcard_imports_helper.rs, tests/ui/wildcard_imports.fixed, tests/ui/wildcard_imports.rs, tests/ui/wildcard_imports.stderr
This commit fixes #10846 by checking if the path segment contains the word "prelude", allowing us 
`use module_prelude::*`.
changelog: [`wildcard_imports`]: Modules that contain `prelude` are also allowed
=> [`wildcard_imports`] Modules that contain `prelude` are also allowed

clippy_lints/src/booleans.rs, tests/ui/nonminimal_bool.rs, tests/ui/nonminimal_bool.stderr
fix issue https://github.com/rust-lang/rust-clippy/issues/10836
changelog: Fix [`nonminimal_bool`] false positive when `!!x`, `x` isn't boolean and implements `Not`
=> nonminimal_bool fix double not

.github/ISSUE_TEMPLATE/new_lint.yml
Picking a name/category is something the implementers/reviewers tend to cover anyway, I think asking people to come up with it at the time of their suggestion is more of a barrier than it's worth
Inspired by the mention in #10849
=> Remove lint name and category fields from the new lint issue form

book/src/configuration.md, book/src/development/adding_lints.md, clippy_lints/src/utils/conf.rs
Fixes https://github.com/rust-lang/rust-clippy/issues/9921.
Adds information on where to place the configuration files, it may be a bit verbose. Also added a comment to the section of the code where the search happens, to hopefully prevent changing that without updating the docs.
changelog: Make documentation about where to place configuration files clearer.
=> Explain which paths clippy searches for configuration in docs

CHANGELOG.md, clippy_lints/src/attrs.rs, clippy_lints/src/declared_lints.rs, tests/ui/cfg_features.rs, tests/ui/cfg_features.stderr
changelog: [`maybe_misused_cfg`]: check if `#[cfg(feature = "...")]` misused as `#[cfg(features = "...")]`
I've found that there is no indication when `#[cfg(features = "...")]` is used incorrectly, which can easily make mistakes hard to spot. When I searched for this code on github, I also found many misuse cases([link](https://github.com/search?q=%23%5Bcfg%28features+language%3ARust&type=code)).
PS: This clippy name is just a temporary name, it can be replaced with a better name.
=> add checking for cfg(features = ...)

CHANGELOG.md
Roses are red,
the new version was released,
and our changelog too
---
=> Update *Current stable* text in `CHANGELOG.md`

clippy_lints/src/casts/mod.rs, clippy_lints/src/casts/unnecessary_cast.rs, tests/ui/as_ptr_cast_mut.rs, tests/ui/as_ptr_cast_mut.stderr, tests/ui/cast_slice_different_sizes.rs, tests/ui/crashes/ice-1782.rs, tests/ui/from_raw_with_void_ptr.rs, tests/ui/from_raw_with_void_ptr.stderr, tests/ui/transmute_ptr_to_ref.fixed, tests/ui/transmute_ptr_to_ref.rs, tests/ui/unnecessary_cast.fixed, tests/ui/unnecessary_cast.rs, tests/ui/unnecessary_cast.stderr
Supersedes(?) #10782, since this and #10567 will cover the original issue.
Does not lint on type aliases or inferred types.
changelog: [`unnecessary_cast`]: Also emit on casts between raw pointers with the same type and constness
=> Emit `unnecessary_cast` on raw pointers as well

util/gh-pages/index.html, util/gh-pages/script.js
This fixes #8510 by storing Clippy Lints page filter configuration in the URL parameters.
This includes:
- Lint levels
- Lint groups
- Version filters
"Filter" was already present in the URL and its behavior is retained. There is existing support for passing a `sel` query parameter; this is also retained, but I am not sure if it used in the wild.
The URL parameters only get included if they are modified after loading the page.
I have these changes available here in case people want to play with it: https://whee.github.io/rust-clippy/master/
An example with levels, groups, and versions set (oddly):
https://whee.github.io/rust-clippy/master/#/?groups=pedantic,perf&levels=allow,warn&versions=gte:53,lte:57,eq:54
Adding a filter:
https://whee.github.io/rust-clippy/master/#/manual_str_repeat?gro …
=> Use URL parameters for filter states

clippy_lints/src/casts/ptr_cast_constness.rs, tests/ui/ptr_cast_constness.fixed, tests/ui/ptr_cast_constness.rs, tests/ui/ptr_cast_constness.stderr
fixes #10874
changelog: [`ptr_cast_constness`]: Only lint on casts which don't change type
=> [`ptr_cast_constness`]: Only lint on casts which don't change type

clippy_lints/src/manual_let_else.rs, tests/ui/manual_let_else.rs, tests/ui/manual_let_else.stderr, tests/ui/manual_let_else_match.rs, tests/ui/manual_let_else_match.stderr
This adds upon the improvements of #10797 and:
* Only prints `()` around `Or` patterns at the top level (fixing a regression of #10797)
* Supports multi-binding patterns: `let (u, v) = if let (Some(u_i), Ok(v_i)) = ex { (u_i, v_i) } else ...`
* Traverses through tuple patterns: `let v = if let (Some(v), None) = ex { v } else ...`
* Supports struct patterns: `let v = if let S { v, w, } = ex { (v, w) } else ...`
```
changelog: [`manual_let_else`]: improve pattern printing to support struct patterns
```
fixes #10708
fixes #10424
=> manual_let_else: support struct patterns

clippy_lints/src/useless_conversion.rs, tests/ui/useless_conversion.stderr
context: https://github.com/rust-lang/rust-clippy/pull/10814#issuecomment-1575036086
changelog: [`useless_conversion`]: pluralize if there are multiple `.into_iter()` calls in the chain
r? @llogiq
=> [`useless_conversion`]: pluralize if there are multiple `.into_iter()` calls

clippy_lints/src/dereference.rs, tests/ui/explicit_deref_methods.fixed, tests/ui/explicit_deref_methods.rs, tests/ui/explicit_deref_methods.stderr
fixes #10850
changelog: [`explicit_deref_methods`]: Fix malformed suggestion on `Foo::deref(&foo)`
=> Fix suggestion on fully qualified syntax

clippy_lints/src/allow_attributes.rs, clippy_lints/src/attrs.rs, clippy_utils/src/check_proc_macro.rs, tests/ui/allow_attributes.fixed, tests/ui/allow_attributes.rs, tests/ui/allow_attributes.stderr, tests/ui/allow_attributes_false_positive.rs, tests/ui/allow_attributes_without_reason.rs, tests/ui/allow_attributes_without_reason.stderr
I use `lint_reasons` and `clap`, which is a bit overzealous when it comes to preventing warnings in its macros; it uses a ton of allow attributes on everything to, as ironic as it is, silence warnings. These two now ignore anything from procedural macros.
PS, I think `allow_attributes.rs` should be merged with `attrs.rs` in the future.
fixes #10377 
changelog: [`allow_attributes`, `allow_attributes_without_reason`]: Ignore attributes from procedural macros
=> [`allow_attributes`, `allow_attributes_without_reason`]: Ignore attributes from procedural macros

.github/workflows/clippy.yml, .github/workflows/clippy_bors.yml, .github/workflows/clippy_dev.yml
Sparse registry is the default so we don't need these anymore
=> Remove `CARGO_UNSTABLE_SPARSE_REGISTRY` env from ci

clippy_lints/src/redundant_clone.rs, tests/ui/redundant_clone.fixed, tests/ui/redundant_clone.rs, tests/ui/redundant_clone.stderr, tests/ui/unnecessary_to_owned.fixed, tests/ui/unnecessary_to_owned.rs
changelog: [`redundant_clone`]: Move to `nursery`
A bunch of FPs in `redundant_clone` have sprung up after upstream MIR changes: https://github.com/rust-lang/rust/pull/108944
- https://github.com/rust-lang/rust-clippy/issues/10870
- https://github.com/rust-lang/rust-clippy/issues/10577
- https://github.com/rust-lang/rust-clippy/issues/10545
- https://github.com/rust-lang/rust-clippy/issues/10517
r? @flip1995
=> Move `redundant_clone` to `nursery`

tests/headers.rs, tests/ui/crashes/ice-10645.rs, tests/ui/crashes/ice-10645.stderr, tests/ui/crashes/ice-4968.rs, tests/ui/expect_tool_lint_rfc_2383.rs, tests/ui/expect_tool_lint_rfc_2383.stderr
Follow up to #10669, we're pretty used to them so they're easy to slip through
=> Add a test that checks for old style test headers

clippy_utils/src/eager_or_lazy.rs, tests/ui/unnecessary_lazy_eval.fixed, tests/ui/unnecessary_lazy_eval.rs, tests/ui/unnecessary_lazy_eval.stderr
Fixes #10437.
This PR changes clippy's util module `eager_or_lazy` to also consider deref expressions whose type has a non-builtin deref impl and not suggest replacing it as that might have observable side effects.
A prominent example might be the `lazy_static` macro, which creates a newtype with a `Deref` impl that you need to go through to get access to the inner value. Going from lazy to eager can make a difference there.
changelog: [`unnecessary_lazy_eval`]: don't lint on types with non-builtin deref impl
=> [`unnecessary_lazy_eval`]: don't lint on types with deref impl

clippy_lints/src/returns.rs
Fixes https://github.com/rust-lang/rust-clippy/issues/4182.
I don't think conforming to this lint could trigger the issue immediately, only if subsequent code-changes go wrong, but I may be mistaken. 
Since the lint can't trigger it by itself, just closing this issue might be reasonable, if not maybe this PR fixes it.
changelog: Update docs for `let_and_return`, mention rust-lang #37612
=> Bring up Rust lang #37612 as a known problem for let_and_return

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/lib.rs, clippy_lints/src/redundant_type_annotations.rs, tests/ui/redundant_type_annotations.rs, tests/ui/redundant_type_annotations.stderr
Hello, I'm trying to add the `redundat_type_annotations` lint.
It's still WIP but I'd like to start gathering some feedbacks to be sure that I'm not doing things 100% wrong :)
Right now it still misses lints like:
I've some problems regarding the second example above, in the `init` part of the `Local` I have:
```rust
init: Some(
Expr {
hir_id: HirId(DefId(0:24 ~ playground[e1bd]::main).58),
kind: Call(
Expr {
hir_id: HirId(DefId(0:24 ~ playground[e1bd]::main).59),
kind: Path(
TypeRelative(
Ty {
hir_id: HirId(DefId(0:24 ~ playground[e1bd]::main).61),
kind: Path(
Resolved(
None,
Path {
span: src/main.rs:77:21: 77:27 (#0),
res: Def(
Struct,
DefId(0:17 ~ playground[e1bd]::STest2),
),
segments: [
PathSegment {
ident: STest2#0,
hir_id: HirId(DefId(0:24 ~ playground[e1bd]::main).60),
res: Def( …
```
=> Add redundant type annotations lint

clippy_lints/src/casts/cast_possible_wrap.rs, clippy_lints/src/casts/mod.rs, tests/ui/cast.rs, tests/ui/cast.stderr
These changes make `cast_possible_wrap` aware of the different pointer widths and fixes the implementation to print the correct pointer widths.
Fixes #9337 
changelog: `cast_possible_wrap` does not lint on `u8 as isize` or `usize as i8`, since these can never wrap.
`cast_possible_wrap` now properly considers 16 bit pointer size and prints the correct bit widths.
=> make cast_possible_wrap work correctly for 16 bit {u,i}size

clippy_lints/src/let_with_type_underscore.rs, tests/ui/let_with_type_underscore.rs, tests/ui/let_with_type_underscore.stderr
closes #10498
changelog: [`let_with_type_underscore`]: Don't emit on locals from procedural macros
=> [`let_with_type_underscore`]: Don't emit on locals from procedural macros

clippy_utils/src/eager_or_lazy.rs, tests/ui/unnecessary_lazy_eval.fixed, tests/ui/unnecessary_lazy_eval.rs, tests/ui/unnecessary_lazy_eval.stderr
Fixes #10462
This PR handles autoderef in the `eager_or_lazy` util module and stops suggesting to change lazy to eager if autoderef in an expression goes through user defined `Deref` impls, e.g. 
```rs
struct S;
impl Deref for S {
type Target = ();
fn deref(&self) -> &Self::Target { &() }
}
let _ = Some(()).as_ref().unwrap_or_else(|| &S); // autoderef `&S` -> `&()`
``` 
changelog: [`unnecessary_lazy_evaluations`]: don't suggest changing lazy evaluation to eager if autoderef goes through user-defined `Deref`
r? @xFrednet  (because of the earlier review in #10864, might help for context here)
=> consider autoderef through user-defined `Deref` in `eager_or_lazy`

clippy_lints/src/missing_fields_in_debug.rs
Fixes #10887
This PR fixes an ICE that happens when the implementor (self type) of a `Debug` impl is a generic parameter.
The lint calls `TyCtxt::type_of` with that self type, which ICEs when called with generic parameters, so this just adds a quick check before getting there to ignore them.
That can only happen inside of core itself (afaik) because the orphan rules forbid defining an impl such as `impl<T> Debug for T` outside of core, so I'm not sure how to add a test for this.
It seems like this impl in particular caused this: https://doc.rust-lang.org/stable/std/fmt/trait.Debug.html#impl-Debug-for-F
changelog: [`missing_fields_in_debug`]: don't ICE on blanket `Debug` impl in core
=> [`missing_fields_in_debug`]: don't ICE when self type is a generic param

clippy_lints/src/formatting.rs, tests/ui/suspicious_else_formatting.rs
This PR fixes https://github.com/rust-lang/rust-clippy/issues/10273
The idea is that if the only thing after `else` and before `{` is a comment, we will not warn because, probably, the line break was "made" by rustfmt.
changelog: [`suspicious_else_formatting`]: Don't warn if the only thing between `else` and curly bracket is a comment
=> `suspicious_else_formatting`: Don't warn if there is a comment between else and curly bracket

CHANGELOG.md, clippy_lints/src/arc_with_non_send_sync.rs, clippy_lints/src/declared_lints.rs, clippy_lints/src/lib.rs, tests/ui/arc_with_non_send_sync.rs, tests/ui/arc_with_non_send_sync.stderr
Fixes #653
Adds a new lint to check for uses of non-Send/Sync types within Arc.
```
changelog: [`arc_with_non_send_sync`]: Added a lint to detect uses of non-Send/Sync types within Arc.
```
=> Adds new lint `arc_with_non_send_or_sync`

clippy_lints/src/eta_reduction.rs, tests/ui/eta.fixed, tests/ui/eta.rs, tests/ui/eta.stderr
Fixes #10684.
`x..=y` ranges need a bit of special handling in this lint because it desugars to a call to the lang item `RangeInclusiveNew`, where the callee span would be the same as the range expression itself, so the suggestion looked a bit weird. It now correctly suggests `RangeInclusive::new`.
changelog: [`redundant_closure`]: special case `RangeInclusive`
=> [`redundant_closure`]: special case inclusive ranges

clippy_lints/src/lib.rs, clippy_lints/src/vec.rs, tests/ui/vec.fixed, tests/ui/vec.rs, tests/ui/vec.stderr
Fixes https://github.com/rust-lang/rust/issues/111034
Fixes #2256
changelog: [`useless_vec`]: Fix suggestion in `for _ in vec![..]`
=> Fix `useless_vec` suggestion in `for _ in vec![..]`

clippy_lints/src/casts/unnecessary_cast.rs, tests/ui/unnecessary_cast.fixed, tests/ui/unnecessary_cast.rs, tests/ui/unnecessary_cast.stderr
Spotted this because
https://github.com/rust-lang/rust-clippy/blob/e2c655b4c07c912ef749be316aeea8453cb9d840/tests/ui/suspicious_to_owned.rs#L9-L10
currently fails on `aarch64-unknown-linux-gnu` as `c_char` is `u8` there
The current implementation checks for `as alias`, `as _`. This adds things like
- `as *const alias`
- `as *const cfg_dependant`
- `as *const _`
=> Ignore more pointer types in `unnecessary_cast`

clippy_lints/src/excessive_nesting.rs
=> Fix `excessive_nesting` example

book/src/lint_configuration.md, clippy_lints/src/enum_variants.rs, clippy_lints/src/lib.rs, clippy_lints/src/utils/conf.rs, tests/ui-toml/module_inception/clippy.toml, tests/ui-toml/module_inception/module_inception.rs, tests/ui-toml/module_inception/module_inception.stderr, tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr, tests/ui/module_inception.stderr
Fixes #10842
changelog: Enhancement [`module_inception`]: Added `allow-private-module-inception` configuration.
[#10917](https://github.com/rust-lang/rust-clippy/pull/10917)
=> allow disabling module inception on private modules

clippy_dev/src/main.rs, clippy_dev/src/new_lint.rs
This would be the tooling part of #9311
- `--pass late` is now the default
- It prints a message recommending the use of a late pass if you choose `--pass early`
=> Direct towards late passes in `cargo dev new_lint`

clippy_utils/src/numeric_literal.rs, rustfmt.toml, tests/ui/crashes/ice-10912.rs, tests/ui/crashes/ice-10912.stderr
Fixes #10912 
The numeric literal util module didn't check for exponents with no digits.
So:
https://github.com/rust-lang/rust-clippy/blob/384cf376120f09df7710d2ff39c986144a7b1517/clippy_utils/src/numeric_literal.rs#L163-L168
`exponent` here would be the empty string, which passed the `!= "0"` check (when it shouldn't have, it should probably be treated as if the user wrote `E0`), then later fails when counting the digits and subtracting one (0 - 1 = overflow).
Also, interestingly I can't even write a test for this because exponents with no digits is some kind of error by itself and `cargo dev fmt` fails on it.
changelog: [`unreadable_literal`]: don't (debug) ICE on numeric literal with empty exponent
=> handle exponent without digits in `numeric_literal`

clippy_lints/src/casts/unnecessary_cast.rs, tests/ui/unnecessary_cast.fixed, tests/ui/unnecessary_cast.rs, tests/ui/unnecessary_cast.stderr
Fixes #10555
changelog: [`unnecessary_cast`]: No longer lints cast from locals that are type aliases
=> Ignore more type aliases in unnecessary_cast

clippy_lints/src/trait_bounds.rs, clippy_utils/src/check_proc_macro.rs, tests/ui/type_repetition_in_bounds.rs, tests/ui/type_repetition_in_bounds.stderr
fixes #10504.
changelog: [`type_repetition_in_bounds`]: Don't lint on derived code
=> [`type_repetition_in_bounds`]: Don't lint on derived code

clippy_lints/src/as_conversions.rs, clippy_lints/src/lib.rs, tests/ui/as_conversions.rs, tests/ui/as_conversions.stderr
Don't linting `as_conversions` if code was generated by procedural macro.
This PR fixes https://github.com/rust-lang/rust-clippy/issues/9657
I implemented the fix changing the lint code to be a `LateLintPass` in order to be able to use the `is_from_proc_macro` out of the box. If the reviwer thinks that it would be better to do the other way (implementing `WithSearchPat`) just let me know. I might need some help in implementing it for the `ustc_ast::ast::Expr`
changelog: [`as_conversions`] avoiding warnings in macro-generated code
=> Don't linting `as_conversions` in proc macros

clippy_lints/src/needless_if.rs, tests/ui/needless_if.fixed, tests/ui/needless_if.rs, tests/ui/needless_if.stderr
Also has a basic fall-back for `if` statements that have attributes applied to them and incorporates https://github.com/rust-lang/rust-clippy/pull/10921#pullrequestreview-1474008780 while I was there
=> Don't lint non-statement/faux empty `needless_if`s

clippy_utils/src/lib.rs, clippy_utils/src/qualify_min_const_fn.rs, tests/ui/missing_const_for_fn/cant_be_const.rs, tests/ui/missing_const_for_fn/could_be_const.rs, tests/ui/missing_const_for_fn/could_be_const.stderr
this will check every local for `TerminatorKind::Drop` to ensure they can be evaluated at compile time, not sure if this is the best way to do this but MIR is confusing and it works so...
fixes #10617
changelog: [`missing_const_for_fn`]: Ensure dropped locals are `~const Destruct`
=> [`missing_const_for_fn`]: Ensure dropped locals are `~const Destruct`

clippy_lints/src/lifetimes.rs, tests/ui/crashes/ice-2774.stderr, tests/ui/crashes/needless_lifetimes_impl_trait.stderr, tests/ui/issue_4266.stderr, tests/ui/needless_lifetimes.stderr
Fixes #10093
changelog: [`needless_lifetimes`]: Suggestion now points at the elidable lifetimes, rather than the entire function declaration
=> Improve suggestion for [`needless_lifetimes`]

clippy_lints/src/no_effect.rs, tests/ui/no_effect_return.rs, tests/ui/no_effect_return.stderr
Closes #10941
Unfortunately doesn't catch anything complex as `no_effect` already wouldn't, but I'm fine with that (it catches `ControlFlow` at least :D)
changelog: [`no_effect`]: Suggest adding `return` if statement has same type as function's return type and is the last statement in a block
=> [`no_effect`]: Suggest adding `return` if applicable

clippy_lints/src/methods/option_map_unwrap_or.rs, tests/ui/map_unwrap_or.rs
Fixes #10579.
The previous way of checking if changing `map(f).unwrap_or(a)` to `map_or(a, f)` is safe had a flaw when the argument to `unwrap_or` moves a binding and the `map` closure references that binding in some way.
It used to simply check if any of the identifiers in the `unwrap_or` argument are referenced in the `map` closure, but it didn't consider the case where the moved binding is referred to through references, for example:
```rs
let x = vec![1, 2];
let x_ref = &x;
Some(()).map(|_| x_ref.clone()).unwrap_or(x);
```
This compiles as is, but we cannot change it to `map_or`. This lint however did suggest changing it, because the simple way of checking if `x` is referenced anywhere in the `map` closure fails here. The safest thing to do here imo (what this PR does) is check if the …
=> [`map_unwrap_or`]: don't lint when referenced variable is moved

clippy_lints/src/derivable_impls.rs, tests/ui/derivable_impls.fixed, tests/ui/derivable_impls.rs
Fixes #10158.
This fixes a FP where the derive-generated Default impl would have different behavior because of unsize coercion from `Box<T>` to `Box<dyn Trait>`:
```rs
struct S {
x: Box<dyn std::fmt::Debug>
}
impl Default for S {
fn default() -> Self {
Self {
x: Box::<()>::default()
// ^~ Box<()> coerces to Box<dyn Debug>
// #[derive(Default)] would call Box::<dyn Debug>::default()
}
}
}
```
(this intentionally only looks for trait objects `dyn` specifically, and not any unsize coercion, e.g. `&[i32; 5]` to `&[i32]`, because that breaks existing tests and isn't actually problematic, as far as I can tell)
changelog: [`derivable_impls`]: don't lint if `default()` call expression unsize-coerces to trait object
=> [`derivable_impls`]: don't lint if `default()` call expr unsize-coerces to trait object

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/lib.rs, clippy_lints/src/single_range_in_vec_init.rs, tests/ui/single_element_loop.fixed, tests/ui/single_element_loop.rs, tests/ui/single_element_loop.stderr, tests/ui/single_range_in_vec_init.rs, tests/ui/single_range_in_vec_init.stderr, tests/ui/while_let_on_iterator.fixed, tests/ui/while_let_on_iterator.rs, tests/ui/while_let_on_iterator.stderr
Lints on `vec![0..200]` (or `[0..200]`), suggesting either `(0..200).collect::<Vec<i32>>()` or `[0; 200]`.
Haven't tested it with anything that isn't primitive. Probably should!
Closes #10932
changelog: new lint [`single_range_in_vec_init`]
=> new lint [`single_range_in_vec_init`]

clippy_lints/src/methods/unnecessary_fold.rs, tests/ui/unnecessary_fold.fixed, tests/ui/unnecessary_fold.rs, tests/ui/unnecessary_fold.stderr
Fixes #10000
This adds turbofish `::<T>` to the suggestion in `unnecessary_fold`. This is necessary because the `Sum` trait is generic, which breaks inference when changing `fold()` to `sum()`.
changelog: [`unnecessary_fold`]: suggest turbofish if necessary
=> [`unnecessary_fold`]: suggest turbofish if necessary

clippy_lints/src/from_over_into.rs, tests/ui/from_over_into.fixed, tests/ui/from_over_into.rs, tests/ui/from_over_into.stderr, tests/ui/from_over_into_unfixable.rs
changelog: [`from_over_into`]: Show suggestions when the body contains macros not expanding to `Self`
Currently any path in a macro expansion causes the suggestion to be hidden, meaning most macro calls cause it to be hidden
Now it's only hidden if the expansion contains `Self`
=> from_over_into: Show suggestions for non-Self expanded paths

clippy_lints/src/matches/match_same_arms.rs, clippy_lints/src/matches/mod.rs, tests/ui/match_same_arms_non_exhaustive.rs, tests/ui/match_same_arms_non_exhaustive.stderr
Fixes #10327
changelog: [`match_same_arms`]: Don't lint if `non_exhaustive_omitted_patterns` is `warn` or `deny`
=> [`match_same_arms`]: don't lint if `non_exhaustive_omitted_patterns`

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/methods/drain_collect.rs, clippy_lints/src/methods/mod.rs, tests/ui/drain_collect.fixed, tests/ui/drain_collect.rs, tests/ui/drain_collect.stderr, tests/ui/iter_with_drain.fixed, tests/ui/iter_with_drain.rs
Closes #10818.
This adds a new lint that looks for `.drain(..).collect()` and suggests replacing it with `mem::take`.
changelog: [`drain_collect`]: new lint
=> new lint: `drain_collect`

clippy_lints/src/lib.rs, src/main.rs
changelog: The `--explain` subcommand now exits with the 1 exit code for missing lints
=> Make `--explain` subcommand return 1 for missing lints

clippy_lints/src/casts/unnecessary_cast.rs, tests/ui/auxiliary/extern_fake_libc.rs, tests/ui/unnecessary_cast.fixed, tests/ui/unnecessary_cast.rs, tests/ui/unnecessary_cast.stderr
This is potentially the worst code I've ever written, and even if not, it's very close to being on par with starb. This will ignore `call() as i32` and `local_obtained_from_call as i32` now.
This should fix every reasonable way to reproduce #10555, but likely not entirely.
changelog: Ignore more type aliases in `unnecessary_cast`
=> Ignore more type aliases in `unnecessary_cast`

util/gh-pages/versions.html
Companion PR to #10875
changelog: Remove legacy v0.0.* versions from Clippy repository and documentation. 
Must be merged together with #10875 (best with a closed tree)
r? @Alexendoo (because you were randomly selected on the other PR :P)
=> Adapt versions.html file to cleaned up gh-pages

util/versions.py
I missed updating this file.
I also ran black and isort over it.
Fixes the [deployment failure](https://github.com/rust-lang/rust-clippy/actions/runs/5297071588/jobs/9588599397)
r? @ghost
=> Fix version.py after deleting v* dirs

clippy_lints/src/doc.rs, tests/ui/auxiliary/macro_rules.rs, tests/ui/missing_panics_doc.rs, tests/ui/missing_panics_doc.stderr
closes #10966
changelog: [`missing_panics_doc`] now does not lint for `todo!()`
=> Make [`missing_panics_doc`]  not lint for `todo!()`

CHANGELOG.md, book/src/lint_configuration.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/lib.rs, clippy_lints/src/single_call_fn.rs, clippy_lints/src/utils/conf.rs, tests/ui/single_call_fn.rs, tests/ui/single_call_fn.stderr
Closes #10861
changelog: New lint [`single_call_fn`]
=> new lint [`single_call_fn`]

clippy_utils/src/macros.rs, tests/ui/to_string_in_format_args_incremental.fixed, tests/ui/to_string_in_format_args_incremental.rs, tests/ui/to_string_in_format_args_incremental.stderr
Fixes #10969
[`lower_span`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_ast_lowering/struct.LoweringContext.html#method.lower_span) gives AST spans a [parent](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_span/struct.SpanData.html#structfield.parent) when lowering to the HIR. That meant the `==` span comparison would return false even though the spans are pointing to the same thing. We now ignore the parent when comparing the spans
Debugging this was quite the puzzle, because the parent is not included in the debug output of `Span`s or `SpanData` 😬
=> Fix `find_format_arg_expr` when incremental compilation is enabled

clippy_lints/src/enum_clike.rs, clippy_lints/src/floating_point_arithmetic.rs, clippy_lints/src/matches/overlapping_arms.rs, clippy_lints/src/minmax.rs, clippy_lints/src/operators/float_cmp.rs, clippy_lints/src/ranges.rs, clippy_utils/src/consts.rs, clippy_utils/src/lib.rs, tests/ui/arithmetic_side_effects.rs
Fix #10792 
```
changelog: [`arithmetic_side_effects`]: Retrieve field values of structures that are in constant environments
```
=> [`arithmetic_side_effects`] Fix #10792 

clippy_lints/src/items_after_test_module.rs
The library `test-case` is having some problems with this lint, ignoring proc macros should fix it.
Related to #10713 and frondeus/test-case#122
(Couldn't add test cases for this exact situation without importing the library, but I think the fix is simple enough that we can be pretty sure there won't be any problems :) )
changelog:[`items_after_test_module`]: Ignore items in procedural macros
=> `items_after_test_module`: Ignore in-proc-macros items

clippy_lints/src/redundant_clone.rs, clippy_utils/src/qualify_min_const_fn.rs, tests/ui/missing_const_for_fn/cant_be_const.rs
rust-lang/rust#80647 suggests refactoring certain patterns with MIR places to use higher-level abstractions provided by the [`Place`](https://doc.rust-lang.org/stable/nightly-rustc/rustc_middle/mir/struct.Place.html)/[`PlaceRef`](https://doc.rust-lang.org/stable/nightly-rustc/rustc_middle/mir/struct.PlaceRef.html). While working on that issue, I found a couple candidates for such refactoring in clippy.
=> Use placeref abstraction

book/src/lint_configuration.md, clippy_lints/src/utils/conf.rs
Closes #10998
changelog: [`doc_markdown`]: No longer lints WebAssembly
=> Add WebAssembly to allowed idents

tests/ui/doc/doc-fixable.fixed, tests/ui/doc/doc-fixable.rs, tests/ui/doc/doc-fixable.stderr
=> add WebAssembly to test

clippy_lints/src/casts/borrow_as_ptr.rs, tests/ui/borrow_as_ptr.fixed, tests/ui/borrow_as_ptr.rs, tests/ui/borrow_as_ptr.stderr
Fixes #9884
changelog: [`borrow_as_ptr`]: Ignore temporaries
=> [`borrow_as_ptr`]: Ignore temporaries

clippy_lints/src/methods/iter_nth.rs, clippy_lints/src/methods/iter_nth_zero.rs, tests/ui/iter_nth.stderr, tests/ui/iter_nth_zero.fixed, tests/ui/iter_nth_zero.rs
Closes #9820
This also *slightlyy* modifies the output of `iter_nth`, as I noticed the types' names weren't in backticks
changelog: [`iter_nth_zero`]: No longer lints in implementations of `Iterator::next`
=> Don't lint [`iter_nth_zero`] in `next`

clippy_lints/src/methods/get_unwrap.rs, tests/ui/get_unwrap.fixed, tests/ui/get_unwrap.rs, tests/ui/get_unwrap.stderr
Fixes #9909
I have to say, I don't really understand what the previous logic was trying to do, but this fixes the linked bug.
It was checking if the argument passed to `.get()` can be parsed as a usize (i.e. if it's an integer literal, probably?), and if not, it wouldn't include a borrow? I don't know how we came to that conclusion, but that logic doesn't work:
```rs
let slice = &[1, 2];
let _r: &i32 = slice.get({ 1 }).unwrap();
// previous suggestion: slice[{ 1 }]
// the suggestion should be: &slice[{ 1 }]
```
Here the argument passed to it isn't an integer literal, but it should still include a borrow, because it would otherwise change the type from `&i32` to `i32`.
The exception is that if the parent of the `get().unwrap()` expr is a dereference or a method call or the like, we don't …
=> [`get_unwrap`]: include a borrow in the suggestion if argument is not an integer literal

clippy_lints/src/ptr.rs, tests/ui/ptr_arg.rs, tests/ui/ptr_arg.stderr
Closes #9218
changelog: [`ptr_arg`]: Don't lint when return type uses `Cow`'s lifetime
=> [`ptr_arg`]: Don't lint when return type uses `Cow`'s lifetime

clippy_lints/src/format_push_string.rs, tests/ui/format_push_string.rs, tests/ui/format_push_string.stderr
Closes #9493.
changelog: [`format_push_string`]: look through `match` and `if` expressions
=> [`format_push_string`]: look through `match` and `if` expressions

clippy_lints/src/extra_unused_type_parameters.rs, tests/ui/extra_unused_type_parameters.fixed, tests/ui/extra_unused_type_parameters.rs, tests/ui/extra_unused_type_parameters.stderr
Don't lint `extra_unused_type_parameters` if code was generated by procedural macro.
This PR fixes https://github.com/rust-lang/rust-clippy/issues/11014
changelog: [`extra_unused_type_parameters`] avoid linting macro-generated code
=> Avoid linting `extra_unused_type_parameters` on procedural macros

clippy_lints/src/loops/never_loop.rs, clippy_utils/src/consts.rs, tests/ui/large_futures.rs, tests/ui/large_futures.stderr, tests/ui/never_loop.rs, tests/ui/never_loop.stderr
This fixes the example provided in #11004, but it shouldn't be closed as this is still an issue on like
```rust
let x = true;
if x { /* etc */ }`
```
This also makes `clippy_utils::consts::constant` handle `ConstBlock` and `DropTemps`.
changelog: [`never_loop`]: Check if `if` conditions always evaluate to true
=> Check if `if` conditions always evaluate to true in `never_loop`

CHANGELOG.md, book/src/development/infrastructure/changelog_update.md
Related to #10847
Instead of the non-descriptive commit ranges, now the changelog uses dates (much more illustrative, and cooler :sunglasses: )
changelog:none
=> Update changelog's data ranges

clippy_lints/src/misc_early/mod.rs, tests/ui/patterns.fixed, tests/ui/patterns.rs, tests/ui/patterns.stderr, tests/ui/unneeded_field_pattern.rs, tests/ui/unneeded_field_pattern.stderr, tests/ui/unneeded_wildcard_pattern.fixed, tests/ui/unneeded_wildcard_pattern.rs, tests/ui/unneeded_wildcard_pattern.stderr
Fixes #11008
changelog: [`unneeded_field_pattern`], [`redundant_pattern`], [`uneeded_wildcard_pattern`], [`double_neg`], [`separated_literal_suffix`], [`unseparated_literal_suffix`], [`mixed_case_hex_literals`], [`zero_prefixed_literal`]: Don't lint code from external macros
(wow, that's one hell of a changelog for such a small change...)
=> Don't lint code from external macros for 8 lints

book/src/development/adding_lints.md, clippy_test_deps/Cargo.toml, tests/compile-test.rs
Allows passing the environment variable `BLESS` to bless tests, which is useful when you want to bless internal tests - `BLESS= cargo uitest -Finternal`
Also updates a place in the docs referring to `cargo dev bless` and removes some unused test deps
=> Add `BLESS` for compile-test and some cleanup

tests/compile-test.rs
Restores the previous behaviour of matching using a substring match rather than needing a full match
=> Use substring matching for TESTNAME

clippy_lints/src/unused_async.rs, clippy_utils/src/lib.rs, tests/ui/unused_async.rs, tests/ui/unused_async.stderr
Fixes #10459.
We shouldn't lint if the function is part of a trait, because the user won't be able to easily remove the `async`, as this will then not match with the function signature in the trait definition
changelog: [`unused_async`]: don't lint if function is part of a trait
=> [`unused_async`]: don't lint if function is part of a trait

clippy_lints/src/option_if_let_else.rs, tests/ui/option_if_let_else.fixed, tests/ui/option_if_let_else.rs, tests/ui/option_if_let_else.stderr
Fixes #10729
`Option::map_or` takes ownership, so if matching on an `&Option<_>`, we need to suggest `.as_ref()` before calling `map_or` to get the same effect and to not cause a borrowck error. 
changelog: [`option_if_let_else`]: suggest `.as_ref()`/`.as_mut()` if scrutinee is of type `&Option<_>`/`&mut Option<_>`
=> [`option_if_let_else`]: suggest `.as_ref()` if scrutinee is of type `&Option<_>`

clippy_lints/src/lib.rs, clippy_lints/src/question_mark.rs, tests/ui/question_mark.fixed, tests/ui/question_mark.rs, tests/ui/question_mark.stderr
Fixes #8628.
Diff looks a bit noisy because I had to move the two functions into an impl, because they now need to access the structs `try_block_depth` field to see if they're inside a try block.
changelog: [`question_mark`]: don't lint inside of `try` block
=> [`question_mark`]: don't lint inside of `try` block

clippy_lints/src/significant_drop_tightening.rs, tests/ui/significant_drop_tightening.fixed, tests/ui/significant_drop_tightening.rs, tests/ui/significant_drop_tightening.stderr
Fix #10413
This is quite a rewrite that unfortunately took a  large amount of time. I tried my best to comment what is going on to easy review but feel free to ask any question.
The problem basically is that the current algorithm is only taking into consideration single blocks which means that things like the following don't work or show unpredictable results.
```rust
let mutex = Mutex::new(1);
{
let lock = mutex.lock().unwrap();
{
let _ = *lock;
}
}
```
The solve the issue, each path that refers a lock is now being tracked individually.
```
changelog: [`significant_drop_tightening`]: Lift the restriction of only considerate single blocks
```
=> [significant_drop_tightening] Fix #10413

clippy_lints/src/operators/eq_op.rs, tests/ui/eq_op.rs, tests/ui/eq_op.stderr
changelog: Enhancement: [`eq_op`]: Suggests `is_nan()` for `x != x` where `x` is a float
=> Make `eq_op` suggest `.is_nan()`

.github/workflows/clippy.yml, .github/workflows/clippy_bors.yml
I noticed that we run a `cargo build` but end up downloading/building a bunch of deps after that for tests in CI
https://github.com/rust-lang/rust-clippy/actions/runs/5426673277/jobs/9869019973#step:6:12
https://github.com/rust-lang/rust-clippy/actions/runs/5426673277/jobs/9869019973#step:7:11
This builds the tests in the build step too, it may speed up runs by downloading/building more in parallel
=> Use `cargo build --tests` in CI

clippy_lints/src/returns.rs, tests/ui/let_and_return.rs, tests/ui/let_and_return.stderr
Fixes #11056
Now also ignores functions returning `'static` lifetimes, since I noticed the `stdin.lock()` example was still being linted but doesn't need to be since https://github.com/rust-lang/rust/pull/93965
=> `let_and_return`: lint 'static lifetimes, don't lint borrows in closures

book/src/development/speedtest.md, tests/compile-test.rs
In the `master` branch, we currently don't have any way to test the performance of a single lint in changes.
This PR adds `SPEEDTEST`, the environment variable which lets you do a speed test on a lint / category of tests with various configuration options.
Maybe we should merge this with `lintcheck` :thinking: 
See the book page for more information.
changelog:none
=> Add `SPEEDTEST`

clippy_lints/src/missing_fields_in_debug.rs
Fixes #11063, another ICE that can only happen in core.
This lint needs the `DefId` of the implementor to get its fields, but that ICEs if the implementor does not have a `DefId` (as is the case with primitive types, e.g. `impl Debug for bool`), which is where this ICE comes from.
This PR changes the check I added in #10897 to be more... robust against `Debug` implementations we don't want to lint.
Instead of just checking if the self type is a type parameter and "special casing" one specific case we don't want to lint, we should probably rather just check that the self type is either a struct, an enum or a union and only then continue.
That prevents weird edge cases like this one that can only happen in core.
Again, I don't know if it's even possible to add a test case for this since one …
=> [`missing_fields_in_debug`]: make sure self type is an adt

clippy_lints/src/arc_with_non_send_sync.rs, tests/ui/arc_with_non_send_sync.rs, tests/ui/arc_with_non_send_sync.stderr
Fixes #11076
changelog: [`arc_with_non_send_sync`]: don't lint if type has nested type parameters
=> [`arc_with_non_send_sync`]: don't lint if type has nested type parameters

clippy_lints/src/vec.rs, tests/ui/vec.fixed, tests/ui/vec.rs, tests/ui/vec.stderr
Fixes #11075.
changelog: [`useless_vec`]: use the source span for the initializer expression when inside of a macro
=> [`useless_vec`]: use the source span for initializer

clippy_lints/src/lib.rs, clippy_lints/src/manual_let_else.rs, clippy_lints/src/manual_rem_euclid.rs, clippy_lints/src/question_mark.rs, clippy_utils/src/lib.rs, tests/ui/manual_let_else_question_mark.fixed, tests/ui/manual_let_else_question_mark.rs, tests/ui/manual_let_else_question_mark.stderr
Don't lint `manual_let_else` where the question mark operator `?` would be sufficient, that is, mostly in cases like:
```Rust
let v = if let Some(v) = ex { v } else { return None };
```
Also, this PR emits the `question_mark` lint for `let...else` patterns that could be written with `?` (also, only `return None` like cases).
```
changelog: [`manual_let_else`]: don't lint in cases where question_mark already lints
changelog: [`question_mark`]: lint for `let Some(...) = ex else { return None };`
```
Fixes  #8755
=> Don't lint manual_let_else in cases where ? would work

clippy_lints/src/vec.rs, tests/ui/vec.fixed, tests/ui/vec.rs, tests/ui/vec.stderr
Closes #11084.
I realized that the fix I added in #11081 itself also causes an error in a suggestion when inside of a macro. Example:
```rs
macro_rules! x {
() => {
for _ in vec![1, 2] {}
}
}
x!();
```
Here it would suggest replacing `vec![1, 2]` with `[x!()]`, because that's what the source callsite is (reminder: it does this to get the correct span of `x!()` for code like `for _ in vec![x!()]`), but that's wrong when *inside* macros, so I decided to make it not lint if the whole loop construct is inside a macro to avoid this issue.
changelog: [`useless_vec`]: add more tests and don't lint inside of macros
r? @Alexendoo since these were your tests, I figured it makes most sense to assign you
=> [`useless_vec`]: add more tests and don't lint inside of macros

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/methods/mod.rs, clippy_lints/src/methods/read_line_without_trim.rs, tests/ui/read_line_without_trim.fixed, tests/ui/read_line_without_trim.rs, tests/ui/read_line_without_trim.stderr
This adds a new lint that checks for calls to `Stdin::read_line` with a reference to a string that is then attempted to parse into an integer type without first trimming it, which is always going to fail at runtime.
This is something that I've seen happen a lot to beginners, because it's easy to run into when following the example of chapter 2 in the book where it shows how to program a guessing game.
It would be nice if we could point beginners to clippy and tell them "let's see what clippy has to say" and have clippy explain to them why it fails 👀 
I think this lint can later be "generalized" to work not just for `Stdin` but also any `BufRead` (which seems to be where the guarantee about the trailing newline comes from) and also, matching/comparing it to a string slice that doesn't end …
=> new lint: `read_line_without_trim`

clippy_lints/src/arc_with_non_send_sync.rs, tests/ui/arc_with_non_send_sync.rs, tests/ui/arc_with_non_send_sync.stderr
Fixes #11079
changelog: [`arc_with_non_send_sync`]: move to complexity
=> `arc_with_non_send_sync`: reword and move to `suspicious`

clippy_lints/src/incorrect_impls.rs
`Copy<T>` does in fact not exist. The substs on the trait_ref contain the `Self` type of the impl as the first parameter, so passing that to `implements_trait`, which then nicely prepends the `Self` type for us does not end will.
fixes  #11121
The assertions requires debug assertions inside rustc, which is probably why it didn't fire here. I tested the change locally in rust-lang/rust and it did not ICE anymore.
cc @xFrednet @Centri3 
changelog: [`incorrect_impls`]: fix confusion about generic parameters
=> Pass correct substs to `implements_trait` in `incorrect_impls`

CHANGELOG.md, book/src/development/infrastructure/changelog_update.md, util/fetch_prs_between.sh
`fetch_prs_between.sh` now finds the date of the newest and oldest merges from GitHub to use in the range, this does add a dependency on https://github.com/cli/cli
It also no longer prints rollups/merges that come from rustc, so only clippy changes should be printed
r? @xFrednet
cc #10847
=> Fix changelog PR listings, create them automatically in `fetch_prs_between.sh`

clippy_lints/src/significant_drop_tightening.rs, clippy_utils/src/paths.rs, tests/ui/significant_drop_tightening.fixed, tests/ui/significant_drop_tightening.rs, tests/ui/significant_drop_tightening.stderr
Fix #11128
```
changelog: [`significant_drop_tightening`]: Consider manual aliases of the `drop` function.
```
=> [significant_drop_tightening] Fix #11128

clippy_lints/src/dereference.rs, clippy_utils/src/mir/mod.rs, tests/ui/needless_borrow.fixed, tests/ui/needless_borrow.rs
Fixes #10535
r? @Jarcho
changelog: Eliminate ICE described in #10535
=> Fix ICE in #10535

clippy_lints/src/methods/unnecessary_literal_unwrap.rs, tests/ui/unnecessary_literal_unwrap.fixed, tests/ui/unnecessary_literal_unwrap.rs
Fixes https://github.com/rust-lang/rust-clippy/discussions/11109
changelog: [`unnecessary_literal_unwrap`]: don't lint if binding initializer comes from expansion
=> [`unnecessary_literal_unwrap`]: don't lint if binding initializer comes from expansion

clippy_lints/src/needless_pass_by_ref_mut.rs
Someone nicely showed me that I made a small typo in https://github.com/rust-lang/rust-clippy/pull/10900.
=> Fix typo in `needless_pass_by_ref_mut` lint description

clippy_lints/src/methods/filter_next.rs, tests/ui/methods_unfixable.rs, tests/ui/methods_unfixable.stderr
Fixes #10029
changelog: [`filter_next`]: suggest making binding mutable if it needs to be and adjust applicability
=> [`filter_next`]: suggest making binding mutable if it needs to be

clippy_lints/src/methods/mod.rs, clippy_lints/src/methods/unnecessary_literal_unwrap.rs, tests/ui/unnecessary_literal_unwrap.fixed, tests/ui/unnecessary_literal_unwrap.rs, tests/ui/unnecessary_literal_unwrap.stderr
Closes #11093
changelog: [`unnecessary_literal_unwrap`]: also lint `unwrap_unchecked` and `unwrap_err_unchecked`
=> [`unnecessary_literal_unwrap`]: also lint `unwrap_(err_)unchecked`

CHANGELOG.md, clippy_lints/src/items_after_test_module.rs, clippy_lints/src/loops/mod.rs, clippy_lints/src/needless_bool.rs
Roses are red,
new format is tried,
it's way less of a fight
---
Hey @rust-lang/clippy, @blyxyas, and @Centri3, I've tried the "new"/minimal changelog format we discussed a few meetings ago. I like it, and the writing process was also way quicker.
[:framed_picture: Rendered :framed_picture:](https://github.com/xFrednet/rust-clippy/blob/changelog-1-71/CHANGELOG.md#rust-171)
Furthermore, a big thank you to @blyxyas and @Alexendoo for updating the script that fetches the PR commits and adding links to the config values to the changelog. :heart: 
---
=> Changelog for Rust 1.71 :crown:

clippy_lints/src/panic_in_result_fn.rs, tests/ui/panic_in_result_fn.stderr, tests/ui/panic_in_result_fn_assertions.stderr
This commit fixes #11025 by removing checks for `todo!`, `unimplemented!` and `unreachable!`.
changelog: [`panic_in_result_fn`] remove `todo!`, `unimplemented!`, `unreachable!`
=> [`panic_in_result_fn`] remove `todo!`, `unimplemented!`, `unreachable!`

clippy_lints/src/dereference.rs
While this PR doesn't fix the issue in #11142, it at least communicates that this is a known limitation.
r? @Jarcho
changelog: Add "Known problems" section to `needless_borrow` documentation
=> Add "Known problems" section to `needless_borrow` documentation

clippy_lints/src/tuple_array_conversions.rs
The lint suggestion is arguably often less readable and more complex than the original code.
For example, which of the following is the most readable:
```rust
let _vertices = edges.flat_map(|(src, dst)| [src, dst]);
let _vertices = edges.flat_map(<_ as Into<[i32; 2]>>::into);
let _vertices = edges.flat_map(<[i32; 2]>::from);
```
The lint can be useful, but really only applies if the tuple is either long enough that naming the fields is silly (maybe at least 4 entries long), or if the author intends the fields to be homogenous, which is author intent and can't be determined by the lint. Therefore I think the lint should be marked as pedantic.
Currently, there are also a lot of false positives with the lint:
* https://github.com/rust-lang/rust-clippy/issues/11082
* …
=> [`tuple_array_conversions`]: move from `complexity` to `nursery`

clippy_lints/src/operators/arithmetic_side_effects.rs, tests/ui/arithmetic_side_effects.rs
Fixes #11145
This lint has a list of allowed types, one of which is `Wrapping<T>`, but it was only actually allowed if the type on the right hand side was also `Wrapping<T>`, which meant that, for example, `Wrapping<u32> += u32` would still lint. It now allows binary ops involving `Wrapping<T>` regardless of the type on the rhs.
These impls have only existed since Rust 1.60.0, so that is probably why the lint was previously not handling this correctly
changelog: [`arithmetic_side_effect`]: allow different types on the right hand side for `Wrapping<T>` (e.g. `Wrapping<T> += T`)
=> [`arithmetic_side_effect`]: allow different types on the right hand side for `Wrapping<T>`

src/driver.rs
This is a fix for https://github.com/rust-lang/rust-clippy/issues/9928#issuecomment-1634698183, any time `CLIPPY_CONF_DIR` changes cargo will now rebuild the crate clippy is being run on, giving it a chance to lint with the (potentially) different config file
r? @flip1995
=> Trigger a rebuild when `CLIPPY_CONF_DIR` changes

clippy_lints/src/casts/unnecessary_cast.rs, tests/ui/unnecessary_cast_unfixable.rs, tests/ui/unnecessary_cast_unfixable.stderr
=> Set `unnecessary_cast` suggestion to `MaybeIncorrect` for pointer casts

clippy_dev/src/new_lint.rs
Running `cargo dev new_lint --type methods` creates the lint file with hidden lifetimes for the `LateContext` parameter (i.e. `&LateContext`, when it should be `&LateContext<'_>`). This is already warned on with `#![warn(rust_2018_idioms)]`, so clippy should not use hidden lifetimes
=> don't hide lifetimes for `LateContext`

src/driver.rs, tests/ui-internal/custom_ice_message.stderr
The previous URL linked to the blank new issue from without any template. This will now link to the ICE template :)
* Before: https://github.com/rust-lang/rust-clippy/issues/new
* After: https://github.com/rust-lang/rust-clippy/issues/new?template=ice.yml
That's it, nothing too interesting besides that. For everyone reading this: here, have some free cream :ice_cream: :icecream: and have a beautiful day. :upside_down_face: 
=> Update bug URL to use the ice template

clippy_lints/src/semicolon_if_nothing_returned.rs, tests/ui/semicolon_if_nothing_returned.fixed, tests/ui/semicolon_if_nothing_returned.stderr
changelog: [`semicolon_if_nothing_returned`]: add an autofix
=> [`semicolon_if_nothing_returned`]: add an autofix

clippy_lints/src/tuple_array_conversions.rs
changelog: Move [`tuple_array_conversions`] to `nursery` (Now allow-by-default)
[#11172](https://github.com/rust-lang/rust-clippy/pull/11172)
The nursery change got lost in #11146 and it ended up in pedantic, this puts it in nursery and gives something to backport
r? @xFrednet
=> Move tuple_array_conversions to nursery

clippy_lints/src/returns.rs, tests/ui/let_and_return.rs
=> Don't lint `needless_return` in fns across a macro boundary

clippy_lints/src/tuple_array_conversions.rs, tests/ui/tuple_array_conversions.rs, tests/ui/tuple_array_conversions.stderr
Fixes #11100
Fixes #11144
Fixes #11124
#11082 still needs discussion and #11085 likely can't be fixed.
changelog: [`tuple_array_conversions`]: Move to `pedantic`
changelog: [`tuple_array_conversions`]: Don't lint if mutability of references changes
changelog: [`tuple_array_conversions`]: Don't lint if bindings don't come from the exact same pattern
changelog: [`tuple_array_conversions`]: Don't lint if bindings are used for more than just the conversion
=> Rewrite [`tuple_array_conversions`]

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/four_forward_slashes.rs, clippy_lints/src/lib.rs, tests/ui/four_forward_slashes.fixed, tests/ui/four_forward_slashes.rs, tests/ui/four_forward_slashes.stderr, tests/ui/four_forward_slashes_first_line.fixed, tests/ui/four_forward_slashes_first_line.rs, tests/ui/four_forward_slashes_first_line.stderr
Closes #9212
changelog: New lint [`four_forward_slashes`]
=> New lint [`four_forward_slashes`]

clippy_lints/src/matches/redundant_pattern_match.rs, tests/ui/redundant_pattern_matching_option.fixed, tests/ui/redundant_pattern_matching_option.rs, tests/ui/redundant_pattern_matching_option.stderr
Fixes #11174
changelog: [`redundant_pattern_matching`]: include guard in suggestion
=> [`redundant_pattern_matching`]: include guard in suggestion

CHANGELOG.md, clippy_lints/src/casts/unnecessary_cast.rs, clippy_lints/src/declared_lints.rs, clippy_lints/src/methods/iter_skip_zero.rs, clippy_lints/src/methods/mod.rs, tests/ui/iter_skip_zero.fixed, tests/ui/iter_skip_zero.rs, tests/ui/iter_skip_zero.stderr
Idea came from my contribution to `unnecessary_cast` recently. Sorry about that :sweat_smile:
Could be an issue if somebody manually implements `skip`, but I don't think anybody will (and this would be an issue with other lints too, afaik)
changelog: New lint [`iter_skip_zero`]
=> New lint [`iter_skip_zero`]

clippy_dev/src/new_lint.rs, tests/ui-cargo/cargo_common_metadata/fail/src/main.rs, tests/ui-cargo/cargo_common_metadata/fail_publish/src/main.rs, tests/ui-cargo/cargo_common_metadata/fail_publish_true/src/main.rs, tests/ui-cargo/cargo_common_metadata/pass/src/main.rs, tests/ui-cargo/cargo_common_metadata/pass_publish_empty/src/main.rs, tests/ui-cargo/cargo_common_metadata/pass_publish_false/src/main.rs, tests/ui-cargo/feature_name/fail/src/main.rs, tests/ui-cargo/feature_name/pass/src/main.rs, tests/ui-cargo/module_style/fail_mod_remap/src/main.rs, tests/ui-cargo/multiple_crate_versions/5041_allow_dev_build/src/main.rs, tests/ui-cargo/multiple_crate_versions/fail/src/main.rs, tests/ui-cargo/multiple_crate_versions/pass/src/main.rs, tests/ui-cargo/wildcard_dependencies/fail/src/main.rs, tests/ui-cargo/wildcard_dependencies/pass/src/main.rs
Also removes some unused flags from `ui-cargo` tests because the entrypoint is now the `Cargo.toml`, not the `.rs` files
=> Remove `#![allow(unused)]` and `--crate-name` from `cargo dev new_lint` generated tests

clippy_lints/src/methods/filter_map.rs, clippy_utils/src/higher.rs, tests/ui/manual_filter_map.fixed, tests/ui/manual_filter_map.rs, tests/ui/manual_filter_map.stderr, tests/ui/manual_find_map.stderr
Fixes #8010
Previously this lint only worked specifically for a very limited set of methods on the filter call (`.filter(|opt| opt.is_some())` and `.filter(|res| res.is_ok())`). This PR extends it to also recognize `matches!` in the `filter` and pattern matching with `if let` or `match` in the `map`.
Example:
```rs
enum Enum {
A(i32),
B,
}
let _ = [Enum::A(123), Enum::B].into_iter()
.filter(|x| matches!(x, Enum::A(_)))
.map(|x| if let Enum::A(s) = x { s } else { unreachable!() });
```
Now suggests:
```diff
-  .filter(|x| matches!(x, Enum::A(_))).map(if let Enum::A(s) = x { s } else { unreachable!() })
+  .filter_map(|x| match x { Enum::A(s) => Some(s), _ => None })
```
Adding this required a somewhat large change in code because it originally seemed to be specifically written with only …
=> [`manual_filter_map`]: lint on `matches` and pattern matching

clippy_lints/src/significant_drop_tightening.rs, tests/ui/significant_drop_tightening.fixed, tests/ui/significant_drop_tightening.rs, tests/ui/significant_drop_tightening.stderr
Fix #11160
changelog: [`significant_drop_tightening`]: Ignore literals in function returns
=> [significant_drop_tightening] Fix #11160

triagebot.toml
And with that you will now be picked automatically by rustbot to review pull requests.
Welcome to the team!
Thank you for making Clippy better!
r? @xFrednet 
changelog: New team members @Centri3 and @blyxyas
=> Add Centri3 and blyxyas to the reviewer rotation

clippy_lints/src/casts/mod.rs, clippy_lints/src/casts/unnecessary_cast.rs, tests/ui/unnecessary_cast.fixed, tests/ui/unnecessary_cast.rs, tests/ui/unnecessary_cast.stderr
Noticed this doesn't pick up `::std::primitive::u32` or the sort, now it does
=> Check for fully qualified paths in `unnecessary_cast`

clippy_lints/src/methods/unnecessary_literal_unwrap.rs, tests/ui/unnecessary_literal_unwrap.fixed, tests/ui/unnecessary_literal_unwrap.rs, tests/ui/unnecessary_literal_unwrap.stderr, tests/ui/unnecessary_literal_unwrap_unfixable.rs, tests/ui/unnecessary_literal_unwrap_unfixable.stderr
Fixes #11099 
Fixes #11064 
I'm running into #11099 (cc @y21) on my Rust codebase. Clippy ICEs on this code when evaluating the `unnecessary_literal_unwrap` lint:
```rust
fn main() {
let val1: u8 = None.unwrap_or_default();
}
```
This fixes that ICE and adds an message specifically for that case:
```
error: used `unwrap_or_default()` on `None` value
--> $DIR/unnecessary_literal_unwrap.rs:26:5
|
LL |     None::<String>.unwrap_or_default();
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove the `None` and `unwrap_or_default()`: `String::default()`
```
This PR also fixes the same ICE with `None.unwrap_or_else` (by giving the generic error message for the lint in that case).
changelog: Fix ICE in `unnecessary_literal_unwrap` on `None.unwrap_or_default()`
=> [`unnecessary_literal_unwrap`]: Fix ICE on None.unwrap_or_default()

clippy_lints/src/incorrect_impls.rs, clippy_utils/src/paths.rs, tests/ui/incorrect_partial_ord_impl_on_ord_type.fixed, tests/ui/incorrect_partial_ord_impl_on_ord_type.rs, tests/ui/incorrect_partial_ord_impl_on_ord_type.stderr, tests/ui/incorrect_partial_ord_impl_on_ord_type_fully_qual.rs, tests/ui/incorrect_partial_ord_impl_on_ord_type_fully_qual.stderr
Fixes #11178
Also no longer checks if the method name is *just* cmp, but the path. That was an oversight on my part ^^
r? @xFrednet
(and @blyxyas too!)
changelog: [`incorrect_partial_ord_impl_on_ord_type`]: Now allows non-method calls to `cmp` like `Self::cmp(self, other)`
=> Allow `Self::cmp(self, other)` as a correct impl

clippy_lints/src/inherent_to_string.rs, tests/ui/inherent_to_string.rs, tests/ui/inherent_to_string.stderr
Fixes #11201
changelog: [`inherent_to_string`]: No longer lints `unsafe` or `extern` fns
=> [`inherent_to_string`]: Don't lint `unsafe` or `extern` fns

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/lib.rs, clippy_lints/src/redundant_locals.rs, tests/ui/option_if_let_else.fixed, tests/ui/option_if_let_else.rs, tests/ui/option_if_let_else.stderr, tests/ui/redundant_locals.rs, tests/ui/redundant_locals.stderr, tests/ui/shadow.rs, tests/ui/swap.fixed, tests/ui/swap.rs, tests/ui/swap.stderr
This lint checks for code like the following:
```rs
let x = 1;
let x = x;
```
It checks (afaik) all cases where a binding is shadowed by its own value in the same block, including function parameters. This has no effect and is almost certainly accidental, so it's in the `correctness` category like `self_assignment`.
This also lays the groundwork for a more generalized version of #5102.  
changelog: new lint: [`redundant_local`]
=> new lint: `redundant_locals`

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/loops/utils.rs, clippy_lints/src/matches/mod.rs, clippy_lints/src/matches/redundant_guards.rs, tests/ui/match_expr_like_matches_macro.fixed, tests/ui/match_expr_like_matches_macro.rs, tests/ui/match_expr_like_matches_macro.stderr, tests/ui/redundant_guards.fixed, tests/ui/redundant_guards.rs, tests/ui/redundant_guards.stderr, tests/ui/shadow.rs, tests/ui/shadow.stderr, tests/ui/single_match.fixed, tests/ui/single_match.rs, tests/ui/single_match.stderr
Closes #7825, maybe somebody else can get the ranges lint in the comments?
changelog: New lint [`redundant_guards`]
=> new lint [`redundant_guards`]

clippy_lints/src/significant_drop_tightening.rs, tests/ui/significant_drop_tightening.fixed, tests/ui/significant_drop_tightening.rs, tests/ui/significant_drop_tightening.stderr
Fix #11189
```
changelog: FP: [`significant_drop_tightening`]: Consider tuples in drop calls
```
=> [significant_drop_tightening] Fix #11189

clippy_lints/src/lib.rs, clippy_lints/src/unused_async.rs, tests/ui/unused_async.rs, tests/ui/unused_async.stderr
Fixes #9695
Fixes #9359
Clippy shouldn't lint unused `async` if there are paths referencing them if that path isn't the receiver of a function call, because that means that the function might be passed to some other function:
```rs
async fn f() {} // No await statements, so unused at this point
fn requires_fn_future<F: Future<Output = ()>>(_: fn() -> F) {}
requires_fn_future(f); // `f`'s asyncness is actually not unused.
```
(This isn't limited to just passing the function as a parameter to another function, it could also first be stored in a variable and later passed to another function as an argument)
This requires delaying the linting until post-crate and collecting path references to local async functions along the way.
changelog: [`unused_async`]: don't lint if paths reference async …
=> [`unused_async`]: don't lint if paths reference async fn without immediate call

clippy_lints/src/len_zero.rs, clippy_utils/src/higher.rs, tests/ui/comparison_to_empty.fixed, tests/ui/comparison_to_empty.rs, tests/ui/comparison_to_empty.stderr
This adds `LetChain` to `clippy_utils::higher`, other lints may benefit from such a change as well :D
changelog: Enhancement: [`comparison_to_empty`]: Now lints on `if let`
=> Make `comparison_to_empty` work on `if let`/`let` chains

clippy_lints/src/needless_pass_by_ref_mut.rs, tests/ui/needless_pass_by_ref_mut.rs, tests/ui/needless_pass_by_ref_mut.stderr
Fixes https://github.com/rust-lang/rust-clippy/issues/11179.
The problem with async is that "internals" are actually inside a closure from the `ExprUseVisitor` point of view, meaning we need to actually run the check on the closures' body as well.
r? @llogiq
=> Fix async functions handling for `needless_pass_by_ref_mut` lint

clippy_lints/src/dereference.rs, clippy_utils/src/lib.rs
I've seen a few lints that need to be able to tell if changing the type of an expression would be a vaild suggestion. This extracts part of how that's done from `explicit_auto_deref`.
=> Refactor some of  `dereference.rs` to util functions

clippy_utils/src/hir_utils.rs, tests/ui/if_same_then_else.rs, tests/ui/if_same_then_else.stderr
Fixes #11213
changelog: [`if_same_then_else`]: don't lint for integer literals of different types
=> check that the types are equal in `SpanlessEq::eq_expr`

clippy_lints/src/ptr.rs, tests/ui/ptr_arg.rs
Fixes: #11181
changelog: [`ptr_arg`]: ignore extern functions that are not  
I am not sure whether we should ignore other Rust calling conventions like `rust-intrinsic`, `rust-call` or `rust-cold`.
=> ptr_arg should ignore extern functions

clippy_lints/src/min_ident_chars.rs, tests/ui/min_ident_chars.rs
Fixes: #11163 
changelog: [`min_ident_chars`]: don't lint const generics
=> changelog: [`min_ident_chars`]: don't lint const generics

clippy_lints/src/needless_pass_by_ref_mut.rs, tests/ui/infinite_loop.stderr, tests/ui/let_underscore_future.stderr, tests/ui/mut_key.stderr, tests/ui/mut_reference.stderr, tests/ui/needless_pass_by_ref_mut.rs, tests/ui/needless_pass_by_ref_mut.stderr, tests/ui/should_impl_trait/method_list_2.stderr
Fixes #11182 and also fixes #11199 (though this is kind of a duplicate)
There's likely a case or two I've missed, so this likely needs a bit more work but it seems to work fine with the tests I've added.
PS, the diff for the test is useless because it iterates over a hashmap before linting. Seems to work fine but we could maybe change this for consistency's sake
changelog: [`needless_pass_by_ref_mut`]: No longer lints if the function is passed as a fn-like argument
=> [`needless_pass_by_ref_mut`]: Do not lint if passed as a fn-like argument

clippy_lints/src/utils/mod.rs, tests/compile-test.rs
Disables the github specific output for now since it can be a bit confusing - https://github.com/oli-obk/ui_test/issues/109, in particular the truncation/repetition
r? @flip1995
=> Remove Gha status emitter in compile-test

clippy_lints/src/needless_pass_by_ref_mut.rs, clippy_utils/src/lib.rs, tests/ui/needless_pass_by_ref_mut.rs, tests/ui/needless_pass_by_ref_mut.stderr
Fixes https://github.com/rust-lang/rust-clippy/issues/11185.
cc @Centri3 
changelog: Emit note if function is behind a cfg for `NEEDLESS_PASS_BY_REF_MUT` lint.
=> Needless ref mut cfg

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/methods/filter_map_bool_then.rs, clippy_lints/src/methods/mod.rs, clippy_utils/src/paths.rs, tests/ui/filter_map_bool_then.fixed, tests/ui/filter_map_bool_then.rs, tests/ui/filter_map_bool_then.stderr
Closes #9098
changelog: New lint [`filter_map_bool_then`]
=> New lint [`filter_map_bool_then`]

clippy_lints/src/arc_with_non_send_sync.rs, tests/ui/arc_with_non_send_sync.rs, tests/ui/arc_with_non_send_sync.stderr
Fixes #11232
changelog: [`arc_with_non_send_sync`]: No longer lints macro-generated code
=> [`arc_with_non_send_sync`]: No longer lints macro-generated code

triagebot.toml
I just found out that `@rustbot` can automatically add a note about our *no-merge commits* policy, if it detects a merge commit: https://forge.rust-lang.org/triagebot/no-merge.html
Funnly enough, I found this while writing documentation for Marker. `@rustbot` is a cool tool :+1: 
---
r? @flip1995 since you'll probably be the person that will see this message the most ^^
=> Add *no merge policy* note via rustbot

.github/workflows/clippy_bors.yml, tests/integration.rs
fix integration tests.
It turned out that the following tests fail to build at all:
chalk, combine, stdarch and hyper.
This is often a problem of passing `--all-targets --all-features`, in case of combine though, outdated deps were to blame.
I have opened tickets against combine and rustfmt
https://github.com/rust-lang/rustfmt/issues/5859
https://github.com/Marwes/combine/issues/357
should we just remove the other failing repos? :/
changelog: fix integration tests on ci
=> Fix integration tests #2

.github/workflows/clippy_bors.yml, tests/integration.rs
should be merged after https://github.com/rust-lang/rust-clippy/pull/11225 
changelog: add test for integration tests
=> test that we correctly detect panics in intergation tests

clippy_lints/src/option_env_unwrap.rs, tests/ui/option_env_unwrap.rs, tests/ui/option_env_unwrap.stderr
Fixes #10742
changelog: Fix false negative where `option_env_unwrap` wouldn't warn if the env variable isn't set at compile-time.
=> Now `option_env_unwrap` warns even if a variable isn't set at compiletime

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/methods/mod.rs, clippy_lints/src/methods/readonly_write_lock.rs, tests/ui/readonly_write_lock.rs, tests/ui/readonly_write_lock.stderr
Closes #8555
A new lint that catches `RwLock::write` calls to acquire a write lock only to read from it and not actually do any writes (mutations).
changelog: new lint: [`readonly_write_lock`]
=> new lint: [`readonly_write_lock`]

clippy_lints/src/derive.rs, clippy_lints/src/eta_reduction.rs, clippy_lints/src/incorrect_impls.rs, clippy_lints/src/loops/explicit_iter_loop.rs, clippy_lints/src/methods/or_fun_call.rs, clippy_lints/src/needless_pass_by_value.rs, clippy_utils/src/ty.rs, clippy_utils/src/usage.rs, clippy_utils/src/visitors.rs, tests/ui/eta.fixed, tests/ui/eta.rs, tests/ui/eta.stderr
fixes #8548
A good chunk of the code is fixing false negatives. The old code banned any non late-bound regions from appearing in the callee's signature. The new version checks when the late-bound region is actually required.
changelog: Better track when a early-bound region appears when a late-bound region is required in `redundant_closure`.
changelog: Don't lint `redundant_closure` when the closure gives explicit types.
=> `redundant_closure` fixes

clippy_utils/src/ty/type_certainty/mod.rs, tests/ui/unwrap_or_else_default.fixed, tests/ui/unwrap_or_else_default.rs, tests/ui/unwrap_or_else_default.stderr
Fixes #11256
changelog: `unwrap_or_default`: Fix ICE when local types are declared using alias types
=> Resolve type aliases in `type_certainty`

clippy_lints/src/methods/unnecessary_filter_map.rs, tests/ui/unnecessary_filter_map.rs, tests/ui/unnecessary_filter_map.stderr, tests/ui/unnecessary_find_map.rs, tests/ui/unnecessary_find_map.stderr
Closes #11260
changelog: [`unnecessary_find_map`]: lint `.then_some()` in closure
=> [`unnecessary_find_map`]: look for then_some

clippy_lints/src/operators/arithmetic_side_effects.rs, tests/ui/arithmetic_side_effects.rs
Fix #11262
Rustc already handles paths that refer literals -> https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d795058a2e1634c867288c20ff9432c8
```
changelog: [`arithmetic_side_effects`]: Ignore paths that refer literals
```
=> [`arithmetic_side_effects`] Fix #11262

clippy_lints/src/mut_reference.rs, tests/ui/mut_reference.rs, tests/ui/mut_reference.stderr
Fixes #11268
changelog: [`unnecessary_mut_passed`]: don't lint in macro expansions
=> [`unnecessary_mut_passed`]: don't lint in macro expansions

clippy_lints/src/question_mark.rs, tests/ui/question_mark.fixed, tests/ui/question_mark.rs, tests/ui/question_mark.stderr
Closes #11283
changelog: [`question_mark`]: Don't lint if `question_mark_used` is not allowed
=> Suppress `question_mark` warning if `question_mark_used` is not allowed

clippy_lints/src/casts/ptr_as_ptr.rs, tests/ui/ptr_as_ptr.fixed, tests/ui/ptr_as_ptr.rs, tests/ui/ptr_as_ptr.stderr
Fixes #11278
changelog: [`ptr_as_ptr`]: Include leading `super`s in suggestion
=> [`ptr_as_ptr`]: Take snippet instead of pretty printing type

CHANGELOG.md, clippy_dev/src/main.rs, clippy_dev/src/setup/vscode.rs, clippy_lints/src/declared_lints.rs, clippy_lints/src/ignored_unit_patterns.rs, clippy_lints/src/lib.rs, clippy_lints/src/option_if_let_else.rs, tests/ui/ignored_unit_patterns.fixed, tests/ui/ignored_unit_patterns.rs, tests/ui/ignored_unit_patterns.stderr
This idea comes from #11238. I've put the lint in `pedantic` as it might trigger numerous positives (three in Clippy itself).
changelog: [`ignored_unit_patterns`]: new lint
=> New lint `ignored_unit_patterns`

clippy_lints/src/suspicious_xor_used_as_pow.rs, tests/ui/suspicious_xor_used_as_pow.stderr
The original `suspicious_xor_used_as_pow` lint had poor performance, so I fixed that + a little refactor so that module is readable.
**107 millis. -> 106 millis.** Using `SPEEDTEST` on Rust's VMs
fix #11060 
changelog: [`suspicious_xor_used_as_pow`]: Improve performance by 0.934%
=> Fix `suspicious_xor_used_as_pow.rs` performance

clippy_lints/src/redundant_type_annotations.rs, tests/ui/redundant_type_annotations.rs, tests/ui/redundant_type_annotations.stderr
Fixes #11190
Fixes rust-lang/rust#113516
Also adds an `is_lint_allowed` check to skip the lint when it's not needed
=> redundant_type_annotations: only pass certain def kinds to type_of

clippy_lints/src/matches/redundant_guards.rs, tests/ui/redundant_guards.fixed, tests/ui/redundant_guards.rs, tests/ui/redundant_guards.stderr
Fixes #11304
changelog: [`redundant_guards`]: don't lint on float literals
r? @Centri3 i figured you are probably a good reviewer for this since you implemented the lint ^^
=> [`redundant_guards`]: don't lint on float literals

clippy_lints/src/slow_vector_initialization.rs
#11198 extended this lint to also warn on `Vec::new()` + `resize(0, len)`, but did not update the lint documentation, so it left some confused (https://github.com/rust-lang/rust-clippy/issues/10938#issuecomment-1663880083).
This PR should make it a bit more clear. (cc @djc @vi what do you think about this?)
<details>
<summary>More details</summary>
Godbolt for `Vec::new()` + `.resize(x, 0)`: https://godbolt.org/z/e7q9xc9rG
The resize call first does a normal allocation (`__rust_alloc`):
```asm
alloc::raw_vec::finish_grow:
...
cmp     qword ptr [rcx + 8], 0
je      .LBB1_7  ; if capacity == 0 -> LBB1_7
.LBB1_7:
...
call    qword ptr [rip + __rust_alloc@GOTPCREL]
```
*Then* a memset for zero initialization:
```asm
example::f:
...
xor     esi, esi  ; 0
call    qword ptr [rip + …
```
=> [`slow_vector_initialization`]: clarify why `Vec::new()` + resize is worse

clippy_lints/src/redundant_locals.rs, tests/ui/redundant_locals.rs, tests/ui/redundant_locals.stderr
Fixes #11290.
When a mutable binding is shadowed by
a mutable binding of the same name in a different scope, mutations in that scope have different meaning.
This PR fixes spurious `redundant_locals` emissions on such locals.
cc @Centri3, @flip1995 
changelog: [`redundant_locals`]: fix false positives on mutated shadows
=> redundant_locals: fix FPs on mutated shadows

book/src/development/speedtest.md, tests/compile-test.rs
* `--nocapture` hasn't been needed anymore since forever (even before `ui_test`)
* the result was dividing by 1000 instead of the number of test runs, giving bogus (but still useful for the purpose) timing results.
changelog: fix SPEEDTEST instructions and output
=> Fix SPEEDTEST instructions and output

.cargo/config.toml, tests/compile-test.rs
This restores the default behaviour to check the `.stderr`, it was changed in #11239 to bless by default in `cargo test` (unless in github actions), but check by default in `cargo uitest` which is fairly confusing
It also meant `cargo uitest -F internal` no longer worked
`--bless` prevents the use of `Args::test` but we can look at reintegrating with that after @oli-obk's vacation
r? @flip1995
=> Do not bless by default in ui tests

clippy_lints/src/manual_retain.rs, clippy_utils/src/msrvs.rs, clippy_utils/src/paths.rs, tests/ui/manual_retain.fixed, tests/ui/manual_retain.rs, tests/ui/manual_retain.stderr
Closes #9059
This PR adds changes to perform linting on the `binary_heap` as well, under the [manual_retain rule](https://rust-lang.github.io/rust-clippy/master/index.html#/manual_retain).
changelog: [manual_retain]: update for lint `binary_heap`
=> [`manual_retain`]: add lint case for `binary_heap`

clippy_lints/src/methods/iter_overeager_cloned.rs, clippy_lints/src/methods/mod.rs, tests/ui/iter_overeager_cloned.fixed, tests/ui/iter_overeager_cloned.rs, tests/ui/iter_overeager_cloned.stderr
changelog: [`iter_overeager_cloned`]: detect `.cloned().filter()` and `.cloned().find()`
Key idea:
```
// before
iter.cloned().filter(|x| unimplemented!() )
// after
iter.filter(|&x| unimplemented!() ).cloned()
// before
iter.cloned().filter( foo )
// after
// notice `iter` must be `Iterator<Item= &T>` (callee of `cloned()`)
// so the parameter in the closure of `filter` must be `&&T`
// so the deref is safe
iter.filter(|&x| foo(x) ).cloned()
```
=>  [iter_overeager_cloned]: detect `.cloned().filter()` and `.cloned().find()`

clippy_lints/src/methods/implicit_clone.rs, tests/ui/implicit_clone.fixed, tests/ui/implicit_clone.stderr
fixes: #11281 
a small and simple fix that give up checking for `referenced_value.to_owned()` usage.
changelog: allow calling `to_owned` with borrowed value for [`implicit_clone`]
=> allow calling `to_owned` on borrowed value for [`implicit_clone`]

clippy_lints/src/useless_conversion.rs, tests/ui/crashes/ice-11065.rs, tests/ui/useless_conversion.fixed, tests/ui/useless_conversion.rs, tests/ui/useless_conversion.stderr
Fixes #11065 (which is actually two issues: an ICE and a false positive)
It now makes sure that the function call path points to a function-like item (and not e.g. a `const` like in the linked issue), so that calling `TyCtxt::fn_sig` later in the lint does not ICE (fixes https://github.com/rust-lang/rust-clippy/issues/11065#issuecomment-1616836099).
It *also* makes sure that the expression is not part of a macro call (fixes https://github.com/rust-lang/rust-clippy/issues/11065#issuecomment-1616919639). ~~I'm not sure if there's a better way to check this other than to walk the parent expr chain and see if any of them are expansions.~~ (edit: it doesn't do this anymore)
changelog: [`useless_conversion`]: fix ICE when call receiver is a non-fn item
changelog: [`useless_conversion`]: don't …
=> [`useless_conversion`]: only lint on paths to fn items and fix FP in macro

clippy_lints/src/needless_pass_by_ref_mut.rs, tests/ui/needless_pass_by_ref_mut.rs, tests/ui/needless_pass_by_ref_mut.stderr
Fixes https://github.com/rust-lang/rust-clippy/issues/11299.
The problem was that the `async block`s are popping a closure which we didn't go into, making it miss the mutable access to the variables.
cc @Centri3 
=> Correctly handle async blocks for NEEDLESS_PASS_BY_REF_MUT

CONTRIBUTING.md
`box_syntax` no longer exists.
[`clippy_lints/src/lib.rs` now uses `Box::new`](https://github.com/rust-lang/rust-clipp/blob/d5298bea7fd0ce133506d156795e3dc7c68efc20/clippy_lints/src/lib.rs#L809C70-L809C70)
=> Remove use of `box_syntax` in `CONTRIBUTING.md` example

clippy_lints/src/new_without_default.rs, tests/ui/new_without_default.fixed, tests/ui/new_without_default.rs, tests/ui/new_without_default.stderr
Fixes #11267
changelog: [`new_without_default`]: include `where` clause in suggestions
=> [new_without_default]: include `where` clause in suggestions, make applicable

CHANGELOG.md, clippy_lints/src/casts/mod.rs, clippy_lints/src/endian_bytes.rs, clippy_lints/src/excessive_nesting.rs, clippy_lints/src/large_stack_frames.rs, clippy_lints/src/methods/mod.rs, clippy_lints/src/needless_else.rs, clippy_lints/src/redundant_type_annotations.rs
Roses are red,
Marker is alive,
and so are you!
---
cc: https://github.com/rust-lang/rust-clippy/issues/10847#issuecomment-1683927955
---
I've also checked the `beta-nominated` label, the changelog should include everything :)
=> Update version attribute for 1.72 lints

CHANGELOG.md, clippy_lints/src/attrs.rs, clippy_lints/src/declared_lints.rs, clippy_utils/src/paths.rs, tests/ui/should_panic_without_expect.rs, tests/ui/should_panic_without_expect.stderr
Closes #10956
changelog: new lint: [`should_panic_without_expect`]
=> new lint: [`should_panic_without_expect`]

clippy_lints/src/methods/iter_overeager_cloned.rs, clippy_lints/src/methods/mod.rs, tests/ui/iter_overeager_cloned.fixed, tests/ui/iter_overeager_cloned.rs, tests/ui/iter_overeager_cloned.stderr
changelog: [`iter_overeager_cloned`]
key idea:
for `f` in `.map(f)` and `.for_each(f)`:
1. `f` must be closure
2. don't lint if mutable paramter in clsure `f`: `|mut x| ...`
3. don't lint if parameter is moved
4. maybe incorrect
=> [iter_overeager_cloned]: detect .cloned().map() and .cloned().for_each()

clippy_lints/src/tuple_array_conversions.rs, tests/ui/tuple_array_conversions.rs, tests/ui/tuple_array_conversions.stderr
```
changelog: ICE: [`tuple_array_conversions`]: Don't expect array length to always be usize
```
tl;dr: changed [`Const::eval_target_usize`](https://github.com/rust-lang/rust/blob/master/compiler/rustc_middle/src/ty/consts.rs#L359) to [`Consts::try_eval_target_usize`](https://github.com/rust-lang/rust/blob/master/compiler/rustc_middle/src/ty/consts.rs#L327) to get rid of ICE.
I have encountered a problem with clippy: it caught ICE when working with a codebase that uses a lot of nightly features.
Here's a (stripped) ICE info:
```
error: internal compiler error: /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/compiler/rustc_middle/src/ty/consts.rs:361:32: expected usize, got Const { ty: usize, kind: N/#1 }
thread 'rustc' panicked at …
```
=> Fix tuple_array_conversions lint on nightly

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/lib.rs, clippy_lints/src/reserve_after_initialization.rs, tests/ui/reserve_after_initialization.fixed, tests/ui/reserve_after_initialization.rs, tests/ui/reserve_after_initialization.stderr
Closes https://github.com/rust-lang/rust-clippy/issues/11330.
A new lint that informs the user about a more concise way to create a vector with a known capacity.
Example:
```rust
let mut v: Vec<usize> = vec![];
v.reserve(10);
```
Produces the following help:
```rust
|
2 | /     let mut v: Vec<usize> = vec![];
3 | |     v.reserve(10);
| |__________________^ help: consider using `Vec::with_capacity(space_hint)`: `let v: Vec<usize> = Vec::with_capacity(10);`
|
```
And can be rewritten as:
```rust
let v: Vec<usize> = Vec::with_capacity(10);
```
changelog: new lint [`reserve_after_initialization`]
=> Added new lint: `reserve_after_initialization`

clippy_utils/src/lib.rs, clippy_utils/src/ty.rs, tests/ui/crashes/ice-11337.rs
=> allow trait alias DefIds in `implements_trait_with_env_from_iter`

clippy_lints/src/operators/arithmetic_side_effects.rs, tests/ui/arithmetic_side_effects.rs, tests/ui/arithmetic_side_effects.stderr
Fix #11393
```
changelog: [`arithmetic_side_effects`]: Detect division by zero for `Wrapping` and `Saturating`
```
=> [`arithmetic_side_effects`] Fix #11393

clippy_lints/src/derivable_impls.rs, tests/ui/derivable_impls.fixed, tests/ui/derivable_impls.rs
changelog: [`derivable_impls`]: allow the lint when the trait-impl methods has any attribute.
=> fix "derivable_impls: attributes are ignored"

tests/ui/enum_clike_unportable_variant.rs, tests/ui/enum_clike_unportable_variant.stderr
=> fix the uitest `enum_clike_unportable_variant`

clippy_lints/src/operators/float_cmp.rs, tests/ui/float_cmp.rs, tests/ui/float_cmp.stderr
changelog: [`float_cmp`]: allow float eq comparison when lhs is a custom type that implements PartialEq<f32/f64>
If the lhs of a comparison is not float, it means there is a user implemented PartialEq, and the caller is invoking that custom version of `==`, instead of the default floating point equal comparison. 
People may wrap f32 with a struct (say `MyF32`) and implement its PartialEq that will do the `is_close()` check, so that `MyF32` can be compared with either f32 or `MyF32`.
=> skip float_cmp check if lhs is a custom type

clippy_lints/src/unwrap.rs, clippy_utils/src/usage.rs, tests/ui/checked_unwrap/simple_conditionals.rs, tests/ui/checked_unwrap/simple_conditionals.stderr
Closes #11371 
This turned out to be a little more code than I originally thought, because the lint also makes sure to not lint if the user tries to mutate the option:
```rs
if option.is_some() {
option = None;
option.unwrap(); // don't lint here
}
```
... which means that even if we taught this lint to recognize `.as_mut()`, it would *still* not lint because that would count as a mutation. So we need to allow `.as_mut()` calls but reject other kinds of mutations.
Unfortunately it doesn't look like this is possible with `is_potentially_mutated` (seeing what kind of mutation happened).
This replaces it with a custom little visitor that does basically what it did before, but also allows `.as_mut()`.
changelog: [`unnecessary_unwrap`]: lint on `.as_ref().unwrap()`
=> [`unnecessary_unwrap`]: lint on `.as_ref().unwrap()`

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/methods/iter_out_of_bounds.rs, clippy_lints/src/methods/mod.rs, clippy_utils/src/paths.rs, tests/ui/iter_out_of_bounds.rs, tests/ui/iter_out_of_bounds.stderr, tests/ui/iter_skip_next.fixed, tests/ui/iter_skip_next.rs, tests/ui/iter_skip_next.stderr, tests/ui/iter_skip_next_unfixable.rs, tests/ui/iter_skip_zero.fixed, tests/ui/iter_skip_zero.rs
Closes #11345
The original idea in the linked issue seemed to be just about arrays afaict, but I extended this to catch some other iterator sources such as `iter::once` or `iter::empty`.
I'm not entirely sure if this name makes a lot of sense now that it's not just about arrays anymore (specifically, not sure if you can call `.take(1)` on an `iter::Empty` to be "out of bounds"?).
changelog: [`iter_out_of_bounds`]: new lint
=> new lint: `iter_out_of_bounds`

clippy_lints/src/dereference.rs, tests/ui/explicit_auto_deref.fixed, tests/ui/explicit_auto_deref.rs, tests/ui/explicit_auto_deref.stderr
fixes #11366
changelog: `explicit_auto_deref`: Fix span when linting immediately after `needless_borrow`
=> Fix span when linting `explicit_auto_deref` immediately after `needless_borrow`

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/lib.rs, clippy_lints/src/missing_asserts_for_indexing.rs, tests/ui/missing_asserts_for_indexing.fixed, tests/ui/missing_asserts_for_indexing.rs, tests/ui/missing_asserts_for_indexing.stderr, tests/ui/missing_asserts_for_indexing_unfixable.rs, tests/ui/missing_asserts_for_indexing_unfixable.stderr
Fixes #8296
This lint looks for repeated slice indexing and suggests adding an `assert!` beforehand that helps LLVM elide bounds checks. The lint documentation has an example.
I'm not really sure what category this should be in. It seems like a nice lint for the `perf` category but I suspect this has a pretty high FP rate, so it might have to be a pedantic lint or something.
I'm also not sure about the name. If someone knows a better name for this lint, I'd be fine with changing it.
changelog: new lint [`missing_asserts_for_indexing`]
=> new lint: `missing_asserts_for_indexing`

clippy_lints/src/methods/mod.rs, clippy_lints/src/unit_return_expecting_ord.rs
The [Rust Style Guide](https://doc.rust-lang.org/nightly/style-guide/expressions.html?highlight=vec#array-literals) says that `vec!` should alwys be used with square brackets, not parenthesis. Within the lint documentation, that rule was violated twice.
=> Correctly format `vec!` invocations

Cargo.toml, tests/compile-test.rs
This makes `ui_test` parse `--bless` and allows a follow up change to use `Mode::Error` (instead of `Mode::Yolo`) with `RustfixMode::Everything`
=> Bump ui_test

clippy_lints/src/raw_strings.rs, tests/ui/needless_raw_string.fixed, tests/ui/needless_raw_string.rs, tests/ui/needless_raw_string.stderr, tests/ui/needless_raw_string_hashes.fixed, tests/ui/needless_raw_string_hashes.rs, tests/ui/needless_raw_string_hashes.stderr, tests/ui/write_literal_2.stderr
Should make it slightly easier to see the suggested edit
Before/after for `needless_raw_string_hashes`:
| Before| After |
|--------|--------|
| ![before](https://github.com/rust-lang/rust-clippy/assets/1830331/da52a436-d890-4594-9191-819c1af946c7) | ![after](https://github.com/rust-lang/rust-clippy/assets/1830331/9731d790-8efa-42a2-b2e9-0ec51398f8f3) | 
=> Use multipart suggestions for raw string lints

book/src/SUMMARY.md, book/src/development/writing_tests.md
This PR adds  a new chapter to the book: "Writing tests". The changes have been mainly done from reviews from #9426 and some minor re-writes.
- We still need to check that the `git status`es are correct, as `cargo dev new_lint` changed a lot since 2022.
- Requires #10598: Link to "Emitting Lints" where I flagged with `FIXME:`.
- To talk about the whole project, please use the tracking issue for the project #10597 (It also contains a timeline, discussions and more information)
changelog: Add a new "Writing tests" chapter to the book
r? @flip1995
=> Clippy Book Chapter Updates Reborn: Writing tests

book/src/SUMMARY.md, book/src/development/emitting_lints.md
The PR adds a new chapter to the book: "Emitting lints". This time it changed a lot from the old source file.
- For discussion about  the whole project, please use the tracking issue for the project #10597 (It also contains a timeline, discussions, and more information)
changelog: Add a new "Emitting lints" chapter to the book
r? @flip1995
=> Clippy Book Chapter Updates Reborn: Emitting lints

clippy_utils/src/source.rs, clippy_utils/src/sugg.rs, clippy_utils/src/ty/type_certainty/mod.rs
Thank you for making Clippy better!
We're collecting our changelog from pull request descriptions.
If your PR only includes internal changes, you can just write
`changelog: none`. Otherwise, please write a short comment
explaining your change.
It's also helpful for us that the lint name is put within backticks (`` ` ` ``),
and then encapsulated by square brackets (`[]`), for example:
```
changelog: [`lint_name`]: your change
```
If your PR fixes an issue, you can add `fixes #issue_number` into this
PR description. This way the issue will be automatically closed when
your PR is merged.
- \[x] Added passing UI tests …
=> fix some comments

clippy_lints/src/default_union_representation.rs
=> DefaultUnionRepresentation: explain why we only warn about unions with at least 2 non-ZST fields

book/src/SUMMARY.md, book/src/development/trait_checking.md
This PR adds a new chapter to the book: "Trait Checking". No major changes from the source (just some typos, re-phrasing, the usual).
- Does not require any other PR to be merged.
- To talk about the whole project, please use the tracking issue for the project #10597 (It also contains a timeline, discussions and more information)
changelog: Add a new "Trait Checking" chapter to the book
=> Clippy Book Chapter Updates Reborn: Trait Checking

clippy_lints/src/loops/never_loop.rs, tests/ui/never_loop.rs, tests/ui/never_loop.stderr
Fixes #11004. This is a "more principled" rewrite of `never_loop` which does a proper reachability analysis of `continue 'main_loop`.
* Rather than using the `IgnoreUntilEnd(label)` which had an unclear (and ultimately incorrect) relationship to reachability of labels and divergence, local label reachability is now being tracked once per label in the `local_labels` list (previously `ignore_ids`)
* `AlwaysBreak` and `Otherwise` have been renamed to `Diverging` and `Normal` respectively
* The lint now strictly only evaluates subexpressions when the entry point is reachable. This is important because we do not want unreachable subexpressions to return `MayContinueMainLoop` - this was the source of one of the bugs.
The constant check from #11005 was removed, because it is no longer necessary …
=> Rewrite `never_loop` as a strict reachability pass

clippy_lints/src/loops/never_loop.rs, tests/ui/crashes/ice-360.rs, tests/ui/crashes/ice-360.stderr, tests/ui/empty_loop.rs, tests/ui/empty_loop.stderr, tests/ui/iter_out_of_bounds.rs, tests/ui/iter_out_of_bounds.stderr, tests/ui/needless_collect_indirect.rs, tests/ui/needless_collect_indirect.stderr, tests/ui/never_loop.rs, tests/ui/never_loop.stderr, tests/ui/similar_names.rs, tests/ui/similar_names.stderr, tests/ui/vec.fixed, tests/ui/vec.rs, tests/ui/vec.stderr
* Depends on: #11447 
This is an outgrowth of #11447 which I felt would best be done as a separate PR because it yields significant new results.
This uses typecheck results to determine divergence, meaning we can now detect cases like `loop { std::process::abort() }` or `loop { panic!() }`. A downside is that `loop { unimplemented!() }` is also being linted, which is arguably a false positive. I'm not really sure how to check this from HIR though, and it seems best to leave this epicycle for a later PR.
changelog: [`never_loop`]: Now lints on `loop { panic!() }` and similar constructs
=> `never_loop` catches `loop { panic!() }`

clippy_lints/src/implied_bounds_in_impls.rs, tests/ui/crashes/ice-11422.fixed, tests/ui/crashes/ice-11422.rs, tests/ui/crashes/ice-11422.stderr, tests/ui/implied_bounds_in_impls.fixed, tests/ui/implied_bounds_in_impls.rs, tests/ui/implied_bounds_in_impls.stderr
Fixes #11422
This fixes two ICEs ([1](https://github.com/rust-lang/rust-clippy/issues/11422#issue-1872351763), [2](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2901e6febb479d3bd2a74f8a5b8a9305)), and moves it to nursery for now, because this lint needs some improvements in its suggestion (see #11435, for one such example).
changelog: Moved [`implied_bounds_in_impls`] to nursery (Now allow-by-default)
[#11437](https://github.com/rust-lang/rust-clippy/pull/11437)
changelog: [`implied_bounds_in_impls`]: don't ICE on default generic parameter in supertrait clause
r? @xFrednet (since you reviewed my PR that added this lint, I figured it might make sense to have you review this as well since you have seen this code before. If you don't want to review this, sorry! Feel …
=> [`implied_bounds_in_impls`]: don't ICE on default generic parameter and move to nursery

book/src/development/writing_tests.md
Fixes that book `FIXME`.
r? @flip1995
=> Should be final writing_tests commit

clippy_lints/src/dereference.rs, tests/ui/needless_borrow.fixed, tests/ui/needless_borrow.rs
fixes #10253
Also switches to using `implements_trait` which does ICE when clippy's debug assertions are enabled.
=> Don't pass extra generic arguments in `needless_borrow`

clippy_lints/src/loops/never_loop.rs, tests/ui/needless_collect_indirect.rs, tests/ui/needless_collect_indirect.stderr, tests/ui/never_loop.rs, tests/ui/never_loop.stderr, tests/ui/vec.fixed, tests/ui/vec.rs, tests/ui/vec.stderr
As promised in #11450, here is an implementation which skips occurrences of the `todo!()` macro.
changelog: [`never_loop`]: skip loops containing `todo!()`
=> skip `todo!()` in  `never_loop`

clippy_lints/src/undocumented_unsafe_blocks.rs, tests/ui-toml/undocumented_unsafe_blocks/undocumented_unsafe_blocks.rs
fixes: #11246
changelog: fix detection on global variables for [`undocumented_unsafe_blocks`]
=> fix fp when [`undocumented_unsafe_blocks`] not able to detect comment on globally defined const/static variables

clippy_lints/src/ignored_unit_patterns.rs, tests/ui/ignored_unit_patterns.fixed, tests/ui/ignored_unit_patterns.rs, tests/ui/ignored_unit_patterns.stderr
=> Ignore wildcards in function arguments and local bindings

clippy_lints/src/disallowed_macros.rs, tests/ui-toml/disallowed_macros/auxiliary/macros.rs, tests/ui-toml/disallowed_macros/clippy.toml, tests/ui-toml/disallowed_macros/disallowed_macros.rs, tests/ui-toml/disallowed_macros/disallowed_macros.stderr
=> Check binary operators and attributes in disallowed_macros

clippy_lints/src/slow_vector_initialization.rs, tests/ui/slow_vector_initialization.rs, tests/ui/slow_vector_initialization.stderr
Fixes #11408
<details>
<summary>Also fixes a FP when the vec initializer comes from a macro other than `vec![]`</summary>
```rs
macro_rules! x {
() => { vec![] }
}
fn f() {
let mut v = x!();
v.resize(10, 0);
}
```
This shouldn't warn. The `x!` macro might be doing other things, so just replacing `x!()` with `vec![0; 10]` is not always an option.
</details>
I added some test cases for macro expansions, however I don't think there's a way to write a test for that specific warning that appeared in the linked issue. As far as I understand, that happens when the rust-src rustup component isn't installed (so the stdlib source is unavailable) and the span points to the `vec![]` *expansion*, instead of the `vec![]` that the user wrote.
changelog: [`slow_vector_initialization`]: use the source …
=> [`slow_vector_initialization`]: use the source span of vec![] macro and fix another FP

clippy_lints/src/manual_range_patterns.rs, tests/ui/manual_range_patterns.fixed, tests/ui/manual_range_patterns.rs, tests/ui/manual_range_patterns.stderr
Fixes #11461
Also enables linting when there are 3 or fewer alternatives if one of them is already a range pattern
=> Preserve literals and range kinds in `manual_range_patterns`

clippy_lints/src/std_instead_of_core.rs, tests/ui/std_instead_of_core.fixed, tests/ui/std_instead_of_core.stderr
```
changelog: [`std_instead_of_core`]: add suggestions
```
Fixes #11446
=> Add suggestions for std_instead_of_core

clippy_lints/src/implied_bounds_in_impls.rs, tests/ui/implied_bounds_in_impls.fixed, tests/ui/implied_bounds_in_impls.rs, tests/ui/implied_bounds_in_impls.stderr
Fixes #11435
It now includes associated types from the implied bound that were omitted in the second bound. Example:
```rs
fn f() -> impl Iterator<Item = u8> + ExactSizeIterator> {..}
```
Suggestion before this change:
```diff
- pub fn my_iter() -> impl Iterator<Item = u32> + ExactSizeIterator {
+ pub fn my_iter() -> impl ExactSizeIterator {
```
It didn't include `<Item = u32>` on `ExactSizeIterator`. Now, with this change, it does.
```diff
- pub fn my_iter() -> impl Iterator<Item = u32> + ExactSizeIterator {
+ pub fn my_iter() -> impl ExactSizeIterator<Item = u32> {
```
We also now extend the span to include not just possible `+` ahead of it, but also behind it (an example for this is in the linked issue as well).
**Note:** The overall diff is a bit noisy, because building up the …
=> [`implied_bounds_in_impls`]: include (previously omitted) associated types in suggestion

clippy_lints/src/dereference.rs, tests/ui/explicit_auto_deref.fixed, tests/ui/explicit_auto_deref.rs
changelog: [`explicit_auto_deref`]: do not suggest propose to auto-dereference an union field
Fix #11474
=> Auto deref does not apply on union field

CHANGELOG.md, clippy_lints/src/declared_lints.rs, clippy_lints/src/lib.rs, clippy_lints/src/unnecessary_map_on_constructor.rs, tests/ui/eta.fixed, tests/ui/eta.rs, tests/ui/eta.stderr, tests/ui/manual_map_option.fixed, tests/ui/manual_map_option.rs, tests/ui/manual_map_option.stderr, tests/ui/option_filter_map.fixed, tests/ui/option_filter_map.rs, tests/ui/result_map_unit_fn_unfixable.rs, tests/ui/unnecessary_map_on_constructor.fixed, tests/ui/unnecessary_map_on_constructor.rs, tests/ui/unnecessary_map_on_constructor.stderr
changelog: [`unnecessary_map_on_constructor`]: adds lint for cases in which map is not necessary. `Some(4).map(myfunction)` => `Some(myfunction(4))`
Closes https://github.com/rust-lang/rust-clippy/issues/6472
Note that the case mentioned in the issue `Some(..).and_then(|..| Some(..))` is fixed by a chain of lint changes. This PR completes the last part of that chain.
By `bind_instead_of_map`[lint](https://rust-lang.github.io/rust-clippy/master/index.html#/bind_instead_of_map):
`Some(4).and_then(|x| Some(foo(4)))` => `Some(4).map(|x| foo)`
By `redundant_closure` [lint](https://rust-lang.github.io/rust-clippy/master/index.html#/redundant_closure):
`Some(4).map(|x| foo)` => `Some(4).map(fun)`
Finally by this PR `unnecessary_map_on_constructor`:
`Some(4).map(fun)` => `Some(fun(4))`
I'm not …
=> new unnecessary_map_on_constructor lint

clippy_utils/src/macros.rs
Fixes #11470, covers some cases missed by #10980
Can't have a test yet because of #11126 but it works locally
r? @dswij
=> Ignore span's parents in `collect_ast_format_args`/`find_format_args`

clippy_lints/src/len_zero.rs, tests/ui/len_without_is_empty.rs, tests/ui/len_without_is_empty.stderr
Fixes #11165
When we see an `impl B` and `B` is a type alias to some type `A`, then we need to follow the type alias to look for an `is_empty` method on the aliased type `A`. Before this PR, it'd get the inherent impls of `B`, which there aren't any and so it would warn that there isn't an `is_empty` method even if there was one.
Passing the type alias `DefId` to `TyCtxt::type_of` gives us the aliased `DefId` (or simply return the type itself if it wasn't a type alias) so we can just use that
changelog: [`len_without_is_empty`]: follow type alias to find inherent `is_empty` method
=> [`len_without_is_empty`]: follow type alias to find inherent `is_empty` method

Cargo.toml, tests/compile-test.rs, tests/ui/redundant_field_names.fixed, tests/ui/redundant_field_names.rs, tests/ui/redundant_field_names.stderr
It is the last thing depending on syn 1.0 in clippy
=> Remove `derive_new` test dependency

clippy_lints/src/explicit_write.rs, clippy_lints/src/format.rs, clippy_lints/src/format_args.rs, clippy_lints/src/format_impl.rs, clippy_lints/src/lib.rs, clippy_lints/src/methods/expect_fun_call.rs, clippy_lints/src/utils/format_args_collector.rs, clippy_lints/src/write.rs, clippy_utils/src/macros.rs
=> Return a value from find_format_args instead of using a callback

clippy_lints/src/types/mod.rs, tests/ui/redundant_allocation.rs, tests/ui/vec_box_sized.fixed, tests/ui/vec_box_sized.rs
Fixes #11417
`hir_ty_to_ty` is used in a couple of the `!is_local` lints, which doesn't play nicely inside bodies
=> Ignore closures for some type lints

clippy_lints/src/extra_unused_type_parameters.rs, tests/ui/extra_unused_type_parameters.fixed, tests/ui/extra_unused_type_parameters.rs
Generic parameters can end up being used on the left side of where-bounds if they are not directly bound but instead appear nested in some concrete generic type. Therefore, we should walk the left side of where bounds, but only if the bounded type is *not* a generic param, in which case we still need to ignore the bound.
Fixes #11302 
changelog: [`extra_unused_type_parameters`]: Fix edge case false positive for parameters in where bounds
=> [`extra_unused_type_parameters`]: Fix edge case FP for parameters in where bounds

clippy_lints/src/methods/filter_map_bool_then.rs, tests/ui/filter_map_bool_then.fixed, tests/ui/filter_map_bool_then.rs, tests/ui/filter_map_bool_then.stderr
changelog: [`filter_map_bool_then`]: Fix the incorrect autofix when the `bool` in question is a reference.
fix #11503
=> fix filter_map_bool_then with a bool reference

clippy_lints/src/useless_conversion.rs, tests/ui/useless_conversion.fixed, tests/ui/useless_conversion.rs, tests/ui/useless_conversion.stderr
Fixes #11300.
Before this PR, clippy assumed that if it sees a `f(x.into_iter())` call and the type at that argument position is generic over any `IntoIterator`, then the `.into_iter()` call must be useless because `x` already implements `IntoIterator`, *however* this assumption is not right if the generic parameter has more than just the `IntoIterator` bound (because other traits can be implemented for the IntoIterator target type but not the IntoIterator implementor, as can be seen in the linked issue: `<[i32; 3] as IntoIterator>::IntoIter` satisfies `ExactSizeIterator`, but `[i32; 3]` does not).
So, this PR makes it check that the type parameter only has a single `IntoIterator` bound. It *might* be possible to check if the type of `x` in `f(x.into_iter())` satisfies all the bounds on …
=> [`useless_conversion`]: don't lint if type parameter has unsatisfiable bounds for `.into_iter()` receiver
